### PR TITLE
gives extinguishers to all cyborg modules and fixes a comment

### PR DESCRIPTION
**Pull request by ZWRh3**
## About the PR 
removes the mechanic job comment from the engineer borg as the job has been merged with engineer

gives all cyborgs the cyborg xl extinguisher (only brobocop and medical didnt have it)

## Why's this needed? 
**for brobocop:** mainly so you can use it as a knockoff jetpack in case you get stuck in space

space push is known to strand cyborgs in a way they cant move at all, this requires you to either:
get the jetpack upgrade, have an extinguisher, or straight up get saved by someone else (or extreme nerding like using telesci on yourself).

this doesnt fuck over the balance of the jetpack upgrade as it provides proper space movement rather than being a last ditch effort tool to save yourself when space push strands you in a spot you cant move at all in

**for medical:** same as brobocop and so you can actually put out patients rather than awkwardly automending them until the fire goes out in its own

possibly bad balance implications:
further makes the chemistry module just a worse version of the medical one in most ways
the wonders of chemnerds with access to a 300u chemistry container (NOTE: you cant take chems back out of it in other ways than just spraying it so using it as a storage is near impossible however you can use it for smoke powder bombs)
## Changelog

```changelog
(u)ZWRh3
(*)Brobocop and medical cyborg modules now have a fire extinguisher.
```

### CODE REVIEW

**Comment by ZWRh3** [comment]
fuck forgot to add category labels hold on

**Comment by ZWRh3** [comment]
> fuck forgot to add category labels hold on

**Comment by ZeWaka** [comment]
not to detract from this PR but a handy very cheap borg upgrade (or something, not sure on the right system) would be built-in fire suppressant - like it just shoots out a cloud of fire suppressant from the borg - this would also lessen the need for borgs to have actual fire extinguishers

**Review by Sord213 — CHANGES_REQUESTED** [review]
Give them the /cyborg version so they can't melt it and it's a bit safer.

**Comment by ZWRh3** [comment]
im honestly amazed i managed to fuck that up since i copypasted it

fixed

**Pull request closed without merging**
