### PR TITLE
removes hos xp

### PR DESCRIPTION
**Pull request by nefarious6th**
[removal]

## About the PR 
removes hos xp; opens up hos job rewards to be claimable roundstart
related: https://forum.ss13.co/showthread.php?tid=18104

## Why's this needed? 
the XP mechanic for hos is not as refined as some of the other job roles and has somewhat encouraged the development of unhealthy relationships with the job and its purpose.

### CODE REVIEW

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
I don't want to make the antique as common as the regular one. My plan was to make it roll like a 1/100 chance to be the antique if you selected that option. Otherwise it would give you the regular one.

**Comment by nefarious6th** [comment]
> I don't want to make the antique as common as the regular one. My plan was to make it roll like a 1/100 chance to be the antique if you selected that option. Otherwise it would give you the regular one.

Sounds good, I'll try to get it done tonight

**Comment by nefarious6th** [comment]
this one's good for re-review

**Comment by nefarious6th** [comment]
also if anyone on triage can cert organic this or w/e, would be appreciated

**Comment by nefarious6th** [comment]
@DimWhat can triage re-open closed PRs at all? would rather that than make a new one

**Comment by nefarious6th** [comment]
> Yes it can, I can reopen it if you do plan on working on this more.

Sure thing; thank you. Mostly I just want to ask for a re-review and then see where it goes!

**Pull request closed without merging**
