### PR TITLE
Removes santa's teleport ability

### PR DESCRIPTION
**Pull request by Merlin1230**
[input wanted] [removal]

## About the PR 
Removes santa's teleport ability (still in the code, so an admin could give it)

## Why's this needed? 
There has been a massive self-antag problem with santa's abusing their AA and teleport ability, removing their teleport ability should make it much easier and fun for sec to actually catch santa, as on RP as sec santa usually just teleports away before you even get a chance to talk, which means the best option is to just shoot them on sight. I'm sure the same applies to main as well, but I could be wrong.

## Changelog

```changelog
(u)Merlin1230
(*)Santa has been too naughty this year, so they've lost their ability to teleport.
```

### CODE REVIEW

**Comment by alexeric123** [comment]
This 100% seems more of a situation where ahelping it is the right move, instead of punishing everyone.

**Comment by Merlin1230** [comment]
> This 100% seems more of a situation where ahelping it is the right move, instead of punishing everyone.

Fair, but people have been abusing the teleport ability. I just don't think its fun to be unable to arrest santa and having to resort to killing them since they can just no-RP teleport away, and thats also what they do.

**Comment by Merlin1230** [comment]
Also, I am open to this just being closed, I mostly wanted to get people's opinions on this.

**Comment by ThatFiveGuys** [comment]
Maybe instead just make the teleport ability take longer and have it unable to be done while stunned?

**Comment by Merlin1230** [comment]
> Maybe instead just make the teleport ability take longer and have it unable to be done while stunned?

You know what, I like this idea. I'll probably give it like... a 2-3 second action bar or something

**Comment by Merlin1230** [comment]
im gonna close this, and just open a new PR when I actually get around to coding that action bar

**Pull request closed without merging**
