### PR TITLE
Changes how observers interact with respawns

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BALANCE]
## About the PR 
Makes the following changes to observers:
- Joining as an observer no longer sets DNR.
- Observers can get respawn events alongside regular ghosts, although players who have joined the round normally and died will always be prioritized.
- Observers can once again use the 10 minute respawn timer on RP.

## Why's this needed? 
Observers setting DNR caused issues for admin events occasionally, see also #12789.

## Changelog 

```changelog
(u)LeahTheTech
(*)Joining the round as an observer no longer sets DNR, observers can get respawn events but other ghosts will be prioritized over them. Observers can also once again respawn on RP.
```

### CODE REVIEW

**Comment by Xkeeper0** [comment]
question: if you observe, 10 minute respawn, and then die, are you still in the observer queue or do you go into the dead player queue

**Comment by TobleroneSwordfish** [comment]
I think you'd be in the dead player queue then, since your ghost would be created through `ghostize` and not joining as an observer.

**Comment by TobleroneSwordfish** [comment]
oh also note to self if this gets merged: fix the stuff in secret too

**Comment by pali6** [comment]
I prefer this solution to the same problem that #12789 wants to solve (as I was the nerd to suggest it in adminchat).

**Comment by DisturbHerb** [comment]
dom't forget to fix the popup that warns you about DNR when trying to observe

**Comment by virvatuli-gh** [comment]
Would like to have logging of some kind when it comes to observer respawning if we're going this route.

**Pull request merged**
