### PR TITLE
bandaid on borgs pulling mobs causing a slowdown

### LINKED ISSUE #1126: Borg slowed when dragging someone.
[BUG]

**Describe the bug**
When dragging someone, borg are being slowed as is the normal case with humans. I didn't see anything in the changelog so I assume this is a bug?

**To Reproduce**
1. Be borg
2. Drag person alive or dead
3. Be super slowed
4. Be sad

**Expected behavior**
Being able to drag someone at normal speed.

### PR DESCRIPTION
**Pull request by Tarmunora**
[FIX]
## About the PR 
Fixes slowdown from pulling mobs to not affect silicons (as per old behavior)
I assume the original change was unintentional 

## Why's this needed? 
closes #1126

### CODE REVIEW

**Comment by Tiggersaurus** [comment]
Thank you! Love you buddy.

**Comment by Flaborized** [comment]
Hi, unless another bug came around and changed this behavior recently, borgs having a pull slowdown looks like it was intentional. Change was made in October last year, with a commit message "...cyborgs slowed by pulls, pull slowing occurs when dragging the nuke..." by Infinite_Monkeys (who is no longer on stafff)

Not vouching for or against this PR, I just don't think it's a _bug?_ Unless they recently had no slowdown and then got slowdown

**Comment by mybluecorners** [comment]
my guess is that when i generalized movement code from /human up into /living, it made cyborgs use pull speed - which someone had originally intended for them to do but was broken

**Comment by Tiggersaurus** [comment]
> Hi, unless another bug came around and changed this behavior recently, borgs having a pull slowdown looks like it was intentional. Change was made in October last year, with a commit message "...cyborgs slowed by pulls, pull slowing occurs when dragging the nuke..." by Infinite_Monkeys (who is no longer on stafff)
> 
> Not vouching for or against this PR, I just don't think it's a _bug?_ Unless they recently had no slowdown and then got slowdown

As long as I've been playing they've had no slowdown when pulling people/corpses.

**Comment by Tiggersaurus** [comment]
Taken from the wiki: Can pull anything without being slowed down, including corpses, downed humans, and a crate/locker/container of player mobs not on Help intent. Nuclear bombs are the one exception.

**Comment by mordent-goonstation** [comment]
Appreciate the bandaid fix, would prefer it implemented via a var on `/mob` to determine how much they're affected by pull slowdown (`pull_slowdown_multiplier`?). Default would be `1`, then cyborgs could have it lower (`0` would be the previous, unaffected behavior, and checking for `0` should be done to avoid the looping above).

I don't know what number would feel "right". I wouldn't be against setting it to `0` as a bandaid then adjusting up a little bit as we dial in on a good number. Essentially, I like that cyborgs are better at pulling people around (they lack a "grab" so they're behind in that regard), but I wouldn't be opposed to being affected by the slowdown a little bit to avoid the old "aaand they took the guy into space" scenario.

**Comment by Tarmunora** [comment]
Superseded by #1311

**Pull request closed without merging**
