### PR TITLE
Disarm nerfs the sequel

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
Instead of dramatically changing the mechanics of disarm (#5309), which seemed to be poorly received, lets see if mainly numbers tweaks are taken better:
* disarm stam cost 10 -> 30
* disarm stam damage 20 -> 10 
* Disarm chance scaled down to 50% of current (18.5%) at targets with 200 or more stamina, and linerally scaled to current value (37%) on targets with 100 or less. Disarm chances on blocks is reduced by 80% (multiplicative)
* Disarm targets all held items at once

## Why's this needed? 
Stam costs: Make disarm less spammable as a main action in a brawl

Disarm stamina scaling: Make disarm less useful in a first-strike scenario, as well as less useful against ranged weapons (which typically do not use stamina) - numbers here might want poking

Arm targeting -> hand targeting:
* No other mechanic in this game, afaik, cares about what active hand slot someone *else* is using at any given time, 
* Additionally, there is no feedback that a player has swapped hands or indication of which hand a player has as their active hand at any given time (until they attack/you attempt a disarm)

Together, this makes for a feature that is unintuitive and nigh-impossible to play around, as suddenly your disarm attacks stop working with exactly zero indication that anything in the situation has changed. Letting players target a specific hand for disarms will help alleviate that element, while still leaving inventory management as a way to reduce chance of weapon loss (pocket, bag, move *weapon* to other hand [which would trigger a change in the inhand sprite for the item as well as changing examine text, giving some feedback as to why disarms stop working])

## Changelog

```changelog
(u)Tarmunora
(*)Disarm changes. See minor changes for details. To be reverted by Sat, July 3 for further review
(+)disarm stam cost 10 -> 30
(+)disarm stam damage 20 -> 10 
(+)Disarm chance scaled down to 50% of current (18.5%) at targets with 200 or more stamina, and linerally scaled to current value (37%) on targets with 100 or less. Disarm chances on blocks is reduced by 80% (multiplicative)
(+)Disarm targets all held items at once
```

### CODE REVIEW

**Comment by RGBDeadSilent** [comment]
Stamina cost of disarm going up and the stamina damage done going down would be good. It would make disarm more of a last resort thing. You also might not get into a situation where two people permastun you by just pushing you into a corner for eternity.

I think the disarm chance at full stamina is fine, but I think it should scale up to 0 stamina instead of 100 stamina. One C-Saber swing and you crank your disarm chance up to 26% as is setup here.

Limb targeting is a good idea, and I think it could work out interestingly, but it really really would kill a few things. There is a delay when you hit someone with a melee weapon, and during that delay you can't stow most things. Fire Extinguishers and normal items can be instantly swooped into a backpack easily, but a C-Saber has a pretty long delay to deactivate it when you've hit someone with it, and the same goes for a katana. Worse off is our friend the Red Chainsaw, you can't even stow that. So, if you hit someone with a C-Saber, and then do the normal switch hands, wait a moment, switch back and deactivate, that person might not care you switched hands, because that Saber is being directly targetted. You also can't block on an offhand and then switch to a different hand, it drops the block.

I'm also curious how this change will interact with weapon arms. When my C-Saber is activated and I switch hands and someone shoves my C-Saber arm, do I dunk myself and bleed out while they shove lock me and I die? Does my Red-Chainsaw stun me and then cut out all of my own organs when someone goes to push me once? Katana is Katana, not a lot of Katana arms honestly, things super dangerous to get weapon arm pushed with.

Answers to these questions would be neat.

**Comment by Alexalmighty502** [comment]
> Targeting the left or right arm while on disarm intent will attempt to disarm the item held in the left or right hand, respectively, of the target.

I'm not a fan of this, in the moments when you are able to disarm you really don't have the time to check which arm the person is using 

> I think the disarm chance at full stamina is fine, but I think it should scale up to 0 stamina instead of 100 stamina. One C-Saber swing and you crank your disarm chance up to 26% as is setup here.

I mean isn't this the inherent weakness of the c saber? I really don't think c saber rampages need any more buffs as is.

**Comment by TTerc** [comment]
I'd personally prefer having disarm chance not based on limb targeting, as limb targeting sucks and so do default hotkeys. I think having it based on whichever hand you currently have active would be a better solution. More simple to understand for new players too.

**Comment by Yellow-Mushroom** [comment]
I very much enjoyed the idea of the disarmed weapon getting thrown the direction of the disarm shove to create scenarios where two people scramble for a weapon.

I can’t say I’m overly positive or negative to this change but I think getting the weapon thrown being added would help with this PR

**Comment by Tarmunora** [comment]
Limb targeting thing removed entirely

**Pull request merged**
