### PR TITLE
Give HoP consistent green carpets

### PR DESCRIPTION
**Pull request by flappybatpal**
## About the PR 
Gives the HoP bedrooms green carpets instead of blue in cogmap2, donut3 and wrestlemap.
Change green carpet in wrestlemap captain's quarters to blue.
Removes arcade carpet from cogmap2 HoP bedroom.
Replaces some mismatched carpeting in the Donut3 captain's quarters with standard floor tiles.

## Why's this needed? 
Most maps give the HoP green carpets and blue for the captain. This makes it a bit easier to tell their areas apart and increases the consistency across our maps.
AFAIK the arcade carpeting is a joke about the captain just like the bedsheets. This is even more consistent across maps in being captain only.

### CODE REVIEW

**Comment by CheffieGithub** [comment]
I noticed that wrestle map still has green carpets in the captains office

**Comment by CheffieGithub** [comment]
also blue carpets in customs if thats also an issue

**Comment by flappybatpal** [comment]
> also blue carpets in customs if thats also an issue

Wasn't sure if to change this at the same time. This is more inconsistent across maps.

**Comment by CheffieGithub** [comment]
if you only want to change offices then save it for a later PR

**Pull request merged**
