### PR TITLE
changed ass_explosion

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
[BALANCE] [INPUT]
## About the PR 
This changes the ass_explosion proc to only roll to remove people's limbs if they have no ass.
This should mostly only affect the wizard spell.
Other places that use ass_explosion are butt-pipebombs, but those have only a 1% chance to delimb anyway, and the fartwaves caused by admins, but I don't care about admins. 🐸 

Do note that, according to my knowledge of probabilities, the current code will have approximately a 25% chance to take off at least one limb, if the person is missing an arse. (Seeing as rathen's secret has a 7% delimb chance.)
Perhaps this value should be changed, or ass_explosion changed altogether to always remove exactly one limb if the person has no arse.
If you have an opinion, please comment here or on the [forum thread](https://forum.ss13.co/showthread.php?tid=14579)!
## Why's this needed? 
There have been lots of complaints about Rathen's Secret recently.
I think that allowing people to reduce the potential damage to themselves by reattaching their butts before the spell gets used on them again provides a nice measure of counterplay, while still giving Rathen's Secret a good use as an AoE stun. 
In addition, if people do not reattach their butts, I think that making it so there is a 100% chance to detach exactly 1 limb would also make it a more reliable spell for wizards to use, as opposed to the rng fiesta it is right now.
## Changelog

```
(u)zjdtmkhzt:
(*) Changed the Rathen's Secret wizard spell to only delimb if you have no arse. It also now always removes exactly one randomly chosen limb in that case.
```

### CODE REVIEW

**Comment by Kyle2143** [comment]
This is good. This is the way I always thought it had worked anyway.

**Comment by zjdtmkhzt** [comment]
Anyone have any thoughts on changing it to always take exactly one limb instead of having it be chance-based? I think that might be a better way of doing things.

**Comment by Kyle2143** [comment]
That is a good idea as well.

**Comment by pali6** [comment]
Yeah, losing 3 limbs at once sucks.

**Comment by Tarmunora** [comment]
Personally, I feel the issue of the spell is more the instant undodgeable/unmissable AoE stun, which makes it trivial to combo into magic missile + polymorph/cluwne

**Comment by zjdtmkhzt** [comment]
Hmm, what would be a good solution to that issue? Perhaps adding a cast time to the spell? It would definitely require buffs if that were to happen, though.

**Comment by UrsulaMejor** [comment]
I saw we go the iterative improvement route; let's merge this as is and spin up a new PR to problem solve the balance concern

**Pull request merged**
