### PR TITLE
Rework faustian chaplain a bit

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[REMOVAL] [BALANCE]
## About the PR 
Removes the voluntary infernal contract signing mechanic from faustian contracts and decreases the forced signing actionbar from 4 to 3 seconds. Also reduces the number of souls required to summon the horseman drone from 15 to 8 and makes some of the contract effects a bit more directly Bad and Evil.

## Why's this needed? 
Nothing else in the game works like this, we have rules against helping obvious antagonists get stronger and yet there's this one mechanic that basically requires people to do that.
The voluntary signing mostly turns what should be an interesting and dangerous gimmick antag into a weird kind of meta situation where people are reluctant to stop them and the inevitable horseman drone feels more like a result of apathy than effort on the antag's part.

These changes should push chaplains more towards stunning and kidnapping people to force them to sign and make them y'know actually play as an antag.

## Changelog 

```changelog
(u)LeahTheTech
(*)Faustian contracts can no longer be signed voluntarily.
(*)Faustian contracts are now almost always hilariously bad for you.
(+)Reduced faustian contract force signing actionbar duration from 4 -> 3 seconds.
(+)Reduced the number of souls required to summon a horseman drone from 15 to 8.
```

### CODE REVIEW

**Comment by Sbmhawk** [comment]
This accomplishes nothing other than making station-wiping much, much easier

**Comment by TobleroneSwordfish** [comment]
Errr what? How?

**Comment by Sbmhawk** [comment]
Working on editing my initial thing

**Comment by TobleroneSwordfish** [comment]
Ah well, now that it's no longer an obvious voluntary action we could enforce not letting a chaplain steal your soul in the same way we enforce not deliberately getting revved or feeding yourself to a changeling. Hopefully that would also encourage a culture shift of people not putting up with faustian chaplains in the same way they do now.

**Comment by TDHooligan** [comment]
this is definitely better than as is. i also wouldnt mind some faith mechanic working similarly to contracts (like Blessings) and then the faustian contracts being turned into ironic blessings.

**Comment by Sbmhawk** [comment]
The drone is rare, yes

But when it does get summoned, it is almost always the result of the crew not doing anything because "friendly contract seller"

**Pull request closed without merging**
