### PR TITLE
Silicons only apply touch to artifacts when not using a tool

### LINKED ISSUE #8291: Using cargo transport on an artifact that is silicone touch activated activates the artifact
### Labels

[TRIVIAL]

### Description

Using cargo transport on an artifact that is silicone touch activated activates the artifact

### Steps to reproduce

1. Be a cyborg that can use the cargo transporter
2. Find artifact that activates with silicone touch
3. Transport the artifact

### Expected Behavior

It does not activate when the transporter is used, as this does not happen for carbon touch activation artifacts when a human uses a cargo transporter on them

### Additional Information & Screenshots

Reported by: ImJustAStrangeMan
On server: Goonstation 1 Classic: Heisenbee
Round log date: 2022-04-21-00-35
Reported on: 2022-04-21 01:01:26

### PR DESCRIPTION
**Pull request by pgmzeta**
[Silicons][science][bug][minor]
## About the PR 
Only apply the silicon touch stimulus when you are not using an item.

## Why's this needed? 
Fixes #8291

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
Is there not an Attack() or after attack handler???

**Comment by pgmzeta** [comment]
> Is there not an Attack() or after attack handler???

Sorry, I don't follow you here; do you mean for artifacts or cyborgs?

**Comment by ZeWaka** [comment]
> > Is there not an Attack() or after attack handler???
> 
> Sorry, I don't follow you here; do you mean for artifacts or cyborgs?

artifacts

**Comment by pgmzeta** [comment]
all of the artifact `attackby` handlers run through this codepath, presumably to keep reactions consistent between them? Not sure what else to poke at here since this is happening to the artifact itself.

**Comment by ZeWaka** [comment]
> all of the artifact `attackby` handlers run through this codepath, presumably to keep reactions consistent between them? Not sure what else to poke at here since this is happening to the artifact itself.

yes, that's why i said attack or afterattack

**Comment by pgmzeta** [comment]
I'm not understanding the relevance - aren't attack/afterattack used when the item itself is used on something else?

**Comment by ZeWaka** [comment]
> I'm not understanding the relevance - aren't attack/afterattack used when the item itself is used on something else?

No, that's attackby - ask me on discord if you have further questions

**Review by ZeWaka — APPROVED** [review]
gaming

**Pull request merged**
