### PR TITLE
New Wizard Names

### PR DESCRIPTION
**Pull request by Sartorius7**
## About the PR 
Adds more wizard names to strings.txt

## Why's this needed? 
Adds more variety to male wizard names.

## Changelog

```
(u)Sartorius7:
(+)Many, many more wizard names for the game to pick from!
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Definitely not a major change

**Comment by Sartorius7** [comment]
Updated the tags, is no longer a major change.

**Comment by ZeWaka** [comment]
changelog entry is incorrect

**Comment by Sartorius7** [comment]
Corrected again.

**Review by pali6 — APPROVED** [review]

**Pull request merged**
