### PR TITLE
Face Disfiguration Retool

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT][REWORK]
## About the PR 

Changes the way face disfiguration (from acid, currently) affects your name:

- Mobs now have a "disfigured" variable, used for the below changes.
- Instead of setting your real_name to Unknown, face melting will now set the disfigured variable to true.
- The disfigured variable is now checked in UpdateName(), causing your visual name to be Unknown in circumstances where your face is visible.
- Synthflesh can be used on a disfigured individual to restore their face.
- Fully healing a mob also removes disfigured.

## Why's this needed? 

Makes facemelting interact better with systems that use real_name (prominently ghosting), and reversible so it's not a permanent hindrance, given treatment.

## Changelog

```changelog
(u)Kubius
(+)Disfigured faces can now be mended with synthflesh, and no longer persist with you into the ethereal plane.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
I feel like the current methods for healing disfigurement are too easy, maybe make it a surgical procedure or have it require some more scarce materials?

**Comment by ZWRh3** [comment]
> I feel like the current methods for healing disfigurement are too easy, maybe make it a surgical procedure or have it require some more scarce materials?

i agree this also makes it worse for antag purposeful self face melting which is a real strat that can be sometimes done

**Comment by Kubius** [comment]
Open to the possibility of changing up what works for face correction. Some ideas I had (picking one):

- Requires that you have less than 25 burn damage (threshold for burn damage going away).
- Requires that you have less than 25 combined burn and brute damage.
- Remove face-mending entirely from the scope of this PR and introduce a different dedicated mending tool or procedure in a subsequent PR.

WRT changing your real_name - disfiguration does not do that anymore at all. A "disfigured" var is set to true instead, and that now affects specifically your outward appearance; voice is currently **not** affected, but it would be fairly straightforward to make that the case with a ternary check in a particular location.

**Comment by TDHooligan** [comment]
i'd definitely change fixing it to something more avoidable & deliberate like synthflesh applied topically to the face. having a disfigured face is sometimes the players' choice.

**Comment by Kubius** [comment]
Synthflesh's healing mechanism is already exclusively topical, and I don't think there's a way to make it act differently when administered by, say, a dropper. A dedicated "dermal regenerator" device loaded with synthflesh could behave differently, but that would likely be a discrete PR.

**Comment by DisturbHerb** [comment]
facial reconstruction surgery would be cool, i think

**Review by Tarmunora — APPROVED** [review]

**Comment by ThatFiveGuys** [comment]
I think synthflesh should just be the only option to repairing faces.

**Pull request merged**
