### PR TITLE
Replaces the red cross with a symbol that doesn't violate the Geneva Convention

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
It has recently come to my attention that we aren't allowed to use the red cross symbol. This PR fixes this oversight.
dreamseeker_uIavZC1JD7

(Also makes ass jam actually compile. Also adds _std/ass_jam.dm. Also reorganizes __std.dme a bit to be saner.)

## Why's this needed? 
We'll be taken to court as war criminals otherwise. Top priority to merge.

## Changelog

```
(u)pali
(*)Red cross symbols violated the Geneva Convention. They were replaced by a more appropriate medbay symbol.

```

### CODE REVIEW

**Comment by moonlol** [comment]
yes please

**Review by moonlol — APPROVED** [review]

**Comment by Adharainspace** [comment]
ty

**Comment by comradef191** [comment]
thank god

**Comment by pali6** [comment]
Proof of kyle's approval:
image

**Pull request merged**
