### PR TITLE
Land Mine Resprite + Slight Changes To Mine Name/Desc

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Resprites land mines, gives each type a unique sprite, including a sprite for when they're armed (the little light blinks!). Changes the name of the mines from things like "land mine (stun)" to just "stun land mine". Adds a terse descriptor of what each mine is supposed to do to the desc.

(Old on top, bottom row, left to right, high explosive, incendiary, radiation, stun)

## Why's this needed? 

Old sprite bugged me, I wanted to draw land mines, so I've done so. I think these look better and I think the visual distinction is a better way to convey info to players that was previously only shown on mouseover. I think the name's just read better and that the detail in the description better match what a description in this game is typically trying to tell you.

## Changelog

```changelog
(u)Flaborized
(+)Resprited land mines.
```

### CODE REVIEW

**Comment by Studenterhue** [comment]
I dig the new armed indicator and really, really dig having different sprites for different mines (definitely need more of that kind of differentiation). The "legs"/spikes bug me a bit though. They kinda make me think it's a sort of stand or holographic display, like with the holo-emitter janitor signs.

**Comment by Flaborized** [comment]
> I dig the new armed indicator and really, really dig having different sprites for different mines (definitely need more of that kind of differentiation). The "legs"/spikes bug me a bit though. They kinda make me think it's a sort of stand or holographic display, like with the holo-emitter janitor signs.

That's a fair opinion to have, they are definitely just greebles, though I think without them they look very Basic (even though that's what realistic land mines look like) and bare without, and the little legs makes it both larger (I wanted it to be about as wide as the original without making it an oval) and and a little bit more like a sci-fi prop.

**Comment by virvatuli-gh** [comment]
I like em, they're perhaps a little too visible now which will hurt them actually being useful but anything to replace the old sprite (that I said I was going to resprite months ago and never did). More of a sci-fi aesthetic is good in my opinion, you could say the little arms are grabbers and part of the anti-tamper system or something. Justification for greebles.

**Comment by Flaborized** [comment]
Figuring that if people walk into hallway crushers, they'll also step on these wrt size. Old ones mostly blended in because their sprites really low contrast and a bit Bad

**Review by virvatuli-gh — APPROVED** [review]

**Comment by notfrying1pans** [comment]
old landmine was from before 40.93.2 btw, so 2005/2006-ish

**Pull request merged**
