### PR TITLE
Adds decon flags to things which probably should've had them

### LINKED ISSUE #6425: Guardbuddy docking station cannot be deconstructed
Submitter: anon
**Describe the bug**
The charging docks that the guardbuddies sleep at are unable to be deconstructed with the deconstruction tool.

### PR DESCRIPTION
**Pull request by Nexusuxen**
## About the PR 

The following things now have decon flags, including DECON_DESTRUCT to properly initialize their New() procs:

- Telepad and Teleconsole
- Firedoors (now also mechscannable with Mats set to 30, though this can be adjusted)
- Guardbuddy docks

If the firedoor one is too out of the scope of bug/oversight fixing, I'd be happy to remove it.

Inherently fixes #6425 

## Why's this needed? 

These should really be able to be deconstructed. That and having telepads/teleconsoles brick is annoying as heck and is both confusing and frustrating for players trying to learn how to use these.

## Changelog

```changelog
(u)Nexusuxen
(+)Firedoors and a couple other things can now be deconstructed. Telepads and Teleconsoles will also connect to data terminals when you redeploy them instead of bricking.
```

### CODE REVIEW

**Comment by Arthur-Holiday** [comment]
Do mech scanned firedoors behave properly when built in a different area?

**Comment by Nexusuxen** [comment]
> Do mech scanned firedoors behave properly when built in a different area?

That's a fantastic question; I had presumed they would given that they'd get their area on New(). I should make them DECON_DESTRUCT so that they also reset their area

**Comment by Nexusuxen** [comment]
Update:

Firelocks will now spawn in their new area as normal and be connected to their respective firelock, either when deconstructed from an existing firelock or a newly printed one. Their direction will also depend on the direction of the frame before being deployed. I also tested to make sure that you couldn't scan different directions of firelocks; you can't.

**Comment by flrsh** [comment]
This being a bug is debatable. At most it's an oversight. Imo, if you're submitting bugfixes during the freeze, they should be straightforward and should not require discussions about balance and intent.

**Comment by Nexusuxen** [comment]
> This being a bug is debatable. At most it's an oversight. Imo, if you're submitting bugfixes during the freeze, they should be straightforward and should not require discussions about balance and intent.

Got it. Should the PR be closed or should I reduce it to only include telepads/teleconsoles?

**Comment by Crystalwarrior** [comment]
> This being a bug is debatable. At most it's an oversight. Imo, if you're submitting bugfixes during the freeze, they should be straightforward and should not require discussions about balance and intent.

No, I don't think it's an oversight, everything this pr affects can be scanned including fire locks, the behavior is just completely jank

**Comment by frawhst** [comment]
fire door cost could probably go lower, but we'll see how it works out

**Pull request merged**
