### PR TITLE
Horizon QM piping removal

### PR DESCRIPTION
**Pull request by Chatauscours**
[QOL]

## About the PR 
This PR rennovates the horzion QM office in order to make it not reliant on piping, which burst every single round from some random explosion.
Also adds a new jazz lounge where the old router was.
Before:
beofre 1
before 2
before 3
before 4

After:
after 1
after 2
after 3
after 4

## Why's this needed? 
Because that piping breaks every single time, making QM unusable. 

## Changelog

```changelog
(u)Chatauscours
(*)The Horizon QM does not rely on piping anymore, having now direct imput and export loaders.
```

### CODE REVIEW

**Review by TTerc — COMMENTED** [review]
I didn't look at all of the changes you made but I noticed you misplaced some wallsign letters, for example, here:

**Comment by Chatauscours** [comment]
This is wierd considering I haven't touched the wallsigns at all. Anyway, it is fixed now.

**Comment by TTerc** [comment]
> This is wierd considering I haven't touched the wallsigns at all. 
The research one also got moved

**Comment by Chatauscours** [comment]
Ah, yes, fair enough, forgot about it.  It us at the northen artsci wall now. I do guess I did a mishap that moved the O signs everywhere. It is fixed now.

**Comment by NightmareChamillian** [comment]
image
if this is the router I think it is, I'm pretty sure it's the one ghostdrones rely on in order to get onstation. Is there a way for them to have transportation still?

**Comment by Chatauscours** [comment]
Yes, you can see at the screenshot of the new router, that there is a blast door is turned towards the station (north) and, even if not visible on the screen, there is a loader directed towards the station to lauch the ghostdrones there.

**Review by TTerc — APPROVED** [review]

**Pull request merged**
