### PR TITLE
Introduce /datum/storage/no_hud/machine for stacking bars from other storages

### LINKED ISSUE #19326: Fabricator: adding materials from a bag doesn't register them
### Labels

[BUG][MAJOR]

### Description

Materials added by hitting a bag against a fabricator (which transfers materials) aren't usable to build items.

### Steps to reproduce

1. Refine some material bars. Put them in a satchel, enough to make a recipe in the target fabricator.
2. Hit the satchel against the fab. This should transfer all materials from the satchel to the fab.
3. The materials are listed in its inventory, but recipes requiring them are still blocked.
4. Eject the materials and load them by hand one-by-one. The recipes now work.

### Expected Behavior

Materials in the inventory to be usable at any time

### Additional Information & Screenshots

hi romayne

Reported by: smilg
Client version: 515.1637
On server: Goonstation Nightshade 1
Active test merges: nothing
Round log date: 2024-06-04-04-08
Reported on: 2024-06-04 04:55:40
Round ID: 1433
Map: OSHAN

### PR DESCRIPTION
**Pull request by MeggalBozale**
## About the PR 
Introduces a new storage datum for machines, which stacks any stackable items being inserted into them.

This is directly aimed at manufacturers and taken from a project I'm working on, since it should help fix a relevant bug.

EDIT: Upon request, now changes /datum/storage code to support stacking over adding when possible, if the bool is TRUE (FALSE on /datum/storage, TRUE for this new machine storage datum)

## Why's this needed? 
Fixes #19326

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
i think this should just be a var on datum/storage

you also no longer inherit from no_hud

**Comment by MeggalBozale** [comment]
woops, and sure thing

**Comment by MeggalBozale** [comment]
image

**Comment by MeggalBozale** [comment]
image
Because of this, I am going to do:
`P.amount = round( (P.amount - (required_amount/10)), 4)`

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
