### PR TITLE
Buff taser shotgun

### PR DESCRIPTION
**Pull request by Tarmunora**
[BALANCE]
## About the PR 
Tightens spread on taser shotgun and improves the rate of fire (6 ds delay down from 15)
Standard taser mode has standard 4 ds shoot delay

## Why's this needed? 
Taser shotguns are currently slow, and underwhelming at anything but literal pointblanks.
Tightening the spread to 10 degrees makes the pellets cover a 3 tile spread at the end of their range, which feels much better

## Changelog

```
(u)Tarmunora:
(+)Buffed taser shotgun
```

### CODE REVIEW

**Comment by flrsh** [comment]
3 tile spread sounds good to me. Maybe keep the delay at, say, 10 seconds, though.

**Comment by Tarmunora** [comment]
10 second firing delay seems uh. Harsh.

**Comment by flrsh** [comment]
Whoops sorry I meant deciseconds, so 1 second.

**Comment by Tarmunora** [comment]
Hm. Assuming all projectile hit at very close range:
* Nonburst taser - 5 power/ds
* burst taser - 15 power/ds
* old shotgun - 3 power/ds
* current shotgun - 7.5 power/ds
* 1s delay shotgun - 4.5 power/ds
I think that being 50% more average tasing-power at point-blank ranges is fine, especially consider taser shotgun pellets fall off much faster than taser bolts, plus the spread.

**Comment by flrsh** [comment]
Fair, I'll trust your judgement! I just don't want these to be *too* effective against multiple opponents, but that's probably better suited for actual ingame testing.

**Pull request merged**
