### PR TITLE
Adds an "Offbrand Dart Crate" to EMAGged QM consoles

### PR DESCRIPTION
**Pull request by Zonespace27**
[Feature] [Balance]
## About the PR 
You know how there's the on-brand nerf darts, then there are those ones that you can buy in bulk that have those near-solid tips? These are the latter.

On EMAGging a QM console, there will be a new option available ontop of the already available SpecOps crate, being an "Offbrand Dart Crate". This crate costs 5000 credits, and contains two boxes of offbrand foam darts along with its respective dart gun. The boxes. the darts, and the dart gun have a unique sprite, switching out the lime green for a red color. The darts themselves are slightly faster, and deal 25 stamina damage per shot.

## Why's this needed? 
EMAGging a QM console is a bit sparce, and could use some more gear, and I thought this'd be a fun addition to slightly weaponize dart guns.

## Changelog

```changelog
(u)Zonespace
(*)Using an EMAG on a QM console now will unlock an "Offbrand Dart Crate" in QM. Details in the minor changes section.
(+)The crate costs 5000 credits and contains two boxes of 20 darts each, along with a specific dart gun that can only load the darts.
(+)The darts themselves have a slightly more distinguishable sprite, can only fit in the offbrand dart gun the crate contains, and deal 25 stamina damage per shot.
```

### CODE REVIEW

**Comment by BatElite** [comment]
Why not toss a dart gun into the crate?

**Comment by penny64** [comment]
The creator doesn't want any weaponization of nerf guns, they are supposed to be toys that aren't suspicious to use

**Comment by unfunnyperson** [comment]
Maybe if the darts have to be loaded in a special colored nerf gun that comes with the crate? This would make carrying around a regular nerf gun significantly more suspicious which ruins the fun of them being harmless toys.

**Comment by Zonespace27** [comment]
> The creator doesn't want any weaponization of nerf guns, they are supposed to be toys that aren't suspicious to use

@penny64 The creator of it, @unfunnyperson, seems to be fine with it as long as it can only fit in a different dart gun, which i did.

**Comment by penny64** [comment]
oh yeah this looks good now sorry

**Comment by Bram-KEP** [comment]
Ah shame

**Pull request closed without merging**
