### PR TITLE
Replaces burst fire on tasers with detain.

### PR DESCRIPTION
**Pull request by DimWhat**
[balance] [input wanted]
## About the PR 
Replaces the burst fire mode on default tasers with the AOE detain mode from the lawbringer. This will remove the most go-to instant stun in security's arsenal while giving more utility to the default taser.

## Why's this needed? 
Taser burst currently serves as a one shot down with very little downside besides a higher cost. Which is actually more energy efficient than firing 3 taser shots. People tend to burst fire in order to instantly knock down a target with very little counterplay. This leads to the taser overshadowing things like the taser shotgun for high stamina damage in a single click, as well as the taser SMG for firing lots of shots out.

## Changelog

```changelog
(u)DimWhat
(*)Replaced burst mode on tasers with an AOE mode
```

### CODE REVIEW

**Comment by DimWhat** [comment]
> If anything I would rather see the secondary functionality of the taser be removed entirely. It's supposed to be the boring, default choice for those who are not interested in anything other than utilitarianism. I do not want to see lawbringer functions added to it, and would rather see other options buffed instead to make them worth picking for their gimmicks.

Interesting point, I mostly made this out of a feeling that it needed to be replaced with something else. Though that may be a way of thinking I need to kick.

**Comment by flrsh** [comment]
> If anything I would rather see the secondary functionality of the taser be removed entirely. It's supposed to be the boring, default choice for those who are not interested in anything other than utilitarianism. I do not want to see lawbringer functions added to it, and would rather see other options buffed instead to make them worth picking for their gimmicks.

Agreed. I actually think burst fire is fine, too, since it's a gamble (and it's not more cost efficient either - it costs 75, while regular taser shots cost 25).

**Comment by mralexs5** [comment]
There are quite a few people on the discord that think the burst is a problem, mostly because its not that hard to use well

**Comment by Tarmunora** [comment]
Giving tasers an AoE mode is a no.

**Pull request closed without merging**
