### PR TITLE
Changes ling island iced tea recipes heat when being created

### PR DESCRIPTION
**Pull request by unfunnyperson**
[BALANCE]
## About the PR 
Changes ling island iced tea to need to be heated when being created.

## Why's this needed? 
Using the long island iced tea recipe you can instantly purge all neurotoxin which isnt fun for lings who have one of their abilities rendered pretty much useless. 

## Changelog

```changelog
(u)UnfunnyPerson
(+)Ling Island Iced Tea recipe now requires heating to 100C when being created.
```

### CODE REVIEW

**Comment by Alexalmighty502** [comment]
This kind of removes ling from ling iced tea.

**Comment by Vaskritaya** [comment]
> 
> 
> This kind of removes ling from ling iced tea.

Lings have capulettium in their sting instead of neurotox on the RP servers, so it's still plenty relevant.

That being said, doesn't this just kinda shift the problem over to the rp servers? I suppose in theory it's less likely to see that sort of powergaming in rp, but in practice...

**Comment by Zonespace27** [comment]
As an RP player, I just see this as shifting the problem over to another server, not a fan in the least.

**Comment by unfunnyperson** [comment]
capu+?, although that could make it a little too hard to make

**Comment by ThatFiveGuys** [comment]
Using ling iced tea on rp would be pretty powergamey and get you bwoinked. Also its important to note that with these changes you could take a hydrogen and fluorine pill to turn neuro into capu, then take a tea pill to make ling iced tea

**Comment by unfunnyperson** [comment]
changed it to require an open container so the problem isnt shifted to rp

**Comment by penny64** [comment]
It's weird for things to randomly stop working in a pill, bad UX

Why not just nerf the effectiveness? That's the problem here it's as least twice as good as it needs to be

**Comment by MatheusIsNotAvailable** [comment]
Make it so the resulting mix has some of the neurotoxin in it, that way a bartender could easily filter it out but a powergamer with a pill would still have the neuro In them

**Comment by flrsh** [comment]
Open container doesn't feel super intuitive yeah. Maybe do this—

> Make it so the resulting mix has some of the neurotoxin in it, that way a bartender could easily filter it out but a powergamer with a pill would still have the neuro In them

Or maybe even make ling island iced tea similarly debilitating?

**Comment by mordent-goonstation** [comment]
> Open container doesn't feel super intuitive. Maybe do this—
> 
> > Make it so the resulting mix has some of the neurotoxin in it, that way a bartender could easily filter it out but a powergamer with a pill would still have the neuro In them
> 
> Or maybe even make ling island iced tea similarly debilitating?

You could also change the amounts for the recipe so that it doesn't consume much neurotoxin, i.e. you would have to chug a lot more Long Island Iced Tea to convert the 50u of Neurotoxin (example: 1u Neurotoxin, 4u Long Island Iced Tea -> 5u Ling Island Iced Tea).

You could also making it require heating up, akin to how you test changeling blood. I feel like this would be thematic and make purging the Neurotoxin a little fiddlier (still possible, but you'd risk some burn damage as well).

**Review by Tarmunora — CHANGES_REQUESTED** [review]
Seconding suggestion to make recipe require heating instead

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
