### PR TITLE
Adds a counter on the hud for possession points for trickster

### PR DESCRIPTION
**Pull request by Bartimeus973**
[QOL] [UI]
## About the PR 
Moves the possession_points variable tracking available possession points from the wraith over to it's abilityHolder which lets me display the amount of possession points available.

## Why's this needed? 
It was unclear "when" you could possess someone. Now with the counter being proudly displayed you can know that you are generating possession points and when you can use them.

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
I'm pretty sure the ability holder is meant to be able to display more than two variables?

**Comment by Bartimeus973** [comment]
Didnt seem to work while testing, it didnt show any variable past the second one, might be a display restriction i could tweak.

**Comment by Bartimeus973** [comment]
After some fiddling with the ability parent, i've re-purposed some bits of codes from the composite ability holder to allow more than two values to be displayed. Didnt appear to break anything during testing.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
conflict

**Comment by Bartimeus973** [comment]
I believe i fixed it. The label merge conflict seems to have been happening all day. Do tell me if i am mistaken!

**Pull request merged**
