### PR TITLE
Adds glass floors to the observatory in COG1

### PR DESCRIPTION
**Pull request by Laboredih123**
## About the PR 
image

## Why's this needed? 
It looks neat

## Changelog 

```changelog
(u)cringe
(+)Nanotrasen put some new flooring in the cogmap observatory.
```

### CODE REVIEW

**Comment by Laboredih123** [comment]
why is it shattering, its *meant* to have underlays

**Comment by Laboredih123** [comment]
otherwise how would the effect work in non-parallax mode?

**Comment by itchybones** [comment]
I think the cl entry should specify that it's on cog1, since most people's minds would probably jump to the telesci place

**Comment by Laboredih123** [comment]
done

**Pull request merged**
