### PR TITLE
Removes space_fastpath, Fixes Issue #3545

### LINKED ISSUE #3545: Windows atmospherics issues
[BUG]

**Describe the bug**
Windows seem to interact with atmos in very strange and unintentional ways. In this instance specifically, a thindow was used to rapidly depressurize a large part of the station.

**To Reproduce**
Dislodge any thindow, I used one near the cogmap1 medbay:

Pull it with you to any airlock directly connected to a space turf; I was unable to reproduce this when using an airlock connecting to a catwalk surface. I used the south-west airlock in the cogmap1 escape wing:

Open the airlock, keep pulling the thindow and run around for a bit. Observe:

For reference, this is the effect opening an airlock has on atmos when you're not dragging a thindow around (for roughly the same duration):

**Expected behavior**
Not obliterating atmos.

**Additional context**
Related to https://forum.ss13.co/showthread.php?tid=10637

EDIT: This is not exclusive to thindows. The above can be reproduced using a regular window as well.

### PR DESCRIPTION
**Pull request by Laboredih123**
## About the PR 
Comments out references to space_fastpath and  #space_fastpath. Closes #3545 

## Why's this needed? 
Without this fix, rooms would be easily depressurized.

### CODE REVIEW

**Comment by ZeWaka** [comment]
This is hardly the right fix for the issue, lol. This is a feature removal and should be marked as such.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
Please remove the code instead of commenting it out. Git revision history exists for a reason.

**Comment by Laboredih123** [comment]
I'm still pretty new at this

**Comment by Laboredih123** [comment]
So I'm still learning

**Comment by Laboredih123** [comment]
There we go

**Comment by penny64** [comment]
So what feature is removed what are the ramifications of this besides the bug fix?

**Comment by Laboredih123** [comment]
No idea, but I'm not the admin

**Comment by ZeWaka** [comment]
Not the fix we're looking for at this time.

**Pull request closed without merging**
