### PR TITLE
AI-driven NPCs use bioEffect powers

### PR DESCRIPTION
**Pull request by pgmzeta**
[FEATURE][AI]
## About the PR 
AI-driven monkeys attempt to use the following bioEffects, at random, as part of their wandering routine:
* Midas Touch
* Ink Glands
* Healing Touch

AI-driven NPCs (including monkeys), when aggroed:
* Use  Optic Energizer, Cyrokinesis, and Jumpy when their target is at a distance
* Use Adrenaline Rush when unable to get to a target (frustration > 25)

## Why's this needed? 
need is a strong word but my answer is: genetics.

## Changelog
```
(u)glowbold
(*)Monkeys have learned how to use some genetic abilities!
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
Do you think you'd also be able to add the adrenal gland ability?

**Comment by pgmzeta** [comment]
this would be so much easier if I refactored all power abilities to have a separate effect() that assumes you have a valid target. Hm.

**Comment by pgmzeta** [comment]
> Do you think you'd also be able to add the adrenal gland ability? Would love to see a geneticist get bonked by a meth-driven chimp

Hm, maybe when they drop below a certain % health?

**Comment by pgmzeta** [comment]
actually, maybe what should happen is that targetable effects get a `target()` for human abilityHolders to pick/aim at a target, which then does the `cast()` to do the ability.

**Pull request merged**
