### PR TITLE
Security Badges

### PR DESCRIPTION
**Pull request by Flaborized**
[FEAT]

## About the PR 

Adds in **Security Badges**, which spawn inside the backpacks of Security Officers, Detectives, NTSO Operatives (The latejoin ones), Vice Officers and the HoS. They're small items, and can fit in pockets, boxes, pouches, w/e. If you use them in-hand, you show them to nearby people (like you can do with ID cards), showing off the name and job on the badge. It can also be worn in the outer suit slot if you really want, but it's not armored or anything so it's really just an aesthetic thing. The name and job on it are the same as the person who spawned with it, and cannot be changed.

## Why's this needed? 

Badges are a fun police trope, and would have fun mechanical implications IMO. Having a badge indicates that you're a "real" sec officer, and didn't transfer over. This means that showing your badge is like a way to indicate that you're _probably_ not a traitor in disguise. Because it adds this credibility to you, I think it'd mimic the "show me your badge!!" trope in practice, which I think is fun. Could also lead to some fun roleplaying opportunities! Like the HoS firing the det and telling them to "Turn in their badge and their gun" just like in the movies **!!!**

Is not a job or medal reward because I feel that it's important to the identity of the item that all sec have it when they start. It's like an "All cops have a badge!!" sorta thing.

## Changelog

```
(u)Flaborized:
(*)Security department roles now start with badges that they can show off!
```

### CODE REVIEW

**Comment by trerri** [comment]
when worn in outer suit make it reflect 100% electricity damage but only if your first name is Franklin

**Comment by mybluecorners** [comment]
we should add a particle effect similar to the ones glowstick dancing uses, a bright 'shine' that flashes over your sprite when you show someone your badge

**Comment by ZeWaka** [comment]
Would be cool if you could pin it to your uniform, like as a little inventory slot for it or something... Same with the "first place" medals

**Comment by Kyle2143** [comment]
I feel like these badges can replace the whistles that are in the security pouches. If that was the only way to get whistles, we can add em to the security vending machine.

Also, we discussed this in discord. Give a badge to Beepsky and Sylvester that you can take if you kill em! (Sylvester's death proc is in the secret submodule so I can add the line that drops the badge there if this is done).

**Pull request merged**
