### PR TITLE
Landmarks Refactored

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Refactors landmarks to be a bit saner:

- unused landmarks gone
- `landmarks` is now an associative list of lists, `landmarks["latejoin"]` is the list of latejoin landmarks for example
- _std/defines/landmarks.dm contains macros for most landmarks
- some spawner landmarks got replaced by the actual objects, others got cleaned up and smooshed into /obj/landmark/spawner
- fixed the biodome elevator bug
- added `pick_landmark` proc to help with picking landmarks
- moved the spawner landmarks to use `initialize` if pre-roundstart
- I guess number of loot crates is now a bit different. Previously it was restricted to some random number. Now each loot crate landmark has 75% chance to contain a crate. I can change that if needed.
- cryotrons now use by_type and friends
- I have no idea how nukie boss always got spawned in the boss chair, I literally can't find the code that did that. Now it's guaranteed in the code that they will spawn there.
- fixed some other random crap that I forget
- idk, probably a lot of stuff

## Why's this needed? 
Old code sucked. New code sucks less. A bit.

### CODE REVIEW

**Comment by pali6** [comment]
Did I test this? Yes.
Did I test everything I changed? Hell no.
Stuff like artifacts, lootboxes, npcs etc. gets spawned properly.
Latejoin and missile latejoin works fine.
Job spawn points also seem to work.
newplayer landmark seems to be ok too.
All nukie stuff seems to work.
Compiling with only one z-level doesn't create any runtimes.

I didn't check most of the other stuff (mineral magnet, vr, telesci, long range teleporter, blob tutorial, cruisers, wizard spawn, thunderdome, prison zone, escape pods, pests, kudzu, AI blob, elevator holes, ...).

**Comment by pali6** [comment]
Did additional testing. What works: VR, prison zone, magnet (probably?), thunderdome, lrt, telesci, biodome elevator.

**Comment by pali6** [comment]
Oh and also this regex should fix maps affected by this change:
```
/obj/landmark([\s\n]*\{[\s\n]*name = "(shitty_bill|john_bill|big_yank|father_jack|don_glab|monkeyspawn_normal|monkeyspawn_albert|monkeyspawn_rathen|monkeyspawn_mrmuggles|monkeyspawn_mrsmuggles|monkeyspawn_syndicate|monkeyspawn_horse|monkeyspawn_krimpus|monkeyspawn_tanhony|monkeyspawn_stirstir|seamonkeyspawn|seamonkeyspawn_gang|seamonkeyspawn_gang_gun|seamonkeyspawn_rich|seamonkeyspawn_lab|waiter)"[\s\n]*\})
```
replace with:
`/obj/landmark/spawner$1`

Moreover you need to yeet weed / strange seed spawners and just replace them with the damn item.

**Comment by geneva-breaker** [comment]
sure why not

**Comment by pali6** [comment]
Not like anyone was gonna review this anyway. yolo

**Pull request merged**
