### PR TITLE
Adjusts colour of coloured cables & made cable pathing a bit more sane.

### PR DESCRIPTION
**Pull request by comradef191**
[FEATURE]
## About the PR 
**!! This PR Will break any maps using coloured cables due to changes in the pathing of cables !!**
**_Remove all cases of `colored/` using a text editor inorder to fix your maps & code, as only coloured cables use this path!_**

Adjusted the colour of coloured cables,
	Black made darker, so as to be clear its actually black & not grey
	Purple is now Mentor Purple, rather then being ALMOST Mentor Purple
	Brown made more of a Chocolate shade, rather then Orange
	White made white, rather then very, very _almost_ white
	Yellow, Orange, Blue, Green made brighter & generally more distinguishable

Removed the use of the unnecessary `cable/color/_color`, now making it just `/cable/_color`
Removed the Abstract Type for cables crates, because why did i do that rather then just have coloured crates just be a child of the regular crate? _(Spoiler: Its because I'm a dumbass)_

Comparison of old colours vs new/adjusted colours.
image

## Why's this needed? 
Orange barely looks orange, brown looks orange, the colours are generally not quite as clear as they could be
I was a dumbass and gave coloured cables & stupid pathing

### CODE REVIEW

**Comment by ZeWaka** [comment]
Not a big fan of the color changes, except for the orange

**Comment by comradef191** [comment]
uh wuh wah oh no

**Comment by comradef191** [comment]
### i appear to have done a fuckey wuckey oh no

**Comment by comradef191** [comment]
okay, fuck, nearly there

**Comment by comradef191** [comment]
huzzah

**Comment by comradef191** [comment]
wait hang on what
image

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
