### PR TITLE
Adds a DIY holy water kit to the Chaplains locker

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Adds a box to the chaplains locker that contains 3 bottles of wine, 3 bottles of mercury and a holy water bottle

## Why's this needed? 
Relying on the Barman to get you holy water is a bit eh. Getting a refill seems more fitting

## Changelog

```
(u)Carbadox:
(+)Added DIY Holy Water kit to Chaplains locker. Contains 3 bottles of wine and 3 bottles of mercury alongside a holy water container
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
This seems like a funny addition, although, to be perfectly honest, I would prefer it if the chaplain got some kind of mechanic that allows them to just 'bless' regular water into holy water, which seems like it would be in line with the other benefits that chaplain training grants.

**Comment by Carbadox** [comment]
My reasoning why I think chaplain is fine without a way to bless water is that it's almost a bit of a joke that the only way to get holy water is through science

**Comment by ZeWaka** [comment]
eh, I don't like this because the chaplain loses the cool holy water bottle, it has a neat sprite

**Comment by zjdtmkhzt** [comment]
@ZeWaka 
How would they lose the bottle? There is one in the kit, and I think the idea is that you refill it using the other stuff.

**Comment by ZeWaka** [comment]
> How would they lose the bottle? There is one in the kit, and I think the idea is that you refill it using the other stuff.

oops, didn't see that the bottle was in the kit, only that it was removed from the locker

**Pull request merged**
