### PR TITLE
Add death confetti purchase

### PR DESCRIPTION
**Pull request by BatElite**
[feat]
## About the PR 
Adds a spacebux thing to add the death confetti component you normally only get as a clown.

## Why's this needed? 
I figured it'd be fun.

## Changelog

```changelog
(u)BatElite
(+)Make the most of a sombre situation with spacebux death confetti!
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Not a bad idea but I saw criticism when this was getting added to mentor mouse that it was supposed to be quite unique to the clown and adding it to mice would dilute that.

**Comment by BatElite** [comment]
Wasn't aware of that conversation having happened, we'll see if anyone minds. It's not a big deal if it doesn't go through.
I think it'd be nice to have something along the lines of an on-death effect available though.

**Comment by Flaborized** [comment]
Hi yeah I didn't like this with mentor mice, I think it's better as a Just Clown Thing, the more the joke is used the less funny it is imo. Keeping it to just the clown makes it more unique and thus more interesting/surprising/humorous when it happens.

**Comment by BatElite** [comment]
Fair enough

**Pull request closed without merging**
