### PR TITLE
Fixes AI status displays not showing the AI status.

### PR DESCRIPTION
**Pull request by Paaiii**
## About the PR 

Should fix #15672 making all AI status displays completely blank because of not updating the names in the statusdisplay dmi file

also cleans standardization further: uses _ as a break between the item type and the specific instance, with - being further subdivision between instances
so "frame_radio" specifies the sprite category as an AI frame object, with the specific file being the radio,
and "ai_happy-lod" specifies the sprite category as AI screen, and the specific file as the happy expression, in light on dark mode.

## Why's this needed? 

Fixes a silly bug, further standardization good

### CODE REVIEW

**Comment by 444Portal** [comment]
Oh, thank you so much. Sorry for causing this in the first place.

**Comment by 444Portal** [comment]
Oh, and, one note. The reason I changed things to be 'ai-display_lod' for example, is per recommendation. But I guess this way works too.

**Comment by Paaiii** [comment]
> Oh, and, one note. The reason I changed things to be 'ai-display_lod' for example, is per recommendation. But I guess this way works too.

aah, was it? I mean, I just blinked and suddenly I'd completely redone the naming standardization i wasnt even cognizant during it hjsdkhgdsg
I can change the -s back to _s and all the other things but this also affects the naming for the powermode overlays and the open cover overlays and the framing kits and all of that

**Comment by 444Portal** [comment]
> > Oh, and, one note. The reason I changed things to be 'ai-display_lod' for example, is per recommendation. But I guess this way works too.
> 
> aah, was it? I mean, I just blinked and suddenly I'd completely redone the naming standardization i wasnt even cognizant during it hjsdkhgdsg I can change the -s back to _s and all the other things but this also affects the naming for the powermode overlays and the open cover overlays and the framing kits and all of that

Any consistency is better than no consistency i think

**Comment by ZeWaka** [comment]
whatever

**Pull request merged**
