### PR TITLE
New Mining level prefab: Crashed Genetics Transport

### PR DESCRIPTION
**Pull request by Bartimeus973**
## About the PR 
Adds a new prefab, a ruined medical shuttle embedded into a fermid nest, pictured here:
geneticsship

The shuttle contains some medical tools and chems, an animal control locker, a few fermids, one storage shelf with 6 full medkits if someone is brave enough to fight all the fermids, and one special geneticist.

That special geneticist will grab anyone who comes close and stuff them into a pod which will give them a bunch of random mutations. The geneticist will try to remain around his console and will answer to provocation with violence. The geneticist can only use his special console and pod which are unusable by anyone else.

Reuses bits and bobs of different AI like mimics, dogs and pikaia.

Idea originally suggested by PrimeNumb.

## Why's this needed? 
It's a fun prefab which rewards explorers with something very hard to get in other random prefabs: Genes (not necessarily good ones). Also provides a bit of storytelling through context and items, and can serve as a fun encounter for explorers with some decent medical rewards.

## Changelog 

```changelog
(u)Bartimeus973
(*)A new random prefab has landed in the mining level: A crashed medical transport with one surviving occupant!
```

### CODE REVIEW

**Comment by pali6** [comment]
I think the idea was originally suggested by @PrimeNumb and not me

**Comment by Bartimeus973** [comment]
Changed PR description to credit the right person!

**Comment by pali6** [comment]
Does it currently add new effects or activate ones in the mob's gene pool?

**Comment by Bartimeus973** [comment]
The gimmick pod adds completely random effects to the occupant through `bioHolder.RandomEffect("either")` .

**Comment by CheffieGithub** [comment]
A few things:
All the space turfs should be variable clear turfs.
The turf under the corner in the asteroid should probably be an asteriod turf.
The turfs under windows should be plating.
The cockpit windows are going to look a little odd in-game maybe add shuttle corners or connect them fully?
The geneticist could have a monkey or two as well.

But a very good idea for a prefab, always working hard those geneticists even in the most dire of situations.

**Comment by Bartimeus973** [comment]
Thanks for the recommendations, added all of them. I also redid the back-room and changed it from a bedroom to an engine room.

**Comment by NightmareChamillian** [comment]
Most situationally aware geneticist:

**Comment by Bartimeus973** [comment]
There's a few AI bugs i'm going to try to resolve before this is merged.

**Comment by TobleroneSwordfish** [comment]
Is this ready for review?

**Comment by Bartimeus973** [comment]
Certainly. I just have a little struggle with the ai seemingly evaluating tasks it shouldn't sometimes. Any help would be most welcome with it.

**Comment by Bartimeus973** [comment]
Still struggling with the AI but haven't given up on this yet. I'll try and find help once my schedule is freed up.

**Pull request closed without merging**
