### PR TITLE
xray syndicate glasses

### PR DESCRIPTION
**Pull request by flappybatpal**
[FEATURE][WIP][INPUT WANTED]

## About the PR 
Adds 3d glasses and a red tier civilian loot crate version with xray vision.
Sprites by Gannets!

image

## Why's this needed? 
Xray vision is a very interesting bioeffect but it's hard to get hold of. Civilian red crates only have a skateboard or frogsuit with jumpy so this seemed like a good place to add a second gene ability giving item.
This also gets a cosmetic version with no gene effect added to the trinket list and clothing vendor.

## Changelog

```changelog
(u)Flappybat
(*)Added 3D glasses to clothing vendor and trinkets plus a working xray specs variant in red tier civilian loot crates.
(+)Sprites by Gannets.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
These have logic to avoid removing an xray gene. This will fail if you somehow get the gene while getting the glasses. I don't think there is currently any way to handle that situation.

I need to make these slightly more available to prevent them being too rare.

**Comment by Flaborized** [comment]
isn't this just a better version of the advanced thermal scanner traitor detectives can buy? the one that lets you see people through walls (also in surplus crates i think)

I like the sprites and think they're a fun vanity item outside of the traitor item being a direct upgrade to an existing traitor item

**Comment by predmetparfuyit86** [comment]
> isn't this just a better version of the advanced thermal scanner traitor detectives can buy? the one that lets you see people through walls (also in surplus crates i think)
> 
> I like the sprites and think they're a fun vanity item outside of the traitor item being a direct upgrade to an existing traitor item

the advanced thermal scanner is kinda useless tbh

**Comment by Flaborized** [comment]
> > isn't this just a better version of the advanced thermal scanner traitor detectives can buy? the one that lets you see people through walls (also in surplus crates i think)
> > I like the sprites and think they're a fun vanity item outside of the traitor item being a direct upgrade to an existing traitor item
> 
> the advanced thermal scanner is kinda useless tbh

its still pretty sloppy to have an items that completely functionally surpasses it instead of either removing the weak item or making the weak item stronger imo 👁️ Plus I think seeing people through walls is at least *cooler* than having full x-ray, leads to some interesting interactions based on what you can't see.

**Comment by alexeric123** [comment]
From what I remember, old thermals were removed?

**Comment by alexeric123** [comment]
> isn't this just a better version of the advanced thermal scanner traitor detectives can buy? the one that lets you see people through walls (also in surplus crates i think)
> 
> I like the sprites and think they're a fun vanity item outside of the traitor item being a direct upgrade to an existing traitor item

From what I remember, old thermals were removed?

**Comment by flappybatpal** [comment]
Tested with the advanced thermal scanner to see how they compare.

Advanced thermal scanner
- Shows people as fully visible in darkness
- Acts as night vision, a light source other players can't see
- Shows cloaked people
- Shows people through walls

Xray
- Shows people/room through walls at their regular brightness
- Can see through smoke/fog

Admittedly seeing cloaks is really situational. Thermal needs dark rooms for it's benefit.

**Comment by Flaborized** [comment]
the reason traitor thermals are weak to flashes is so that people can't flash people wearing thermals to 'check' if they're evil thermals. I still think as an item the full-x-ray glasses pretty much fills the purpose/niche of the traitor thermals and does it just Better. Also correct me if I'm wrong but I remember the x-ray mutation showing cloaks? Though it's been a while

**Comment by flappybatpal** [comment]
I tested it and it couldn't see a cloaking device on my dead body.

**Comment by flappybatpal** [comment]
I've removed it from syndicate loot and put it in the red tier civilian loot crate. This is the same boxes that can get you jumpy gene frogsuit, voltron, teleport wand, hermes sandals etc.

Civilian red only had frog suit or skateboard so I think it would be a nice addition.

**Pull request closed without merging**
