### PR TITLE
Allows hacked clothing manufacturers to print handkerchiefs

### PR DESCRIPTION
**Pull request by Bartimeus973**
## About the PR 
Hacked clothing manufacturers now print handkerchiefs at a cost of 0.4 fabric for white handkerchiefs, and 0.6 fabric for colored ones.

## Why's this needed? 
There is currently no reliable way to get handkerchiefs apart from the spacebux purchase (which is random) or being an ntso.
Allows players to pick a handkerchief they like without resorting to randomness. Also makes https://github.com/goonstation/goonstation/pull/12079 better by allowing it to make handkerchiefs you like reliably.

## Changelog 

```changelog
(u)Bartimeus973
(+)White handkerchiefs can now be printed at hacked clothing manufacturers. You can color the handkerchiefs with paint. 
```

### CODE REVIEW

**Review by frawhst — APPROVED** [review]

**Comment by BatElite** [comment]
Feels like this'd make the spacebux thing superfluous; I'm curious what flourish thinks of it.

**Comment by Bartimeus973** [comment]
It does make it slightly less useful, but it does save you the trouble of having to find a multitool and hacking a clohing manufacturer. I'll request a review from flourish.

**Comment by flrsh** [comment]
I really like your bandana PR, but I'd like the handkerchief spacebux purchase to remain meaningful. What about only white handkerchiefs? One thing Pali suggested was letting the paint color of handkerchief transfer to bandanas. Which I think would allow some extra variety with colors, but still encourages you to buy one with spacebux if you want a fancy pattern.

**Comment by Bartimeus973** [comment]
Very well! I'll do so! White handkerchifes it is.

**Review by flrsh — APPROVED** [review]

**Pull request merged**
