### PR TITLE
Rework clown shoe slipping

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
* Reworks clown shoe slipping to be more forgiving and less miserable.
* Lowers slip weakened times
* Causes you to actually fall over when you slip instead of just awkwardly being unable to take action for 5 seconds
* Removes old defunct check for sec helm that looked at the wrong type path anyway

## Why's this needed? 
* Make clown more enjoyable to play
* Make slipping actually slip you
* Remove old garbage code that did nothing

## Changelog

```changelog
(u)Sovexe
(+)Reworked clown shoes to have shorter slip durations. Fixed a bug where slipping as a clown didn't actually make you fall over.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Can we have a cooldown too?

**Comment by Sovexe** [comment]
> Can we have a cooldown too?

The time between slips already seemed pretty significant, I'm not sure if a cooldown would have much effect

**Comment by Tarmunora** [comment]
would it suck too much if it made you slip like how other slips worked (speed-dependent with a throw etc)

**Comment by Sovexe** [comment]
> would it suck too much if it made you slip like how other slips worked (speed-dependent with a throw etc)

I feels more jarring but sure

**Comment by Tarmunora** [comment]
> It feels more jarring but sure

If it feels bad don't do it 🤷

**Comment by Sovexe** [comment]
> > It feels more jarring but sure
> 
> If it feels bad don't do it 🤷

honestly it could go either way, slipping probably makes the most sense to be consistent

**Pull request merged**
