### PR TITLE
Updates Arcfiend's Sap Ability Description

### PR DESCRIPTION
**Pull request by Wisemonster**
[QoL]

## About the PR 
Updates the description of the sap ability

## Why's this needed? 
Apparently it can be used on people? This clarifies that.

### CODE REVIEW

**Comment by Sovexe** [comment]
entity = person

**Comment by Wisemonster** [comment]
The problem with using entity to mean person is that it's very vague. For example, if the AI said "There are entities in the bridge" would you know what the AI was talking about? It could be talking about beepsky for all we know.

**Comment by Wisemonster** [comment]
> entity = person

If you're asking to replace entity with person, I could do that, although I think sap can be used on entities like fire elementals.

**Comment by Wisemonster** [comment]
Ok, I can't really find anything that sap can be used on that doesn't fall under person or machine, so I'm just removing reference to entity from the abilities description.

**Pull request merged**
