### PR TITLE
Changeling radio mimic now changes hover tooltip of fake radio icon

### LINKED ISSUE #12605: Changeling Phony Radio can be detected
### Labels

[BUG][MAJOR]

### Description

Hovering over the name of a phony Ling radio shows the true headset used

### Steps to reproduce

1. Have a Changeling send a voice changed radio message through a Research Director headset, using the ability to make it sound like a different headset
2. Hover over the name of the person that sent the phony message, showing a popup that reveals the true headset used to send the message
3. Kill the antag and win the game forever!!! fart on face too

### Expected Behavior

Hovering over should show the headset the Changeling intended to show, rather than the true headset

### Additional Information & Screenshots

Reported by: Mintyphresh
On server: Goonstation 4 Roleplay: Sylvester
Round log date: 2023-01-02-04-02
Reported on: 2023-01-02 04:59:31
Map: CLARION

### PR DESCRIPTION
**Pull request by soleilan**
## About the PR 
Moved the list of possible jobs to mimic to a var outside of the proc, key for the icon_override coupled with respective hover tooltip values. Should be easier to read and add/remove jobs that can be mimicked over radio.  
Mimic voice ability will now temporarily change the hover tooltip text and revert it as expected.

~~omg why cant they mimic a det or miner or radio host~~

[tooltip yay.webm](https://user-images.githubusercontent.com/111906440/222355457-7e79716a-be82-4acc-99a9-eef0392e48d1.webm)

## Why's this needed? 
Fixes #12605, weird oversight, stealth good

### CODE REVIEW

**Comment by soleilan** [comment]
wait hold on, why dont i just swap the key and values so the selection menu uses the job names

**Comment by soleilan** [comment]
image
:)

**Comment by TobleroneSwordfish** [comment]
may as well add the missing ones while you're at it, pretty sure they're only missing because they were added after mimic voice:
"nt" - NTSC
"rh" - radio show host
"det" - detective
"Min" - miner (yes it's capitalised, no I don't know why)
"mail" - mailman

**Comment by soleilan** [comment]
job's done 👍

**Pull request merged**
