### PR TITLE
Adds a new antag type to mixed, Arcfiend

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
* Adds a new antagonist type, the Arcfiend
* 10% chance to spawn 1 arcfiend in mixed and mixed rp. This number will be adjusted as we evaluate how the role plays out in normal rounds

Abilities....
* Sap Power - Drain power from a target entity or machine
* Discharge - Run a powerful current through a target in melee range damaging mobs and depowering doors
* Flash - Release a sudden burst of power around yourself disorienting nearby foes
* Arc Flash - Unleash a ranged bolt of electricity that chains to nearby targets with reduced damage
* Polarize - Unleash a wave of charged particles polarizing nearby mobs giving them magnetic auras
* Ride The Lightning - Expend energy to travel through electrical cables
* EM Field - Radiate electromagnetic waves disrupting nearby electrical signals such as radio communications for 30 seconds
* Jolt - Charge up and release a series of powerful jolts into your target, eventually stopping their heart
* (Passive) Energy Storage - Store up to 2000 energy to use with your abilities
* (Passive) SMES Human - Immunity to most electric based attacks, identical to the gene

## Why's this needed? 
* Fun

## Changelog

```changelog
(u)Sovexe
(*)A new antagonist type, the Arcfiend joins the fray. Be sure to enable it in your job preferences to be amog the first to play!
```

### CODE REVIEW

**Comment by Azrun** [comment]
I had thought a fire elemental equivalent with abilities like sap, ride the lighting, arc flash would be cool. This is... so much more.  Awesome.

**Comment by zjdtmkhzt** [comment]
Can't wait to see how the Polarize ability will work out! ^^

**Comment by millicentjwi** [comment]
i suggest a rename to avoid confusion with the other kind of vampires and better shorthand names for them (better than evamp)
heres a few ideas
sapper
drainer
energy eater
power soaker
electrical sponge
voltage sycophant

**Comment by WALPVRGIS** [comment]
Love the idea of this, and that new name rules omg. Can't wait to catch seeing one ingame :0

**Comment by millicentjwi** [comment]
excellent new name

**Pull request merged**
