### PR TITLE
Reworks Chess + Adds Board Game Clocks

### PR DESCRIPTION
**Pull request by DisturbHerb**
[FEAT][OBJECTS][REWORK][TGUI][WIKI]

## About the PR
This PR introduces a new framework for building tgui-based board games and includes the implementation of **chess and draughts boards**. The interface has been redesigned with a smooth and intuitive design to make playing these games a more enjoyable experience for players of all skill levels.

An image of the chess board interface.

With a new smooth interface, playing chess and draughts will hopefully be a more enjoyable experience. The interface has been redesigned from the ground up to provide a more intuitive and user-friendly experience for players of all skill levels.

A gif of chess pieces being moved

You can currently select between two setups for the board, chess and draughts. More will come later!

A gif showing how the preset buttons work

---
**Boardgame Framework Details**

The framework provides a simple and intuitive way to create new boards. Developers can define custom board sizes and styles, including a built-in checker pattern. More styles can be easily added to the framework to support a wide range of board game designs.
Code of a board game example

The framework also allows for custom styles to be applied to the board, enabling developers to create unique and personalized games.
Different styles that can be applied to a board

Additionally, the framework provides a range of procs that can be overridden to customize how the pieces interact with each other, allowing for even greater flexibility and customization.
Multiple procs that can be used and/or overrided
Overall, this PR aims to provide a powerful and versatile framework for building and playing tgui-based board games.

---

**Game clocks** are also introduced in this PR. Designed for two-player competitive games, they are devices which track the amount of time elapsed on both player's turns, and can be used where time controls are desired.

An image of the game clock interface.

The **game clock** is fully featured with the ability to set both timers independently, show the winning side when one player flags, and the orientation of the clock can be flipped client-side to suit the needs of the player.

Both of these items are presently available from the gaming vendor for purchase. All the equipment introduced in this PR is fully silicon-interactable at range, so even the station's AI can beat you at chess.

Friends not included.

## Asset Credits
This PR introduces a few sounds, as credited:

- "knock-wood-4times.aiff" by stereostereo at https://freesound.org/people/stereostereo/sounds/124537/ (CC BY 3.0) (Edited from original)
- "Switch ON - Livingroom.wav" by MastersDisaster at https://freesound.org/people/MastersDisaster/packs/13813/ (CC BY 4.0)

All other sounds are the original creations of the authors of this PR.

## Future plans
- As this PR is projected to make the prior game kits obselete, in the future we'll path-replace all instances of game kits with the new chess boards once this PR is merged.
- Additional board games (such as go and xiangqi) are planned, and there already exist icons for these in `boardgame.dmi`.
- Re-introduction of the import and preset modal along with GNot (a bespoke notation system for board positions).
- for the love of god make those clock animations look better
- fix klepto interactions?
  - thanks #12391

## Why's this needed?
These changes represent a massive increase in the quality of life of those who want to enjoy these classic games on Goon; making large scale tournaments and the like possible. This PR is only the first step in introducing more tabletop games to Goon, and the framework in place may have other useful applications.

obligatory tgui good

## Changelog 

```changelog!
(u)DisturbHerb + Grokberg
(*)The NanoTrasen Recreational Appropriations Committee has secured funding to upgrade the quality of crew entertainment in its stations. Chess boards and game clocks have been made available at gaming vendor machines, and a further rollout of the new equipment is anticipated in the near future.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
whoever wrote #4288 must be quivering in their boots

**Review by virvatuli-gh — APPROVED** [review]
All the sound stuff looks and sounds fine to me. What's the deal with `Wood_paT.ogg` though? I don't see it being used anywhere (unless I missed it) and it's just a reversed file of `Wood_Tap.ogg` which can be done with code if needed. Thanks for remembering the sound cache!

**Comment by ruben-svensson** [comment]
> All the sound stuff looks and sounds fine to me. What's the deal with `Wood_paT.ogg` though? I don't see it being used anywhere (unless I missed it) and it's just a reversed file of `Wood_Tap.ogg` which can be done with code if needed. Thanks for remembering the sound cache!

God damn, forgot to remove it, was testing a remove sound effect for pawns. Fixing that.

**Comment by DisturbHerb** [comment]
!merge_upstream

**Pull request merged**
