### PR TITLE
Stops borg fire extinguishers from melting

### LINKED ISSUE #6757: Cyborg fire extinguisher can be destroyed
### Labels

[BUG]

### Description

Cyborg fire extinguisher just like normal fire extinguishers but unlike them are hard to replace

### Steps to reproduce

1. empty the fire extinguisher
2. add a chemical that will melt it (e.g. phlogiston)
3. use it
4. done

### Expected Behavior

it not melting

### Additional Information & Screenshots

in my opinion,  just use the generic clog message for all blacklisted chems if the user is an android as a fix

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BUG]
## About the PR 
Fixes #6757

## Why's this needed? 
Seems bad to delete a part of a cyborg's module because they clicked on a sabotaged tank. Also thank you `]gh randomissue`

### CODE REVIEW

**Review by ZeWaka — APPROVED** [review]

**Comment by ThatFiveGuys** [comment]
Does this allow borgs to bypass chemicals that would normally be blacklisted and use them?

**Comment by ZeWaka** [comment]
> Does this allow borgs to bypass chemicals that would normally be blacklisted and use them?

No, it just adds any reagents that would melt the extinguisher to the blacklist

**Comment by ZWRh3** [comment]
i think this doesnt fix certain special custom melts eg. clf3 + black powder extinguisher going boom

**Comment by TobleroneSwordfish** [comment]
> i think this doesnt fix certain special custom melts eg. clf3 + black powder extinguisher going boom

it does now!

**Pull request merged**
