### PR TITLE
Movable toilets!

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
[FEATURE]

## About the PR 

Makes toilets able to be un-anchored by using a screwdriver or a wrench on it, you can anchor them back in place by using the wrench or screwdriver again.

## Why's this needed? 

Stealing a toilet is just way too funny and someone requested it on discord.

### CODE REVIEW

**Comment by Sovexe** [comment]
If we're going to let toilets move again I'd want a flush delay added. Spamming toilet flush noises is bad

**Comment by Carbadox** [comment]
Did you test this on a local server? Would be worth confirming whether or not the two attackbys (one for stuffing items and one for unanchoring) override one another

**Comment by MatheusIsNotAvailable** [comment]
It works, you use a wrench/screwdriver on it and it unbolts/bolts it, you won't be able to put them inside toilets anymore though.

**Comment by geneva-breaker** [comment]
Without any sort of cooldown this becomes a portable instant evidence destroyer. Or a grief machine. Drag a toilet into medbay and flush all the supplies in 60 seconds. 

Kind of screws the balance of Bathrooms as "very public but still desireable" places to spawn in traitor gear. 

My gut feeling is strongly opposed to this and I'll whinge about it.

**Comment by MatheusIsNotAvailable** [comment]
Closing because I am not attached enough to this idea to keep improving on it. <3

**Pull request closed without merging**
