### PR TITLE
Fixes typo in clown bananna job reward description

### LINKED ISSUE #10016: Clown Reward for Bananna gives a regular Banana
### Labels

[TRIVIAL]

### Description

When you activate the level 20 Bananna reward you get a regular banana instead of the Bananna

### Steps to reproduce

-Be a level 20 Clown.
-Claim the Bananna Reward
-Examine the Reward.

### Expected Behavior

Be given a mispelled Banana instead of a regular banana

### Additional Information & Screenshots

https://i.gyazo.com/34c1b46f36dcf87f455d811830bd6243.png

Reported by: EristheSlackWyrm
On server: Goonstation 4 Roleplay: Sylvester
Round log date: 2022-08-01-20-04
Reported on: 2022-08-01 21:29:23

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Changes the description of the level 20 clown reward to say "Bananna, but misspelled!" instead of "Banana, but misspelled!"

## Why's this needed? 
Fixes #10016

### CODE REVIEW

**Comment by BatElite** [comment]
I'd think the description was referring to the name of the reward and not the banana in question

**Comment by ThatFiveGuys** [comment]
> I'd think the description was referring to the name of the reward and not the banana in question

The name of job rewards is the reward itself in all cases, its weird to have both the reward and description just lie to you (and while kyle didnt remember why it was like this im pretty sure wasnt intentional). While it would be easy to make the reward give you what it says it gives you i think this is a funnier solution.

**Review by frawhst — APPROVED** [review]
remove the `return` at the end of `activate()` and I'll merge this :^)

**Comment by ThatFiveGuys** [comment]
Done!

**Pull request merged**
