### PR TITLE
Standardises The Nadir Armoury

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Mapping] [Balance] [QoL] [Add To Wiki]

## About the PR:
See initial PR: #10917
Slightly expands the Nadir Armoury, adding a phaser crate, two night vision goggles, one airlock breaching sledgehammer, and one N2O canister. As a result, the adjacent bathroom has been contracted slightly.

image

When being compared to the [standardised equipment list](https://hackmd.io/@Mister-Moriarty/BkmMgDLZs), the Nadir Armoury also possesses:
* 2x Riot Launchers
* 2x 40mm Smoke Shells
* 1x Stinger Grenade Box
	* 7x Stinger Grenades
* 3x Crowd Dispersal Grenades
* 5x Flashbangs
* 3x Emergency Auto-Injectors (Atropine)

And **lacks**:
* 1x Pod Weapons Crate
	* 2x Mk.3 Disruptors
	* 2x Mk.2 Scout Lasers
	* 2x 40mm HE Pod-Seeking Shells

## Why's this needed?
Armouries really should be standardised as to contain the same basic equipment as each other, while also being distinct in their own unique ways. Nadir specifically does not need a pod weapons crate, as the map does not possess pods or submarines.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)Standardised Nadir's Armoury.
```

### CODE REVIEW

**Comment by Kubius** [comment]
Good catch on the pod weapons crate; while it's not strictly out of the question that they'll return in future, the crate is definitely not needed right now.

From what I can see of the adjustment to the adjacent bathroom, I'm not a particular fan of it; expanding the Armory south instead and adjusting the position of the auxiliary communications dish is still snug, but it moves the snugness into a non-room space instead of a room space.

image

An extension downward like this (this is just a rough rip, of course) does still preserve the double layering of reinforced walls; it's technically a little easier than before because you'd no longer need to go through the bathroom to avoid acid and the walls are more consolidated, but it's still more robust than Oshan's protection.

**Comment by Kubius** [comment]
Looks good overall - giving this the thumbs up. One minor thing is that the Armory area might now reasonably stretch down to the edge of the breach hull hall since it's one contiguous wall now, but that's entirely pedantic.

**Review by Kubius — APPROVED** [review]

**Review by Kubius — CHANGES_REQUESTED** [review]
Sorry for borking this, but the PR size change indicates that map merge may have worked incorrectly. You may need to copy a clean Nadir from master and move your changed armory into it.

**Comment by Mister-Moriarty** [comment]
> Sorry for borking this, but some other fixbatches significantly altered the map and PR size change indicates that map merge may not have done enough. You may need to copy a clean Nadir from master and move your changed armory into it.

I'm afraid that this is what I attempted to do in [a39bc10](https://github.com/goonstation/goonstation/pull/11592/commits/a39bc100bee266e2cae95382c62f5ca358fd12a9) to no avail; I excised my armoury changes into a 7x12 temporary map file, and copied `Nadir.dmm` from `master` into the PR branch, then pasted my changes from the temporary file back into `Nadir.dmm`.
The above, in conjunction with a _very_ brief skim over the changes, lead me to believe that the large number of changed lines are a result of SDMM saving the map file in a different configuration; the contents are the same, just in a different order.
Reviewing this is going to be painful.

**Comment by Kubius** [comment]
If you'd like, you could send me the armory snippet on its own and I could integrate it into a subsequent fixbatch, to cut down on the fuss. Elsewise, let me know how I can help.

**Pull request closed without merging**
