### PR TITLE
Playable pugs

### PR DESCRIPTION
**Pull request by flrsh**
## About the PR 

This PR adds playable pugs. 

image
https://streamable.com/e/57663b
https://streamable.com/e/zgntqw

The pug trait costs 4 points, as pugs are intended as a challenge mode for players who’d like to show off their prowess. 

On the assets side of things, this PR adds:

- Extremely cool and distinctive pug sprites (by Flaborized!)
- Pug talk, scream (or rather, growl), sneeze, sniff, snore, and wheeze SFX 
- Pug sneeze and snore animations

Along with the high quality sprites and SFX, pugs also:

- Are poisoned by chocolate
    - Spaceacillin helps shorten the poisoned effect
- Take 2x oxy damage
- Are able to sprint til they run out of stamina and flop over
- Have a small chance of reflexively throwing themselves towards thrown objects 
    - This is hilarious and you should try it with your local pug. Preferably over a glass table.
- Have a tiny chance of dislocating an eyeball every time they sneeze 
- Spawn with an exclusive dog biscuit that gives them strong food buffs
- Have a special *sleuth emote, which lets them investigate things using their keen sense of smell
    - Pugs smell color (this is canon)
    - Using *sleuth on a mob will tell the pug what color the mob smells like
    - Using *sleuth on an object will tell the pug the color of one of the people that interacted with it and a general idea of how long ago
    - Using *sleuth over and over on the same object will uncover all the colors of the people that interacted with it
    - Pugs cannot *sleuth when they’re poisoned by chocolate
- Have some other cool easter eggs that you really shouldn’t code dive for!

Pugs are the joint effort of many different people. Aloe, Flaborized, mbc, and I worked on the assets and implementation, but many others also contributed their ideas and suggestions!

## Why's this needed? 
We’ve wanted pugs for over a year and a half now. Now they’re finally here! :shelterfrogmasagain: 

## Changelog
```changelog
(u)Aloe, Flaborized, Flourish, and mbc
(*)Added playable pugs. The pug trait costs 4 points, as pugs are intended as a challenge mode for players who’d like to show off their prowess. Check out the PR page for full details.
```

### CODE REVIEW

**Comment by flrsh** [comment]
I will be merging this as soon as the checks pass (or don't pass, given Github's issues today). Pugs have been tested and signed off by many admins on the team. The purpose of making this a PR is just so players can access all the important info about pugs in a central location.

**Comment by Gannets** [comment]
🐶

**Comment by mopcat** [comment]
so, is it any coincidence you put this up during the massive outage so that there's little chance of anyone complaining about this absolute dogshit (heh) PR due to diminished access to github? or is that just a conspiracy theory? do let me know, i'm genuinely curious.

**Comment by zjdtmkhzt** [comment]
Pun or no pun, and regardless of your opinion on the PR, that is a very rude thing to say,

**Comment by mopcat** [comment]
i realize that i probably should have said why i dislike this in a more concise and less rude manner. let's see...
-no reason for players to actually play this other than sheer masochism, considering the sheer amount of downsides for FOUR POINTS
-appears to be a thinly-veiled attempt to both make fun of dogpeople and the people who want an actual dogperson race, and create a new target for bullying in the game, as highlighted by one point in the pr literally encouraging players to try to make pugs throw themselves into glass tables. we already have clowns. and they're good enough targets for light bullying, we really don't need more.
-ALSO making fun of how unhealthy pugs are as a breed in real life. i have no problem with dark comedy but there comes a point where it gets too dark to be funny, and i'd say making fun of animal abuse and decades of inbreeding crosses that line. you wouldn't point a finger at a dog literally sneezing its eye out and say "look!! its funny because this dog sucks! please laugh!", and making it part of a funny fart clown game doesn't make it any funnier and less appalling, but who knows, maybe my standards are too high or too picky. as someone who finds farting on clowns while they burn to death "funny".
-really just... does not fit the game. i can't for the life of me grasp for a reason why this fits SS13, or why anyone would want this. i'm sorry, i just don't see the point, i don't see anywhere where it meshes well with the game other than an attempt at dark comedy which just. is not funny.

**Comment by mopcat** [comment]
i also want to point out that i'm nowhere close to mad because it's a furry race. i'm one of those people who always stood by adding more races and features and QoL for existing races! this is a "furry" race that goes against everything i'd want out of a "furry" race. it's dumb. it's got downsides upon downsides piled onto with a few half-baked benefits, it makes fun of how some dog breeds are so inbred that their existence is plagued with health issues. and it not only costs trait points, but it has the highest trait points in the game. i cannot wrap my head around any reason for adding this other than having a new "bullying target" in the game other than clowns and to make fun of the people who like furry stuff and want to see more "furry" mutantraces in the game.

**Comment by mopcat** [comment]
and i get that you've "wanted to add this for a while". there's a lot of things people have wanted to add for a while. like... a lot of the PRs that have been rejected for arbitrary or personal reasons. or atmos that isn't shit. or mutantraces that aren't shit. or an engine (as in, a power source, not what the game runs on) that isn't shit. that's not a justification, sorry, so don't even try it.

**Comment by mopcat** [comment]
one more thing i forgot to mention: _this definitely feels like it's leaning into that "fantasy racism" shit i thought you guys wanted to get rid of_. no thanks.

**Comment by TobleroneSwordfish** [comment]
Instantly self merging a gameplay affecting PR that people are actively discussing doesn't look great, especially during #6548
Also, pugs...?

**Comment by flrsh** [comment]
I was going to respond to your comments, but -

> one more thing i forgot to mention: _this definitely feels like it's leaning into that "fantasy racism" shit i thought you guys wanted to get rid of_. no thanks.

Just makes you look incredibly ridiculous. No one's being racist or encouraging racism against pugs. If you think I'm actually, genuinely, encouraging people to go around randomly griefing pugs just because they're pugs, you need to take a hard look at yourself and reorient. 

Given that you've been banned from the Discord for being incredibly toxic, and are continuing to be toxic here, I'm going to block you from the Goonstation org.

**Comment by flrsh** [comment]
> Instantly self merging a gameplay affecting PR that people are actively discussing doesn't look great, especially during #6548 Also, pugs...?

Part of why we have a feature freeze in the first place is so devs can work on their own stuff. Also see my earlier comment about making a PR just so info's all in one place. I could've just straight pushed to master.

**Comment by ZeWaka** [comment]
> mopcat: and i get that you've "wanted to add this for a while".

> TobleroneSwordfish: Instantly self merging a gameplay affecting PR that people are actively discussing doesn't look great, especially during #6548 Also, pugs...?

This has semi-not-actively been worked on for over a year and a half now.

**Comment by TobleroneSwordfish** [comment]
> This has semi-not-actively been worked on for over a year and a half now by multiple devs.

fair enough, just looks weird if you haven't seen that I suppose

**Comment by pali6** [comment]
For all the people downvoting the feature freeze explanation can I ask what the point of feature freeze is in your opinion?

**Comment by SirSnek** [comment]
PR feedback:
-I understand that you have worked on this for over a year and a half but almost instantly closing the PR is still a bit weird as it's clearly a pretty controversial PR and even if you insist on merging it you should probably keep it open for an hour or 2 and address the problems and then merge it.
-Weren't we supposed to stop adding animal mutantraces? The most common argument against adding some races is that they're existing animals and we don't want more of those. (Once again I get that it took over a year to make but you could have looked back at it and tried to rework it into a different creature, maybe a canine one so you can reuse some parts like the pug appearence!)
Gameplay feedback:
-The eyeball sneeze thing seems unnecessary and weird. It's not funny at all so I don't see that as a possible reason for including it.
-The race seems to have zero customization which is pretty bad, even if players could shade a part or 2 of the body slightly it'd be nice, it's important that you can tell people apart at a glance.
-The noises seem grody and feel pretty uncomfortable? I really do not like them and would not want to hear that throughout the entire round.
-The 4 trait point cost is huge. To get it you need to either take puritan and one other negative trait or three negative traits. I feel like this will draw a lot of players away because of the point commitment. Because of the large trait cost you also can't take many positive traits to make your character more interesting! iirc the max trait amount is 6? So in the best scenario we take pug, puritan, 1 bad trait and with this we can only get 1 positive and negative trait + 1 neutral if we want that. 
-I get that you want to make it a "hard mode" race but the downsides are just weird if you want to make that. Doubled oxy damage is a big downside but that's pretty much the only notable downside. Chocolate poisoning is... fine mechanically but will almost never be seen. It also brings some awareness to the fact chocolate is bad for dogs and that's good. The throw thing is okay but extremely situational.
-I do want to say that I find the running out of stamina and falling over aspect funny.
-The sleuthing feature is actually really cool and interesting plus it will actually be useful and semi common since it's just an emote!

**Comment by LadyBirb** [comment]
> For all the people downvoting the feature freeze explanation can I ask what the point of feature freeze is in your opinion?

I was assuming it was so we could focus on bugfixing and balancing existing features.

**Comment by pali6** [comment]
> > For all the people downvoting the feature freeze explanation can I ask what the point of feature freeze is in your opinion?
> 
> I was assuming it was so we could focus on bugfixing and balancing existing features.

Partially (well, balance was never stated as one of the reasons afaik) but multiple reasons were stated when talking about the code freeze, one of which was developers wanting to finish their own projects instead of focusing on reviewing PRs. (Because reviewing PRs often takes up most of developers' time these days so we don't get to add as much of our code as we'd like.) Apologies if there was confusion about the goal of the "event".

**Comment by flrsh** [comment]
> I understand that you have worked on this for over a year and a half but almost instantly closing the PR is still a bit weird as it's clearly a pretty controversial PR and even if you insist on merging it you should probably keep it open for an hour or 2 and address the problems and then merge it.

Is it really "controversial" if the majority of the downvotes are from either those who are banned from the Discord for being toxic or those who don't play and only hang around to handwring about every single change that they don't like? This is even ignoring the fact that reception on Discord has been largely positive.

**Comment by Yellow-Mushroom** [comment]
I really don’t mean to sound nit picky but pugs just in general make me very depressed to think about (most their life is attempting to ease the suffering of not being able to breath/having their parts be too big for their head) and after having observed a video of a pug eye popping out, I really dislike that feature as these creatures don’t ask to be born into a malformed & painful body, but are instead bred into a market of people who buy pugs and cause more of them to be made with progressingly unhealthy features.

Some aspects I do enjoy a lot is the sniffing mechanic, that’s unique as hell and props to whoever came up with that and got it working. 

While I don’t like the idea of the “mutant race is MADE to be hard to play” as opposed to “mutant race has a harder time being on station as the station isn’t designed for them”, I do think the idea of more taxing traits (such as the pugs -4) is a good direction, as all our traits currently range from -2 to +1 (iirc)

**Comment by LadyBirb** [comment]
After thinking on it for a bit, I feel like the changes that should be made are removing the eyeball-sneezing and chasing-thrown-objects mechanics and changing the cost to -2 instead of -4. The current implementation,  I can't really say it better than it just gives me bad vibes, like thinking about it just gives me a bad feeling in my chest. tbh I dislike the idea of "hardmode" races in general when if you want hardmode you can already just take a bunch of negative traits with no positives and set clown to favorite.

**Comment by flrsh** [comment]
> and after having observed a video of a pug eye popping out, I really dislike that feature 

Fair, others have also expressed similar sentiments. It's been removed and replaced with pugs being able to smell exactly who has apocrine enhancement/poor hygiene, I'll update the PR description to reflect that accordingly.

**Comment by Momoberry** [comment]
I like it! I think some of sfx are a bit loud, though. But I haven't interacted with them in game for myself yet, so it could just be goonstation sound being super loud when there's nothing else making sounds, like in the video. Specifically the 2nd sound in this. The others are fine, that "Aow!" one really throws me off. "https://streamable.com/e/57663b"

**Comment by Yellow-Mushroom** [comment]
I mean, have you heard a pug? Poor inbred creatures can be heard grunting and struggling to breathe from rooms over.

**Comment by optimumtact** [comment]
Now this is what I call features

**Comment by BigManMassive** [comment]
I like this a lot.

**Pull request merged**
