### PR TITLE
Add a stove to the kitchen in Destiny, also move the intercom

### PR DESCRIPTION
**Pull request by Josephin23**
## About the PR 
Adds a stove to the kitchen in Destiny on the tile where the hotdog stand used to be, subsequently moved it next to the lockers. The intercom was moved to behind the chute due to it being covered by the APC.

obraz

Also, this is my first PR so if i screwed anything up say so and i'll fix it.
## Why's this needed? 
There's a stove on (almost) every active map, there's no reason as to why it should be excluded on this one, especially when making soup is such a major part in the work of a chef.

## Changelog

```changelog
(u)Josephin23
(+)Added a stove to the kitchen in Destiny, also moved the intercom.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
why is the intercom on the apc

**Comment by Josephin23** [comment]
> why is the intercom on the apc

Didn't touch that, it's just like that for some reason. 
obraz

**Comment by Josephin23** [comment]
woops, ignore that

**Comment by ZeWaka** [comment]
can you move it to behind the chute?

**Comment by Josephin23** [comment]
sure enough

**Pull request merged**
