### PR TITLE
Makes the HoP and HoS uniforms more visually distinct.

### PR DESCRIPTION
**Pull request by DimWhat**
[Sprites]
## About the PR 
Changes the HoP's uniform to be more of a unique design than the HoS, which shares a similar sprite aside from color. Also changes the HoS dress to be more similar to it's original uniform.
Before:
image
After:
image

## Why's this needed? 
The HoP uniform is a recolor of the HoS uniform, I think they should look different as they are two entirely different heads.

## Changelog
```changelog
(u)DimWhat
(+)Made some sprite changes to the HoP uniform and dress as well as the HoS Dress.
```

### CODE REVIEW

**Comment by Flaborized** [comment]
I like this, don't like flat recolors for clothing items overall and more distinctions is good imo

**Comment by BatElite** [comment]
HoS getting the short end of that one, appropriately

**Comment by Crackaduck** [comment]
I don't think it needs a resprite, they're already distinct in color and pattern, the biggest change appears to be making the suit version have the same upper body as the dress version, and making the hos's dress upper body the same as the male version. un needed and removes some of the uniqueness of the dress compared to the suit option in my opinion.

**Review by Sovexe — APPROVED** [review]

**Review by flrsh — APPROVED** [review]
Rip HoS.

**Pull request merged**
