### PR TITLE
Ports paper formatting help tooltip from BeeStation

### PR DESCRIPTION
**Pull request by ZeWaka**
[feature]

## About the PR 

by PowerfulBacon of BeeStation
BeeStation/BeeStation-Hornet/pull/2035

image

## Why's this needed? 

it good

### CODE REVIEW

**Comment by Sovexe** [comment]
Do we need to update the license header?

**Comment by ZeWaka** [comment]
> Do we need to update the license header?
they didn't

**Comment by Fikou** [comment]
:trollface:

**Comment by Qustinnus** [comment]
it's about time you caught up to tg

**Comment by ZeWaka** [comment]
> it's about time you caught up to tg

tg doesn't have this, rekt

**Comment by ZeWaka** [comment]
> image

yeah that doesn't have the help tooltip which this PR is specifically about you buffoon

**Comment by Qustinnus** [comment]
tldr

**Pull request merged**
