### PR TITLE
Mechanic headset

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
Adds a dedicated headset for mechanics

## Why's this needed? 
Seems odd to be the only engineering subdepartment w/o one, also a significant difference between mechanics and what they were identifying themselves as on the radio

## Changelog

```changelog
(u)CheekyBrdy
(+)Mechanics now have mechanic headsets instead of engineering headsets.
```

### CODE REVIEW

**Comment by cheekybrdy** [comment]
Just out of curiosity, is there a reason for no icon variety in medical?

**Review by cheekybrdy — COMMENTED** [review]
Should be a easily visible icon, while still having a good signature light yellow.

**Comment by flrsh** [comment]
It still looks difficult to read to me, please up the saturation / contrast.

**Comment by cheekybrdy** [comment]
should be good now, contrast should be better now

**Comment by flrsh** [comment]
Congrats on your first merged PR! 🎉

**Pull request merged**
