### PR TITLE
Resprites captain spacesuit, adds captain backpack

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Resprites the captain spacesuit to have colors that match the hat (which you're supposed to wear with it), adds a new backpack that the captain spawns with. You can turn it into a satchel, turn it blue, or turn it blue and a satchel. Picture:

## Why's this needed? 
I think it looks better, I want to eventually do departmental backpacks for more departments, starting with the captain cuz they're special and have the most complicated bag of all (it has to be able to turn blue!). 

## Changelog

```
(u)Flaborized
(+)Resprited captain's spacesuit, added captain's backpack.
```

### CODE REVIEW

**Comment by Superlagg** [comment]
Oooh, I like those sprites! The equipped space suit no longer looks like captain-themed footie pajamas, and now suitably like a cross between the armor and a space suit, and the backpack item sprites kinda look like a tacticool military backpack reupholstered for a grown-up preschooler.

However, I think the space suit item could use some more contrast on the edges, mostly around the lower arm pieces, cus they almost look like they're attached to the body.

And the worn backpack sprite could use some narrowing, as it looks like it covers their whole back-area, which to me kinda looks like the captain's wearing a green wicker basket breastplate. Might just be the character's hair or the fact they're not wearing their armor, though!

**Comment by Flaborized** [comment]
Changed front facing cap suit to hopefully be a bit clearer with the arms and shading, I think the backpack ends up looking fine in-game (or it did for me) especially since it sticks out a lot more when viewed from the side (like the regular backpack)

**Comment by twoski** [comment]
i like the backpack but the little dot in the middle feels offputting... especially without much texture in that area, it's just flat. Maybe add some subtle darker green stripes or something to give it more texture?

**Comment by Kyle2143** [comment]
Yes good, fat captain. You trade style for useability.

**Comment by Flaborized** [comment]
Slight touch on backpack, adding a bit of shadow to the bottom of the flap. I want it to look like a more flat surface and more square-like though, since that's the sorta bag that I'm going for-

**Pull request merged**
