### PR TITLE
Cogmap 1 Modernisation & Access Updates

### PR DESCRIPTION
**Pull request by comradef191**
[MAPPPING] [QOL] 

## About the PR 

Big PR that changes many things on Cogmap1, most of which are unnoticeable in standard play

- Access has been swapped over to obj/access_spawn rather than being variables in the doors
- All windows, bar Armoury & AI Defences have been swapped to using `obj/wingrille_spawn/auto`, However, due to the lack of a wingrille spawner for unreinforced windows, unreinforced windows have been left as-is.
- Swapped APCs over to use `obj/autoname_[dir]`, fixed one hallway having two APCs while another has none
- Updated Firedoors to use `obj/firedoor_spawn`
- Removed several instances of windows or firedoors in walls
- Catwalks somehow lost their `simulated/floor/airless/plating/catwalk` turf, added it back like other modern maps.
- Extended the QM Intake belt by 2 tiles, slight QOL Change for big orders

Revamped Engineering Access:
- Engineers no longer have direct access to the AI Upload Foyer, now having a Heads-Level Door between them and the Foyer.
- Engineering Storage and Engineering Dock moved to `engineering_storage`
- Burnchamber, both Loops, Gas Storage, TEG Chamber, PTL & Gas Storage still use `engineering_engine`
- Engineering Power Room & both substations now use `engineering_power`
- The entrance to engineering is now `engineering` rather than `engineering_engine`

- Mining is no longer public via space, added a new disposal chute to the mining shuttle dock so those who are spaced and catch themselves on the mineral magnet can still get inside quickly
- Belt Hell, Cargo Routers & Hanger Bays now have Door-Linked Atmospheric Forcefields

## Why's this needed? 
Cleanliness & Modernity. Brings Cogmap 1 up to using modern standards. Plus some QOL Changes too.

## Changelog

```
(u)Comradef191:
(*) Added Atmospherics Forcefields to Cogmap 1, located at the hanger bays and Cargo Routers.
(+) Revamped Engineering Access on Cogmap 1; Engineers no longer have direct access to the AI Upload Foyer, Engineering Storage and Engineering Dock moved to 'Engineering Storage' Access rather than 'Engineering Engine', Engineering Power Room & both substations now use 'Engineering Power' Access rather than 'Engineering Engine' & the entrance to Engineering no longer requires Engineering Engine access
(+) Mining is no longer publicly accessible via space! Use the disposals chute in the Mining Shuttle Dock if needed!
(+) QM Cargo Intake extended by two tiles
```

### CODE REVIEW

**Comment by TTerc** [comment]
Forcefields, at last
Good, good

**Comment by libbmaster** [comment]
> Mining is no longer public via space

Aw, son of a gun!

Gonna actually have to actually try if I want a jetpack/engi suit as a greyshirt now. :)

**Comment by pali6** [comment]
Probably good changes but also imnotmapper.

**Comment by pali6** [comment]
yolo

**Pull request merged**
