### PR TITLE
Standardize bar & related areas across all maps

### PR DESCRIPTION
**Pull request by Glamurio**
[Catering] [QoL] [Internal]

## About the PR 
Standardizes all bars to utilize the areas `/area/station/crew_quarters/bar` and `/area/station/crew_quarters/cafeteria` more accurately. Mainly, this means that the area enclosed with reinforced tables on all maps is now considered the "Bar", and everything outside of that is the "Cafeteria".

Furthermore, it cleans up many `/area/station/crew_quarters/kitchen/freezer` areas that were erroneously or otherwise marked as `/area/station/crew_quarters/catering`.

It also replaces a few spots with `/area/station/storage/hydroponics`, particularly the ones adjacent to `/area/station/crew_quarters/catering`.

Lastly, specficially on `cogmap2`, it shrinks down the cafeteria to the actual wall cut off and replaces the gap with `/area/station/hallway/primary/northwest`, and it does the same with the southern Medbay Lobby and `/area/station/hallway/primary/southwest`.

## Why's this needed? 
We already have aptly named and utilized areas, but when these maps were made or overhauled the areas were often assembled hastily or without much thought. This makes it both easier to find the specific areas when the game mentions them (Spief, Alerts) and additionally helps improve existing or future logic that specifically targets areas.

### CODE REVIEW

**Comment by pgmzeta** [comment]
you need to add APCs for all the newly split areas

**Comment by Glamurio** [comment]
Dammit I forgot about the damn APCs

**Comment by JORJ949** [comment]
Your version of clarion is outdated

**Comment by Glamurio** [comment]
> Your version of clarion is outdated

Is it still? I can't tell. But I did merge it.

**Comment by Chatauscours** [comment]
> Is it still? I can't tell. But I did merge it.

Yes, the medbay and ranch areas seem to be from an older version.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
- Afaik we don't put APCs on south walls because they look very weird with the perspective.
- You're definitely reverting some clarion medbay and ranch changes
- On cog 2, donut 2, donut 3, kondaru and oshan you have 2-4 APCs in a row in the same area. Please try to keep APCs at least somewhat in or near the areas they're powering otherwise it becomes hell to find and repair them as an engineer.

Overall the area changes sound reasonable, I've noticed what cog 2 considers corridor vs room can be a little inconsistent 👍

**Comment by Glamurio** [comment]
> * Afaik we don't put APCs on south walls because they look very weird with the perspective.
> * You're definitely reverting some clarion medbay and ranch changes
> * On cog 2, donut 2, donut 3, kondaru and oshan you have 2-4 APCs in a row in the same area. Please try to keep APCs at least somewhat in or near the areas they're powering otherwise it becomes hell to find and repair them as an engineer.
> 
> Overall the area changes sound reasonable, I've noticed what cog 2 considers corridor vs room can be a little inconsistent 👍

I'll copy Clarion again from the master, weird how this happened.
Also on the Discord I was told to try and clump APCs of relevant areas together because it's easier, but I don't mind it either way, I can spread them out a bit.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
- The Atlas APC is still on the south wall
- The cog 2 cafeteria APCs are in an inaccessible (to engineers) back room
- The Nadir bar APC is in the wrong room

**Pull request merged**
