### PR TITLE
Mechcomp gps

### PR DESCRIPTION
**Pull request by Arivias**
[FEATURE][SPRITES]
## About the PR 
Adds the Mechcomp GPS component, which has three functions:
Output the coordinates of the component
Output the coordinates of the GPS unit with the specified ID
Output the coordinates of the GPS unit with the specified serial number

## Why's this needed? 
Currently, getting coordinates with mechcomp is... extremely inconvenient.

## Changelog

```
(u)Sidewinder7:
(*)Added Mechcomp GPS Component.
```

### CODE REVIEW

**Comment by pali6** [comment]
I feel like I'd rather see regular GPS units respond to some kind of a ping packet with their coordinates.

**Comment by ThePotato97** [comment]
> 
> 
> I feel like I'd rather see regular GPS units respond to some kind of a ping packet with their coordinates.
they do

**Comment by Sovexe** [comment]
I feel that `serial` makes more sense since the identifiers are alterable by users

GPS having an engraving on them inside a removable cover like APCs / Doors may also fit more in theme

**Comment by glassofmilk** [comment]
This seems like it's just duplicating what you can already do with GPS units using wireless packets

**Comment by Arivias** [comment]
I was under the impression that using packets would have a more limited range than what is available through gps units. If that's not the case then this patch isn't needed.

**Comment by MarkNais** [comment]
GPS broadcasts have infinite range, and #2207 is clarifying their ping-response packet.

**Comment by ZeWaka** [comment]
Closing due to #2207 being merged, and I believe it satisfies the goal of this PR. Feel free to make a new PR or reopen this one if that is not the case.

**Pull request closed without merging**
