### PR TITLE
Adds some new turf sprites

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 
This adds a couple of new turf sprites for players (via the Floor and Wall Planner), admins (via Build Mode's Adventure sub-mode) and mappers to play with.

turfsprites

Regal Carpet, Dark Carpet and Clown Carpet. These all have options for borders/edges and inner corners so you can make a regular rug, or completely fill in a weirdly-shaped room.

carpet_fancy carpet_fancydark carpet_fancyclown

White marble, Black marble and Terrazzo tiles (for that 70s/80s corporate lobby look). Both marble floors also have inverted border sprites.

marble_white marble_black terrazzo

Two new alternate snow sprites (both with outer edges/borders, I found it didn't need inner corners tbh).

snow_calm snow_rough

These wacky animated floors (not in the Floor and Wall Planner as they're probably a bit too annoying to have spammed everywhere)

animatedfloor

## Why's this needed? 
- I made a bunch of these for gimmick shuttles I've made/prefabs I'm working on, and this is me atomizing my PRs 😺 
- Also some of these tiles were options that I wished existed while playing as Construction Worker in the past, or just renovating the station in the present, and maybe I'm not alone in that? :o
- More options for mappers making prefabs etc, and for admin gimmicks.
- Bill really wanted me to finish these snow sprites

## Changelog

```changelog
(u)Walpvrgis
(*)The Floor and Wall Planner now has a few new flooring designs to choose from. Check the PR link above for preview images.
```

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Cursory glance, with the caveat of "I don't know if we actually encourage use of this, see if another developer wants to chime in first because Mordent doesn't know what the heck he's talking about": take a look at the `DEFINE_FLOORS` macro.

**Comment by WALPVRGIS** [comment]
> 
> 
> Cursory glance, with the caveat of "I don't know if we actually encourage use of this, see if another developer wants to chime in first because Mordent doesn't know what the heck he's talking about": take a look at the `DEFINE_FLOORS` macro.

Sure! :) I did notice it was used for a couple of turfs, but didn't look into it myself as the majority of existing ones didn't? But if it's preferred going forward I can take a look.

**Comment by Sovexe** [comment]
> > Cursory glance, with the caveat of "I don't know if we actually encourage use of this, see if another developer wants to chime in first because Mordent doesn't know what the heck he's talking about": take a look at the `DEFINE_FLOORS` macro.
> 
> Sure! :) I did notice it was used for a couple of turfs, but didn't look into it myself as the majority of existing ones didn't? But if it's preferred going forward I can take a look.

if your turf doesnt have any other fancy code the macro is the easy mode for making the four variants all at once. sim, airless sim, unsim, and airless unsim

**Comment by Gannets** [comment]
Looks absolutely lovely.

**Review by virvatuli-gh — APPROVED** [review]

**Pull request merged**
