### PR TITLE
Fixes MONO card game icons

### PR DESCRIPTION
**Pull request by Gonzako**
## About the PR 
Makes the MONO card game actually show the mono icons

## Why's this needed? 
Bad Icon

## Changelog
sweep this under the rug please

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Might close #7793, make sure that any changes here don't accidentally conflict with #7791 either

**Comment by TobleroneSwordfish** [comment]
Is the rules file actually used anywhere?

**Comment by Gonzako** [comment]
> Is the rules file actually used anywhere?

It's on the card game vendor. Though I really dont know where those are

**Review by ZeWaka — COMMENTED** [review]
how is it on the vendor if it's not added in this commit

**Comment by Gonzako** [comment]
> how is it on the vendor if it's not added in this commit

It was added in #7656 which sadly came with broken icons. Which this PR fixes

**Comment by ZeWaka** [comment]
No, the text file.

**Comment by Gonzako** [comment]
> No, the text file.

File got added in #7656 and then #7791 changed the file and moved the class to books.dm

**Review by pali6 — APPROVED** [review]

**Pull request merged**
