### PR TITLE
Give every scientist a pen

### PR DESCRIPTION
**Pull request by flappybatpal**
[QOL]

## About the PR 
Adds a standard black pen to every scientist's starting pocket.

## Why's this needed? 
Artifact lab require pens to fill in forms but availability of pens depends upon the map.
Sleepy pens are a common scientist item but even with artifact research typically only 2~ scientists doing that would carry pens making any pen still suspicious.

## Changelog

```changelog
(u)Flappybat
(+)Every scientist now starts with a pen.
```

### CODE REVIEW

**Comment by Azrun** [comment]
I like it being suspicious. 🤷
Picking from a list of writing implements could spice it up so there would be an expectation of "something".

**Comment by ZeWaka** [comment]
It'd be nice if it'd pick from the different types. Could you make a new `obj/item/pen/random` and have it pick from `/obj/item/pen, /obj/item/pen/fancy, /obj/item/pen/red (lower chance), /obj/item/pen/pencil)`?

**Comment by zjdtmkhzt** [comment]
Hmm, my plan was to just add pens to the artlabs, but I suppose this would work too!

**Comment by ZeWaka** [comment]
merging @flappybatpal - you can refactor to be random pens later

**Pull request merged**
