### PR TITLE
Removes the fuckable girder

### PR DESCRIPTION
**Pull request by DisturbHerb**
[REMOVAL][OBJECTS]

## About the PR 
Removes the ability for the player to construct a, and I quote, "fuckable girder". This one might be tagged incorrectly, please feel free to fix.

## Why's this needed? 
image

### CODE REVIEW

**Comment by TheTyrant25** [comment]
the what

**Comment by frawhst** [comment]
[FUCK] [GAME OBJECTS]

**Comment by Sord213** [comment]
the girder, tho

**Review by Gannets — APPROVED** [review]
Yeah, It's probably time.

**Comment by BatElite** [comment]
Wouldn't you need a message to replace that one? since it's meant to reach 70 exactly

**Comment by DisturbHerb** [comment]
> Wouldn't you need a message to replace that one? since it's meant to reach 70 exactly

thanks for reminding me

**Comment by Tarmunora** [comment]
soul

**Comment by Kapu1178** [comment]
No.. you cant...

**Comment by geneva-breaker** [comment]
Disney's fisher price kindergarten girder

**Pull request merged**
