### PR TITLE
Resprites Satchels

### PR DESCRIPTION
**Pull request by MitchTheUser**
[GAME OBJECTS]

## About the PR 

Resprites all the Satchels in the game, as well as their Counter Overlays:

**-  Plain (Unused?)**

**-  Hydroponics**

**-  Engineering**

**-  Mailman**

**- Orebag (Unused, just did it for fun)**

The new sprites have nicer coloring and shading, and should pop out with a more vibrant color scheme. All 4 main types of satchels now also have unique inhands. In addition, the large and (unused?) spatially-compressed subtypes have gotten their own unique sprites to show off how big they are compared to normal satchels. As a fun bonus, a new "Spatially-Compressed Produce Satchel" subtype has been added to the code, holding up to a thousand crop/seed items, compared to the two hundred item capacity of the large subtype, just for any crazy botany testers out there.

SatchelDisplay

## Why's this needed? 

The current sprites are quite old and out of date, looking a bit dull compared to other sprites in Botany and Engineering. Theres no visual difference between normal satchels and large/spatially-compressed satchels, which is a problem if you need to find your large satchel and it blends in with normal ones. The Counter Overlays have dull colors, with the gauge using pure blacks and greys. Inhands are always appreciated, and help to show if you are holding a satchel and what type as well.

SatchelInhands

## Changelog 

```changelog
(u)MitchSmith
(+)Resprites Satchels!
```

### CODE REVIEW

**Review by Gannets — APPROVED** [review]
Almost wish we could integrate the fill overlay better, ah well. Better than the existing sprites.

**Comment by BatElite** [comment]
While you're at this, can you make the large mining satchel look any different from the small one?

**Comment by AXLFAN2000** [comment]
> While you're at this, can you make the large mining satchel look any different from the small one?

This would be a godsend

**Comment by MitchTheUser** [comment]
> While you're at this, can you make the large mining satchel look any different from the small one?

Big satchel sprites? It's yours my friend. Have a large mining satchel sprite, have a large produce satchel sprite. Not done yet, have some inhands to go with your satchel sprites. You think I'm done yet? Nope, how about some JUMBO ("Spacially-Compressed" satchel sprites?

**Pull request merged**
