### PR TITLE
Resprites some dogs and adds some new ones.

### PR DESCRIPTION
**Pull request by Shmiggy**
[SPRITES][STATUS EFFECTS]

## About the PR 
Resprites the corgi, pug, and shiba, and adds the borzoi, dachshund, and retriever. Dogs, when pet, will no longer become unconscious.
newdogs
## Why's this needed? 
I saw that dogs were lacking in variety, so I figured it would make sense to add some new ones. 
While I was at it, I resprited some of the old dogs.
Dogs becoming unconscious upon being pet seemed annoying, so I removed the code that allowed this to happen.

## Changelog 

```changelog
(u)Shmiggy
(+)Resprites some dogs and adds some new ones. Being pet as a dog no longer knocks you out..
```

### CODE REVIEW

**Comment by BatElite** [comment]
why is the pug so long?

**Comment by Shmiggy** [comment]
ok, I condensed the pug sprite. I am pretty sure that I committed this change to this PR but I'm not 100% sure
image

**Comment by nefarious6th** [comment]
> ok, I condensed the pug sprite. I am pretty sure that I committed this change to this PR but I'm not 100% sure

looks good. if you ever wonder if you updated the PR sprites correctly, under the "checks" tab at the top, you can click there, then on the left side, look for IconDiffBot, click that; you'll get a list of the modified dmi files and can expand the dropdown under the triangle to see if your changes made it.

happy to report the pug sprite is updated 👍

**Comment by Shmiggy** [comment]
Alright cool. Something else I’m not sure about is the “update branch” button on this page. Do I only need to press it if someone makes changes to the files that I’ve changed?

**Comment by nefarious6th** [comment]
generally, yeah; it just merges your master branch into this one to keep it on par with wherever the main goonstation repository is at. it's really specifically important for when it says you have merge conflicts, which are what happens when someone edits in a different pull request/commit the files that you touched in your pull request. it'll have a different indicator (i think "resolve merge conflicts") on the button instead, so you'd know if you have extra work to do to fix anything.

**Comment by WALPVRGIS** [comment]
Hey just a heads up, I'm writing a thorough review on these, it'll just be a couple of days as I'm not around much this week and I need to sketch up some example images.

**Comment by Shmiggy** [comment]
Thank you, I greatly appreciate any feedback you have for me

**Pull request closed without merging**
