### PR TITLE
Adds 1 double color braid and 1 shoulder braid

### PR DESCRIPTION
**Pull request by Blahowsky**
## About the PR 
 Adds 3 new hairs, loose long braid, loose long braid twin color and loose long braid over shoulder.

## Why's this needed? 
 I think there aren't enough braids in game and I am pretty positive there is no faded/twin color braid type hairs

braids

## Changelog
```changelog
(u)Blahowsky
(*)Added two new hairstyles and one fade; Loose Long Braid (with Loose Long Braid: Twin Color to customise) and Loose Long Braid Over Shoulder.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Would be nice to see some screenshots

**Comment by Blahowsky** [comment]
> Would be nice to see some screenshots

There sorry first PR

**Comment by nefarious6th** [comment]
super cute and good ideas for new hairstyles.

**Comment by WALPVRGIS** [comment]
These are pretty cute! I added a changelog entry so that players would have reference of what the new hair is and how it's named! 👍

**Pull request merged**
