### PR TITLE
3x3 random room: Cluwne Hole

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
Adds a new 3x3 room

## Why's this needed? 
Another piece of variety in a random room situation

### CODE REVIEW

**Comment by cheekybrdy** [comment]
image

**Comment by CaioFrancisco** [comment]
The competition closed a few hours ago, but it **must** get into the game.

**Comment by cheekybrdy** [comment]
This should be good to go, other then maybe a assessment of the power of the items in there (cluwne mask and the elden AI holo module)

**Review by Sord213 — CHANGES_REQUESTED** [review]
Sorry I must have missed this one. Could you increase the rarity so it's not super common? Somewhere between 50 and 80 would work.

**Comment by cheekybrdy** [comment]
from what I know about the randomness system, that does it?

**Pull request merged**
