### PR TITLE
Resprites backpacks/satchels and adds 3 new Spacebux bags

### PR DESCRIPTION
**Pull request by WALPVRGIS**
[FEATURE] [WIKI] [SPRITES] [QOL]
## About the PR 
This PR does a few bag related things;
- Resprites backpacks and satchels (not including Syndie Tactical Assault backpack, or Captain backpacks as they looked fine to me!)
- Adds satchels for all bags that were missing them, so all bags (except the Syndie Tactical Assault Backpack) can be turned into satchels using the medal reward!
- Adds inhand sprites for all bags that were missing them. Oh god my drawing hand. So many.
- Adds the Studded Backpack, Itabag (in 5 colours) and Brown Backpack purchases to the Spacebux menu.
- Updates HUD icons for the back slot to use the new backpack sprites.

New backpack sprites. The medic backpack and satchel have been modified to use differently-styled symbols, as we are no longer using the red cross on white imagery. The blue, red, brown and green backpacks are resprites of old unused (I believe?) backpack colours. They are all now functioning items ingame, though only the brown backpack is obtainable at the moment as the other colours look a little too much like the Captain's backpacks imo.
backpack_resprites

New satchel sprites (Captain's Satchels have only had the straps updated);
satchel_resprites

New backpacks + their satchel versions, as well as satchel versions of the previously existing spacebux bags;
bags_new

Examples of worn and inhand sprites (not all are pictured but all have been tested and work);
bags_worn

HUD update example. I also have updated the back icon for the Spooky HUD.
hud_new

## Why's this needed? 
- Old backpack and satchel sprites were a bit vague and out of date. Especially for a prominent item that most players have on their screen at all times.
- I was sad that not all backpacks could be turned into satchels :'(
- New customization options and cosmetic SB purchases are fun!

## Changelog

```changelog
(u)Walpvrgis
(*)Three new Spacebux bags are now available to purchase; Studded Backpack, Itabag (in one of 5 random pastel shades), and a brown backpack! 
(*)Backpacks and Satchels have been resprited. You also can now turn almost all backpacks into satchels using the medal reward.
```

### CODE REVIEW

**Comment by Flaborized** [comment]
Love these, I especially like the new medical pack design as the more prominent red means the bag won't blend into med doc's labcoats so much, imo will make them look much more visually interesting.

If I had to complain about anything, I'd say the strap for the satchels still has a sorta inconsistent use of outlines since there's light colors on the outside of the sprite (when compared to the rest of the bag), but even then I think they're a significant improvement over the current satchel sprites, that's more of just a nitpick and I'd be fine with the sprites as-is, especially since it's only really visible with the lighter bags.

**Review by Gannets — APPROVED** [review]
Looks great, good work!

**Comment by WALPVRGIS** [comment]
Thanks to both of u! :D 

With the satchel straps, it was a bit of a struggle without making them look too chonky sadly.I went against my own spriting credo to have light-coloured border sprites, aha >:'D

**Comment by virvatuli-gh** [comment]
Great stuff, looking forward to seeing more variety on the station, old grey packs are so boring compared to colours!

**Comment by WALPVRGIS** [comment]
Thanks! :)

If folks think the red/blue/green backpacks are fine to implement, I'm down to add them to, say, clothing manufacturers or the clothing booth! Was thinking about that tbh. Originally I had the "Brown Backpack" sb purchase instead as "Random Alternate Backpack Colour", but multiple people were only interested in the brown one, ahaha. :P Clothing booth might work, as then it's not TOO common and requires cash. Hmmm

**Pull request merged**
