### PR TITLE
Filteriffic by Actioninja

### PR DESCRIPTION
**Pull request by Azrun**
[feature]
## About the PR 
https://streamable.com/tt23et

Port of @actioninja's https://github.com/tgstation/tgstation/pull/55246

## Why's this needed? 
Allow content creators to voodoo program themselves some filters.
Allow shenanigans with filters.
Allow for easy adjustment and modification of filters.

### CODE REVIEW

**Comment by pali6** [comment]
👀 I've wanted to make something like this for a while, nice! (Now if only you could also animate the filters...)

**Comment by pali6** [comment]
Does this mean that with this PR merged we should use `add_filter` etc. instead of directly managing filters in code? (Similarly to how UpdateOverlays is used instead of touching `overlays` directly.)

**Comment by Azrun** [comment]
> 👀 I've wanted to make something like this for a while, nice! (Now if only you could also animate the filters...)

That would be slick. Could probably bake it into the parameters and "hide" it in a FontAwesome icon.  Would make for a good feature to PR back to TG.

**Comment by pali6** [comment]
Btw I am separating the general filter management procs into a separate file in __std for organization purposes (keeping the license header).

**Pull request merged**
