### PR TITLE
Dummies' Guide to Material Science, 8th Ed.

### PR DESCRIPTION
**Pull request by MeggalBozale**
## About the PR 
dreamseeker_GGiJTyn3UV
Update's the "Dummies' Guide to Material Science, 7th Ed." book with minor tweaks to updated material values, and resolves some minor spelling mistakes.

Feel free to make suggestions to rewording and whatnot.

## Why's this needed?
In-Game reference material should be accurate and up to date. Also spelt correctly.
#8252 should be fixed by this but will still need a wiki update (It was already, but needed another once-over)

## Changelog
```changelog
(u)MeggalBozale
(+)NT has spent a few million credits stocking its stations with newly printed guides to material science, featuring minor spelling corrections and updated material values.
```

### CODE REVIEW

**Comment by MeggalBozale** [comment]
Oh hey, just to mention: I wanted to make the values dynamic, or maybe even have it go material by material. But I have NO idea how to make a book dynamic that loads itself from a text file. If anyone does know, I'd be happy to have this book keep itself up to date once and for all.
(Though, I think it would be nice to have hand-typed descriptions for each ore, and if new mats are added, "tell a coder!" pops up for no desc.)

**Comment by Glamurio** [comment]
> Oh hey, just to mention: I wanted to make the values dynamic, or maybe even have it go material by material. But I have NO idea how to make a book dynamic that loads itself from a text file. If anyone does know, I'd be happy to have this book keep itself up to date once and for all. (Though, I think it would be nice to have hand-typed descriptions for each ore, and if new mats are added, "tell a coder!" pops up for no desc.)

I don't know if it's possible in DM, but we do use TypeScript for TGUI stuff, and I'm wondering if we can run a script at the beginning of a round that reads the values (from an XML, or whatever) and then generates the resulting text file, which in turn gets loaded by the game. How we would generate the XML without manually creating it when all values exist in .DM files is beyond me, however.

**Comment by MeggalBozale** [comment]
First step would prolly be autogenerating as much as possible, then getting the descriptions for unique materials and filling them in.
E.G.
[material_name]
[custom_description]
[material_properties]

Bohrum
A green, mildly conductive metal which closely resembles steel, but with higher hardness and density. It's useful for tools and equipment which need something a bit extra. (idk i made it up)
Electrical Conductivity: 5
Thermal Conductivity: 6
Hardness: 5
Density: 6
Flammability: 1
Chemical Resistance: 7

**Comment by TobleroneSwordfish** [comment]
The smart string picker system lets you embed DM proc calls into text files, you could probably hack that into generating a matsci book with stuff like `[get_material_property("bohrum", "density")]`. I defer to pali on whether that's a good idea though :)

**Comment by Glamurio** [comment]
> The smart string picker system lets you embed DM proc calls into text files, you could probably hack that into generating a matsci book with stuff like `[get_material_property("bohrum", "density")]`. I defer to pali on whether that's a good idea though 

@pali6 Is that a good idea? Might be better than to hardcode values at multiple locations, less likely to mess things up

**Comment by pali6** [comment]
Sounds like a good idea yes! Note that you will need to pass the proc ref with its name as one of the arguments. Look at Father Grife's lines for an example of ping me on discord.

**Comment by pgmzeta** [comment]
updated wiki

**Pull request merged**
