### PR TITLE
ComTac Headset utility item

### PR DESCRIPTION
**Pull request by Gannets**
## About the PR 
A syndicate radio headset that blocks 100% of ear disorient while allowing full radio conversation.

## Why's this needed? 
Nuke ops have been having a rough time with flashbangs.

## Changelog

```changelog
(u)Gannets & BatElite
(*)Adds a new utility purchase to the Syndicate Weapons Vendor on the Cairngorm: the Military Headset. 
(*)This headset allows an operative to communicate on their usual radio frequencies, but with the advantage of blocking 100% of ear disorient damage from things like flashbang grenades. 
```

### CODE REVIEW

**Comment by UrsulaMejor** [comment]
Fix your changelog entry!!!

**Comment by Gannets** [comment]
> Fix your changelog entry!!!

yes ma'am

**Comment by Sovexe** [comment]
Does it get a themed sprite?

**Comment by Gannets** [comment]
> Does it get a themed sprite?

I am bullying #imspriter it to making one for me.

**Comment by BatElite** [comment]
> 
> 
> > Does it get a themed sprite?
> 
> I am bullying #imspriter it to making one for me.

For your consideration:
https://discord.com/channels/182249960895545344/585526776550391819/883004454624968704

**Comment by Gannets** [comment]
> > 
> > 
> > > Does it get a themed sprite?
> > 
> > I am bullying #imspriter it to making one for me.
> 
> For your consideration:
> https://discord.com/channels/182249960895545344/585526776550391819/883004454624968704

Nice, thanks! Will add when I'm next at a computer.

**Pull request merged**
