### PR TITLE
Monkey clothes part 3

### PR DESCRIPTION
**Pull request by DimWhat**
[Sprites]
## About the PR 
Adds a bunch more monkey clothes from misc, gimmick, and a few suits. Also renames the icon_state for the senior botanist jumpsuit and pilot suit as to actually be able to distinguish them in monkey_clothes.dmi
image

## Why's this needed?
More monkey clothes good.

## Changelog

```changelog
(u)DimWhat
(+)Added several more sprites for monkey clothing. Time for monkey business.
```

### CODE REVIEW

**Review by flrsh — APPROVED** [review]

**Comment by nefarious6th** [comment]
Thank you for doing all these sprites! Looking great so far!

**Comment by DimWhat** [comment]
Oh shoot I accidentally messed with the dme with my last commit. I'll fix that when I get to my PC. Please do not merge until then.

**Comment by flrsh** [comment]
@DimWhat looks like there may have been some unintentional changes to `clown-fancy` in some of the files?

**Comment by DimWhat** [comment]
> @DimWhat looks like there may have been some unintentional changes to `clown-fancy` in some of the files?

Oh I had forgotten walp had made changes and updated that. In my weird fugue "end all conflicts" state I didn't realize they updated the fancy suit. I'll fix it.

**Comment by mordent-goonstation** [comment]
Looks like the `clown-fancy` icon state still has changes to it? Would prefer splitting those into a separate PR (with associated monkey sprites) if we can.

(Above comment is based on the IconDiffBot result.)

**Comment by DimWhat** [comment]
> Looks like the `clown-fancy` icon state still has changes to it? Would prefer splitting those into a separate PR (with associated monkey sprites) if we can.
> 
> (Above comment is based on the IconDiffBot result.)

Still? I thought I fixed that.

**Comment by DimWhat** [comment]
I give up. I have no idea how or why there are changes. I don't know what I did. I am going to just start from scratch.

**Pull request closed without merging**
