### PR TITLE
Refactor loot crates

### PR DESCRIPTION
**Pull request by maybeserendipitous**
[CLEANLINESS][WIP]

## About the PR 

Refactor loot crate code to be more declarative instead of deep nesting, switches, and `+=` everywhere.

## Why's this needed? 

Makes code cleaner.
Should also make it easier to add new loot, which is actually why I'm doing this.

### CODE REVIEW

**Comment by Laboredih123** [comment]
I think it would be nice with absolute pathing

**Comment by maybeserendipitous** [comment]
> I think it would be nice with absolute pathing

I do not understand what you mean. Can you give me an example?

**Comment by Laboredih123** [comment]
image

absolute pathing greatly helps with searching for type defs, since you can just search for /obj/thing, while relative pathing, while easy to code in, makes searching harder since a def can be a path spread out through multiple lines.

**Comment by maybeserendipitous** [comment]
> absolute pathing greatly helps with searching for type defs, since you can just search for /obj/thing, while relative pathing, while easy to code in, makes searching harder since a def can be a path spread out through multiple lines.

Oh, I see. Sure thing, I need to start from 0 anyways...

**Comment by maybeserendipitous** [comment]
Maybe some other day.

**Pull request closed without merging**
