### PR TITLE
Reworks how space in plates work (and a little extra)

### LINKED ISSUE #11369: Pizza boxes can contain a whole pizza but not all of their individual slices
### Labels

[BUG][TRIVIAL]

### Description

pizza

### Steps to reproduce

1) cut a pizza
2) attempt to place all of the slices in the box
3) turn your head skyward and shed a single tear as you can only fit two inside at a time

### Expected Behavior

i expected it to be able to fit the pizza slices

### Additional Information & Screenshots

Reported by: Babayetu83
On server: Goonstation 3 Roleplay: Morty
Round log date: 2022-10-15-06-07
Reported on: 2022-10-15 07:10:30

### PR DESCRIPTION
**Pull request by CaioFrancisco**
[REWORK] [QOL] [CATERING] [OBJECTS]

## About the PR 

The PR reworks how plates (including trays and pizza boxes) holds items. Instead of having a limited amount of items it can hold, each item will hold a different amount of space on the plate by it's weight, which is decided by the W_CLASS macros. Tiny items holds 1 unit of space, small items hold 2 units of space, normal items hold 3 units of space and so on. Spaces can hold 3 units of space, pizza boxes can hold 6 units of space and trays can hold 30 units of space.

The little extra is that this also makes pizza slices weight tiny when sliced, not weight as much as an entire pizza. 

## Why's this needed? 

Because it ultimately fixes #11369. The whole new space system fixes slices not fitting inside the box but 2 entire pizzas do. The change to pizza slices is to make it all tie together, because you'd only fit 2 slices in the pizza box if it weighted like a normal item.

### CODE REVIEW

**Comment by CaioFrancisco** [comment]
i effed up. i'll fix it in a bit, i'm gonna lunch rn.

**Comment by CaioFrancisco** [comment]
should work fine now

**Comment by CaioFrancisco** [comment]
I'm requesting a review from you because you are the one who reworked plates.

**Comment by frawhst** [comment]
why are pizza slices not a separate item from entire pizzas. what the hell
```dm
			var/obj/item/reagent_containers/food/snacks/pizza/P = new src.type(get_turf(src))
			P.topping_holder += src.topping_colors
			P.overlays.len = 0
			P.sharpened = src.sharpened
			P.sliced = TRUE
			P.bites_left = 1
			P.icon_state = sliced_icon
			P.quality = src.quality
			P.heal_amt += round((src.heal_amt/makeslices))
			P.topping_color = src.topping_color
			P.w_class = W_CLASS_TINY
```
fixing that is out of scope here though.

**Review by frawhst — APPROVED** [review]

**Comment by CaioFrancisco** [comment]
I had the same thought when I looked at pizza code, but I heard it's because of how custom pizzas work (which doesn't really make sense to me.) I will probably rework it in the future to procrastinate doing something useful IRL.

**Pull request merged**
