### PR TITLE
Adds medical clothing lockers to most maps, adds a uniform locker to destiny, increases clothing locker contents. and removes a double define of the nurse dress

### PR DESCRIPTION
**Pull request by DimWhat**
[Mapping] [Cleanliness]
## About the PR
This will allow doctors to change up their look a bit more than generic lab coat, no generic lab coat, or the paramedic suit without leaving medbay. This is done by adding a locker of medical clothing to every map except kondaru which is pending on Krump's Kondaru medical changes. Also makes it so medical lockers will hold more coats. I don't believe I see many doctors wear the coat and it's mostly cause there is usually one or two per map.

Please tell me if you have any problems with the locations of the locker!

## The locations of medical clothing lockers:
- Atlas: The cryo area of medical where a uniform locker was.
- Cog 1: In the break room next to the uniform locker.
- Cog 2: Next to the coffee maker and couch south of cryo.
- Clarion: Next to the rack outside of surgery.
- Destiny: Right Outside the medbay entrance to cloning.
- Horizon: Right next to the Uniform locker in the by the entrance. The gurney that was there has been moved next to the disposals unit. Foreboding... 
- Oshan: Right next to the uniform locker in the equipment room. The blood locker that was in there has been moved to surgery.

## Why's this needed?
People have requested these articles of clothing to be on more maps. Increasing the amount of clothing inside to accommodate for the increased population so multiple doctors can put on varied clothes is a good idea in my book. Also destiny has no uniform lockers and that's no good. Finally, double defines have actually no purpose, goodbye forever exact replica of code.

## Changelog

```changelog
(u)DimWhat
(+)Added medical clothing lockers to Atlas, Cog 1, Cog 2, Clarion, Destiny, Horizon, and Oshan.
(+)Added medical winter coats to medical clothing lockers and increased their amount of clothing.
```

### CODE REVIEW

**Comment by flrsh** [comment]
The Clarion location is a little busy, maybe consider swapping with the leftmost rack here?

image

And for Oshan, maybe swap with the blood locker here - 

image

And place the blood locker in the bottom left corner of the OR?

image

**Comment by DimWhat** [comment]
> The Clarion location is a little busy, maybe consider swapping with the leftmost rack here?
> 
> image
> 
> And for Oshan, maybe swap with the blood locker here -
> 
> image
> 
> And place the blood locker in the bottom left corner of the OR?
> 
> image

I'll hop right to it

**Comment by DimWhat** [comment]
done and done

**Review by flrsh — APPROVED** [review]

**Comment by DimWhat** [comment]
I would like to request that this do not be merged until I the wiki is updated accordingly. I'll get to it tomorrow.

**Comment by DimWhat** [comment]
The stuff has been added to the wiki. I think it is now okay to push this.

**Pull request merged**
