### PR TITLE
AI Abilities

### PR DESCRIPTION
**Pull request by Azrun**
[experimental]
## About the PR 
Friend computer would like to help ~hurt~ you.

Provides _framework_ for giving abilities via `/obj/item/aiModule` to attached AIs.

* Taser Module
* Laser Module
https://streamable.com/m0ff3u
* Metal Foam Launcher Module
https://streamable.com/5uakvf
* Teleporter Module (Easy Send and Receive)
https://streamable.com/5a6pvl
* Camera and Silicon Repair Module
* Security Vision
* Doctor Vision
https://streamable.com/ulj322

## Why's this needed? 
Gimmickry and possible future integration into general play.  Would allow for crew to have some control over how they want the AI to best serve the station.  Additionally a vector for rogue AIs to have something other to do than explode lights and electrify/bolt doors.

### CODE REVIEW

**Comment by Wisemonster** [comment]
I know this is only a framework, but how would this work? Would the AIs be able to, say, shoot a taser shot where their AI eye is, or is this meant for the shells?

**Comment by Azrun** [comment]
Taser, Laser, and Foam Launcher would come from the security cameras around the station.

**Comment by ThatFiveGuys** [comment]
I very much like the idea of ai upgrades, however i feel as if giving the ai more control here would be good. Also cameras shooting projectiles seems off, maybe replace it with upgrades that give turrets access to more projectiles (like wavegun green mode and a weaker ass laser to get through and destroy blockades respectively)

**Comment by Azrun** [comment]
> I very much like the idea of ai upgrades, however i feel as if giving the ai more control here would be good. Maybe have the rack that upgrades the AI be a separate rack from the law one, and a few blank ones that the AI can download unique programs (with less of em of course) into with printable modules with more storage space alongside the more specified ones that you can find? Though that would probably be outside of scope. 

I'm not entirely sure what your are describing.  More storage space, like for the PDA?  So maybe what is missing really is a demo of what this currently looks like.  As it curly works as ability button(s) that already when an ability explain module is inserted. 

Constraining choices, between laws and upgrades, allows the crew (or those interacting with the law racks) to weigh the value of thier options and ultimately limit choice. The idea being that the AI wouldn't be able to do everything, and if you wanted more functionality you may have a reason to have a separate law racks and AI to support those functions.

>Also cameras shooting projectiles seems off, maybe replace it with upgrades that give turrets access to more projectiles (like wavegun green mode and a weaker ass laser to get through and destroy blockades respectively)

Hmmm, the cameras leverage an existing resource and give a reason for antagonists, and those interested in doing a crime, a reason to interact with them.  This also gives interesting limits regard shot angles. They are currently all energy based projectiles that pull power relative to the cost as it works be pulled from a cell from the APC.

If there were turrets, would those be sperate deployable/constructable items? I had an idea for a gimmick specific version that allowed the AI to cause a turret to be deployed momentarily wherever but that is separate.

**Comment by ThatFiveGuys** [comment]
Main thing is there cameras and also i can see people being super supercop with them, which just seems frustrating and really confusing for new players who dont know that cameras are apparently also guns. I was moreso talking about things that upgrade the pre existing turrets found in upload. Honestly itd probably best to lean away from ai upgrades that can directly aid in validhunting, as supercop ai can be bad for the game. A few other upgrade ideas are things like prodoc vision (ideally upgraded version, would be super useful with nanomed play), and security status vision, just things that help from day to day.

**Comment by NightmareChamillian** [comment]
Maybe make these these could apply to AIshells, which as it stands are pretty useless and always inferior to borgs? Giving cameras the ability to shoot lasers and spew foam seems unintuitive and confusing, as well as overpowered to have the AI be able to stun or shoot anyone, anywhere, without giving them a good way to retaliate or retreat like antags can against sec/a hostile borg, and will just encourage antags to spam wirecutters on all the cameras.

**Comment by Azrun** [comment]
> Main thing is there cameras and also i can see people being super supercop with them, which just seems frustrating and really confusing for new players who dont know that cameras are apparently also guns. I was moreso talking about things that upgrade the pre existing turrets found in upload. Honestly itd probably best to lean away from ai upgrades that can directly aid in validhunting, as supercop ai can be bad for the game. 

Good feedback, and has been the major overall concern.  The weaponizing of the cameras is really only intended for gimmicks where oversight of the player is more possible to ensure the oppressive nature of the abilities is in the spirit of the round.  Currently has an animation of an outline when the ability activates and then a short delay before it fires. An auditory cue world also help and additionally Dim had a great suggestion of a laser pointer to allow for an escalation (was considering a hologram of a reticle as well).

I've also been playing with different means of determining if a shot is valid from a camera as some of the camera placements are not ideal (which I prefer).

>A few other upgrade ideas are things like prodoc vision (ideally upgraded version, would be super useful with nanomed play), and security status vision, just things that help from day to day.

SecHud + Quick access to modifiable security records and Procdocs with basic scanning were both ideas I was thinking about trying out later.  With the current communication and PDA abilities of the AI these would synergize well.

**Comment by ThatFiveGuys** [comment]
Upon further thought, I think the camera shooting is sadly unworkable. Not only do I really see any positive interactions coming out of this, I think hammer theory (look I just want a common term to use as a catchall for this type of stuff okay, Im coining it now and you cant stop me) needs to be taken into account here. Basically, give a player a hammer, and theyll be expect nails, and thus change there behavior to use the hammer. By giving AIs a direct weapon to antagonize the crew with, you frame it as something theyll want to do. I feel as if things this direct at hunting antags will encourage it directly. Though, if it is to be kept, I think making the projectile into a ranged flash (to where eyeprot blocks it and all that jazz), would be more fitting. The AI using a shitty security cameras flash tactically seems fitting.

**Pull request merged**
