### PR TITLE
CE gets special reskinned engineering suits

### PR DESCRIPTION
**Pull request by NightmareChamillian**
## About the PR 
This PR adds two new suits to the game: A chief engineer diving and a chief engineer space suit, that can only be found in the CE's locker. They differ from the normal engineering suits only in cosmetics.

image

image

## Why's this needed? 

99% of the time, especially on space maps, the chief engineer is wearing some form of space suit suit, and looks the exact same as all the other engineers as consequence. No other departmental head has this problem due to the fact that EVA is really only engineering's thing. Giving the chief engineer an option to have their rank obvious when fully suited up will help the CE organize engineers in space and make it more obvious who has the RCD.

## Changelog

```changelog
(u)NightmareChamillian
(*)CE now gets a special looking suit so you can tell who they are in space
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
Very good change, I can’t tell you how many times I haven’t been able to locate the CE cause they blend in with the rest of their crew

**Comment by Eagletanker** [comment]
These feel kinda noisy. Consider making the green HI Vis

**Comment by ThatFiveGuys** [comment]
I think these arent really distinct enough from normal engineering spacesuit sprites. Also stripe on side bar looks off.

**Comment by NightmareChamillian** [comment]
Closing, since thatgiveguys offered to their own take on it and I did shamelessly spend 20 minutes color-shifting the base engie one for this PR.

**Pull request closed without merging**
