### PR TITLE
Reflective_Glasses

### PR DESCRIPTION
**Pull request by klushy225**
## About the PR 
This PR adds a style for glasses that does not allow the face under the lenses to be seen- aka nerd glasses. This also adds an emote where you can push the glasses up your nose. Yes, like in anime.

image

## Why's this needed? 
While some people may like the current glasses, it can be hard to tell at times if there is a lense even there. This also adds an emote that smart asses can use to be funny.
Current video of emote: https://imgur.com/a/o2vOjTL

https://github.com/goonstation/goonstation/assets/57295136/070b97c3-532a-4d25-af79-30188b96e5af

A video of the emote:(outdated)

https://github.com/goonstation/goonstation/assets/57295136/6373519c-24ab-4725-87da-9a611776e770

[https://imgur.com/a/deF2pQy](url)    <-- uncompressed

## Changelog 

```changelog
(u)Klushy225
(+)Added a new glasses style that reflects light
(+)Added an emote that allows you to switch to the style, in style!
```
NOTE: This shoud be good to pr- I just removed the playsound call altogether, so there shouldn't be any issues

### CODE REVIEW

**Comment by imawxome** [comment]
me when pizza changelog

**Comment by klushy225** [comment]
> me when pizza changelog

hehe yeah I accidentally posted it while I was still setting it up- it's all set up now

**Comment by Sbmhawk** [comment]
Maybe have a sparkle effect for a second or two also?

**Comment by IPling** [comment]
I like it, but using the flash sound doesnt make much sense. Maybe the vampire glare would be better, or even opting out of sound completely and doing what Sbmhawk suggested.

I also think being able to nudge back the glasses to their previous state without having to take them off would be great.

**Comment by klushy225** [comment]
righty- when I'll get home today I'll work on that

**Comment by Valtsu0** [comment]
I mostly agree with Ipling, but do not use the vampire glare sound. That sound needs to be distinctive.

**Comment by klushy225** [comment]
well everything suggested is mostly done, except for the sparks. Once I finish that, I'll put a new video up

**Comment by klushy225** [comment]
righty- just did the sparks- alot simpler than I anticipated it to be. I'm recording a demo now

**Comment by Kyle2143** [comment]
I say give that emote effect the ol Detective sunglasses "YYEEAAAAHHH!!!" treatment. It only plays the sound/visual if it's the first time someone tries the emote.

**Comment by klushy225** [comment]
> I say give that emote effect the ol Detective sunglasses "YYEEAAAAHHH!!!" treatment. It only plays the sound/visual if it's the first time someone tries the emote.

I'll work on that!

**Pull request closed without merging**
