### PR TITLE
Pop locks most maps above 80 players

### PR DESCRIPTION
**Pull request by moonlol**
[BALANCE] [INPUT]

## About the PR 
~~This pr pop locks cog1 to 75 players giving a 35 player window when both cog1 and cog2 are votable. im unsure about this value~~ This pr pop locks most maps to 80 players, as most maps arent just suited to such high pop.

## Why's this needed? 
~~Cog2 and donut 3 are maps much more suited to high pop then cog1 and considering the large increase in server population id say this is pretty needed~~ Cog2 donut 3 horizon and oshan are pretty much the only maps suited to high pop (less so for horizon and oshan but we need a ship and ocean map.)

## Changelog

```
(u)Moonlol:
(*)All maps apart from Cog2, Donut 3, Horizon and Oshan cannot be voted past 80 players.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Even if we really wanna lock the most popular map, 60 players feels like _way_ too low a cap for cogmap1 to me.

**Comment by Flaborized** [comment]
Don't like it, I think Cog1 plays Just Fine at 60 players and is quite popular, I think it's a bad idea to restrict our Most Popular Map at a population that Works For It

**Comment by moonlol** [comment]
70? 75? 80?

**Comment by TTerc** [comment]
Alright, I'll say that again
Pop locking cog1 only won't fix the issue with maps overpopulating
My take: pop lock all the maps except cog2, donut3, and maybe horizon. Set the pop lock to 80.
Oshan, Manta, Kondaru, the RP maps, all of them are still too small and they'll suffer in case of superhighpop we currently have. You feel that cog1 is the problem because that's the most popular map.
As people might complain about proposed changes, opening goon2 overflow seems like a good idea. Both 2 and RP suffer from overpopulation, both of them need an overflow server. That will give everyone an opportunity to play on their favourite maps, while also keeping people from choosing cog1 on 100 pop over and over again. But that's up to Wire I guess

**Comment by moonlol** [comment]
oh yeah the other maps, but isnt oshan big enough for high pop?

**Comment by TTerc** [comment]
hmm you're right, I'd go for compromise actually and leave Oshan alone as people might want to play ocean map on highpop too, once in a while
but it can get pretty hellish on highpop

**Comment by Sovexe** [comment]
What if we considered giving certain maps vote modifiers at high pop. Like at 80 plus a vote for donut 3/cog2 counts for 20% more.

That way if players really want it they can have it still

**Comment by moonlol** [comment]
(a bit late but) if people want to play those lower pop maps then can move to the overflow servers

**Comment by Adharainspace** [comment]
water maps have their place in high pop bc theyre much less laggy. but i think this is a good pr, might alleviate some of the overcrowding by people voluntarily voting in smaller maps, fine for lower populations but weve been b

**Pull request merged**
