### PR TITLE
Resprites building materials & standardises their code a bunch

### PR DESCRIPTION
**Pull request by BatElite**
[qol][cleanliness]
## About the PR 
This PR started out with the idea of updating the sprites for construction materials (sheets, rods and floor tiles) while also making the stacks indicate roughly the amount of material left. There's sprites for every 10 units up to 50 for rods/sheets and 80 for tiles.

afbeelding

However, building material consumption code was inconsistent and not everything called the procs or updated the graphics accordingly, so I made what I could find use the `change_stack_amount` and `update_stack_appearance` instead.

`change_stack_amount` now returns early if the difference would make for a negative `amount` where I guess it just didn't care beforehand. Some interactions with rods(/sheets) depend on something like this being present.

Because the cleanup ended up quite scattershot all over the codebase, I can't guarantee everything being exactly right but I did test a bunch of stuff I could. I've also made an effort to preserve previous functionality/messages even if that means the materials don't work exactly alike.

## Why's this needed? 
-Looks better and the sprites are not as giant.
-Behaviour should be subtly more consistent especially with stuff like the inventory counters.
-You can tell (for normal stacks) roughly how large they are.
-Finally different types of sheets (reinforced vs regular, glass vs metal) now shows up differently in map editors.

## Changelog
```changelog
(u)BatElite & ZeWaka
(*)Material sheets, rods and tiles look a lot better now. They also show roughly the amount that's on a stack.
```

### CODE REVIEW

**Comment by Gannets** [comment]
These look rad

**Comment by MatheusIsNotAvailable** [comment]
Imo those floortiles are way too small, will be hard to click them, apart from that the rest looks cool.

**Comment by ZeWaka** [comment]
not a fan of these sheets, they look abysmally small
also discussed this in adminchat and others shared my opinion

the reinforced metal also just looks like floortiles

**Comment by Studenterhue** [comment]
I echo ZeWaka's sentiments, but I personally also want to add that the sheets don't have to be the same chonky-ass size as the original. Making them a couple pixels wider might work!

**Comment by Azrun** [comment]
The height of the mini-stacks remind me of pavers or blocks of ice. 

The visual indication of stack size is really cool but my 🧠 see stack of big heavy thingies. Not sure if some variation in the height dimension would help convey many thin items or just muddy the sprites 😔.

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
Not sure if any changes have been made on this one yet based on feedback, so for clarity I'm going to request changes here and reiterate some of the points brought up both here and in admin chat when this was discussed a week or so ago.

- The **material sheets** should be a bit bigger. Maybe like 2-4 pixels in x/y
- **Reinforced sheets**: Both the metal and glass sheets need something of a redesign. They don't really read as "reinforced", they don't look like they are _tougher_ than the standard sheets. 
    - Regarding the **reinforced glass** sheets specifically, it was mentioned that they look a bit like cracked glass given the pixels on the sheet that are the shine that is retained from the unreinforced glass.
- **Rods**. They look a bit too short/small, more like steel pegs. (personally, the shading on the bottom part of it made it look a bit like tubes to me). It's important that the rods really read as being big-ish rods because they are a decent melee weapon too.

**Pull request merged**
