### PR TITLE
Remove all abstract toolboxes

### LINKED ISSUE #13937: There's an abstract toolbox in the aviary on Kondaru
### Labels

[BUG] [TRIVIAL]

### Description

it keeps pausing my game when i'm debugging

### Steps to reproduce

1. Load kondaru with `CHECK_MORE_RUNTIMES` enabled
2. Runtime due to abstract instantiation

### Expected Behavior

no runtime

### Additional Information & Screenshots

it's this one
image

### PR DESCRIPTION
**Pull request by TheTyrant25**
## About the PR
Removes the multiple abstract toolboxes across multiple maps (even ones not in use, for completeness):
- In kondaru, 1 toolbox in the aviary, replaces it with an actual lunchbox (what it was supposed to be). Same in fleet.
- wrestlemap had 4 abstract toolboxes, which have been replaced with blue empty mechanical toolboxes.
- manta had 1 in the ghostdrone factory, as did horizon and crash_gimmick. replaced with blue empty mechanical ones.
- donut3 had one in engineering for some odd reason. Replaced with an empty mechanical blue one.
## Why's this needed?
Bugs bad. Fixes #13937

### CODE REVIEW

**Comment by TheTyrant25** [comment]
seems like it was meant to be a var edited toolbox or something? but i've just made it an emergency one for now. @Kubius if you meant for it to be a specific in joke or something do let me know and i'll var edit it back.

**Comment by Kubius** [comment]
Its intent was as a "lunchbox", so an emergency toolbox likely wouldn't be a good counterpart. Could just eliminate it entirely; it's thoroughly nonessential.

**Comment by CheffieGithub** [comment]
just make it a lunchbox item, its a box subtype

**Comment by Kubius** [comment]
Oh, neat.

**Comment by TheTyrant25** [comment]
i have somehow accidentally created 150 thousand lines of changes
i'm trying to fix this

**Pull request merged**
