### PR TITLE
Donut 3 sec layout modifications

### PR DESCRIPTION
**Pull request by Chatauscours**
## About the PR 
This PR rebuilds a part of the sec on donut 3, especially the foyer and the equipment room.

## Why's this needed? 
The sec on donut 3 was always a bit bland. The foyer/checkpoint is not very useful and more of a liability than an actual front desk. That same foyer is not very prectical to use, as the Secmate computer is on the opposite side of the room, blocked by Hooty, there are no camer, lack of tools for a front desk, making that generally never used in comparison to other maps, notably due to it being separated from main sec. And a front desk not used is a shame, especially on RP.

## Changelog

```changelog
(u)Chatauscours
(*)Modifies the foyer, main sec, south brig, equip and dorms in the security area of donut 3.
```

### Old:
old32

### Original proposition:
New

### First revision:
new2

### CODE REVIEW

**Comment by Eagletanker** [comment]
Might want to update your old picture to the current donut 3 layout. Also this seems to decrease the amount of room available at the front, along with making going in and out of sec a hassle. There is also no room to set up flashers

**Comment by Chatauscours** [comment]
> Might want to update your old picture to the current donut 3 layout. Also this seems to decrease the amount of room available at the front, along with making going in and out of sec a hassle. There is also no room to set up flashers. (Side Note purely personal tastes but those rooms are bland as hell)

Updated the current donut 3 layout picture. Changed the front room to add more place to walk as well as a place for the flashers (in the bushes).  Added some things here and there, as well as changed some floors to remove some blandness. Please let me know what do you think about it.

**Comment by ThatFiveGuys** [comment]
The shape and general feel of the old equipment room i feel is a lot nicer, dont like the addition of additional hacking tools for sec to use. I think the desk feels shoved in currently, maybe have the enterance be from the equipment room instead of main sec, remove the security access requirement on the outside doors of the sec enterance, and have the table be in the middle of the computers instead of to the right. I feel itd allow it to feel much more organic.

**Comment by Chatauscours** [comment]
So, I reverted most of the equipment room modifications, and pushed it back a little, gaining some more place in the checkpoint, which I modified to do an Oshan-like desc, which I actually like. If a second door in the main entrance is needed, it could be possible to remove the Personnal computer in the checkpoint and place a door here. Tell me what you think @ThatFiveGuys @nefarious6th 
Снимок экрана (104)

**Comment by ThatFiveGuys** [comment]
Much better however I think there are a few things that are off. I think having a wall instead of a window on the other side of the door that leads to the desk would make it look a lot nicer. Also the tiling doesnt blend in well with the rest of security and the hallway, I dont know if you have enough room to blend from black and red tiling to white and red tiling then to grey tiling. Also it is hard to make red and white tiling look good so it may be worth just scrapping that tile color scheme entirely for that area. The shape of the tiling just doesnt look good, mess around here and just find one that looks nice. 

I think moving the doors to the edges of the enterance and having two doors with benches in the middle would help a lot with the flow.

**Comment by nefarious6th** [comment]
much bigger fan of a more approachable front desk here versus that thing across from the teleporter. i think i could live with the one door if it meant making the front desk more findable like you have it here.
looks good, nicely done.

**Comment by Chatauscours** [comment]
Not stale, just exams consuming huge amounts of time

**Comment by Chatauscours** [comment]
So, I did reswapped the floors, but with the wall on the other side it just look wierd, without it too, so I dedcided to tweak the layout a bit. Here is how it looks now ingame:
D3 foyer

Right now for me it looks good, but as always I'm willing to discuss any potential changes.

**Comment by Chatauscours** [comment]
Uuuuuuuh... Either checks are dumb, or I am missing something, because the map is compiling just fine when I'm hosting it locally.

**Comment by ZeWaka** [comment]
> Uuuuuuuh... Either checks are dumb, or I am missing something, because the map is compiling just fine when I'm hosting it locally.

maybe you have local changes?

**Comment by Chatauscours** [comment]
Yay, that fixed it. It was about darts being changed recently, making it a new subtype,and the ones I used were the old ones, but now it 's fixed.

**Pull request closed without merging**
