### PR TITLE
Donut2 Bridge revamp

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr spices up donut2 bridge, CE office, and hops office in order to make them much nicer.
image
image

Also ends up adding a new carpet and glassblock variant for the map, and also a minor bug fix with pod fuel tanks to make the broken down car in the CEs office work properly. 
image
image

## Why's this needed? 
I think this looks much nicer and this is a more fitting place for a hop office.

## Changelog

```changelog
(u)Ikea
(*)Donut2 bridge has been overhauled
```

### CODE REVIEW

**Review by Sord213 — COMMENTED** [review]
The central area feels weird with just empty space with a glass floor in it. Could be you get stuck by wormholes, being shoved in roundstart, teleporter malfunctions, etc. If you got plopped in there without tools you're just stuck with no way out which is bad. 

I dislike the CE's office being changed from a usable space to tiny undecorated broomcloset for no reason other than "small broom closet funny"

The top right corner of the bridge is strangely empty, could use something? Booze vendor? Microwave? Something.
Screenshot_650

Mail chute should be moved out of the radio room and into bridge proper, same with the lockdown control buttons.

I dislike the windows in the entryway, makes it even more trivial to break into the bridge, even if it was electrified it makes very little difference. Would prefer just a wall + solid doors on the bridge side so you can't see into bridge from the hallway as it was before.
Screenshot_649

As for the ID office...eh. This removes all use from the courtroom as the ID desk (as intended) and makes the courtroom become a completely unused space compared to what it is now; the ID office.
If I had to add one feedback for the ID office, it would be that with the lockdown doors being the way they are a backdoor into maint would be necessary, plus the crime/breakin option.

Overall not a fan of these changes.

edit: there's also an errant glass floor tile up by the aux comms dish.

**Comment by t-toasted** [comment]
Lengthy discussion in the Mapper chat, but I’ll put my official statement here too:

Unintuitive design is not fun design for most players. The HoP office not being included in bridge lockdown is odd, and very odd on a map that is not otherwise outright unintuitive. It is something that, if implemented, would be PR’d away in a fix weeks later by my guess. Also takes away the usage for the courtroom HoP office.

CE closet being a closet is funny but not exactly great for the CE. Wouldn’t mind if it was, say, in addition to a proper office. But your explanation again for the car being in a weird spot for a ‘challenge’ again would not be very fun after a bit. 

I really like the central bit honestly. This is such a cute and unique bridge, and a fantastic use of the floors. Maybe having a wrench in the middle by default or a table missing and instead being a fence to prevent any issues.

**Comment by ThatFiveGuys** [comment]
> But your explanation again for the car being in a weird spot for a ‘challenge’ again would not be very fun after a bit.

To clarify this for people who wont here for that discord conversation/my intents regarding the car, the car is intentionally a bit hard to drive out, with a few places you can get it stuck. This is for two reasons, 1. I want this to be a decoration thats a car instead of a car thats a decoration. I want this car to be a background object the majority of the round, as I think its more interesting to have the car being driven around as an exception instead of a rule. The main reason why the car starts broken and you have to drive it out carefully is to act as discouragement for CEs to just do it every round, and instead as something they only do once or twice. And also 2. Half of the fun of cars is getting it stuck in a really inconvenient place. You either have to break a wall and drive it out, or you have to just leave it there and now theres that barrier thats just there and that to me is always a funny thing when it comes up in game.

**Comment by ThatFiveGuys** [comment]
Alright decided to do several changes, going to list the changes I made and why I made them:

Moved mail chute outside of radio room and replaced radio room chute with a disposals chute:
Keeps the bit of the oil slipping you into the chute, and also allows command to actually know when an item gets sent to them.

Moved coffee machine + glass table to top right of bridge and replaced coffee machine with cigarette machine:
While I think the deadspace was nice, I also think that with the mail chute the area near where the wine table was looked cramped. It opens up that area. Also smoking is cool.

Moved lockdown buttons to table:
Just a more visible place for these things.

Moved teleporter beacon off the table and to the right:
Lowers the chance of people getting teleported inside of the prison table.

Adds a mechanical toolbox to the table: 
Gives a way for people who got stuck there to break loose.

Prettied up CEs office: 
While I like gritty its not an asthetic for everyone and this should make people more happy. 

Adds a maintenance door to hop office:
crime

Moved the lockdown shutters to the right for the main entrance: 
This allows for the first entrance to serve as a stopgap entrance to allow people to notice people breaking in, thus run to lockdown the bridge. 

Electrified the plasma windows: 
The bridge entrance is balanced primarily around lockdown, as during nukie rounds when they plant in bridge it can often dominate the round. With the glass changes, hacking through plasmawindows take more time then hacking through doors, this doesnt really impact the difficulty/easiness of a tider breaking into the bridge. What this does do however, is introduce a way to break into bridge even when lockdown is in effect, just a slow way. The electrification will impede in the case of revs beating down the window, but it wont impede for an engineer hacking into the bridge to open the way for nukies. This should make bridge nukie plants on donut2 more interesting as you get a really good chokepoint with harder ways around said chokepoint, instead of it just being people standing around outside of bridge due to emergency shutters having infinite health.

**Comment by WALPVRGIS** [comment]
Those transparent floors sprites look really weird to me, it doesn't take depth into account. If you want I'll merge some transparent glass versions that I'm happier with for you to replace them with (I intended to forever ago and forgot oop)

**Comment by ThatFiveGuys** [comment]
> Those transparent floors sprites look really weird to me, it doesn't take depth into account. If you want I'll merge some transparent glass versions that I'm happier with for you to replace them with (I intended to forever ago and forgot oop)

That would be very appreciated

**Pull request closed without merging**
