### PR TITLE
Adds the Paper Cigarette Packet

### PR DESCRIPTION
**Pull request by trazodont**
## About the PR 

Adds the paper cigarette packet as a paper folding option.

## Why's this needed? 

Gives botanists (or anyone really) the ability to make their own packets for custom cigs and joints. Currently the only way to get packets is by buying (or button vending) packets out of the cig vendor. The previous tgui menu for paper folding had to be changed to allow for more than 3 options, if a different menu is wanted, if can be changed.

image
image

## Changelog 

```changelog
(u)Shiiba
(*)Adds the paper folding option for cigarette packets, make your own customs joints and cigs today!
```

### CODE REVIEW

**Comment by RelentlessGarbage** [comment]
I like this - lets botany make more custom products, which I'm all for.

**Comment by TDHooligan** [comment]
good idea. would be neato if these also let you name them with a pen

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Uhh I think you accidentally removed the folding code?

**Comment by trazodont** [comment]
> Uhh I think you accidentally removed the folding code?

WHAT oh my god how tf did I do THAT

**Comment by trazodont** [comment]
> Uhh I think you accidentally removed the folding code?

Okay SHOULD be good, no idea what happened

**Pull request merged**
