### PR TITLE
Nerfs mousetrap bombs

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BALANCE]
## About the PR 
Makes mousetrap bombs have a 0.7 second activation delay when they go off in your hands and makes the inventory they are in still open when activated.
This makes it possible to throw in time to escape the explosion if you're expecting it, but still likely to catch you off guard if you are not.

## Why's this needed? 
image
image
image

## Changelog

```changelog
(u)LeahTheTech
(+)Mousetrap bombs now have a short activation delay if they are set off in your hands.
```

### CODE REVIEW

**Comment by TDHooligan** [comment]
> honestly, I don't see how this is too big of an issue, since if it ends up killing the secoff chances are it'll gib you as well. If you wanna kill the person that arrested you, you also get to die. That seems pretty fair and balanced.

a huge number of explosion gib ranges are 1 tile iirc, so you don't die

**Comment by TobleroneSwordfish** [comment]
Basically the way I've been doing it is: make phlog + steel pipe bombs, put them in backpacks and hand them to people. So far one single person hasn't fallen for it and instantly gibbed and that's because I bombed the cloner in front of them.
Also phlog pipe bombs only gib on the exact tile they are on, and do moderate damage otherwise (because `ex_act` is a whole mess on its own)
Personally I'm indifferent to this existing, but Cal asked me to PR a nerf and it does seem a little bullshit.

**Comment by MitchTheUser** [comment]
Personally, I feel this weakens floor mousetrap bombs incredibly as most people will be on the edge of the bombs radius if they are simply walking over it without stopping, and I feel that 0.7 seconds isn't going to save people even if they are expecting it.

**Comment by TDHooligan** [comment]
a lazy fix would be to move the SPAWN to the backpack's proc call instead, which would hypothetically mean someone very quick can also grab it out of the back.

**Comment by ThatFiveGuys** [comment]
Reworking it to support multiple contexts seems best, I think making it be instant for stepping but not instant for openning is good. As is balance aside backpack mousetraps just arent interesting, having the interaction be you open backpack, instagibbed, is bad, turning the interaction from you open backpack, oh shit theres a bomb, probably gibbed anyways is way more interesting

**Pull request closed without merging**
