### PR TITLE
Roboticist belt on spawn

### PR DESCRIPTION
**Pull request by NightmareChamillian**
## About the PR 
This PR gives robotics a special belt they start with on spawn, that contains a crowbar, screwdriver, weldingtool, wrench, wirecutters, scalpel, and surgical saw, but removes their toobox. It looks like this:
image

## Why's this needed? 
Roboticists spawning with a generic toolbox has always seemed a little weird/short-term, and it's a lot nicer to have all your basics when you spawn in.

## Changelog

```changelog
(u)NightmareChamillian
(+)Roboticists now spawn with a stocked toolbelt
```

### CODE REVIEW

**Comment by frawhst** [comment]
What's it look like when worn?

**Comment by NightmareChamillian** [comment]
> What's it look like when worn?

It uses the same worn state as a secbelt, since they're the same general color and the roboticist's belts are almost always under their coats, though if this is problematic I can change it.

**Comment by frawhst** [comment]
Yeah, it does look a bit too close to a sec belt for me. Could make it white if you want to keep with the robotics white/black color scheme, or even grey.

**Comment by NightmareChamillian** [comment]
update: It now has a special worn sprite:

image

I did mess around with lightening the icon, but decided it didn't either didn't look good or was too close to justify changing, especially since their icons look very, very different side by side

image

If I'm wrong about it I still do have a lighter sprite to use, though. It's up to you @frawhst 
image

**Comment by frawhst** [comment]
Works for me; will wait on feedback from someone who knows more about sprites, though.

**Comment by NightmareChamillian** [comment]
update: it would appear in a haze of sleep deprivation I accidentally did in fact add the lighter sprite last night that also looks good. Works for me.

**Comment by ThyOverlord** [comment]
Looks good! looks pretty recognizable and small too! doubt it will get mistaken at all!

**Comment by frawhst** [comment]
icon diffs are broken why is this a cursed PR

**Review by frawhst — APPROVED** [review]
but yeah lgtm

**Pull request merged**
