### PR TITLE
Rockbox UI quality of life changes

### PR DESCRIPTION
**Pull request by Merlin1230**
[feature] [QoL]

## About the PR 
This makes it so you can eject ores when the ejection amount is set higher then the number of ores, where it will then just eject all the ores it can. The ejection button will be orange, like this:
image

On top of that, the UI will update everytime a ore gets added, which makes it look a whole lot smoother

## Why's this needed? 
Someone in the discord talked about wanting this, and I didn't like how choppy it looked when you added ores.

### CODE REVIEW

**Comment by ZeWaka** [comment]
sadly, [freeze]

**Comment by BatElite** [comment]
orange reads to me more like ejecting isn't possible, don't know what colour would be suitable though.

**Comment by Merlin1230** [comment]
Yeah, I'm not 100% on the orange, and I'm not sure what color to use. I could just make it the same default blue.

**Comment by flappybatpal** [comment]
Personal request, for it to list properties of the material for player QOL. Giving this info is a big help for players to learn what materials do what.

So displaying metal, sturdy metal, conductive material etc.

**Comment by Merlin1230** [comment]
> Personal request, for it to list properties of the material for player QOL. Giving this info is a big help for players to learn what materials do what.
> 
> 
> 
> So displaying metal, sturdy metal, conductive material etc.

It already shows what would show up on a mat analyzer as a tooltip, just without the number. Of course it doesn't show something like clarentine as a high energy conductor, it just says its conductive. I could try and make it show if it would count as a high energy conductor and such, however.

**Pull request merged**
