### PR TITLE
Engineering toolboxes now come with glass and metal sheets

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
The milk and pbj has been replaced by 50 glass sheets and 50 metal sheets

## Why's this needed? 
The ones in engineering storage can easily be gone, and these are pretty essiental to the job. Also this should hopefully make the toolboxes more used instead of them being tossed on a table and forgotten.

## Changelog

```changelog
(u)Ikea
(*)Engineering toolboxes now come with metal and glass sheets.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
Do you think you could ditch the banana and leave the peanut butter sandwich? 80% of the time I use it for the minor healing and/or the stamina buffs it gives, since it's a really really nice thing to have.

**Comment by ThatFiveGuys** [comment]
Yeah but banana slips people and thats funny (also the banana doesnt contain potassium but if it did (which it should) engineers could use the banana to cause themselves to explode, which is a galaxy brain molitz b strat that i very much approve of)

**Comment by BatElite** [comment]
I feel like a better course of action is to make mining connect more effectively with the station since they mine *a lot* of shit

takes like 5 ores for a full stack, it's almost maddening how much stuff they just uselessly sit on.

**Comment by ThatFiveGuys** [comment]
Very much outside of scope for this pr (i have other prs in the work for mining), and also id prefer mining as mostly a power booster to where it helps but it not being involved doesnt hurt.

**Comment by ThatFiveGuys** [comment]
The majority of the time its both way too small for 5 engineers (only like 2 stacks of metal) and gets stolen often anyways. Also a big part of this change is currently the toolboxes engineers spawn with have minimal initial value and by informing players you can fit sheets into them you make them feel more worthwhile to carry around

**Comment by Kubius** [comment]
I think that the sandwich should be preserved, potentially in lieu of the soldering iron. Sheets wise, I have two main comments - it could potentially be a lower count (20 of each?) to avoid giving out so much for free, and it should be either basic metal and glass sheets, or basic metal and reinforced glass.

**Comment by flrsh** [comment]
> This seems like a nice QoL change but... Engineers should already have access to at least one cache of glass and metal sheets on existing maps. Couple maps have breach repair carts as well. If more resources are required they can be ordered from QM (cooperation!) or Fabricated (Mining win!).

**Pull request closed without merging**
