### PR TITLE
Locking Genebooth and Ruckingenur Kit

### PR DESCRIPTION
**Pull request by Azrun**
[feature][balance][help wanted]
## About the PR 
- Adds ability to disable printing of blueprints (on a per blueprint basis) on rkit, those with permission will get an additional option to lock/unlock or print directly. 
- Adds ability to remove downloaded (loaded through blueprint) schematics from fabricator, prompt is provided to ensure correct action is performed.
- Adds ability to disable specific mutations from genebooth, those with permission will get a separate dialog with options to adjust the price and lock/unlock.

- Access is gated using `allowed()` which makes it work without changing state of the device. (Input Wanted)
- Access is based on heads instead of Medical Director and CE. (Input Wanted)

Ruckingenur Kit
Screenshot 2021-03-23 151723

Fabricators
Screenshot 2021-03-29 212545
Screenshot 2021-03-23 152029
Screenshot 2021-03-29 212750

Genebooth:
Screenshot 2021-03-23 153727

## Why's this needed? 
Gives Heads the ability to deal with undesirable genes and fabricated items non-destructively. 
Counter-play shenanigans is available by procuring sufficient access.

## Changelog

```changelog
(u)Azrun
(*)Allows department head of staff to lock down output from Genebooth and Ruckingenur Kit.
(+)Department heads can now adjust price of Genebooth items as well as delete downloaded schematics from fabricators.
```

### CODE REVIEW

**Comment by MatheusIsNotAvailable** [comment]
If I scan something on the ruck kit back on station does it still appear on the one at the mech outpost?, if it does, maybe it shouldn't so people can still sneak to there and start a new operation after theirs gets busted by the heads.

will heads be able to delete stuff from every fab or only from the the ones you put the blueprints on and only the blueprints? I think that aspect of this isn't very needed because you already could just destroy the fab.

I don't think every head should be able to delete the stuff from the ruck kit/gene booth, only the heads of the respective department, captain and HoS. Just makes more sense to me.

This is a good change overall ye, way more fun for both people trying to counter bad stuff being made with those and also for people that made the bad stuff since the only solution right now is blowing it up, wich sucks for everyone. Why no [INPUT WANTED] label though? This feels like it would need one.

**Comment by Azrun** [comment]
> If I scan something on the ruck kit back on station does it still appear on the one at the mech outpost?, if it does, maybe it shouldn't so people can still sneak to there and start a new operation after theirs gets busted by the heads.

Should still show up there.  I'm going to make it so the lock doesn't have any affect on _that_ rkit though.

> will heads be able to delete stuff from every fab or only from the the ones you put the blueprints on and only the blueprints? I think that aspect of this isn't very needed because you already could just destroy the fab.

Only from that specific fab and only items loaded with blueprints.  Idea is to avoid destroying the fab.

> I don't think every head should be able to delete the stuff from the ruck kit/gene booth, only the heads of the respective department, captain and HoS. Just makes more sense to me.

I choose to share some of the responsibility.  If some heads are not available, there should be someone available that can remedy the situation.  Is this just a too many cooks situation or are there concerns with other heads mucking with things that our outside their lane? CE running in, unlocking the crazy genes and getting them for free and running off? Captain could do the same...

> This is a good change overall ye, way more fun for both people trying to counter bad stuff being made with those and also for people that made the bad stuff since the only solution right now is blowing it up, wich sucks for everyone. Why no [INPUT WANTED] label though? This feels like it would need one.

Was going to slap Input Wanted after preliminary feedback, assuming it still jives with what I think makes sense.

**Comment by Yellow-Mushroom** [comment]
I think this is a pretty good PR since if an EMAG or gun gets uploaded to the ruck, sec either has to shut down mech or just hope no one prints any contraband which is just... not fun on RP

**Comment by penny64** [comment]
Hey still massively in favor of this I think even the problems presented or just social mechanics, it'll be fun

**Comment by Tarmunora** [comment]
Hm. Might be good if there was some evidence that something *was* in the rkit, so you can't print something and then delete it sneakily.

**Comment by Azrun** [comment]
> 
> 
> Hm. Might be good if there was some evidence that something _was_ in the rkit, so you can't print something and then delete it sneakily.

Something like an audit log that can't be deleted? Time+Product. Then you could forensics (+luminol) your way to an answer?

**Review by Tarmunora — APPROVED** [review]
in-game/logging can be handled in a followup probably

**Comment by pali6** [comment]
I'd rather also limit this to the respective heads instead of all heads.

**Review by pali6 — APPROVED** [review]

**Comment by Azrun** [comment]
Updated access to include Cap, HoP, HoS (maxsec), and CE/MD respectively. Following suggestion from @zjdtmkhzt, @flrsh, @pali6, and others. 🍻

**Pull request merged**
