### PR TITLE
Removes the majority of Thindows from Cogmap 1 and Cogmap2

### PR DESCRIPTION
**Pull request by comradef191**
[MAPPING] [BUG] [INPUT WANTED]
## About the PR 

Reworks and edits current Cogmap 1 & 2to completely remove as many remaining Thindows as possible.
Cogmap 1 AI satellite & Medbay is _excluded_ from this PR, and will be modified in a follow-up PR due to the large amount of changes that will need to be made in order to accommodate these sections.

**Cogmap 1:**
- [x] Rework Interrogation Room
- [x] Remove Thindows from Brig Visitation
- [ ] ~~Rework AI Upload & Computer Core Entrance + SMES room~~
- [x] Rework Chemistry Lab Shower
- [x] Rework Escape Animal Windows
- [x] Rework & remove Thindows, Where possible, from Belt Hell
- [x] Rework the Gym
- [x] Rework Chapel Office & Mass Driver
- [x] Rework Mechanics Computer & MailChute
- [x] Rework the Engine
_(Advise creation of improved Railing Sprites, Current ones are rather.... ugly)_
- [x] Rework Engineering Storage
- [x] Rework QM Desk & warehouse ABCU 
- [x] Rework Northern Medical Booth, Tool Storage & Botany desks
_(Medical Booth requires the creation of a dedicated North-facing sprite for the Perspective Windoor)_
- [ ] ~~Rework Medbay~~

**Cogmap 2:**
- [x] Remove thindows from AI Core, Armoury IR detectors & PTL Path; replace with full windows
- [x] Rework Brig Visitation

## Why's this needed? 

Numerous known bugs with Thindows, alongside it being expressly against the Mapping Guidelines and, generally, ugly.

## Changelog

```changelog
(u)Comradef191
(*)Cogmap 1: Expanded the Warehouse; Interrogation Room; Arrivals; Gym; QM; Brig Visitation, and Engineering Storage in order to minimise the usage of 'Thindows', replaced the Thindows in the Engine with Railings and swapped Thindows at many desks with Perspective ThinDoors.
(+)Cogmap1: Added a Forensics Locker to the Interrogation Room
```

### CODE REVIEW

**Comment by comradef191** [comment]
Belt Hell Thindows Partially removed, need to evaluate requirement of these Thindows, and if needed rework belt hell router, else; simply remove
image

**Comment by comradef191** [comment]
Due to the rather... Extensive modifications that will be required in order to remove Thindows _Entirely_ from Cogmap 1, I will be splitting to changes to the AI Satellite into a seperate PR so as to minimise difficultly in reversion or review.

**Comment by PrimeNumb** [comment]
I would suggest fixing thindows rather than just outright removing them. Thindoors, for example, do not suffer from the same issues and are basically thindows with door functionality.

**Comment by comradef191** [comment]
Closed in favour of #3542, only took em,..... ughhh..... way too fucking long...

**Comment by comradef191** [comment]
they're still broken af nevermind lol

**Comment by moonlol** [comment]
> they're still broken af nevermind lol

How are they broken?

**Comment by comradef191** [comment]
> How are they broken?
i'm going off of zewaka's saying
when they declare them not broken then yeah sure

**Comment by moonlol** [comment]
> > How are they broken?
> 
> i'm going off of what zewaka's saying
> when they declare them not broken then yeah sure

the supposed issue is from a very old post that pali said they had no luck replicating. I myself had no luck replicating, and that issue came from when thindows didn't act as full windows in respect to atmos.

**Comment by comradef191** [comment]
> the supposed issue is from a very old post that pali said they had no luck replicating. I myself had no luck replicating, and that issue came from when thindows didn't act as full windows in respect to atmos.

bruh poke @ zewaka not me
when they say they aint broke, sure

**Comment by flappybatpal** [comment]
The problem with thindows is even bug fixed people will still destroy them to get into cog1 operating theatre.

People don't respect them.

**Comment by comradef191** [comment]
yaaay conflicts woop woop ill fix these at somepoint soon:tm:

**Comment by ZeWaka** [comment]
please atomize your PRs to 1 map maximum for stuff like this.

**Pull request closed without merging**
