### PR TITLE
Shambler + Headspider perspective

### PR DESCRIPTION
**Pull request by binarysudoku**
[human resprite]

ling_anim_test_8

image

### CODE REVIEW

**Comment by Kapu1178** [comment]
jesus christ

**Comment by Flaborized** [comment]
absolutely fantastic

**Comment by Carbadox** [comment]
I feel like the head spider would have a spookier face. As is, it just kinda of looks unimpressed with his surrounding.

**Review by Gannets — APPROVED** [review]

**Comment by binarysudoku** [comment]
EAT SHIT, MERGE CONFLICTS

**Comment by Gannets** [comment]
Green means go

**Pull request merged**
