### PR TITLE
Watering can reagent amount

### PR DESCRIPTION
**Pull request by Nitre88**
[Hydroponics] [QOL]
## About the PR 

Fixes issue https://github.com/goonstation/goonstation/issues/14804
Adds correct amount poured from watering cans(and other containers) when used on hydroponic trays

## Why's this needed? 

The game currently shows the amount per transfer which is the maximum instead of what the reagents are actually transfering.
This would improve the correctness of ingame feedback your given. When interacting with hydroponics

### CODE REVIEW

**Comment by Nitre88** [comment]
and another one

**Comment by TheTyrant25** [comment]
everything okay?

**Comment by Nitre88** [comment]
did a thing you arn't supposed to do. committed stuff to my master master branch

**Comment by Nitre88** [comment]
fixed maybe

**Comment by TheTyrant25** [comment]
my condolences

**Pull request closed without merging**
