### PR TITLE
Kondaru move to standard rotation

### PR DESCRIPTION
**Pull request by Kubius**
## About the PR 

- playerPickable flag for map switched from ASS_JAM to 1. oh boy

- Cryo room's area type now /area/station/crewquarters/cryotron

- Added voting box outside cryo room

- Swapped Zoldorf and loudspeaker in bar to give Zoldorf more space

- Added robustris pro and claw machine to arcade

- Put some atmos analyzer upgrades in Engineering (2 in core, 1 in main)

## Why's this needed? 

Reception of the map during Ass Jam was positive both ingame and out of game (with several people immediately requesting it stick around), and I had intended the map for rotation sooner rather then later - despite my apprehension, I figured I may as well get the request over with.

I fully intend to support this map on an ongoing basis, now that I am capable of doing so, and believe it has much better current quality and future potential than its Kubius map predecessors.

## Changelog

```
(u)Kubius:
(*)Kondaru (Kubius Map 3: Third Time's the Charm) has moved into official rotation.
```

### CODE REVIEW

**Comment by geneva-breaker** [comment]
Map has issues to correct before rotation. Will elaborate further

**Comment by ZeWaka** [comment]
Applied DNM re: above

**Comment by PrimeNumb** [comment]
I love everything about this map. It is neatly dense, which greatly nudges people into interacting with one another. Even the miners are close to high-traffic areas!

Points of interest, such as the armory and AI core, are heavily defended and take a bit of extra effort to break into, as opposed to breaching armory from space completely unhindered like on cog1.

Most departments have easy or immediate access to the main hallway. Chemnerds (and their interdepartmental equivalents) may actually be bothered by actual living beings now, instead of sitting comfortably deep inside research, never to be seen by outsiders.

Kondaru has some of the best maintenance tunnels design I've seen yet, hands down. 
If you want to take a stealthy approach, you can get around most of the station just using the maintenance. It is an _amazing_ antagonist experience to crawl these tunnels.

Seeing this merged into the regular rotation of maps is something I absolutely support.

**Comment by Kubius** [comment]
Additional commit (23ec9bd) added to fix a couple things alongside rotation-ification, which include an issue raised externally by @geneva-breaker - PR description updated with all included changes.

**Pull request merged**
