### PR TITLE
Documents the fact that the NT loyalist trait prevents you from spawning as a revhead

### PR DESCRIPTION
**Pull request by frawhst**
## About the PR 
Adds a bit of text to the trait description to clarify that behavior.
I'm kinda uninspired and can't think of a way to make it clear without sounding janky, so feel free to suggest something better.

## Why's this needed? 
It's a thing people should probably know

### CODE REVIEW

**Review by Azrun — APPROVED** [review]
Should this provide some kind of visual cue in antagonist selection? #FeatureCreep

**Comment by PrimeNumb** [comment]
Question is if this behavior should even remain. Seems a bit awkward to lock someone out of being a specific antagonist because they chose to spawn with a funny hat.

**Comment by frawhst** [comment]
> Should this provide some kind of visual cue in antagonist selection? #FeatureCreep

I could grey out revhead if you have the trait, but I feel like that would only add to confusion.

> Question is if this behavior should even remain. Seems a bit awkward to lock someone out of being a specific antagonist because they chose to spawn with a funny hat.

It was discussed a bit on discord and the consensus seemed to be "makes sense, I guess". I'll make a forum thread in a min.

**Comment by Azrun** [comment]
> > Should this provide some kind of visual cue in antagonist selection? #FeatureCreep
> 
> I could grey out revhead if you have the trait, but I feel like that would only add to confusion.

On Hover with explanation seems like that should solve that. But I don't think that UX is really consistent...

**Comment by frawhst** [comment]
turns out the variable doesn't do anything? I think? there's a bunch of smelly nonsensical code surrounding any use of it so i'm going to conclude that I was making a hubbub about nothing. Will probably clean out jobcode in the future to avoid this kinda confusion from happening again.

**Pull request closed without merging**
