### PR TITLE
Changes the headrev icon background to red

### PR DESCRIPTION
**Pull request by Chatauscours**
[QOL]

## About the PR 
This PR changes the revhead icon background to a red, both on sechud and rev overlays. It also gives the normal revs the old headrev icons

## Why's this needed? 
This is needed because it is sometimes frustrating to do the difference between Revhead and Released, especially for newer people. The red is used because it is easily spottable and is in accordance with the red of the arrest status.

## Changelog

```changelog
(+)Gives the head revs an icon with a red background with a big white R on the sechud
(+)Gives the head revs an icon with a red background with a big white R on the revs overlay
(+)Gives the normal revs the old head rev icon
```
rev
rev_head

### CODE REVIEW

**Comment by Chatauscours** [comment]
Somehow forgot to agg the demo of the icons to PR description. Here they are
rev_head
rev

**Comment by ZeWaka** [comment]
Changelog is not properly formatted.

**Comment by Chatauscours** [comment]
I agree that swapping the rev icons around would confuse people in the short term, it would though cause a lot less confusion in the long term. The initial confusion will also be quickly gone, as headrevs will see that they have another icon on spawn, and norrmal revs will see a huge load of other normal revs with their icon, making it easy to understand that the icons swapped.
More generally, the red better catches the eye, is easier to spot and is in coherence with the arrest status.
If the change of the rev icons seems to be unsuitable and/or unwanted, I would suggest to rename released for something else, respriting the icon for another letter, as preety much all standart colours are already in use by the sechud. (Though a white R on a gray background for the release status could be possible and would represent well the "not longer a POI" part of the released status). 
Please let me know what you think @BatElite.

**Comment by Chatauscours** [comment]
Uhm did a bad thing by merging accidently fetching upstream, closing PR.

**Pull request closed without merging**
