### PR TITLE
TGUI paper color and noticeboard fixes

### PR DESCRIPTION
**Pull request by keiyakins**
[FEATURE] [TGUI]
## About the PR 

There was a silly little one-line bug in TGUI paper that made the first screenful have a white background, and the rest was colored appropriately to the paper. When I fixed that, I realized noticeboards didn't save the color, and when I looked into *that* I realized they weren't using TGUI paper to show their contents! This fixes all of this, so now people can pin weirdly colored notes and they should just work.

## Why's this needed? 

Making things weird colors with matsci is fun, and having them behave sensibly is good. Plus, the noticeboard now defers to the paper to handle reading and writing, which just makes more sense.

## Changelog

```changelog
(u)Keiya
(+) Colorful paper should now work better, and maintain its colors on persistent noticeboards. 
```

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
You need to rebuild the tgui bundle.

**Comment by keiyakins** [comment]
Ah, sorry, done now. I kinda figured that was done on building the rest of it, or at least on deploy, because to do otherwise sounds like merge conflict city.

**Comment by ZeWaka** [comment]
Design review: Do we really want people to be able to create hideously colored paper for people to read? Or do we want to limit it like we do some things to be within a certain saturation/etc - like we could just have slightly pink colored paper instead of missing texture pink.

**Comment by keiyakins** [comment]
You can already do some pretty hideous colors for the text, and with crayons you even get a color picker. Here, at least, to get something truely offensive (other than maybe hot pink synthrubber) you'd have to futz with matsci for a while.

**Pull request merged**
