### PR TITLE
Command & Security airlocks are now more secure to break-ins.

### PR DESCRIPTION
**Pull request by Zonespace27**
[Balance] [Feature]
## About the PR 
This PR makes command & security (and only them) airlocks much harder to break into. This is done in two ways:

- Airlocks now have a 4 second action bar to screw/unscrew the panel, and will attempt to shock you (cancelling the screwing/unscrewing, should it succeed) on completion.
- Airlocks have a much higher chance to shock you, being guaranteed for wirecutting, and a +50% chance for multitooling.

## Why's this needed? 
As-is, it's trivial to break into high-value areas such as the armory, HoS office, bridge, and AI upload, and the need to get insulated gloves should at least help reduce the ease of breaking in. Also requested by Duke Nukem on discord.

## Changelog

```changelog
(u)Zonespace
(*)Command and Security airlocks now have a 4 second action bar to unscrew their access panel, along with being much more likely to shock you.
```

### CODE REVIEW

**Comment by Sord213** [comment]
Great addition. Couple suggestions of my own, add the action bar (but at a reduced length) to all doors and the shock chances. A sound effect for unscrewing the panel would be nice as well.

**Comment by BatElite** [comment]
Mandatory insuls for hacking sounds like it's going to lead to everyone and their grandma making/stealing them even more than currently. Also, making it easy to just trap people by leaving the doors to their departments unscrewed.

**Comment by Eagletanker** [comment]
Don’t the wire cutters have insulation from the airlocks on their handles? Also, 4 seconds is a tad too much, if the problem is breaking into those high value areas, then it should be a delayed PDA alert to security and command rather than making it take a pretty long time to get into a place. This also fucks over nukie plants in areas such as the bridge or sec on some maps. The multi tool shocking you for hacking in seems kinda weird and unintuitive considering your just testing the wire to see what it does and there’s no indication of you being exposed to electrical hazards while doing so. I also think that should apply to the unscrewing and screwing back on cause that also doesn’t make much sense as your unscrewing the ID scanner and then letting it hang by wires.

**Comment by Zonespace27** [comment]
> Mandatory insuls for hacking sounds like it's going to lead to everyone and their grandma making/stealing them even more than currently. 

I will be touching this in a PR i will be making later today.

> Also, making it easy to just trap people by leaving the doors to their departments unscrewed.

May remove the shock from screwing the panel back in place, not sure yet.

> Don’t the wire cutters have insulation from the airlocks on their handles?

You could get shocked on regular doors too, secure doors just make it _much more likely, if not guaranteed_ that it happens.

> Also, 4 seconds is a tad too much, if the problem is breaking into those high value areas, then it should be a delayed PDA alert to security and command rather than making it take a pretty long time to get into a place. 

These areas are highly secure, and as-is it takes one greytider with matsci gloves just a bare few seconds to screw open a door, cut the ID wire, screw it closed, and now the door's AA.

> This also fucks over nukie plants in areas such as the bridge or sec on some maps.

They get breaching charges, also may take a look at SWAT insulation later.

> The multi tool shocking you for hacking in seems kinda weird and unintuitive considering your just testing the wire to see what it does and there’s no indication of you being exposed to electrical hazards while doing so.

This PR does not add multitool shocking, it already existed, it was just very unlikely. This PR increases the odds of it happening to secure doors, however.

**Comment by Sovexe** [comment]
I have concerns of how communicating this to newer players, if merged

**Comment by Zonespace27** [comment]
> I have concerns of how communicating this to newer players, if merged

Added a description indicator to doors (if they're unscrewed or not, then if they're secure if unscrewed)

**Comment by NightmareChamillian** [comment]
I'd argue _all_ security doors don't really need this. As is, security is resistant to break ins as a native part of the game thanks to the fact that secoffs themselves will usually stop you from breaking into their department. Adding a 4 second long action bar would make it awkward. If you need to stand still for 4 seconds, chances are security is already dead or unable to stop you regardless.

For the bridge and armory, however, I do think the change should go through.

**Comment by virvatuli-gh** [comment]
This is being closed as part of some PR spring cleaning. Please remake the PR if you're still interested in seeing these changes ingame.

**Pull request closed without merging**
