### PR TITLE
Parallax

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[UI] [Feature] [Experimental]

## About the PR:
Adoption, rework, and expansion of #8808.
​

Implements a layer based parallax system. The various features added are catalogued below:
* Each map may be assigned a set of parallax layers, permitting for maps to possess their own distinct layers.
* Each non-station Z-level may be assigned a set of parallax layers, independent of the layers allocated to the station map.
* Support for tessellating parallax layers, such as stars and nebulae; and support for non-tessellating parallax layers, such as Cogwerk's planetary background assets.
* Support for predetermined "centre positions" for non-tessellating parallax layers; in effect the coordinates at which the parallax layer would appear to be centred on a client's screen.
* Support for infinite scrolling of tessellating parallax layers. This system has not yet been expanded to accommodate for non-tessellating layers; this shall be delegated to a future PR.
* Support for recolouring the parallax layers on a specified z-level at runtime by use of an animation, with variable animation time.
* Support for the addition and removal of parallax layers at runtime, which utilise a fade-in and fade-out animation, with variable animation time. Animation types outside of fades have not yet been implemented; this shall be delegated to a future PR.

MD's Office

Each in-rotation space-situated map has been provided with an assemblage of parallax layers, with ship maps possessing slowly scrolling parallax layers, and station maps possessing some of Cogwerk's planets, most predominantly the plasma giant Typhon.

The debris and asteroid fields have both received two asteroid parallax layers, in addition to the two background layers. Z2 and Z4 are both exempt from parallax layers; they will retain their static space turfs until an area based parallax system can be devised.

Alongside recolouring the space parallax layers, the radiation blowout random event will add a "radiation cloud" parallax layer to clients' screens, scrolling rapidly in a random direction.
The meteor shower random event will add a meteor parallax layer to clients' screen, scrolling in the direction of the shower.
The space colours random event will recolour the two background parallax layers to a random colour matrix.

Void parallax layers have been sprited, however they are unused at this time.

## Demonstrations:
General Demonstration, on Cog1: https://streamable.com/g6hwi1

Debris Field Demonstration: https://streamable.com/mjnf98

Scrolling Demonstration, on Clarion: https://streamable.com/q9uj9p

Radiation Blowout Demonstration, on Cog2: https://streamable.com/x7k8xr _(slightly outdated background assets)_

## Performance Impact:
Statistics accurate as of commit [ce36112](https://github.com/goonstation/goonstation/pull/13667/commits/ce36112c95ca658c5d3d35c191f33f6c0e2c45a6).
The following results were collected from `update_parallax_layers()` with 10,000 calls in aggregate. The player was thrown across the debris and asteroid field, both of which have four parallax layers, with parallax values of 0, 0.009, 0.06, and 0.1.

image

On average, each parallax layer costs 17µs-21µs of processing time, however it should be noted that a proportion of this time will be exclusively clientside due to the use of `animate()` in updating parallax layer positions.

I have the stack trace saved, should any performance queries arise.

## Known Bugs:
~~During development, a BYOND bug pertaining to `animate()` arose, which I will be unable to fix; an animation using a colour matrix as the colour value will not correctly animate should another animation be running in parallel. However, using non-matrix colour values will result in less-than-acceptable qualities of parallax layer recolouring, so I have opted to keep the matrix system and accept that it will occasionally skip the animation until the bug can be resolved.~~
_Reported to Lummox and resolved._

A potentially related bug was encountered when implementing scrolling parallax layers; when a transform animation is played in parallel with two continuous scrolling animations, also transformation animations, the layer seems to jump as if correcting its position. The magnitude of the jump appears to be correlated to the speed at which the parallax layer is scrolling.

The black overlays at the edge of z-levels appear to be layered below the parallax layers if a mob's light cone overlaps with them, however I have no clue as to how to fix this, given that the overlays seem to be innate to BYOND.

## Why Is This Needed?
Space currently resembles a carpet, in that it looks flat.

## Changelog:
```changelog
(u)Mr. Moriarty
(*)Replaced the static space background with parallaxing background layers, with layer contents varying between station maps and z-levels. Should you wish to toggle it off, you may do so through the `Game -> Effects -> Parallax` toggle.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Okay great incredible amazing pr but what carpets are you getting that are flat? if you need glasses Ill toss in five bucks

**Comment by pali6** [comment]
doesn't work for nested contents. Use the outermost movable complex signal and Move / set_loc signals on the outermost movable to track movement. (Tbh it might be a good idea to maybe create another "layer" of complex signals that fire basically whenever an object's x, y, z changes.)

**Comment by flappybatpal** [comment]
The cordon issue is not great, it's going to mess people up feeling out where the border of space is.
The cut off at the top of pod HUD is a bit distracting but not a show stopper.
I feel the station Z is missing a more responsive layer like Debris has to easily convey direction of motion. It's relatively subtle in pods.

**Comment by flappybatpal** [comment]
As mentioned on Discord, I think this will need a client side toggle to go live.

**Comment by flappybatpal** [comment]
Container inside vehicle working now, clientside toggle also worked for me.
Personally would like to see another layer on the station Z that is highly responsive like debris' asteroids to give a better motion reference.

**Comment by flappybatpal** [comment]
Meteor event layer doesn't work on Kondaru although I can't tell why, it worked for me on Cogmap.

**Comment by LikeLakers2** [comment]
@flappybatpal I'm curious why this was un-testmerged? It seemed to be working fine on Goon3 for the most part, even if it was turned off on Goon1 for performance reasons. Was it by request of Mister-Moriarty?

To be clear, I'm just curious. I'm not asking for it to be re-testmerged (although that'd be nice because I really like the effect).

**Comment by Sord213** [comment]
https://user-images.githubusercontent.com/71185626/233726003-fdd1992f-b8da-4059-8ff8-2f16e4139976.mp4

Noticed some weird behavior while I was observing a cockroach in space. Notice near the end when I stop observing the cockroach

**Review by flappybatpal — APPROVED** [review]
I'd like to see cordons fixed and azone support is a big thing (for PR 2) but as-is there aren't really any significant bugs and the performance impact seems OK.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
One last request: an admin button to turn off parallax server-side as an emergency measure in case of extreme lag events/population spikes.

**Review by TobleroneSwordfish — APPROVED** [review]

**Pull request merged**
