### PR TITLE
Turn port-a-nanomed mutadone pills into emergency autoinjectors

### PR DESCRIPTION
**Pull request by FlameArrow57**
[FEATURE][BALANCE]

## About the PR 
This PR turns the mutadone pills found in the porta nanomed into emergency autoinjectors, along with adding a new gray version of the auto injector for them.

image

image

One of the inhands:
image

## Why's this needed? 
Mutadone pills are currently available in the porta nanomed, but going with the other pills available as injectors, it would make more sense for them to be an injector, also falling in line with the porta nanomed being more of an emergency thing.

## Changelog
```changelog
(u)FlameArrow57
(+)Port-A-NanoMed mutadone pills are now available instead as emergency auto-injectors.
```

### CODE REVIEW

**Comment by colossusqw** [comment]
Couldn't this make removing someone else's genes without their consent easier?

**Comment by DimWhat** [comment]
> Wouldn't this make removing someone else's genes without their consent easier?

You can already fill hyposprays with mutadone so I don't see the harm in this.

**Comment by FlameArrow57** [comment]
> Wouldn't this make removing someone else's genes without their consent easier?

It would make it a bit faster. From a security perspective, right now, I think you would stun someone long enough anyways that they could be fed a mutadone pill, would be similar for autoinjectors. MD and some armories I think also have mutadone tranq darts.

**Comment by MetricDuck** [comment]
Feels like an unnecessary nerf to bioeffects by dramatically increasing the availability of a one-click counter - don't really think Genetics is dominant enough right now to warrant it.

Hypo/smoke requires a degree of prep/reactivity and armoury requires armoury which leaves Sec, Cap and the MD as the only crew who would likely have an immediate response to an aggressor using bioeffects (baton, gun, tranq). The PDA-app summon function would extend this group to all of medical staff and whomever else has the relevant app on their pda.

**Comment by NightmareChamillian** [comment]
I can see concerns with greifing, but in my experience, the only time I'm ever feeding someone mutadone is if they're radioactive and I absolutely wish I could instantly treat them in those rare cases. If someone's mutations are already enough of a threat to justify whipping out the nanomed and trying to inject them, chances are they've already won an encounter, and you might as well prepare other, instant means ahead of time.

**Comment by ZeWaka** [comment]
not a super big fan just like duck said

**Comment by FlameArrow57** [comment]
Alrighty, I'll close this then.

**Pull request closed without merging**
