### PR TITLE
Makes Apiculturist into a daily job on Mondays and makes mime a regular job selectable via job preferences

### PR DESCRIPTION
**Pull request by predmetparfuyit86**
## About the PR 
this will make apiculturist daily job limited to Mondays and make the mime selectable via job preferences

## Why's this needed? 
We have a lot of new bees recently so they will need someone to look after them 

## Changelog`

```
(u)Predmetparfuyit86:
(+)Nanotrasen has hired an apiculturist to help take care of the bees on Mondays. The mime has also graduated top of their class at the Nanotrasen Spec ops traini- i mean uhhhh 'mime school' as a result they are now a full part of the Nanotrasen family! 
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
might possibly break for things using the path, I'd imagine the special job thing does

**Comment by predmetparfuyit86** [comment]
> might possibly break for things using the path, I'd imagine the special job thing does

anyway to test if it does? or how to fix it?

**Comment by ThePotato97** [comment]
Input needed tag?

**Comment by predmetparfuyit86** [comment]
> Input needed label?

ok how do i put the label on it?

**Comment by Carbadox** [comment]
If I understood you correctly, on the forums you said that it's still possible to get a 2nd Mime on Mondays. If that's the case then I'd probably say that should probably get fixed to not be the case

**Comment by predmetparfuyit86** [comment]
> If I understood you correctly, on the forums you said that it's still possible to get a 2nd Mime on Mondays. If that's the case then I'd probably say that should probably get fixed to not be the case

what would i fix that with? who would replace the mime? im no super coder and i cant sprote so i dont think i could replace mime job on mondays

**Comment by ZeWaka** [comment]
that'll break stuff more, now that monday doesn't exist

**Comment by predmetparfuyit86** [comment]
> that'll break stuff more, now that monday doesn't exist

fuck how do i bring back mondays? also should i just close this and hope someone who an actually code will do it properly?

**Comment by Carbadox** [comment]
You could probably take one of the jobs from the randomised jobs (look under line 1287) and put it in place of the mime's Monday slot. Just remember to remove the random jobs entry.

Also, I think this is a change worthy of a changelog. If you're out of ideas, maybe write something like how the Mime has finally gotten a promotion and is now a full-time NanoTransen employee

**Comment by predmetparfuyit86** [comment]
> You could probably take one of the jobs from the randomised jobs (look under line 1287) and put it in place of the mime's Monday slot. Just remember to remove the random jobs entry.
> 
> Also, I think this is a change worthy of a changelog. If you're out of ideas, maybe write something like how the Mime has finally gotten a promotion and is now a full-time NanoTransen employee

ill do that then also how do i revert the commit where i deleted mondays as a whole?

**Comment by Carbadox** [comment]
no need to revert, just rewrite and commit what you have so that it replaces the Monday job.

**Comment by predmetparfuyit86** [comment]
> no need to revert, just rewrite and commit what you have so that it replaces the Monday job.

done i picked conworker because honestly i think the rcd deluxe is far far to strong to have every day and is very often misused in ways which harm the crew as a whole if anyone disagrees with this i would be happy to change it to another job.

**Comment by Carbadox** [comment]
Consider updating the PR description to reflect that change as well.

**Comment by TTerc** [comment]
I like mimes

However I very much dislike outright removing conworker from the list of roundstart jobs, I have not noticed many cases of abusing this job and I definetly have witnesses many conworkers working on fun creative projects. It'd be sad to see it gone

I'd just add some latejoin role as a monday job instead of messing with existing job list

**Comment by Tiggersaurus** [comment]
> I like mimes
> 
> However I very much dislike outright removing conworker from the list of roundstart jobs, I have not noticed many cases of abusing this job and I definetly have witnesses many conworkers working on fun creative projects. It'd be sad to see it gone
> 

As far as I was aware, having tried with favourite etc that roundstart conworker doesn't work/is bugged?

I remember poking about it back near when I started and was told by an admin to latejoin in order to be a conworker. Happy to be wrong though if this isn't the case anymore?

**Comment by predmetparfuyit86** [comment]
> I like mimes
> 
> However I very much dislike outright removing conworker from the list of roundstart jobs, I have not noticed many cases of abusing this job and I definetly have witnesses many conworkers working on fun creative projects. It'd be sad to see it gone
> 
> I'd just add some latejoin role as a monday job instead of messing with existing job list
what would you rather see on Mondays then musician or apiculturist? i mostly picked con worker because people said it would be a good idea and i want to listen to the people.

**Comment by predmetparfuyit86** [comment]
> > I like mimes
> > However I very much dislike outright removing conworker from the list of roundstart jobs, I have not noticed many cases of abusing this job and I definetly have witnesses many conworkers working on fun creative projects. It'd be sad to see it gone
> 
> As far as I was aware, having tried with favourite etc that roundstart conworker doesn't work/is bugged?
> 
> I remember poking about it back near when I started and was told by an admin to latejoin in order to be a conworker. Happy to be wrong though if this isn't the case anymore?

im adding the conworker gear to engi lockers and the ce will get the rcd deluxe so you can still conworker

**Comment by predmetparfuyit86** [comment]
> ## About the PR
> this will make Apiculturalist a daily job limited to mondays and make the mime selectable via job preferences
> 
> ## Why's this needed?
>Apiculturalists are cool and we need more bees also mimes are cool
> 
> ## Changelog`
> Nanotrasen has hired the Apiculturist as a part timer for all shifts taking place on Mondays, the mime has now graduated from the Nanotrasen special op- i mean 'mime school' so they are now a full time member of the nanotrasen family!

**Review by MarkNais — APPROVED** [review]

**Comment by Adharainspace** [comment]
push an empty commit to restart the checks please. map one is broken

**Comment by ZeWaka** [comment]
Not really a big fan of this change.

**Comment by UrsulaMejor** [comment]
Mimes not being able to speak is bad gameplay, in my opinion. Less ability to interact with the crew tends to push people into more borderline griefy behaviors.

**Comment by ZeWaka** [comment]
Closing due to discussion with developer team, and we have decided to not merge this PR. Currently, mimes have no unique mechanics and thus don't really have a spot as a full job. Furthermore, mimes aren't generally 'good' for the current gameplay, since they don't have good mechanics to interact with other players, which often leads to grief-ish behavior.

**Pull request closed without merging**
