### PR TITLE
Switches gloves forensics functionality

### PR DESCRIPTION
**Pull request by Carbadox**
[BALANCE] [INPUT WANTED] [ENHANCEMENT]

## About the PR 
Removes the ability to hide your prints with the use of all gloves, excluding latex gloves. Instead all gloves now scramble your fingerprints. In addition, latex gloves are now the only gloves that hide fingerprints 

## Why's this needed?
Gloves forensics is broken currently. Having to run around and stopping people to find matching material fibres isn't fun nor is it good gameplay. I believe by reversing the functionality of hiding fingerprints, forensics would be more viable. It would also give detectives actual work to do, EG having to compile a list of prints, writing down their full strings and then identifying to whom they belong to.

Now, having to hide your tracks has to be intentional, not a side effect of wearing insulated gloves. I think latex gloves are pretty common mundane item so having to go the extra mile so that security doesn't find you should be worth it.

## Changelog
```
(u)Carbadox:
(*)All types of gloves, excluding latex, will no longer hide your fingerprints. Instead, they will now only scramble them instead. In addition, only latex gloves will hide your prints now.
```

There's kind of a bug where touching something with gloves that scramble once will leave your mark there twice. No clue how to resolve it and it was there before I got here so.

### CODE REVIEW

**Comment by Flaborized** [comment]
I think it's sorta unintuitive that big rubber gloves (or boxing gloves or swat gloves or whatever) would leave *partial* fingerprints, since they're like, thick gloves. I'd rather the latex gloves leave _no_ prints at all and then have the rest of the gloves operate the way they do currently; I don't even think the full print blocking is *as* strong as people think it is, it can be surprisingly quick to match a pair of insulateds (especially if you check specific doors like the CE's office or a door you watched someone go through) and I feel that making latex gloves work like regular gloves do now would make them really easy to suss out still, since fewer people wear them than insulateds. No fingerprints at all would give them their niche IMO.

**Comment by Carbadox** [comment]
I agree that the biggest issue with this patch is that, realisitically/in game it doesnt make alot of sense. In my opinion, as well as some feedback, though I'd imagine that it would work very well mechanically. 

I think it could probably be resolved by kinda reinterprating how forensics supposedly work. How exactly I do not know as I don't really have an idea that sticks. I'd like to imagine that gloves leave smudges from touching stuff so that's where the partial prints come from. idk lol

**Comment by Tarmunora** [comment]
Latex gloves leaving no forensics / having a highly reduced chance to leave a forensic would be a less awkward sol__n__ I think, as it doesn't make much sense for say, boxing gloves, to be leaving partial fingerprints

**Comment by trerri** [comment]
Maybe spacemen have really sweaty hands and by putting on the boxing gloves they touched them and left their fingerprints on

**Comment by Ley-bunned** [comment]
Making latex gloves leave no forensics is kind of an unneeded buff to subtle crime. Glove swapping requires more mindfulness which is a good thing and it is probably just as/more effective when people think it through. Latex gloves would also become a tell that someone is probably up to no good.

**Pull request closed without merging**
