### PR TITLE
adds caipirinha

### PR DESCRIPTION
**Pull request by colossusqw**
[LABEL][feature]
## About the PR 
It adds pineapple caipirinha, a common drink in Brazil. It's made with 2 vodka 2 pineapple juice 1 sugar and 1 ice.

## Why's this needed? 
Caipirinha is super good, i wanted to see it ingame.

## Changelog

```changelog
(u)Hans
(+)Adds a new drink, caipirinha.
```

### CODE REVIEW

**Comment by TDHooligan** [comment]
isn't cachaca more closely related to rum?

**Comment by colossusqw** [comment]
> isn't cachaca more closely related to rum?

some caipirinha is made with vodka, i have more contact with the vodka varieties so i just went with it

**Comment by Azrun** [comment]
Upon further research, I'm confused what this cocktail is. Caipiroska or caipivodka seems to be the vodka variant, but they both still use lime. 🤔

What is this cocktail and is it good?

**Comment by colossusqw** [comment]
i think i went a bit overboard with choosing a variant, but , i can change it to regular caipirinha or caipivodka if rum isnt a suitable enough to replace rum

**Review by pali6 — APPROVED** [review]

**Pull request merged**
