### PR TITLE
Cogmap2 Medbay Revamp

### PR DESCRIPTION
**Pull request by Sord213**
## About the PR 
Completely redesigns Cog2's medbay.

## Why's this needed? 
Cog2 medbay is older in design, while still good it could use some flow changes.

## Changelog 

```changelog
(u)Sord
(*)Cogmap2's Medbay has been completely revamped
```

### CODE REVIEW

**Review by TheTyrant25 — APPROVED** [review]
Looks fantastic. Does strongly resemble cog1 medbay as well, especially on the left side, but to me that's a good thing.

However, it is presently missing a navbeacon and is therefore failing checks, but apart from that, great stuff.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
morgue disposal is broken

**Comment by mordent-goonstation** [comment]
Could stand to have a sink or two available for washing the blood and gore off of tools.

**Comment by Keiiro** [comment]
The MD's and Genetics APC are unusually far away from their room, and feel somewhat hidden, I think putting those inside their respective rooms is preferable.

**Comment by Cherman0** [comment]
Overall it looks way better than the old cog2 medbay. Two things stand out to me as of note:

- Cremator in the morgue. I'm not necessarily against it, but typically only the chapel morgue has one. RP security actually had its morgue access removed over it, if I recall.
- There is a comical number of atmos hookup vents, which will probably render the whole system useless. Dividing your gas pressure amongst 13 vents means a pretty pitiful output to each one, and a decent amount of that pressure will probably be wasted going towards rooms that dont need it. Not to mention that their sprite is enormous, animated, and a bit grody (that pipe nub that extends off of them renders above the floor tile, which looks awkward as it connects to a pipe that is below the floor tile). I'd probably have one vent in the main room and one vent in the side room to its right.

**Comment by 444Portal** [comment]
I'm in love. Crematorium I think could be removed - otherwise, looks great!

**Comment by Sord213** [comment]
> The MD's and Genetics APC are unusually far away from their room, and feel somewhat hidden, I think putting those inside their respective rooms is preferable.

It's typical on Cog2 to have the APCs in maint except for highly secure areas. Kept for consistency. Only reason the reception and cloner have theirs inside is they're even further from maint. Plus making people have to go into maints to access their APCs is a good thing, imo.



> I'm in love. Crematorium I think could be removed - otherwise, looks great!

Crematorium was a suggestion from some other devs, so I'll keep it for now. It can always be removed or adjusted later.




>     ...Not to mention that their sprite is enormous, animated, and a bit grody (that pipe nub that extends off of them renders above the floor tile, which looks awkward as it connects to a pipe that is below the floor tile). ...

Sprite looks fine to me. The extra bits are hidden.
Screenshot_784

**Pull request merged**
