### PR TITLE
Syndicate Exploding Cigars

### PR DESCRIPTION
**Pull request by flappybatpal**
[FEATURE][INPUT]

## About the PR 
Adds exploding cigars as a Bartender exclusive traitor item. 5 TC cost.
Cigars come in a case of two. Each cigar explodes with 12 strength (vs 32 of a chameleon bomb).
Gibs on same tile, crit on next tile, red health two tiles away.

## Why's this needed? 
I wanted a "big brother" to the trick cigarettes. This is given a similar price to the chameleon bomb, it has substantially less power but still lethal on the same tile. You get two in the box to compensate for it being harder to use than a chameleon bomb. While stealthy to carry the smoking cigar itself is fairly obvious when dropped on a tile, even more so if thrown. Unlike the trick cig the explosion is not stealthy at all!
For the moment I gave this to the Bartender as it is on theme for them and they already have access to a chem dispenser at round start to make explosives it they wanted to.

## Changelog

```changelog
(u)Flappybat:
(*)Added exploding cigars for the bartender. Prank your friends!
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
I'm indecisive on how well this fits. 5 TC cost is a bit high for a gimmick but you can potentially kill two people or more. The explosive power is still pretty good despite the reduction to 20. It will do reasonable structural damage and kill anyone on the same tile.

The value of stealth from being a cigar is also a bit mixed. It's more stealthy than a pipebomb but the lit cigar sprite is quite eye catching. Cigars are also in short supply unlike cigarettes.

I am considering changing to a custom explosion to make this crit and remove limbs rather than gib.

**Comment by flappybatpal** [comment]
Added a turf check and an attempt at a two pack sprite, cigarpack.

cigarpack

**Comment by Tarmunora** [comment]
Kinda ehhh about this - we got rid of the old 'syndicate pipebomb' purchase for a reason (reason being that people would always gravitate towards the "get a bunch of nice medium-size bombs" option)

**Comment by flappybatpal** [comment]
The explosion strength can go down from 20, from testing it will gib at 9 so structural damage can be toned down. If gibbing is an issue you have to go down to 8 where it will suddenly only put you into light crit and maybe remove a limb.

**Pull request closed without merging**
