### PR TITLE
Change max stun time to 20 seconds instead of 30

### PR DESCRIPTION
**Pull request by mybluecorners**
## Changelog

```
(u)mbc:
(+)Maximum stun time is lowered to 20 seconds from 30
```

### CODE REVIEW

**Comment by PrimeNumb** [comment]
Might affect vampires severely

**Comment by Tiggersaurus** [comment]
Is this human-types only or all living mobs?

**Comment by Tarmunora** [comment]
For any atom that receives the stun/weaken/paralysis effect.
@mybluecorners care to give your reasoning for the change?

**Comment by Kyle2143** [comment]
This seems fine to me. Mostly cause I don't really expect that it will come up often anyway. Rarely do I see a  stun that goes into 30 seconds.  Like richard said, the only thing I can think of offhand that applies a single stun for around that time is the vampire hypnosis.

**Comment by PrimeNumb** [comment]
Tested on local and the usual combo of glaring -> taking off mask + helmet -> hypno -> drain is just barely doable if you're _very_ quick and don't have any unlucky aggressive grab rolls. I think this is going to make vampire very difficult for the average player, so some adjustments are probably needed to compensate.

**Comment by mybluecorners** [comment]
The reasoning was that 20 seconds might feel better than 30 without really gameplay too much. Evidently that is not the case with vampires, maybe their hypno ability progress bar could be shortened? would that fix it?

**Comment by PrimeNumb** [comment]
> The reasoning was that 20 seconds might feel better than 30 without affecting gameplay too much. Evidently that is not the case with vampires, maybe their hypno ability progress bar could be shortened? would that fix it?

It's already about 4 seconds and can be used from 2 tiles away, so shortening it too much could end up being wack.

Maybe only shorten the duration if the target is KO'd?

**Pull request closed without merging**
