### PR TITLE
Kondaru clowntainment radiation shielding

### LINKED ISSUE #14178: Lil bit of Kondaru maints becomes radioactive during radstorms
### Labels

[BUG][MINOR]

### Description

Three tiles in the north west corner of the station are radioactive despite maintainance tunnels being  a rad-proof area

### Steps to reproduce

1. Be on Kondaru during a rad storm
2. Lay eyes upon the three tiles directly outside the entryway to the clown hole in the maint tunnels
3. Oof owch owie my eyes they are so radioactive

### Expected Behavior

Either none of this section of tunnel is affected by the rad storm, or all of it is.

### Additional Information & Screenshots

Reported by: Emrsnn
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #14156
Round log date: 2023-05-20-20-50
Reported on: 2023-05-20 21:49:00
Map: KONDARU

### PR DESCRIPTION
**Pull request by Kubius**
[FIX]
## About the PR 

Adds radiation shielding to Kondaru's clowntainment chamber and its small lobby area in Maintenance.

## Why's this needed? 

Fixes #14178. And prevents a mere radiation storm from freeing the Clown from their prison.

### CODE REVIEW

**Comment by Kubius** [comment]
mdb bugged apparently

**Comment by TobleroneSwordfish** [comment]
Unless I'm misunderstanding how DMM files work, this will make the entire clown hole rad proof, which I think is inconsistent with other maps?

**Comment by Kubius** [comment]
The clown hole on Kondaru is a repurposed hazardous subject containment chamber bolted onto Maintenance. It's thematically suitable.

**Comment by Kubius** [comment]
Closing this to tackle the issue a different way.

**Pull request closed without merging**
