### PR TITLE
Replaces Cluwne sounds with new copyright free versions

### PR DESCRIPTION
**Pull request by MitchTheUser**
## About the PR 

As the tin says, adds new sounds for the Cluwne Laughs and Cluwne Step sounds with original versions, instead of their original copyrighted versions.

The Cluwne's laugh is now much more demonic and less animalistic, having occasional slow, deep chuckles, quick baritone giggles, and weird distorted horn sounds, as if stuck, emanating from the Cluwne's throat.

The Cluwne's footsteps are mostly the same, being short laughs mixed with distorted Clown shoe steps.

Laughs:

https://github.com/user-attachments/assets/6abc1f1b-1c54-4c88-ae56-3a2360047f5d

https://github.com/user-attachments/assets/8a0e83da-e738-458b-ac3d-e76b053d10ff

https://github.com/user-attachments/assets/e42c496b-e3f4-404b-8c72-e561a2866e89

Steps:

https://github.com/user-attachments/assets/820d0080-ec7d-403f-8b6b-3a11260b7e25

https://github.com/user-attachments/assets/074fe126-ea78-4805-a645-1f0bffe81b48

https://github.com/user-attachments/assets/1ea6209e-56e7-4d95-ad2e-c304351713cd

https://github.com/user-attachments/assets/3054352a-ac89-41b2-a9da-dd46e085415d

## Why's this needed? 

The current Laughs and Steps that the Cluwne makes are from Left 4 Dead 2's Jockey, which are simply audio ripped from another game, which we probably shouldn't do.

### CODE REVIEW

**Comment by ZeWaka** [comment]
how is the volume compared to the existing sounds

**Comment by MitchTheUser** [comment]
> how is the volume compared to the existing sounds

Here's all the old sounds if you want to hear them for comparison yourself.

https://github.com/user-attachments/assets/831ee3fb-3bdd-408d-afaa-50fa3ab0569b

https://github.com/user-attachments/assets/fbbdf80b-652b-42d6-8178-c63c9f48d77f

https://github.com/user-attachments/assets/676df485-2b45-4630-837f-2f85603a3faf

https://github.com/user-attachments/assets/a39802ee-f5af-4604-a0b0-b847ce1f2075

https://github.com/user-attachments/assets/373910fc-a17d-4546-9664-ae47397d75d9

https://github.com/user-attachments/assets/e147e989-bfdb-4bb5-84e0-c22245658969

https://github.com/user-attachments/assets/8d7a972d-4b8b-4eef-968c-12a1f55a912c

https://github.com/user-attachments/assets/ac39f967-f1ee-4c85-9b13-9436a0882385

**Review by Glamurio — CHANGES_REQUESTED** [review]
Not a fan of the martian screech, and it's also not really thematic to the rest of the PR. I'd personally cull that from the PR.

**Comment by MitchTheUser** [comment]
> Not a fan of the martian screeches, and it's also not really thematic to the rest of the PR. I'd personally cull those from the PR.
> 
> As for the cluwne sounds, like mentioned on Discord, they seem fine to me and an improvement over using the Jockey sounds.

Reverted the Martian Screech back to it's old current version until I can work on it later for It's own PR.

**Comment by Glamurio** [comment]
> > Not a fan of the martian screeches, and it's also not really thematic to the rest of the PR. I'd personally cull those from the PR.
> > As for the cluwne sounds, like mentioned on Discord, they seem fine to me and an improvement over using the Jockey sounds.
> 
> Reverted the Martian Screech back to it's old current version until I can work on it later for It's own PR.

Make sure to change the name / description of the PR to reflect that

**Comment by MitchTheUser** [comment]
> > > Not a fan of the martian screeches, and it's also not really thematic to the rest of the PR. I'd personally cull those from the PR.
> > > As for the cluwne sounds, like mentioned on Discord, they seem fine to me and an improvement over using the Jockey sounds.
> > 
> > 
> > Reverted the Martian Screech back to it's old current version until I can work on it later for It's own PR.
> 
> Make sure to change the name / description of the PR to reflect that. Also I don't think this necessarily warrants a changelog entry at all.

Done

**Review by Glamurio — APPROVED** [review]

**Comment by MitchTheUser** [comment]
PR hasn't had any additional review, but it doesn't have any outstanding issues and has been received mostly positively, so I think I'll close this myself and reopen later when I can get some developer comment on if it is ready to merge rather than just letting the stale label auto close it.

**Pull request closed without merging**
