### PR TITLE
Allows 3 Security Officers to revoke Armory access

### PR DESCRIPTION
**Pull request by JORJ949**
( Theres no A tag for Security 👎 and I was unsure which tag was right, thanks 444 )
## About the PR 
Applies Armory authorization rules to revoking authorization by allowing 3 people with security equipment access to unauthorize.

## Why's this needed? 
Security can gain access, but not lock it back up when they are done with it unless the HoS or Captain does it, they should be able to lock it themselves considering they can unlock it

## Changelog 

```changelog
(u)JORJ949
(*) 3 Security Officers can now deauthorize Armory.
```

### CODE REVIEW

**Comment by pgmzeta** [comment]
I think you could reduce code duplication here with procs called from `attackby` and `print_auth_needed`, as a lot of the logic is shared between the authorized and unauthorized code paths.

**Comment by JORJ949** [comment]
> I think you could reduce code duplication here with procs called from `attackby` and `print_auth_needed`, as a lot of the logic is shared between the authorized and unauthorized code paths.

I considered that but couldn't come up with a clean way to also include the different text for if its authed or not

**Comment by JORJ949** [comment]
I've got a plan to reduce duplicate code, should be coming on monday

**Comment by Tarmunora** [comment]
Nah

**Pull request closed without merging**
