### PR TITLE
Remove unneeded catwalk types

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Removes unneeded catwalk subtypes now they all auto connect.
and fixes icon_state pathing to the new file.
obj/grille/catwalk/cross
obj/grill/catwalk/jen/inner
obj/grill/catwalk/jen/side
obj/grill/catwalk/jen/twosides
obj/grill/catwalk/jen/fourcorners

## Why's this needed? 
FIX ME bad

### CODE REVIEW

**Comment by flappybatpal** [comment]
It should be relatively easy to fix this properly using UpdatePaths?

**Comment by CheffieGithub** [comment]
that works

**Comment by CheffieGithub** [comment]
im guessing there will be secret ones too so if a dev could run the scipt for those

**Comment by CaioFrancisco** [comment]
Thank you for doing the work I was deliberately avoiding (erasing all the catwalk sub-types because old icons) and thank you for the work I **keep forgetting** (fixing map editor icons)

**Comment by flappybatpal** [comment]
> im guessing there will be secret ones too so if a dev could run the scipt for those

Secret has been updated using the provided script.

**Review by flappybatpal — APPROVED** [review]

**Pull request merged**
