### PR TITLE
cache medals to player datum

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
* Cache medals to player datum
* Change medal requests to check local cache rather than relying on getmedal cache/hub

## Why's this needed? 
* Faster medal checks
* No need to sleep medal checks anymore

## Changelog 

```changelog
(u)Sovexe
(+)Medal checks have been refactored to be more performant and responsive
```

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
needs wrappers around has

**Comment by ZeWaka** [comment]
https://github.com/goonstation/goonstation/issues/19352

**Comment by Sovexe** [comment]
I can only assume the hub failed to respond for them. We can implement a retry for players with null medals

**Comment by ZeWaka** [comment]
@Sovexe do you still want this open

**Pull request closed without merging**
