### PR TITLE
Shuttle medbay door fixes

### LINKED ISSUE #7936: Escape Shuttle Medical Room Door
### Labels

[MINOR]

### Description

Med room door on escape shuttle not restricted to med access.

### Steps to reproduce

1. Go escape shuttle
2. Open medical door without med access.

### Expected Behavior

Door be restricted to IDs with med access.

### Additional Information & Screenshots

Reported by: SvedkaMerc
On server: Goonstation 4 Roleplay: Sylvester
Round log date: 2022-03-24-01-21
Reported on: 2022-03-24 03:10:17

### PR DESCRIPTION
**Pull request by nefarious6th**
[bugfix]

## About the PR 
fixes door access on shuttle medbay compartments 
mug rack thing is a broken filepath on the south shuttle

## Why's this needed? 
fixes #7936

### CODE REVIEW

**Comment by DisturbHerb** [comment]
beloved beloved beloved

**Comment by Sord213** [comment]
The door lacking access is intentional, so people can get medical aid if no doctors are alive on the shuttle, and make use of the sleepers. I'm not opposed to adding access but that's the reasoning why it's that way. 

Also altering density is not what you want. Density determines if people can walk through it, so making it 0 would let people walk through the door as if it didn't exist until it opens and closes again. I'm assuming you wanted opacity, so you can see through it. This wouldn't work though as doors are coded to set opacity back to 1 when they close. You would need to make a new door subtype.

**Comment by nefarious6th** [comment]
> The door lacking access is intentional, so people can get medical aid if no doctors are alive on the shuttle, and make use of the sleepers. I'm not opposed to adding access but that's the reasoning why it's that way.
> 
> Also altering density is not what you want. 

oops, i missed that on the northbase shuttle since i placed the doortype from the disaster shuttles; the disaster shuttles have the density set as 0 by default though, which i assume is from when the doors all had 0 density, something that was fixed on the base shuttles a while back, i think. not that moving through a door to a compartment that already has the wall next to the door missing is a huge issue

i figured the open first aid station might've been the reasoning for the lack of the variable. if we're good to keep it like that, though, this PR can just get closed out along with the associated issue report

**Comment by Sord213** [comment]
Ah, yeah the doors on disaster shuttle having density set to 0 isn't intended but otherwise the rest of this PR is.

**Pull request closed without merging**
