### PR TITLE
Cogmap 1 engine adjustments

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Makes some changes to the cogmap 1 engine. Focused on improving visibility, vanity, and reducing the amount of pipes/wires under walls.

image

some changes not pictured:
Furnished the waiting area before entering engineering proper.
Removed the hotwired grilles from the AI smes room.
Made many cameras and lights accross all of engineering perspective.
Rerouted the crematorium pipe to not go through the AI core.

## Why's this needed? 
The engine should be better to work in for engineering, and perspective lights are always good.

## Changelog 

```changelog
(u)Cheffie
(*)The engine room on Cogmap 1 has been remodeled and overhauled.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Having the wires on top of pipes is a bad idea. Yes, it's pretty. It's absolutely terrible to try to repair or play with though.

**Comment by CheffieGithub** [comment]
I do agree but there is really not much space to not have wires under pipes, I put full tiles over the pipes with overlap so its not that hard to repair unless it gets exploded and at that point the engine is probably inoperable anyway.
I can move the ones in the TEG room to not be over wires in the same direction at least.

**Comment by ZeWaka** [comment]
> I do agree but there is really not much space to not have wires under pipes
... there's a whole tile's worth of space?

**Comment by CheffieGithub** [comment]
In the TEG room?

**Comment by CheffieGithub** [comment]
image

updated

**Comment by CheffieGithub** [comment]
the black PTL wire and the red one above it for the hangar can't really not go over any pipes without going under walls

**Comment by CheffieGithub** [comment]
note only the more industrial looking gray tiles between the top and bottom will actually show the wires / disposal pipes

**Comment by ZeWaka** [comment]
> note only the more industrial looking gray tiles between the top and bottom will actually show the wires / disposal pipes

i dont really get why wires wouldn't be visible in engineering

**Comment by CheffieGithub** [comment]
As you have already said wires and pipes do not mix and its not like wires are super visible on other maps, look at kondaru for example

**Comment by Tarmunora** [comment]
The hotwired grilles by the AI SMES are intentional

**Comment by CheffieGithub** [comment]
I asked cogs and he said he was fine with the grille removal, I removed them because thindows are getting phased out and having full windows over them or being exposed make no sense.

**Comment by CheffieGithub** [comment]
Updated the smes didn't readd the grilles but put Rwalls for similar level of security as before 
image

**Pull request merged**
