### PR TITLE
laser assault rifle resprite + nanotrasen specialist operative changes

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This job just touches on a bunch of stuff for ntspeco that was pretty out of place. Removes a frag grenade and pouch of 5 200 pu cells. The frag grenade was just because it was a single one and felt pretty out of place, and also helped contribute to item bloat (currently ntspeco actually spawns with more items then can fit in there backpack), the pouch was removed because it was just really odd. The laser assault rifle has had some numbers tweaked, the modes actually burst now, the spread angle is removed, and they do slightly more damage but for more cost, this should make the gun overall feel more nice and in line with other guns. Also the gun was resprited because the sprite was showing its age.
Current:
image

This pr:
image

## Why's this needed? 
A lot of the aspects of this job were pretty crusty and I think these changes should make the job nicer to use for admemes.

## Changelog

Shouldnt be needed for an admeme only job.

### CODE REVIEW

**Comment by frawhst** [comment]
still the halo gun 😭

**Comment by ThatFiveGuys** [comment]
Ah but have you considered, it has gamer lights on it.

**Comment by flappybatpal** [comment]
Not a spriter but is that actually correct outlining? It's consistent, even on the light edges.

**Comment by ThatFiveGuys** [comment]
Ill admit was lazy there, good call, improved it.

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Review by Tarmunora — CHANGES_REQUESTED** [review]
Should be in the NTSO armoury colour palette (see signifer, vexilifer).

Would also be nice to not be literally the halo assault rifle :|

**Comment by ThatsMamaLuigiToYouMario** [comment]
Aren't the bag of cells needed as ammo for the gun? If I'm not mistaken the gun doesn't recharge on its own with the cell inside.

**Comment by ThatFiveGuys** [comment]
This pr makes it self recharge

**Comment by ThatFiveGuys** [comment]
Realizied I didnt really want to finish this pr

**Pull request closed without merging**
