### PR TITLE
Add Heavy Clown Boots + Military Shoes

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
image
Adds "Heavy clown boots" obtainable by someone with clown training drawing crayon all over heavy military boots
Adds "Military shoes" obtainable by someone with security training graffiti spraypainting clown shoes 

## Why's this needed? 
Just a funny idea I thought up and adds potential for increased hos/clown hijinx. Intentional lack of changelog as not knowing the clown can draw on your shoes will be hilarious.

### CODE REVIEW

**Comment by Glamurio** [comment]
This is a fun idea.

**Comment by JORJ949** [comment]
> This is a fun idea. Do we have a medal we could tie the reward to? Could make your own medal, I think we have the ability for that now. Otherwise the only one I can think of is "honk HONK mother FU-".

I heard an idea for a medal for clownshotting/being clownshot which could be fun, though id rather add rewards to existing medals that dont have a reward, rather than making new ones

**Comment by JORJ949** [comment]
Im going to change this to instead be just actually graffitiing/crayoning on them if you have clown or security training, but thats whenever I get to that

**Comment by JORJ949** [comment]
FUCK

**Comment by Glamurio** [comment]
> Im going to change this to instead be just actually graffitiing/crayoning on them if you have clown or security training, but thats whenever I get to that
> 
> EDIT: Done

Eeeeh, I think that's significantly less cool. Training locked rewards are less fun, and it means that before you could find clown shoes and spray paint them black, or vice versa, even without being the respective job. Could've made the medal reward something like "As Clown, end the shift while wearing HoS boots, or vice versa".

**Review by TobleroneSwordfish — APPROVED** [review]
funny

**Pull request merged**
