### PR TITLE
ouija board text and grenade updoot

### PR DESCRIPTION
**Pull request by TiberianEuan**
## About the PR 
some minor changes that might never be seen in-game, including a new grenade that spawns npc people and the word "fuck" in ouija boards because sometimes ghosts need to vent their frustrations.

## Why's this needed? 
because it allows for more things to be done with Ouija boards, also admins can bulk-spawn npc people (they have assistant uniforms)

## Changelog

```changelog
(u)TiberianEuan
(+) Added ghost swearing
(+) Added assistant NPC grenade
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
These seem like pretty unrelated changes, should probably be separate PRs, also admin only changes don't need a changelog entry.

**Comment by ZeWaka** [comment]
Terribly sorry, but this PR contains feature additions. We have a feature freeze (this means no new PRs with features in them until the end of the month. This PR is being automatically closed as a result.

For more details, see our Discord #codebase-news channel, or https://github.com/goonstation/goonstation/discussions/9811

**Comment by TiberianEuan** [comment]
@ZeWaka my code is bugless

**Comment by TiberianEuan** [comment]
let me check again to be %100 sure

**Pull request closed without merging**
