### PR TITLE
New sprites for CustodiPRO, CodeBreaker, and ringtone cartridges

### PR DESCRIPTION
**Pull request by pgmzeta**
[sprite][game objects]
## About the PR 

split 'cart-c' sprite use into 'cart-game' and 'cart-tone', with new sprites
new sprite for the janitor's CustodiPRO cartridge
removes older cart sprites

## Why's this needed? 
Match other PDA cartridge style i.e. exposed contacts on bottom 

## Screenshot
image
New PDA cart sprites on the ground, as well as how they look in the CartyParty UI.

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
just remove unused stuff git exists

**Review by Gannets — APPROVED** [review]
Sure

**Comment by ZeWaka** [comment]
The detomax doesn't use the cart image with the D on it?

**Comment by pgmzeta** [comment]
> The detomax doesn't use the cart image with the D on it?

it uses the bomb image icon "cart-deto"

**Pull request merged**
