### PR TITLE
Sanity Checks: Creation and Deletion 

### PR DESCRIPTION
**Pull request by Azrun**
[cleanliness]
## About the PR 
Addresses runtimes found during creation and deletion of * or adds `CRASH` to indicate something was used incorrectly where applicable.

## Why's this needed? 
Runtimes bad.

### CODE REVIEW

**Comment by Azrun** [comment]
image

**Comment by ZeWaka** [comment]
Not sure if this is a good idea. Some objects will probably fail as they're expected to spawn with another obj, ex. Cloning equipment

**Comment by Azrun** [comment]
> 
> 
> Not sure if this is a good idea. Some objects will probably fail as they're expected to spawn with another obj, ex. Cloning equipment

Supports list of: Items to skip (besides abstract types), Items that are expected to runtime/crash (with number expected [aiLaw generates 20 for API calls for example]).

I don't think it should be a normal test that is run as part of CI due to possibility of noise but there might be value in it for regression analysis and general integrity. Having 1000s of objects stacked on each other interacting creates some... interesting interactions.

**Comment by ZeWaka** [comment]
Hmm. I agree, but I dunno if worth dev effort. Moreso better tests imo are ones like equipping, basic scenarios, etc.

**Pull request merged**
