### PR TITLE
Cog2- Swap AI Core Announcement Console for QM

### PR DESCRIPTION
**Pull request by MarkNais**
[MAPPING]
## About the PR 
Swaps the Announcement Console in the AI core for a Cargo Console. 

## Why's this needed? 
AIUsers cannot "login" to announcement consoles, rendering it useless.

## Changelog

```
(u)MarkNstein:
(+)Cog2: AI Core Announcement console replaced with QM console.
```

### CODE REVIEW

**Comment by MarkNais** [comment]
Looking at that line-count of changes, I think I need to set SDMM to TGM format..

**Comment by ZeWaka** [comment]
They certainly used to be able to.

**Comment by ZeWaka** [comment]
DNM for tgm reasons

**Comment by ZeWaka** [comment]
Was wrong about announcement computer, still DNM for them reasons

**Comment by MarkNais** [comment]
You self assigned, but is it up to me to fix the TGM issues? As I tried by setting SDMM to TGM.

**Comment by ZeWaka** [comment]
Converted.

**Comment by MarkNais** [comment]
Thanks! I'll dig into the issue next time, Perhaps I might need to update SDMM itself.

**Comment by ZeWaka** [comment]
> 
> Perhaps I might need to update SDMM itself.

It should auto update if you're using the latest launcher.

**Comment by MarkNais** [comment]
Closing this as I don't trust some of the things I saw in the merge-conflict resolution.

**Pull request closed without merging**
