### PR TITLE
Winter scarf!

### PR DESCRIPTION
**Pull request by wiverns**
## About the PR 
Adds a cozy new scarf to the game to keep your neck warm! It's worn in the mask slot, so you can pair it with a coat, and provides a bit less cold resistance than the coat does.

scarf spin

## Why's this needed? 
Fashion! Also extra warmth, at the cost of not being able to use internals.

## Changelog 

```changelog
(u)Wivernshy
(*)Added a winter scarf for the mask slot, found in the Cold Weather Gear crate from cargo!
```

### CODE REVIEW

**Comment by pali6** [comment]
Don't we have some scarf in a different slot?

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
Nice idea having these in the cold weather crate. As others mentioned above, scarves are usually in the outerwear/overcoat slot, but it doesn't bother me personally if you lose out on internals for the Fashion.

Sprite wise though, could you please add outlines to the item-state? To be consistent with the spriting guidelines and other recent clothing. 👍

**Comment by pali6** [comment]
We could move the existing scarf to the mask slot for consistency and for more fashion options (as it lets you combine it with overcoat clothing).

**Comment by WALPVRGIS** [comment]
> We could move the existing scarf to the mask slot for consistency and for more fashion options (as it lets you combine it with overcoat clothing).

The only downside is that mimes may be unable to wear their scarf and mask at the same time :waa: but ig we could figure out something dskjhgf. (sorry this is getting a bit far off topic)

**Comment by wiverns** [comment]
> > We could move the existing scarf to the mask slot for consistency and for more fashion options (as it lets you combine it with overcoat clothing).
> 
> The only downside is that mimes may be unable to wear their scarf and mask at the same time :waa: but ig we could figure out something dskjhgf. (sorry this is getting a bit far off topic)

I thought about that, yeah! These are intentionally in the mask slot instead of overcoat so that they can be worn with winter coats, and I do intend to add department scarves at some point (though, I guess it'd be easier to just add them to this PR?). I don't really see a reason to change the mime scarf, since it's a different type of scarf entirely.


> Nice idea having these in the cold weather crate. As others mentioned above, scarves are usually in the outerwear/overcoat slot, but it doesn't bother me personally if you lose out on internals for the Fashion.
> 
> Sprite wise though, could you please add outlines to the item-state? To be consistent with the spriting guidelines and other recent clothing. 👍

And sure!! I'll get on that later today o7

**Pull request closed without merging**
