### PR TITLE
Cereal-boxes!

### PR DESCRIPTION
**Pull request by GustavGoldman**
## About the PR 

Changes the sprites of Syndie Shreddies, Pope Crunch, and Roach Puff cereals!
Pope Crunch has now been replaced with Cookie Swirlies! With a new description!

## Why's this needed? 
Cereal boxes were not in the right perspective and Pope Crunch needed an update!
image

### CODE REVIEW

**Comment by GustavGoldman** [comment]
This is my first PR! So sorry for any troubles!

**Comment by ZeWaka** [comment]
Incorrect changelog format

**Comment by DisturbHerb** [comment]
popecrunch removal

literally 1984

**Comment by GustavGoldman** [comment]
Removed the changelog!
Also yes this is just like 1984 AND Fahrenheit 451

**Pull request merged**
