### PR TITLE
Makes monkey AI more immersive

### PR DESCRIPTION
**Pull request by TerraGS**
## About the PR 

Adds the *urinate emote as a possible monkey AI action.

## Why's this needed? 

For the sake of science and humor. With this comes even more reminder that monkeys are simple animals with no appreciation for the human concept of a toilet.

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Why not make this check the /mob.urine value instead of reagents, and use the *urinate emote?

**Comment by TerraGS** [comment]
From what I saw, the value you speak of is reserved for sims mode. Also the emote gets its text from the urinate function.

**Comment by pali6** [comment]
> From what I saw, the value you speak of is reserved for sims mode. Also the emote gets its text from the urinate function.

It's not reserved for sims mode.

**Comment by TerraGS** [comment]
Ok finally found it. Testing changes now.

**Comment by TerraGS** [comment]
Made it infinitely better.

**Comment by ThatFiveGuys** [comment]
This makes staffies closer in civility to monkeys which i dislike.

**Review by ZeWaka — COMMENTED** [review]
I'd rather monkeys unrinate on their enemies if they knock them down successfully.

**Comment by BatElite** [comment]
Don't monkeys already wear diapers for this reason?

**Comment by Tarmunora** [comment]
Overall, i'd rather not add more urine-related stuff to the game :/

**Comment by TerraGS** [comment]
I apologize if I touched on a sore spot. As I am still rather new to goon I don't have much to base perceptions off of other than what's already here. In the future I might try helping reduce existing urine-related stuff. With that being said I'll close this PR to keep with that intention.

**Pull request closed without merging**
