### PR TITLE
Alters manta botany, adds a closet for botany

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This PR significantly relocates various machinery inside of botany increasing ease of movement. The amount of garden gears and plant masters (previously one of each) have been doubled. Previously there were 9 botany trays (for comparision atlas has 12). This pr increases that number to 15 trays, with 4 additional trays in the botany closet. The botany closet accessible by a ladder hidden under the crate contains a weed couch, multitool, 4 trays and one spare UV lamp.
image
image

## Why's this needed? 
Previously, manta botany had not nearly enough tray for its frequent pop, and was very poor to navigate. This PR makes manta botany much nicer to work in. It also adds a manta closet to aid with crime and to add more space for trays.

## Changelog

```changelog
(u)Ikea
(*)Manta botany has had various mapping changes increasing QoL. During the renovation of botany a worker discovered a ladder leading to a forgotten part of botany, not wanting to file the paperwork for unaccounted for architecture, they proceeded to cover this ladder back up with a crate.
```

### CODE REVIEW

**Comment by millicentjwi** [comment]
lmao love the underground weed plantation

**Comment by vocalpocal** [comment]
Manta botany is extremely public and doing anything in secret is very difficult (although this is true to almost any job in manta lol)

Small changes like this would be very welcome I think

**Review by UrsulaMejor — CHANGES_REQUESTED** [review]
Un-commit your changes to __build.dm

I don't like there being an off-z component. It's fine for the occasional secret content piece, but when you're talking about it in terms of actually being a regular part  of the station architecture, it runs into a lot of gameplay issues.

I don't like how utterly cramped this botany looks; there isn't a single two-tile-wide space to just chill in.

**Comment by ThatFiveGuys** [comment]
> Un-commit your changes to __build.dm
> 
> I don't like there being an off-z component. It's fine for the occasional secret content piece, but when you're talking about it in terms of actually being a regular part of the station architecture, it runs into a lot of gameplay issues.
> 
> I don't like how utterly cramped this botany looks; there isn't a single two-tile-wide space to just chill in.

Gonna redo this pr eventually, loads of issues besides those that need to be messed with. Gonna see if i can take some space from other places too to add to botany but yeah. For now gonna close it.

**Pull request closed without merging**
