### PR TITLE
Makes weedkiller (atrazine) remove kudzu on contact with it.

### PR DESCRIPTION
**Pull request by TTerc**
[feature][input wanted][balance][wiki]

## About the PR 

As the title says. It will only remove the weakest kudzu, thick and dense kudzu tiles will be immune to it.

## Why's this needed? 

Kudzu is extremely annoying to deal with. It'd be nice to have some decently strong counter against it.

## Changelog

```changelog
(u)TTerc
(*)Weedkiller (atrazine) can now remove non-thick/dense kudzu tiles.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
I can absolutely see the use of this and it'd be nice to get people to stop using flamethrowers and welderbombs to combat kudzu, but at the same time, it might not be the best way of bringing it around. Kudzu already has the hard counters of welding tools, multitools, candles, any melee, and any and all fire. I feel like, if anything, this might encourage people to poison bomb kudzu-infested and do as much harm to the crew as to kudzu, for better and for worse.

I'd love to see a test round or two where this gets used in a multiplayer situation.

**Comment by colossusqw** [comment]
I had an idea to do this on the back of my mind, thank god someone else decided to do it cause the way i get ideas and never code em i'd never even start lol. Real nice change!

**Comment by Kyle2143** [comment]
I like it, it makes sense. But I think the reagents should deplete for each kudzu tile it destroys. And more dense kudzu tiles, the more reagent should deplete from the pool.

**Review by Tarmunora — APPROVED** [review]

**Comment by TTerc** [comment]
I tried to mess with reagent depletion but as of now, atrazine smoke that stayed on the tiles would not further affect the spread of leftover kudzu, if I observed that correctly, meaning that changing the depletion values wouldn't really do that much

And, dense/thick kudzu will be immune, like I mentioned

**Comment by TTerc** [comment]
Closing it since I like #7173 better

**Pull request closed without merging**
