### PR TITLE
Oshan tweak to southern end, primarily security

### PR DESCRIPTION
**Pull request by Kubius**
[INPUT]
## About the PR 

Set of changes to the south end of Oshan, including some fixes and a significant change to Maintenance. **Should be assessed by relevant mappers before merge.**

- Fixed erroneous presence of a wall under the new Armory entrance, and relocated it to a less corner-y spot.
- Extended Armory to create room for the items that were previously blocking the new entrance.
- Added windows for the single-person Brig cells.
- Added a maintenance entrance to the Refinery to increase maintenance contiguity.
- Adjustment to Maintenance to accommodate changes, including a little break area by the Brig cells.

oshansouthtweak

## Why's this needed? 

Improves the security and functionality of Oshan's armory, and maintains/increases the navigation contiguity of Oshan south maintenance.

## Changelog

```
(u)Kubius:
(+)Adjustments to the southern region of Oshan Laboratory, primarily centered around Security by the maintenance side.
```

### CODE REVIEW

**Comment by MarkNais** [comment]
The walls of the solitary cells: are those normal walls behind the computers?
Otherwise, looks good to me (Not that I have any stake in this map)

**Comment by Kubius** [comment]
They are. Said normal walls were preserved as-is from Oshan's current live state.

**Comment by mybluecorners** [comment]
I don't like the removal of the maint corridor behind sec - it is a fun vulnerable area where lots of fights tend to happen and although the disposal chutes preserve the route they erase that space of 'sketchy security backdoor' existing

**Comment by Carbadox** [comment]
I like old Oshan as it is but find the maint tunnel under sec a bit off though I think getting entirely rid of the corridor is also kinda eh. My suggested, as illustrated below
https://media.discordapp.net/attachments/383743035894267905/723603130067058698/84840437-23ca3180-b005-11ea-8ada-d8236e712a2d.png
Continue the maint and end it at the sec hangar. The pink is plasma glass

**Comment by Kubius** [comment]
Re-kerfuffled the changes significantly. PR description and image have been updated.

**Pull request merged**
