### PR TITLE
Choking change to Various Hats/Helmats/Cigarettes

### PR DESCRIPTION
**Pull request by RSG250**
[BALANCE]

## About the PR 

Changes the choking interaction of most hats to work on hats that it LOOKS like it would work on (excludeing wizard hats)
changes choking interaction with some helmats (adjusted the sec "hardhats" so they remained unchanged, dont want to touch) 
Cigarettes and its childern no longer stop choking

## Why's this needed? 
its silly that that you cant choke people wearing a paper hat for example

## Changelog

```
(u)RSG250:
(*)Changes to Hats/Helmats/Cigarettes, If it looks like you can choke someone they you probably should be able to now (excluding wizard hats and sec helmats)
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
A very nice change to make things more consistent.

Description and changelog could use some work though. ^^

**Comment by RSG250** [comment]
i was following the guide so i requested from VS code lol

**Comment by RSG250** [comment]
i left most of the helmets unchanged and most hats dont have protection normally, and the few that do are cloth hats, if it does affect pierce protection there could be an issue with the helmats i changed.

**Comment by Carbadox** [comment]
Perhaps a similar change could be done in regards to cigarettes taking up the mask slot and still acting as protection against choking

**Comment by RSG250** [comment]
hmm ill take a look

**Review by PrimeNumb — CHANGES_REQUESTED** [review]
I like the idea, it's one that I've been bothered about for quite a long time.

Implementation-wise, this does affect the behavior of pierce protection. I don't think any of the affected hats actually have pierce protection (I think hostile critter drops can add this though? I am unsure), so it's likely not gonna be an issue _at the moment_, but I think it might be best to nip this in the bud right away so it doesn't turn up as a source of bugs in the future.

You could do this by either making a different flag and make it so aggressive grabs check for this new flag in `grab.dm`, or perhaps some other equivalent solution of your choosing.

This change also affects vampire bites. If that is intentional I would suggest having a look in that area of code as well.

**Comment by RSG250** [comment]
thanks for pointing that out, the bit about the vampires being affected was unintentional and im going to need to rethink how to do this, so im going to close this pr and start from scratch

**Pull request closed without merging**
