### PR TITLE
Alternate Spes Buff

### PR DESCRIPTION
**Pull request by Tarmunora**
[BALANCE] [EXPERIMENTAL] [INPUT]
## About the PR 
Instead of making it cheaper, how about we make the spes cooler?
Makes the spes always hit floor targets, so the throw is less detrimental
Changed range profile a bit, mostly similar
Spes will now attempt to delimb at close range, and will cause widespread organ damage
Spes ammo in ammotech replaced with spes/weak which does not cause the delimb, has reduced organ shredding power, and does slightly less damage/shot, to keep the Spes more unique, and not something that can be so closely replicated by hacking into the armory

## Why's this needed? 
An alternate approach to #752 , in making the weapon stronger/more interesting, instead of making it cheaper

## Changelog

```
(u)Tarmunora:
(*)Changed Spes-12 to blow off limbs and cause massive organ damage.
(+)Replaced buckshot in armory with weaker variant.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
fair wrt armor, but handling armor in on_hit() is kinda aaaaa.
TODO: look into that

**Comment by ryebek** [comment]
I'd personally keep the buck in the ammovend the same as current buck, it doesn't need a nerf lumped in with a spes buff. Other than that, I think this is nice, although delimb chance should preferably major imo, as otherwise, it just feels tacked on and isn't much of a buff to the spes. Its not like we don't already have high damage stunning weapons that also delimb(csaber), and that costs less than the spes.

**Comment by Tarmunora** [comment]
Between the 100% floorhit and the organ shredding, I think that losing 20 damage/shot on armory buckshot is about an even trade.

**Comment by ryebek** [comment]
I'll probably make a PR separating current buck, spes ammo, and weak buckshot after this is merged, as doing so requires changing more files than this affects, and I'm too lazy to download this repository to make a pull request to it, but I still think the ammovend buck shouldn't be nerfed, so I'll be doing that later I guess 🤷

**Pull request merged**
