### PR TITLE
Update Lawbringer "Assault" sounds

### PR DESCRIPTION
**Pull request by Carton171**
## About the PR 
Adds a new sound effect for the lawbringers Assault mode.

## Why's this needed? 
The current sound has very little weight to it for such a high damage projectile that instantly melts doors.

## Changelog 

```changelog
(u)Carton171
(*)Introduced a new sound for the Lawbringer "Assault" mode.
```

### CODE REVIEW

**Comment by trazodont** [comment]
asslaser.ogg

**Comment by Cherman0** [comment]
The rising pitch part at the end seems a bit odd, especially since the laser has probably already hit something at that point. I'dd probably trim it to just that initial "energy blast" sound

**Comment by Carton171** [comment]
> The rising pitch part at the end seems a bit odd, especially since the laser has probably already hit something at that point. I'dd probably trim it to just that initial "energy blast" sound

That's not meant to be a sound made by the projectile itself, it's moreso meant to be from the weapon as the leftover energy from the shot dissipates.

**Comment by Gibuscode** [comment]
new-ass-sound my beloved

in all seriousness this sounds rad as hell and i sure wouldnt mind getting shot by it

**Comment by TealSeer** [comment]
where did you get the sound/how is it licensed?

**Comment by Carton171** [comment]
> where did you get the sound/how is it licensed?

I got it directly from the creator of said sound, and it's licensed under CC0 1.0 Universal

**Comment by Carton171** [comment]
> > where did you get the sound/how is it licensed?
> 
> I got it directly from the creator of said sound, and it's licensed under CC0 1.0 Universal
It's one of a couple weapon sound effects Eric Gurt that he made available on his website:

**Comment by Carton171** [comment]
> > > where did you get the sound/how is it licensed?
> > 
> > 
> > I got it directly from the creator of said sound, and it's licensed under CC0 1.0 Universal
> > It's one of a couple weapon sound effects Eric Gurt that he made available on his website:
> > https://www.gevanni.com/?page=sfx

**Comment by Carton171** [comment]
It seems like a github glitch broke my comment and closed the PR, thank you very much github

**Comment by DecidedlyUnethical** [comment]
Carton wanted to request a review but couldn't, requesting it for him.

**Pull request merged**
