### PR TITLE
Adds The Security Backpack/Satchel

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Adds the security backpack and/or satchel. Sec officers, sec assistants and the HoS spawn with one instead of a regular backpack. Contains a box with oxygen as normal, also includes in-hand sprites. No mechanical differences from normal bags

## Why's this needed? 

IMO departmental backpacks are a good and cool thing. Adds style and flavor to jobs, and is something I think would be good to expand even beyond med/cap/sec eventually. Bag is an older sprite I made and had sitting around modified and tweaked to match the palette sec uses. Little extra visual connection between the jobs in the department. also i think they look cool

## Changelog

```changelog
(u)Flaborized
(*)Security personnel now spawn with a visually distinct bag.
```

### CODE REVIEW

**Review by Gannets — APPROVED** [review]
Departmental bakcpacks, yes!

**Review by Tarmunora — CHANGES_REQUESTED** [review]
should add one to security lockers, so they aren't job-spawn-only, I think

**Comment by Zonespace27** [comment]
Any chance we could get a blue (for bluesec) variant as a medal reward?

**Comment by Flaborized** [comment]
> should add one to security lockers, so they aren't job-spawn-only, I think

Good idea

> Any chance we could get a blue (for bluesec) variant as a medal reward?

Nope, a lot of sec gear stuff is red with no alternative (even outside of HoS headgear and outerwear, sec assistants are also red) and I feel like a medal reward like that wouldn't make sense to function as just changing *one* item while leaving the rest red. Making a medal reward to make sec gear blue is out of scope for this and generally something I don't think is a fantastic idea anyways.

**Comment by virvatuli-gh** [comment]
Hell yeah they look great! Love the little golden button/latch being visible on the worn state, makes it pop well.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
