### PR TITLE
Brain Food for Big Brain

### PR DESCRIPTION
**Pull request by Azrun**
## About the PR 
Squid folks gain the ability to safely eat brain matter.  
* Become asymptomatic of Kuru if infected (from prions).
* Gain a minor foodbuff that heals brain damage when eating fleshy brains.

## Why's this needed? 
Improves the Starspawn experience. 
Updates `/datum/component/consume/food_effects` to function as intended.

## Changelog

```changelog
(u)Azrun
(*)Aquatic Genetics gives immunity to Kuru and minor food buff when eating brains.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
I think actively rewarding eating brains is a bit too far and doesnt seem like itll lead to any meaningfully positive scenarios (best case scenario is eating a monkey brain and only person involved with that is the squid and no external interaction, worst case scenario is non antag squid eats brain of person about to be borged for funny food buff, which seems like itll lead to a lot of toxicity.), though not taking an effect from eating them seems like it could be interesting as itd make eating brains more of an antag thing then a thing that every squid should do.

**Comment by Titanslayer71** [comment]
> I think actively rewarding eating brains is a bit too far and doesnt seem like itll lead to any meaningfully positive scenarios (best case scenario is eating a monkey brain and only person involved with that is the squid and no external interaction, worst case scenario is non antag squid eats brain of person about to be borged for funny food buff, which seems like itll lead to a lot of toxicity.), though not taking an effect from eating them seems like it could be interesting as itd make eating brains more of an antag thing then a thing that every squid should do.

Just make sure ghost critters don't walk up to brain and eat it.

**Comment by Azrun** [comment]
> I think actively rewarding eating brains is a bit too far and doesnt seem like itll lead to any meaningfully positive scenarios (best case scenario is eating a monkey brain and only person involved with that is the squid and no external interaction, worst case scenario is non antag squid eats brain of person about to be borged for funny food buff, which seems like itll lead to a lot of toxicity.), though not taking an effect from eating them seems like it could be interesting as itd make eating brains more of an antag thing then a thing that every squid should do. 

Super great criticism.  Current implementation was a compromise to this exact concern.  The brain damage heal is pretty limited and intended as more of a thematic reward without giving a real boon to go out of your way to achieve.

More appreciable benefits should definitely be behind antag or something similar.  As brain eating is often unintentional grief from misunderstanding the prompts to straight up grief...

**Comment by ThatFiveGuys** [comment]
My main thing is i think that any reward is a reward no matter how extreme, and some people reading eating brains give buffs when squid on wiki will then eat brains regardless of what buffs it gives. Maybe instead of a status effect just a little sidebar message as like an easter egg thats like “you feel your mind absorbing the brain’s essence, or maybe that’s just your body rapidly trying to deal with the incoming prions.”

**Comment by Azrun** [comment]
Some of these commits do not belong here....

**Review by Azrun — COMMENTED** [review]
👍

**Pull request merged**
