### PR TITLE
Connects the north catalytic substation on nadir with the newly added PTL

### PR DESCRIPTION
**Pull request by Knipje**
[STATION-SYSTEMS]

## About the PR 
This PR connects the north catalytic substation on Nadir with the PTL in order to allow it to access this part too, consequently it also combines all three engine output wires into one, making them all accessible through the same wire.

## Why's this needed? 
Only the south substation was connected previously which is a weird inconsistency as it allows all engines to be connected except for the north ones.

## Changelog 

```changelog
(u)Knipje
(+)Nadir North Catalytic Substation connected to PTL.
```

### CODE REVIEW

**Review by TheTyrant25 — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
Very big long wire with not much purpose? Iunno, doesn't seem very realistic

**Comment by TheTyrant25** [comment]
tbh i don't think the south catalytics should connect to PTL anyway, they're pretty much nadir solars. But if one's connected, the other one should be too

**Comment by Knipje** [comment]
good point honestly, itd probably be better for neither to be connected

**Comment by ZeWaka** [comment]
Seems like this PR is no longer wanted?

**Pull request closed without merging**
