### PR TITLE
damaged floors overlays, fix some walls breaking

### PR DESCRIPTION
**Pull request by Skeletonman0**
[SPRITES] [QOL] [FEATURE]
## About the PR 
this PR mainly aims to reduce the amount of interactions that can cause "FIX ME" sprites to appear on floor tiles.

changed it so that floor tiles now use overlays to show damage, instead of swapping out the sprite.

the spookify station proc has been changed to fix the disaster/sol issues caused by swapping the sprite for walls.
it also burns the floor tiles instead of leaving them as regular tiles with the damage sprite

## Why's this needed? 

currently, disaster/sol breaks all non reinforced wall sprites, and burning/exploding certain kinds of floor tiles can result in broken sprites.

damaged floors using overlays also allows things such as the ss13 sign staying visible when damaged

with this PR:
image

current behavior:
image

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
idk some of these will probably look pretty bad on a non-tile turf, like grass.

**Comment by ThatFiveGuys** [comment]
I think having it whitelist based seems the best.

**Comment by ZeWaka** [comment]
> I think having it whitelist based seems the best.

i was thinking just improve the sprites

**Comment by frawhst** [comment]
System seems good, agree that the sprites could use improvement.
Generally happy with this though.

**Pull request merged**
