### PR TITLE
Warm farts

### PR DESCRIPTION
**Pull request by Azrun**
## About the PR 
Expelled gas from farts uses body temperature. [feature]
  * Certain interactions could presumably allow for flaming flatulence. [balance]
  * Farting would be more likely to ungroup atmos on standard air_groups.
**Note: This does allow for cold farts!** 🧊 

## Why's this needed? 
Enhanced system interactions between chem/diseases/effects -> atmos -> objects/mobs

## Changelog

```changelog
(u)Azrun
(+)Your flatulence now corresponds to your body temperature.
```

### CODE REVIEW

**Comment by Carbadox** [comment]
Does this mean I can burn people to death with superheated farts?

**Comment by comradef191** [comment]
farts
of
f i r e

**Comment by PrimeNumb** [comment]
> Does this mean I can burn people to death with superheated farts?

As funny as this is, this could be a potential problem due to how wacky body temperature likes to be.

**Comment by TTerc** [comment]
It actually could be a problem funnily enough as being close to superhot fires also raises your body temp a lot
But I guess if you have access to superheated gas, you could've as well just release it instead of farming superhot farts in your body. And you'd likely be the first victim of your own farts

**Comment by BatElite** [comment]
I'm a little concerned about the volume thing, aside from hot farts you'd fart more the hotter your body temp gets?
AFAIK it is (or at least used to be) quite possible to live at extremely high body temps.

**Comment by Tarmunora** [comment]
as funny as this could be, I feel like it's a bad idea

**Comment by Carbadox** [comment]
Perhaps make them transfer only 10% of the heat? That would probably resolve some balance concerns and make it work more realistically.

**Comment by Azrun** [comment]
Unless the area has been depressurized, the amount of gas introduced is going to be mixed so it has a lot to overcome.  Volume doesn't matter for turf `merge` as out is introduction of molar quantity and temperature and heat capacity.  I can post some maths later.

Based on how some interactions work it seems like cold farts would be more annoying with things that set your body temp to 0.

Or maybe I just need to do my fart game in my testing.

----

Objectively it seems like a performance hit with nonstandard body temps for memes.  There might be some goofy interactions that could be leveraged but I don't see it outshining an igniter or welder.

**Comment by Azrun** [comment]
Eating two VERY (chili con flagration, El Diablo, used welding tool between the two...)
0.69 moles o' Fart
Body Temp: 2758 K
Air: 293.15 K --> 348.32 K

Fartonium!
6.9 moles o' Fart
Body Temp: 2012 K
Air: 298.7339 K  --> 617.34393 K

Fartonium!
6.9 moles o' Fart
Body Temp: 1588.065 K
Air: 379.63483 K --> 595.4034 K

Small Room Farty (3x4)
small_farty

Big Fartonium Body Temp Around 345 K (3x9)
big_farty

So depending on how recently you did something to extremely shift your body temperature vs size of the space can have a pretty big effect.

**Comment by ZeWaka** [comment]
going to close this until atmos is like completely reworked or something so it's not so laggy

**Pull request closed without merging**
