### PR TITLE
Minor engiborg and constructiborg buff.

### PR DESCRIPTION
**Pull request by Arahimine**
## About the PR
Engiborgs get floor/wall planners for proper station renovation. To compensate, constructiborgs (I was shocked to find out they're even a thing) get hand labelers for APC naming, and their RCD has been upgraded to a (safe) RCD Deluxe. Input and feedback appreciated.

(Also, made the RCD Deluxe's cost reduction actually work for silicons. I know there's probably a better way to do it than setting the multiplier to 10 for the Deluxe, but I'm not at all experienced in DM and this is my first PR, so I'm terrified to touch code that isn't just variables.)

## Why's this needed?
Fully removed tiles don't retain their original appearance upon being replaced, meaning that a sufficiently powerful explosion can and will mess up the carefully curated aesthetic of the ship, and there's just nothing that borgs can do about that. Additionally, the planner is the only practical advantage that constructiborgs have over engiborgs. Given that the construction module is only available in the trench of all places, which is already only accessible from certain maps, it's absolutely NOT worth launching an expedition for. Now, an upgraded RCD that produces no sparks and has a tenth of the cost, that just might be worth the effort.

## Changelog

```
(u)Arahimine:
(+)Gave floor/wall planners to engineering cyborgs.
(+)Gave hand labelers to construction cyborgs, and upgraded their RCD.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Hm. I think that conworker borgs aren't available normally in-game so this is probably fine. Otherwise I might be concerned about giving a borg a cost-reduced RCD

**Comment by Arahimine** [comment]
I'm working purely off months old second-hand information, but apparently there is or was a single construction worker module in the trenches. So if it is in the game, it's clearly rarer than seeing a macho man.

**Comment by nefarious6th** [comment]
I'm half-and-half on this. I don't hate it and I play more as borg, but this just makes it so there's no reason to play Construction Worker, like ever, when you can just be an engineering borg and do all the customizations for someone (and not have needs on RP, or whatever). FWIW, when I do build things for people, it's usually staff assistants if a totally new room, or a room renovation of a public place if for someone else, so the door labelling and access isn't totally essential, meaning CWorker is even less meaningful. (And that borgs can just device scan and print the door with the right access anyways). Again, not sure, but all I see is total redundacy of CWorker with this.

**Comment by Arahimine** [comment]
Oh, I agree, but really that just puts conworker in parity with a lot of other roles. There's not much a medical doctor can do that a mediborg can't do (and arguably better, since mediborgs can't run out of basic healing chems), not much an engineer can do that an engiborg can't do (plus engiborgs can run straight into fires with no real concern). Plus the fact that there's only one conworker per station, and I don't really see engiborgs using their existing RCD to actually construct anyway. But yet, people still play engineer, medical doctor and janitor despite cyborgs being at least as good as them, so I don't see why people would likewise stop playing conworker. (Also, consider that conworker is explicitly meant to build and renovate, whereas engiborgs merely can do so, but aren't necessarily expected to - and are generally worse at it due to having regular RCDs.)

**Comment by nefarious6th** [comment]
The construction module I'm fine with; the more I think about the engineering one though, not as much.
I fail to see the regular vs. deluxe RCD thing, since the only thing a borg RCD can't do is name doors and do access, which they can just do by scanning and printing the door they want/no one cares about door access for renovation projects. I'm fine with the rare module for a construction borg having these tools especially since construction borgs also can't do everything an engineer can; but not the all-around engineering borg because it seems like overstepping the boundaries of the role. A medical borg can heal people but can't do everything in the medical department like make new borgs or reasonably run the pharmacy (and maybe path, if that's added back). A mining borg has a tougher time running cargo than a human and has a lock on the power tools it can use, a chem/science borg isn't running artlab, a civ borg can't run the kitchen alone, and a brobocop can do detective work at most, if they're feeling useful. I understand engineering borgs can do everything an engineer can do, but they can't do everything the Engineering Department can do, and I don't see a reason to change that when no other module is able to do everything in a given department. I'm not sure what else to say. If you want to make new rooms, then play CWorker; if you want to repair things to how they were, then work _with_ the CWorker. This just seems to be increasingly isolating for silicon players.

**Comment by Arahimine** [comment]
That's fair. What would you think about making conworker modules more available (perhaps as an option from hacked module rewriters) instead?

Also, by the RCD thing, I mean that borg RCDs take internal battery, and eat it up fairly quickly. I know from experience that actually trying to do a conworker's job as an engiborg basically requires you to have a charging dock nearby, which usually isn't an option when you're constructing something in some far-flung corner of the station, or worse, off-station entirely.

**Comment by nefarious6th** [comment]
Sorry, I didn't quite understand what you were initially getting at with the RCDs, but I do now! Thank you for clarifying that!
I think a hacked conworker version would be a good compromise. You get better accessibility of the tools without it being a default, and some motivation, but not too much, to actually go through the work of making it; you also then get the distinct construction/engineering/mining groups in the borgs to mirror the way the greater department breaks down for humans, too. I don't have too much worry about how this works for a rogue borg/traitor roboticist either, because if you're a borg making holes in the floor, an RCD is an RCD, I guess! It's hard to strike a balance between having a borg that can satisfy a role where it's missing, like an engineer, without having them subsume the entire department; but I think this would be a good solution to that.

**Pull request closed without merging**
