### PR TITLE
AI laws update timer

### PR DESCRIPTION
**Pull request by amylizzle**
## About the PR 
image

It now takes a couple minutes for law updates to propagate. Exceptions to this: Ion laws apply instantly, admin law reset verb applies instantly.
Oh also I dropped the weld/screw/insert time from 5 to 3 seconds.

## Why's this needed? 
People kept asking for it, also [I proposed a rule change which might need it](https://forum.ss13.co/showthread.php?tid=19117)

## Changelog

```changelog
(u)Amylizzle
(*)AI Law Racks now have a time delay before law updates apply. 
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Timer honestly seems like itll make it even more harder to rogue, with the AI being able to be on default laws for minutes until its actually rogue. Also I think itd be better to keep the weld and screw time as is but remove the insert time, that way its still harder to remove default laws but its easier to add new ones.

**Comment by ZWRh3** [comment]
major flaws: the AI can just report its being rouged in the several minutes before update

hell even a single high ranking nerd can do stuff like "report every law update before it happens" and even laws that have do not state clauses would get snitched

while it would prevent the akward thing that is being rouged for 30 seconds its not thought out well

**Comment by amylizzle** [comment]
Yeah, if I'm honest - I don't particularly like this idea. I did it because people kept asking for it, and maybe we could test it on live and see how it plays.

In terms of balance though: the AI receives no notification that their laws are being changed until they receive the actual update, so no real change to the "hey someone's in my upload" behaviour. The timer is only set to two minutes, and it isn't reset when laws change, so you could in theory wait until the timer was on the last few seconds before inserting your new law to have it apply almost instantly.

**Comment by ThatFiveGuys** [comment]
This still makes experienced ais who rely on viewports far stronger at preventing getting rogue, and inexperienced players who dont know that actually youre supposed to rogue them during time intervals far less capable at roguing the ai

**Comment by amylizzle** [comment]
> 

That doesn't sound like a problem? People who are more skilled at the game should do better than people who are not skilled at the game.

**Comment by flrsh** [comment]
Not a fan of this specific PR (though your proposed rule change seems like a good idea to me), it seems unintuitive. Dropping the weld/screw/insert time seems okay though.

**Comment by amylizzle** [comment]
Yeah, I think given that I don't actually want this in the game, I'mma close this PR. I'll do a new one with the shorter timings in it.

**Pull request closed without merging**
