### PR TITLE
Mulebot Donut 3

### PR DESCRIPTION
**Pull request by Wisemonster**
[FEATURE] [QoL]

## About the PR 
Adds mule bot functionality to Donut 3, along with a mule bot.

## Why's this needed? 
Stardardization. Donut 3 also doesn't have any kind of delivery system for cargo to use, besides the pads.

## Changelog

```changelog
(u)Wisemonster
(*)NanoTrasen Has added the proper systems to Donut 3 to allow mulebots to function. (Mule bot included)
```

### CODE REVIEW

**Comment by Wisemonster** [comment]
Some Notes:
  - I tried adding delivery locations to the court room, security, and the bridge. Unfortunately, these locations are positioned in such a way that the mule bot would go through med bay in order to deliver, and use robotics on it's return trip.
  - I originally had hydro deliver next to the entrance to the hallway, in hydro. However, the mule bot would take a """"shortcut"""" through maint, into the ranch, then into hydro. The current location should function without the bot taking this path.

**Comment by Wisemonster** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Review by virvatuli-gh — APPROVED** [review]
Sure, I'd love to see people getting over by Mulebots on Donut 3.

**Pull request merged**
