### PR TITLE
Makes pool floors actual floors

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BUG] [CLEANLINESS]
## About the PR 
Changes all pool floor types to inherit from `/turf/simulated/floor` or `/turf/unsimulated/floor`, moves them into the `floors.dm` file and their sprites into `floors.dmi`. This fixes a minor visual bug with flock conversion and the only other real changes it should cause are pool floors now being able to be torn up and scorched.

## Why's this needed? 
FlameArrow pointed out that #10044 is just introducing a snowflake check instead of actually solving the issue so I bit the bullet and did this.

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Looks like mapdiffbot is exploding from having to parse unused maps, let me know if it's better to manually exclude them, I just did find and replace all in VScode.

**Comment by TobleroneSwordfish** [comment]
I am going to regret this

**Comment by TobleroneSwordfish** [comment]
!merge_upstream

**Comment by TobleroneSwordfish** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
would like to see this

**Comment by TobleroneSwordfish** [comment]
alright I'll probably just make a new branch for it then because this one has a radioactive git history

**Comment by TobleroneSwordfish** [comment]
💀

**Comment by TobleroneSwordfish** [comment]
remade here #10592

**Pull request closed without merging**
