### PR TITLE
Deluxe Agent Card - HoP traitor item

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Adds the "deluxe agent card", a reusable version of the agent card allowing for on the run identity crafting for 3 tc

## Why's this needed? 
HoP only has the AI law traitor items and thats kinda boring

## Changelog 

```changelog
(u)JORJ949
(*)The Head of Personnel can now buy a reusable "Deluxe" agent card. Also available to spy thieves and nuclear operatives.
```

### CODE REVIEW

**Comment by TDHooligan** [comment]
might be too crazy? just swapping your ID freely, constantly, without being near an ID computer. could make it way too easy to entirely fuck up any and all comms with just a voice changer.

**Comment by JORJ949** [comment]
> might be too crazy? just swapping your ID freely, constantly, without being near an ID computer. could make it way too easy to entirely fuck up any and all comms with just a voice changer.

If this does become an issue it would be a fairly simple change to just add a limit on how many uses it has

**Comment by JORJ949** [comment]
> But i also think it does not need to be a HOP-exclusive item. This could fit pretty snuggly in the general traitor list, especially with a whopping 3TC cost.

This was made because HoP had no real exclusive items other than AI stuff which isn't great and also while it could possibly fit in the main traitor menu I wouldnt want to see it used too much because of the potential it has that TD pointed out.

**Comment by JORJ949** [comment]
:/

**Comment by FronkyGeniuZ** [comment]
Woah cool idea

**Pull request closed without merging**
