### PR TITLE
Adds Air Alarms to Cogmap 1

### PR DESCRIPTION
**Pull request by comradef191**
## About the PR 

Adds Air Alarms to Cogmap1, located in most major and large rooms, and not in Maitenance Tunnels

Adds four General Alert computers to Cogmap 1:
_One in both Arrivals & Escape-adjacent Air Hookups
One in that maint room i forgot the name of above the Owlery with the computer and shit in it
One in Engineering_

## Why's this needed? 

Makes the PDA program for Air Alarms actually usable on Cogmap 1, also gives players some indication of the state of other sections of the Station without needing to confirm it in-person.

## Changelog

```changelog
(u)Comradef191
(*)Added Air Alarms & Alert Computers to Cogmap 1.
```

### CODE REVIEW

**Comment by penny64** [comment]
Niiiice thanks for this! 👍

**Comment by penny64** [comment]
I dunno tho are you sure 600 lines isn't too big? >;p

**Comment by Sovexe** [comment]
changes look ok, air alarms were removed forever ago. I don't actually know why though

**Comment by Azrun** [comment]
Pathology Research (@ 124, 83) needs nudge
Should Owelry (@ 133, 174) have sensor?

**Review by ZeWaka — CHANGES_REQUESTED** [review]
^

**Comment by comradef191** [comment]
Arzun fixes implemented, plus some minor changes I spotted.

**Pull request closed without merging**
