### PR TITLE
Offsets a few common station items

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr offsets a few common station items to make them look better in context. See picture below
image

## Why's this needed? 
I think it makes these sprite look much better in game

## Changelog 

Shouldnt be needed

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Hey fair warning this can lead to some maps looking jank, I intend to run through these items and find offset ones so I can manually make them not jank, so to avoid mapping conflicts galore, can a dev tell me when your ready to merge this, I do the mapping changes, then I get a relatively quick merge

**Comment by Sord213** [comment]
Hm. I'm not sure if this is the best way to do this. I think adding a default pixel_y value might be better, as any map that has them already offset will have them pushed up even further. Mostly talking about the microwave and glass recycler. I doubt the others would have much offsets set on them already.

**Comment by ZeWaka** [comment]
> Hm. I'm not sure if this is the best way to do this. I think adding a default pixel_y value might be better, as any map that has them already offset will have them pushed up even further. Mostly talking about the microwave and glass recycler. I doubt the others would have much offsets set on them already.

yeah i'd rather do this

**Comment by ThatFiveGuys** [comment]
Sounds like a better idea, Ill remake this pr in a bit

**Pull request closed without merging**
