### PR TITLE
Adds printing sound effect to security records computer

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Adds printing sound effect to security records computer

## Why's this needed? 
Current iteration lacks a matching sound effect informing the user that the action was done successfully. This should resolve that

### CODE REVIEW

**Review by virvatuli-gh — CHANGES_REQUESTED** [review]
As per the PR that added the sound `printer_cargo.ogg` , it was made specifically to make label printers sound different from other printers. Consider using an alternate sound effect to add to the soundscape rather than reusing it.

**Comment by Carbadox** [comment]
Alot of stuff shares the same sound effects EG - Jumpy mutation and shoving. Seems wierd for a sound effect to exclusively allowed on one object.

**Comment by virvatuli-gh** [comment]
> 
> 
> Alot of stuff shares the same sound effects EG - Jumpy mutation and shoving. Seems wierd for a sound effect to exclusively allowed on one object.

It's not weird, it's good sound design. A specific sound being attached to a department allows for auditory identification for that department. Said sound becomes associated with the area, and allows players to recognize "hey, I hear that sound effect, that must mean I'm near X location". This contributes positively to the station's soundscape, which is something I want to focus on going forward. Like reusing sprite assets, reusing sound assets is lazy.

**Review by virvatuli-gh — APPROVED** [review]
I like this a lot better and would give some more life to a sound that's rarely heard otherwise, seeing as how it's tied to only the printing press currently. Good choice.

**Pull request merged**
