### PR TITLE
PTL rework

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
## About the PR 
Refactors power transfer lasers into a type of linked laser that recursively propagates and updates instantly using signals.
This lets us have the long coveted PTL mirrors!

image

Performance impacts: probably okay ish. The laser is effectively free while running, the only expensive part is redirecting it.
To help with performance, the lights on each laser segment have been replaced with simple lights since doing so seems to cut the total CPU time of propagation by about a 1/3, and the laser causing atmos hotspots has been removed entirely because frankly you didn't know it did that either.

TODO:
- [x] fix obtaining credits from PTL
- [ ] some way of obtaining mirrors
- [x] less codersprite mirror sprites
- [ ] an actual use for the laser power
- [x] make mirrors work with emitter lasers too (scope creep time)
- [x] testmerge this and watch the world burn

## Why's this needed? 
Lasers are cool, especially when they go around corners.

```changelog
(u)LeahTheTech
(+)The PTL has been internally reworked, and should respond a lot faster. Please report any weirdness with the beam.
```

### CODE REVIEW

**Comment by RelentlessGarbage** [comment]
Any changes to PTL strength? I know that people have been having trouble getting "For your Ohm Good" nowadays with some of the engine/atmos reworks.

**Comment by TobleroneSwordfish** [comment]
Not in this PR, although I'd welcome an attempt to rescale it if anyone wants to try to decipher the formula.

**Comment by Gannets** [comment]
holy fuck, ptl mirrors

**Comment by ZeWaka** [comment]
> Not in this PR, although I'd welcome an attempt to rescale it if anyone wants to try to decipher the formula.

Isn't the formula a desmos?

**Comment by Azrun** [comment]
> > Not in this PR, although I'd welcome an attempt to rescale it if anyone wants to try to decipher the formula.
> 
> Isn't the formula a desmos?

Yep!
Some relevant forum threads, not sure how useful they are though...
https://forum.ss13.co/showthread.php?tid=16828
https://forum.ss13.co/showthread.php?tid=16471
https://forum.ss13.co/showthread.php?tid=15976

**Comment by ThatFiveGuys** [comment]
Scope creep but any chance of PTL laser splitters?

**Comment by TobleroneSwordfish** [comment]
Definitely, but probably not in this PR

**Pull request merged**
