### PR TITLE
Cuffs rebalance

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Shakes up handcuffs a lil bit

Removal times
normal cuffs: 40 - 50 seconds to 25 - 35 seconds
custom material cuff: max cuff time 50 seconds to 40 seconds

Apply times
Overall 6 seconds
Security bonus: 2x to 1.5x
ziptie cuffs 0.5x apply
normal cuffs: 6 seconds crew / 4 seconds security
ziptie cuffs: 3 seconds crew / 2 seconds security

before was 4 seconds crew / 2 security for both

Pouch changes
Security officers now spawns with 2 pairs of ziptie cuffs and 1 pair normal
Security assistants now spawn with 2 pairs of ziptie cuffs

## Why's this needed? 
I think that currently cuffs are too strong. If you do get cuffed they are either a non issue due to strength or you need to stand still for almost a full minute to remove them, its just too punishing. 
There is also no reason at all to use ziptie cuffs since they take the same time to cuff someone. Now ziptie cuffs should be the standard for most arrests with normal cuffs being reserved for higher priority targets with the slightly longer cuff time.

## Changelog 

```changelog
(u)Cheffie
(+)Cuffs have been rebalanced slightly:
Normal cuffs now take a bit longer to apply and less time to remove. Ziptie cuffs take less time to apply. 
Security now spawns with some ziptie cuffs in their pouches.
```

### CODE REVIEW

**Comment by Juggernaut2442** [comment]
not quite sure about this one, think a forum post might be good to discuss it

**Comment by Tarmunora** [comment]
Not really a fan of these changes, at least not all together. This PR ends up being a large shotgun nerf to handcuffs by hitting availability, apply time, and cuff duration all at once.

**Comment by CheffieGithub** [comment]
You have to consider the fact that security still has a massive supply of handcuffs, the majority of stun times will still allow for cuffs with a gracious amount of time spare and even with ziptie cuffs there will be more than enough time to search someone even more so if they are buckled.

Maybe this PR is a good candicate for a test merge? won't know how it plays otherwise.

**Comment by colossusqw** [comment]
> You have to consider the fact that security still has a massive supply of handcuffs, the majority of stun times will still allow for cuffs with a gracious amount of time spare and even with ziptie cuffs there will be more than enough time to search someone even more so if they are buckled.
> 
> Maybe this PR is a good candicate for a test merge? won't know how it plays otherwise.

This seems like a very big and overarching change, but i would personally love to see how it goes with a test merge. Could end up horribly, but it could also just work and giving it a couple of days wouldn't really be horrible even if it turns out to be the wrong call...

**Comment by flappybatpal** [comment]
Also have my doubts about these changes.

**Pull request closed without merging**
