### PR TITLE
Rationalize Donut 3 phones

### PR DESCRIPTION
**Pull request by flappybatpal**
## About the PR 
Removes the following phones from Donut 3:
RD Office
Security Equipment Room
Chief Engineer's Office
Brig Long Term Cell - North (Replaced with Robustris/Slot machine to match South when divider is raised)
Pod Bay Security
Arrivals Security
Escape Hallway Security
Chapel Office

Moves the following phones on Donut 3:
Captains Office -> Bridge
Medbay Lobby converted to Wall Phone for visibility.
Chemistry -> Science Lobby

New left, old right
image
Ignore Drug Den - Random prefab

## Why's this needed? 
Excessive number of phones.
Office phones are largely pointless but these might be wanted for RP?

## Changelog

```changelog
(u)Flappybat
(*)Changed phones on Donut 3, removed arrivals/office phones. Moved and added some phones.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Bridge phone:
image

Moved bar phone:
image

Botany phone:
image

QM phone:
image

Science lobby phone:
image

**Comment by Tiresoup** [comment]
Remember your changelog, you forgot to switch it from the default.

**Comment by EyeSpider** [comment]
Shouldn't the bar phone be somewhere the bartender can reach without having to leave from behind the desk?

**Comment by TobleroneSwordfish** [comment]
> Shouldn't the bar phone be somewhere the bartender can reach without having to leave from behind the desk?

but also it's a public phone now that's nice for calling the radio station or whatever so it should stay publicly accessible, perhaps put it on the bar like Cog1

**Comment by flappybatpal** [comment]
> Shouldn't the bar phone be somewhere the bartender can reach without having to leave from behind the desk?

It was even further away before. Now it is closer.

**Review by TTerc — APPROVED** [review]
Looks good 2 me

**Pull request merged**
