### PR TITLE
trying to grab a shambler throws you away

### PR DESCRIPTION
**Pull request by ZWRh3**
[BALANCE][FEATURE]
## About the PR 
Makes shamblers no longer grabable.
(has a minor visual bug that only happens if you are wearing magboots and using stims while trying to grab a shambler) (the grab item icon staying even after deletion)

## Why's this needed? 
its very common for shamblers to be straight up pinned then executed while helpless. It is also common for someone to just grab a shambler and suicidally run off with them off the shuttle.

## Changelog

```changelog
(u)ZWRh3
(*)You can no longer grab shamblers, trying to do so will stun and throw you.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
can't you just drop the grab before qdel to fix the visual bug?

**Comment by nefarious6th** [comment]
im personally a fan of the shambler grab and would hate to see it go. sometimes it's too busy to start potshot firing in the shuttle or whatever and if someone wants to be a hero and do the grab and run, im inclined to let them. it's always funny.

**Comment by nefarious6th** [comment]
im personally a fan of the shambler grab and would hate to see it go. sometimes it's too busy to start potshot firing in the shuttle or whatever and if someone wants to be a hero and do the grab and run, im inclined to let them. it's always funny.

**Comment by colossusqw** [comment]
I feel just grabbing a shambler is extremely jarring, as it's supposed to be a big mess of meat and teeth, and just having some assistant grab it out of killing someone, pinning it to the ground and bashing it a bunch with a fire extinguisher reeeally doesn't fit. Great change imo.

**Comment by ThatFiveGuys** [comment]
Parroting nefs take here, its a funny way to take out an otherwise basically unkillable entity and helps make the shuttle a little less chaotic by preventing the inevitable fest of people misfiring and hitting people in the crowd. Having you be actively punished for even trying by having grabs throw you back seems bad too, I dont think actively punishing players for experimenting with combat strategies is good for new players. I wouldnt be opposed to having you take damage while holding a ling but i think this should be mild and mostly for thematic reasons, god knows ling as is doesnt need a buff. I do think lings being pinned is an issue, i dont think this is a good fix however and is a bandaid on a larger issue with pins and grabs. With lings infinite stam, lings can easily escape from pins/grabs, however the resist button is very out of the way and unintuitive. I think making iljk work the same as resist (or maybe just wasd and habe iljk do nothing for roleplay purposes) when it comes to grabs and pins would make escaping out of pins far more new player friendly and would fix the issue of lings getting pinned.

**Comment by ZWRh3** [comment]
if this change is bad would just no pins for shamblers be a good alternative?

**Comment by flrsh** [comment]
> if this change is bad would just no pins for shamblers be a good alternative?

Works for me.

**Comment by flrsh** [comment]
@ZWRh3 still planning on working on this?

**Comment by ZWRh3** [comment]
> @ZWRh3 still planning on working on this?

i will gladly make changes to it if needed tho i dont know what changes are needed

**Comment by flrsh** [comment]
> i will gladly make changes to it if needed tho i dont know what changes are needed

Changing this to just not being able to pin shamblers would be good I think!

**Comment by ZWRh3** [comment]
!merge_upstream

**Comment by ZWRh3** [comment]
if i were to make a grab upgrade signal should it be on the grabbing mob the target or the grab itself?

**Review by ZeWaka — APPROVED** [review]

**Comment by ZeWaka** [comment]
looking for the above changes

**Comment by ZWRh3** [comment]
> looking for the above changes

was planning to do it but wasnt able to due to being busy and someone already made an alternative PR now anyways

**Pull request closed without merging**
