### PR TITLE
Mono Card Resprite

### PR DESCRIPTION
**Pull request by ThyOverlord**
## About the PR 
I made new sprites for all mono cards, the new ones are much more unique and in my own opinion more enjoyable than the rather legally-non-distinct current sprites.
The new mono cards go off of origins rather than colors. These origins are as follows: Eldritch, Martian, Precursor, and Wizard
I believe the new cards will be very enjoyable!
image
The palettes are improved artifact palettes for recognizability!

## Why's this needed? 
UrsulaMajor(Emily) raised concerns over the sprites used for mono cards, as they may be under certain card game's Copywrite!
The new variants are completely distinct from this cardgame, and from any other variants of said card game.

## Changelog

```changelog
(u)ThyOverlord
(*)Resprited Mono cards and their respective stacks/hands.
```

### CODE REVIEW

**Review by ThyOverlord — COMMENTED** [review]
GOD WHY IS IT TRYING TO PULL THE CYBORG STUFF THEY ARE A DIFFERENT BRANCH AAA GOD

**Comment by DisturbHerb** [comment]
nice

**Comment by ThyOverlord** [comment]
keeping this up till new draft is made

**Comment by arborinus** [comment]
I feel like the martian and eldritch colors (maybe precursor too) may be a little hard to tell the difference between for colorblind players. Maybe even for people in dimly lit rooms (in-game) or playing on a smaller resolution. But that is a minor nitpick

**Pull request closed without merging**
