### PR TITLE
Potential fix for lizard skintone in character preview

### PR DESCRIPTION
**Pull request by Luxizzle**
## About the PR 

This fixes lizard skin tones in character preview, but I'm not sure what the original intent was for copying the original skin tone instead of the actual skin tone here.

## Why's this needed? 

Our lizard friends want to have scales, not some weird human skin.

## Changelog

```changelog
(u)Luxizzle
(+)Fixed lizard skin tone in character preview.
```

### CODE REVIEW

**Comment by Azrun** [comment]
I believe this will cause geneticsScanner to display the color-changed skin color instead of the original. As `colorshift` and `colorchange` adjust `s_tone`.

**Comment by Luxizzle** [comment]
> 
> 
> I believe this will cause geneticsScanner to display the color-changed skin color instead of the original. As `colorshift` and `colorchange` adjust `s_tone`.

Genetics scanner uses the

**Comment by Luxizzle** [comment]
Github mobile sucks

**Comment by Luxizzle** [comment]
> 
> 
> I believe this will cause geneticsScanner to display the color-changed skin color instead of the original. As `colorshift` and `colorchange` adjust `s_tone`.

Bah you're right and this breaks it.

**Pull request closed without merging**
