### PR TITLE
Datumises Syndicate Cyborgs

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Gamemodes] [Internal] [Code Quality]

## About the PR:
Syndicate cyborgs have been fully migrated onto the new datum system, however aside from Admin intervention, all sources still use the `make_syndicate()` wrapper, for logging purposes.

## Why's this needed?
Same rationale as #9366.

### CODE REVIEW

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Should probably also change the check in `antag_overlay_refresh` to check for the antag datum instead of the `special_role`

**Comment by Mister-Moriarty** [comment]
> Should probably also change the check in `antag_overlay_refresh` to check for the antag datum instead of the `special_role`

I intend to rework `antagonist_overlay_refresh()` into antagonist datums at a later date, utilising client image groups; I am unaware of any benefit gained from replacing the special role check with an antagonist datum check at this time.

**Comment by TobleroneSwordfish** [comment]
Unless it's changed with the way antag datums apply `special_role`, currently the special role only gets set if they didn't already have an antag role, meaning if you're a changeling and get syndie-borged you won't be able to see traitors.

**Comment by Mister-Moriarty** [comment]
> Unless it's changed with the way antag datums apply `special_role`, currently the special role only gets set if they didn't already have an antag role, meaning if you're a changeling and get syndie-borged you won't be able to see traitors.

The antagonist datum will always override the mind's `special_role`, regardless of whether the mind already has a `special_role`; Syndicate cyborgs with a preexisting antagonist role still may see other Syndicate cyborgs, traitors, and so forth.

**Pull request merged**
