### PR TITLE
Added identifer to GPS ping response

### PR DESCRIPTION
**Pull request by ThePotato97**
[qol] [minor]

## About the PR 

Adds GPS' identifier to the ping response, Added a sticker saying the GPS' netid on inspect, fixes bug where status would reply with the user's coordinates

## Why's this needed? 

Makes it easier to tell which GPS is which when pinging them for mechcomp stuff

### CODE REVIEW

**Comment by Sovexe** [comment]
I feel that serial makes more sense since the identifiers are alterable by users, have a default value of NT13, and can contain special characters

GPS's having a WNET engraving on them inside of a removable cover like APCs / Doors may also fit more in theme

**Comment by glassofmilk** [comment]
The device field on a packet is usually just the static device type name without any identifying information. If you want to have the GPS identifier on the ping packet, I think it would be better to create a different field instead of adding it on to device for consistency's sake

**Comment by ThePotato97** [comment]
image
Now it works more like PDAs

**Comment by ThePotato97** [comment]
image

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
