### PR TITLE
adds enakais mapvote sound

### PR DESCRIPTION
**Pull request by Adharainspace**
## About the PR 
this adds enakais mapvote sound to the pool of potential mapvote sounds. i cant do a sound preview so you'll have to download it to check yourself, heres the link: https://www.dropbox.com/s/sgvxuuyf6fjdr70/mapvote_enakai.ogg?dl=0

[ENHANCEMENT]
## Why's this needed? 
i thought this was funny and a good addition to existing map vote sounds, HOWEVER please let me know if theyre an admin only deal and ill close this pr

## Changelog

```
```

### CODE REVIEW

**Comment by flrsh** [comment]
I was actually thinking of making a PR to remove all the mapvotes lol. I feel like they've overstayed their welcome, but maybe that's just me.

**Comment by Adharainspace** [comment]
> I was actually thinking of making a PR to remove all the mapvotes lol. I feel like they've overstayed their welcome, but maybe that's just me.

idk thats fine too, this was just something i thought was funny

**Comment by MarkNais** [comment]
Map vote sounds are good. I particularly miss the in-chat link that came with the announcement, as I often have my "upper right" controls areas set to Local, and don't want to change to Status, wait for it to update, and then click. And I prefer to not use the command bar map-vote.

**Comment by ZeWaka** [comment]
Yeah - I think we just need a whole refresh of the sounds.

Not so much a fan of this particular one.

**Pull request closed without merging**
