### PR TITLE
Remaps Clarion's medbay

### PR DESCRIPTION
**Pull request by Chatauscours**
[mapping] [rework]
## About the PR 
This PR remaps the Clarion medbay entirely.
Removed the unused pathology to make up space for other rooms.
There are 4 major crime rooms: - the toilet in the staff room, the morgue autopsy, a new random room, the robotics maintance.
Generally makes the medbay more open and easier to navigate.
The rest of medbay is up to modern stadarts, with the interlink, etc...
Снимок экрана (114)

## Why's this needed? 
A lot of people have been expressing negativity about the wierd shape of the medbay (aka, a hallway), resulting in it being usually rebuilt mid round, every round.

## Changelog 

```changelog
(u)Chatauscours
(*)The Clarion medbay has been entirely remapped.
```

### CODE REVIEW

**Comment by flrsh** [comment]
Preliminary thoughts - this looks good! Both aesthetically and in terms of player flow. I foresee things getting pretty chaotic in the main medbay room, since you have to navigate in a circle around the tables, but that's still less chaotic than how things are now. My only other concern would be that this feels pretty different from the rest of the map in character (or, like, vibes), but I'd take a much improved experience over total cohesion.

**Comment by TemThrush** [comment]
This is a pretty good improvement from Clarion's current Medbay! Glad to see another medical breakroom, God knows they need it! I did notice that there are four medical vendors (not including the Interlink and the portable Nanomed) and while I'm certainly not going to complain if Medbay gets extra medicine I don't think there's a single map in rotation that ever exceeds three medical vendors (or two now, with the interlink replacing one). I'd say maybe cut it down to three or two medical vendors depending. There's no need for one to be in the pharmacy for sure. 

 Now I'm gonna be a bit nit-picky, but I noticed that you've removed the patient/long-term care rooms, and while they aren't necessarily vital to medical and I know we're a bit tight on space, I think it's a shame to just delete them altogether. As I said, they're not super necessary, but even the smaller maps like Atlas have a room with roller beds available for patients, and this Medbay seems to have none available at all even just the parts for building. 
 
Now for my even smaller gripes, the front reception area is incredibly bland with a pure white floor... (I think adding a wooden floor to the area with the gene-booth and couches could add a lot, reminiscent of Cog1, maybe get some snack vendors in here!) and there's no direct door to cloning from the main area the doctors will be in. Maybe adjusting the location of the surgery tables to be more accessible to multiple doctors and moving the cryo pods to the main area would help. Also, get a sink in that surgery room, we gotta keep our tools clean! Mostly small stuff but I think addressing them can really improve the QoL for medical staff if this gets merged. Otherwise, great work, I look forward to seeing where this goes! 👏

**Review by Sord213 — CHANGES_REQUESTED** [review]
Looks pretty nice, I do have some concerns though.
Screenshot_338
I'd like for the two maint tunnels to connect. It's one thing that's always bugged me. Both of those maint tunnels are dead ends for a staffie which suuuuuucks.
Screenshot_339
Would be nice to get a door from the medbay inner area so you don't have to walk through either the morgue or the medbay lobby to get to cloning.
Screenshot_340
Lacking a storage area for medkits and chems means this is going to get looted...instantly. 
Screenshot_341
The robotics flow/spacing seems pretty rough. Roboticists regularly walk to the fabricators and will get pushed by borgs going to charge. Not sure if you can find any space to make the lower area a little larger?

My biggest complaint is the lack of medkit/medicine storage room. Just as a couple rough ideas you could maybe swap the cloning and pharmacy around, make cloning a little smaller and genetics as well and have a small medicine storage room around there. Or if you come up with some other remedy feel free to try that as well.

**Comment by Chatauscours** [comment]
>I'd like for the two maint tunnels to connect. It's one thing that's always bugged me. Both of those maint tunnels are dead ends for a staffie which suuuuuucks.

Sure! Done!

>Would be nice to get a door from the medbay inner area so you don't have to walk through either the morgue or the medbay lobby to get to cloning.

Agreed, done!

>Lacking a storage area for medkits and chems means this is going to get looted...instantly.

>I noticed that you've removed the patient/long-term care rooms, and while they aren't necessarily vital to medical and I know we're a bit tight on space, I think it's a shame to just delete them altogether

Added a treatment center on the left side of the main room, where there's both roller beds and a locker filled with medkits that could store more medkits.

>I think adding a wooden floor to the area with the gene-booth and couches could add a lot, reminiscent of Cog1, maybe get some snack vendors in here!

Done! But didn't put in a snack vendor for people not to get crushed by it when they get thrown out of the booth.

>Also, get a sink in that surgery room, we gotta keep our tools clean!

Forgout about that, hehe

>The robotics flow/spacing seems pretty rough. Roboticists regularly walk to the fabricators and will get pushed by borgs going to charge. Not sure if you can find any space to make the lower area a little larger?

Really don't know how to expand it. I could swap the chargers and fabricators though, if you think it would help.

Снимок экрана (116)

Anyway, here's what we have now.

**Review by Sord213 — APPROVED** [review]
Yeah I don't have any real good ideas for improving the robotics setup/flow but it might not be a big deal. I may poke at it post-merging once you get the merge conflict (oops) resolved. Overall this seems like a really nice improvement.

**Comment by Chatauscours** [comment]
Right, it appears to me I have solved the merge confilct, at least both the github and vsc say that the merge conflicts have been solved, yet the githubbot isn't removing the tag. I might be dumb, but it looks good to me. 
Up to you @Sord213.

**Comment by Chatauscours** [comment]
Should be good to merge!

**Comment by Sord213** [comment]
Screenshot_351
pipe machine broke

**Pull request merged**
