### PR TITLE
fixes there only being one token for nukie murder box vr

### PR DESCRIPTION
**Pull request by Camryn-Buttes**
[BUG] [FEATURE] [QOL]
## About the PR 

Implements a token dispenser instead of a single solitary token for the syndicate weapons vendor in the vr murderbox

## Why's this needed? 

one token wasn't really enough to fight your friends

### CODE REVIEW

**Comment by alexeric123** [comment]
The one token had 999 credits of each type, but sometimes someone took that token into the murderbox by accident/purpose instead of using it in the vendor.

**Comment by Camryn-Buttes** [comment]
> The one token had 999 credits of each type, but sometimes someone took that token into the murderbox by accident/purpose instead of using it in the vendor.

I saw nothing in the code indicating this and it didn't seem to work this way during testing. It seemed to be equivalent to just one regular token.

**Comment by alexeric123** [comment]
> > The one token had 999 credits of each type, but sometimes someone took that token into the murderbox by accident/purpose instead of using it in the vendor.
> 
> I saw nothing in the code indicating this and it didn't seem to work this way during testing. It seemed to be equivalent to just one regular token.

In the lasts couple days, something seems to have broken, but on the first couple days of the vendor being there, it had 999 credits. I believe it might've been #4331 that broke this.

**Comment by Gannets** [comment]
I promise it worked locally. But yeah it's busted. I'll try and look if I get time.

**Comment by Camryn-Buttes** [comment]
> 
> 
> I promise it worked locally. But yeah it's busted. I'll try and look if I get time.

I mean, this'll solve the whole problem by replacing the single token with a token spawner.

**Review by Tarmunora — APPROVED** [review]

**Review by Sovexe — APPROVED** [review]

**Comment by Gannets** [comment]
> > 
> > 
> > I promise it worked locally. But yeah it's busted. I'll try and look if I get time.
> 
> I mean, this'll solve the whole problem by replacing the single token with a token spawner.

I thought this was a bug report not a pr. I'm very tired.

**Pull request merged**
