### PR TITLE
Adds a horns trait

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[FEATURE]
## About the PR 
Adds a trait to give yourself horns at roundstart. Costs 1 because horns are weird and so should be rareish (despite being entirely cosmetic).
Could cost 0 maybe, and also could be made to only be compatible with certain mutantraces if humans with permanent horns is a little too wacky.

## Why's this needed? 
Myth wanted it: https://forum.ss13.co/showthread.php?tid=17981
The original suggestion included being able to pick the style, but I flat out refuse to try to code that until #6676 or something like it gets merged.

## Changelog

```changelog
(u)LeahTheTech
(*)Added horns as a 1 cost trait.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
okay I'll stop with the PR spam now (probably)

**Comment by Flaborized** [comment]
I don't personally like this idea because I think genetics having unique aesthetic things to offer is cool, and giving one of their coolest things away like this lessens that impact. Unique desirable things that only certain jobs can provide make the jobs more valuable, even by a little, and I think that's a significant advantage over having it be a roundstart thing you pick in a meta menu

**Comment by TobleroneSwordfish** [comment]
Honestly I somewhat agree, in that being able to get interesting cosmetics is a large part of why I'd choose to go get gene scanned. Although that could be telling about how genetics in general could do with feeling more useful to non antags.

**Comment by frawhst** [comment]
After some discussion, we're not looking to make the current horns mutation into a trait. The horns are pretty silly and good for gimmicks or genetics fun, but having people start with them consistently would get old, and would clash with any future head ornaments.
With that said, we're likely to add customizable horns for mutantraces that they'd fit on sometime in the future (no ETA, but- we'll get there)

**Pull request closed without merging**
