### PR TITLE
Moves mining on ship, Sea turtle moves and gets a trader

### PR DESCRIPTION
**Pull request by Eagletanker**
[XXL] [MAPPING]
## About the PR 
Alt to Ikea's PR. Work started on this before they put up theirs, but they got their's done faster. Tries to address the problems I saw with their mining, and touchs cargo a bit as space was taken from it to build up the refinery and mining a bit more. It keeps the sea turtle. 

Edit:

(these should work)

#
Major Differences
Nerd dungoen not in maint (People Like Nice Things and will improve their situation)
Sea turtle still here
Refinery is smaller, although not spread out. Sea Turtle refinery is able to be used, without rock box and mining fabs. 
mining is larger
mining hanger is only able to be access by miners (however this can be changed. Of the possible layouts I put up on discord, the current one was the most voted for) 
New Trader (Hopefully)
Gary gets a friend, Sara
Gary is left on the sea turtle w/ Sara.
Minor differences
LRMT now has a let me out button near it if you get stuck in mining
Notes!
Moved around cargo layout as a result of mining changes 
Trader buys syndie boards for some money. Take em with you, even if you dont want the rep they are still useful!
Some other things I dont remember cause it's 1:40 and I really should sleep.

## Why's this needed? 
Alterinative option to Ikea's PR. the Sea Turtle is cool and is alright. However it's design means less crew interaction when miners come on station and it's locked behind maint access. Trader added to give it some use, as well as it moving forwards to act as a thing to explore around the Manta, which is something the sub really needs.

## Changelog

```changelog
(u) Eagle
(*) Manta Mining has moved back onto the Manta. The Sea Turtle has remained in the surronding seas while they replenish their materials from repairing the Manta. 
```

### CODE REVIEW

**Comment by Eagletanker** [comment]
Manta fails checks is known and I’m trying to think why it fails even though I didn’t touch it. I’m not as fast as ikea, nor have as much control over my life so bear with me. It’s gonna get done though, even if it might take a bit longer than expected.

**Comment by ThatFiveGuys** [comment]
Remember to remove the ore delivery pipe in mining/cargo if it isnt used.

**Comment by Eagletanker** [comment]
Well I fixed one thing, and some how broke the sea diner :shelterfrog:

**Comment by Eagletanker** [comment]
Closed as per emily's request

**Pull request closed without merging**
