### PR TITLE
Kondaru Medbay update

### PR DESCRIPTION
**Pull request by tanker4390**
## About the PR 
Replaces Pathology on Kondaru with a slightly familiar Psychiatrist's Office.

Screenshot_20230118_031223

## Why's this needed? 
Yet another act of killing Pathology.

## Changelog 

```changelog
(u)Tanker
(*)Replaces the Pathology Lab on Kondaru with a Psychiatrist's Office. For the trauma caused by diseases.
```

### CODE REVIEW

**Comment by Kubius** [comment]
Couple thoughts from looking at this:

- Disposal and mail pipe bends on the same tile is kinda cursed - that could easily be one tile south.
- Swap water cooler and the tall cabinet, move air monitor two tiles east.
- There are four small green switches and two fire alarms - some of those have got to be redundant.
- South blinds are stretched over a span of window that bends. May be wiser to make that spot have two 1x1 blinds, and put a wall in between them.
- Could maybe have a west door out to maintenance (right above the desk) for more traversal options.
- Lighting doesn't seem like it was updated from the previous setup. You should probably look it over ingame; I'd light it only with small lights (mainly wall, but using a floor light or two if necessary) if you want the subdued look.

**Comment by Kubius** [comment]
From the look of this, I'd advise two more changes:

Relocation so the water cooler's in a more main-room spot, and the cabinet isn't overlapping with a light fixture. Putting a plant in the newly created gap could also create pleasing symmetry.

image

Swap these east wall mounted things, and add a floor light to **one** of the two circles. If you've checked the lighting ingame and think it looks fine, let me know and you can skip this.

image

**Comment by tanker4390** [comment]
See, the computer provides light, and a small amount of light goes in through the south window (even if the blinds are closed)

**Review by Kubius — APPROVED** [review]
A few closing thoughts, non-essential:
- Box in the surgical suite (presumably head surgeon) is weird. Could take the place of one of the psych office shrubs.
- APC in maintenance to the west could likely be moved up by two tiles so it isn't visually occupying the same tile as the intercom.
- Random cable terminus south of the bio closets.

**Pull request merged**
