### PR TITLE
Remove the hygiene motive from RP

### PR DESCRIPTION
**Pull request by TealSeer**
[RP] [REMOVAL] 
## About the PR 

Comments out the hygiene motive in `make_motives`.

## Why's this needed? 

There's been multiple forum threads re-litigating everyone's reasons but the gist is unlike hunger and thirst that encourage you to have RP encounters (chef/bar/etc.) having to go take a shower alone every 20 minutes doesn't.

## Changelog 

```changelog
(u) TealSeer
(*) The hygiene motive has been disabled.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Above all else, I want to be able to preserve stink lines *somewhere.* This might be out of scope of the PR, though.

**Comment by TealSeer** [comment]
> Above all else, I want to be able to preserve stink lines _somewhere._ This might be out of scope of the PR, though.

The bioeffects themselves aren't touched by this, so they'll still be there if someone wants to implement a way for them to appear (and for admin shenanagins)

**Comment by 444Portal** [comment]
yes please

**Comment by yelloworlemons** [comment]
Personally I'd prefer that the passive decay of the motive was either nerfed or removed instead of the entire thing itself.

**Comment by GabrielMation** [comment]
No! just wash your hands above 50%. it's not that hard. You get used to it.

**Review by AXLFAN2000 — APPROVED** [review]
code lgtm

**Review by 444Portal — APPROVED** [review]
ive already said my thoughts a decent bit, hygiene sucks, lets kill it :)

**Review by Glamurio — APPROVED** [review]

**Comment by TDHooligan** [comment]
deffo better shelved until it's reworked in some gameplay-enhancing regard.

i recently suggested removing passive/splash decay and instead letting you wipe yourself clean with self-help intent at the cost of hygiene. instead letting you hide obvious stains conveniently, at the cost of getting stinkier.

**Pull request merged**
