### PR TITLE
Remove "HoS" from owned lawbringer names

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Removes the "HoS" part from owned lawbringer names (currently "HoS [NAME]'s Lawbringer")

## Why's this needed? 
Not all lawbringer owners are HoSes

### CODE REVIEW

**Comment by Cherman0** [comment]
Should probably just never say "HoS" so it isn't a weird meta-identifying thing that an impersonator can't copy

**Comment by JORJ949** [comment]
> Should probably just never say "HoS" so it isn't a weird meta-identifying thing that an impersonator can't copy

If there IS a HoS with a lawbringer its probably very obvious that its not the HoS as HoSes are both announced and on radio (and the lawbringer is only there if a hos is in the round, so its much harder to impersonate)

**Comment by Tarmunora** [comment]
> Should probably just never say "HoS" so it isn't a weird meta-identifying thing that an impersonator can't copy

Agreed, should be all or nothing.

**Comment by TobleroneSwordfish** [comment]
On balance I'm just going to close this, it's the HoS's gun and seeing "HoS Kevin Bakins" or whatever every time it gets mechscanned is pretty funny.

**Pull request closed without merging**
