### PR TITLE
Creaca's Fruit Milk: New Flavors 

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
Creaca's Fruit Milk Factory TM has finally outsourced production and begun adding new flavors to their milk. 10 new flavors have been added to the pool, including pineapple, strawberry, and surprise mystery flavor. 

Note: am open to changing the surprise of the surprise mystery flavor if it's too much surprise. 

## Why's this needed? 
Was intended originally, but I lacked the coding ability. Now it works as intended. 

## Changelog

```changelog
(u)Roddy
(+)Creaca's Fruit Milk has outsourced production. Local vending machines now contain 10 new flavors of fruit milk; try one today.
```

### CODE REVIEW

**Comment by t-toasted** [comment]
accidentally put this in my master branch, feels bad man

**Comment by wolfolotl** [comment]
recommendation: if it's possible give them all different Colors I like to look at colors for food and beverages

**Comment by t-toasted** [comment]
> recommendation: if it's possible give them all different Colors I like to look at colors for food and beverages
> 
> also: the strawberry flavor will almost instantly turn into the reagent strawberry milk, don't know if that's an intended behavior or not

hmmm, I might save that for a future PR where I actually make the beverage color both represent the drink color and also deplete when its been drunk- since right now it looks pretty but always looks full. As far as the strawberry one, at first it wasn't intended, but then I realized it's cute and fun so I kept it

**Comment by maybeserendipitous** [comment]
Not to get too nerd emoji but is this "lore" consistent? Like, Discount Dan's is the "eat this to definitely not literally die lmao" brand. Is Creaca's the "oopsie woopsie! *puts neurodepressant into your drink*" brand?

**Review by flrsh — APPROVED** [review]
Code looks fine to me!

**Comment by t-toasted** [comment]
> Not to get too nerd emoji but is this "lore" consistent? Like, Discount Dan's is the "eat this to definitely not literally die lmao" brand. Is Creaca's the "oopsie woopsie! _puts neurodepressant into your drink_" brand?

Not sure! I wanted to put one funny thing in the drinks, since everything has a silly thing, but I also wanna see what Cog thinks mhm mhm :nods:

**Pull request merged**
