### PR TITLE
Hard cap reagents per burned herb, Add Syndicate Hotbox Lighter

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
* hard caps the number of reagents per burned herb
* Adds a syndie lighter that cost 1tc for traitor botanist. Will bypass the hardcap, and also gives you 20% bonus reagents in the smoke
* Adds hotbox info overlay for debugging, shows turfs that are allowing traitor hotboxing

## Why's this needed? 
* restricts the ability of high reagent count herbs from creating tremendous smoke clouds with significant reagent counts
* allow for traitor hotboxing

## Changelog

```changelog
(u)Sovexe
(*)There is now a per herb hardcap on the reagents transferred into smoke when burning herbs.
(*)Traitor botanists can now purchase a hotbox lighter for 1 credit. This lighter has unlimited fuel, bypasses the herb hardcap, and gives a bonus multiplier to the reagent volume of the smoke. Sprite by DimWhat.
```

### CODE REVIEW

**Comment by Azrun** [comment]
Take that incredibly reagent packed herb! 🌿

**Comment by zjdtmkhzt** [comment]
Since we already have a changelog entry, maybe consider mentioning the actual value of the cap in that?

**Comment by Camryn-Buttes** [comment]
Harsh but necessary

**Comment by Zonespace27** [comment]
maybe scale how much of the chem per herb is released, dependent on how many are in the pile?

**Comment by Tarmunora** [comment]
tbqh could even go down to 5u for tomato parity

**Comment by Sovexe** [comment]
> tbqh could even go down to 5u for tomato parity

I didn't realize there was an existing precedent, I'm just as fine with 5 as 15. It's very simple to adjust if/when needed

**Comment by vocalpocal** [comment]
How about instead make it scale through endurance, like Balloon Melons do?

I don't agree with this hard-cap approach at all. Not only does this hurt toxboxing, it also deletes tactical venne/contusine healboxing (pretty much the only thing botanits have right now against nukies) and more fun gimmicks like making the station more beautiful with GrassGro. Traitor hotboxing is super nerfed already, so you could just reduce greytide weed boxing easily by making hotboxing more difficult.

**Comment by millicentjwi** [comment]
i'd understand if this was a performance change but it's balance....?

please do consider herbs were recently changed to only light 1 on the pile per ignite attempt, rather than a fixed chance rolled on every herb (due to me almost crashing the server oops)

if this change goes through, this makes hotboxes really, really really really really slow and weak

**Comment by Sovexe** [comment]
The other option being considered was complete removal which this will hopefully avoid

10 plants of 15u still make a rather sizable cloud covering a rather large area. 10 plants would be a 150u chem smoke, much larger than a beaker bomb. 

If it was tied to endurance it would still have a hard cap and a non linear scaling function. This would also require additional code as the herbs themselves do not track the stats of the plants that made them. Though this may compromise people's ability to receive various mutations that have requirements on endurance to qualify

**Comment by PrimeNumb** [comment]
Considering how easy it is to mass produce certain herbs, it might be worth considering a lower cap to start with and see how that plays out.

**Comment by Sovexe** [comment]
Added a syndie lighter that cost 1tc for traitor botanist. Will bypass the hardcap, and also gives you 20% bonus reagents in the smoke

**Comment by vocalpocal** [comment]
Traitor Zippo looks like a great compromise! I like it. Might be a bit too weak at first but could get buffs later on (like it could have a 100% chance to lit herbs on use or something else if needed)

**Comment by Sovexe** [comment]
> Traitor Zippo looks like a great compromise! I like it. Might be a bit too weak at first but could get buffs later on (like it could have a 100% chance to lit herbs on use or something else if needed)

i'd like it to have some cool interaction eventually, haven't thought of any just yet though

**Pull request merged**
