### PR TITLE
Adds unique key sprites

### PR DESCRIPTION
**Pull request by DimWhat**
[sprites] [game objects]
## About the PR 
Adds new sprites for KEYS as well as a generic one for any future keys, defines the radio studio key, moves all key sprites to icons/obj/artifacts/keys.dmi as well as some new descriptions, and a touch of code cleanliness with keys. This should make players able to tell keys apart and allow for more flavorful keys in the future like the ones cogwerks made a while back.
https://cdn.discordapp.com/attachments/972366159938744370/1102156541005680760/SPOILER_image.png
https://cdn.discordapp.com/attachments/890231630097182720/915286720013033502/SPOILER_hot.gif
image

Special thanks to retrino for helping me with the bone key all that time ago.

## Why's this needed? 
Keys don't look too great at the moment and on top of that being able to distinguish which key is which would really help make finding the keys feel more special.

## Changelog 

```changelog
(u)DimWhat
(+)Added some new sprites to some special keys.
```

### CODE REVIEW

**Comment by DimWhat** [comment]
I will note that I am unable to change the key sprites for a specific azone as it is in the secret repository!

**Comment by Exester509** [comment]
Is it me or are these sprites smaller than the iridium and onyx keys? That aside, these look great

**Comment by DimWhat** [comment]
> Is it me or are these sprites smaller than the iridium and onyx keys? That aside, these look great

That's because they are! The onyx and iridium keys are special as the onyx key is a scepter and the iridium key is an extremely alien device. The keys I've made are more similar to actual keys.

**Comment by CheffieGithub** [comment]
Thanks for doing the larry sprite

**Comment by flappybatpal** [comment]
I am told that the sprites are acceptable!
Tested locally with secret.

**Pull request merged**
