### PR TITLE
Remote signalers tgui

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[QOL]
## About the PR 
Makes remote signalers use the generic radio tgui interface:
image
and modifies said interface slightly to fit.

Also re-enables wire cutting on signalers, since that was just broken apparently? Let me know if there's a reason why.

## Why's this needed? 
tgui good, not sure why they weren't already since they're just a subtype of radio
Fixes the signaler portion of #9777

## Changelog

```changelog
(u)LeahTheTech
(+)Remote signalers are now tgui
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
can you adjust the height it looks so weird having all that empty space

**Comment by TobleroneSwordfish** [comment]
> can you adjust the height it looks so weird having all that empty space

That's how all radios are, it's filled by the wires when the panel is open. I suppose you could maybe resize the window when the wires are open, but I'm not sure how to do that.
image

**Comment by blackrep** [comment]
> I suppose you could maybe resize the window when the wires are open, but I'm not sure how to do that.

@TobleroneSwordfish Put a ternary statement in height based on `!!data.modifiable`, which tells you if the wire panel is open or not. For example it'd be something like:
```
<Window width="280" height={!!data.modifiable ? 600 : 200} title={data.name}>
```

**Comment by TobleroneSwordfish** [comment]
Okay having played around with it, dynamically changing the size messes with other radio types a bit too much I think, so unless anyone's really attached the idea I'll leave it how it is for now.

**Review by ZeWaka — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
!merge_upstream

**Pull request merged**
