### PR TITLE
Fixes plating changing spacesuit stats

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Title, also removes Onmaterialchanged interaction with base clothing as I dont wanna hear bug reports about plating reducing melee protection (to clarify the best stats you could get with that interaction was -2 melee prot and .4% fire resistance. This is just confusing considering the things people would plate are higher then that.)

## Why's this needed? 
Bug fix

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Huh, I thought the entire point of the matplater was to improve the stats of items you couldn't normally make.
Do custom space suit stats even justify making them over simply using indy armor with this change? You can also mat-plate fire extinguishers, baseball bats, etc. to improve their force - is that also unintended?

**Comment by ThatFiveGuys** [comment]
> Huh, I thought the entire point of the matplater was to improve the stats of items you couldn't normally make. Do custom space suit stats even justify making them over simply using indy armor with this change? You can also mat-plate fire extinguishers, baseball bats, etc. to improve their force - is that also unintended?

Arc electroplater was added from what i can tell, basically to see what would happen, I can get the opinion of emily but i dont believe it was intended to make matsci spacesuits 3 times as cheap. At least thats what it sounded like from Emily. Space suits can get pretty good damage resistance (8 melee prot) with some work, indy armor only has 2 body prot and 3 head prot, so there is a niche for custom spacesuits still. While im unsure of if emily was aware of plating items or not changing damage, it doesnt lead to much in the way of issues or balance issues. Electroplation of spacesuits allows you to get a 8 melee prot spacesuit with very high thermal resistances for far cheaper then what making it via nanofab would do.

**Comment by Crystalwarrior** [comment]
> > Huh, I thought the entire point of the matplater was to improve the stats of items you couldn't normally make. Do custom space suit stats even justify making them over simply using indy armor with this change? You can also mat-plate fire extinguishers, baseball bats, etc. to improve their force - is that also unintended?
> 
> Arc electroplater was added from what i can tell, basically to see what would happen, I can get the opinion of emily but i dont believe it was intended to make matsci spacesuits 3 times as cheap. At least thats what it sounded like from Emily. Space suits can get pretty good damage resistance (8 melee prot) with some work, indy armor only has 2 body prot and 3 head prot, so there is a niche for custom spacesuits still. While im unsure of if emily was aware of plating items or not changing damage, it doesnt lead to much in the way of issues or balance issues. Electroplation of spacesuits allows you to get a 8 melee prot spacesuit with very high thermal resistances for far cheaper then what making it via nanofab would do.

Yeah this makes sense to me. Though I still suggest to keep electroplater effects, just vastly nerf them so building your own stuff is always better than plating, but it's enough to give you a clue that material actually affects things. Otherwise my immediate assumption as a player new to the system would be "welp it's bugged" which is what I went through having my expectations what plating did being broken in unfun ways.

**Comment by zjdtmkhzt** [comment]
I would classify this more as a balance change than a bugfix, but I think it is a good change.

**Comment by Tarmunora** [comment]
might be worth renaming the custom spacesuit items a little to better indicate that they're different/fabricated

**Comment by ThatFiveGuys** [comment]
> might be worth renaming the custom spacesuit items a little to better indicate that they're different/fabricated

Good idea, let me do that here in a bit

**Comment by Tarmunora** [comment]
wait why did I push that button

**Comment by ThatFiveGuys** [comment]
Lol

**Comment by Tarmunora** [comment]
i'll do the naming thing i guess

**Comment by ThatFiveGuys** [comment]
Thanks!

**Pull request merged**
