### PR TITLE
unresprite

### PR DESCRIPTION
**Pull request by geneva-breaker**
## Changelog

```changelog
(u)The War Crime Bitch
(*)Replaced human mobsprites with something I found in the shed. 
(+)Part one of a few
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
no

**Comment by coolstation** [comment]
FUCK THATS NOT RIGHT

**Comment by coolstation** [comment]
THIS WAS NOT INTENTIONAL

**Comment by coolstation** [comment]
SORRY, FUCKING VSCODE

**Pull request closed without merging**
