### PR TITLE
Multitool data diagnostics

### PR DESCRIPTION
**Pull request by penny64**
[QOL]
## About the PR 

Following up on #4027 this PR deals with issues players have with connecting data terminals and equipment, which will now output errors if a data terminal is unplugged from the powernet (or equipment using it) or if equipment lacks a valid powernet link.
It's an extension of #4012 
(please merge that one first)

image
image

 

## Why's this needed? 

Powernet issues with connecting data terminals and equipment trip up new and seasoned players alike and generate mentorhelps, this provides a much easier and more focused method for players to determine if they've hooked up equipment correctly

## Changelog

```changelog
(u)Penny
(+)Multitools now detect if your equipment or data terminal is unplugged
```

### CODE REVIEW

**Comment by Azrun** [comment]
Logic in `/obj/item/device/multitool/afterattack` should probably be either moved to a global helper so it can be called by `/obj/item/tool/omnitool/` or do something to account for other `ispulsingtool()` items.

**QoL**:
It seems to simplify a lot of things, so if we want to get more of the player base into the wild world of Signals this is great.

**Theme**:
Thematically I think I struggle with the multitool doing so many packet related things.  Maybe NanoTrasen machinery has a standard response when pulsed by a multitool and that gets displayed? Then it might be neat if different types of devices were displayed slightly differently.  Having to disassemble a PC and pulse the interface card seems more thematic, but I guess they could be rolled together.  Then again it has a UI popup for a handful of atmos devices but all it does is change a value and on/off.

**Balance**:
Frequency seems okay… as that data is _mostly_ available on the wiki and is otherwise something you discover once and then never have to deal with again.

Providing NET_ID seems to bypass existing mechanisms that require time to gain that information: physical access for isscrewing() for doors/APCs, pinging (closets), or sniffing (most other things).

- Walking by and smacking a door, locker, device with a tool can be rather innocuous so this mitigates discovery of CRIMES.  Busting out a screw-driver to remove the maintenance panel to get the net_id takes time and increases visibility of the user.

- Pinging can result in a little trial and error. This takes time and can be optimized with player placement when pinging.

- Sniffing can require physical access and time as you may need to interact with the device or wait for someone else to.

**Comment by penny64** [comment]
APCs do not have their netid in the maintenance panel doors are almost the only case of this, in general the information is almost always not available without packets.
Doors still require a code and also of course are pingable, I frequently build devices that access them based on proximity- little in the way of "trial and error" and this is true of other wireless devices e.g. lockers
It's extremely trivial to get that information for anyone skilled enough to craft the packets.

>Sniffing can require physical access and time as you may need to interact with the device or wait for someone else to.

I cannot think of any situation where this is applicable

**Comment by Azrun** [comment]
image
The access panel available from `isscrewingtool()` is what I was referring to for APCs.

**Comment by Azrun** [comment]
Hmmm seems I commented on the wrong issue. Other PR was merged and none of my comments are actually applicable to these changes so ignore me. 👍

**Comment by penny64** [comment]
Merge conflict resolved

**Comment by penny64** [comment]
@ZeWaka Sorry to bug you, this it getting a bit stale

**Pull request merged**
