### PR TITLE
ID Card Resprite

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Resprites all the ID cards in the game, the dabbing license and the emag. Also data cards but I don't think those are used at all and if they are it's by chemists. The new sprites are horizontal. Also also includes a few "bonus" sprites that I didn't implement, for a syndicate ID, pink ID and head of staff IDs. Could be used for whatever purpose in the future. I have supplied a picture of me with my ID cards below. 

## Why's this needed? 

1. Having a horizontal sprite means that in the future, when people want to create new sprites that are ID cards, it'll be easier because it's a much nicer angle to draw in. I've heard at least one person talk about it being difficult to draw new variations on the current orientation, and I've had the issue before too when doodling ID stuff in the past. 

2. I think it looks better! I've come around since the last PR by Erin, and I think their sprites are great looking but I prefer a larger horizontal ID instead of the smaller IDs featured in their PR; I feel that it's important for gameplay reasons that you always be able to see an ID under someone when looting them. I consider this to be a "best of both" solution. Aims to look cleaner and also retain the same sorta look that current IDs have, so you can still identify everything at a glance.

Open to critique and Opinions as always.

## Changelog

```
(u)Flaborized
(*)Resprited ID cards, emags and dabbing licences. 
```

### CODE REVIEW

**Comment by Gannets** [comment]
Horizontal id cards makes sense. There's no other rectangular object in the game that we'd draw diagonally.

**Comment by Flaborized** [comment]
someone asked me for a ref pic of them in the inventory. ask and you shall perceive

**Comment by trerri** [comment]
Your testing spaceman is all kinds of fucked up, good contribution

I would merge this with no changelog and let the community scream about it until they accept that it does indeed look a lot better. Can't wait to see Jeff's reaction.

**Comment by ZeWaka** [comment]
I like these ones.

Bit bikesheddy, but the contrast is a bit strong on them. Especially on the internal shading.

**Comment by Flaborized** [comment]
Bikeshedding aside, I lowered the contrast on the internal shading and on the cards in general (except on the cap ID because I feel the strong contrast makes it look shinier)

**Comment by geneva-breaker** [comment]
these are gorgeous and the shading makes them look THICK like an old-school RFID access pass from the 90s 
Which is more or less how they work
+2 because I get two votes

**Pull request merged**
