### PR TITLE
Makes prodoc heart unaffected by lighting

### PR DESCRIPTION
**Pull request by BatElite**
[qol][balance][input wanted]
## About the PR 
This PR puts the prodoc heart image on the overlay effects plane, which means it's no longer affected by lighting intensity or colour.

There's a few side-effects: the hearts will display over other sprites like shrubs and trees, but they also can't be targeted to attack the associated mob anymore.
(There's no way to make them lighting-independent without showing through in one way or another.)
afbeelding

## Why's this needed? 
People tend to complain that coloured lightning fucks with doctors especially on this point, and I think those two don't need to be in conflict. I think the accessibility/qol benefit is more important than prodocs showing people hiding behind large sprites.

## Changelog

```changelog
(u)BatElite
(+)Prodoc hearts are less affected by coloured lighting.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
this really doesn't need a thread

**Comment by pali6** [comment]
Disagree, this is potentially quite a significant balance change and it absolutely does need a thread.

**Comment by BatElite** [comment]
Following concerns I've applied an alpha thing based on darkness on the heart, so it doesn't clearly show people in the dark while also largely staying its base colour. I put some pros/cons of the whole thing in the thread yesterday or so.
Here's a slightly more elaborate example image of the result though:
afbeelding

**Review by Tarmunora — APPROVED** [review]
lgtm

**Comment by BatElite** [comment]
Fixed changelog for new behaviour, good to go.

**Review by ZeWaka — APPROVED** [review]
lgtm

**Review by flrsh — CHANGES_REQUESTED** [review]
Requesting changes so that someone doesn't accidentally merge this (there are some significant concerns on the forum thread). 

Mbc also mentioned how this would make prodocs even more combat viable than they are now. Potential ways to address this include maybe making them proximity based or maybe having a scanning function?

**Pull request closed without merging**
