### PR TITLE
adds a batch file that creates a blank __secret.dme file

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
This adds a small batch file in the root folder which, when executed, tries to make a small, blank __secret.dme file in the +secret subfolder.

I don't exactly have much experience with this type of stuff, so any improvement suggestions would be very welcome.
## Why's this needed? 
Lots of people seems to have trouble doing this when trying to set up a private server, often due to the windows option to not show file extensions. This could expedite the process of helping them, or make it so they don't need help in the first place.
image

### CODE REVIEW

**Comment by ZeWaka** [comment]
would rather not bloat the root folder, and move to `tools/`

**Comment by zjdtmkhzt** [comment]
I asked pali which of the two to put it and they were leaning towards root, iirc?
Maybe since this should be as easy to access as possible, since it is meant for more inexperienced people?
But yes, I can see reason to have it in the tools folder too. 🤔

**Comment by Zonespace27** [comment]
Maybe have a shortcut in the root folder, and the .bat itself in `tools/`?

**Comment by zjdtmkhzt** [comment]
That wouldn't really lessen the issue of bloating the root folder.

**Comment by Zonespace27** [comment]
I could see the .bat deleting the shortcut once the __secret.dme is created

**Comment by pali6** [comment]
I feel like the name of the file could be more general as I suggested in discord. At some point later we might need to put something else there idk. And a person just downloading the repo for the first time won't know what the hell a secret file is. Go with something like initial_setup.bat or something along those lines.

**Comment by pali6** [comment]
> I could see the .bat deleting the shortcut once the __secret.dme is created

That would make a change which people would accidentally commit.

**Review by pali6 — APPROVED** [review]

**Pull request merged**
