### PR TITLE
Ties Lawbringer to DNA and not Fingerprints

### LINKED ISSUE #8507: Getting cloned as HoS prevents the HoS from changing lawbringer modes
### Labels

[MAJOR]

### Description

Getting cloned as HoS prevents the HoS from changing lawbringer modes, this inlcudes via disk

### Steps to reproduce

1. Die as HoS
2. Get cloned
3. Can't change lawbringer modes

### Expected Behavior

Your gun should change modes 

### Additional Information & Screenshots

Reported by: Mralexs
On server: Goonstation 2 Classic: Bombini
Round log date: 2022-05-08-01-46
Reported on: 2022-05-08 02:27:12

### PR DESCRIPTION
**Pull request by Chatauscours**
[QOL] [BALANCE]

## About the PR 
This small PR makes the lawbringer tied to DNA rather than to fingerprints. 
It will make possible for a cloned HOS to use his lawbringer, as well as for an impostor, whether it is a changeling or a traitor with a DNA scrabler.
Fixes #8507

## Why's this needed? 
For some reason, right now, when you get cloned, your fingerprint ID goes wild. Same goes if you use a DNA scrabler or stable mutagen. As the lawbringer is tied to your fingerprint ID, so you aren't able to use it if the fingerprint ID goes wild.  It would be nice for the lawbringer to make it possible to use the Lawbringer after cloning or after trasmutating into the HOS.

That said, the issue is a lot more complex, and lies into the deep roots of code, but as the code is spaghetti and I am not a great coder, I can only fix the consequence, and not the cause.

## Changelog

```changelog
(u)Chatauscours
(*)The Lawbringer is now linked to the user's DNA and not the fingerprints.
```

### CODE REVIEW

**Comment by frawhst** [comment]
...do you not get cloned with the same fingerprints?
why am I just learning this now?

**Comment by SirSnek** [comment]
wait what?

**Comment by Cthucky** [comment]
Pretty sure you're supposed to get cloned with the same fingerprints.  Maybe it got broken in one of the many cloning updates.

**Comment by Chatauscours** [comment]
You infact, do not get cloned with the same fingerprints.
Here is the forensic analysis of a cloned person:
Analys
And here is their record:
record

As you can see, whilist the DNA matches, the fingerprints do not. As I said, the issue seems to be very complex, and I have no idea how to fix it, as the same bug goes for the stable mutagen, but I suspect that the tocopy proc is broken, and it only copies the Bioholder.Uid, but not the Bioholder.Fingerprints

**Review by ZeWaka — APPROVED** [review]
this brings it more in line with the actual gun

**Comment by Kyle2143** [comment]
This seems like a problem with fingerprints/cloning/Stable Mutagen not the Lawbringer. It's supposed to be fingerprints cause that's the reference, but I suppose this is a fine stopgap until fingerprints are fixed (and if fingerprints get tied to arms...)

**Pull request merged**
