### PR TITLE
Pod shotgun uses ammo

### PR DESCRIPTION
**Pull request by flappybatpal**
[BALANCE]

## About the PR 
The pod shotgun ammo system has unlimited ammo. This adjusts it to 18.
The other projectile weapon, the 40mm, has 14 shots.

## Why's this needed? 
On a syndicate minisub this lets you cruise corridors with a SPES 12 (same projectile) with unlimited ammo.
Pods aren't invincible but it can kill a ton of unarmored and melee weapon equipped crew.
As far as I know the 40mm is armory only but the shotgun is available at the start.

### CODE REVIEW

**Comment by RSG250** [comment]
One issue with this is there is no place to actually buy buckshot, the listening post trader doesnt sell it only aex
and the armor sec tech can some times have none at all. its also not scanable

**Comment by flappybatpal** [comment]
Guess my questions are:

- Is the balance issue exclusive to the minisub? I'm not aware of shotgun pods causing havoc.
- How easily available are the pod weapons? Pod shotgun is power ranked with the precursor weapon, MK4 assault laser and heavy disruptor array. This is the tier below the 40mm.
- Is the main intended use of this weapon pod to pod combat? Would 18 be too low for this?
- Should the availability of buckshot be addressed separately?

**Comment by RSG250** [comment]
Availability of buckshot should probably be addressed separately

 about the other questions yea im not to sure about those ones, and i personally do believe the pod shotgun part current balance issue is exclusive to subs

the pod weapons, the shotgun part, spawn in the nuclear operative hanger for their pods/subs, However on non-nuke rounds it can be bought from the trader at the listening outpost, i am unsure on the price of it however.

**Comment by flappybatpal** [comment]
Possible option is to leave this one alone and replace the one that spawns in the nukie hangar with a variant that uses the weak spez 12 slug, exactly the same as the nukie mechanic gets.

**Comment by ZeWaka** [comment]
Unsure on this, tossing it to the forums.

**Comment by ZeWaka** [comment]
Not so sure on this PR based on forums discussion. I could see a PR like frank's idea in the thread being merged.

Closing tomorrow unless feedback.

**Pull request closed without merging**
