### PR TITLE
Adds the Electric guitar

### PR DESCRIPTION
**Pull request by Mantweerp**
[GAME-OBJECTS] [SOUND]

## About the PR 
Adds a new instrument, The electric guitar.
It can be bought from cargo for 2000 credits, 
comes in multiple different variants and colors, 
and features a range from e2 to c6. 
The sprites/the notes were made by Mcdangus.

Note range:

https://github.com/goonstation/goonstation/assets/112985775/088d39d6-4779-4577-9713-628043c092a7

## Why's this needed? 
This allows for a lot more freedom in terms of music-playing ingame, and also instrument variation good

## Changelog 

```changelog
(u)Mantwerp and Mcdangus
(*)Added the electric guitar, which you can get from cargo. Sprites and sounds by Mcdangus.
```

### CODE REVIEW

**Comment by TDHooligan** [comment]
it's pretty darn good

https://github.com/goonstation/goonstation/assets/6061314/825a82cc-25fb-403d-9ac7-4a6ddcacd12f

**Comment by mcdangus** [comment]
> it's pretty darn good
> 
>  8efadc5c-88dc-47e8-9f2c-c412b2e8c46d.mp4

sweet jesus ice cold christ, you're shredding up that six string like it owes you money

**Comment by Gannets** [comment]
Happy with the sprites on this. 👍

**Comment by frawhst** [comment]
Brief moment of "oh god why does this touch 50 files" horror

**Pull request merged**
