### PR TITLE
changes cuffs in sectechs to buddy cuffs

### PR DESCRIPTION
**Pull request by Tarmunora**
[FEATURE]

## About the PR 
changes handcuffs in sectechs to buddy cuffs (faster to escape, disintegrate when resisted out of)
Adds a few regular cuffs to hacked sectechs to compensate

## Why's this needed? 
Ziptie cuffs gives sec a way to 'lightly' handcuff people, and just gives security another option in how they deal with (lesser) crime
Sec already gets a lot of standard cuffs, and you can hack the sectech vendors to get a few more

## Changelog

```
(u)Tarmunora:
(+)Added plastic cuffs, which take a shorter amount of time to break out of, to security vendors.
```

### CODE REVIEW

**Comment by Carbadox** [comment]
Feel like it would be more appropriate to just add BuddyCuffs to the SecTech in addition to regular cuffs. I'd like to see them as an addition but a complete replacement seems out of place and too much.

**Comment by ryebek** [comment]
Yeah, what Carb said. Its a good idea, but I've had plenty of occasions where I've had to deal with so many shitters, that I've had to raid the sectechs for more cuffs repeatedly, so I'd prefer them being added alongside normal cuffs, maybe having twice as many of them available as regular handcuffs.

**Comment by mybluecorners** [comment]
not sure if this is the case already : do they have a different sprite that looks like zipties?

**Comment by Tarmunora** [comment]
> 
> 
> not sure if this is the case already : do they have a different sprite that looks like zipties?

They do have a unique sprite

**Comment by Tarmunora** [comment]
> 
> 
> Feel like it would be more appropriate to just add BuddyCuffs to the SecTech in addition to regular cuffs. I'd like to see them as an addition but a complete replacement seems out of place and too much.

Each officer starts with 3 cuffs, each locker has 1 more, sec usually has a box with another 7, each sectech would be hackable for 1-4 more... and cuffs are reusable. How many cuffs do you *go* through?
I'll tweak a number.

**Comment by Ley-bunned** [comment]
The problem sometimes isn't so much using a lot of cuffs but getting a lot of cuffs stolen by the people you just uncuffed.

**Comment by Kyle2143** [comment]
I think this is good. It's got me thinking though. Do these ziptie cuffs make it faster to escape while you're buckled to a chair? If so, then I don't like that. But I mostly don't like that because I don't like the change that allowed you to escape from a buckle-cuffed chair silently. It should have the progress bar over making it obvious at the least.

**Comment by ZeWaka** [comment]
Good change.

**Comment by flrsh** [comment]
Not a fan. I'd rather just have buddy cuffs as an additional option in the SecTech, like Carb said. I really don't want to have to hack vendors just to get more regular cuffs.

**Pull request merged**
