### PR TITLE
Adds custom keybinds to the game

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

This adds custom keybinds to the game.
You can open up the modifier window using a verb named `Modify Keybinds` in the Command panel.

This PR does not have:
* Performant key replacement - Rebuilds it every change right now
* Support for non-alphanumeric keys - ex. NUM3, PgDn
* Nice keybind input stuff, being able to press a key and it enters

This PR has:
* Working key rebind for 100% of existing keys
* Saving of keybinds cross-round
* Refactored additive keybind system for easy addition
* Shitty JS:
```javascript
$(".input").on("change keyup paste", function(){var elem=$(this); chui.bycall("changed_key", {action:elem.attr("id"), key:elem.val()})
```

## Why's this needed? 

Obvious?

## Changelog

```
(u)ZeWaka:
(*)Added a basic custom keybinding system to the game. 😸
(*)Change your keybinds by going to the interface menu in the top left.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
If you want to test this branch out with it working, use the commit hash above and not below here.

**Comment by ZeWaka** [comment]
I'll work on the refactor finalization this weekend.

**Comment by ZeWaka** [comment]
That was a lie. Now I'm going to work on it.

**Comment by ZeWaka** [comment]
Refactor all works good now. Saving it might actually work too? Just need to finish up other docket items.

**Comment by ZeWaka** [comment]
Still needs a small amt. of work with resetting, documented in a TODO. But other than that, basically done.

**Comment by pali6** [comment]
I'd say the the button to modify keybindings should either be in the top bar (Game -> Interface) or in the character preferences (or ideally both) instead of being a verb.

When testing locally the Keybinding Customization window is empty;
image

**Comment by pali6** [comment]
Rebinding keys doesn't seem to be persistent across respawns.

**Comment by ZeWaka** [comment]
> 
> 
> Rebinding keys doesn't seem to be persistent across respawns.

This is expected to occur on local, as this uses the Goonhub cloud to save/load custom key json on key rebuild. Other solutions would likely be more complex, but would enable local functionality.

**Comment by pali6** [comment]
Hmm, fair I guess. I hope it won't cause too many performance issues if someone decides to keep modifying their keybindings. 

From my testing it seems to work. Code looks decent. If there are bugs I didn't notice players will surely tell us. I'd merge it.

**Comment by ZeWaka** [comment]
lmao get merged

**Pull request merged**
