### PR TITLE
Additional Dinosaur Pajamas Color Variety

### PR DESCRIPTION
**Pull request by HatNJacket**
[CLOTHING] [SPRITES]
## About the PR 
Adds 8 different dinosaur pajamas to the clothing booth into a new Pajamas category.
## Why's this needed? 

The original dinosaur costume is cute, but seeing differently colored dinosaurs running around is even cuter. Maybe a clown could get the bananasaur costume and go bananas. Variety is good and more dino costumes sounds like a lot of fun.

The yellow dinosaur pajamas have a 25% chance to be renamed "bananasaur pajamas" with a matching description.

This PR is a continuation of https://github.com/goonstation/goonstation/pull/12112. The PR was locked and sat waiting for a clothing booth color swap mechanic that would make this PR obsolete, but that never came around so we closed the original PR and have decided to re-open it now.

Credit to the original dinosaur costume goes to KoboldCommando from PR https://github.com/goonstation/goonstation/pull/5424

Deeno!

## Changelog 

```changelog
(u)KolIsDumb, DeadMan164
(+)Added 8 colors of dinosaur pajamas for purchase at the clothing booth within a new category
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
image

**Comment by ZeWaka** [comment]
#12112 for reference

**Comment by DisturbHerb** [comment]
would it be possible/acceptable to slap a cheeky DNM on this until i finish my rework im so tireb

**Comment by ZeWaka** [comment]
I'm just going to close this for now

**Pull request closed without merging**
