### PR TITLE
Gibber nerf

### PR DESCRIPTION
**Pull request by flappybatpal**
[BALANCE]

## About the PR 
Prevents living humans being loaded into the gibber. Also adds a squelch noise and mutant race blood pool!

## Why's this needed? 
The enzymatic reclaimer needs to be emagged to kill someone, this is located in a public place.
The gibber can kill people after 3 seconds with a flash/baton or other disable and leaves no evidence.

## Changelog

```changelog
(u)Flappybat
(+)Gibber no longer accepts living people for easy kills
```

### CODE REVIEW

**Comment by Carbadox** [comment]
I dont like this cus it already nerfs one of the few pluses of being a traitor chef/bartender and no one reliably uses the gibber anyways.

**Comment by flappybatpal** [comment]
Well my thoughts are that we only have a few rapid kills. The crusher, enzymatic reclaimer and currently the gibber.

The crusher is a well known unique map hazard, people tend to be more alarmed when attacked or taken near disposals
The enzymatic reclaimer has a safety lock that needs to be overridden, takes 5 seconds and is located in a very public place.

The gibber is IMO too stealthy and even upping the time to say 15 seconds won't solve the problem of it being an almost risk free way of killing people with no body. It's not hard to flash or stun someone for long enough if you have a tool.

**Comment by Retrino** [comment]
honestly, making it more apparent that the gibber has been used would be a much better route for this. maybe make it pool blood, have a blood id left on it, etc, from use. adding an action bar could be a good solution, too. 

it seems like an unnecessary nerf when not only the crusher exists, but that it’s easily escaped when not stunned. tldr, just add a visual que or more remnants of the steakified person

**Comment by witheld9** [comment]
This needs a discussion thread

**Comment by Sovexe** [comment]
If this is going to be changed it should at least rip off an arm or do some brute damage.

Similar to how you can't fry living humans but can burn them.

**Comment by Tarmunora** [comment]
Huh. I always assumed the gibber worked like the enzymatic reclaimer already.

**Comment by Kyle2143** [comment]
Closing cause of the pretty strong disagreement from admins and players alike in the discussion forums. 

I think, though, that there is agreement that changing the gibber to being less of an instant kill like maybe removing limbs a being loud. But flat out removing its ability to kill is not the way to go.

**Pull request closed without merging**
