### PR TITLE
Don't hit mechcomp on edit custom signal

### PR DESCRIPTION
**Pull request by monkeymilesmoo**
## About the PR 
Fixes hitting mechcomp with multitool when you edit a custom signal

## Why's this needed? 
Stop being clumsy and smacking your mechcomp!

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Does this affect fingerprints left on stuff?

**Comment by CheffieGithub** [comment]
Please label your PRs

**Comment by monkeymilesmoo** [comment]
It might affect fingerprints, I'm not sure, but if it does, wouldn't the other functions also not leave fingerprints already?

**Comment by TobleroneSwordfish** [comment]
Ah I see, it was backwards.

**Pull request merged**
