### PR TITLE
Cigs

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
Cleans up some cig code, makes massive custom cigs get you really high instead of just lasting forever, and puffing on a cig (unequipping it from the mask slot) does a reagent transfer, allowing you to chain-smoke up to 6 times faster if you diligently puff on your cig (can puff once per process call, cigs do their reagent transfer exactly once every 5 process calls instead of having a 20% chance per process)
PR is a WiP, as @Kyle2143 has mentioned they're working on a cig-related thing of their own, and I'd rather merge this on top of whatever that will be

## Why's this needed? 
Cigs are in a bit of a sorry state, and need some love

## Changelog

```
(u)Tarmunora:
* Cigarettes now have a fixed burn time, with the reagent/cycle adjusted to match
* Pocket cigs no longer transfer reagents if you have on active internals or a gas mask
```

### CODE REVIEW

**Comment by Adharainspace** [comment]
does this remove pocket cigs?

**Comment by Tarmunora** [comment]
Pocket cigs will require you to have a cig (lit or unlit) in your mask slot to function

**Comment by Kyle2143** [comment]
> Pocket cigs will require you to have a cig (lit or unlit) in your mask slot to function

Does this mean that pocket cigarettes won't add reagents into the mob if they are lit and the cigarette in the mask slot is not lit? Or just that they don't transfer reagents at all?

**Comment by pali6** [comment]
Is this supposed to still be a draft?

**Comment by Tarmunora** [comment]
@Kyle2143 Pocket cigs will only transfer reagents if you have a cig equipped in your mask slot - and if a cig doesn't transfer reagents, it will drain them instead, yes.
@pali6 pr is still supposed to be a draft - I thought it would be easier to merge the 'cigarette holder' item into this than vice-versa

**Comment by Kyle2143** [comment]
This has been updated so that you can still smoke pocket cigarettes, but not while you have on active internals or a gas mask. I think it's a suitable and logical change. Adds a bit of logic to the cigarette process proc but I think it's worth it.

**Pull request merged**
