### PR TITLE
reduces construction times, allow building multiple girders at the same time.

### PR DESCRIPTION
**Pull request by mathis650**
[BALANCE] [INPUT WANTED]

## About the PR 

This PR reduces the length of the actionbar to build things like floor tiles, beds, lockers, etc.. It also allows building multiple girders at once, like you could before, also allows reinforcing multiple floors at once. Girders now take 2 seconds to build as opposed to 3. Attaching light fixtures only takes 2 seconds now instead of 4. Also allows building multiple things in parallel.

## Why's this needed? 

Construction is incredibly tedious, and the fact that we can't build multiple girders at once is a big part of that.

## Changelog

```changelog
(u)Matlap
(*)You can build multiple girders at once now!
(+)Reduced action bar lengths for various construction actions.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
not a fan of building multiple girders at once, that was intentionally removed

**Comment by mathis650** [comment]
it is the biggest thing that makes building awful though

**Comment by penny64** [comment]
Can we maybe tag it for discussion? I'm pretty into it just saying

**Comment by Momoberry** [comment]
I do think it should be discussion'd. A lot of people hate building and the only builds you see on classic are using station architecture and just filling in the floor. Like the windows in space on cog1 around escape/security. There's no free space builds cause it takes way too long.

**Pull request closed without merging**
