### PR TITLE
Botany Field Guide

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Adds the botany field guide to botanists' pocket when spawning, which has a basic picture explaining the very very core gameplay loop of the department, the very very basic stuff.

## Scientists have determined that pictures are better than books. 

Talked about this a bit in admin chat; the hydroponics book is overwritten and very Unuseful as a Very Basic Starter. It's overwritten and unnecessarily detailed for what it is. A picture diagram should ideally be a lot more engaging and easy to parse. This obviously doesn't get into mutations, splicing, nutrients, rare seeds ect. ect. but I don't think these guides *should*. The idea is to introduce very very new players to the core gameplay loop of botany. Once they're comfortable with that, they should start experimenting with the equipment in the department themselves or learn more from the wiki/helpful people nearby. I'd like to make more of these for other jobs down the road if this one is positively received/merged. 👁️ 

## Changelog

```
(u)Flaborized:
(+)Botanists now spawn with a field guide in their pocket explaining the very very basic mechanics of the job.
```

[FEAT]

### CODE REVIEW

**Review by flrsh — APPROVED** [review]
This is great.

**Comment by Emcee-Gore** [comment]
Delicious.

Might I request an additional field-guide for the science department? Detailing how one should test dangerous chems on a monkey in the test-chamber?

I love the flavor; yo!

**Comment by ZeWaka** [comment]
Why not have these as posters in the department? Less inventory clutter.

**Comment by Flaborized** [comment]
> Why not have these as posters in the department? Less inventory clutter.

I thought of that but then figured that new players are more likely to use an item in their inventory than to examine a poster out of it. And since I _want_ people to curiously check it out when new I think it's a better fit in pocket. Like the currently existing pocket guides (that I'd like to replace with these if I make one for a job that has one)

**Comment by ZeWaka** [comment]
Idea: Only give these to players with less than 100 rounds or something then maybe? I dunno, we don't really have tracking for rounds played as X job I think

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
