### PR TITLE
Buff vampires cancel stuns 

### PR DESCRIPTION
**Pull request by CheffieGithub**
[BALANCE][PLAYER ACTIONS]
## About the PR 
Halves the damage taken and gives 20 stam instead of 1 when used below 0 to give the vampire a chance to escape.

## Why's this needed? 
Currently cancel stuns just seems like a noob trap since I see new players die to its usage often. mostly its never actually helpful unless you have a speedbuff of some sort since the 1 stam you get and damage makes you slow and unable to run meaning getting stunned again is a given.

## Changelog 

```changelog
(u)Cheffie
(+)Halved the damage from cancel stuns and gives the vampire a bit more stamina back if below 0
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Have to see how it works out in practice. Agree that in most situations it's unusable because 1 stamina is effectively useless.
Mostly OK with halving the damage, 30 for a full stun is a bit of a rough trade.

**Review by flappybatpal — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
Cautious yes? Might need to stick a short cooldown on it, lest a vampire with some nerd healing mix be completely unstunnable.

**Comment by CheffieGithub** [comment]
!merge_upstream

**Comment by CheffieGithub** [comment]
For some reason empty commit message?? cooldown 1 second -> 4 seconds

**Pull request merged**
