### PR TITLE
Adds DNA to zoomed-in Microscope

### PR DESCRIPTION
**Pull request by MarkNais**
[ENHANCEMENT]
## About the PR 
Viewing a pathogen with a zoomed-in microscope will show each symptom's DNA string.

## Why's this needed? 
Makes patho easier for benevolent virologists, and does very little for malevolent virologists, as they'll likely include every symptom anyways.

It's not a very thematic or realistic method, but it's an easy code-change that helps a department that suffers a lot of public vitriol.

### CODE REVIEW

**Comment by Kyle2143** [comment]
This seems good, I don't think it requires a changelog entry though.

**Comment by MarkNais** [comment]
That's why it's minor note, note a major one.

**Comment by Kyle2143** [comment]
Yes, I think it's too small even for the minor tag.

https://github.com/goonstation/goonstation/blob/master/.github/CONTRIBUTOR_GUIDELINES.md

**Comment by MarkNais** [comment]
Yeah, it's fair to say it doesn't change the balance or add a feature.
The main reason I was hoping it'd be "visible" on the changelog is to try to entice more people to try pathology by lowering the barrier a bit more, especially for benevolent pathologists. 
If that's unpersuasive then I can remove the changelog part (or edit it out yourself).

**Comment by MarkNais** [comment]
Then again, the changelog as worded wouldn't make it obvious to the uninitiated that it's easier.

**Comment by Kyle2143** [comment]
It's a good, common sense change, but I don't think that learning of this would have that effect on players unfamiliar with pathology. Unless this change suddenly makes the microscope very useful when before it was completely ignored by all, I don't think that it warrants mention in the changelog. Trying to keep the changelog light.

**Pull request merged**
