### PR TITLE
Moves Cogmap2 mechanics to engineering

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr moves mechanics closer to the core of engineering
image
image
image

## Why's this needed? 
Mechanics and Engineers are the same job now, the maps should treat them that way.

## Changelog 

```changelog
(u)Ikea
(*)On cogmap2, mechanics has been moved closer to the teg. Expect some minor shuffling around of things.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Bleh think my strongdmm is out of date leading to some whacky mapping behavior, Ill fix all of that  stuff later tm

**Review by Tarmunora — CHANGES_REQUESTED** [review]
After some discussion in admin channels, we've decided we'd rather see something more along the lines of a transit chute between cog2 mech/engineering rather than moving the department.

**Comment by TobleroneSwordfish** [comment]
To add some context:
Moving mechanics out of there leaves mining very isolated, which is a shame since cog 2 mining is one of the more busy mining departments right now, being across the hall from one of the main uses of their work. Also the new area is more cramped than the old one, having less floor space for mechcomp machinery.

**Comment by ThatFiveGuys** [comment]
Hmm okay gonna close this pr and make a new one with pipe

**Pull request closed without merging**
