### PR TITLE
Flock relay compute cost 1000 -> 500, resource cost 1000 -> 750

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BALANCE] [GAMEMODES]
## About the PR 
^

## Why's this needed? 
The relay currently is so highly priced that it acts more like a victory lap for a flock that has already annihilated the crew than a serious threat the crew have a chance of defeating. This should hopefully make it more common to see in game and less of a boring extension to an already won round.

## Changelog

```changelog
(u)LeahTheTech
(+)Changed Flock relay compute cost 1000 -> 500, resource cost 1000 -> 750.
```

### CODE REVIEW

**Comment by FlameArrow57** [comment]
Feel 500 is maybe a bit low from the games I've seen

**Comment by TobleroneSwordfish** [comment]
> Feel 500 is maybe a bit low from the games I've seen. Might also affect scope of structures that can be made in the future. Could also use an array structure as a way to get relay sooner, idk

What value would you suggest then? 1000 is definitely too high

**Comment by FlameArrow57** [comment]
Could try 750 probably. Just think relay shouldn't be too low on compute cost otherwise it's much less of a challenge, not being too high with like what you said, damage to the station dealt and the time the shuttle is called

**Comment by amylizzle** [comment]
Honestly I think we should keep it low at 500 - if the flock pops it early and gets stomped, that's a tactical error on their part. If they hold out until it's late in the game, that might be unfun, we should probably figure a way to punish that.

**Comment by cheekybrdy** [comment]
what about making relay broadcast time proportional to the used compute amount? makes sense because you need to send the whole mind which is stored in the currently accessed compute

**Comment by TobleroneSwordfish** [comment]
The issue with scaling the broadcast time to compute is that there's no real way to communicate that to the crew, it already feels bad enough on nukie rounds when no one realises the disk went in and you just explode 3 minutes earlier than you expected.

**Pull request merged**
