### PR TITLE
Makes flipping/rotating disposal pipes easier

### PR DESCRIPTION
**Pull request by TTerc**
[qol]

## About the PR 

This PR changes how flipping/rotating disposal pipes works: 

-clicking the pipe with a crowbar rotates it
-clicking a pipe junction with empty hand simply changes its direction

## Why's this needed? 

Currently using a crowbar on a pipe opens a window that lets you choose between flipping and rotating. When you need to rotate multiple pipes, it gets tedious.

## Changelog

```changelog
(u)TTerc
(+)Removed the flip/rotate window for disposal pipes. Instead, you can click the pipe with a crowbar to rotate it and click the junction with empty hand to change its direction.
```

### CODE REVIEW

**Comment by Adharainspace** [comment]
im not a fan of click drag actions. unintuitive :pensive: id rather have you have to click 2x to flip. bit more tedium but not thaaat much.

**Comment by TTerc** [comment]
>  id rather have you have to click 2x to flip.

That's just my opinion but as someone with a mouse that likes to accidentally doubleclick, I'm not a fan. Clickdrag seems to be the best option to me, a lot of interactions ingame already require you to clickdrag, unlike doubleclicking, which is very uncommon

**Comment by ZeWaka** [comment]
yeah not a fan of clickdrag, it's very nonintuitive for new players

**Comment by TTerc** [comment]
Updated it. Clicking with empty hand changes the junction's direction, clicking with crowbar rotates the pipe


https://user-images.githubusercontent.com/62990808/111155903-5c4b6b80-8595-11eb-870d-b469df4752ff.mp4

**Pull request merged**
