### PR TITLE
Plunger Resprite (icon_state only)

### PR DESCRIPTION
**Pull request by Conchuckter**
## About the PR 
Resprites the plunger icon_state
Plunger

## Why's this needed? 
New sprites are rather scrumptious

### CODE REVIEW

**Comment by muzcl** [comment]
> Due to budget constraints NanoTrasen has chosen to cease supplying the current type of toilet plunger and have instead decided on a cheaper alternative. Any concerns or feedback may be submitted via email to NOREPLY@HELPDESK.NT13.
what happened to NT 1-12?

**Comment by Conchuckter** [comment]
> > Due to budget constraints NanoTrasen has chosen to cease supplying the current type of toilet plunger and have instead decided on a cheaper alternative. Any concerns or feedback may be submitted via email to NOREPLY@HELPDESK.NT13.
> > what happened to NT 1-12?

Syndies got em

**Comment by flappybatpal** [comment]
I don't think we'd changelog this.

**Comment by Conchuckter** [comment]
> I don't think we'd changelog this.

Done

**Review by virvatuli-gh — APPROVED** [review]

**Pull request merged**
