### PR TITLE
Cog1 Armory Hardening

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
- Creates a new area  `securityexternal` meant for use with external turrets. Turrets only shoot people in their area.
- Adds an internal and external turret defense system to the armory.
- Internal turrets can be disabled by anyone with sec access
- External turrets require HoS access
- EDIT: not pictured, sec scanners on the two doors

image
image

## Why's this needed? 
- Armory defense

### CODE REVIEW

**Comment by Carbadox** [comment]
I kind of like my idea of having a NARCs turret inside of the armoury. I think a barking security system has a lot more personality than just regular taser turrets. +1 on the tasers around the out walls though.

**Comment by comradef191** [comment]
While I like this change, It adds a lot of ugly empty wasted space in the Armoury.
Perhaps drawing inspiration from the Armoury on a map like Donut 3 would be a good idea?

**Comment by Sovexe** [comment]
> While I like this change, It adds a lot of ugly empty wasted space in the Armoury.
> Perhaps drawing inspiration from the Armoury on a map like Donut 3 would be a good idea?

Donut 3 has significantly wasted space than this does. I can squish this down some but it means removing a turret and leaving the other in the room so that it's not super cheeseable

**Comment by Sovexe** [comment]
changed to NARCS turret design (dont worry about the dir it faces in the screen)

image

**Pull request merged**
