### PR TITLE
tiny pathology fixes and changes

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
[ENHANCEMENT] [BUG - MINOR] [BALANCE] [QOL]
## About the PR 
This makes some small fixes and changes to pathology that I thought would be good.
Sorry about all the empty line changes due to formatting in some files, I will try not to have those in future PRs.

**Balance**:
- There was (what I believe to be) a typo in co2 farts that caused it to behave a little bit differently from intended, but not much.
- I changed it so arctic chills and dragon fever will not gib you if you have the cold/fire/thermal resist mutations.
- I changed meta-neural haze and pseudonecrosis to count as bad mutations, so the beneficial mutations symptom wouldn't give them, because it makes being a doctor a nightmare when a beneficial mutations pathogen is around.

**QoL**:
- I added some spaces between the segments in the list of known symptom sequences to make it easier to look at.
- I changed the dna analyzer to automatically discard the suppressant segment (which is never part of a symptom and was basically just a noob trap). I also made it sort the segments, so you can find the ones you are looking for more easily.
- I made it so the + and - buttons in the splicing GUI can now be used to select a range of segments and move them all at once. (The code for this was already there, I really just made it so it's actually used.) This feature should really be in the changelog, or else people will not be aware of it.  [Explanatory video](https://streamable.com/npgefv)

**Fixes**:
- I fixed a bug in the dna analyzer where one of the lights would not change color properly.
- I fixed a bug where some elements of the dna analyzer where slightly out of place.
- I changed how the dna analyzer determines which symptoms are beneficial and which are harmful, so it could be more accurate. (Previously autobrewery counted as beneficial and oxygen farts and beneficial mutations couldn't be beneficial, because they are derived from harmful symptoms.)

## Why's this needed? 
- It will make the pathogen UI easier to use and less confusing.
- It will make some things about pathology make more sense to both pathologists and afflicted crewmembers.
- It will make it so beneficial mutations pathogens are not super annoying for doctors.

## Changelog

```
(u)zjdtmkhzt:
(+)Minor pathology GUI improvements. You can now use the + and - buttons to select multiple segments when splicing.
```

### CODE REVIEW

**Comment by flrsh** [comment]
Codewise it looks fine to me! I haven't ever really done any pathology, though, so I would appreciate other people's thoughts (mostly regarding automatically discarding the suppressant segment).

**Comment by zjdtmkhzt** [comment]
I only discard it in the dna analyzer, Basically, there is one segment at the very start of every pathogen's code that does not correspond to any of the 6 t1 symptoms. It was always there in the dna analyzation, but you couldn't ever use it for anything, because any symptom you try to build with it would fail, seeing as those can only be made of the t1 symptom segments.
Basically, it is completely, 100% useless.

**Comment by zjdtmkhzt** [comment]
Just remembered to make ossification a bad mutation as well, seeing as it prevents cloning.

**Comment by MarkNais** [comment]
I think noob traps should give greater feedback that you're making a mistake.  Opening the purge valve on a TEG decreases power, and if it's an active hell burn, possible floods hall ways with plasma from burst pipes.
Falling for the supressing agent is identical to properly trying an invalid dna sequence, AND clutters up the dna-history of what you've tried.
I'd be fine with keeping it in, if falling for the trap gave other, unique feedback to the player. Such as a different "false" light on the console, or a special message on the dna-history window.

**Comment by zjdtmkhzt** [comment]
Counterpoint: Is _Pathology_ really the department that needs more random, useless and confusing features for new players?
The purge valve has a purpose for clearing out the pipes or flooding escape as an antag, unlike the suppression segment. Also, the suppression segment clutters up the UI, which is already a UI that a lot of people complain about as cluttered and confusing.

**Comment by ZeWaka** [comment]
Even though a lot of people are calling to just **DELET** pathology, hopefully this PR will help a tad until something more drastic is done with it.

**Pull request merged**
