### PR TITLE
HoS clothing box has a stinky kilt that makes you Scottish

### PR DESCRIPTION
**Pull request by ryebek**
[FEATURE]
## About the PR 
Title.

## Why's this needed? 
Scottish HoS best HoS, and how can you scot without a kilt?

## Changelog

```
(u)TrustworthyFella:
(+)Added a kilt to the Head of Security's clothing box. It reeks a bit, and its probably possessed by some ancient Scottish ghost, but hey, it looks cool!
```

### CODE REVIEW

**Comment by BatElite** [comment]
Since this deals with bioeffects, there's a bug where having obesity + jumpsuit effects causes infinite recursion along a bunch of procs. (unequipped->RemoveEffect->UpdateMob->update_clothing->u_equip->unequipped is the order that my previous note tells me)

As such, you might want to add the flag to let obese people wear it, or if you're brave you could fix the issue. :P

**Comment by Carbadox** [comment]
I think the accent might give more cons than wearing the kilt for fun might have pros. I think the accent should be entirely the descision of the player

**Comment by Adharainspace** [comment]
id rather have this be a fun recolour/redesign of the hos clothes than one that just adds the accent. alternatively, you could make this some sort of z5 setpiece reward and make it unremovable and permanently add the accent. couple different places to take this

**Comment by Luxizzle** [comment]
Doesn't the HoS already have like 2-3 special sets of clothing it can wear? And a job-locked weapon. I'd rather see some love being done to other heads because i feel like the HoS already gets a lot.

**Pull request closed without merging**
