### PR TITLE
tgui-bench port

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

ports https://github.com/tgstation/tgstation/pull/61081

## Why's this needed? 

performance testing good

not currently working - opens IE and runs server with html but tests don't occur even though js is loaded and fetched

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Looks fine. Bundle update.

**Review by mordent-goonstation — APPROVED** [review]

**Comment by ZeWaka** [comment]
dnm

**Comment by pali6** [comment]
> dnm

still DNM?

**Comment by ZeWaka** [comment]
yes it doesn't work fully iirc

**Comment by ZeWaka** [comment]
Just have to spend time debugging I don't have

**Comment by ruben-svensson** [comment]
Gonna pick this up, I'd like some benchmark for the board game project.

**Comment by MeggalBozale** [comment]
I might also try this but good chance leah beats me to it
Need need this for big UIs like the manufacturer, big lag

**Pull request closed without merging**
