### PR TITLE
Resprites autoinjectors but differently

### PR DESCRIPTION
**Pull request by BatElite**
[feat]
## About the PR 
Fancy sprites for autoinjectors (based on real life ish designs), with ever fancier animations on using them

- [ ] VR flavours
- [ ] Big flavours (+ figure out what to do with animations for them)
- [ ] The state I left the icon updating code in is uhhhh

This is just a brief draft for now I'm gonna leave this for now and bap the morgue PR
image

## Why's this needed? 
TBD

## Changelog

```changelog
(u)BatElite
(+)Auto-injectors have been resprited!
```

### CODE REVIEW

**Comment by frawhst** [comment]
per virva:
>autoinjectors do *not* have a protruding needle in their used state, as that's contrary to their whole design philosophy

**Comment by BatElite** [comment]
I was basing them off of fairly generic things, where sometimes they don't have a guard pop up. But those designs do have cases you're meant to put them in after use so fair enough
image
Pretty chonky used but frankly I feel like docs should clean up after themselves if it causes issues.

**Comment by Cboyjet4** [comment]
IMO, the sprites look great, although they look less like an actual inject in my opinion.

**Comment by Yellow-Mushroom** [comment]
Still very interested in seeing this go through, auto-injectors are still very small and hard to pick up, contribute to visual clutter when they pile up (because they are hard for janitors to pick up so they get ignored), overall just look nice, and are actually readable

**Pull request closed without merging**
