### PR TITLE
Ensure recipient of 'Give Item' is alive and not yourself

### LINKED ISSUE #12973: You can accept items while unconscious
### Labels

[BUG][minor]

### Description

The give command apparently works on unconscious people

### Steps to reproduce

1. Have a friend
2. Put one of the two of you under anaesthetic
3. The awake person tries to give something to the other player

### Expected Behavior

For it to fail before the prompt even shows

### Additional Information & Screenshots

If it wasn't clear from reproduction steps, I found this bug while using an N2O tank

### PR DESCRIPTION
**Pull request by MeggalBozale**
## About the PR 
Removes the ability to give yourself an item or to try and give someone under anesthetic/who is asleep/who is dead an item.

## Why's this needed? 
Fixes #12973

TODO:

- [x] Remove Right-Click option to give yourself an item as well 
Cant give items to yourself but it still shows up cos verb sadly
- [x] Prevent people lying down/stunned from receiving items as well
(Not planned unless requested, unconscious is fine enough)

### CODE REVIEW

**Comment by UrsulaMejor** [comment]
Use isalive() instead of checking stat directly

**Review by ZeWaka — APPROVED** [review]

**Comment by UrsulaMejor** [comment]
Not seeing ` Prevent people lying down/stunned from receiving items as well`? Am I missing something?

**Comment by MeggalBozale** [comment]
Oh right yeah uhhhh I would have to check for if someone is horizontal

Is there a nice way to do that? Islying or something? Would that count for being stunned?

Currently checking isalive(M) means people under anesthetic won't work, but if you're just lying down you probably can

**Comment by UrsulaMejor** [comment]
isincapacitated(X)

**Comment by UrsulaMejor** [comment]
I think letting lying down (not stunned) people accept items would be fine. It's funny to imagine someone taking a thing and then just dropping it lazily

**Comment by MeggalBozale** [comment]
In that case no changes would be needed as such is the current behavior

**Comment by ZeWaka** [comment]
> In that case no changes would be needed as such is the current behavior

i don't see that being called tho?

**Comment by MeggalBozale** [comment]
> > In that case no changes would be needed as such is the current behavior
> 
> i don't see that being called tho?

Apologies for the vagueness, I meant it in reply to the previous comment that being able to hand items to the incapacitated is the current behavior.

**Pull request merged**
