### PR TITLE
adjust filgrastim recipe

### PR DESCRIPTION
**Pull request by TDHooligan**
[C-QOL][A-Chemistry][A-Medical]

## About the PR 

https://forum.ss13.co/showthread.php?tid=21112 
Suggests changing this, and it makes sense as pathology is kill.  Probably better than having to add more accessible e-coli.

I figure beff's a pretty good substitute for 'some effort required', There's probably some third-party/pharmaceutical strains of bacteria in whatever cheap meats 'beff' is implied to be made from. Beff's recipe is also made easier with hemolymph, another type of blood. Win-win? 

Ultimately not fussed on if this specific patch is merged or another route is picked, but figured the forum thread had merit, so it's worth raising.

## Why's this needed? 

pathology is dead.

### CODE REVIEW

**Review by Tarmunora — APPROVED** [review]

**Comment by nefarious6th** [comment]
consider this the poor man's wiki tag

minor changelog needed for both recipes?

**Comment by colossusqw** [comment]
I'm not sure if this is quite the best chem to replace E. Coli, considering how heparin never saw the light of day having meat slurry as a precursor, and beff seems even harder to acquire. Sure, heparin doesn't quite have as many straight up uses as filgrastim, but even then, i'm not sure you're gonna see filgrastim around 99% of the time.

**Comment by TobleroneSwordfish** [comment]
Beff is a pretty rough pre-requisite for a niche medical chem, ideally it'd be nice to make e. coli accessible in some other way, but I don't know enough (any) microbiology to figure out what would be a sane way of getting it

**Comment by TDHooligan** [comment]
added to wiki.

**Pull request merged**
