### PR TITLE
PDA: Ability Button to Open Interface

### PR DESCRIPTION
**Pull request by MarkNais**
[QoL]
## About the PR 
Adds an ability button for the PDA to open it's interface.
Spiritual successor to #1459 
image

## Why's this needed? 
Quality of Life

## Changelog

```
(u)MarkNstein:
(*)Added an ability button for opening the PDA interface.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
This seems like something that is quite in line with all the other things getting buttons, like flashlights, lab coats, etc...
It would probably also be very good for newbies that may not be aware of the existing functionality of dragging your PDA onto yourself!

**Comment by Carbadox** [comment]
Only issue I have isn't really with PR it's self, it just thats this and the flashlight sprites are the exact same. Perhaps the flashlight one could be updated to have the small light on it to have a minor differentiation

**Comment by MarkNais** [comment]
I had the same thought. Like currently, if you turn the flashlight module on, the PDA itself has a small glow around it's corner. That being adapted to a sprite would be effective IMO

But I am not good with the pixels...

**Comment by mybluecorners** [comment]
Maybe there could be 1 singular 'PDA' ability icon that either : has 2 clickable regions that it reads using mouse params, or 2 popout multicontext buttons?

**Comment by UrsulaMejor** [comment]
https://cdn.discordapp.com/attachments/585526776550391819/735367868258058290/new_pda_buttons.dmi

**Comment by MarkNais** [comment]
Yeah I've got more work I can put into this

**Comment by MarkNais** [comment]
I'll get back to this if someone else doesn't. Life's been busy.

**Pull request closed without merging**
