### PR TITLE
Allow playing slot machines with MechComp

### PR DESCRIPTION
**Pull request by glassofmilk**
[FEATURE]
## About the PR 
It's been a TODO for a while. Now you can use MechComp to activate the slot machines!

## Why's this needed? 
Makes gambling slightly less tedious.

## Changelog

```
(u)glassofmilk:
(+)Implemented playing the slot machines using MechComp. Good luck!
```

### CODE REVIEW

**Comment by Emcee-Gore** [comment]
Do you manually need to insert your ID first for it to work...or is it that the slot machines in and of themselves become a sort of randomizer?

Only giving an output when they win a role?
But losing their ability to cash out when connected to MechComp?

I do not necessarily know what you mean by your change - or what the proposed implications are...except that you can somehow roll the slot machine...somehow?

**Comment by pali6** [comment]
Sadly slot machines being tedious is pretty much the only thing that keeps them "balanced". I don't like this PR, especially not with the current slot machine probabilities.

**Comment by glassofmilk** [comment]
@Emcee-Gore You have to insert your ID and leave it in the machine, so all mechcomp is really automating is pressing the play button over and over again.

@pali6 Ok, I saw the unfinished code in there and thought it seemed like a low-hanging fruit. I'll leave the PR up for a bit, but if nobody actually wants this implemented, then I'll revise it to just pull out the mechcomp stubbing completely.

**Comment by Emcee-Gore** [comment]
What would be cool though...if you could receive an output from a slot machine - IF YOU WIN - that be a fun trigger for MechComp works.

Like you could attach it to a signaler and rig a slot machine. Once people win; boom! Beaker bombs go off!

**Comment by mordent-goonstation** [comment]
Yeah; as mechanics can make slot machines, I wouldn't want them just sticking in a handful with IDs given by the HoP to generate free money forever.

> What would be cool though...if you could receive an output from a slot machine - IF YOU WIN - that be a fun trigger for MechComp works.
> 
> Like you could attach it to a signaler and rig a slot machine. Once people win; boom! Beaker bombs go off!

 I *do* like this idea!

**Comment by ZeWaka** [comment]
right now it does a signal on it being used, but could have another for winning with the level of winning

**Comment by ZeWaka** [comment]
Closing this PR due to the concerns raised, and mechcomp being triggered on winning can go in a different PR.

**Pull request closed without merging**
