### PR TITLE
Wine Description Change

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
Changes the wine description from,
desc = "Not to be confused with pubbie tears."
to
desc = "No, not that kind of whine."

## Why's this needed? 
Deprecated term no longer in use on the server.
 
[c-sprites] [size/xs]

### CODE REVIEW

**Comment by t-toasted** [comment]
sobbing at my tags not working

**Comment by ThatFiveGuys** [comment]
I think this makes the pun too on the nose, maybe have it be "Not to be confused with high pitched crying" or something like that?

**Comment by t-toasted** [comment]
> I think this makes the pun too on the nose, maybe have it be "Not to be confused with high pitched crying" or something like that?

works for meeeee

**Review by ZeWaka — APPROVED** [review]
muh soul

**Pull request merged**
