### PR TITLE
Visually differentiates medbay's lockers

### PR DESCRIPTION
**Pull request by BatElite**
[input wanted] [qol] [feat]
## About the PR 
This PR adds several new sprites for various medical lockers, so that they look different. The regular locker and blue clothes locker have been poked a little bit along with the new sprites so they fit together nicely.

medlockers
In order: medicine, anaesthetic, medkit, restricted medicine, medical uniform/clothing, patient's stuff*

afbeelding
Here's what Cog1's medbay looks like with these sprites, since that map has them close enough together to fit on one screenshot.

*The blue patient lockers aren't used yet, and I think I might have to make a new locker in code and/or alter all the maps to put those in. I don't really have time or will to do that today, so that's for a follow-up PR. The locker on Manta with the nurse stuff in now also uses the red variant.

## Why's this needed? 
Having to memorize the locations + functions of the lockers for each map is a bit of a pain in the ass.

## Changelog

```
(u)BatElite:
(+)Medbay's lockers now look mostly different from one another!
```
## Input wanted

I didn't show these sprites to anyone so IDK if people think they're any good at communicating their contents. These have been sitting in my sprite thing for months now, and I figured I might as well PR them while I have a moment. My prediction is that the restricted locker is going to have the most opinions attached, but I personally like the stark contrast.
If changes need making that'll happen after the weekend.

### CODE REVIEW

**Comment by Carbadox** [comment]
Love it

**Comment by Gerhazo** [comment]
I like the concept of this change.

Not sure about the sprites, not in an "I think these are bad" way but in an "are they good enough and convey the information properly" way, a concern you have yourself expressed, which I assume spriters looking through this will voice their opinion of.

**Comment by Gannets** [comment]
Any visual distinction is better than none. Maybe in future these lockers could be entirely different sizes and designs, but for now a changed logo will do.

**Comment by BatElite** [comment]
It'd still be good if the logos are good though. I'd like to establish some kind of visual language instead of being a stepping stone.

**Comment by ZeWaka** [comment]
maybe change medkit to just be a square?

**Pull request merged**
