### PR TITLE
Adds disorient resist to several outersuits and cleans kendo code a bit.

### PR DESCRIPTION
**Pull request by DimWhat**
[Balance] [Cleanliness]
## About the PR
Adds a disorient resist, also known as taser + baton resistance, to several outersuits. This would weaken the strength of the stun baton's monopoly in fighting just a small amount and increase the amount of preparation people can make when fighting against a person with stun weapons. Also cleans up kendo code to use tabs instead of spaces.
**CURRENT LIST**
- Dou and Tare = 10%
- Firesuit = 15%
- Heavy Fire = 25%
- Makeshift armour = 20%
- Radsuit = 15%
- SUV suit = 35%
- SECRET = 30%

## Why's this needed?
Currently disorient resistant gear is solely from security and magboots. I believe that disorient resistant gear the crew can get their hands on should be a little more expanded upon so that fighting against security as a bad guy or a revolutionary would be a bit more than "get meth."

## Changelog
```changelog
(u)DimWhat
(+)Added disorient resistance to several suits.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
why is there a secret label on this PR

**Comment by DimWhat** [comment]
> why is there a secret label on this PR

Because the armour is secret content right?

**Comment by ZeWaka** [comment]
> > why is there a secret label on this PR
> 
> Because the armour is secret content right?

that's not what the label means

**Comment by DimWhat** [comment]
> that's not what the label means
woops, my bad.

**Comment by Tarmunora** [comment]
imo, most of those number could/should be rounded to the nearest 5%. Just reads cleaner that way

**Comment by ZeWaka** [comment]
> imo, most of those resist numbers could/should be rounded to the nearest 5%. Just reads cleaner that way

dis

**Comment by DimWhat** [comment]
> imo, most of those resist numbers could/should be rounded to the nearest 5%. Just reads cleaner that way

Donezo

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
