### PR TITLE
Removes uncool quip by father jack

### PR DESCRIPTION
**Pull request by MRLinew**
## About the PR 
Just removes one thing that father jack says, "GIRLS".

## Why's this needed? 
Any time I see father jack randomly shout "GIRLS", I don't think its funny, instead I'm left wondering why this is in the game.

### CODE REVIEW

**Comment by Eagletanker** [comment]
Girls

**Comment by DisturbHerb** [comment]
Girls?

**Comment by MRLinew** [comment]
I should probably add, the chaplain randomly shouting "GIRLS" plays into the classic chaplain pedophile stereotype that I feel has no place here.

**Comment by coolbugcoder** [comment]
I mean, without context, someone just randomly shouting "GIRLS" seems funny af, I don't see how it plays into the chaplain pedo stereotype. But to be fair, I haven't seen Father Jack myself so maybe it comes off as way more creepy with context.

**Comment by Yellow-Mushroom** [comment]
It does come off as very strange and like, a bit objectifying. Less pedophilic and more like the creep stereotype tho.

**Comment by Conchuckter** [comment]
father jack has no girls

**Comment by MRLinew** [comment]
yea im really bad with words I think yellow puts it better then I can

**Comment by Xkeeper0** [comment]
https://en.wikipedia.org/wiki/Frank_Kelly#Father_Ted

**Comment by ThatFiveGuys** [comment]
Considering the vast majority of players wont get the reference i think its good to look at this seperate from what its referencing.

**Pull request closed without merging**
