### PR TITLE
Expands Clarion's botany and ranch

### PR DESCRIPTION
**Pull request by Chatauscours**
[MAPPING] [QOL]

## About the PR 
Expands the Clarion botany and ranch.
Before: 
Снимок экрана (11)

After:
Снимок экрана (12)

## Why's this needed? 
They are currently extremly small and impractical.

## Changelog

```changelog
(u)Chatauscours
(+)Clarion's botany and ranch area has been expanded.
```

### CODE REVIEW

**Review by Sord213 — CHANGES_REQUESTED** [review]
Needs a locker for rancher gear. You can probably expand into maint a little and remove the bottom portion of the airlock if needed. You also seem to have removed the general manufacturer in the hangar.

**Comment by nefarious6th** [comment]
Looks good; dont forget to add two scrubbers and an air pump in maint elsewhere to make up for the two removed for the ranch

**Comment by Chatauscours** [comment]
> Looks good; dont forget to add two scrubbers and an air pump in maint elsewhere to make up for the two removed for the ranch

Thanks! The two scrubbers and air pump are there, barely seen (3 pixels) on the screen shot in the bottom right, (accidentally cropped them out), but they are there :) !


> Needs a locker for rancher gear. You can probably expand into maint a little and remove the bottom portion of the airlock if needed. You also seem to have removed the general manufacturer in the hangar.
Locker added. 

About the general manufacturer, I did remove it, but added the ship parts manufacturer that was (for some reason) missing in the hangar. The nearest general manufactured is located 10 tiles above in the tool storage. Here's how the top part of the podbay looks now. 
Снимок экрана (15)

**Review by Sord213 — CHANGES_REQUESTED** [review]
Got a couple other things I missed on first review.
Screenshot_623
The two APCs in maint need their dirs set correctly and the top one should not be behind the extinguisher wall container.
West = 8
East = 4 (although imo you probably want to move the "Pod Bay" APC on to the wall to the north and leave the dir at "1".
Third circle the camera could probably do being moved up one tile so it's not right on top of the disposal unit. 
Ranch also does not have a light switch.
Screenshot_624
Light switch here is a little closely placed to the disposal unit. You could either remove the offset on the disposal unit or just move the light switch.

**Pull request closed without merging**
