### PR TITLE
tidied up the cog2 TEG cables

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [MINOR]
## About the PR 
Tidies up the TEG room cabling to be a bit tidier and not in the way of potential engineers.
Old:
image
(caption: what the junt is even happening here)

New:
image
(nice, clean and tidy)

## Why's this needed? 
the messy cables jumpscared me when i had a peek. They connected to seemingly nothing in various places and are probably plain confusing. Plus one bloke on discord said 'Please nuke the wire art it makes the wiring such a pain' and i thought 'okay i should do that then'.

## Changelog 

```changelog
(u)Tyrant
(+)Unspaghetti'd the Cog2 TEG room cables.
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
A story in 4 parts
image
image
image
and then i cried
image
image


in conclusion, this may be controversial

**Comment by Laboredih123** [comment]
wire art is nice

**Comment by TheTyrant25** [comment]
well, that's why it's controversial, innit

**Comment by TobleroneSwordfish** [comment]
Okay this is `soul` removal, but it would make changing the type of all high power cables less cursed.

**Comment by TheTyrant25** [comment]
> Okay this is `soul` removal, but it would make changing the type of all high power cables less cursed.

Not sure what you mean by high power cable. Are you perhaps referencing to #11981 and its wattage thingys? There's only really one kind of cable used here, the default red one.

**Comment by TobleroneSwordfish** [comment]
engine-power vs grid-power cables (currently they look exactly the same apart from on cog 1)

**Comment by TheTyrant25** [comment]
Oh, wow. Never noticed that the direct TEG cables are brown on cog1. Maybe that's recent? who knows.
Should I make them brown here?

**Comment by TheTyrant25** [comment]
thats scope creep nvm
when this pr gets closed (or merged) i'll make a brown TEG cables pr

**Comment by TheTyrant25** [comment]
if everyone hates this i may just close the pr ngl

**Comment by frawhst** [comment]
cogs approved

**Pull request merged**
