### PR TITLE
Renames the AK-477 to the JK-47

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Renames the AK-477 to the JK-47

## Why's this needed? 
I am funny

### CODE REVIEW

**Review by flrsh — APPROVED** [review]
Lol.

**Comment by DimWhat** [comment]
Boooooo! Stolen jokes!

**Comment by Gannets** [comment]
i don't get it

**Comment by Kyle2143** [comment]
Reference to this guy maybe? https://en.wikipedia.org/wiki/JK-47

**Comment by Carbadox** [comment]
The AK-477 is the replica gun. JK stands for Just Kidding

**Comment by Carbadox** [comment]
Lmao

**Pull request merged**
