### PR TITLE
cleans up some misc bugs on gimmick and out-of-rotation maps

### PR DESCRIPTION
**Pull request by nefarious6th**
[bug]

## About the PR 
cleans up some bugs and errant pipes and whatnot on the gimmick / out of rotation maps
replaces the missing mining shuttle computers on them

## Why's this needed? 
keeps them functioning for gimmick rounds and whatnot

### CODE REVIEW

**Comment by nefarious6th** [comment]
ALSO! Lmk if I can just cut any of these from the repo so we dont have to maintain them anymore. I was thinking of removing destiny since I dont think anyone's used it for anything since it went out of rotation and there's maps that fill the ship and midpop niches better, but I wasnt sure if someone was using it for crash gamemode or anything like that

**Comment by frawhst** [comment]
Will check with other devs on which maps we're cool with axing completely. General sentiment is "kill the entire unused folder" but I'll give it a couple days to be safe.

**Review by frawhst — APPROVED** [review]
other than merg conflicts this is good yeah

**Comment by nefarious6th** [comment]
Oh Shoot This Thing Closed. will re-pr something like this later maybe

**Pull request closed without merging**
