### PR TITLE
Mapload Go Faster

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

autowalls r slow
u might have been complaining about mining z-level generation speed - this solves lots of the lag
also more for general roundstart because this affects basically every wall we use lmao

```
  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█■GREETZ■█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  
 █                                                                             █ 
 █     Special thanks goes to Remmie from /tg/ for their typecacheof() code    █ 
 █          Additional thanks goes to Kapu for telling me about this           █ 
 █                                                                             █ 
  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  
```
## Why's this needed? 

fast
image
image

## Changelog
```changelog
(u)ZeWaka
(+)Made some large internal changes to how our walls smooth out and look pretty. Be sure to report any bugs!
```

### CODE REVIEW

**Comment by Kapu1178** [comment]
yw

**Comment by Tarmunora** [comment]
@ZeWaka reminder to merge this if it's ready

**Comment by ZeWaka** [comment]
Not

**Comment by Tarmunora** [comment]
😱

**Pull request merged**
