### PR TITLE
Removes the taser the HoS gets on roundstart

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
[BALANCE] [WIKI]

## About the PR 
removes the taser the HoS gets when they spawn.
## Why's this needed? 
The taser is unneeded if they want to, they can get one by using a token from the armory, they already spawn with a token too and because taking down an HoS is already hard enough without their extra taser.

## Changelog

```changelog
(u)Arthur Holiday
(+)The Head of Security does not get a taser at roundstart anymore.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
Curious what the plan is for a hos that joins up partway through the round and cant make it to their locker/it's revs or something so people are immediately flocking to them.
I imagine this being important on nukies or revs or blob or something where access from arrivals to Sec may be disrupted or cut off if the bar is a primary area of activity, eg. the plant site.

**Comment by MatheusIsNotAvailable** [comment]
HoS can't latejoin on revs and what is the taser gonna do against a blob? On the nukies thing yeah, some plant sites are way too close to arrivals, but on cog1 there is a sec booth near arrivals and if you ask me the bar plant site should just be removed. Being attacked by antagonists that rush you not very late after foi Spawn is a problem that always existed and exists for every other sec officer

**Comment by MatheusIsNotAvailable** [comment]
Accidentally pressed close with comment, oops

**Comment by Crackaduck** [comment]
instead of removing it, give it to a local head or deputy :)

**Comment by DimWhat** [comment]
If you remove the taser, give them a flash instead. All heads start with one in their inventory.

**Comment by Tarmunora** [comment]
Don't they get a flash in the sec pouch anyways? 🤷

**Pull request merged**
