### PR TITLE
Resprites Cyborg HUD Elements

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Resprites the cyborg HUD elements, including: "Hand" slots, the 'store item' button, the battery indicator, the module button with all existing modules I'm 99% sure, the weird and useless 'radio' button, the intent button, the unused target dummy button that I didn't know was unused until I tested in-game, the 'stop pulling' button, the 'show upgrades' button, the upgrade backgrounds, and the health, oxy and temp indicators. Doesn't touch anything I thought was unused or the background UI for the storage items (or the actually used target dummy sprites, since those are ripped from newHUD apparently)

Some of them have added animation as well. The intent button has a little animation when swapping, the battery blinks when low on charge, the health and temp and oxy blink a little bit when relevant. Mostly small detail things to try and give parity to the human UI. I tried not to make any of them too intrusive.

Pictures:

## Why's this needed? 

Current UI is a bit rough IMO, I like the idea of HUD icons that 'look like things' and also wanted to try and add visual clarity to some effects. Should hopefully make some things clearer (ie: the fact that you need to click the module button to set your module, the 'full health' icon having a non-color exclusive indicator in the form of a checkmark, big red X behind the O2 indicator when there's no O2) while also looking neat. I also really enjoy the idea of having a UI that looks like it's built together, and I think it fits cyborgs. Also also there's some fancy colors on the health and battery sprites that hopefully make them look cooler

## Changelog

```changelog
(u)Flaborized
(*)Resprited the cyborg HUD elements.
```

### CODE REVIEW

**Comment by Hypertripp** [comment]
Doing the Omnisia's work!

**Comment by Enderthunder** [comment]
9/10 and i dont know where the last one goes!

**Comment by flappybatpal** [comment]
I feel like some of the scan line ones are hard to read in the preview, particularly dark blue or red against black.
However, they may be fine in game.

**Review by Gannets — APPROVED** [review]

**Comment by rmeaper** [comment]
I love the new look of all the UI elements, but IMO I think that the 3/4 perspective doesn't really fit UI. I feel that it makes the UI blend in with the in game objects, rather than look like it's an overlay.

**Comment by ZeWaka** [comment]
notes:
i like the beaker colors on the original chemistry module a bit more, more muted and would align with the other modules

rest looks great

**Pull request merged**
