### PR TITLE
Makes CE start with aurora belt, removes it from locker

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Makes CE start with aurora belt, removes it from locker

## Why's this needed? 
I think it'd be good to start moving jobs with unique gear to being tied to their station presence rather than their lockers, EG Janitor galoshes.

### CODE REVIEW

**Comment by virvatuli-gh** [comment]
Would suck if you got this as a steal objective just to find out that there's no CE that shift.

**Comment by MatheusIsNotAvailable** [comment]
Same happens with the HoS beret, no? I think it is more of a problem with spy objectives than with the actual change, stuff shouldn't be appearing as an objective if there isn't any of it on station

**Comment by Azrun** [comment]
But the prefab!

**Comment by virvatuli-gh** [comment]
> Same happens with the HoS beret, no? I think it is more of a problem with spy objectives than with the actual change, stuff shouldn't be appearing as an objective if there isn't any of it on station

Not a spy objective, an actual traitor objective. And yes the HoS beret objective is silly too, just because something exists in the code currently doesn't mean it's good.

**Comment by MatheusIsNotAvailable** [comment]
I gave it some thought and I think the CE locker without the belt would have very bad loot compared to other head's lockers, breaking into a head's locker should be rewarding.

**Comment by Eagletanker** [comment]
Good PR,  and the CE locker has some good stuff in it, though probably could use a bit more than just "Everything engineering + Aurora" anyways

**Comment by ZeWaka** [comment]
not a fan for above reasons

**Comment by Carbadox** [comment]
> Would suck if you got this as a steal objective just to find out that there's no CE that shift.

Counter point : Bounties and steal objectives should ideally check  whether or not something is present in the current round, rather than just having a list of possible objectives.

**Comment by Azrun** [comment]
The objective would then be limited to there being round-start CE or **later** start antagonists.

What is the goal of the transition to job-spawn gear, what makes it good? Reduce coupling of equipment to mapping activities? Stopping people from stealing the gear from late-joiners?

**Comment by Carbadox** [comment]
> 
> 
> What is the goal of the transition to job-spawn gear, what makes it good? Reduce coupling of equipment to mapping activities? Stopping people from stealing the gear from late-joiners?

Not really an isssue with mapping. The main incentive is guaranteeing jobs their unique equipment. Janitors would often be galosh-less from people rushing their lockers and the same has happened with CE's and the aroura belt, usually Captains or HoPs.
Also, mechanics and engineers already start with their belts equipped, I think it'd be better to be consistent with that

**Comment by ZeWaka** [comment]
> The main incentive is guaranteeing jobs their unique equipment. Janitors would often be galosh-less from people rushing their lockers and the same has happened with CE's and the aroura belt...

I see no problem with this. Leads to more interesting stories and gameplay.

**Comment by Eagletanker** [comment]
The Aurora belt is integral to being a CE due to it’s ability to hold the RCD and it’s shield helps in fire fighting. It also separates them from engineering. That getting stolen before they are on station means they lose yellow tools and their only indicator that defines them.

**Comment by Tarmunora** [comment]
> 
> 
> I gave it some thought and I think the CE locker without the belt would have very bad loot compared to other head's lockers, breaking into a head's locker should be rewarding.

Could move the RCD-Custom to CE locker instead of a plain crate nearby

> 
> 
> But the prefab!

Prefab would need *something* added, yeah

**Comment by Eagletanker** [comment]
idea for the problem of the prefab
Add a different aroura belt in, along with a engineering space suit and stuff that's actually from SS12. Takes away the easy "Haha I can get powerful stuff" from that prefab and makes it have something unique to the lore too.

**Comment by ThatFiveGuys** [comment]
> The Aurora belt is integral to being a CE due to it’s ability to hold the RCD and it’s shield helps in fire fighting. It also separates them from engineering. That getting stolen before they are on station means they lose yellow tools and their only indicator that defines them.

Going to have to disagree, while the aurora is nice to have as a ce its far from required. While the aurora may be the most unique thing gear wise, just because they dont have it doesnt change the fact theyre still the chief engineer. 

Personally as someone who has player ce a fair bit of times, ive only had it taken twice, both of which ive gotten the belt back. Ive never had aurora being stolen be a consistent serious issue.

**Comment by flappybatpal** [comment]
> Same happens with the HoS beret, no? I think it is more of a problem with spy objectives than with the actual change, stuff shouldn't be appearing as an objective if there isn't any of it on station

BTW the issue here is that the items can't be found until the lockers have been opened due to spawn_contents. They don't get created until the locker opens so there are no items to find.

**Pull request closed without merging**
