### PR TITLE
Removes striping from loot crates.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This title removes striping from loot crates, and alongside it description + name changes that come with different tiers. This pr also fucks with the locks and traps crates have a little bit. These changes are all designed to make loot crate tiers practically unidentifable. Oh also this minorly resprites science, crime, and industrial loot crates too I guess to make the sprite work without the tier sprite.
image

## Why's this needed? 
This should slow down the rushability of loot crates greatly. This makes the timesink for crates not getting the crates (which is not hard to do fast), but opening them. Currently, you can get 16 crates in around 5 minutes, if you know which crate tiers are the good ones, this can allow you to collect insanely powerful items very conveniently with basically no cost of time. These changes should highly reduce powergamability of crates. (Oh yeah why tf did t1 have crusher trap available as one of them? Thats just rude and doesnt fit. I swapped that to t3 cause it makes more sense for that).

## Changelog

```changelog
(u)Ikea
(*)Loot crates no longer have stripes indicating their tier.
```

### CODE REVIEW

**Comment by BatElite** [comment]
changelog typo: there -> their

**Comment by ThatFiveGuys** [comment]
> changelog typo: there -> their

I word good

**Review by Tarmunora — APPROVED** [review]

**Comment by Flaborized** [comment]
Personally I think the remaining crates look pretty bare without the stripes, and I think it'd be better aesthetically to keep them or add some kind of design to them to keep the same level of chunky-ness. Even without the color-coding the stripes are part of the design and they'd be worse looking on a purely visual level with them just flat removed, taking the old stripes and recoloring them and imposing them on the sprites like you did for the sci crate would work well IMO

**Comment by ThatFiveGuys** [comment]
Yeah thats a fair point and ill look into that in a few hours

**Comment by blackrep** [comment]
Seems like players still might be able to powergame based on trap & lock type. Might just be better to remove the tiering logic for them, and have them all use the same potential trap & lock pool.

**Comment by ThatFiveGuys** [comment]
> Seems like players still might be able to powergame based on trap & lock type. Might just be better to remove the tiering logic for them, and have them all use the same potential trap & lock pool.
> 
> Alternatively, remove the ability for the multitool to see the trap type.
> 
> Ex: If I see a bomb trap, I know I'm dealing with a T3 crate.

I considered this while making this pr. This pr also changes what locks and traps they use, there's now a lot of overlap between what traps and locks different tier crates get. No trap or lock guarantees what you have is the tier, you can only use it to guess what you have (generally a 50% chance that its the tier you want).

**Comment by ThatFiveGuys** [comment]
> Personally I think the remaining crates look pretty bare without the stripes, and I think it'd be better aesthetically to keep them or add some kind of design to them to keep the same level of chunky-ness. Even without the color-coding the stripes are part of the design and they'd be worse looking on a purely visual level with them just flat removed, taking the old stripes and recoloring them and imposing them on the sprites like you did for the sci crate would work well IMO

Found the civilian and military crates didnt need it, but changed industrial and military crates a little bit so they looked good without them (image of all the crates is in this prs description if you want to see it)

**Comment by Momoberry** [comment]
Good changes imo.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
