### PR TITLE
Sutures are now instant while in proper surgical position

### PR DESCRIPTION
**Pull request by Superlagg**
[BALANCE]
## About the PR 

If you're lying on a table (or any surgery-enabled surface), suturing will be instant. Otherwise, suturing has been sped up a bit, and had the maximum time a suture can take reduced quite a bit.

## Why's this needed? 

From what I've heard, sutures could also use a buff while in surgery.

## Changelog

```
(u)Superlagg:
(*)Suturing someone on a table is now instant.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Hm. I'd skip the instant suturing, keep the general speedup, and make sutures *only* usable on a surgical surface - so that hemostats and bandages still can keep their niches (bleed reduction *during* surgery and bleed-heal out-of-surgery, respectively)

**Comment by Superlagg** [comment]
> Hm. I'd skip the instant suturing, keep the general speedup, and make sutures _only_ usable on a surgical surface - so that hemostats and bandages still can keep their niches (bleed reduction _during_ surgery and bleed-heal out-of-surgery, respectively)

Apparently sutures were supposed to instantly work for surgery. I also don't know why the thing I did made it instant while on a table, so I'd have to figure out that mystery before I can do that.

**Comment by Superlagg** [comment]
So apparently sutures are already instant in surgery, and this PR would do pretty much nothing. Whoops!

**Comment by ZeWaka** [comment]
@Superlagg If this PR does nothing, I'm going to close it.

**Comment by Superlagg** [comment]
> @Superlagg If this PR does nothing, I'm going to close it.

Not if I close it first!

(I forgot I could close these, my bad)

**Pull request closed without merging**
