### PR TITLE
Reworks frenzy like abilities to be a subtype of frenzy

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Changes the spiker frenzy and Crab frenzy to inherit from the brullbar frenzy to reduce code duplication.
Adds king brullbar frenzy.

## Why's this needed? 
Having multiple abilites that are almost exactly the same besides value tweaks which are not subtypes seems like bad practice.
The brullbar king should have a little more punch then normal ones.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Feature freeze, sorry - feel free to re-PR after

**Comment by CheffieGithub** [comment]
Freeze over

**Comment by CheffieGithub** [comment]
need to change the canmove stuff

**Comment by CheffieGithub** [comment]
flail is also very close to frenzy but its different enough

**Review by flappybatpal — APPROVED** [review]

**Comment by flappybatpal** [comment]
Actually on second check, why was the base damage raised from 6 to 7 and weakened duration by 0.5 seconds?

**Comment by CheffieGithub** [comment]
Oh oops, I changed the values to test something and I guess I never changed it back.

**Comment by CheffieGithub** [comment]
Tested the spiker cast code ages ago and forgot to remove it also since you can't cast anything while shuffling nor interact with the ability you don't need the check

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
