### PR TITLE
Rockbox Terminal

### PR DESCRIPTION
**Pull request by NightmareChamillian**
[feature]
## About the PR 

This PR adds a new machine to the game-the rockbox terminal. This is a stationary machine that lets you buy from the rockbox cloud. Codewise, it's just an incredibly, _incredibly_ gutted manufacturer, but since I really feel like it's needed, here it is. Currently, there's one in every map that's in rotation.

image
image
image

## Why's this needed? 
Mining will always put ores into the rockbox, but nobody ever really buys said ores out of it because the only way to purchase them is an incredibly small and easy to miss submenu of the manufacturer.  Also, a lot of the times you'll want to buy something but aren't near a manufacturer.

By adding an object whose sole purpose is to be an interface with the rockbox, hopefully more people will be encouraged to use it.

## Changelog

```changelog
(u)NightmareChamillian
(*)Adds the rockbox terminal to the game and all in-rotation maps
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
Could we get a pic of the sprites in the PR 👀

**Comment by Azrun** [comment]
What locations do you see this going that doesn't have manufacturers?

**Comment by ThatFiveGuys** [comment]
I think the main reason why no one buys from rockbox is simply why would you, besides robotics most jobs have basically no need for mats. My concern with this pr is that people will see this item, and thus assume that its the only way to purchase items from the rockbox, however i dount thatll happen tbh because the rockbox interface is hard to miss on manufactures.

**Comment by NightmareChamillian** [comment]
This didn't fully get the reception I was expecting. It's starting to seem like I might be wrong or the only person on the server who wants an alternative way to buy from the ore cloud. This in mind I may push it not as a mapping change, but a blueprint that spawns in mechanic's so people have to set it up themselves, and keep in mind that the only use it'll see for the test phase is through someone going out of their way to set it up.

> What locations do you see this going that doesn't have manufacturers?

Ideally, I'd want to put them in every rotating map's refinery that's not donut 3, and maybe tool storage, podbay, and/or maint on some maps. As I mentioned, I went through the trouble of making it because more likely to buy from the rockbox when there's a dedicated machine to do, since going to a manufacturer to do so is clunky, easy to miss, and adds steps to the process. It's a more intuitive and obvious way of going about it, but it **isn't a replacement for buying from manufacturers.**

>  simply why would you, besides robotics most jobs
In my experience, any time I'm doing matsci (Making a spear, funny space suit, so on and so forth), aa mechanic, and anytime after tool storage gets looted, as an engineer. Also, as a staffie I often need gold and pharosium for multitools and .22 bullets respectively

> My concern with this pr is that people will see this item, and thus assume that its the only way to purchase items from the rockbox, however i dount thatll happen tbh because the rockbox interface is hard to miss on manufactures.

TBH, that seems like a win win. If people see it and think it's the only way to buy from the cloud, than it's done its' purpose in being a more obvious way around it. If they already know manufacturers, then (In my opinion, at least) it's still a less convoluted method of doing so.

**Comment by codeJester27** [comment]
I think it is a pretty good addition, since some ores have purposes outside of fabricating, and since it might help new players understand the Rockbox and its ores more easily.

Speaking of, maybe the material classification, like "Sturdy Metal, Conductor, Crystal," could also be shown for each ore? It's not very obvious what each ore is good for with their sci-fi names (along with wacky stuff like rocks counting as Sturdy Metal and ice counting as Crystal/Conductor).

**Comment by NightmareChamillian** [comment]
> I think it is a pretty good addition, since some ores have purposes outside of fabricating, and since it might help new players understand the Rockbox and its ores more easily.
> 
> Speaking of, maybe the material classification, like "Sturdy Metal, Conductor, Crystal," could also be shown for each ore? It's not very obvious what each ore is good for with their sci-fi names (along with wacky stuff like rocks counting as Sturdy Metal and ice counting as Crystal/Conductor).

I'll be frank and say that I'm really bad at HTML/TGUI things, and have already had more than enough trouble getting the thing go work, and since the rockbox is TGUI, but the fabricators, which this is derived from are HTML, it'd be really hard deriving a way to get this to work.

**Comment by pali6** [comment]
I think a better idea would be to:

- let rockbox store processed materials too
- make it so the manufacturers show you a menu to directly purchase materials when you click something and lack materials to craft it

A separate machine for purchasing ores doesn't seem like a needed addition to me personally.

**Comment by NightmareChamillian** [comment]
Simply porting the UI to the nanofab would be a much, much better way of doing it. Closing this.

**Pull request closed without merging**
