### PR TITLE
Glasses resprited by Flaborized

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
https://forum.ss13.co/showthread.php?tid=13534&pid=152832#pid152832

## Why's this needed? 
sprot pretty

## Changelog

```
(u)Flaborized
(+)New sprites for a wide variety of glasses
```

### CODE REVIEW

**Review by Gannets — APPROVED** [review]

**Comment by Adharainspace** [comment]
cute and good

**Comment by flrsh** [comment]
The ProDocs especially look gorgeous. The bands for the top row of glasses seem a tad too thick and shaded to me though. @Flaborized do you think you could change the shading a bit?

**Comment by Flaborized** [comment]
> The ProDocs especially look gorgeous. The bands for the top row of glasses seem a tad too thick and shaded to me though. @Flaborized do you think you could change the shading a bit?

I like the thick bands, it makes me feel like they're big worker goggles!

**Comment by flrsh** [comment]
> I like the thick bands, it makes me feel like they're big worker goggles!

What about the shading? Can you make them slightly less dark and more gray?

**Comment by flrsh** [comment]
Thanks Flab :pelterfrog:

**Review by flrsh — APPROVED** [review]

**Pull request merged**
