### PR TITLE
Refactor anchored

### PR DESCRIPTION
**Pull request by TheTyrant25**
[INTERNAL]
## About the PR 
the anchored var in movable atoms now uses the three new defines, `UNANCHORED`, `ANCHORED` and `ANCHORED_ALWAYS`. This change is applied to every file except for map files (the code would still work on dmm files, but the checks wouldn't).
## Why's this needed? 
They previously used anchored = x where x is `0`, `1`, `2`, `TRUE` or `FALSE`. Terribly inconsistent. Code cleanup is good, and prevents stuff like `anchored = 3`.

### CODE REVIEW

**Comment by TheTyrant25** [comment]
map diff bot is uhh
it very much doesn't like `'assets/maps/allocated/flock_tutorial.dmm'`
And probably hates everything else involving this replacement in map files.
Not sure how to resolve that other than changing the individual file.

**Comment by frawhst** [comment]
I'm like 80% sure you can't use preprocessor macros/defines in `dmm` files. So those have to be the raw numbers unfortunately (or people could just make subtypes!!!!)

**Comment by TheTyrant25** [comment]
that takes away like half of the changes lmao

**Review by frawhst — APPROVED** [review]
github can barely handle loading the diffs

**Review by Tarmunora — APPROVED** [review]
Good idea but also I'm not going to double-check that the regex worked

**Comment by frawhst** [comment]
we ball

**Pull request merged**
