### PR TITLE
Adds the taser rifle 

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Adds a taser rifle. Has 2 modes, a 3 shot burst and single shot.

## Why's this needed? 
Taser shotgun is kinda of meh. The spread is extremely niche, since the occasion of having to use it against multiple targets is pretty rare and successfully hitting those shots isn't that easy.

The general design of the taser rifle is to -

1. offer a stronger, more aggresive taser option at the cost of a limited number of shots (about 5 bursts will drain it completely) and it being 2 handed, meaning you're limited to just the rifle until you put it away. The cell can't be replaced, so once the taser is drained, you need to go recharge it.

2. The single shot option is still there, however its weaker than a regular taser shot and costs about the same as the burst, meaning that when you're using it, its go big or go home.

3. Provide better crowd control compared to the taser shotgun due to the direct, concentrated fire.

Let me know if you think anything might be too strong, I'll try and adjust anything I might have missed

Sprites kindly commisioned from Gannets

## Changelog
```
(u)Carbadox & Gannets
(*)Added the taser rifle and put it into a new loadout option called offense alongside 3 flashbangs, while renaming the current offence loadout (the wave gun one) to utility. 
(+)The taser rifle has 2 modes, burst and single shot. It's two handed and it's cell can not be replaced.
```

### CODE REVIEW

**Comment by flrsh** [comment]
What do you think @Tarmunora @PrimeNumb @mybluecorners? 

Also, instead of replacing the shotgun, you could just create another loadout. I think mbc wanted more loadouts but we were kinda short on ideas.

**Comment by Carbadox** [comment]
> Also, instead of replacing the shotgun, you could just create another loadout. I think mbc wanted more loadouts but we were kinda short on ideas.

Sounds fine with me,

**Comment by Carbadox** [comment]
Gonna copy paste the update I put on the forums 

I've put the taser shotgun back into the control loadout. But I've also renamed the waveguns loadout from offense to utility and made a new loadout for the taser rifle (rifle, 3 flashbangs and a baton)

Also bumped up the cell from 200 to 300 per Superlaggs suggestion (if I understood it correctly)

**Comment by Tarmunora** [comment]
Can't say that I'm a fan of any of this (except maybe the sprite). It's a 2h taser that gets 13 shots of burstfire and a joke of a singleshot mode (2/9 of the power of the burst and costs *more* than the burst), at the cost of not being able to hotswap the cell. I don't think this is something that should be given to security, especially as a loadout item. 
The sprite itself is good, though it looks more like a modified egun, which makes me feel it would be better used on the existing taser assault rifles that NT-SpecOps get, which switch between a stun and lethal mode

**Comment by Kyle2143** [comment]
I don't really think the sprite matches what it's supposed to be. Mainly because the rifle shoots yellow taser and minispark projectiles only, but has a blue energy indicator similar to the egun, also the wooden bit beneath the indicator near the front looks more like a pump that would be found on a shotgun.

I agree with yass about the single shot vs burst modes. If single shot is so much worse than burst in every possible way, then I can't imagine there ever being a reason to use it. There should be pros/cons to both ideally. If not, then make burst be the only mode, I don't see the point of having a useless firing mode on the weapon.

**Pull request closed without merging**
