### PR TITLE
Rockbox Default Price and Auto-Sell

### PR DESCRIPTION
**Pull request by codeJester27**
[feature][qol]

## About the PR 
Adds a default price number input to the Rockbox, that lets you control the default price of new ore entries when they are loaded. It is $20 by default.
Adds an "Auto-Sell" checkbox that automatically marks new ore entries for sale when they are loaded. It is enabled by default.
image

## Why's this needed? 
Makes selling ore easier, especially if you don't care about individual pricing.

## Changelog

```changelog
(u)CodeJester
(+)The Rockbox now has a tweakable default price for new ore entries, and an auto-sell feature for automatically marking new ore entries for sale. "Please use it." -Mechanics and Roboticists
```

### CODE REVIEW

**Comment by blackrep** [comment]
IMO "Sell All" seems misleading. For me, "Sell All" would also include overriding the prices of the ores on sale already. Might want a different Call to Action text.

**Comment by codeJester27** [comment]
> IMO "Sell All" seems misleading. For me, "Sell All" would also include overriding the prices of the ores on sale already. Might want a different Call to Action text.

Should it just be Auto-Sell?

**Comment by Merlin1230** [comment]
Maybe this could be toggleable? That way whenever I add a new ore that doesn't have a entry, it'll be set for sale already and I dont have to worry about it

**Comment by mordent-goonstation** [comment]
Agreed with comment that the interaction isn't intuitive in how it works. Could consider framing as a "default price" and whether that default price is enabled or not?

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Pull request merged**
