### PR TITLE
Refactor Nanomed-Plus inventory

### PR DESCRIPTION
**Pull request by Sord213**
[feature][add to wiki]
## About the PR 
Changes the Nanomed Plus inventory to be a bit more stocked and to be more in-line with the Port-A-Nanomed. Changes a lot of chemicals that were in syringes to bottles. Adds emergency auto injectors to some more common chems. Also increased materials cost from 10 to 18 to balance the increased stock.

New stock
Screenshot_571
Old stock
Screenshot_569

## Why's this needed? 
I've never liked how the stationary Nanomeds were lacking in a lot of stock when compared to the portable version. The stationary versions should, in my opinion, be more robust than the portable version. Auto injectors allow lifesaving meds to be dispensed more quickly. The patch count in particular also never seemed right to me.

## Changelog

```changelog
(u)Sord
(+)Changed Nanomed Plus inventory
```

### CODE REVIEW

**Comment by jan-antilles** [comment]
Fewer automenders but more patches... definitely will make some rounds more hectic, but I think I like this.

**Comment by Yellow-Mushroom** [comment]
I agree, I will miss my charcoal bottles since I always kept those on my belt. This change will hurt but I like the effects it will have on medbay a lot

**Comment by Tarmunora** [comment]
Prefer having more menders than patches available. Stacked patches can reach some honestly obscene healing rates

**Comment by jan-antilles** [comment]
> 
> 
> I agree, I will miss my charcoal bottles since I always kept those on my belt. This change will hurt but I like the effects it will have on medbay a lot

He mentions in the description that the charcoal bottles aren't in the screenshot but are there in the code he's PRing. :)

**Comment by Tarmunora** [comment]
And as more of an overall direction kind of thing, I'd rather the port-a-nanomed have less stuff in it and be more of an on-site triage/emergency heal rather than completely homogenize the medical vendors

Especially the idea of doctors vending emergency autoinjectors for all the in-medbay treatments feels very wrong

**Comment by Sord213** [comment]
> 
> 
> And as more of an overall direction kind of thing, I'd rather the port-a-nanomed have less stuff in it and be more of an on-site triage/emergency heal rather than completely homogenize the medical vendors
> 
> Especially the idea of doctors vending emergency autoinjectors for all the in-medbay treatments feels very wrong

Maybe this is just me but I never liked the pre-loaded syringes. Syringes can be a little fumbly for new players, accidentally toggling them to draw instead of inject was one of the big issues I've noticed. Or not knowing you can stack injections so they slowly add 5u at a time.

Bottles on the other side tend to get vended and either their entire contents dumped into a hypospray and used in one go or 10u of them is used and the bottles are scattered around medbay half empty. Emergency autoinjectors are simple to use and clear to see when they're expended.

I was also going to hit the stock of the port-a-nanomed but figured I'd save it for a separate PR.

**Comment by BatElite** [comment]
Just-now bottle edit looks fairly good to me, as my main concern was that you can't get the reagents out of auto-injectors (which was maybe a problem for secret chems I don't know of, but mostly a complication for the synaptizine + atropine combo.) Here's a few thoughts though:

-Mannitol and salbutamol pills were pretty useful at least for me, as I like to add them. The former is pretty trivial to make via chemistry so not a huge loss, while salb is pretty doable if a bit annoying.

-I'm wondering if calomel bottles are a good idea. It's better to have a bit more flexibility with the stuff than the 5u auto-injectors, but the syringes spanned the range between 5u "deal with neuro/ethanol" and 15u "nuke the bloodstream" use cases. (It is probably the only chem that is particularly suited to a pre-filled syringe though.) 30u bottles are probably a bit overkill if this is aimed at helping newbies.

-You've accidentally listed oculine bottles twice

**Comment by virvatuli-gh** [comment]
This will make people (as in, non-doctors) raid medbay to hack the machines even more, similar to how medkit lockers always get targeted for autoinjectors and menders. That being said I literally never use regular syringes unless I there is no alternative as a Doc because injectors are just so easy to use and dose with, and they definitely are much easier to understand for newbies. If I remember correctly the original idea behind autoinjectors is that they're _supposed_ to be a limited resource which you can restock through QM, and why the Portanano is limited to begin with. Adding them to regular Nanomeds throws the balance idea out the window with how easy Nanomeds are to replicate.

**Comment by TDHooligan** [comment]
Was definitely on the PR's side til i read the comments, perhaps it's better to keep the autoinjectors out of the main vending machines, but I do think doctors should have some easier access to them without having to raid the emergency triage storage.

**Comment by Sord213** [comment]
> 
> 
> This will make people (as in, non-doctors) raid medbay to hack the machines even more, similar to how medkit lockers always get targeted for autoinjectors and menders. That being said I literally never use regular syringes unless I there is no alternative as a Doc because injectors are just so easy to use and dose with, and they definitely are much easier to understand for newbies. If I remember correctly the original idea behind autoinjectors is that they're _supposed_ to be a limited resource which you can restock through QM, and why the Portanano is limited to begin with. Adding them to regular Nanomeds throws the balance idea out the window with how easy Nanomeds are to replicate.

Initially I did have more auto injectors compared to bottles of chems, but some good arguments were made from experienced doctors in discord so I moved a lot of the chems that were in syringes into bottles and put them back. With the bottles, some of the chems are actually more limited in supply than before. For example calomel, before there were 10 syringes at 15u each for a total of 150u of calomel. Now there's only 3 bottles of 30u each. 

The reason I, personally, prefer auto injectors is they're much easier for new players to use and understand how to use than syringes. No accidentally toggling withdraw mode and thinking their syringe is broken. Or not knowing they can stack injections and thinking syringes are useless because they're so slow to inject. But on the other side, experienced doctors can still grab their bottles of chems for use in hyposprays or syringes in a pinch.

**Comment by ThatFiveGuys** [comment]
> If I remember correctly the original idea behind autoinjectors is that they're _supposed_ to be a limited resource which you can restock through QM, and why the Portanano is limited to begin with. Adding them to regular Nanomeds throws the balance idea out the window with how easy Nanomeds are to replicate.

Id like to point out here that port a nanomeds are easier to replicate then nanomeds with them costing less mats to make more of them.

**Comment by BatElite** [comment]
> Id like to point out here that port a nanomeds are easier to replicate then nanomeds with them costing less mats to make more of them.

Port-a-nanomeds are 30 mats though? Even with the boost in mats this PR gives you can get close to double regular nanomeds for that price.

**Comment by ThatFiveGuys** [comment]
> > Id like to point out here that port a nanomeds are easier to replicate then nanomeds with them costing less mats to make more of them.
> 
> Port-a-nanomeds are 30 mats though? Even with the boost in mats this PR gives you can get close to double regular nanomeds for that price.

Oh huh swore they costed less, whack. Oh well still pretty easy to get more port a nanomeds.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
