### PR TITLE
Adds a new chemical, neurodepressant

### PR DESCRIPTION
**Pull request by colossusqw**
[LABEL]

## About the PR 
This PR adds a new chemical, neurodepressant, which is a compound obtained via breaking down neurotoxin with solvants and heat, in this case, sulfuric acid and acetone. It's not lethal, nor does it KO you, however it's still rather debilitating due to it's missteps and random drowsiness/muted effects. Comes with a lot of flavor messages as well, useful when you want to subdue someone or just scare them a bit :).

## Why's this needed? 
We have a lot of chemicals that either just KO you or kill you, but i feel some chemicals to make it harder to function normally and still be scary, without completely taking away your agency or being outright super dangerous, would be good! It's not the easiest chemical to make, and considering acquiring much stronger stuff like panc, sarin or capu is just as easy i don't really see it as being an issue balance wise.

## Changelog
```changelog
(u)Hans
(*)Added a new chemical, neurodepressant! A compound that messes with muscular function and causes dizziness.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
Some feedback after testing this in singleplayer on myself:
1) IMHO the muted effect is a little too commonly applied- maybe make it slightly rarer
2) Add drooling and staring blankly as involuntary emotes to be in the later stages to fill in for the muted effect
3) To compliment the muteness, maybe add occasional, but short knocked down/ stunned/staggered effects?
4) Make the blurriness *slightly* more noticeable 
5) If you're adding some of the things I added, consider toning down the misstep chance, or making it less likely overall
4) Some additional flavor text items for less repetitiveness:
"You feel a numbness spread through your (limbs, maybe a bit more more precise like fingers)
"your vision (spins, twirls, devolves into a blur, devolves into static, goes fuzzy)

**Comment by colossusqw** [comment]
> Some feedback after testing this in singleplayer on myself:
> 
> 1. IMHO the muted effect is a little too commonly applied- maybe make it slightly rarer
> 2. Add drooling and staring blankly as involuntary emotes to be in the later stages to fill in for the muted effect
> 3. To compliment the muteness, maybe add occasional, but short knocked down/ stunned/staggered effects?
> 4. Make the blurriness _slightly_ more noticeable
> 5. If can, consider toning down the misstep chance. It's slightly obnoxious, but could be set to the side show for more interesting effects
> 6. Some possible flavor text items for less repetitiveness:
>    "You feel a numbness spread through your (limbs, maybe a bit more more precise like fingers)
>    "your vision (spins, twirls, devolves into a blur, devolves into static, goes fuzzy)

ooh, thanks for the input

**Comment by Tarmunora** [comment]
Personally, I think that something like this would be better if it was purely just discount neurotoxin (i.e.: neuro but without the tox/brain/paralysis), without having a bunch of custom text and statuses applied on top, giving it a niche as a non/less-griefy additive to bar drinks etc. As it is presented here, can't say I'm a huge fan.

**Comment by colossusqw** [comment]
> s), without having a bunch of custom text and statuses applied on top, giving it a niche as a non/less-griefy additive to bar drinks etc. As it is presented here, can't say I'm a huge fan.

would you prefer most the messages gone, or simply have them appear very rarely?

**Pull request merged**
