### PR TITLE
Fix shuttle window connections

### LINKED ISSUE #8114: Shuttle windows auto-connect to station windows
### Labels

[minor]

### Description

Emergency shuttle windows automerge with station windows, leading to a weird broken look once the shuttle departs

### Steps to reproduce

1. Have the emergency shuttle come in
2. Have the shuttle depart
3. See wonky windows

### Expected Behavior

Some special case where the windows of shuttle areas don't merge with those from adjacent areas

### Additional Information & Screenshots

image

This was on cog1, which has a lot of glass around escape

### PR DESCRIPTION
**Pull request by pgmzeta**
## About the PR 
Adds exceptions for both window/auto and auto/lead/blue walls so they don't auto-connect with each other.

## Why's this needed? 
Fixes #8114

## In game example

https://user-images.githubusercontent.com/91498627/163601166-cc3c16cd-91f3-4913-b367-cd7c1eab2eca.mp4

### CODE REVIEW

**Comment by Laboredih123** [comment]
What about making windows update on move?

**Comment by pgmzeta** [comment]
updating on move would leave a weird interaction with cogmap's glass escape hallway

**Comment by flappybatpal** [comment]
I don't know why you'd want to update on move?

**Comment by pgmzeta** [comment]
I'm not thrilled at how this messed with centcom windows. not sure what other tack to take here, though.

**Comment by ZeWaka** [comment]
shuttle is a bit more of priority imo

**Pull request merged**
