### PR TITLE
Rearranges some rooms on Mushroom

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
5/6 Departments are in the south of Mushroom, this PR moves mechlab as a high traffic area back to its home department to generate more traffic in the north, then moves emergency storage A which was where mechlab was to ranch, which has been moved to a new area in what is currently space west of botany. Warehouse has had a small cleanup and a public refinery added. The area where mechlab was is now a stock exchange with a market stall to make the most out of the high traffic of the south. The random room behind mechlab has been made to a supply closet for janitors as while them having to go all the way to the top of the map to resupply can generate traffic in the northern hallways it was in a very anti-qol way. Also adds 2 escape pods at escape and one in maint near brig, as the map previously had no escape pods.

## Why's this needed? 
Gives Mushroom's northern hallways some more visited areas which are returned to in order to pull traffic from the cluttered south.

### CODE REVIEW

**Review by Sord213 — COMMENTED** [review]
Not a fan in general. Don't like gluing the ranch to the exterior of botany, don't like the random third market stall/stock market, and just moving the emergency storage on top of the warehouse feels weird. "Here's the big storage room on top of the big storage room"

**Comment by cheekybrdy** [comment]
Done some adjustments for the concern areas of the PR, removed the ranch area and instead put Emergency Storage A where the stock exchange was, moved Ranch to crew quarters and vice versa for where ranch initially was

**Comment by cheekybrdy** [comment]
!merge_upstream

**Comment by cheekybrdy** [comment]
Closing due to me being incompetent at conflict fixes, will reopen the revised version post feedback

**Pull request closed without merging**
