### PR TITLE
Preferred cyborg name

### PR DESCRIPTION
**Pull request by Luxizzle**
## About the PR 

Adds a "Preferred Cyborg Name" in the general tab of your character profile. Allowing you to set a name that will be set as the default name in the cyborg name pop up instead of the random name.

image

## Why's this needed? 

People like having the same name across shifts, and the same should be for cyborgs.

## Changelog

```changelog
(u)Luxizzle
(+)You can now set a preferred cyborg name in your character profile
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Now we just need this for mime and clown too

**Comment by Josephin23** [comment]
throw in AI too actually

**Comment by Luxizzle** [comment]
@Josephin23 AI is included with this

**Comment by Luxizzle** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Pull request merged**
