### PR TITLE
AAAAAAAAAA

### PR DESCRIPTION
**Pull request by Eagletanker**
[BUG FIX] [XS]
## About the PR 
Fixes Brullbar plush

## Why's this needed? 

AAAAAAAAAA

### CODE REVIEW

**Comment by Eagletanker** [comment]
Fuck i forgot to wipe tjis

**Comment by flappybatpal** [comment]
I think you might have a branch before the armory area change resulting in map changes?
It's probably easiest to reset your branch to master and reimplement your fix.

Also please use a real PR name.

**Review by pali6 — CHANGES_REQUESTED** [review]
What katzen said

**Comment by Eagletanker** [comment]
Tam fixed it aaaaaaaaaaa…..

**Pull request closed without merging**
