### PR TITLE
Lets you dissolve pills by attacking them with a container

### PR DESCRIPTION
**Pull request by BatElite**
[feat][qol]
## About the PR 
This PR makes it possible to dissolve pills in a reagent container by attacking the pill with one, similar to how you can pick up stuff with backpacks and boxes.

I also removed a superfluous copy of attackby from pill code.

## Why's this needed? 
Partially it's an ease of use thing, but mainly it allows borgs to pick up chems in pill form easily. It's especially relevant to medborgs wrt salbutamol & mannitol, but borgs can also feasibly store intermediate chem steps in pill form without taking up a beaker.

## Changelog

```
(u)BatElite:
(+)You can now dissolve pills by using a suitable container on them instead of only the other way around. Cyborgs might find this particularly useful.
```

### CODE REVIEW

**Comment by Tiggersaurus** [comment]
This would be a massive QoL change for borg o.o;

**Review by Tarmunora — APPROVED** [review]

**Review by ZeWaka — APPROVED** [review]

**Comment by Sovexe** [comment]
image
bug

**Comment by BatElite** [comment]
Huh. I figured this wasn't going to be that easy.

What cigarettes are you using to get that result? I've tried a few brands and a custom one, but none would consume the pill.

**Comment by Sovexe** [comment]
`/obj/item/clothing/mask/cigarette/custom`

**Comment by BatElite** [comment]
Ah, I wasn't spawning in them directly, hence why I didn't get that result.

I don't think you can normally get uninitialised custom cigs. Otherwise that 600u default cap is a bit worrying. :P

**Comment by Sovexe** [comment]
Any rolled cigarette will be a custom one, however the bug doesn't occur when they are first spawned as they have a filled reagent holder. However if you smoke such that the reagent holder is no longer filled it will occur

Additionally I like spawning handing out custom cigs for admin gimmicks sometimes

**Review by Sovexe — APPROVED** [review]

**Review by pali6 — APPROVED** [review]

**Pull request merged**
