### PR TITLE
Removes numbers from health scanners on RP

### PR DESCRIPTION
**Pull request by frawhst**
todo:
- [ ] Fix sleeper
- [ ] Add a way to force a numeric scan (for admin stuff and maybe the surgical computer)
- [ ] 2nd/3rd/4th pass on adjectives
## About the PR 
No changes to Classic.
Changes health analyzers and similar to use adjectives rather than hard numbers or percentages:
image
image
image

## Why's this needed? 
"Doctor she has 109 brute damage!!"
"I am 54% healthy"
what does this even mean
Ideally people will use more accurate/less gamey medical terminology for injuries.

## Changelog 
```
(u)aloe
(+)Health analyzers and similar on the RP servers now give adjectives rather than hard numbers for health scans.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Would appreciate a description of the damage values and their respective adjectives for posterity. Life threatening is also a tad long, I sugegest FATAL.

**Comment by Xkeeper0** [comment]
I said this in the admin channel as well, but I don't like it.

it's going to annoy people with "great, how much is none/minor/major/life-threatening, what do all these words mean, and why are they changing position so it makes it harder to read at a glance"; the thresholds aren't clear, and you can conceivably be dying with three "minor" and one "major".

People already dislike the Health Implant HUD because it severely muddies the ground between the standard 100-80-60-40-20-0 health meter scale by replacing it with four even _less_ clear icons; this is doing that, but for _everyone_.

**Comment by DisturbHerb** [comment]
Label added based on the current consensus (really, lack thereof) developing in the forums discussion and the discord server. Feel free to remove if inappropriate.

**Comment by Tarmunora** [comment]
To repost from adminchat, mildly against further RP/main code divergence.

**Comment by nefarious6th** [comment]
it's a game, some elements are inherently mechanical, telling health based on numerical is a part of that since the medical system is quite exacting (you can have numeric deficits to your health), versus being mostly dependent on sort of qualitative things that appear via various symptoms (think of how food poisoning functions in-game, for example; analysis of someone with it and the treatment of it is non-numeric, it's all qualitative).
I think non-numeric health scans works, but only if the health system you're analyzing is also non-numeric. If numeric health values/damages were to be removed and instead you ended up with qualitative treatable conditions that you could scan for, like the organ damages or perhaps something like "internal bleeding" for brute, "3rd degree burns" for burns, more specific poisonings for toxins, then I could see qualitative descriptors working in diagnoses. Because the 4 base damage types don't currently work in that way, changing from the exact terminology to representative words obfuscates that. It doesn't add a layer of meaningful depth, it just adds another link in the chain to work past as people would go to memorize the words as shorthand for a range of quantitative damage values, versus the more qualitative representation of an overall state. I think there's have to be a system overall of damage to be more qualitative in order to introduce a feature like this, otherwise, instead of adding more realism in the measurements, it distances you from the object you're actually meant to measure.

**Comment by Kubius** [comment]
I think one possible way to explain it is "54% healthy" means an assessment provided by the analyzer that your condition will deteriorate on its own if unattended, with 0% (crit) being "you Will Not recover unless action is taken".

The health numbers are an abstraction of more detailed physiological damage, and it makes sense that something capable of analyzing that physiological damage would provide you with sufficient detail of that abstraction.

My suggestion, if you still want to go ahead with this: **Require medical training to interpret the results of an analyzer scan at full precision** (barring cyborgs). IMO, this would more properly work into that abstraction - a medically trained eye would be able to pick things out on scans that a layman couldn't, but anyone can see "leg broken" or "skin seared off".

**Comment by TDHooligan** [comment]
given this change is controversial i think it's worth encouraging opinions unrelated to the code itself going on the thread rather than the github comments. 
git comments will likely be read more thoroughly than the forum, in case of any actual code comments (i know i'm guilty of doing this a couple times)

**Comment by ZeWaka** [comment]
I'm personally for closing this PR based on the forum discussion - @frawhst?

**Comment by frawhst** [comment]
ye, fine with closing this.

**Pull request closed without merging**
