### PR TITLE
changes nanomed access to medlocker access

### PR DESCRIPTION
**Pull request by nefarious6th**
[input wanted]
## About the PR 
changes both stationary Nanomeds and Port-a-Nanomed access requirements to access_medical_lockers versus access_medical

## Why's this needed?
All medical personnel who had access to the machines before still have access.
Security Officers and Janitors will no longer have access. Prevents self-treatment automatically. Both jobs are now in parity with other non-medical jobs in that they will have to hack the machines or get an ID upgrade first to be able to use them.

```changelog
(u)nefarious6th
(*)removes security officers' and janitors' access to the Nanomed and Port-a-Nanomed
```

### CODE REVIEW

**Comment by LuminousAether** [comment]
This one... probably should have the forum thread treatment.
It's potentially reducing the nonmedical staff that have medical access in an emergency to nearly zero (Basically Cap/HoP/HoS). And that has probably a pretty big balance implication. Especially on Main where the med staff are a whole lot... spottier. That's not a small change.

And kind of feels like making life more difficult for everyone just to satisfy a personal pet peeve.

**Comment by pgmzeta** [comment]
Restricting stationary nano-meds to medical locker access seems OK to me, but I think the portable one should remain available for wider/emergency use. A wider discussion thread with more main & RP players seems like a good idea here.

**Comment by Yellow-Mushroom** [comment]
I do not believe this poses that large of an issue as security officers can raid medbay for supply or choose the medical utilities from their sec vend if they want to carry meds.

This significantly helps with the RP issues of sec swerving out of their lane and ignoring doctors to treat others/themselves. As a doc on RP, you often have very little to do due to a lack of general violence/threats to the station. This paired with the very efficiency and speed of medborgs means doctors can often just stand around waiting for patients, or getting highly territorial like vultures for patients. 

This is only made worse when sec decides to doctor people with the nano-med instead of calling a doctor to their location. 

If the situation is desperate, and they really need meds, they can have the AI summon then dispense meds to them/others while they wait for a doctor to arrive

**Comment by nefarious6th** [comment]
Opened thread

**Comment by Kyle2143** [comment]
I'd say removing this access from janitors makes sense. But not security. Maybe if porta-nanomed was on its own access then I'd remove security from accessing the standard medical vendors.

**Comment by nefarious6th** [comment]
For whatever it's worth, this was made with complaints from people doctoring on classic in mind too; i have had concerns and have heard other people raise concerns about everyone rushing into the OR to do their own stuff on classic, which is certainly allowed, I just personally think more effort to disrupt people's jobs would be a fair thing.
I also do tend to find the Public minimeds underutilized and able to solve most emergency medical situations that require access to medchems.

**Comment by Momoberry** [comment]
> Restricting stationary nano-meds to medical locker access seems OK to me, but I think the portable one should remain available for wider/emergency use. A wider discussion thread with more main & RP players seems like a good idea here.

This seems like the best of both worlds, as the portable is made for emergencies. Personally like the PR, medical is in shambles currently lmao.

**Pull request closed without merging**
