### PR TITLE
Easier Access to writing for Wraith

### PR DESCRIPTION
**Pull request by Momoberry**
## About the PR 
PR removes the cooldown and reduces the price to 2 points for blood writing. 

## Why's this needed? 
Easier access to spooky writing seems nice. The writing is easy to clean, so even with it being more frequent, it shouldn't really cause any issues and makes it easier to engage the crew with spooky messages. It's also a request from the idea forums: https://forum.ss13.co/showthread.php?tid=19749

## Changelog

```changelog
(u)Momoberry
(+)Wraiths blood writing no longer has a cooldown and costs 2 points, instead of 10.
```

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
not a fan of 0 cooldown, needs /something/

**Comment by Momoberry** [comment]
> not a fan of 0 cooldown, needs /something/

It's mostly an aesthetic choice cause I don't like having the cooldown low enough where it won't visually update with a cooldown overlay. But then if I have it high enough where it applies, it's a pretty notable delay. I'll tweak with it

**Comment by Momoberry** [comment]
> not a fan of 0 cooldown, needs /something/

Flat one second cooldown added. Do you know of a way to make it so the cooldown overlay will immediately activate on usage?

**Comment by ZeWaka** [comment]
> > not a fan of 0 cooldown, needs /something/
> 
> Flat one second cooldown added. Do you know of a way to make it so the cooldown overlay will immediately activate on usage?

there's probably a proc to refresh

**Pull request merged**
