### PR TITLE
make unloading a gun make a sound

### LINKED ISSUE #7837: Unloading guns is silent
### Labels

[trivial]

### Description

Unloading a gun makes no noise

### Steps to reproduce

1. unload a gun
2. it makes no noise

### Expected Behavior

The gun makes a noise!!!

### Additional Information & Screenshots

_No response_

### PR DESCRIPTION
**Pull request by TheTyrant25**
[SOUND] [BUG]
## About the PR
Makes unloading a gun play the same sound as loading it.

## Why's this needed? 
It did not have a sound
Fixes  #7837

### CODE REVIEW

**Comment by CheffieGithub** [comment]
The same sound as loading could cause confusion

**Comment by TheTyrant25** [comment]
what sound do you suggest then? different guns have different loading sounds so it could get weird if they all were the same

**Comment by CheffieGithub** [comment]
Im not sure but the two should be distinct in some way. you can use the same sound with sound settings to make it a bitdifferent I suppose

**Comment by TheTyrant25** [comment]
that's a good idea, i'll do that

**Review by frawhst — APPROVED** [review]
Slightly varied sound would be nice but yeah overall I want this (i made the issue report, so slightly biased).

**Comment by TheTyrant25** [comment]
it turns out i could not figure out how to do that

**Comment by CheffieGithub** [comment]
proc/playsound(atom/source, soundin, vol, vary, extrarange, pitch, ignore_flag, channel, flags) 
I would mess with vol, vary, and pitch

**Comment by TheTyrant25** [comment]
turns out that vary is a bool which automatically messes with the pitch for you, who knew. I didn't.

**Pull request merged**
