### PR TITLE
UM-042 - Remove .38 Stunners from Hacked General Fabricator

### PR DESCRIPTION
**Pull request by UrsulaMejor**
## About the PR 

- Title

## Why's this needed? 

Blocks #1337 

I've never run out of ammo as Detective, as there's plenty of ammo available in the SecTechs around the station.

## Changelog

```
(u)UrsulaMajor:
(+)Removed 0.38 Stun Rounds from the General Manufacturer
```

### CODE REVIEW

**Comment by Gerhazo** [comment]
I've always seen these and used personally as being there for people trying to make us of a zipgun, rather than spare ammo for detectives. Something to consider.

**Comment by UrsulaMejor** [comment]
> I've always seen these and used personally as being there for people trying to make use of a zipgun, rather than spare ammo for detectives. Something to consider.

If that's the case, then they should deffo be removed, seeing as the current design direction we've settled on is to remove easy access to stun weaponry from non-sec crew: see the securitry & securitron changes. Those changes don't work if there's still just another thing that's trivial for the crew to get.

**Comment by Carbadox** [comment]
Eh, zip guns are hardly used by power gamers. I think they're in a good position as they are and this would unneccesarily nerf them way too much,

**Comment by UrsulaMejor** [comment]
did you see https://github.com/goonstation/goonstation/pull/1337? This PR is part of a duo that would buff zipguns overall

**Pull request merged**
