### PR TITLE
Adds pride vendors, find-replaces all the pride lockers

### PR DESCRIPTION
**Pull request by DisturbHerb**
[QOL][MAPPING][OBJECTS]

## About the PR 
Adds a pride clothing vendor to the codebase. No access requirements, no hidden items (I briefly considered the pride-o-matic but... naaah.)

pride locker

Also did a cheeky find-replace of all the pride lockers on the public repo. The item still exists.

## Why's this needed? 
We're moving towards vendors and people seem to be generally okay with 'em, figured that if we end up expanding the pride merch lineup it'd be helpful for reducing clutter as well.

## Changelog 

```changelog
(u)DisturbHerb
(+)Replaced all the pride lockers with pride vendors.
```

### CODE REVIEW

**Comment by Adharainspace** [comment]
I don't really think the pride locker needs to be a vendor. No reason for a basic clothes locker to not work without power. Any further extensions (like pride flags) could be constructed in game in other ways to avoid cluttering up the pride locker. Those are my thoughts on this.

**Comment by Adharainspace** [comment]
If the PR author has no further comments I will be closing this pr.

**Comment by DisturbHerb** [comment]
My rationale for replacing the lockers with a vendor was to consolidate everything pride-related into one place, and it just seemed like the best solution to accommodate the pride flags only after discussing other methods of acquiring them on imcoder. I just personally think that the other methods conceived would be overly unintuitive or janky.

Having departmental clothing lockers replaced with vendors have already made them inaccessible with loss of power anyway (similarly to other methods of acquiring basic clothing such as the booth and fabricators) and it seems to have been a trade-off that has been generally accepted given that they have largely supplanted equipment lockers.

While I'm not going to die on this hill, I would personally appreciate a broader range of feedback on the concept so we can reach some consensus on their inclusion or rejection.

**Comment by DisturbHerb** [comment]
> I just personally think that the other methods conceived would be overly unintuitive or janky.

this was true until like two minutes ago, feel free to close the PR

**Pull request closed without merging**
