### PR TITLE
Adds kendo sword

### PR DESCRIPTION
**Pull request by Carbadox**
[ENHANCEMENT]

## About the PR
Adds a kendo sword into the game along with a sheath.
It's a child of the katana without the teleport special attack or delimb chance however, so it can be used for sword duels training and fights. Part of a hopefully series of PRs.

## Why's this needed? 
Having a dedicated item for parrying and sword fighting is fun. It's also nice to give the crew a sword. Much better than having to rob the captain of his.

## Changelog
```
(u)Carbadox and Enakai:
(+)Added a new wooden training sword, for martial art of Kendo!  Find it in your local fitness room on Cog1, Oshan, Manta, Horizon and Clarion!
```

### CODE REVIEW

**Comment by AwkwardDryad** [comment]
So....About a day before development on this patch was started, I'd talked about my own plans for a kendo patch that is currently in development. by me...In fact, the only reason talk about kendo came up in the first place was because i was asking enakai for permission to code their assets into the game. Aaaaaand after that this happened while I was in the middle of respriting their lost armor sprites and apparently the project was sniped from. Originally, I decided to concede this feature, but after my direct ping to you was ignored and seeing how this feature was executed, I feel like it was rushed, poorly implemented, and I personally feel a little attacked.

Forgive me for being majorly rubbed the wrong way, but it kinda feels like this project was ripped out of my hands and I'm going to continue development on my patch.

**Comment by Avatharian** [comment]
> horizon was straight up deleted in this PR...

And nothing of value was lost.

**Comment by geneva-breaker** [comment]
Thank

**Comment by ZeWaka** [comment]
If you can't convert the map to TGM to fix the conflict, I can. Or, use the master one and then edit it

**Comment by Carbadox** [comment]
Please do. No other mapping programs work on my craptop other than qwertyDMM and I'm pretty sure it's why and how I managed to delete horizon in the first place.

**Comment by ZeWaka** [comment]
I'll be able to in ~10h.

**Comment by ZeWaka** [comment]
Ok tomorrow.

**Comment by Gannets** [comment]
I like the idea of giving the crew access to some  neutered versions of traitor items, gives folks a chance to train with some of our more advanced features without having to wait for an antag round to pop.

**Comment by Tarmunora** [comment]
merge conflicts and a different implementation of this idea was merged (#1258). @Carbadox consider closing

**Pull request closed without merging**
