### PR TITLE
A Devious Expression for the AI

### PR DESCRIPTION
**Pull request by Terms-On-Dragon**
## About the PR 
This provides a particularly devious expression the AI can display on their core and status displays. Any Nanotrason employees may find this certain face unnerving.

## Why's this needed? 
As to allow the AI to show the station crew their conspicuous grin.  :]

## Changelog 

```changelog
(u)Terms-On-Dragon
(+)The AI has learned a new DEVIOUS face to express across the station.
```
https://github.com/goonstation/goonstation/assets/139170673/39018a61-daa1-4dc5-b2d3-2b48c1fc8897

DeviousAIFace-Sheet

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
AI sus

**Comment by Cherman0** [comment]
reopening per author request

**Comment by frawhst** [comment]
!merge_upstream

**Review by ZeWaka — APPROVED** [review]

**Comment by ZeWaka** [comment]
x

**Pull request merged**
