### PR TITLE
Map vote's window's wrapping fix

### LINKED ISSUE #20070: Map vote improper wrapping with 8 map choices
### Labels

[BUG] [TRIVIAL]

### Description

The map vote UI doesn't properly display for 8 maps.

### Steps to reproduce

1. Generate the mapvote with 8 maps (Cog1, Cog2, Donut2, Donut3, Kondaru, Clarion, Oshan, Nadir. Any should work, the widths seem to be the same)
2. Open the mapvote selection
3. Notice graphical error

### Expected Behavior

The images should be aligned to two rows

### Additional Information & Screenshots

What it looks like upon opening
nf6NdlOfuR

What it looks like after slightly increasing the width manually
image

### PR DESCRIPTION
**Pull request by Garash2k**
## About the PR 
Shuffles margins around so that everything is better aligned and more predictable. Old, default technique had extra margin on the first item of a new line.

LnIPB9VXxp
3up3O6lxDs
hy7piT25zx

## Why's this needed? 
Fixes #20070

[UI][Bugfix]

### CODE REVIEW

**Comment by ZeWaka** [comment]
X

**Comment by mordent-goonstation** [comment]
It'll do until we can dump IE and get some more modern CSS (`gap`). Merge `master` into it, rebundle, push, and should be good to go.

**Comment by Garash2k** [comment]
Yep, would have used gap if I didn't look it up on caniuse and see that it wasn't ie11 compatible

**Comment by mordent-goonstation** [comment]
Do the thing with the merge from master and rebundling, and this is good to go.

**Pull request merged**
