### PR TITLE
Resprites Spiders

### PR DESCRIPTION
**Pull request by colossusqw**
[LABEL][sprites][critters]

## About the PR 
This PR resprites the large and medium sized spiders of all colors, as well as the ice spiders, updating them a bit and giving them four directional sprites.
EDITED YET AGAIN:
image

## Why's this needed? 
Cool spiders pretty. (Please do not ask me to resprite the clownspiders the prospect of respriting them is terrifying)

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
i like the old sprites a lot more because they have a lot more contrast and aren't mushy

See: ice in the game looks like this 
image

**Comment by WALPVRGIS** [comment]
I won't be able to today (in bed with neck injury like a fool) but I'll be doing a sprite review with some feedback and examples in the next day or so, just a heads up!

**Comment by colossusqw** [comment]
> i like the old sprites a lot more because they have a lot more contrast and aren't mushy
> 
> See: ice in the game looks like this image

Is this an issue specifically with the ice spiders or with all of the sprites? I can definitely change the color palettes for more readable contrast in them either way.

**Comment by colossusqw** [comment]
Some extra images of spiders ingame for accessing what could use change and whatnot:

**Comment by flappybatpal** [comment]
Quite like the newest ones, they have more similarity to the current sprites.

**Comment by Glamurio** [comment]
Absolutely love the way they turned out.

**Comment by colossusqw** [comment]
An update on the spider color flavors
image

**Comment by ZeWaka** [comment]
could you put an updated image in the OP?

**Comment by colossusqw** [comment]
> could you put an updated image in the OP?

Alrighty!

**Review by Gannets — APPROVED** [review]

**Pull request merged**
