### PR TITLE
Handgun belts show if they hold a gun or not

### PR DESCRIPTION
**Pull request by flappybatpal**
[QOL][BALANCE]

## About the PR 
Nuclear Operative pistol belt sprites display if they contain a pistol.
Sprites hacked up by me, apologies to creators.

image

## Why's this needed? 
I didn't like having a belt showing a weapon it didn't contain.
This adds a another var based on can_hold to only accept exact types. Seems pretty useful to me!
Balance wise the only difference is that you can no longer put a smartgun in a pistol holster, although I feel this is a minor change as you were already unable to do the opposite because of paths.

## Changelog

```changelog
(u)Flappybat
(+)Nuclear Operative pistol belt sprites show if they contain a pistol.
```

### CODE REVIEW

**Comment by Gannets** [comment]
thank

**Review by Tarmunora — COMMENTED** [review]
Seems like there'd be some weirdness if you had 2 guns in one belt, but otherwise looks fine

**Comment by flappybatpal** [comment]
> 

The way it's coded is to show the gun in the holster if there is at least one present. Little weird having three guns in one holster and only showing one but we allow that already.

**Comment by DimWhat** [comment]
Does this effect the worn sprites?

**Comment by flappybatpal** [comment]
Nope

**Pull request merged**
