### PR TITLE
Remove infiltrator from syndicate vendor

### PR DESCRIPTION
**Pull request by keiyakins**
## About the PR 
Remove infiltrator from the syndie vendor

## Why's this needed? 
I have literally never once seen an infiltrator not just ruin the round by
being spotted early. Removing it will make nukie rounds more competitive.

## Changelog

```
(u)CodeDude:
(*)Removed infiltrator from the Syndicate loadout vendor
```

### CODE REVIEW

**Comment by TTerc** [comment]
Infiltrator isn't about disguising and infiltrating, it's about being a ninja with a cloaker and a tranq gun. This is a really bad idea overall
If you want to limit nukies going stealth, remove DNA scrambler instead

**Review by Gannets — CHANGES_REQUESTED** [review]
I'd be interested to see what other players think about the current state of the infiltrator class, hopefully the forum discussion thread will yield some useful feedback.
That aside, I don't think blanket removal of a class is a solution to your stated problem, better to improve the existing item set or retool it to fit a different role. 
Besides, there is nothing stopping any operative from leaving the Cairngorm at roundstart and revealing the rest of their team immediately and this PR does not address that.

**Comment by comradef191** [comment]
@keiyakins you need to credit your changelog

**Comment by Kyle2143** [comment]
This should not be merged. For one thing, I have seen many usages of the infiltrator being used effectively, though I wish their cloaker was a bit more interesting.
Things like this should generally try to be worked out before being removed completely. This feels like someone made a knee-jerk PR which is obstensibly against our rules since it is on the suggestion forums.

**Comment by UrsulaMejor** [comment]
The infiltrator is a great class for cloaking and shooting in the middle of intense firefights from unexpected angles. Tranq darting the crew from behind their lines and slipping away. It's a powerful combat option.

The infiltrator might not be the best at, well, _infiltrating_, but it's an extremely good class when used well.

Flukies are half the fun of nukies. Learn to laugh at yourself.

**Pull request closed without merging**
