### PR TITLE
Adds 3/4 Gannets Doors

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
Changes the old Gannets doors to modern day perspective standards
image

## Why's this needed? 
This will open new pathways for mappers, and help everyone look at things from a new perspective!

### CODE REVIEW

**Comment by cheekybrdy** [comment]
image

**Comment by cheekybrdy** [comment]
image

**Comment by cheekybrdy** [comment]
image

**Comment by flappybatpal** [comment]
Fantastic!

**Comment by ZeWaka** [comment]
can you put screenshots of them being used ingame in the main post

**Comment by cheekybrdy** [comment]
there is 1 non perspective related change here that I'd like input on, while the non full blue one is a red cross with a blue background instead of white so I've left it as is, I've changed the full blue medical door's cross colour to pink as it had a white background to change it to be appropriate, input is wanted on that change.

**Review by ZeWaka — APPROVED** [review]

**Pull request closed without merging**
