### PR TITLE
Replaces a room on kondaru.

### PR DESCRIPTION
**Pull request by SirSnek**
## About the PR 
It replaces one of the crew quarters' contents with something that toes less on breaking rule 4. You can now find a crumpet, some tea and fancy clothes in that location.

## Why's this needed? 
Right now this room is very suggestive to say the least and I highly doubt that we need any of that anywhere close to goonstation.

### CODE REVIEW

**Comment by Kubius** [comment]
....It's a maid's room. Like, a person who tidies things up and organizes them, gets everything all neat. If you glean something suggestive from it, I kinda feel like that's on you? If there's wider sentiment that it comes across a little weird, I wouldn't mind it being replaced, but the intent was "cute".

**Comment by SirSnek** [comment]
If it was just a maid dress + headwear and spray bottle I'd understand it but combined with the hearts in the room you can easily get a different view of it. Also the keeping things tidy bit doesn't come across at all because the hearts use randompos and the posters are just randomly thrown around the walls and they often clip over one another. If you really want to keep it this way I'd suggest replacing the hearts with something else or making them not use randompos so it gets your point across.

**Comment by Kubius** [comment]
Would you be alright with closing this and I'll tidy up the room in a subsequent PR / change set?

**Comment by SirSnek** [comment]
Completely fine with it but if you'd me like to I can make alternative changes that are more like what the room is now. Comment again with what you'd like me to do.

**Comment by SirSnek** [comment]
I decided to make the changes now as I had the time and was in the mood. 
New version of the room as can be seen here:
maid room v2

Oh and I'd like to apologize for my attitude, I didn't mean to sound accusatory if I did and looking back at it the room isn't all that bad but I am a little on the hypersensitive side when it comes to seeing things that might rub people the wrong way. I think this new version is a good middle ground as it makes the room more interesting and tidies it up.

**Review by Kubius — APPROVED** [review]
Teacup could maybe be moved up a bit, but that's just a bit of fussiness. I'm down with it overall.

**Pull request merged**
