### PR TITLE
Adds DECON DESTRUCT and was_deconstructed_to_frame to several machinery

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Prevents objects from still working while inside there frames, fixes bugs. (To explain a little bit further, decon destruct saves items in frames by there path instead of the object itself, this prevents things like Stompers being set to auto and being deconstructed still stomping even though it got deconstructed.)

## Why's this needed? 
Bug fix

### CODE REVIEW

**Comment by penny64** [comment]
A couple points
Chemicompiler will forget all of its programs and destroy everything in it
Furnaces will have their fuel destroyed

I'm not sure this is actually bad, but I didn't do it originally as I thought it would be bad UX

**Comment by pali6** [comment]
Agreed with Penny I think. I'd prefer if stopping these machines was handled through `was_deconstructed_to_frame` and `was_built_from_frame` instead and/or by adding `!istype(src.loc, /obj/item/electronics/frame)`.

**Review by ZeWaka — APPROVED** [review]

**Comment by ThatFiveGuys** [comment]
> Agreed with Penny I think. I'd prefer if stopping these machines was handled through `was_deconstructed_to_frame` and `was_built_from_frame` instead and/or by adding `!istype(src.loc, /obj/item/electronics/frame)`.

Done for furnaces and chemicomplier! Dont see any reason to change stomper to do it as it wont make any difference.

**Comment by pali6** [comment]
What about plantpots? Currently this will destroy plants and reagents in the plant pot.

**Comment by ThatFiveGuys** [comment]
> What about plantpots? Currently this will destroy plants and reagents in the plant pot.

Intentional, this is done mostly for rafflesia, radweed could probably be abused too for this.

**Comment by pali6** [comment]
Hm. What if you made it so plant pots can only be deconstructed when plant-free and give you a message otherwise?

**Comment by ThatFiveGuys** [comment]
Would be good, ill look into it later.

**Comment by ThatFiveGuys** [comment]
Plant pots now destroy plants when deconstructed, dont think this would cause much frustration as like, how many people deconstruct plant pots to transport them.

**Review by pali6 — APPROVED** [review]

**Pull request merged**
