### PR TITLE
Adds 4 Bee-Related Secret Chems

### PR DESCRIPTION
**Pull request by Zonespace27**
[FEATURE] [SECRET]

## About the PR
This PR adds 4 new secret chems, all of which are bee-related, with the proportions of said bees getting larger, and each tier of the chem requires the last tier, plus other chems.

Adds: (Thank you RealB for the name)
Be-Bee: Infects you with Bee Fever, eventually turns you into a bee (akin to featherfluid/sheltestgrog, as are all of the rest)
Royal Be-Bee: Infects you with Royal Bee Fever, makes you a queen bee.
Royaler Be-Bee: Infects you with Royaler Bee Fever, which makes you a large queen bee.
Royalest Be-Bee: Infects you with Royalest Bee Fever, which makes you (to quote the code) an omega queen bee.

All of the infections can be cured by consuming garlic juice, since bees (apparently) don't like garlic.

## Why's this needed? 
There already is all sorts of critter conversion chems, and the bee critter's been sitting in the code, mostly unused, for a good amount of time now. In addition, I'd like to see bee critters be consistently playable, in some way.

Side note, since the chems are (hopefully) going in the secret submodule, their recipes are not in this PR.
## Changelog

```changelog
(u)Zonespace
(*)Adds 4 new bee-related secret chems, the hints for them are in the Minor Changes section.
(+)Be-Bee: Think about all sorts of bee-related things, and give them a mix.
(+)Royal Be-Bee: It's all in the name.
(+)Royaler Be-Bee: Think about some potent bee-chem, and try mixing it with the previous incarnation of Be-Bee.
(+)Royalest Be-Bee: Take an even more powerful bee-chem, and mix it with the former tier of Be-Bee.
```

### CODE REVIEW

**Comment by Zonespace27** [comment]
Figured out a vastly better way to handle PRing it, sorry about having to make a second PR!

**Comment by DimWhat** [comment]
Mirror post: Player bees? That's illegal!

**Comment by Zonespace27** [comment]
> Mirror post: Player bees? That's illegal!
> 
> Jokes aside, when a player is turned into a bee it eventually turns them into a wasp.
> And these chems aren't very secret due to you making them a PR instead of talking with a dev.

The chems themselves are not secret, the recipes, which aren't in the PR, are.

**Comment by DimWhat** [comment]
You stayed a bee because you are an "admin" on a test server.

**Comment by Zonespace27** [comment]
> You stayed a bee because you are an "admin" on a test server.

Ah shit, forgot about that

**Comment by mordent-goonstation** [comment]
Bees are sacred. 👎

**Comment by Camryn-Buttes** [comment]
Honestly, no matter how obscure or difficult the recipe is, it won't be sufficient to balance such a powerful effect.

There's a good reason why player controlled bees are limited to the wizard poly pool and admin shenanigans.

**Comment by Kyle2143** [comment]
Uhhh, players aren't supposed to be able to play as bees...

**Comment by Flaborized** [comment]
no player bees imo

**Comment by penny64** [comment]
I'm too new to truly understand why but my bones say players shouldn't bee bees

**Comment by Zonespace27** [comment]
Closed, because the world doesn't seem ready for player bees yet.

**Pull request closed without merging**
