### PR TITLE
Readds dwarves

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
This PR readds dwarfism as a regular bioeffect (and not a mutantrace). This means that it is now also (sorta) compatible with using a mutantrace. As a consequence the thermal resist has been removed from the mutation. Miners keep their 20% chance of starting as dwarves and the oddjob hat now adds and removes dwarfism properly.

The dwarfism effect is now achieved through precise distortion effect applied onto the base mob which means that most likely no dwarf-specific clothing is required. (Specifically the effect sorta just removes a few pixel rows in the leg area to mimic the human-resprite dwarf sprite.)

dreamseeker_pjLHU1f7Ix
dreamseeker_T0uFDivH85
(note: I did some reckless mob copypasting when making the examples above which caused mild issues, I think the feet on the right-facing sprites in the first screenshot are slightly off from the actual product but I'm too lazy to redo the demonstration screenshot properly 😩)

## Why's this needed? 
I think there's no harm in keeping dwarfism as it was only removed due to mismatched sprites.

## Changelog
```changelog
(u)pali
(*)Dwarves are back! Better than ever!
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
very pog

**Comment by MatheusIsNotAvailable** [comment]
Pog PR

**Comment by TTerc** [comment]
poggers indeed

**Comment by MatheusIsNotAvailable** [comment]
A trait would just be extra bloat, something like a job reward would be better

**Comment by DimWhat** [comment]
I would prefer this to not be a trait. Keep it as a goofy thing for genetics to discover.

**Comment by Tarmunora** [comment]
> 
> 
> Some people seem to be dissatisfied with 20% dwarf miners. I'd like to hear some opinions about that. Should it perhaps be moved to a zero-cost trait instead?

trait... bad

**Comment by Sord213** [comment]
Miners sometimes spawning as dwarves is great. Do not remove. Great job on this, pali.

**Comment by Flaborized** [comment]
Happy to have been proven wrong, looks great!

**Comment by Eagletanker** [comment]
> Some people seem to be dissatisfied with 20% dwarf miners. I'd like to hear some opinions about that. Should it perhaps be moved to a zero-cost trait instead?

It’s annoying and should be taken out entirely. It’s not fun trying to get genetics to pay attention to you and then revert you back to your normal body, and I don’t know about other mutraces but it might convert people from what their mutrace was into a human

**Comment by pali6** [comment]
> 
> 
> > Some people seem to be dissatisfied with 20% dwarf miners. I'd like to hear some opinions about that. Should it perhaps be moved to a zero-cost trait instead?
> 
> It’s annoying and should be taken out entirely. It’s not fun trying to get genetics to pay attention to you and then revert you back to your normal body, and I don’t know about other mutraces but it might convert people from what their mutrace was into a human

If you actually read the PR or at least looked at the screenshot you'd know that's not the case.

**Comment by Eagletanker** [comment]
> > > Some people seem to be dissatisfied with 20% dwarf miners. I'd like to hear some opinions about that. Should it perhaps be moved to a zero-cost trait instead?
> > 
> > 
> > It’s annoying and should be taken out entirely. It’s not fun trying to get genetics to pay attention to you and then revert you back to your normal body, and I don’t know about other mutraces but it might convert people from what their mutrace was into a human
> 
> If you actually read the PR or at least looked at the screenshot you'd know that's not the case.

Ah let me adjust that Sentence, was meant to refer to it before.

**Pull request merged**
