### PR TITLE
Polishes rand item spawners, adds #'ed versions

### PR DESCRIPTION
**Pull request by Tenryumi**
## About the PR 
This gives a unique sprite to each item spawner, and adds to each a variation that lets you choose how many of that item category you want to spawn.

(Ignore the stuff surrounding the spawners it's just donut3 stuff)

javaw_2020-04-23_00-41-08

javaw_2020-04-23_00-49-23

## Why's this needed? 
It makes using these a lot easier as you have a visual showing what a spawner creates, and gives mappers more control over spawners by letting them choose how many to spawn.

### CODE REVIEW

**Comment by Tenryumi** [comment]
Oh, sure! Force of habit at this point.
Also, I can add a Map Guidelines entry!

**Comment by Tenryumi** [comment]
image

There we are!

**Comment by ZeWaka** [comment]
> There we are!

The actual used ones that are here on GitHub, not the mirror (unsure why it exists, since links are a thing) on the wiki.

https://github.com/goonstation/goonstation/blob/master/.github/MAP_GUIDELINES.md

**Comment by Tenryumi** [comment]
> 
> 
> > There we are!
> 
> The actual official used ones that are here on GitHub, not the mirror (unsure why it exists, since links are a thing) on the wiki.
> 
> https://github.com/goonstation/goonstation/blob/master/.github/MAP_GUIDELINES.md

Oops... and that's why I didn't actually add that change and only had it in preview form, haha.
I did not know that guidelines file was a thing, my bad. I'll add it to that then!

**Comment by mordent-goonstation** [comment]
I like the idea, but think the implementation of having spawners for specifically 1 to 7 things (or less, in a few cases) is a bit odd.

If the intent is to prevent RNG from either flooding a room with items or having them be extremely scarce (I personally find the slight boom/bust nature of what you can find in some of the rooms to be interesting as it changes the dynamic of that room a bit for that round, but I'm totally willing to acknowledge that sometimes that's not desired behavior), could this be simplified by having some more semantic subtypes (e.g. "few", "some", "lots") with appropriate min/maxes (varies based on the type of spawner - a "lot" of tools and a "lot" of guns don't have to be the same number)?

This comes from someone who doesn't do much mapping, so don't weight my opinion too highly here, it's just how I expected this to be done and was surprised when it wasn't, so figured worth raising.

**Comment by Tenryumi** [comment]
> 
> 
> I like the idea, but think the implementation of having spawners for specifically 1 to 7 things (or less, in a few cases) is a bit odd.
> 
> If the intent is to prevent RNG from either flooding a room with items or having them be extremely scarce (I personally find the slight boom/bust nature of what you can find in some of the rooms to be interesting as it changes the dynamic of that room a bit for that round, but I'm totally willing to acknowledge that sometimes that's not desired behavior), could this be simplified by having some more semantic subtypes (e.g. "few", "some", "lots") with appropriate min/maxes (varies based on the type of spawner - a "lot" of tools and a "lot" of guns don't have to be the same number)?
> 
> This comes from someone who doesn't do much mapping, so don't weight my opinion too highly here, it's just how I expected this to be done and was surprised when it wasn't, so figured worth raising.

No, the point you've raised is a great one! I made spawners that make a particular number of items because of how I want my different style of maintenance in Donut 3 to work, in that I would like for it to be worth it to go "dumpster diving" as it were, without an actual guarantee you'll find what you're looking for because the items spawn in such low numbers in each spot they go into.

However, I do very much like your suggestion! a vague number, like:

- "Maybe few": 0 - 2
- "Few": 1 - 3
- "Some": 3 - 5
- "Lots": 5 - 7

I like that idea very much too, and while it's not what I had in mind initially I'm gonna make that a thing anyway in case I or another mapper may want to use something like that!

**Comment by mordent-goonstation** [comment]
> I like that idea very much too, and while it's not what I had in mind initially I'm gonna make that a thing anyway in case I or another mapper may want to use something like that!

Sounds good! No reason they can't both exist.

**Comment by Tenryumi** [comment]
Also added a one-or-zero version, that either spawns one item or none at all!

**Comment by mordent-goonstation** [comment]
Outside the scope of this PR, just commenting as a possible extra bit of future work for anyone who wants to: might be nice if the sprites reflected the spawner's amount somewhat, so at a glance I can see that I'm potentially spawning a lot of things in.

**Pull request merged**
