### PR TITLE
Disables antag captains on classic

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BALANCE]
## About the PR 
Disables captains rolling antag on classic, bringing it back in line with RP.

## Why's this needed? 
After joining yet another round with a rampaging antag captain spawn-killing any secoffs who join, I'm finally convinced a role that spawns with AA, armour and a taser should not be able to roll antag. Also it will hopefully lead to captains being more trusted and therefore responsible (maybe?)

## Changelog 

```changelog
(u)LeahTheTech
(*)Captains can no longer spawn as antagonist roles.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
what if they could roll conspiracy

**Comment by frawhst** [comment]
My main concern with this is that it may lead to captains just becoming part of security, if they can never roll antag at all.

**Comment by TobleroneSwordfish** [comment]
I think that's okay honestly? If there's no HoS then the captain is functionally the head of the security department anyway, and defending the station should be a decent part of their duties.

**Comment by Xkeeper0** [comment]
honestly, fair.

one incredibly minor wording note: it's less that captains can no longer be antagonists and more that antagonists cannot be captains.

**Comment by ZeWaka** [comment]
what happen 2 captain traitor item then

**Comment by TobleroneSwordfish** [comment]
Oh umm, make it a trader item and give it to the nukie commander instead? It's just a very loud megaphone. Can also technically be bought by VIPs, regional directors and inspectors, but they're very rare traitor rolls. Oh and I guess admin-created traitor captains too.

**Comment by pali6** [comment]
This is not in any way gonna reduce the number of classic rampages.

**Comment by Sbmhawk** [comment]
The final evolution of secHOPs, hosCAPs.

**Comment by TobleroneSwordfish** [comment]
I'm just going to merge this now, classic has been noticeably better during the testmerge and I haven't seen any more sec-captains than usual.

**Pull request merged**
