### PR TITLE
Adds dwarves as a trait

### PR DESCRIPTION
**Pull request by mantwerp**
## About the PR 
Adds dwarves as a trait, available to be chosen from the character setup menu

## Why's this needed? 
Popular consensus on the forum thread https://forum.ss13.co/showthread.php?tid=19629

## Changelog

```changelog
(u)Mantwerp
(+)Adds a dwarf trait, available to be chosen from the character setup menu
```

### CODE REVIEW

**Comment by DimWhat** [comment]
I still stand adamantly against a dwarfism trait as ever. I do not want to see awkward looking player sprites on the station. Until mutantrace tails , awkwardly scruched clothing items that don't look smooth, inhands of a plethora of low hanging objects, and frankly any monkey in clothing.

On a second note, this is just a free buff to any player that takes this. They get 10% extra thermal resistances (heat and cold res) as well as getting the dreaded smaller player sprite (fewer pixels = harder to hit).
As is, I do not believe this trait should go in mechanically nor appearence wise. Being a rare bioeffect is a quite fine place for it currently.

**Comment by colossusqw** [comment]
> I still stand adamantly against a dwarfism trait as ever. I do not want to see awkward looking player sprites on the station. Until mutantrace tails , awkwardly scruched clothing items that don't look smooth, inhands of a plethora of low hanging objects, and frankly any monkey in clothing.
> 
> On a second note, this is just a free buff to any player that takes this. They get 10% extra thermal resistances (heat and cold res) as well as getting the dreaded smaller player sprite (fewer pixels = harder to hit). As is, I do not believe this trait should go in mechanically nor appearence wise. Being a rare bioeffect is a quite fine place for it currently.

i do agree that it as a no cost thing is unbalanced, however the amount of people that express their want to be able to be a dwarf whenever makes me feel it should be a thing.

**Comment by nefarious6th** [comment]
buff issues aside, less for genetics to interact with people is a Bad Feeling. I always feel like a station hero when I find dwarf and can put it in the booth for 10 credits

**Comment by Momoberry** [comment]
Honestly, out of the two things that were talked about, I was a lot more for the squid people over the dwarf. Dwarf has a lot of gameplay advantages without much theme, versus squid which is a lot more interesting to me. It's also what dim said, they just don't look that good, and really only humans can look decent with it. the mutantraces look pretty crappy.

**Comment by Sovexe** [comment]
does not pass the bar to be a selectable mutant race

Also I dont like the idea of further encouraging the use of displacement maps to butcher spritework outside of the rare occasion

**Comment by mantwerp** [comment]
Closing, since most seem to be against it now

**Pull request closed without merging**
