### PR TITLE
Allow players to deconstruct APCs

### PR DESCRIPTION
**Pull request by MeggalBozale**
[INPUT WANTED]

## About the PR 
Allowing more station objects to be removed by players is a good move. Fixes the rotation issues on deconstructing and then reconstructing player-built APCs as well.

## Why's this needed? 
Players can scan and build APCs just fine, but not deconstruct? Wierd.

## Changelog

```changelog
(u)MeggalBozale
(+)APCs can now be deconstructed.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Good pr! By the way, size tags are automatic, no need to add them manually.

**Comment by MeggalBozale** [comment]
Very cool, it worked. First PR, very smoll. Would anyone like to check if I messed anything up? And yeah I noticed about the tags, my bad lol

**Comment by MeggalBozale** [comment]
apcshow

**Comment by Bartimeus973** [comment]
Just a few thoughts. 

If this works the way i think it does, this instantly depowers the room and likely only requires simple tools you can find in a toolbox with perhaps a multitool added in. Which means that if you head into maintenance with those tools you could likely start depowering a whole bunch of places in a way that forces the crew to make more apcs with the mechanics. If there is no mechanic, or no one scanned an apc, it means you could blackout the station extremely quickly. I do like the idea of being able to deconstruct apcs in general, but i think it should require a lot more work and be slower/more noticeable than for any other machinery, considering how extremely important those things are.

**Comment by CrystalClover** [comment]
@Bartimeus973 
Pretty sure it requires a deconstructer, which is something that is not very easy to obtain as non-engineering staff

**Comment by MeggalBozale** [comment]
> Just a few thoughts.
> 
> If this works the way i think it does, this instantly depowers the room and likely only requires simple tools you can find in a toolbox with perhaps a multitool added in. Which means that if you head into maintenance with those tools you could likely start depowering a whole bunch of places in a way that forces the crew to make more apcs with the mechanics. If there is no mechanic, or no one scanned an apc, it means you could blackout the station extremely quickly. I do like the idea of being able to deconstruct apcs in general, but i think it should require a lot more work and be slower/more noticeable than for any other machinery, considering how extremely important those things are.

Yeah, I'd love to make it longer of a process but I'm not sure how. Currently, you need all 6 tools, a decon device, **and** access to the APC in the first place. Ill see what I can do about making the process more time consuming.

**Comment by Josephin23** [comment]
maybe make the lights malfunction and the objects display messages like "X's power is turning on and off rapidly!", that would be pretty noticable
anyway remember that if you don't know how balance this well you can add the [INPUT WANTED] tag, makes a forum which you can usually get a ton of tips from

**Comment by flappybatpal** [comment]
In my estimation this will probably will result in a lot of silent antagging that mechanics/engineers are slow to fix.
I don't really see how that would be an improvement over power cell removal/sabotage, I don't think the crew will be that responsive to fix this and the risk to the antags will be very low compared to the amount of disruption they can cause.

**Comment by MeggalBozale** [comment]
Yeah it looks like this got out of my skill level quickly. I expected this to be a simple learning project, but this is way over what I can do. I hate to close this but the proper implementation of this feature is just way harder than I thought it would be.

If I can do this later, and do it right, I will!

**Pull request closed without merging**
