### PR TITLE
Fixes critter hud slots not stacking correctly

### LINKED ISSUE #11490: Player controlled skeleton critters messed up UI
### Labels

[BUG]

### Description

Possessing a /mob/living/skeleton gives a messed up UI

### Steps to reproduce

1. Spawn skeleton critter
2. Possess it
3. UI is screwed up

### Expected Behavior

UI is not screwed up. Note skeleton commander and other critters like roaches seemed fine in testing.

### Additional Information & Screenshots

image

### PR DESCRIPTION
**Pull request by MetricDuck**
[BUG]
## About the PR 
When critters are given many HUD slots (like skeletons with their many head equipment slots) the slots are supposed to stack vertically when 6 or more are added from the left or the right.

Currently, this doesn't quite happen correctly due to some issues with the additive logic, the coords go:
-5,0
-6,0
-7,1
-8,2

This PR fixes the logic, making the coords go:
-5,0
-6,0
-6,1
-6,2

In addition, this PR also increases the number of horizontal slots before we start stacking vertically - from 6 either side to 9 either side. A gap of 1 space is left either side to account for storage containers (left side) and the leave pod button (right side).

See comments for pictures.

## Why's this needed? 
Fixes #11490

### CODE REVIEW

**Comment by MetricDuck** [comment]
Before PR:
image

**Comment by MetricDuck** [comment]
After PR:
image

**Comment by MetricDuck** [comment]
hang on

**Comment by MetricDuck** [comment]
After PR updated:
image

**Comment by MetricDuck** [comment]
Actually seeing this old comment that was removed in commit 0fecb237f73a85cd27a1cd0a847f24c95f534f87
image
 
I'm gonna extend the slots so instead of starting to wrap vertically from 6 either side they wrap from 9 on the left (to allow a column for storage) and 10 on the  right (flush with screen).

Critter huds don't have to account for TG layout as that's a human thing.

**Review by frawhst — APPROVED** [review]
Not well versed in HUD code but visually this is way better

**Pull request merged**
