### PR TITLE
Changes disabling sting for Changelings on RP Servers

### PR DESCRIPTION
**Pull request by nefarious6th**
[input wanted][rework][balance]
## About the PR
Looks to swap out the capulettium sting for changelings on the RP Servers for a crydaptus toxin sting that injects 40 units.

Crydaptus Toxin:
- causes blurry vision for the victim after 5 seconds
- causes slowed movement for the victim after 20 seconds
- causes weakness and blindness for the victim after 35 seconds that lasts for **2 minutes and 45 seconds**
- allows the victim to whisper while weakened but doesn't allow them to emote
- causes the victim to appear dead
- doesn't force status to "resting" to prevent sleeping-KOs, but could ?
- can be countered effectively with smelling salts like similar chemicals

Video of how it works/looks:
https://www.youtube.com/watch?v=azi7UVx6VPU&feature=youtu.be

## Why's this needed?
Would ideally drive more interactions between changelings and their victims and give the players the ability to still have conversations and such when they're being absorbed into a hivemind versus staring at the screen for two minutes while they wait to die. 

Revision fixes a bunch of stuff I didn't like about a pancuronium and capu+ combined sting. Retains capu+ as a separate non-knockout chem which is something people in #3184 said they liked; retains a longer knockdown duration than Capu and Capu+ without the loud LOSEBREATH from pancuronium that I think other people on the forum might've been worried about that making murdering on ling less viable because it was more obvious. Also more clearly ties the weakness time to the forced whispering time, since you can only talk normally after the final cycle of the chem starts. It's like a slightly more buffed capu+ which is also why I think having a chem recipe for it right now isn't necessary.

Comments out but does not remove the original capulettium sting. Also swaps the sting reagent IDs over to a list variable for all your multi-chem sting needs. Also fixes one little spelling error I found in one of the files for changelings (very, very trivial).

## Changelog
```changelog
(u)Nefarious6th
(+)Swaps the changeling's debilitating sting on the RP servers with a new crydaptus toxin sting that allows victims to whisper
```

### CODE REVIEW

**Comment by flrsh** [comment]
There were some changes to capulettium plus in #3184, most notably `When you have capu+ in your system, if you lay down, you'll have a dead examine text and you'll only be able to whisper. If you get up, your dead examine text will disappear and you'll be able to move and talk freely.`

**Comment by nefarious6th** [comment]
> There were some changes to capulettium plus in #3184, most notably `When you have capu+ in your system, if you lay down, you'll have a dead examine text and you'll only be able to whisper. If you get up, your dead examine text will disappear and you'll be able to move and talk freely.`

There's a small window where the pancu causes the kind of knockout that coupled with this makes it possible to whisper since it forces the person to "resting", though that window is not nearly as long as I would hope. Currently there's this kind of weird like 

1. "able to talk for 10 seconds while stunned" --> 
2. "able to whisper for about a minute while down" --> 
3. "not able to talk (because of LOSEBREATH) for like a minute/minute and a half while downed" --> 
4. "can talk freely for the last 30 seconds of being stunned" 

thing going on with it that I just...don't really like. I'm honestly thinking making a new chemical is just the way to go, since capu+ isn't giving enough coverage of the stun window for whispering and the LOSEBREATH gasping on pancu is really obvious and frequent. I could split the sting reagents into a "sting reagent 1" and "sting reagent 2" variable and then tweak the reagent amounts for each separately to get the right coverage of the capu+ whispering, but I don't think I'm going to resolve the stuff I don't like about pancuronium by just changing reagent amounts. 

I don't know enough about using chems as an antag to know what effects would be balanced for a new one, whether there needs to be an auditory indicator someone is dying or anything like that.

**Comment by nefarious6th** [comment]
Setting WIP on this to work on a custom sting chem; may switch it back to draft or something later too idk. Will work on new sting once I am back at my PC; I know what I want it to do, I just have NO idea about balancing, names or if it should have a recipe so 🤷 that all can come after

**Comment by nefarious6th** [comment]
If anyone has feedback on this, let me know; I took this out of draft a lil bit ago but I can't get the WIP tag off 😔

**Pull request closed without merging**
