### PR TITLE
Resprite 3006/Rifle clips

### PR DESCRIPTION
**Pull request by Conchuckter**
[SPRITES][GAME OBJECTS]

## About the PR 
Resprites both tranquilizer darts and 3006 clips to a fancy stripper clip.
image
image
The darts also have underlays based on their payload reagent.

## Why's this needed? 
New sprites good and cool. 

## Changelog

```changelog
(u)Conchuckter
(+)Tranquilizer darts and old hunting rifle clips have been resprited, they now look like stripper clips.
```

### CODE REVIEW

**Comment by BatElite** [comment]
Probably don't need to keep the old mags around, old sprites rarely find new use

Are the mutadone & halo darts still the same sprite then?

**Comment by Conchuckter** [comment]
> Probably don't need to keep the old mags around, old sprites rarely find new use
> 
> Are the mutadone & halo darts still the same sprite then?

Yes they use the same sprite

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
Good to see sprite updates, but please add (more obvious) outlines to these as per [our spriting guidelines here.](https://hackmd.io/@goonstation/docs/%2F%40goonstation%2Fsprites#Outlines-%F0%9F%96%8B) 👍

**Review by WALPVRGIS — APPROVED** [review]
Looks good to me!

**Pull request merged**
