### PR TITLE
Remaps Wizard Shuttle

### PR DESCRIPTION
**Pull request by Flaborized**
[FEAT]

## About the PR 

Remaps the wizard shuttle, resprites the wizard teleport computer. (And makes it glow in the dark) The important equipment is all still there, with the addition of a few gimmick-y wizard-themed additions. Also adds a phone to the shuttle, which should be way less of a big deal than the nukeop's phone, as wizards don't rely on being a surprise as much and could get some real fun gimmicks out of having one. Mostly a small mapping project to get me started on mapping so I can have a little experience and practice mapping in the future. Takes up the same amount of space as the current wizard shuttle in z2.

## Why's this needed? 

The old wizard shuttle's teleport computer was pretty poorly conveyed IMO. From what I saw, lots of wizards didn't make use of it and instead wasted their teleport scroll charges to warp into the station. This design has the computer more prominently displayed which will hopefully lead to more wizards using it. Other than that, I just prefer my version aesthetically and functionally.

Comments on anything I forgot to add or ideas for additions are welcome.

Pictures:

## Changelog

```
(u)Flaborized:
(*)Remapped the wizard shuttle.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
idea: different coloured lights, like the cool incandescent colorful ones?

**Comment by Flaborized** [comment]
The kitchen uses cool light tubes while the other bits use warm tubes, though maybe something a bit more abnormal would be more fitting?

**Comment by ZeWaka** [comment]
> something a bit more abnormal would be more fitting?

Yeah, that's what I was thinking. Wizards are pretty wacky in the lore iirc. Up to you though!

**Comment by Kyle2143** [comment]
I gotta say, I kind of liked the old wizard shuttle flooring. The yellow kind.

**Comment by pali6** [comment]
I'd also like the shuttle to look more wizardy.

**Comment by zjdtmkhzt** [comment]
Definitely agree on the old teleport computer not being obvious enough, making it more visible is a very good change!

**Comment by Flaborized** [comment]
I have a few changes I'm gonna make to make it more wizard-y 🧙

**Comment by Manly-Dwarf** [comment]
👍

**Pull request closed without merging**
