### PR TITLE
Allows Unconcious People to Hear Speech

### PR DESCRIPTION
**Pull request by frawhst**
[FEEDBACK] [PLAYER ACTIONS] [EXPERIMENTAL] [QoL]
## About the PR 
Does that thing. Lets unconcious people hear chat, see radio chat, and see maptext. May have some minor discrepancies (haven't tested with intercom maptext), because speech code sux.

## Why's this needed? 
Currently being put under for surgery, in a sleeper, getting knocked out by chemicals or N2O, etc etc etc all suck to experience because you're vastly removed from the round during them, and can't keep track of what's going on at all. This lessens that somewhat. 

Notably this gives a bit more power to people who are being knocked out and kidnapped or whatever, but that's such a low percent of all cases of being knocked out that, imo, this is by far a net good.

This is a very simple implementation, I'd be happy to introduce more intricacies to it if people would like.

```changelog
(u)aloe
(*)Unconscious people can now hear speech normally.
```

### CODE REVIEW

**Comment by frawhst** [comment]
It's been suggested to muffle the heard speech somewhat and only let unconscious people hear bits and pieces of what's being said (as in, "i am going to throw this guy into space" might become "... going to th ... this guy ... space" or similar").

will take a crack at implementing that sometime soon.

**Comment by DecidedlyUnethical** [comment]
Really don't like this; you're unconscious, you shouldn't be hearing dip. Already you'll have people jumping out of the cloner after dying, screaming on the radio "JOHN STAFFMAN KILLED ME IN XYZ, HE'S A TRAITOR"! You can't trust people not to meta with this. Also, people can full hear the radio while they're in cryo (not ghost cryo), not sure if that's an oversight or intended.

**Comment by PastaSpaghett** [comment]
Might help to make it so people in a grab are fully deafened while unconscious.

**Comment by Kyle2143** [comment]
> It's been suggested to muffle the heard speech somewhat and only let unconscious people hear bits and pieces of what's being said (as in, "i am going to throw this guy into space" might become "... going to th ... this guy ... space" or similar").

This is a much better way. Also I'd say it shouldn't tell you the name of who says what. Just that "a muffled voice says "blah...blah blah...bla".

**Comment by frawhst** [comment]
Going to be away for a bit so closing till then!

**Pull request closed without merging**
