### PR TITLE
Adds 6 pairs of overalls to the clothing booth as external suits

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
## About the PR 

What this PR does:

-This PR adds 6 new pairs of overalls to the game as external wear.

-They are: Blue, Grey, Black, Orange, Olive, and Red.

-Adds a new spacer section to the clothing booth (I intend on adding more soon to further flush out spacer culture)

-Moves dirty vest (shitty bill outfit) to the spacer section

Image of said overalls at various angles & various undershirts
image

## Why's this needed? 

These overalls can be worn over jumpsuits, allowing players to get more intouch with their spacer/country side. Most outfits that have overalls (plumber sets, podworker, construction sets, engineer set, etc) are already combined with a specific color, not allowing for a players job to be displayed if they want to wear overalls. Overalls intends to allow for the job to be displayed.

## Changelog

```changelog
(u)Yellow/myco
(+)Adds 6 pairs of overalls to the clothing booth under the new 'Spacer' section
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
I did see these but these were addressed towards brown or mock-brown overalls. That is why these were set to be different colors

**Comment by UrsulaMejor** [comment]
A late round rancher has the ability to summon a batallion of knights and lock you in an invisible mime cage while their posse beats you up

You need to be able to be like "Where the fuck is the rancher in this shuttle full of people, I need to beat the shit out of them"

the overalls are their trademark specifically so
1) They have a strong identity
2) You can easily identify them in a fight

Allowing overalls to the general crew
1) Reduces the rancher's overall based country identity
2) Provides color-differentiated false-ranchers (not everyone can resolve color easily!)

And most importantly, I just want to exercise my design right to say "This is a thing that belongs to this job, it's THEIR THING", because I like it when jobs have unique outfits, style, and reasons to play them. If you wanna be the country bumpkin, play the rancher.

**Comment by nefarious6th** [comment]
this got closed out too fast to comment when it was relevant, but fwiw, mechanics and engis both also have access to overalls too, and there was discussion some time back about allowing botanists to claim either an apron or overalls (probably prior to rancher being added).
would've liked to see these. overalls are my favorite mechanic look and i miss the hydro overalls from para

**Comment by UrsulaMejor** [comment]
It was closed fast because they were told repeatedly before,  during,  and after the process while they were posting WIPs of in imspriter that this pr would not be merged. This closure should be a surprise to nobody

**Comment by Yellow-Mushroom** [comment]
> It was closed fast because they were told repeatedly before, during, and after the process while they were posting WIPs of in imspriter that this pr would not be merged. This closure should be a surprise to nobody

I dont intend to get into a fight over this but this is not the case. Cal at 11pm 5/19 was the first one to bring up to me the fact that even though the colors do not match, it may still provide in issue, in which I tagged you asking about it, which did not get a response. These were made over a single day (5/18-5/19) process so I think you may be having me confused with someone else. 

I'm very confused on where those messages that the pr would not be merged are, if I'm really that blind or if this is a case of items being confused.

Also my follow up prior to the closing never got a response, since it is a better chance to get a response here:

I think this is of note. Rancher is not the only job with overalls, nor is it the only way to get overalls on station as there are 6+ other sets of overalls (11 separately) not including the rancher outfit. I can close out the PR if its a hard no to any new overalls, however, I believe I kept the colors very far from the base overalls, and the fact that they are an external suit, means that they would be worn over their original jumpsuit, keeping the job visibility of where they are, while adding on a custom flair

Although this PR is closed, I'd still be interested in perhaps having overalls be slightly involved in other projects in the future (in either jumpsuit/external fashion), and while its not definitive, is it just a hard no to any new overalls? Should something be done about the other 11 pairs of overalls available to station goers?

**Pull request closed without merging**
