### PR TITLE
Restrict monkey vendor access

### PR DESCRIPTION
**Pull request by flappybatpal**
[BALANCE]

## About the PR 
Adds three types of monkey vendor restricted to kitchen, medical locker or research access. Head access is also able to use any monkey vend.
Replaces existing map vendors with appropriate types.
Adds altered sprites and description to indicate the access level.

monkeyvend

## Why's this needed? 
Stop everyone vending the damn monkeys.
You can still hack the machine to dispense monkeys.

## Changelog

```changelog
(u)Flappybat & Dimwhat
(*)Due to increasing number of monkey uprisings the Valuchimp vending machines are now access restricted according to their station area.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
tentatively based, we could use a forum thread 😰

**Comment by Aivaria** [comment]
as monkey player im against this one. Sometimes geneticist help you turn you monkey, and then run off, without giving you an translator. Having to hack a Monkey Vendor, and then access the translator is already some work. Having an additional access barrier, might make accessing an translator an very difficult task.
This also possibly affects other monkey player. (Simply taking B as example, there are some more nice monkeys on RP)

**Comment by ThatFiveGuys** [comment]
if youre having to hack the vendor anyways, its very little effort to just cut the access wire as well as the hacking wire.

**Comment by ZeWaka** [comment]
So good

**Review by flrsh — APPROVED** [review]

**Comment by Confusedxoz** [comment]
Does this mean I can't use the monkey vendor in ther afterlife bar?

**Comment by flappybatpal** [comment]
> Does this mean I can't use the monkey vendor in ther afterlife bar?

The original unrestricted vendor type still exists. I just replaced ones on the current stations.

**Review by TTerc — APPROVED** [review]

**Pull request merged**
