### PR TITLE
Noslips no longer leave a trail and get dirty from blood

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Noslips will no longer trail blood behind them, and they will no longer get dirty from blood by walking on them.

## Why's this needed? 
It seems like good janitor quality of life, and it makes sense that the clean shoes wouldnt get dirty.

## Changelog

```changelog
(u)Ikea
(*)Galoshes and other noslips no longer get blood on them or leave trails of blood behind
```

### CODE REVIEW

**Comment by maybeserendipitous** [comment]
I always thought that it's not that the galoshes magically stay clean, it's that they have enough grip to not slip regardless of how dirty they are.

**Comment by ThatFiveGuys** [comment]
Actually they work by just repelling the blood through sheer cleanliness, source: I have a phd and masters degree in shoeology. Jokes aside having to constantly clean blood off yourself for the job who gets blood on them constantly is eh. More importantly though the thing that caused me to make this pr, with the addition of using mops in hand to mop the tile youre on, having to play the game of clean up all the liquid then inevitably have to do a little dance then clean that up just is eh.

**Comment by DimWhat** [comment]
This is a buff that these types of shoes don't need. Galoshes are already the powergame shoe and making people unable to be trailed would make it even stronger. This also doesn't feel like it makes any logical sense.

**Comment by ThatFiveGuys** [comment]
Echoing previous comments, if a quality of life change for janitors is what makes noslips truly op, then chances are it was op anyways. Whatever you do, the fact that it doesnt slip has been and will always be 99% of the draw towards these shoes, this change wont change that.

**Comment by ZeWaka** [comment]
Label your PRs.

**Comment by flrsh** [comment]
> This is a buff that these types of shoes don't need. Galoshes are already the powergame shoe and making people unable to be trailed would make it even stronger. This also doesn't feel like it makes any logical sense.

**Pull request closed without merging**
