### PR TITLE
Ephedrine autoinjector and pill

### PR DESCRIPTION
**Pull request by NightmareChamillian**
[QoL] [feature]
## About the PR 
Adds an ephedrine autoinjector to the porta nanomed and a pill to the normal nanomed. Also ups the number of formaldehyde syinges in the porta nanomed by 1.

## Why's this needed? 
I think it's a damn useful chemical, and since the last PR I made about it was shot down due to concerns about menthol, I felt it was worth revisiting. Also the nanomed keeps running out of formaldehyde.

## Changelog

```changelog
(u)NightmarechaMillian
(+)Added ephedrine autoinjectors and pills to appropriate medical vendors.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Label your PRs

**Review by Sord213 — CHANGES_REQUESTED** [review]
Could you also put a couple ephedrine pills in the public nanomed for sale?

**Comment by Tarmunora** [comment]
Not a fan of adding yet another stun-reduction/stimulant chem to nanomeds

**Comment by flrsh** [comment]
> Not a fan of adding yet another stun-reduction/stimulant chem to nanomeds

**Pull request closed without merging**
