### PR TITLE
Molly kondaru

### PR DESCRIPTION
**Pull request by Wisemonster**
[QOL]

## About the PR 
Adds mulebot navigation beacons across the station. Also moved the still in catering storage, removes a couple of chairs in the courtroom, and moves the location of an air injector in security, so that the mulebot can have a location to go in those areas

## Why's this needed? 
Currently, the mulebot doesn't work on Kondaru due to the lack of beacons. This allows it to work on Kondaru, for consistancy.

## Changelog

```changelog
(u)Wisemonster
(*)NanoTrasen has added the proper systems to Kondaru to allow mule bots to work! (mule bot included!)
```

### CODE REVIEW

**Review by Kubius — CHANGES_REQUESTED** [review]
Change requests:
- All beacons **in tiled-floor locations** should have the appropriate set of bot/caution decals.
- Engineering's MULE beacon should deliver east, to the tile next to the staff room's wall phone. The hangar is hard to reach "on foot" and already has a cargo endpoint.
- For Medbay's MULE delivery site, I would suggest the location the north sleeper currently occupies, with the sleeper being moved west. This keeps it clear of the primary traffic junction.
- Catering's MULE beacon should deliver to catering storage. Replace the south serving tray with an unload destination, and place the beacon east of it. Still should return to prior spot.
- I would recommend the escape wing beacon unload onto the floor directly east of the mail chute, south of the window between the two airlocks there. Beacon one tile south of that.
- Pod bay beacon could deliver to the spot in the hall-adjacent section with the light switch next to it.
- Courtroom does not strike me as a suitable MULE destination. If this is not a shared sentiment, the beacon should deliver south onto the tile north of the loudspeaker.
- Security should not have a MULE beacon. Cargo ingress is already handled through the south node.
- West crew quarters should not have a MULE beacon. It's the "arrivals" quarters and is served by nearby beacons already.

Ideas for additional destinations:
- Ranch (delivers east onto tile next to trash chute).
- Mercantile dock (delivers north onto the tile below the window between the entry doors).
- News office (delivers west onto the southwest-most tile of the main room).
- Pool (delivers south onto the southeast-most tile of the pool room).

**Comment by Wisemonster** [comment]
Alright, I've adjusted the locations to what I think you've asked for. Gotta figure out how to add custom locations for the ranch, pool, and news office, though. Might just be minor copy-pasting with a name change to get it to work.

**Comment by Wisemonster** [comment]
> Change requests:
> 
> * All beacons **in tiled-floor locations** should have the appropriate set of bot/caution decals.

Do the ranches dirt and news offices carpet count as tiled locations?

**Comment by Wisemonster** [comment]
Some concerns I discovered while testing

-The mule bot tends to take catering storage as a short cut when delivering to the east side of the station
-The mule bot, when returning to qm from the pod bay, will use the teg room as a shortcut
  -This also happens when going from the north-east crew quarters to medbay
-The mulebot will go through space when going from the east side of the station to the west side, specifically the middle area of the station where mining is. It doesn't git into any of the mining equipment, but I thought I should bring it up.

Besides the TeG ones, I'm not sure how severe the other issues are. Let me know which ones need to be fixed.

**Comment by Kubius** [comment]
* Ranch dirt and news office carpet do not count as tiled.
* Catering storage as a shortcut is a problem *if* it then proceeds into the kitchen or bar.
* I would be hesitant to remove catwalks, but it's OK if it's entirely redundant sections like the small "porch" by the routing depot.
* Routing through space isn't preferable, but may not be avoidable; it's feasible that the inner airlocks could get door-linked forcefields on general principle.

**Comment by Wisemonster** [comment]
>     * Catering storage as a shortcut is a problem _if_ it then proceeds into the kitchen or bar.

Unfortunately, that is exactly what happens. Besides coding in waypoints that the mule bots can use while going to destinations, I can't really fix this with the mule bots current east-side destinations. (Besides the bridge and chapel)


>     * I would be hesitant to remove catwalks, but it's OK if it's entirely redundant sections like the small "porch" by the routing depot.

The catwalk in question was this one (highlighted tile was originally a catwalk, not just a support.)

**Comment by Kubius** [comment]
Yeah, losing that catwalk is reasonable enough.

Not sure what can be done about the eastern destinations; the civilian destinations in crew quarters or pool could be skipped, but escape is a little more useful. Can you scribble the problematic routing over a map screenshot in Paint or something, to get an idea of how it moves?

**Comment by Wisemonster** [comment]
The deliver path is in yellow, and the pink is the difference when it returns to cargo.
2022-02-27 (2)_LI

That yellow part that goes into the wall was just my hand twitching, it normally just goes through the router.

**Comment by Wisemonster** [comment]
The new cafeteria location works fine. Unfortunately, the suggested new escape location causes the mule bot to use security as a short cut. Gonna test out some locations in escape to see if I can find a good spot.

**Comment by Wisemonster** [comment]
Ok, so I found out that by adding a door to the Aviary, the mule bot will stop using security to reach escape, and will instead use the bridge's Network Chamber to reach escape. It returns using the arcade. Not sure how much of a problem this is, if it's a problem.

**Comment by Kubius** [comment]
Routing through the network chamber is less than preferable, but it's better than Security by a wide margin. IMO, delivering to either of the east crew quarters directly isn't all that important, and I have a few more ideas for Escape destinations that might lead to a better routing path:

- West of the charging bench (south of checkpoint), delivered from the west.
- North side of the south arm entry doors (sort of like the last attempted position, just the other side of the doors).
- Site of the chair above the television (remove both chairs there), delivered from the north or east.

**Comment by Wisemonster** [comment]
Ok, so I've tried some of your recommended locations, and they all either take a shortcut through the kitchen, the network chamber, or security. However, I've done a bit of testing and found a possible path.
2022-03-04_LI
If I make a path between these two locations, using the location above the south wing doors as a delivery location, the mulebot will path through the arcade instead of the network chamber. May be usable, but I'm not sure how much the blown out crew quarter room is important to the character of Kondaru. If it's not too important/beloved, I could make a path between these two areas, adjusting maint to take this into account.

**Comment by Kubius** [comment]
Don't think I like that very much. 2 options from here:

- Go through network chamber.
- Skip escape for now, and if there's really a desire for delivery to Escape I can add a belt hell endpoint there.

I'm OK with either.

**Comment by Wisemonster** [comment]
I don't think having it go through the network chamber is a good idea, considering there's an AI reset board and upload board in there. I'll just go with removing the escape and crew quarters destinations.

**Review by Kubius — COMMENTED** [review]
Looking pretty good overall, but there are a few residual tiling goofs from spots where MULE destinations were added and then removed. Once those are fixed, should be good to go.

**Comment by Wisemonster** [comment]
I think I fixed all the residual spots. Bit difficult to tell, but I did get the ones in crew quarters.

**Comment by Kubius** [comment]
They're not showing up on the mapdiff anymore, so you have to have gotten it right. One final bit of tiny detail, but I think the chapel delivery might be more suitable dropping off at one tile west of the printer (room remains wood), as that's not in the path to the confessional room.

**Review by Kubius — APPROVED** [review]
Visually, a few remaining qualms: Medbay sleeper should face east or west (so people operating the sleeper could feasibly reach the control console), blue tiles in bar that are no longer under bushes should be regular bar floor.

Functionally, ready to roll. I'm not sure how I feel about the Hydro destination, but I think you should err on the side of including it, as it should be pretty simple to remove if it ends up causing trouble.

**Comment by Wisemonster** [comment]
Yea, the sleeper is supposed to be facing south, but apparently sleepers don't have a south facing sprite (that or it's bugged).

**Comment by Wisemonster** [comment]
Did you also want the blue tile under the vote box changed?

**Comment by Kubius** [comment]
Works either way. (Probably not?)

**Review by Kubius — APPROVED** [review]
MULE time!

**Pull request merged**
