### PR TITLE
Resprites lattices, catwalks

### PR DESCRIPTION
**Pull request by Flaborized**
## what? 

Resprites lattices and catwalks, the kind that go out in space on the solar arrays. (not the donut 3 ones but maybe someday) Also 'catwalk support' turfs which go under catwalks, they look like a lattice.

## why? 

I don't like the current sprites, I think these versions have a bit more depth and look better.

## Changelog

```changelog
(u)Flaborized
(+)Resprited lattices and catwalks.
```

### CODE REVIEW

**Comment by Adharainspace** [comment]
pog

**Review by ZeWaka — APPROVED** [review]

**Comment by Sovexe** [comment]
what about the corroded and melted icon states

**Comment by Flaborized** [comment]
> what about the corroded and melted icon states

as far as I know these are unused? i can update them if they actually are though

**Comment by Sovexe** [comment]
> > what about the corroded and melted icon states
> 
> as far as I know these are unused? i can update them if they actually are though

attacking a catwalk with a lit welder will get you melted, acid for corroded.

image

**Comment by Flaborized** [comment]
shit! ill update that tomorrow probably

**Comment by Flaborized** [comment]
I have made the things

**Comment by Sovexe** [comment]
image
is this one correct? It looks like the shapes of the new one might not be including some of the older shapes

**Comment by Flaborized** [comment]
> image
> is this one correct? It looks like the shapes of the new one might not be including some of the older shapes

yea those were a bit messed up! i meant for them to be closer to original (though there's no bars on the inside for the catwalk supports: i think those make it look busy unnecessarily)

**Review by Sovexe — APPROVED** [review]

**Review by Gannets — APPROVED** [review]

**Pull request merged**
