### PR TITLE
Help messages for in-game things

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
This lets atoms define `help_message` which is analogous to `desc` except it's displayed when you alt+doubleclick a thing. This is intended to give short instructions on how to interact with a thing (i.e. what tool does what).

This is also available by right-clicking a thing and selecting *Help*, this is only present on items which actually have a help message. Clicking the Help verb in the Command tab or typing Help into the command bar shows you both instructions on how to use it and also a general message informing you about the wiki guide and F1 / F3. I consider this to be a good idea considering that a brand new player might type `help` into the command bar or click the (somewhat non-obvious) Help button in the verbs list. (I tried to make the verb name be bold there but no luck.)

As an example this PR implements the help message for disposal pipes. The expectation is that subsequent PRs from the community or from me will add similar help messages to as many relevant objects as possible.

The help messages can also be dynamic (i.e. a project with several phases of construction can show a different message based on what phase it is in).

Example of the help messages when alt+doubleclicking:
dreamseeker_b13NnZDcLe

The base help message you get when you just click Help:
dreamseeker_sJlv85huHQ

Right click menu option (only present if the object has a help message):
dreamseeker_xwp2nhKLAc

Light mode:
dreamseeker_kJJYz12Die

## Why's this needed? 
Many interactions are somewhat obscure, nonintuitive and hard to remember not only for new players but also for seasoned veterans. Whether it's deconstructing a reinforced wall (which has this sort of help already in its description) or building a custom vending machine or perhaps building a pod most players check the wiki which shouldn't generally be necessary in an ideal world. This is a step in that direction.

In addition to that this should also help with players adapting to the constant stream of new features for which even the wiki documentation tends to lag behind.

## Changelog 

```changelog
(u)pali
(*)You can now Alt+Doubleclick things to see a help message on how to use them. So far this is only implemented for a few things (disposal pipes) but expect this to be more widespread in the future. (Rightclick + clicking Help also works.)
```

### CODE REVIEW

**Comment by pali6** [comment]
Possible extension idea: Provide a macro framework for writing stuff like `[HELP_LINK("wrenching", TOOL_WRENCHING)]` instead of writing `<b>wrenching</b>` and then write code which lets people click these help links to do stuff directly. I.e. clicking the **wrenching** link would find a wrenching tool in your backpack / belt / pockets / hands, put it into your hand and click `src` with it.

**Comment by flappybatpal** [comment]
Idea good, will review.

**Comment by pali6** [comment]
People have criticized the choice of alt+doubleclick which I agree is unorthodox. I have received an alternate suggestion of hold F3 + click (with holding F3 also turning your cursor temporarily into a mentor mouse 🐁) but that is just a bit of a pain to code as our keybind system only supports keypresses and not key releases. Anyway I think that the fact that `help` is in the right click menu is a decent way for players to find it and I feel like most people criticizing the keybind were overlooking that so I'm gonna let it stay at alt+doubleclick for now.

The other criticism was that people wanted the help to be more IC and in regualr description but I mostly disagree with that. I prefer clarity and function over aesthetics. Also having this be a separate thing lets us put more words there while descriptions should be kept short.

Let me know if you have any further issues with this PR as I will likely be self-merging it later.

**Comment by BatElite** [comment]
Bless you pali

**Pull request merged**
