### PR TITLE
Removed tons of right click interactions and replaced them with tool interactions

### PR DESCRIPTION
**Pull request by AwkwardDryad**
[QOL][ENHANCEMENT][PERFORMANCE]

## About the PR
//some rotation verbs for unused things were removed as well for a potential server and client performance increase. Additionally, I fixed some code formatting to make it a little more readable.

- All mech comp components can be modified by clicking them with a multitool instead of right clicking with a multitool in-hand
- !Most! object rotation is handled with a crowbar now instead of right click (pipes, mech comp components, etc.)
- Fixed layering on atmosphere shield so you can actually click the freaking thing
- Rebound atmosphere shield Range and Power functions to a mutitool interaction.
- Alphabetized mech comp vendor

## Why's this needed?
- All verbs must die :heart: 

## Changelog
```
(u)AwkwardDryad:
(*)All MechComp components can be modified by clicking them with a multitool.
(*)Most object rotation is handled with a crowbar instead of right clicking (windows,pipes,etc.)
(+)Atmosphere shields can be clicked while activated and their range and power settings are accessed by clicking them with a multitool.
```

### CODE REVIEW

**Comment by Tenryumi** [comment]
good job
he would be proud
image

**Comment by UrsulaMejor** [comment]
Requiring tools (especially multitool) for atmos shield is bit weird considering that, like meteor shields, they're emergency response things that Assistants should be able to use after grabbing them from maint or having them ordered from QM.

As a general thing, I don't think that the basic game experience should *expect* the user to have tools all the time.

Mechcomp is fine. 

Considering that you can rotate pipes and windows by pulling them around, it's weird to require a crowbar to turn them in place. What about using click drag instead?

**Comment by AwkwardDryad** [comment]
> Requiring tools (especially multitool) for atmos shield is bit weird considering that, like meteor shields, they're emergency response things that Assistants should be able to use after grabbing them from maint or having them ordered from QM.
> 
> As a general thing, I don't think that the basic game experience should _expect_ the user to have tools all the time.
> 
> Mechcomp is fine. Mechanics and engineers can be expected to have a full toolbelt
> 
> Considering that you can rotate pipes and windows by pulling them around, it's weird to require a crowbar to turn them in place. What about using click drag instead?
> 
> edit: actually, does click with empty hand actually do anything for pipes? would it be too weird just to have that rotate them?

i think i didn't explain this well. You modify the settings of the atmosphere shield with a multitool, you can still turn it on and off by hand.

Tool rotation is just for faster, precision rotation as you can still move things around by pulling them.

I didn't bind it to an empty hand because it's too inconsistant.

**Comment by UrsulaMejor** [comment]
> you can still turn it on and off by hand.

Ah that's fine then. I can't remember the last time I wanted to change the settings on those things

everything else makes sense to me. I still find it a bit weird to need a crowbar but overall this shouldn't affect most use cases

**Comment by AwkwardDryad** [comment]
> > you can still turn it on and off by hand.
> 
> Ah that's fine then. I can't remember the last time I wanted to change the settings on those things
> 
> everything else makes sense to me. I still find it a bit weird to need a crowbar but overall this shouldn't affect most use cases

Mainly the crowbar was the tool with the least interactions, so it was easier to universalize without changing too many existing interactions or making new tools to carry around.

**Comment by flrsh** [comment]
Spacing changes like changing `if (blah)` to `if(blah)` make it difficult to find your actual code changes. Please don't change lines just to change spacing.

**Pull request merged**
