### PR TITLE
somewhat balances (?) and brings back construction workers

### PR DESCRIPTION
**Pull request by mathis650**
[FEEDBACK WANTED]

## About the PR 

adds back construction workers, yay!

## Why's this needed? 

very few people wanted them gone, we need a role to fill in the gap left by the removal of conworker

## Changelog

```changelog
(u)matlap
(*) the construction worker is back from the grave
(-) he no longer has his RCDD
(+) but he has a shiny new yellow RCD, with 50 capacity, and the same cool door feature everyone loves!
(-) he also only starts with 100 rcd juice instead of 200. (2x 50 matter cartridges)
```

### CODE REVIEW

**Comment by DimWhat** [comment]
Welp, here we go.

**Comment by BatElite** [comment]
I'm guessing that's the label you were looking for, and not the "help wanted" one?
(FWIW I don't think - is a thing WRT the changelog, but it wouldn't need 4 entries anyway.)

**Comment by Carbadox** [comment]
i think itd be wise to leave CW changes on hold for a while

**Comment by geneva-breaker** [comment]
don't play these games

**Pull request closed without merging**
