### PR TITLE
Clarion Armory/HoS Rework

### PR DESCRIPTION
**Pull request by JORJ949**
[Mapping] [Rework] [Feedback]
## About the PR 
-Swaps around Armory and HoS office on clarion.
-Replaces empty corridor next to AI core with radio room and moves associated objects from bridge to there
-Changes Antibio crate outside of Armory to sec equipment access.
image

## Why's this needed? 
Armory foyer is incredibly cramped and situations in which Armory is needed multiple people will need in.
Empty corridor was weird.
HoS Office was also quite cramped but also fits better being between sec and bridge.
HoS now gets the proper mug.

## Changelog 

```changelog
(u)JORJ949
(*)Reworked Clarion Armory/HoS office
(*)Moved clarion headset crate to new "Radio Room"
```

### CODE REVIEW

**Comment by JORJ949** [comment]
Yes ive seen the random data terminal

**Comment by JORJ949** [comment]
Not sure whats different up and around the ring

**Comment by pgmzeta** [comment]
here's an in-game screenshot, might want to add to the thread/PR desc
image

is this area still supposed to be sticking out of the ai core area (per #18288)
image

armory wiring needs some tuning
image
west side wiring there isn't needed afaict
east/north side window-grilles should have power nodes under them to shock people

**Review by pgmzeta — CHANGES_REQUESTED** [review]
Couple of wiring tweaks needed around the armory, see other comment

**Comment by JORJ949** [comment]
> here's an in-game screenshot, might want to add to the thread/PR desc image
> 
> is this area still supposed to be sticking out of the ai core area (per #18288) image
> 
> armory wiring needs some tuning image west side wiring there isn't needed afaict east/north side window-grilles should have power nodes under them to shock people

This PR was made before my other one was merged, will fix that and wiring tomorrow

**Comment by JORJ949** [comment]
Loafer and wires have been fixed

**Comment by JORJ949** [comment]
FUCK

**Pull request closed without merging**
