### PR TITLE
Fixes poly/cluwne seeming castable whilst stunned

### PR DESCRIPTION
**Pull request by MetricDuck**
[BUG]
## About the PR 
Following #6380 polymorph & cluwneing around were given action bars. 

The action bars are interruptible by stuns, so whilst you can start the action bar while stunned it will nearly always fail at around 70% completion and put the spell on cooldown.

This PR adds an check+early return to cast(), preventing these spells from being channelled if the user can't act.

## Why's this needed? 
The spell should either be successfully castable whilst stunned, or outright uncastable whilst stunned (ie: like in a sanctuary, or with the teleport scroll). Suggesting to the wizard player it is castable with an action bar, then having it inevitably fail at around 70%, isn't good feedback to the player.

### CODE REVIEW

**Comment by MetricDuck** [comment]
Note: the victim can still walk away. Also option of adding an INTERRUPT_ATTACKED flag

**Review by ZeWaka — CHANGES_REQUESTED** [review]
why would this be castable while stunned intentionally lol

**Comment by MetricDuck** [comment]
> why would this be castable while stunned intentionally lol

i saw a coinflip and picked the easiest one to implement lol

The INTERRUPT_STUNNED flag has been restored, and an early return has been added for can_act to the cast() procs.

**Comment by flrsh** [comment]
Whilst is a cool word.

**Pull request merged**
