### PR TITLE
Completely redesign cogmap1 Mechanic's Lab

### PR DESCRIPTION
**Pull request by penny64**
[QOL]
## About the PR 

image
image
image

This builds the mech lab mostly up from the ground up
- Two ruck kits and manufacturer
  - High pop experience on Main 1 is the main factor
  - I enjoy the maps with two of them more in general, it's nice not to be on top of each other
- Equipment layout
  - Nothing in doorways or walking paths
  - Manufacturer and ruck kit positioned by the service window to encourage interaction!
- Data room
  - Some amount of defense from the greytide trying to get your gloves 
  - Data terminals, mechanics love em
  - Shutters on the outside windows, open by default to scream out "I'm doing crime!" to the world
  - Router window has no blinds, go take a peek at their secrets!
  - Electrified window still provides opportunities for crime
  - There's a camera
 - Expansion!
   - Windows as as an escape route from the combustion room
   - A table for socializing!
   - A packet sniffer and some snacks!
 - An actually reasonable number of tables
 - PC is loaded with FROG for connecting to DWAINE
 - Carts are loaded with equipment to compensate for less tables
 - Mule beacons instead of just a cargo pad
 - Added a phone so people can call in requests
 - Added some starting mats
 - A scanner because mechanics are frequent DWAINE users
## Why's this needed? 

Takes advantage of the space available, modernizing it up to standard with other newer maps and making the experience on highpop much more enjoyable and relaxed.

It also feels nice, and is cozy.
## Changelog

```changelog
(u)Penny
(*)Improves the layout of cog1 mechanic's lab and adds equipment and a data closet
```

### CODE REVIEW

**Comment by glassofmilk** [comment]
No more breaking into research to use their scanner!

**Comment by Flaborized** [comment]
This is a minor nitpick but I think this wall here will be a very prime spot for breaking into mechanics (welding the wall down specifically) and IMO having a poster covering it makes a bit more awkward then it needs to be

**Comment by penny64** [comment]
Nudged the poster to the left!

**Comment by Kyle2143** [comment]
Honestly I think the look is pretty good. And I think that the general map design philosophy to have an equipment room for a department is a good one. But I think that this change causes a problem for mechanics that wouldn't really be a bother for some other roles. Namely that it removes a bit of the mechanic's already limited "safe" space for experimentation, practice, testing mech-comp contraptions. Obviously not all mechanics offices are large, but it's nice when it has room and I think limiting their room further would cause issues.

I think that this design can still work, but maybe if instead of using the current space, you could expand the mechanics office to add more space and still have the equipment room. Either into the SMES room above or perhaps even a tile into the hallway below. Going further west would probably be challenging considering the belts.

**Comment by penny64** [comment]
@Kyle2143 honestly this is still of the most comfortable mech labs in existence but expanding up into an L shape into the SMES room would be pretty wonderful and I'm very down.

If I do this and anyone doesn't like it taking up so much space I can also just revert back to this

**Comment by penny64** [comment]
Now on draft for expansion please hold

**Comment by penny64** [comment]
And going out of draft

**Review by flrsh — CHANGES_REQUESTED** [review]
I prefer your previous iteration, where the mechlab didn't expand into the engineering room. It feels kinda awkward with how things are partitioned right now. Having the SMES accessible through a single entrance, right below the room with the burn chamber, isn't great, imo. Also those thindows between mechanics and engineering should probably be replaced with full windows.

**Comment by penny64** [comment]
> 
> 
> I prefer your previous iteration, where the mechlab didn't expand into the engineering room. It feels kinda awkward with how things are partitioned right now. Having the SMES accessible through a single entrance, right below the room with the burn chamber, isn't great, imo. Also those thindows between mechanics and engineering should probably be replaced with full windows.

Now I'm in a weird place cause I've got two devs here saying opposite things
I'm with Kyle and I like bigger here, I was thinking I could possibly take over some of that burn chamber for the SMESes and I dunno, I can work something out. 
Possibly could just steal some of the control room

I also tried this

https://cdn.discordapp.com/attachments/383743035894267905/843204183816929291/unknown.png

Which needs some work but is pretty nifty, I thought

**Comment by penny64** [comment]
Tell you what: I'm gonna move the closet and the SMES chamber to the right and the door to the left and get the best of both worlds

**Comment by penny64** [comment]
Okay new idea, I'm gonna attach the SMES room to to the control room and shift the closet up

**Comment by ZeWaka** [comment]
any update @penny64 ?

**Comment by penny64** [comment]
This is top of my stack atm but I haven't done it yet, probably tomorrow's chore

**Comment by penny64** [comment]
OKAY TIME FOR A NEW PULL REQUEST

**Pull request closed without merging**
