### PR TITLE
Ai hologram personas

### PR DESCRIPTION
**Pull request by Bartimeus973**
## About the PR 
Adds a new interaction with AI status displays which can now be used by the ai to spawn a hologram of their choice they'll control until they either stray too far from the display, they decide to return to the mainframe, or the display is destroyed. Also makes displays able to be broken by smashing it, or repaired with a glass sheet.

To use holograms: Simply click the "holo" button on the left as an ai and use the contextual menu.

Holograms cannot be hurt in any other way than through an EMP. Holograms are considered silicons and have the usual ai goodies: All access, remote usage of machines, no hands. They cannot be touched or directly interact with anything. They can move through anything and everything with the exception of walls. The ai has access to their pda while controlling an hologram. Several AIs can make their own individual hologram at the same holo-projector. Leaving a hologram makes it disappear. The hologram speaks from the status display, but emotes from the hologram.

Currently, there are three hologram forms to pick from: Bee, Persona or Eye. The color of the hologram is inherited from the AI.

Possible holograms:
holograms2

Demonstration:
holograms3

Hud:
image

Possible additions i'm looking into:
Unlock more hologram personas depending on what hologram expansion module is slotted in the law rack.
Add a way for the ai connexion and discussion to be snooped upon, like packets or radio messages.

## Why's this needed? 
It is fairly common for the AI to feel ignored when using the radio. One solution to this is to use an AI Shell, however this requires moving the shell to the location manually. Another solution is using the radios hanging on the walls but they also tend to be forgotten about and a bit obscure to use for newer ai players. This PR adds a new solution for instant, obvious manifestation to give the ai a new fun new way to interact with the crew. This should also provide a lot of fun RP opportunities!
Holograms and fancy lights are peak retro-future and should fit right in.

Note: This pr doesn't add the holo-projectors to any maps and only contains three holograms for now. If this pr gets approved, i'll rapidly deploy a second one adding it to maps with a changelog.

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Maybe give this functionality to status displays? Also these should still have the same camera vision restrictions as normal ai

**Comment by virvatuli-gh** [comment]
bee persona is admin impersonation 🙈

**Comment by Tarmunora** [comment]
Hm. Not sure how I feel about giving the AI personal/non-radio communication like this. It's interesting, but I think that as far as "non-broadcast communication" goes, I'd rather have seen it be built off of AI displays/intercoms instead

**Comment by pgmzeta** [comment]
suggestion: build this off of `/obj/item/aiModule/ability_expansion/` and make the resulting module generally available in uploads (maybe a chance to be pre-installed?).

**Comment by Mister-Moriarty** [comment]
While I agree with the general premise of this PR; to improve crew-AI interaction, I feel personae holograms are too elegant to suit the AI. In my view it is more inline with the aesthetic of the AI to remain presented as a pragmatic and tangible AI in being limited to the station's wired devices, machinery, and radio networks, which I believe is more true to the station's 1980's retrofuture aesthetic.

I believe a more thematic way of encouraging crew-AI interaction would to be improve the communications systems already available onstation for the AI (#6844 being a superlative example of such).

**Comment by Bartimeus973** [comment]
I can very much remove the holo-projector display and instead give this behavior to ai display instead! I'll also have to change ai display to make them breakable but this should be a piece of cake.

**Comment by Azrun** [comment]
Functionality:
Why use status displays (and previously the projector object) when the existing hologram functionality is based on the cameras?

It would be neat if there was some limitation where the hologram would slowly fade over time, was mutually exclusive with other holograms (while in use), or had some silly power consumption.  But that is my "but what will it cost them" brain going. 

Vibes:
I have to agree that this does steer away from the retro-futurism vibes.

**Comment by Tarmunora** [comment]
after some discussion in admin chats, I think that #12386 is more the approach we'd want to take.

**Pull request closed without merging**
