### PR TITLE
Replaces Old Security Records Computers With ThinkDOS SecMate Computers

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[QoL]

## About the PR:
Replaces all instances of `/obj/machinery/computer/secure_data` with `/obj/machinery/computer3/generic/secure_data` and adds data terminals where necessary in the following maps: Cogmap, Destiny, Donut3, Horizon, and Kondaru.

## Why's this needed?
`/obj/machinery/computer3/generic/secure_data` has largely superseded `/obj/machinery/computer/secure_data` due to superior UI and inbuilt functions. If I am not mistaken, the old computers were meant to be removed from maps anyway.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)Replaced old Security Records computers with ThinkDOS SecMate computers.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Okay I'll admit the old records computers are a mess code-wise, but am I the only one that finds them infinitely nicer to use? The ThinkDOS commandline interface involves a lot of repeated inputs and arbitrary number pushing. Like yes you can learn that the sequence to set arrest is `login -> secmate -> 2 -> Name Mcnameson -> 8 -> 1` but that's still a lot of button pushing compared to just doing a ctrl + f search and clicking "arrest".

**Comment by Chatauscours** [comment]
Whilist the sec records consoles are more convinient when you have the full name of the suspect, they are lacking 3 important functions:
-Search by job
-Search by partials
-The new compliementary status function (aka button 9)

That said, if I understand the PR correctly, data banks (aka retextured sec records consoles)  will be made available on all maps in the mainsec office, leaving you the choice of what to use.

I'm in favor of this PR, as it both upgrades systems and leaves you a choice if you prefer the old records.

**Comment by Mister-Moriarty** [comment]
Personally, I despise the old records system; to me, while slightly less intuitive, SecMate provides far superior functionality, with partial name searches, fingerprint lookups, and in my eyes, a more thematic interface. Although that is just my own opinion on the matter, and I do admit that the index navigation system can get a tad repetitive.

**Comment by Mister-Moriarty** [comment]
> That said, if I understand the PR correctly, data banks (aka retextured sec records consoles) will be made available on all maps in the mainsec office, leaving you the choice of what to use.

Data terminals, the underfloor ports allowing computers to interface with the station's wired network. Some instances of `/obj/machinery/computer/secure_data` were placed without accompanying data terminals.

**Comment by FlameArrow57** [comment]
Related (for extra reference): #7049

**Pull request merged**
