### PR TITLE
Removes Unused maps, moves 2020 christmas maps to /unused

### PR DESCRIPTION
**Pull request by comradef191**
[CLEANLINESS]
## About the PR 

Cleans out the /maps/ folder, moving the 2020 chirstmas files to maps/unused/ for future reference, and removing everything else that wasn't an actual used map.

(do we REALLY need old halloween maps from 2010, 2012 & 2014?? do we need a prototype layout of early Cog1's Engineering????)

## Why's this needed? 
...
do we REALLY need outdated old copies of shit on Z2, or already updated? or just plain unused.

+if anyone wants to change a bunch of paths for shit thats used on all maps (ala #2471 & #3732 ), they have to either update **every single map file** or ignore a good amount of files, this removes those files that are _generally_ left forgotten

## Changelog
N/A; No player-visible changes.

### CODE REVIEW

**Comment by comradef191** [comment]
oh no merge conflicts

**Comment by Gannets** [comment]
One of these days we'll probably go through and purge all the old/unused icons too. But other than reducing the repo size, I'm not sure what this gets us?

**Comment by comradef191** [comment]
> One of these days we'll probably go through and purge all the old/unused icons too. But other than reducing the repo size, I'm not sure what this gets us?

Primarily the following:

- If anyone wants to change something thats used universally, such as floors or areas, they no longer have to look through and choose to either update numerous unused files, or leave them more and more unusable

- Files which ARE unused don't end up bloating the repository and continue in a loop of `unused -> no updates -> unused (due to not working due to lack of updates) -> no updates due to rest of file being broken`

- There is no point keeping old, unused, broken mapfiles you cannot even open in the repository. They're not being updated, and they do not work, there is no need to keep files which don't work and/or have newer working versions in the code. If anyone particularly does want to go back to these files, it's as simple as typing `git checkout 05abd023e97f81cbc1357f219e8282925bbf5842` in the terminal

**Comment by Azrun** [comment]
I think having the active maps in one folder makes it more apparent what needs to be updated for consistency instead of having to cross-reference `mapNames` in `map.dm`.

_Those files exist in the repo (on master), they will always exist in the repo.  Culling them doesn't make checkouts faster unless people are doing shallow or single-branch clones. Removing them from `master` does make finding them again more problematic unless we keep a list of "removed" features someplace._

**Comment by Eagletanker** [comment]
I'd say keep the old maps, but maybe place them in their own folder for archival reasons.

**Comment by Gannets** [comment]
> I'd say keep the old maps, but maybe place them in their own folder for archival reasons.

That is what currently happens with old maps.

**Comment by geneva-breaker** [comment]
this pr is way out of date anyway, so if we wanna reorganize the maps we'll just do it on master

**Pull request closed without merging**
