### PR TITLE
Nerfs lit welding tool damage from 15 to 10

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Nerfs lit welding tool damage from 15 to 10

## Why's this needed? 
Its absurd and inconsistent for a welding tool to do more damage than a baseball bat (that deals 12 brute damage)

## Changelog

```changelog
(u)Carbadox
(*)Nerfed lit welding tool damage from 15 to 10
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
How is that absurd, would you rather be hit with a wooden bat or a lit welding tool that is hundreds of degrees hot?
Plus, the welding tool needs fuel and you need to switch it on and off.

**Comment by zjdtmkhzt** [comment]
Also, this code is changing the damage that cauterizing surgery does, it does not change the actual attack damage that a welding tool does when switched on.

**Comment by BatElite** [comment]
Don't feel knowledgeable enough to comment on combat balance, but I am curious about how this affects blob fights. I'm guessing a standard blob tile would take 3 hits now, right?

**Comment by TTerc** [comment]
Welder is fine in its current state imo, considering its low stamina damage and the fact that you need to refuel it. Which also often makes me choose other weapons over it. I don't think it's absurd at all

**Comment by PrimeNumb** [comment]
Consider adjusting blob tile health if this gets merged

**Comment by ThatFiveGuys** [comment]
Considering that welder deals little to no stam, the high damage is fine. Nerfing it to deal 10 damage would make it useless, fire extingusher does 10 damage and slighty more stam then a baseball bat, and thats as hard to get as a weapon. Rn welder has its place on the combat meta as high damage minimal stam damage, if your goal is to make it equal to other weapons, consider 13 damage instead of making it objectively worse then options that are as easy to get.

**Review by flrsh — APPROVED** [review]
Reopening this because I support the change. Welding tools are everywhere, and it's super easy to refuel them (you can just carry around one of those handheld fuel tanks). Most weapons have less than or equal to 10 damage, so having 15 damage for welding tools, which do a less common type of damage (burn instead of brute) is kinda silly.

**Comment by flrsh** [comment]
> Also, this code is changing the damage that cauterizing surgery does, it does not change the actual attack damage that a welding tool does when switched on.

I should've checked the code before approving it :sheltersweat:

But yeah please fix that.

**Comment by Alexalmighty502** [comment]
I'd much rather change the tool in a different fashion to make it less effective like reducing the amount of "charges" it has or increase the amount of "charges" used when in combat.

**Comment by Tarmunora** [comment]
superseded by 905b0f8

**Pull request closed without merging**
