### PR TITLE
Makes the Head Surgeon revvable.

### PR DESCRIPTION
**Pull request by alexeric123**
## About the PR 
Makes the head surgeon revvable

## Why's this needed? 

Requested many times in the discord

### CODE REVIEW

**Comment by alexeric123** [comment]
If people were wrong, and the "cant_spawn_as_rev" isnt what makes them unable to be revved, i will close this.

**Comment by DimWhat** [comment]
I'd rather not let somebody with bridge access be a rev.

**Comment by UrsulaMejor** [comment]
No, for what DimWhat said.

**Comment by alexeric123** [comment]
Yeah, didnt know they had head comms

**Pull request closed without merging**
