### PR TITLE
Adds a Fishbowl Helmet, a variant of the regular Space Helmet. 

### PR DESCRIPTION
**Pull request by Gibuscode**
[Game-Objects] [Feature]

## About the PR  
Adds a fishbowl style helmet, akin to what the Monkeys have. It's based on one of the sprites from monkey helmets, with some variations. Requires the Jimi Heselden medal to claim.

image

## Why's this needed? 
I think there's a distinct lack of clear helmets in the current edition of Goonstation. So, I made one!

## Changelog 

```changelog
(u)gibusgame
(+)Adds the Fishbowl Helmet, a variant of the regular Space Helmet. Available somewhere in space...
```

### CODE REVIEW

**Comment by DecidedlyUnethical** [comment]
I like this, it's really cute.

**Comment by HyenaShepherd** [comment]
I've been wanting a see-through helmet for when I'm outside the station! And I _really_ dig this design.

**Comment by Gibuscode** [comment]
NEARLY FORGOT:
_If and when_ #20366 gets merged, I will try my best to work out a way to make this have a similar mask.

**Comment by 444Portal** [comment]
How does this look with the Space Suit itself on?

**Comment by Gibuscode** [comment]
Here you go, here's pretty much every reasonably obtainable space suit.
image
@444Portal

**Comment by klushy225** [comment]
looks good to me!

**Comment by Glamurio** [comment]
My only concern is that monkeys should now probably have a small variant of the regular helmet of each suit, otherwise this redeem would look identical and might be really confusing.

**Comment by Glamurio** [comment]
> NEARLY FORGOT: _If and when_ #20366 gets merged, I will try my best to work out a way to make this have a similar mask.

Also also, it's merged.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Yeeah sorry I'm going to have to block this. Helmets covering your face is an important design decision that allows for stealth and deception, and adding a medal reward that allows everyone to have a transparent helmet at will breaks that. Imagine you're an antag trying to hide your face in a breached station and everyone's wearing transparent fishbowl helmets.

The only way I could maaaybe see this being okay is if it was a one-of in a prefab somewhere (maybe at faint signal with the weird donk suit thing)

**Comment by ZeWaka** [comment]
Having like one in faint signal and another in an adventure zone would be cool

**Pull request merged**
