### PR TITLE
Bible crate

### PR DESCRIPTION
**Pull request by Mobilfan**
[FEATURE]
## About the PR 

Adds a bible crate to cargo, which contains 5 Nanotrasen issue bibles. These bibles don't have the special damage against evil or healing for people. Neither do they have the storage. The biblefarting has been nerfed for this special version to specifically smite your butt.
The original bible remains unchanged.
The morgue crate had it's bible replaced with an NT issue bible as well.

## Why's this needed? 

Because the only current way to get more bibles is by ordering tons of morgue crates. Also it's funny.

## Changelog

```changelog
(u)Mobilfan
(*)Added a bible crate to cargo.
```

### CODE REVIEW

**Review by pali6 — COMMENTED** [review]
I don't see much point in this and feel like adding another bible with different behaviour to the regular bible would only add confusion.

**Comment by zjdtmkhzt** [comment]
Fake bibles still having some effect on desecrating them seems a bit strange to me, and I don't really see there being much demand for a crate of non-special bibles.

Also, you can already make bible-looking books with the printing press crate, I believe.

**Comment by ZeWaka** [comment]
> I don't see much point in this and feel like adding another bible with different behaviour to the regular bible would only add confusion.

^

**Comment by virvatuli-gh** [comment]
Closing per the feedback above, this is an unnecessary change that we're not really looking to add to the game.

**Pull request closed without merging**
