### PR TITLE
Fix locker-spawn AI status display runtime

### LINKED ISSUE #19381: Adding Locker Spawned AI panel crashes Manufacturers
### Labels

[BUG][MAJOR]

### Description

I believe that adding the map generated "AI panel" to any fabrictor causes that fabricator to display an TERMOS error for the rest of the round. 

### Steps to reproduce

Grab the blueprint from the locker. 
Add it to a manufacturer. 
Be cripped by you inability to build the rest of the game. 

### Expected Behavior

I would expect it just adds the panel to the generation. 

### Additional Information & Screenshots

Reported by: beardedwall
Client version: 515.1636
On server: Goonstation 3 Roleplay: Morty
Active test merges: #18889, #19292, and #19361
Round log date: 2024-06-07-08-29
Reported on: 2024-06-07 09:24:54
Round ID: 180967
Map: DONUT3

### PR DESCRIPTION
**Pull request by pgmzeta**
[runtime][game objects][bug]
## About the PR 
add explicit list of material requirements for ai status displays

## Why's this needed? 
Fix #19381

### CODE REVIEW

**Review by flrsh — APPROVED** [review]
Does this imply that the same bug exists for the other manufacture datums that use `generate_costs`?

**Comment by pgmzeta** [comment]
My understanding is that this breaks because they're not printed from a ruck kit; they're round-spawn in the locker.

@MeggalBozale can you please confirm/take a look?

**Comment by MeggalBozale** [comment]
Sure

**Review by MeggalBozale — CHANGES_REQUESTED** [review]
This is probably a me thing, you shouldn't need to do this to fix this runtime. I'll take a look at get_type_typeinfo and see what's happening.

**Comment by MeggalBozale** [comment]
@pgmzeta I just made a separate PR since the fix for this is quite different, sorry 'bout this bug D:

**Pull request closed without merging**
