### PR TITLE
Reduces the slowdown from disorient

### PR DESCRIPTION
**Pull request by Wisemonster**
[BALANCE] [INPUT WANTED]

## About the PR 
This pr reduces the slowdown effect of the disorient status effect.

## Why's this needed? 
Currently, disorient is the second strongest additive slowdown, only outmatched by the slowed status effect. Considering that the effect causes misstep, and is on all sec weapons, which cause stamina damage, this makes getting hit by one almost guaranteed to lead into a full stun, unless under the effects of strong anti-stun drugs, like meth. This pr aims to make disorient less oppressive of a status effect, and in consequence make sec weapons more focused on reducing stamina to deliver the stun rather than simply landing the hit.

## Videos
Before the pr change:

https://user-images.githubusercontent.com/87689371/182484997-d20a90cd-a39e-4d79-bc1f-97d8d485db68.mp4

After the pr change:

https://user-images.githubusercontent.com/87689371/183481258-72ef8806-7d72-419f-aad7-8bfff394ea48.mp4

In both videos, I held left the entire time, while starting to sprint a tile before the bookcase.

## Changelog

```changelog
(u)Wisemonster
(*)The slowdown effect of the disorient status effect has been reduced (from 8, to 6).
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
no thoughts on how it'll effect tools and such rn; keep in mind disorient is also applied by vamp and ling screech and arcfiend's area flash. not sure how I feel about changing those abils rn either

**Comment by ZWRh3** [comment]
> no thoughts on how it'll effect tools and such rn; keep in mind disorient is also applied by vamp and ling screech and arcfiend's area flash. not sure how I feel about changing those abils rn either

in terms of sec gear and flashes yeah fuck the current slowdown its extreme but for stuff like flashbangs and antag abilities further testing may be needed

**Comment by Tarmunora** [comment]
can't say I'm a fan

**Comment by frawhst** [comment]
Definitely needs a demo video or similar to compare the speeds

**Comment by Wisemonster** [comment]
Aight, added a couple of videos comparing speeds, both running and sprinting.

**Comment by Wisemonster** [comment]
Ok, I've decided to change the speed reduction from disorient from 4, to 6, down from 8.

**Comment by Wisemonster** [comment]
I think I'm gonna instead do a different pr to change the status effect of tasers/batons to something besides disorient, as was suggested on the forums.

**Pull request closed without merging**
