### PR TITLE
Atlas science remap

### PR DESCRIPTION
**Pull request by Cherman0**
## About the PR 

image
image

Remaps the science department on Atlas. Toxins is moved to a seperate research outpost ship available by pod. Also adjusts the adjacent ranch and podbay to fit the new shape.

## Why's this needed? 

Atlas science has a large amount of its space taken up by toxins and a one-tile-wide maint, which struggles to really accomodate players. A seperate toxins allows it to have the space needed to not be really terrible at actually doing anything with and allows the rest of the department and maintenance more space.

This also fixes (at least) two mapping errors:
- The artifact ejector is blocked by the solar panels, meaning it doesnt eject very far and the station consequently gets turbonuked out of existance.
- The artsci pitcher is blocked by the artifact cargo pad, preventing its use without dragging all the artifacts out (which unstacks them)

## Changelog 

```changelog
(u)Cherman0
(+) Atlas's research wing has undergone major renovations. The atmospherics lab was moved to the dedicated support ship NCS Hesperis.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
I don't know how I feel about removing toxins, people blowing up the station is part of the game! If it feels too isolated maybe add some plasmaglass windows for staffies to peer in and watch the toxins nerds at work?

**Comment by Cherman0** [comment]
I added the chemvendor. I made space for it by extending one tile into the ranch pen because the rfence directly up against the ranch table made it impossible to use from the rancher side anyways (rfences are blockers like thindows for the purposes of interacting on the other side). Also added a few spectro goggles, and there is already an office supplies cabinet in the maint (which is sci accessible) which should be sufficient for any writing needs.

**Comment by AXLFAN2000** [comment]
> (toxins kinda has to be isolated because the only thing you do there is crime) 

this isn't true.  I understand other justifications for removing it from atlas but this is not the case anymore and hasn't been for awhile.

**Comment by Cherman0** [comment]
Very rarely does the crystal thing get used in my observation. While this can probably be attributed to money just not being that useful to be worth the effort, I dont think it really justifies the space.

**Comment by klookiyam** [comment]
There's one other map thats removed toxins (nadir) and there's good justification for it - acid and that there's unique systems for the scientist to work on in that map (siphon), theres also a sauna for makeshift ttvs. Using pressure crystals may be niche but people do use them. I think it would be a bummer to remove something already existing in a map just to save space.

**Comment by Cherman0** [comment]
I think youre underselling "just to save space": Atlas is in desperate need of space. If people are really attached to the concept of spending 20 minutes alone and then blowing up half the station I can stick some TTVs in engineering, but I really dont think toxins should be on this map. It commits the same sin as pathology.

**Comment by TealSeer** [comment]
two tile wide maints isn't worth removing an entire department

**Comment by Cherman0** [comment]
While I would maintain that toxins is not a department as much as a 0TC antag item, I put its parts in engineering. I added a mixing pipe in an empty area of the engine block and the engine burn chamber is sufficient to make TTVs with. If we really need to have toxins at all this saves space and is more plausible than dedicating half a wing to jerry-rigging IEDs out of straightpiped fuel cans.
image
Kondaru, cog1, and cog2 already has TTVs in engineering so this is not unprecedented.

**Comment by TealSeer** [comment]
how are scientists supposed to get in to engineering to do toxins

**Comment by Cherman0** [comment]
Put the correct chemvend in. I also noticed that its sprite is 2px offcenter of the tile.

As for scientists, engineering can just do bombs. I can't really think of a reason why it would matter who makes them and engineering conveniently already has all the equipment for it.

**Comment by Cherman0** [comment]
While I obviously wont pretend to like toxins, removing it was actually born out of a need for space. Though if you want to note parts of things names, "NCS Atlas" stands for Nanotrasen Cartography Ship. It isnt a plasma research station. Having the artlab ejector travel through maint is practicall a necessity (the alternative being either cutting off the maint so that it doesnt terminate in a generally accessible exit or having the artlab be in a totally seperate part of the map) and attempting to steal an artbomb through the ejector chute as a non-scientist is both
- A total crapshoot on actually getting one
- Extremely unsubtle. Artbombs loudly tick down and take a long time to actually go off, and you cant carry them in your inventory.
The PDA cart for the program is available in cartyparty vendors and also the AI and silicons all have it.

**Comment by cheekybrdy** [comment]
Against the toxins removal part of this PR myself, I'd rather the subdepartment would get more steered away from TTVs being the sole reason it exists and be futureproofed in that regard

**Comment by Cherman0** [comment]
I'd like that too, and there had been some pretty cool ideas regarding making rocket fuel or other special gas mixes to sell, but that isnt what happened. But removing it is primarily for space: toxins being so unappealing just makes me not feel bad about it.

**Comment by Cherman0** [comment]
I'm considering putting toxins on its own little off-station ship area since people are generally neutral or against removing it entirely. It could probably even have a blast pad for doing detonations, with the thematic reason being [explosive propulsion](https://en.wikipedia.org/wiki/Project_Orion_(nuclear_propulsion)).

**Comment by Cherman0** [comment]
image

Added back toxins in its own little support ship, the NCS Hesperis. Thematically it is a light companion ship designed for taking atmospheric readings of planets. I don't have a clever lore reason for why it would have an explosives testing pad other then that it's better than having toxins scientists blow up the space diner. It has a pod warp beacon and is also not that far out the main podbay hangar. Removed the tox stuff from engineering.

**Comment by TobleroneSwordfish** [comment]
I do like the little ship, you could put a toggleable forcefield on the back and claim it uses [external pulsed plasma propulsion](https://en.wikipedia.org/wiki/Nuclear_pulse_propulsion)
Also maybe a teleport beacon or transport chute connected to the main station (styled as a little docking gantry thing?) to make it feel less isolated (since that was the original complaint of this PR)

**Comment by Cherman0** [comment]
I considered having the explosives pad be for explosive propulsion, but it wouldnt really make sense for a ship designed to enter atmosphere (or in general, hence nasa not really pursuing the concept). 

As for connecting it to the main ship, if it isnt an Ordained By God™ requirement that maps have two merchant shuttle dock points I could repurpose the south one into a connected airbridge and have it docked. Otherwise, it has a pod beacon and a command tele beacon.

**Comment by itchybones** [comment]
As a toxins main, I'm a big fan of this in its current state. Wider maints and a toxins test site!

**Comment by TobleroneSwordfish** [comment]
> but it wouldnt really make sense for a ship designed to enter atmosphere

Oh, well who says it has to be designed to enter atmosphere? Also anything NASA found to be feasible but too wacky seems like exactly the kind of thing that should exist in SS13!

> could repurpose the south one into a connected airbridge and have it docked.

Maaaybe? It'd probably be fine to have only one shuttle dock on atlas but that might put the test pad dangerously close to the pod bay/warp beacon?

**Comment by Cherman0** [comment]
the test pad would be out past the magnet. Shouldnt be an issue for TTV blast ranges.

As for a shield... pretty much all the space inside is used up. Though i guess if it's docked maybe i could replace the comms console. Not sure if theres a 1-tile shield gen console though.

**Comment by TobleroneSwordfish** [comment]
I'm happy to write some code and add the shield/other theming stuff myself if you want to move it to be docked and I'll just merge it for now 👍

**Comment by Cherman0** [comment]
Moved it to be docked, stole one of the airbridges from cog1 to connect them. Also wired it to the main station grid.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Okay one last thing: you've got both the ignichem vendor and the old chemistry counters meaning twice the supplies that should be there.

**Pull request merged**
