### PR TITLE
Replaces naughty word.

### PR DESCRIPTION
**Pull request by Wisemonster**
[CODE QUALITY] [INTERNAL]

## About the PR 
Replaces instances of a word with somewhat fitting substitutes, or redacts them if it's part of a comment. I didn't touch the vox line cause it's handled by a blacklist, and the scots translation turns the word to not break the rules

## Why's this needed? 
Apparently this word is against the rules. Code should reflect the rules

### CODE REVIEW

**Comment by ZWRh3** [comment]
imo replace it instead of just redacting it

**Comment by DisturbHerb** [comment]
correct me if i'm wrong but i thought the usage of this word wasn't rulebreaking if it's not explicitly directed at someone? if it is then i'd be bwoinked several times over for saying "son of a bitch" to express frustration (and not in reference to someone else)

**Comment by Wisemonster** [comment]
Wiki says that it's a gendered term, so it's rule breaky. I am unaware if it isn't directed at someone it isn't rule breaky. I don't think that's the case, however if it is then it needs to be clarified on the wiki.

**Comment by Vaskritaya** [comment]
(Not an admin, just my 2cents) There is precedent for words being rulebreaking or safe depending on context of their use: Dick is pointed out as a word that is safe to call someone, but not safe to use to refer to the genitals. I'd imagine uses like "bitchin' " or abstract uses like "toggle this bitch" (similar in usage to 'shit' as a generic catch-all) would also fall under that kind of contextual safety. Phrases like "son of a bitch" could easily fall either way and need more clarification, though.

**Comment by Momoberry** [comment]
Honestly, it's better just to scorched earth stuff if we're going to crack down on it, that's my two cents. It's more work to selectively enforce it than it is to fully enforce it.

**Comment by juswantnewting** [comment]
I'm no rules expert, but I personally find this a bit goofy. I think that in certain contexts it could probably be okay, like Vaskritaya said.

**Comment by Wisemonster** [comment]
I don't personally agree with the rule myself, but I made this pr so the code matches the rules. If you want to change the rules in some way, I suggest making a forum post.

**Review by TTerc — APPROVED** [review]
Yeah, sure, I don't see why not. The changes are incredibly minor and they help with keeping the code in line with the rules. Really no need to make a big fuss about it.

**Pull request merged**
