### PR TITLE
Power Network Colour Coding

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [QOL]
## About the PR
Recolours several wires based on power net connections:
- red is for station grid
- orange is for main power source
- yellow is for solars (or catalytic generators)
- blue is for the cable connecting to the PTL
The only exception to this is the AI satellite on donut2, which has blue wiring instead of red.
This is also applied to various syndicate listening posts and offstation things.
## Why's this needed?
Did this once before in #12728 , but for some reason all the cables on kondaru are back to being red. After gathering some opinions, brown for engine grid and black for ptl works really poorly with the T ray scanner, as the cables are dark and hard to spot. That is why brighter colours, orange and blue, have been chosen.

Colour coding will make hotwiring the engine a bit more obvious and intuitive (you can visually see that it's two separate networks connected by only SMES), and also easier to avoid doing by accident.
## Changelog 
```changelog
(u)Tyrant
(+)Cables are colour coded in the following way: Red=Station, Orange=Engine, Blue=PTL, Yellow=Solars
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
as a big ol mapping pr, this will merge conflict a lot.

**Comment by TobleroneSwordfish** [comment]
This looks great, from scanning through the diffs it all looks good, although did you mean to remove this cable from the cog 1 engine choice prefab?
image

**Comment by TheTyrant25** [comment]
yeah, i changed the way that the ptl line connects to the engine grid, so it didn't make sense to still have the dangling cable there. It's hard to see on the other engine prefabs because of the glass, but i removed the ptl cables there too

**Comment by TheTyrant25** [comment]
this might merge conflict badly but hopefully it's solvable. gonna run the driver on it

**Pull request merged**
