### PR TITLE
Mercury Poisoning/Chronic Exposure Diseases

### PR DESCRIPTION
**Pull request by Nexusuxen**
## About the PR 

**Implements new type of /ailment/disease: chronic_exposure**
 - Intended to work in tandem with new trace_reagents var on /human to simulate integration of toxins into one's biochemistry (e.g lead replacing calcium in bone tissue)
 - Provides basic foundation to implement similar diseases
 - 3 stages that do not progress/regress without external factors
 - Includes thresholds for initial infection & progress/regress in regards to trace_reagents
 - Exposure diseases will progress/regress if they pass these thresholds
 - Disease will automatically cure once corresponding reagent gets low enough in trace_reagents
 - Contents of trace_reagents will appear in reagent health scans
 - Exposure diseases do not show in health scans without both organ and reagent scanning

**Reworks mercury's effects**
 - Chance of BRAIN per tick from 70% -> 10%
 - 20% of metabolized mercury is absorbed and stored in trace_reagents var and contributes to Mercurialism
 - Does not include any purged mercury. Using charcoal/purgatives will reduce the amount of mercury absorbed.
 - Mercurialism added as a new chronic_exposure disease. It is overall debilitating, but not explicitly/immediately lethal, especially in the first/second stage.
  - Reduced melee damage, stamina, stam regen
  - 'Minimum' brain/kidney damage
   - Severe enough progress results in brain-damaged behavior (e.g bonking into doors) due to minimum damage
  - Vomiting & blurring vision
  - Flavortext

**EDTA added as purging reagent**
 - Purges several metals from body
 - Slowly drains mercury from trace_reagents
 - Recipe: "formaldehyde" = 3, "cyanide" = 2, "ammonia" = 2, "ethanol" = 1, "sodium" = 1, "chlorine" = 1 @374K

**Calomel can now risk mercury poisoning**
- Calomel will contribute small amounts of mercury towards poisoning
- \>20u are needed to start rolling for the disease to start
- Calomel otherwise behaves as it did before

## Why's this needed? 

Currently, mercury poisoning is sorta simple and not that interesting. This PR fixes that by adding a new kind of ailment/disease that attempts to simulate mercury lodging itself into one's body and posing chronic health issues. An organic mercury compound - e.g methylmercury - could be added to more rapidly induce mercury poisoning.
While mercury wasn't what inspired me to make this PR, doing this does set the precedent for adding Lead in the future (because let's face it, those paint cans absolutely have lead in them). It also means other metals can be given some interesting poison effects.

## Changelog

```changelog
(u)Nexusuxen
(*)Reworked mercury to pose more long-term health risks/debuffs and be harder to get rid of. Get mercury poisoning today!
(+)EDTA added to counter/remove mercury and other heavy metals.
(+)Too much calomel can now cause mercury poisoning.
```

### CODE REVIEW

**Comment by colossusqw** [comment]
This is a fantastic improvement on mercury, the more stuff we get away from constant stackable raw damage the better.

**Comment by BatElite** [comment]
Looks like New() on /datum/disease_controller isn't set to handle abstract types, wrt the failing checks
Also don't forget your labels

**Comment by Nexusuxen** [comment]
> Looks like New() on /datum/disease_controller isn't set to handle abstract types, wrt the failing checks Also don't forget your labels

Got it! That's odd, it compiled successfully on my end. Either way I'll see what I can do to fix that! And as for the labels... gonna go find the info page on them

**Comment by Cherman0** [comment]
I've done the labels for you. Also, I'd put a few bottles of the flusher chem in medivends, since mercury poisoning will probably be a somewhat uncommon disease and probably not something that doctors will prep at roundstart. Similar to heparin, which basically only ever gets used if someone ate The Monster, so its available in the medivend if it happens to be needed..

**Comment by nefarious6th** [comment]
I like the chronic_exposure addition, but I'm generally not into anything that makes med/medchem harder for people regarding the calomel changes and the charcoal interaction with this

**Comment by Nexusuxen** [comment]
> I like the chronic_exposure addition, but I'm generally not into anything that makes med/medchem harder for people regarding the calomel changes and the charcoal interaction with this

Fair enough! I can bump the amount of mercury that calomel gives down to require something like 50u+ to have a chance to cause the basic mercury poisoning.
As for the charcoal, are you referring to the fact that it won't get rid of trace reagents?

**Comment by colossusqw** [comment]
> > I like the chronic_exposure addition, but I'm generally not into anything that makes med/medchem harder for people regarding the calomel changes and the charcoal interaction with this
> 
> Fair enough! I can bump the amount of mercury that calomel gives down to require something like 50u+ to have a chance to cause the basic mercury poisoning. As for the charcoal, are you referring to the fact that it won't get rid of trace reagents?

i enjoy the way charcoal and calomel get changed with this, having charcoal also get rid of the trace mercury in you would make it even more of a panacea than it already is, and 20units of calomel is PLENTY for whatever you're going to use it for, so it's not gonna be an issue.(or at the worst possible case a very easily fixable one)

**Comment by Tarmunora** [comment]
After some discussion in adminchat, I don't think we're particularly interested in adding this sort of 'chronic poisoning' thing

**Pull request closed without merging**
