### PR TITLE
Powernet & Artsci sprites

### PR DESCRIPTION
**Pull request by binarysudoku**
## About the PR 

Perspective sprites for powernet and artsci machines

## Why's this needed? 

Visual consistency

## Changelog

```
(u)Erinexx:
(*)Updated powernet & Artsci sprites
```

### CODE REVIEW

**Comment by pali6** [comment]
The heating / cooling overlays are a bit too distracting at this animation frame duration and alpha change. I'd either make the frames take longer or just have them oscilate between full opacity and something just a tiny bit transparent.
C55JKDFyWX

**Comment by pali6** [comment]
Other than that I like the sprites. Here are most of them in their natural habitat:
image
impactstand-extend seems to be new and unused, did you mean to add it to a `flick` call of the impact sensor?

**Comment by binarysudoku** [comment]
> Other than that I like the sprites. Here are most of them in their natural habitat:
> image
> impactstand-extend seems to be new and unused, did you mean to add it to a `flick` call of the impact sensor?

Strange, it was already in the files hmm
we could definitely add them in easily enough, would you be ok with adding that code and submitting it as a suggestion on this PR? <3

**Comment by pali6** [comment]
Actually disregard that `impactstand-extend` comment, the state is used. It's jsut the diffbot that says it's a new sprite.

**Comment by flrsh** [comment]
Nice work!

I'd suggest making the pitcher's nozzle more distinct from its body. And because of the perspective, the xray machine looks unusually bulky. Maybe make it slightly smaller (both height and width wise) and emphasize the middle part where artifacts would sit more.

**Pull request merged**
