### PR TITLE
Adds chili cheese fries

### PR DESCRIPTION
**Pull request by Glamurio**
## About the PR 
Adds `/datum/cookingrecipe/chilifries` (made with fries) and `/datum/cookingrecipe/chilifries_alt` (made with chips), which produce `/obj/item/reagent_containers/food/snacks/chilifries`, a new food that contains some capsaicin and cheese.

## Why's this needed? 
Mhhh, yummy

## Changelog 

```changelog
(u)Ryou (Glamurio)
(+)Adds chili cheese fries. Yummy!
```

### CODE REVIEW

**Comment by Glamurio** [comment]
Apologies for the lack of tagging, thanks Bartimeus, I just kind of tossed this PR out

**Review by flrsh — CHANGES_REQUESTED** [review]
The sprite needs more work. Right now it looks like fries with some globs of ketchup. Maybe consider shifting the color of the fries as a whole? Or adding a pattern to the wrapper.

**Comment by Glamurio** [comment]
> The sprite needs more work. Right now it looks like fries with some globs of ketchup. Maybe consider shifting the color of the fries as a whole? Or adding a pattern to the wrapper.

Got a new sprite, this one's without wrapper and looks more like a prepared dish similar to other prepared dishes, ideally served on a plate.
image

**Comment by deathrobotpunch** [comment]
THANKS ALOT I AM HUNGRY NOW

**Comment by pali6** [comment]
According to sprite-knowledgeable devs and admins the sprites are eh.

**Comment by Glamurio** [comment]
> According to sprite-knowledgeable devs and admins the sprites are eh.

Rejoice, for the gods have bestowed upon us a new sprite. Credits to waffleloffle
image

**Pull request merged**
