### PR TITLE
adds chems to ??? pills

### PR DESCRIPTION
**Pull request by NightmareChamillian**
## About the PR 
Same PR, decontaminated master branch.
As was suggested in https://forum.ss13.co/showthread.php?tid=19231 , adds some newer and older chemicals that would be fun to have in ??? bottles. Full list:

Primaries: atropine, amanitin, neurodepressant, bee(causes you to vomit bees), curacao (similar to bojack daniels), ling island iced tea, honky_tonic, viper_venom, venom, spidereggs (implants with a parasite), rainbow fluid (makes you a clown), water, sugar, fuel, lexorin (removes need to breathe, causes tox), yobihodazine, liquid plasma (makes your lungs plasma lungs), loose_screws

Adulterants: helium, ectocooler, colorful reagent, bee, glitter

## Why's this needed? 

??? pills are a fun roulette, having more whacky stuff that can happen is always nice

## Changelog

```changelog
(u)NightmarechaMillian
(+) ??? pills have been updated with some new chems.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Spider eggs seems like it may be a bit too powerful to make available from all the random pill bottles in maint?

**Comment by colossusqw** [comment]
I agree on the  spider eggs being a bit powerful but besides that it seems good to me!

**Review by Tarmunora — CHANGES_REQUESTED** [review]
the drug primaries should be like... drugs. Not outright poisons (no clue how ricin made it in that list, it should not be there). *Some* of the chems in this PR would be fine for the adulterants list, but of those, only like, neurodepressant and *maybe* sugar (placebo pill funny) would make the cut for a primary.

**Comment by colossusqw** [comment]
> the drug primaries should be like... drugs. Not outright poisons (no clue how ricin made it in that list, it should not be there). _Some_ of the chems in this PR would be fine for the adulterants list, but of those, only like, neurodepressant and _maybe_ sugar (placebo pill funny) would make the cut for a primary.

Hmmm, that's interesting to know, i've always thought poisons were there by design considering y'know... the polonium...

**Comment by Momoberry** [comment]
> > the drug primaries should be like... drugs. Not outright poisons (no clue how ricin made it in that list, it should not be there). _Some_ of the chems in this PR would be fine for the adulterants list, but of those, only like, neurodepressant and _maybe_ sugar (placebo pill funny) would make the cut for a primary.
> 
> Hmmm, that's interesting to know, i've always thought poisons were there by design considering y'know... the polonium...

There are a lot of poison things, yeah. Like a lot more than just polonium, there's like prions, grave dust, nanites, chlorine/fluorine, melonium, histamine, neuro, toxic slurry, literal cyanide, radium/uranium/polonium. I thought the point of floor pills was like, they're truly a cocktail of death and you shouldn't even take em, but they're also a path to discovering secret chems and neat stuff. 🤔

**Review by Tarmunora — APPROVED** [review]

**Comment by Tarmunora** [comment]
> > the drug primaries should be like... drugs. Not outright poisons (no clue how ricin made it in that list, it should not be there). _Some_ of the chems in this PR would be fine for the adulterants list, but of those, only like, neurodepressant and _maybe_ sugar (placebo pill funny) would make the cut for a primary.
> 
> Hmmm, that's interesting to know, i've always thought poisons were there by design considering y'know... the polonium...

To clarify: there are poisons in there by design, but in the adulterants list. The primaries list is pretty much all drugs, so that floorpills will always be some flavor of drug, just with a cocktail of other junk in them as well from the adulterants

**Comment by colossusqw** [comment]
> > > the drug primaries should be like... drugs. Not outright poisons (no clue how ricin made it in that list, it should not be there). _Some_ of the chems in this PR would be fine for the adulterants list, but of those, only like, neurodepressant and _maybe_ sugar (placebo pill funny) would make the cut for a primary.
> > 
> > 
> > Hmmm, that's interesting to know, i've always thought poisons were there by design considering y'know... the polonium...
> 
> To clarify: there are poisons in there by design, but in the adulterants list. The primaries list is pretty much all drugs, so that floorpills will always be some flavor of drug, just with a cocktail of other junk in them as well from the adulterants

ah, i see, thanks for the info!

**Pull request merged**
