### PR TITLE
Shitty Bill's hairstyle update

### PR DESCRIPTION
**Pull request by TTerc**
[qol]

## About the PR 

Updates Shitty Bill's current hairstyle, to match their pre-human resprite looks in a better way. Also does the same to ill-looking fellow, for consistency, since their hairstyle is identical.

Current Bill on the left, new Bill on the right: 

## Why's this needed? 

Human Resprite kinda stripped Bill of their iconic hobo look, this PR attempts to fix it

### CODE REVIEW

**Comment by ZeWaka** [comment]
what happened to his eyes

**Comment by TTerc** [comment]
yea, long bear hairstyle is a bit wonky, it merges with the eyes, which can look weird if you look closely
looks alright ingame, in my opinion

**Comment by BatElite** [comment]
The long beard has a moustache and there's one pixel in between the mouth and eyes, so you get this.

I think it's no different from how it worked pre-HR but nobody was looking all that closely back then

**Review by flrsh — APPROVED** [review]
Regardless of the pixels right under the eyes, it's still an improvement.

**Pull request merged**
