### PR TITLE
Updates Monkey Sprite for: Nurse Dress

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
-Updates the nurse dress sprite for monkey characters
-Minor edits to placement of inhand sprites for nurse dress

## Why's this needed? 
Monkey's deserve the updated nurse dress too, y'know (aka oopsie I forgot to update it). This is needed because awww just look at how cute they are. 

169828124-09784929-0ceb-4fc5-b191-e41698282429

### CODE REVIEW

**Comment by flrsh** [comment]
I don't think nurse dresses are red, and this sprite also doesn't really look like a nurse dress. I also think it blends in too much with other medical gear, such as the medical backpack. If people are looking for a red medical dress-type thing, I think it'd be cool to do a unique design rather than just borrow from the nurse dress (and then we could also call it something else).

**Comment by WALPVRGIS** [comment]
Hm, not sure that I am happy with these sprites, the back view is kinda strange. I understand that it's going for our white-cross-on-red kind of look but looks off 🤔

**Comment by t-toasted** [comment]
Mhm. I can always unpack the nurse dress from the update and just push the monkey sprite update (which adds in the correct monkey nurse dress sprite), and the updated inhand placements for the nurse dress (they were 3 pixels off)

**Comment by t-toasted** [comment]
9D45713E-9222-4F16-A89F-474452272D3F

**Comment by flrsh** [comment]
> Mhm. I can always unpack the nurse dress from the update and just push the monkey sprite update (which adds in the correct monkey nurse dress sprite), and the updated inhand placements for the nurse dress (they were 3 pixels off)

Sounds good to me!

**Comment by t-toasted** [comment]
> > Mhm. I can always unpack the nurse dress from the update and just push the monkey sprite update (which adds in the correct monkey nurse dress sprite), and the updated inhand placements for the nurse dress (they were 3 pixels off)
> 
> Sounds good to me!

aaand done. Removed the red nurse dress from: code references, inhand, icon, wearable, and from the monkey clothing. Kept the blue nurse dress updated variant in the monkey dmi. Also fixed the placement oopsies on the inhands for the blue dress. Should be good now.

**Pull request merged**
