### PR TITLE
Allow putting a Camera on Space Suit Helmet

### PR DESCRIPTION
**Pull request by monkeymilesmoo**
## About the PR 
Adds the ability to combine a camera helmet onto a space suit helmet.

## Why's this needed? 
Allows for test subjects in telesci to actually wear a space suit and also be able to have the scientist watch where they go at the same time without needing to go through the process of getting a camera eye.

### CODE REVIEW

**Comment by DisturbHerb** [comment]
I technically *have* an alternative to this PR, which would be attaching a body-mounted camera to your accessory slot. Problem is, the production version of goonstation doesn't quite have the accessory slot. Some people might be opposed to body cameras on principle, and they kind of clash with goon's current aesthetic with the sprite I've got.

image

**Comment by monkeymilesmooYT** [comment]
I see. Well I think someone is adding an accessory slot, I didn't mess with any of the sprites in order to not mess up anything with how the helmets look since I'm no artist. This is just an easy, current-code way to wear a suit and have someone view you.

**Comment by monkeymilesmooYT** [comment]
Your body cam looks much more finished than my PR, not gonna compare there, I'm just a new developer trying to add new things.

**Comment by monkeymilesmooYT** [comment]
Oh you are the accessory dev, nice

**Comment by monkeymilesmooYT** [comment]
What would you like me to do with my PR?

**Comment by DisturbHerb** [comment]
Keep yours up, wait for more feedback. I've been very hesitant to try and push the body camera to master for the aforementioned reasons; including the fact that the camera helmet presently exists already and can fit in your pocket.

**Pull request closed without merging**
