### PR TITLE
Add Salvager Heavy Combat Suit

### PR DESCRIPTION
**Pull request by blackrep**
[Game Objects][Feature][Add To Wiki]

## About the PR 
This PR adds a unique industrial armor sprite geared towards the Salvager antag:
image

- Salvagers receive the first row, that's palleted more towards looking like a retrofit industrial suit
- The rest were just pallet swaps for testing / fun

This space suit works as a more combat oriented version of the industrial suit, with a built in toggle-able thermal visor in the helmet.

## Why's this needed? 
I kitbashed this together one day and Azrun said they might be interested in using it:
image

## Changelog 

```changelog
(u) Blackrep
(+) The Salvagers gotten their hands on some heavily armored space suits
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
NTSO looks good and appropriate to me. A unique outfit that stands out, distinguishes from NTSC and matches their heavy response role gets a thumbs up.

Feel the salvager version looks too military.

**Comment by blackrep** [comment]
> NTSO looks good and appropriate to me. A unique outfit that stands out, distinguishes from NTSC and matches their heavy response role gets a thumbs up.
> 
> Feel the salvager version looks too military.

Makes sense. The intent wasn't for Salvagers to spawn with this. They already start with their emergency suit version. Mainly just as an upgrade path as they get better gear:
image

**Comment by BatElite** [comment]
NT doing the space marines now?

**Comment by Tarmunora** [comment]
Mm, not huge on the NTSO heavy armor resprite. I don't think tacticool black is the way to go with them.

**Comment by blackrep** [comment]
> Mm, not huge on the NTSO heavy armor resprite. I don't think tacticool black is the way to go with them.

What direction would you be more interested in taking it? The general consensus I've heard is the NTSO's main purpose is to purge. IMO, I envision that as heavily armored with big guns.

**Comment by Tarmunora** [comment]
> > Mm, not huge on the NTSO heavy armor resprite. I don't think tacticool black is the way to go with them.
> 
> What direction would you be more interested in taking it? The general consensus I've heard is the NTSO's main purpose is to purge. IMO, I envision that as heavily armored with big guns.

More in line with the aesthetics of their weaponry (signifer, cornicen, etc) - sleeker rather than tacticool, light-metal-palette rather than black.

**Comment by blackrep** [comment]
> sleeker rather than tacticool, light-metal-palette rather than black.

Want to confirm. Is this more of an issue with the pallet or the overall design? If it's an issue with design, do you have any examples of a sleeker design I can take inspiration from? Looking to better understand the general aesthetic you want.

**Comment by Tarmunora** [comment]
For now, just cut the NTSO resprite, we can workshop stuff on the discord in the future

**Comment by WALPVRGIS** [comment]
Holding off on doing a proper sprite review until stuff is Complete as per previews feedback, but nice looking sprites so far! :)

**Comment by blackrep** [comment]
> Holding off on doing a proper sprite review until stuff is Complete as per previous feedback, but nice looking sprites so far! :)

Should be ready for review now. I've removed the NTSO variant from code & sprites.

**Comment by blackrep** [comment]
!merge_upstream

**Review by WALPVRGIS — APPROVED** [review]
Tested it out ingame, art-wise it looks good to me! 👍

**Comment by blackrep** [comment]
!merge_upstream

**Pull request merged**
