### PR TITLE
Renames surgical apron to white apron, adds it to the food tech vendor.

### PR DESCRIPTION
**Pull request by SgtManGuy**
## About the PR 
Gives the surgical apron that only the medical specialist had previously to the food tech. Also renames it to white apron so it fits a bit more.

## Why's this needed? 
The current chef aprons are all waist aprons, and there's been a few requests for full-length aprons.

## Changelog

```changelog
(u)SgtManGuy/what
(+)Added the white apron to the food tech's stock. There are two available there.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Everything checks out, just a question of if we want to give an apron to the chef.

**Review by flappybatpal — APPROVED** [review]

**Comment by frawhst** [comment]
I'm theoretically fine with this- does the (former) surgical apron look decent with the chef's stock gear? Would appreciate a screenshot (fit pic, whatever)

**Comment by SgtManGuy** [comment]
> I'm theoretically fine with this- does the (former) surgical apron look decent with the chef's stock gear? Would appreciate a screenshot (fit pic, whatever)

Sure. It looks fine, I think. Image attached 
whiteapron1
.

**Comment by DimWhat** [comment]
You forgot to change the monkey version's sprite name.

**Pull request closed without merging**
