### PR TITLE
Cogmap medbay changes - Switches the breakroom and the MD's office, expands both, slightly expands maint and shrinks the halls

### PR DESCRIPTION
**Pull request by F-OS**
[FEATURE] [BALANCE] [MAPPING]
## About the PR 
This PR switches the breakroom and the MD's office in Cog1's medical department, expands both, adds a few objects, and generally alters their flow, it also makes stylistic changes to the breakroom and the MD's office, turning the former into a crappy corporate afterthought and the latter into a nice, still cramped, but clean, corporate office. It also adds a basic, uncammed, restroom to medical, in order to allow for some crimes while also improving the vibe a bit. In order to allow for these changes, the sci-med router and SW maint had to be changed around a bit.

## Why's this needed? 
I believe this both helps reduce the cramped nature of medbay's attached rooms on Cog1, improve the QOL for the medical director, bring cog1 in line with newer maps in not having public-facing offices for the heads, and contribute stylistically to the map. However, I accept that this does contain a few cons, those being that it ~~cramps maint~~ (changes were made to the tunnels, reducing how shrunk they are), changes an accepted design for a map, and may affect balance.

## Changelog
```
(u)Fosstar:
(*)Switches the MD's office and the breakroom in medical, adds a restroom.
```

### CODE REVIEW

**Comment by F-OS** [comment]
I think I may have messed up the tagging but IDK

**Comment by Carbadox** [comment]
Some screenshots of the changes would make giving opinions easier and better

**Comment by F-OS** [comment]
> 
> 
> Some screenshots of the changes would make giving opinions easier and better, sounds like a generally good change though.

Ah, sorry! Here's newmed:
image

Here's oldmed: 
image

**Comment by mordent-goonstation** [comment]
image
I'd look to change the wiring to not go under the toilet, as that just makes repairing it trickier. I added some 10/10 red lines to show an alternative flow.

Unsure of how we feel about north-facing (i.e. on southern wall) sinks, they're pretty few and far between but I do see them used here and there so I'm not fully against them.

Overall I think the intent of swapping the position of MD's office and break room is very good.

**Comment by ZeWaka** [comment]
> Unsure of how we feel about north-facing (i.e. on southern wall) sinks, they're pretty few and far between but I do see them used here and there so I'm not fully against them.
I'd just rotate it 90deg and use a side-sink

**Comment by Flaborized** [comment]
Really don't like this change, I like how the MD is visible outside of medbay at the start of the round, when I've played the role on the map non-doctor people would often talk to me early on if they wanted something, and I could press the fun button to let them in if I wanted. The MD's office being placed in a spot that sees a lot of traffic in general is Cool and your reposition makes it significantly worse off. I think the addition of a bathroom really clutters the maint which otherwise would've had a nice little open area to it (I see lots of players congregate there during radstorms), while I don't think a bathroom really makes sense considering there's one so near to robotics. Generally just moving through maint looks so much more clunky with the proposed redesign.

Also this change would remove Ol' Harner catching the MD when they pick up their tranq rifle early on, one of my favorite features,,,

**Comment by F-OS** [comment]
> 
> 
> Really don't like this change, I like how the MD is visible outside of medbay at the start of the round, when I've played the role on the map non-doctor people would often talk to me early on if they wanted something, and I could press the fun button to let them in if I wanted. The MD's office being placed in a spot that sees a lot of traffic in general is Cool and your reposition makes it significantly worse off. 
I partially see your point there, but I feel that the medical director, as an administrator, should be less responsible for direct contact with other crewmembers outside of their department and more responsible for administering the doctors.

> I think the addition of a bathroom really clutters the maint which otherwise would've had a nice little open area to it (I see lots of players congregate there during radstorms), while I don't think a bathroom really makes sense considering there's one so near to robotics. Generally just moving through maint looks so much more clunky with the proposed redesign.
I'm happy to remove the bathroom and try to find ways to make maint a bit less clunky, any suggestions?

> Also this change would remove Ol' Harner catching the MD when they pick up their tranq rifle early on, one of my favorite features,,,
I'll change their patrol route around to make sure the MD gets their required harassment. Might move beepsky too.

**Comment by Flaborized** [comment]
The bathroom being maint would basically return it to the same level of clunk as before, and the buddy/beepsky change would be Very Good, otherwise I still prefer current to this change but I think those adjustments would make it *better*

**Comment by ZeWaka** [comment]
Not a big fan of the hallway/maint tunnel change, it's cramped for a reason.

**Comment by Tiggersaurus** [comment]
Have to agree that making the maint area more cramped would be ill-advised especially wrt rad storms, some maneuvering for borg during that is needed as they can't lay down/side through people.

**Comment by F-OS** [comment]
Hey, while I see both of your points, this change doesn't reduce the flow of the maint tunnels by that much, and in a way, it increases walkable space above robotics, check it out. 
image

**Comment by F-OS** [comment]
This conflict is a bit complex, I'll close this PR until it's fixed and cleaned up, will probably reopen in 15 days.

**Pull request closed without merging**
