### PR TITLE
Rework mushroom medbay

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Defeat the evil thindows that control mushroom's medbay
+ Move MDir office
+ Add OR
+ Add Pharmacy
+ Expand Morgue
image
(Since image was taken a few minor edits were made)

## Why's this needed? 
The current surgery area is cramped, theres no pharmacy and the war on thindows must be won.

## Changelog 

```changelog
(u)JORJ949
(+)Reworked Mushroom Medbay
```

### CODE REVIEW

**Comment by cheekybrdy** [comment]
I'm aware that blinds were already put into morgue to make it a more crimeable area, but the glass door from op theatre and maybe monkeydome can make the blinds a bit redundant.

**Comment by JORJ949** [comment]
> I'm aware that blinds were already put into morgue to make it a more crimeable area, but the glass door from op theatre and maybe monkeydome can make the blinds a bit redundant. From what I can tell there's quite a few camera blindspots/lack of cameras in some of the main rooms as well may be worth going around as AI.

The camera coverage was correct

**Comment by cheekybrdy** [comment]
There's a bug for the glass medical doors in present Mushroom being unhackable, looks like my fixbatch pulled a weird subtype of the doors by accident. May be worth checking your doors on this.

**Comment by JORJ949** [comment]
I clearly misclicked rebase and never noticed huh

**Pull request closed without merging**
