### PR TITLE
Onigiri have a 1% chance to be named jelly donuts

### PR DESCRIPTION
**Pull request by DisturbHerb**
[GAME OBJECTS]

## About the PR 
title

## Why's this needed? 
funny

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
why

**Comment by flrsh** [comment]
Please provide context in your PRs or else they'll just be closed. Additionally, I don't really care to add random memes to the game.

**Comment by DisturbHerb** [comment]
Eh, fair 'nuff.

**Comment by Sbmhawk** [comment]
image

**Pull request closed without merging**
