### PR TITLE
Removes the 250 blood minimum for cows to perform the milk emote

### PR DESCRIPTION
**Pull request by 112358sam**
## About the PR 
This allows players with the bovine trait to milk themselves regardless of their blood level. This can result in death, but requires ignoring the stacking symptoms of blood loss.

## Why's this needed? 
At the request of asche on Discord. 

## Changelog

```changelog
(u)112358sam
(+)Removes the blood level check for performing the milk emote.
```

### CODE REVIEW

**Comment by frawhst** [comment]
I did indeed request this. I think the odds of milking yourself to death accidentally are pretty slim, and I think it’s funny to be able to do.

**Comment by ZeWaka** [comment]
@mybluecorners

**Comment by mybluecorners** [comment]
looks fine
although they should not be able to milk themselves if they have 0 blood. not sure if this code allows for that or if its safeguarded elsewhere.

**Comment by 112358sam** [comment]
It seems to be safeguarded in the blood code. The blood is removed via the transfer_blood proc or the bleed proc. Both of these have checks for 0 blood. However, the description would would then be inaccurate. I changed it back the original check with 0 replacing 250.

**Pull request merged**
