### PR TITLE
pulse rifle resprite

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Resprites pulse rifle.
Resprite: 
image

Current: 
image

Oh also pulse rifle lawrack resprite I guess:
image

## Why's this needed? 
The current sprite is very dull color wise, this is mostly a pallete swap with a few touch ups here and there. I think this looks a lot better and cooler.

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Review by frawhst — APPROVED** [review]

**Comment by BatElite** [comment]
You layered the guns weird on the rack, having the bottom in front (like of old) will probably look better

**Comment by Gannets** [comment]
I feel like this was a chance to make some bigger improvements to the original sprite. There's a lot of good, modern gun sprites in the codebase now that components could be lifted from. Also Yass' comment on the other PR about using the NTSO palette applies here too.

Also, nitpick but the ammo indicator lights probably should be flipped? Currently the outline is the lightest part.

**Comment by ThatFiveGuys** [comment]
> You layered the guns weird on the rack, having the bottom in front (like of old) will probably look better

Did that initially, looks off perspective wise.

**Comment by ThatFiveGuys** [comment]
> I feel like this was a chance to make some bigger improvements to the original sprite. There's a lot of good, modern gun sprites in the codebase now that components could be lifted from. Also Yass' comment on the other PR about using the NTSO palette applies here too.
> 
> Also, nitpick but the ammo indicator lights probably should be flipped? Currently the outline is the lightest part.

NTSO pallete just doesnt really look good for this sprite. Which specific improvements do you want to be seen for this sprite? A major overhaul of design or just a few specifics area of the gun.

**Pull request closed without merging**
