### PR TITLE
resprites the botanical mr

### PR DESCRIPTION
**Pull request by gunwithaman**
## About the PR 
resprites the botanical mister, the new sprites more accurately reflect the current state of the mister (fine mist vs super fine mist)
https://imgur.com/a/WcJfLum

## Why's this needed? 
not in 3/4 perspective, was kind of hard to tell what it was, also on the wanted resprites list.

### CODE REVIEW

**Review by ZeWaka — APPROVED** [review]
better than existing

**Comment by BatElite** [comment]
Fancy

Is the old sprite still used anywhere? Might as well get rid of it if not.

**Comment by ZeWaka** [comment]
> Fancy
> 
> Is the old sprite still used anywhere? Might as well get rid of it if not.

Yes

**Comment by RelentlessGarbage** [comment]
Oh wow, that's way better! Actually looks like an irrigation device, and not whatever the mister was previously.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
