### PR TITLE
Slasher Pass 2

### PR DESCRIPTION
**Pull request by Zonespace27**
[Balance] [QoL]
## About the PR 
This PR changes & fixes more things with the Slasher, namely:

- Adds them in the postround report
- Adds more spooky sounds for various actions
- Fixes being able to go to the nullzone when incorporeal (fixes with admin noclip too)
- Occasionally, lights will break near The Slasher passively
- Slasher mask gives tier 2 Thermal Vision
- Reduced Corporeal/Incorporeal cooldown to 20 secs from 30
- Cleans up code
- Reduces stagger cooldown to 35 from 40 seconds
- Fixes blood trailing

## Why's this needed? 
Bug fixes are good, fixing oversights is good, and some balance changes (ontop of removing some fluff) should hopefully give The Slasher a little more staying power

### CODE REVIEW

**Comment by pali6** [comment]
What was buggy about the blood trail?

**Comment by pali6** [comment]
What was buggy about the blood trail?

**Comment by Zonespace27** [comment]
> What was buggy about the blood trail?

Walking over a blood pool (thus, resetting it) would stop the blood trail from happening, and when you try to re-enable it after this happening, to the Slasher's code it's still "ON", which disables it. So it seems that, to the user, the button did nothing after walking over a blood pool.

Also, The Slasher makes a ridiculous amount of blood as-is, it's not very needed

**Comment by pali6** [comment]
😔 I guess you are right (but I liked that ability, when I spawned a Slasher on RP they spent a good amount of time just being creepy with the bloody footsteps).

**Comment by Zonespace27** [comment]
Setting DNM until I fix a thing with this

**Comment by Zonespace27** [comment]
thank you GH mobile for not adding DNM

**Comment by Zonespace27** [comment]
@pali6 
Cleaned up the PR, readded a better version of blood trailing

**Review by pali6 — APPROVED** [review]
Skimmed very very very briefly because too tired.

**Pull request merged**
