### PR TITLE
Updates Wrassle Map Medbay

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
image
Updates the wrestlemap medbay. Because we do occasionally play on this map and the medbay wasn't very good. Nor did it have enough WRASSLIN'

Updates lighting in medbay to be smoothed, rearranged surgery/pharmacy/med storage, removed patho, added chemical resupply consoles and clothing vending machine. Also edits the medbooth by the main ring to be better. 

And, of course, turns medbay's main area into a wrestling ring.

Also some minor misc changes such as fixes an errant display monitor, smoothing out some additional lighting, adding the chem console to science as well. 

## Why's this needed? 
We do still occasionally play on this map, and the medbay both wasn't great and also could use some improvements. Just because it's a rarely played map doesn't mean it can't get some TLC every now and then. Having it be improved on also means that when it is played, it's more of a treat, and less of a slough if the round doesn't end immediately. 

## Changelog 

```changelog
(u)Roddy
(*)Updated Wrestlemap's medbay.
```
[mapping] [QoL] [medical]

### CODE REVIEW

**Comment by t-toasted** [comment]
sorry 2 whoever reviews this because I know I likely messed some stuff up somewhere and also its wrestlemap

**Comment by trollbreeder** [comment]
I love that the main area is a wrestling ring now, especially with that big medical cross symbol on it, that's just amazing

**Comment by nefarious6th** [comment]
Looks good, only minor things:

Add extra box of health scanner modules espc since prodocs in the paramed prep room arent advanced
check light switch orientation in robo, genetics, cloning
light switch on south wall by cloning could b moved
Check tile robotics intercom is on, looks one too far back?
wall closet orientation on left in pharmacy
special request but maybe 1 more medtrak pc :>

**Comment by t-toasted** [comment]
> Looks good, only minor things:
> 
> Add extra box of health scanner modules espc since prodocs in the paramed prep room arent advanced check light switch orientation in robo, genetics, cloning light switch on south wall by cloning could b moved Check tile robotics intercom is on, looks one too far back? wall closet orientation on left in pharmacy special request but maybe 1 more medtrak pc :>

-added to storage
-orientations are correct
-moved switch
-oddly a feature of this map, they are properly set up but the map maker decided to make them look like that for their own visual confirmation. But they do not spawn weird. Replaced it nonetheless with the standard version one tile back that we are used to
-orientation correct, breaks up empty wall space entering cloning
-added to reception lobby area, replacing a spare first aid kit/scalpel (woe)
-removed forensics scanner in morgue in keeping with parity with other maps 
-added third defib to one of the carts just in case a staffie steals the others

**Review by pali6 — APPROVED** [review]

**Pull request merged**
