### PR TITLE
Makes robotic, thrall, kudzu, and blob speak more noticeable

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[QOL]
## About the PR 
Gives robotic talk, thrall speak, kudzu speak and blob telepathy outlines in chat to make them more noticeable.
Robotic talk is now bold rather than italic and uses Courier monospace font.
The vampire's name is now bright red in thrall speak.
The vampire TEG thrall speak is now consistent with actual vampire thrall speak.
Kudzu speak's colours have been adjusted to actual kudzu colours as they were basically the same as blob (not that you'd ever see them at the same time outside of admin fuckery, but it makes sense anyway)

image
image

thrall_talk
thrall_talk_light
image

blob_talk
blob_talk_light

image
image

## Why's this needed? 
Despite being arguably the most important communication channels for their respective roles, robotic talk and thrall speak were incredibly easy to miss, especially with robotic talk having the same styling as speech into radio (something you almost always want to ignore)

## Changelog

```changelog
(u)LeahTheTech
(+)Robotic talk, thrallspeak, and blob hivemind communication got a facelift and should now be much more noticeable.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
I suggest a similar highlight on nukie radio and blob speak.

**Comment by TobleroneSwordfish** [comment]
> I suggest a similar highlight on nukie radio and blob speak.

Can do, although it feels kinda weird for nukie radio to have it as it is just a normal radio frequency rather than telepathy like the others.

**Comment by flappybatpal** [comment]
Yeah that's fair, probably not worth doing it unless a dev likes the idea.

**Comment by pali6** [comment]
I don't think nukie radio is appropriate for this.

**Comment by NightmareChamillian** [comment]
already this is a massively needed improvement, but do you think you could do the same thing with kudzu speak?

**Review by pali6 — APPROVED** [review]

**Pull request merged**
