### PR TITLE
SPRITES: Resprite of refinery nano-fabricator

### PR DESCRIPTION
**Pull request by TheTrueMunchkin**
[GAME-OBJECTS] [SPRITES]

## About the PR 
Brings the old nano-fab sprite up to standard.

nano-fabricator1

## Why's this needed? 
Old sprite is old. 

## Changelog 

```changelog
(u)Herb
(*)The Nano-Fabricator has been re-sprited!
```

### CODE REVIEW

**Comment by MitchTheUser** [comment]
Die old sprite die

**Comment by frawhst** [comment]
> god I have no clue how to do labels
You don’t put the letters in front, I think

**Comment by frawhst** [comment]
hmm that isn’t doing it either. shrug. or maybe just slow

**Comment by nefarious6th** [comment]
Very cool, like it a lot

**Comment by cheekybrdy** [comment]
I like this alot

**Comment by Azrun** [comment]
`fab2-work` Why don't the tools maintain thier angle even though the arm hinges?
`fab2-broken` What is with the X? I think it is near for providing the state of the device but it feels like someone came by and painted an X.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
x

**Comment by pali6** [comment]
Any updates on this or is it abandoned?

**Pull request closed without merging**
