### PR TITLE
Makes instruments manufacturable

### PR DESCRIPTION
**Pull request by CaioFrancisco**
[QOL] [OBJECTS] [INPUT WANTED]
## About the PR 

Makes General Manufacturers capable of printing instruments for the station. Also completely instrument parts for crafting and the code for crafting them. If any admin wants me to, I can delete the trumpet or saxophone from the manufacturer to avoid conflict with the Spacebux purchase menu.

## Why's this needed? 

For a band of staff assistants to make a symphony of whistles in Medbay. More seriously, to allow more fun gimmicks involving the instruments. Besides, there's hopefully someone that's going to finish the instrument redesign. 👀

## Changelog

```changelog
(u)Caio029
(+)Makes General Manufacturers capable of printing instruments.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Seems more fitting to expand the amount of instruments cargo can buy

**Comment by CaioFrancisco** [comment]
> Seems more fitting to expand the amount of instruments cargo can buy

That's a good idea, so I'll let GitHub bot make a thread about this on the forums.

**Comment by zjdtmkhzt** [comment]
Doesn't this currently remove the way to make material instruments, necessitating the use of the arcplater?

**Comment by CaioFrancisco** [comment]
> Doesn't this currently remove the way to make material instruments, necessitating the use of the arcplater?

Yeah, and to be honest, using the arcplater is much more simple than the previous dynassembly system.

**Review by ZeWaka — APPROVED** [review]
thanks for deleting my trash code

**Pull request merged**
