### PR TITLE
Slight sword sheathing animation

### PR DESCRIPTION
**Pull request by Flaborized**
## what 

Adds a short, slight animation to the sheathed swords that plays once, with them sliding into the sheath or scabbard.

## why 

This makes a little animation play when you sheath your sword (or when they spawn), which I think is a nice little bit of polish. Sprite animations for player-driven actions like this make the game feel a tiny bit more 'alive'.

### CODE REVIEW

**Review by ZeWaka — APPROVED** [review]
would be cool if we could easily reverse this for drawing too 👀

**Comment by Flaborized** [comment]
problem is that you need to instantly get the sword in your hand, if an animation played on the sheath it'd look like there were two swords. I considered like a little 'sheen' or something shiny on the blade for when you draw it, might do that in another PR some other time

**Comment by BatElite** [comment]
Whether now or in another PR, would it be possible to do the reverse animation on mouse hover instead of clicking? I think that'd be a nice touch while still instant where it counts.

**Review by Gannets — COMMENTED** [review]
Yeah this is a great idea. I was thinking of something similar for firing guns.

**Pull request merged**
