### PR TITLE
Silverware Orientation QoL, Plastic Silverware Sprites, and Chopsticks

### PR DESCRIPTION
**Pull request by AwkwardDryad**
[FEATURE]

## About the PR 
- Added the ability to rotate silverware in hand
- Added the plastic silverware package that refuses to open
- Added premium plastic silverware that looks really shiny and colorful
- Added chopsticks! いただきます！ ( ^ - ^ )

//If I accidentally overwrote something in the silverware code, please let me know. This patch was made on an earlier version of 2020 :P

//Also I de-verbed rotate on silverware and made it a proc instead.

## Why's this needed? 
- Quality of Life, Visuals, and *Engaging Gameplay :tm:*

## Changelog

```
(u)AwkwardDryad:
(*)Added chopsticks and premium plastic silverware
```

### CODE REVIEW

**Comment by UrsulaMejor** [comment]
After playing around with these for a bit, here are my thoughts:

https://cdn.discordapp.com/attachments/182254397999415296/725545738217455696/unknown.png

1) Forks & Spoons:
Great proportions. I like that they're smaller than the "real" forks and spoons, which makes sense. Bright colors for the fancier ones are good. Mergeable as is, but are the white highlights supposed to be polka dots, or plasticky shine? Either way it works, but it's not clear to me which one it is

2) Knives:
The proportions on this are a little off. Most knives for eating are generally proportioned such that the width of the blade is the same as the width of the handle and the length of the blade is a close approximation to the length of the handle. Although for plastic knives the length can vary a bit (the handle will tend to be a teeny bit longer to help support the pressure on the plastic edge), I don't know if we have enough pixels to experiment with proportions and have it come out right, as the blade/handle length/width proportions of a knife are the bulk of what tells you what kind of knife it is. See these examples:

https://cdn.discordapp.com/attachments/338140147558383616/725848258366144532/unknown.png

https://cdn.discordapp.com/attachments/338140147558383616/725848424980938873/unknown.png

The suggested plastic knife sprite is mergeable for sure, as it's better than the existing one, but my feelings are that it could use a little adjustment, as it reads closer to "scalpel" than "dinner knife". If you're a bit burnt out on messing with the sprites, I could give it a go after it's merged and run some ideas by you, if that's okay.

3) Chopsticks
I don't know nearly as much about chopsticks as I do about cutlery, but these look great. Mechanically, for some reason I can't eat sushi with them 😰 

https://cdn.discordapp.com/attachments/338140147558383616/725851031891738674/unknown.png

Maybe this is an unrelated issue with sushi rolls, though?

4) Plastic Silverware Package
The package sprite itself is great, but the utensils in the package are hard to make out:

https://cdn.discordapp.com/attachments/338140147558383616/725851696961421462/unknown.png

It might be better to only show the spoon sprite inside, for readability? This is how the utensils look after they fall out:

https://cdn.discordapp.com/attachments/338140147558383616/725852140052021258/unknown.png

You only ever see the spoon sprite on top, anyways, so you might not have to try to include all of the utensils in the package sprite.

Mechanically, I like the utensils flying everywhere from the package on occasion. You may want to put the throw_at()s in a SPAWN_DBG(0), as the throw_at() proc has a sleep in it, which causes the utensils to very visibly throw themselves one at a time from your location.

Client feedback wise, I know we don't have a _formally_ established "voice" for the messaging we give players, but aside from some very specific wall-breaks, we don't generally do first person narrative messages like "AAAAAAAAGH WHY WON'T IT OPEN!" or "Oh no...The package...It'S tOo PoWeRfUl!". Client feedback messages tend to be in a third/second person objective tone or second person snarky tone. The "Almost open! Wait... Nevermind." message is a near-perfect example of this.

**Comment by AwkwardDryad** [comment]
knife proportions: i did a lot of messing around with it and that's just how plastic knives are. 32x32 is too small for any finer detail, plus this is a minor detail that, in the grand scheme of things, no one will probably ever care about.

chopsticks on sushi: ill test locally and, if I can recreate it, I'll fix it

messages: it doesn't really matter to me, feel free to change these as you see fit, but I really don't feel like changing them right now

sleep statement: ill fix this too.

**Comment by UrsulaMejor** [comment]
If you want to go ahead and fix the sleep statement, I'll go ahead and merge this. The other nitpicks are minor and aren't critical if you're not feeling up to it now.

**Comment by AwkwardDryad** [comment]
> If you fix the spawn/sleep statement thing, I'll go ahead and merge this. The other nitpicks are minor and aren't critical if you're not feeling up to it now.

awww thank you, ill do that really soon. I've been doing an art commission and trying to figure out why my vscode debugger isnt hitting breakpoints D:

**Comment by AwkwardDryad** [comment]
@UrsulaMejor All fixed :heart:

**Pull request merged**
