### PR TITLE
Capybaby

### PR DESCRIPTION
**Pull request by amylizzle**
## About the PR 
Capybaby
image

## Why's this needed? 
Capybaby

## Changelog 

```changelog
(u)Amylizzle & Waffleloffle
(+)Capybaras should not be alone, and so the pool room capybara now has a baby. Sprites by Waffleloffle.
```

### CODE REVIEW

**Comment by wolfolotl** [comment]
I could make some bespoke sprites for the baby, if you like. just gotta know if it needs to sit too

**Comment by amylizzle** [comment]
Could potentially but I'm honestly quite pleased with how just scaling it down looks!

**Comment by pali6** [comment]
I don't think the scaled down version looks good personally.

**Comment by amylizzle** [comment]
Oh no, in that case @wolfolotl yeah bonus sprites would be great. Sitting would be required.

**Comment by pali6** [comment]
At the very least a proper outline 🥺

**Comment by pali6** [comment]
!merge_upstream

**Review by pali6 — APPROVED** [review]

**Pull request merged**
