### PR TITLE
some conveyor refactoring. also bendy conveyors!

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Don't panic, there's only like, 2 code files that actually got proper changes.

Makes the default conveyors switch between two directions that do not have to be directly opposed. This also adds the possibility for conveyors going around a corner, they will look bendy now.

Also adds a small debug item with a component for laying conveyors as you walk and creating switches for them. This may be useful in the future when conveyor construction is added, it may still be a little jank right now.

https://user-images.githubusercontent.com/35579460/198814977-5db15d79-b9df-4f03-8d53-3606396ed388.mp4

For converting the maps I used the tg tool (https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths). 
Here is my script, in case anyone wants to convert other maps apart from the ones I thought were still in use:
[11668_conveyors.txt](https://github.com/goonstation/goonstation/files/9893066/11668_conveyors.txt)

## Why's this needed? 

- The conveyors having dedicated vars for their directions instead of using dir may be nice?
- Bendy conveyors?
- Maybe good for conveyor construction in the future?

## Changelog 

```changelog
(u) zjdtmkhzt
(+) Conveyors can now turn corners. Thanks to Arthur Holiday for helping me with the bendy conveyor sprites!
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Wow can't wait to see if this compiles on all the maps!

**Comment by nefarious6th** [comment]
corner conveyors finally here? O: nice work, as always. ty for staying committed to conveyors.

**Comment by zjdtmkhzt** [comment]
Oh, this is going to need updates to some secret z level files, the scripts can be used for that, feel free to ping me on discord if help is desired!

**Comment by pali6** [comment]
I don't like that the corner sprites don't connect nicely with the non-corner sprites. See the following illustration:
image

**Comment by zjdtmkhzt** [comment]
https://user-images.githubusercontent.com/35579460/199090871-e0de43c3-d1f2-4397-99fc-77e5413a235f.mp4

**Review by pali6 — APPROVED** [review]

**Pull request merged**
