### PR TITLE
add pump to cog1 engineering mixing

### PR DESCRIPTION
**Pull request by mc-oofert**
[MAPPING]

## About the PR 
Adds a pump to the cog1 engineering mixing pipe things in engineerings hotloop room
unknown
Appears in the pump control computer as "Hot Loop Mixing"

## Why's this needed? 
Cog1 engineerings mixing thing was pretty much not very efficient, so i added a pump! (pressure equalization moment)

## Changelog

```changelog
(u)Jimmyl
(+)Added a pump to cog1 engineering "Mixing West"
```

### CODE REVIEW

**Comment by Azrun** [comment]
Can you elaborate on your reason for change? This removes the ability to equalizer contents of connected canisters. This creates an entirely different engineering TEG experience compared to other maps.

**Comment by mc-oofert** [comment]
> Can you elaborate on your reason for change? This removes the ability to equalizer contents of connected canisters. This creates an entirely different engineering TEG (mixing) experience compared to other maps.
> 
> This kind of functionality makes more sense in toxins.

i dont remember anyone using it for equalizing

also you can just turn the pump off

**Comment by Azrun** [comment]
> i dont remember anyone using it for equalizing

What is everyone using it for?

> also you can just turn the pump off

The pump is one way, turning it off is the same as having the valve closed.

**Comment by mc-oofert** [comment]
what about
2021-12-26 17_16_27-goonstation  maps_cogmap dmm  - StrongDMM

**Comment by mc-oofert** [comment]
dont know how to merge conflict resolve

**Pull request closed without merging**
