### PR TITLE
Enables hunger motive on classic servers

### PR DESCRIPTION
**Pull request by Gannets**
## About the PR 

This PR enables the hunger motive for all players on classic servers.
It depletes at the same rate as the RP server hunger motive, you'll generally have to make time to eat twice in a 60 minute long round.
I tested this locally and it seemed to work fine, but I'm writing this at work and would appreciate some folks looking over this and making sure I didn't do it the dumb way.

## Why's this needed? 

I've long discussed how the Chef suffers from a lack of responsability. The crew don't need him and he doesn't need the crew. Sure, if they do cooperate, the chef can cook with more interesting ingredients and the crew gain access to more food buffs which is great. But they can just as easily ignore each other.

This PR would draw the crew together at the kitchen/cafe/bar roughly twice per round, a mandated lunch and dinner-time when crew naturally get hungry.

The Chef gets to spend the start of their round preparing for the lunch service, safe in the knowledge that their dishes will be eaten.
The crew have to take a small break from their work to head to a central location and spend 30 seconds eating food. (Shenanigans will likely occur during this time, in the same way that they do when the shuttle arrives.)

Note: There are numerous other ways for a crewmember to obtain food, so if a Chef isn't present or they don't want to stop what they're doing, they're welcome to head towards a vending machine or their lunhcbox or otherwise plan ahead expecting to be hungry once every half-hour.

## Changelog

```changelog
(u)Gannets
(*)Enabled the hunger motive on classic servers.
```

### CODE REVIEW

**Comment by frawhst** [comment]
your master branch has the funky VSC settings thing going on

**Comment by Gannets** [comment]
> your master branch has the funky VSC settings thing going on

Yeah, I cleaned it up on my pc but forgot to on my laptop. 😔

**Comment by NightmareChamillian** [comment]
I feel like this change would have to be tested pretty thoroughly and fleshed out MUCH more before added to main servers. 
RP servers hover around the 40-60 range, and are pretty relaxed, especially in antag activity, meaning chances are that the average RP chef is:

 A) probably going survive the full round or at least a majority of it

 B) able to cook for the entire crew, and 

C) obligated by the RP rules to at least try and do their job

 Goon1 is an entirely different world than RP. It can go up to 120 pop, has no such restrictions on antag behavior (and more antags to boot) or obligations for the chef actually cooking. While sous chefs do exist, goon1 has a pretty different jobslot setup than RP and can be rare.

What I'm getting at here is that we're looking at twice to three times the number of mouths to feed, way more antags who are also practically encouraged to dispose of the chef, and solid chances are that the one person who can cook probably didn't even want to be chef in the first place. This is a bad scene.

What I'd think would rectify this whole situation:
-Up the number of chef job slots to 2. Since goon has higher population than it used to and cooking is a really deep system that's woefully underexplored, this should happen anyway.
-Do what TG did and give the chef a bonus to combat while in the kitchen, so they have better chances of fighting off attackers
-Make it so you can't eat while full unless injured to stop shitters from running into kitchen and destroying all food

**Comment by flrsh** [comment]
I requested that Gannets let me close this in exchange for adding other, different incentives for chef + kitchen interactions. Please post your ideas in [this thread](https://forum.ss13.co/showthread.php?tid=18731); some things I've already been thinking about include adding announcement computers, a food and drink item of the shift, more food items in requisitons, and a player editable and orderable menu.

**Pull request closed without merging**
