### PR TITLE
Human Resprite: Monkey Base

### PR DESCRIPTION
**Pull request by Flaborized**
## he has no style, he has no grace 

Monkey sprites not by me! As far as I can tell they were started by Skeletonman0, worked on by Matheus after that and then finished up by Flourish and Virvatuli. I adjusted their feet a bit to fit shoes (made one foot smaller on the side sprites) because they needed it. 

These are updated monkeys to fit the [human resprite] . I'd like to get them done soon because there's a lot of dependencies based on this base, and I'm the one on the Trello card, so I'm doing it now. Would like to hear @flrsh 's thoughts first though before merging especially

The light code changes are to make hats and in-hands line up

### CODE REVIEW

**Comment by BatElite** [comment]
monki

They look cute enough not to solicit random violence.

**Comment by Sovexe** [comment]
How can we be expected to conduct science on monkeys if they are cute though

**Comment by Gannets** [comment]
They're perfect

**Comment by BatElite** [comment]
Geneticists will have no choice but actually find crew to do research on, and scientists will have to bribe sec for any antags they catch I guess. :P

**Review by Sovexe — APPROVED** [review]

**Review by flrsh — APPROVED** [review]
Very cute.

**Pull request merged**
