### PR TITLE
Flaborized sprites - hotdog cart, portable flasher, door buttons, brig timer, gift nuke

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
Flaborizes sprites - hotdog cart, portable flasher, door buttons, brig timer, gift nuke
image

## Why's this needed? 
new sprites

## Changelog

```
(u)Flaborized:
(+)New sprites for portable flashers, brig timers, door buttons, hotdog carts, and a special surprise!
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
do we really need to be storing all these old sprites?

**Comment by ZeWaka** [comment]
no flashing animation for flasher

**Comment by Flaborized** [comment]
@ZeWaka it does flash! it's just set to **Play once** so that it only flashes once, and this makes it only play once on the icon diffs :shelterfrog:

**Comment by Sovexe** [comment]
> do we really need to be storing all these old sprites?

Need to no, but I was unsure if they should be preserved for historical purposes like we've done with a few other ancient sprites

**Comment by Sovexe** [comment]
old sprites removed

**Pull request merged**
