### PR TITLE
Device sprites

### PR DESCRIPTION
**Pull request by binarysudoku**
#2397  About the PR 

## Why's this needed? 

Consistency / polish resprites of:
-Juicer (thank fuck)
-GPS
-T-Ray Scanner
-Microphones
-Microphone stands
-Monitor
-Camera

## Changelog

```
(u)Erinexx:
(+)Resprited some devices
```

### CODE REVIEW

**Comment by Flaborized** [comment]
very nice sprite s

**Review by Sovexe — CHANGES_REQUESTED** [review]
These are still in use
image

**Review by Sovexe — APPROVED** [review]
nvm there are new emp sprites in `grenade.dm` that this will enable

**Comment by Sovexe** [comment]
actually you need to fix the name of the grenades still. It's `emp1` in the new dmi and `empar` in the other

**Pull request merged**
