### PR TITLE
Resprites some dogs and adds some new ones.

### PR DESCRIPTION
**Pull request by CaioFrancisco**
[FEATURE]
## About the PR 

!!! THE ORIGINAL PR IS NOT MINE!      !!!
!!! IT WAS MADE BY SHMIGGY!             !!!
!!! THE SPRITES WERE MADE BY THEM !!!

Since their PR was automatically closed because of inactivity during a merge conflict, I asked them on Discord if I could adopt the PR. They allowed me to.

Screenshot_398

Their PR with the original description and replies is #11644.

## Changelog 

```changelog
(u)Shmiggy
(+)Resprites some dogs and adds some new ones. Being pet as a dog no longer knocks you out.
```

### CODE REVIEW

**Comment by wolfolotl** [comment]
the sprites are pretty rough, especially a lot of the sitting ones, which is part of why the original pr Sat until it staled. do you have any plans to touch them up?

**Comment by CaioFrancisco** [comment]
Well, not really. I assumed it was because there was a Merge Conflict, because the sprites were nice enough to be accepted, specially with all the support when the PR came out.

**Comment by ZeWaka** [comment]
> Well, not really. I assumed it was because there was a Merge Conflict, because the sprites were nice enough to be accepted, specially with all the support when the PR came out.

no, merge conflicts are trivial to fix - the PR was not merged because of sprite issues

i'm drafting this until those are resolved

**Comment by WALPVRGIS** [comment]
Whups, this is kinda my bad; I needed to do some Big Feedback but irl stuff has been a Lot the past couple of weeks. Looking to help work on this (or the original) PR soonish!

**Comment by WALPVRGIS** [comment]
> Well, not really. I assumed it was because there was a Merge Conflict, because the sprites were nice enough to be accepted, specially with all the support when the PR came out.

Sprites will need a lot of work before I'd be merging them, hence it waiting until I tied up some other things I am working on first.

**Comment by CaioFrancisco** [comment]
Oh, fair enough. I'll be closing this since my spriting experience and skills are close to none.

**Pull request closed without merging**
