### PR TITLE
More Gun Firing Animations

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Adds firing animations to the riot launcher, regular revolver, detective revolver (the cylinders spin!), derringer, faith, the tranq pistol, (the slide goes back!) the tranq rifle, the old hunting rifle, the AK 747 (the bolt slides back!), and the gyrojet (the slide doesn't go back because it doesn't do that). Also adds animation for the empty flare gun sprite which achieves the same effect since the capacity on the flare gun is zero.

gun_animations

## Why's this needed? 

Animation makes the game feel more alive! And little details make the game feel polished. It works well with other guns that already have this effect and I've wanted to spread it out more for a while now.

## Changelog

```changelog
(u)Flaborized
(+)Many more kinetic weapons will animated while firing.
```

### CODE REVIEW

**Comment by Eagletanker** [comment]
didnt the gyrojet not have any recoil at all?

**Review by Gannets — APPROVED** [review]
hell yeah

**Comment by BatElite** [comment]
You got me excited with the implication that we had a gun shaped like a little blobman, but now I must face the harsh reality that he's just there for demonstration purposes...

**Comment by DimWhat** [comment]
When will we get frog gun fire animations? :frog:

**Comment by Flaborized** [comment]
> didnt the gyrojet not have any recoil at all?

Hi this got merged already but to answer your question: no, doesn't seem that way. I did some (admittedly light) research including watching a video of someone firing one, it appears to have *less* recoil, not none at all. And if there's any recoil, I want to portray that since it adds a lot to the animation imo

**Pull request merged**
