### PR TITLE
Adds a new traitor item: cursed glue

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[FEATURE] [BALANCE] [ADD TO WIKI] [INPUT WANTED]
## About the PR 
Adds a bottle of cursed glue to the traitor buylist for 3TC.
When used on a player it glues a worn item onto them (sets `cant_self_remove` and `cant_other_remove`), the item glued depends on the users body targeting. It cannot be used on yourself. The glue can be flipped in hand to make it unglue all items on the target instead.
It has 5 uses, and the glue is only used up when actually sticking something down.

image image

Body part targeting works like this:
Either arm = gloves glued
Either leg = shoes glued
Chest = outer suit first, then jumpsuit
Head = helmet first, then mask, then glasses, then headset
Targeting drops through, so if a higher piece of clothing is already glued, then the next one down will be targeted. This allows panicked spam clicking to glue everything in that location.

This is a bit convoluted, but I wanted to make sure this was for sticking things to other people rather than preventing your own items being removed, and also restrict which slots items could be stuck to.

The only item the glue refuses to stick is straightjackets, because that feels a little too powerful. Blindfolds and muzzles work fine though.

Things the glue can't remove: cluwne, slasher, horse and waldo gear, anything with `cant_drop`. (Can't test waldo things so it gets a "probably works" if this ever comes up again)
All other cursed items can be removed using the glue (obsidian crown, syndicate hat etc.)
## Why's this needed? 
Pros:
- funny clothing related gimmicks
- the captain chasing a traitor around the station to get the glue bottle back with cat ears stuck to their head
- makes some underutilized matsci item effects more useful (telecrystal shoes anyone?)

Cons:
- possible to use this with a buddy to stick armour, headgear and so forth to yourself
- I'm not an artist so the sprite might not be great
- the long list of items this is extremely broken with that I haven't though of

## Changelog

```changelog
(u)LeahTheTech
(*)Added a new 3TC traitor item: cursed glue. Used to stick clothes to people.
```

### CODE REVIEW

**Comment by Kanthes** [comment]
Exceedingly funny idea.

Might be problematic with Magnetic Boots as well, as they prevent dragging when worn.

**Comment by alexeric123** [comment]
You can aggressive grab with magboots

**Comment by ThatFiveGuys** [comment]
You should be able to glue items and when someone picks those items up it becomes an item arm.

**Comment by TobleroneSwordfish** [comment]
> You should be able to glue items and when someone picks those items up it becomes an item arm.

That's how I originally imagined it, but it would be far too debilitating for the person who picks up a random item and would also make it an auto-buy for c-saber rampages etc.

**Comment by MetricDuck** [comment]
Tested on local:
- Cursed horsemask can be unequipped and placed in pocket. _Unintended?_ 
- Cultist robes & Tommys gear can be unequipped and messed with even with cant_drop. _Feels odd._
- Slasher and Waldo can be stripped entirely. _Slasher especially should probably get an exception._

Untested:
- Looks like it can entirely remove moustache / brass gauntlet / syndie clown / ancient armour / obby crown / owl suit / syndie hat / cursed amongus suit / hotdog suit. _This stuff seems fine IMO._
- Dawson and "The Smiling Man" can be stripped entirely. _I wasn't even sure how to spawn these so eh..._ 

Overall looks great though! Love the little animation

**Comment by NightmareChamillian** [comment]
Wouldn't it make more sense if it was magical glue?

**Comment by TobleroneSwordfish** [comment]
> Tested on local:
> 
> * Cursed horsemask can be unequipped and placed in pocket. _Unintended?_
> * Horse cultist robes & Tommys gear can be unequipped and messed with even with cant_drop. _Feels odd, consider making an exception for things with cant_drop. There's also an ishorse() proc._
> * Slasher and Waldo can be stripped entirely. _Slasher especially should probably get an exception. There's an isslasher() proc._
> 
> Untested:
> 
> * Looks like it can entirely unstick moustache / brass gauntlet / syndie clown / ancient armour / obby crown / owl suit / syndie hat / cursed amongus suit / hotdog suit. _This stuff seems fine IMO though I'm sure someone will find a way to abuse something._
> * Dawson and "The Smiling Man" can be stripped entirely. _I wasn't even sure how to spawn these so eh..._
> 
> Overall looks great though! Love the little animation

thanks for doing all that, I'll go through and add some more checks (I need to learn every is-something macro at some point, there are so many)

**Comment by TobleroneSwordfish** [comment]
I have added more checks and updated the PR to show all the cases I can think of. It can still remove Dawson and "The Smiling Man" clothing, maybe they should just have cant_drop anyway, not sure if that would break something.
>Wouldn't it make more sense if it was magical glue?

Most of the time things are stuck to you it's some kind of curse (horse mask, cluwne, adventure zone items), so I think cursed glue makes sense?

**Review by flrsh — CHANGES_REQUESTED** [review]
I think things are unremovable and removable for a reason, but more importantly, I don't like the idea of players forcing other players to wear things they might not want to wear, which this item would encourage.

**Comment by TobleroneSwordfish** [comment]
Well, yes, I can't really deny that this has potential for abuse, but there are already multiple ways to force someone to wear something (restraints, normal cursed items, mindslaving etc.) which can be abused in much the same way.
At the end of the day I understand not wanting to give admins more headaches.

**Comment by flrsh** [comment]
Yeah, there are other things that can be abused, but this uniquely and specifically encourages that sort of behavior. 

>At the end of the day I understand not wanting to give admins more headaches.

Basically yeah :shelterfrog:

**Pull request closed without merging**
