### PR TITLE
Add the crate manufacter to most maps

### PR DESCRIPTION
**Pull request by Carbadox**
[FEATURE]

## About the PR 
Adds the crate manufactor to Atlas, Clarion, Destiny, Cog1, Cog2, Horizon and Oshan

## Why's this needed? 
It's a good feature and belongs in other maps as well

## Changelog
```
(u)Carbadox
(*)Added the crate manufactor to Atlas, Clarion, Destiny, Cog1, Cog2, Horizon and Oshan
```

### CODE REVIEW

**Comment by MarkNais** [comment]
Changelog busted.
Love this change.

**Comment by Carbadox** [comment]
Note : I didn't add one to Donut3 and Kondaru since their respective creators should probably make that decision

**Comment by UrsulaMejor** [comment]
Not a fan of the placement on Horizon; specifically, it being right in front of the APC terminal that peeps might not know at a glance that they can mess with it at that distance. Might be good to revert and inform Warc so they can mess with it themselves

**Comment by MarkNais** [comment]
Many wall mounted items are placed behind tables etc. I don't think that should be a "stopping" factor of the merge; but having Warc review/place it would be kind to her.

**Comment by Carbadox** [comment]
Is that in regards to all maps or just Horizon, Mark?

**Comment by MarkNais** [comment]
> Many wall mounted items are placed behind tables etc. I don't think that should be a "stopping" factor 
All maps.
> but having Warc review/place it would be kind to her.
Horizon specific.

**Comment by Carbadox** [comment]
that should fix the merge conflict

**Pull request merged**
