### PR TITLE
Borgs and AI can sing too

### PR DESCRIPTION
**Pull request by ausLancaster**
## About the PR 

- Borgs and AI can now sing too!
- They have their own icon and styling 

## Why's this needed? 

Equal opportunity for our synthetic friends.

## Changelog

```
(u)austin:
(+)Borgs and AI can now sing too.
```

### CODE REVIEW

**Comment by Carbadox** [comment]
How would this interact with VOX, if it does?

**Comment by ThePotato97** [comment]
Each PR should be a new branch

**Comment by ThePotato97** [comment]
> How would this interact with VOX, if it does?

It doesn't and shouldn't

**Comment by ausLancaster** [comment]
> Each PR should be a new branch

Should I make a new one?

**Comment by ThePotato97** [comment]
> > Each PR should be a new branch
> 
> Should I make a new PR?

Yeah make a new PR and transfer your changes from this

**Pull request closed without merging**
