### PR TITLE
Updated the sprite for the Ignition-switch.

### PR DESCRIPTION
**Pull request by Enderthunder**
## About the PR 
This is my attempt on a resprite of the Ignition-button,
as well as the science "eject" button as they both share the same sprite.
The work includes a total of 4 total frames, and gives it a small 5("7") frame animation. 
Personally i think it turned out great, altho the motif is now changed from a button, to a lever.

## Why's this needed? 
Sov had written under the "Wanted assets" that the Ignition button was one of the items which was due for a resprite,
so I wanted to take a gander and have a go at it. 

## Changelog

(u)Owari
(+)Resprited the Ignition button and gave it a small animation.

Ignition Lever
test

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Could you please put some images of the sprite in your .dmi editor and in-game in your description?

**Comment by Enderthunder** [comment]
> Could you please put some images of the sprite in your .dmi editor and in-game in your description?

Ignition Lever

**Comment by Enderthunder** [comment]
> Could you please put some images of the sprite in your .dmi editor and in-game in your description?

As this is my first ever PR, im going to be totally honest, ive got no clue on how to make a private server.

**Comment by BatElite** [comment]
If you've got vscode set up, launching a local server should just be pressing F5 and waiting for the thing to compile.

**Comment by Enderthunder** [comment]
> If you've got vscode set up, launching a local server should just be pressing F5 and waiting for the thing to compile.

oh well thats nice to know

**Review by Tarmunora — CHANGES_REQUESTED** [review]
~~Animated sprite has some stray white pixels~~
apparently this is the icondiff bot bugging out. wack

**Review by Tarmunora — APPROVED** [review]

**Comment by ZeWaka** [comment]
not a big fan of this for a button - a button should be a button and not like a knife switch

**Comment by Enderthunder** [comment]
> not a big fan of this for a button - a button should be a button and not like a knife switch

As i answered on discord earlier yesterday i will attempt to resprite it as an actual button at a later date

**Comment by Gannets** [comment]
> 
> 
> not a big fan of this for a button - a button should be a button and not like a knife switch

We could rename it to "ignition switch"

**Pull request closed without merging**
