### PR TITLE
Add the saxophone bit from "Who Can It Be Now"

### PR DESCRIPTION
**Pull request by tloy-x**
[SOUND]

## About the PR 
Adds the saxophone bit from "Who Can It Be Now" by Men at Work.

## Why's this needed? 
Do I really need to explain?

## Changelog

```
(u)tloy-x:
(+)Added the saxophone bit from "Who Can It Be Now"
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
What's the licensing on the sound clip supplied?

**Comment by tloy-x** [comment]
I would assume the same as "Careless Whisper", which is already in the game. Unless Goonstation has the rights to that, in which case I'll drop the PR.

**Comment by ZeWaka** [comment]
I don't think adding more stolen content to the game is the right move here.

**Comment by tloy-x** [comment]
Understandable

**Pull request closed without merging**
