### PR TITLE
Fix bug where you could clone someone that was just cloned

### LINKED ISSUE #2222: Clone's consciousness can be ripped away by borging the old body
[BUG] [MAJOR]

**Describe the bug**
If you borg a person's corpse after they've been cloned, it will rip their consciousness out of their new body and into the borg.

**To Reproduce**
1. Clone a dead person
2. Ensure they are now alive in the new, cloned body
3. Debrain the corpse and place the brain in a cyborg
4. Activate the borg
5. The player's consciousness is now in the borg, and they can no longer control their cloned body.

**Expected behavior**
After cloning the person, their old brain should be "cold", and placing it in a cyborg should do nothing.

**Additional context**
Examining the old brain after the person has been cloned will show that the brain is "still warm".

### LINKED ISSUE #2361: Cloning an existing human
Submitter: palpetinus
**Describe the bug**

A character called Eric Marten died once. I took his brain and cloned him in the body of a monkey. While he was still alive, I was able to take his brain again, put it into a monkey a second time (same monkey, I took the brain out meanwhile) and clone him while he was still alive. This causes his consciousness/mind to be ripped from the correct, alive character into the clone.

**To Reproduce**
I've never had this bug otherwise, so I'm not sure what led up to it.
1. Take the brain from a corpse
2. put it into a monkey
3. put the monkey into the cloner, clone it
4. take the brain out of the monkey and put it back into the monkey. The "mind" of the player is now transferred from the alive character into the dead monkey again
5. clone the monkey a second time

**Expected behavior**

The cloner should give the error "Can't clone: Unable to locate mind." when the player is still alive.

**Screenshots**
That's kind of an impossible thing to screenshot properly.

**Additional context**
The cloner was just recently updated into a new interface, that might be it.

Reported on: Goonstation 2020-10-05 18:12:52

### PR DESCRIPTION
**Pull request by flrsh**
[MAJOR]

## About the PR 

Fixes #2361, probably. Also probably fixes #2222. Basically, the mind was never transferred properly (i.e. nulled) from the old brain, but now it is. 

## Why's this needed? 

Bugs bad. 

## Changelog

```
(u)Flourish:
(+)Fixed the bug where you could clone someone that was just cloned. 
```

### CODE REVIEW

**Review by mordentware — APPROVED** [review]

**Comment by mordentware** [comment]
Add changelog I guess?

**Comment by mordent-goonstation** [comment]
Changelog?

**Review by mordent-goonstation — APPROVED** [review]

**Comment by flrsh** [comment]
> Changelog?

Oh good point. I'll do a minor log.

**Comment by kak0phony** [comment]
Nice!

**Pull request merged**
