### PR TITLE
Resprites disposal pipes

### PR DESCRIPTION
**Pull request by Flaborized**
## what? 

Resprites disposal pipes.

## why? 

The current ones are very banded and Dated Looking assets imo, this seeks to improve them.

## Changelog

```changelog
(u)Flaborized
(+)Resprited disposal pipes.
```

### CODE REVIEW

**Comment by Azrun** [comment]
I felt like there was a nice grimy quality to the old images, but these are way better in providing both a sense curvature and perspective.

Should pipe-t and conpipe-t North directions have the inner diameter highlight on the lower part? Or does that just make it look funny since that wall of the pipe doesn't go all the way down?

**Comment by Flaborized** [comment]
I'm sure they would look fine with the highlight on the lower part instead of the top, I did them this way because I wanted the light source to look like it's from a consistent direction.

**Comment by comradef191** [comment]
Booted up StrongDMM and threw together an example of various pipes that just set the `color` var
With and Without out the Resprite, the hallway above Security on Horizon:
PipeComparison

**Comment by BatElite** [comment]
Oh hey these aren't as dark as I anticipated they'd end up, nice!

Not liking the way the open end on loose pieces look, but people don't leave spare piping lying around so that's not a big issue. I do think making the broken pipes over half a tile is a problem, since opposing broken pieces will end up bridging the tile.

**Comment by Flaborized** [comment]
> I do think making the broken pipes over half a tile is a problem, since opposing broken pieces will end up bridging the tile.

pushed a fix to this, ty for pointing out!

**Review by Sovexe — APPROVED** [review]

**Pull request merged**
