### PR TITLE
Reagents are now clamped to the nearest 1000th, or 0.001

### PR DESCRIPTION
**Pull request by F-OS**
[CLEAN] 
## About the PR
This PR adds clamping in update_total to resolve long-standing bugs in which reagents would reach infinitesimally small levels. 

## Why's this needed?
1.37262e-19 grog bad

## Changelog

```changelog
(u)Fosstar
(+)Reagents are now clamped to the nearest 1000th, or 0.001
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
I feel like it should be higher

**Comment by F-OS** [comment]
> 
> 
> I feel like it should be higher

The very low number was chosen to reduce impacts on stuff like botany and SR pills. I understand where you're coming from, and I'm willing to change it, but there's a lot to consider here seeing as chemistry is a system where slight changes can cascade into balance fuckery

**Comment by ZeWaka** [comment]
> > I feel like it should be higher
> 
> The very low number was chosen to reduce impacts on stuff like botany and SR pills. I understand where you're coming from, and I'm willing to change it, but there's a lot to consider here seeing as chemistry is a system where slight changes can cascade into balance fuckery

Extremely true, but people really don't need 100,000 doses of SR. Perhaps `0.001`

**Comment by Adharainspace** [comment]
quantities smaller than 1u dont even react to form recipes. this is only useful for homeopathy. and you dont need a amount that low, it doesnt need to be this low really, id suggest the nearest thousandth (.001) for clamping.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
