### PR TITLE
Removes references to NASSA

### PR DESCRIPTION
**Pull request by Eagletanker**
## About the PR 

Removes all references to the NASSA suit and it's helmet, and give it the new name Dava.

## Why's this needed? 
Following a discord conversation with Hukhukhuk about where the suit name came from, it's best to change it.
No changelog needed.

### CODE REVIEW

**Comment by Vaskritaya** [comment]
This touches a number of maps which are old an unmaintained, like damaged manta, old trunkmap, 2018 xmas oshan, etc. You're not expected to make commits to them when changing things like paths.

**Comment by Eagletanker** [comment]
> Why/what is Dava
Professor Dava Newman works at MIT and[ as of 2019 is developing a actual version](https://www.usatoday.com/story/news/nation/2019/07/19/50-years-after-apollo-11-nasa-may-use-skintight-space-suit-future/1768544001/) of what I believe the suit to be, which is a functional Mechanical Counter Pressure space suit (hence why its mpcsuit in code). Pretty much, they work by compressing your body to regulate pressure in space, and allows greater survivability if your suit gets breached, as it gives you what is basically a hickey instead of killing you from a loss in suit pressure. It also makes EVA less straining compared to Soft Suits and Hard Shell Suits. It's a working title pretty much, and I'm up to changing it to something better.

**Comment by Sovexe** [comment]
this PR seems to have several totally unrelated changes bundled in

**Comment by Eagletanker** [comment]
> this PR seems to have several totally unrelated changes bundled in. These will need to be corrected before this can be considered
Yep, that's why I'm gonna close this upon someone deciding if it should be changed or not. The huge pr size is unintentional, I'll create a new branch after this to fix it

**Pull request closed without merging**
