### PR TITLE
Adds A Wraith Fighting Kit

### PR DESCRIPTION
**Pull request by Wisemonster**
[BALANCE] [FEATURE] [INPUT WANTED]

## About the PR 
This adds in a secure crate that contains some new items. The ecto blaster, which uses ectoplasm to fire energy bolts that force wraiths to become corporeal, and the advanced ectoplasmoleic imager, a more powerful version of the goggles that the ghost buster uses that can see wraiths and poltergeists. Comes with a box full of ectoplasm blob ammo for the Ecto Blaster, and some auto-injectors of strange green goop to help see the wraith. Ectoplasm blobs now require freezing ectoplasm in a container in order to get the blob. Also changes some back end things with invisibility. Neither the guns nor the goggles can be mech scanned. I also made strange green goop able to see wraiths, in case the goggles are lost.

## Why's this needed? 
Currently, the only counter-play to wraith is hoping they mess up in some way, whether it be crossing salt or corporeallizing in a bad location. This kit intends to add in a more proactive way of fighting a wraith that adds in some level of counter play. The change to ectoplasm blobs is to prevent infinite ammo with the blaster with gas duping. I also think it fits nicely.

## Changelog

```changelog
(u)Wisemonster
(*)The scientists at NanoTrasen have been able to invent and ship out some gear to allow security personal to deal with the less-than-physical threats. Available in each armory, see minor changes for details
(+)Adds a security restricted crate that contains 3 items, the ecto blaster, the advanced ectoplasmoleic imager, a box of ectoplasm balls, and 3 auto-injectors of strange green goop.
(+)The ecto blaster fires special energy bolts that force wraiths and poltergeists to become corporeal for a short amount of time. Is requires ecto plasm in order to fuel it.
(+)The advanced ectoplasmoleic imager is able to see wraiths, as opposed to it's lesser version that only sees ghosts.
(+)Ectoplasm now requires chilling at least 20 units in an open container in order for it to turn into an ectoplasm ball
(+)Strange green goop now let's you see wraiths as well as ghosts
```

### CODE REVIEW

**Comment by Wisemonster** [comment]
I set this as a draft until I get some feedback of whether this should be just a security crate, or a qm security purchase.

**Comment by Eagletanker** [comment]
Ecto goggles work as thermals

**Comment by Wisemonster** [comment]
> Ecto goggles work as thermals

If that's the case, I guess it'll have to be restricted to the armory. Otherwise I'd have to rewrite the vision code, and that seems like a monumental task atm.

**Comment by Wisemonster** [comment]
> Why separate out wraith visibility from ghosts and make a second flavour of ghost goggles? AFAIK the regular one is azone loot so it's not like it's going to be around without effort (plus I think some people actually fetch it for wraith combat)

The reason for separating the wraith vision from the normal goggles is so during Halloween, wraiths can't be spotted round start from ghost busters. Also, before this pr, no goggles could actually see the wraith while it's incorporeal. I believe this is due to a fix for the aforementioned issue with ghost busters.

**Comment by Wisemonster** [comment]
I could replace the azone goggles with the advanced goggles, although without the ecto blaster it's rather limited in what it can do.

**Comment by Wisemonster** [comment]
!merge_upstream

**Comment by Wisemonster** [comment]
I believe this pr is ready for review, unless there is some outstanding issues in it.

**Comment by Wisemonster** [comment]
Also, I'm not sure if it's an issue, but some of the changes to the maps are from other prs being merged. I don't think it's a problem?

**Comment by flappybatpal** [comment]
At a face level this seems like it would be extremely powerful against a wraith? Their methods of fighting back are quite awkward unless in revenant form. Perhaps their ability to trivially escape through walls would make it less dangerous than it sounds.

**Comment by Wisemonster** [comment]
> At a face level this seems like it would be extremely powerful against a wraith? Their methods of fighting back are quite awkward unless in revenant form. Perhaps their ability to trivially escape through walls would make it less dangerous than it sounds.

Currently, the gun makes the wraith corporeal for about 1.5 seconds, and requires 20 units of ectoplasm per shot. I could adjust the time the gun makes the wraith corporeal if it's too long, or raise the gun to use 25 units so it only gets 4 shots max, instead of 5. Or a mix of both could be implemented

**Comment by Wisemonster** [comment]
I'm gonna close this for now, might re-visit it later

**Pull request closed without merging**
