### PR TITLE
set_dir proc for atoms, refactors every existing case of dir = to use it

### PR DESCRIPTION
**Pull request by Adharainspace**
[CLEANLINESS] [ENHANCEMENT]

## About the PR 
(the title is hopeful)
ok so all i really did here was add a new proc to atoms and change all instances of dir = to be set_dir()
i also made all atoms send a signal in set_dir if the dir actually changes.
i also made all atom/movables update medium/medium directional lights on set_dir if they have them
i also made all mobs update directional lights on set_dir if they have them

so i think i fixed a few bugs? one where sometimes flashlights/directional lights in pods wouldnt update correctly
and one where dirlocked was worse than useless
this all comes at the cost of performance. how much? idk. cant profile accurately on my own so lets do the time honoured tradition of just merging it if its good to go and seeing how much it ruins the game. 

it compiles cleanly and nothing seems to be obviously broken. 

special thanks (<3) to tarm for writing the reginald expression i used to make my life less difficult (was still like 5 hours of raw work though EW)

## Why's this needed? 
having a wrapper for setting dir is good, it means that anything that wants to listen to that (like a ptl gun?? 👀) doesnt have to do any weird ugly signal or proc stuff. and it can just listen to the set_dir signal. 
also this fixes a few minor bugs. 

## Changelog

```
(u)adharainspace:
(*)makes directional lights update more consistently when you change direction
```

### CODE REVIEW

**Comment by Adharainspace** [comment]
heres some files where the changes arent just dir -> set_dir
code/atom.dm
_std/defines/component_defines.dm
code/modules/interface/mob_input.dm
code/mob.dm

**Comment by Kyle2143** [comment]
I'm very slightly concerned about performance here. Proc overhead is not usually a big deal, but this will be called any time an atom changes dir. 

I can't find the set_dir proc declaration since I'm on my phone, but is it possible that it's short enough just to make a define?

**Comment by ZeWaka** [comment]
> I can't find the set_dir proc declaration since I'm on my phone, but is it possible that it's short enough just to make a define?

not possible due to inheritance

**Comment by Adharainspace** [comment]
id be up for a test merge for one round and then a revert, tbh. profile the round, or see if it causes visible lag?

**Comment by pali6** [comment]
I doubt it will be significant performance hit. And it can always be reverted.

**Comment by ZeWaka** [comment]
@Tarmunora failed merge

**Comment by Tarmunora** [comment]
I know 😔

**Pull request merged**
