### PR TITLE
Mobifies Repairbots

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Mobifies ancient repair bots and its subtypes.
They will only attack people who aren't incapacitated and are immune to stuns but have little health.

## Why's this needed? 
Object critter bad.

### CODE REVIEW

**Comment by kremlin-** [comment]
unsubscribe

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Please don't just shove the shade changes in here, it makes it much harder to review and merge.

**Comment by CheffieGithub** [comment]
shade changes gone

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Killing the security variant seems to consistently cause this runtime from `hands.dm`:
image
Other than that this looks good, will require secret changes when merged.

**Pull request merged**
