### PR TITLE
Aw shit, here we light again

### PR DESCRIPTION
**Pull request by Laboredih123**
[PERFORMANCE][INTERNAL]

## About the PR 
Same thing as last time 
Fixes the problems of #20623

## Why's this needed? 
slow bad, crash *really* bad

### CODE REVIEW

**Comment by klookiyam** [comment]
What was causing the crash/slowdown in the pr that was reverted?

**Comment by ZeWaka** [comment]
> What was causing the crash/slowdown in the pr that was reverted?

feel free to tell us

**Comment by Laboredih123** [comment]
what

**Comment by klookiyam** [comment]
Sorry I'm dumb, didn't realize this was the test merge to diagnose the issue.

**Comment by Laboredih123** [comment]
nooooo

**Comment by ZeWaka** [comment]
x

**Comment by Laboredih123** [comment]
shush it

**Comment by Laboredih123** [comment]
grrrrrrrrrrrrr

**Pull request closed without merging**
