### PR TITLE
Adds inhand sprites for mate gourds

### PR DESCRIPTION
**Pull request by colossusqw**
[LABEL]

## About the PR 
This PR adds sprites to mate gourds

## Why's this needed? 
Sprotes >:)

### CODE REVIEW

**Comment by colossusqw** [comment]
image

**Review by Tarmunora — CHANGES_REQUESTED** [review]
shouldn't you also y'know... use the new sprite?

**Comment by colossusqw** [comment]
> 

Well, from all the times i booted up the private instance the item already uses it, so i thought it was working as intended?

**Comment by Tarmunora** [comment]
ok yeah i just don't know how item-state works :lazy:

**Pull request merged**
