### PR TITLE
Wrestlemania ranch

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
Adds a ranch to Wrestlemania, which was missing

## Why's this needed? 

We about to have a event, I think the event map should meet guidelines when its being used, hence the mid freeze PR

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Changelog is default

**Review by flrsh — CHANGES_REQUESTED** [review]
~~But the feature freeze image~~

Could you make the ranch more curved so that it blends in better with the rest of the map? Right now it's sticking out too much because it's too square. More space-adjacent windows would also be good. 

I'll merge this PR, but please relay any additional Wrestlemap changes / fixes to me so I can directly make them.

**Review by cheekybrdy — COMMENTED** [review]
Should have fixed its problems, no ranchers spawning in arrivals!

**Comment by cheekybrdy** [comment]
Looking into an issue with the vertical ones, I can solve where the railings aren't with invisible railings, but I can't see any vars which can make the diagonals not put railings in unintended positions when changing the dir var. Any ideas?

**Comment by flrsh** [comment]
Looks like you made some changes to `code/__secret_public.dme` which you'll have to revert. Ranch looks good to me though!

Re: railings, I'm not sure - maybe @Sovexe would know?

**Review by flrsh — APPROVED** [review]

**Pull request merged**
