### PR TITLE
Removes the food synth from space bux purchase

### PR DESCRIPTION
**Pull request by DimWhat**
[Removal]

## About the PR 
Removes the food synth from space bux purchase. This will make getting food and bottles more difficult and lower the amount of _good_ purchases available with space bux.

## Why's this needed? 
The food synth is an incredibly powerful item only balanced by the fact you need to expend borg cell charge to create the food. This is entirely circumvented by being able to purchase the food synth at round start with space bux. This item is able to infinitely heal an injured player because food heals injuries, able to infinitely provide many good food buffs including regeneration, and the ability to create infinite glass containers, and completely circumventing the need for going to get food and water on the RP. Something as powerful as the food synth goes against the entire point of space bux.

## Changelog

```changelog
(u)DimWhat
(*)Made the food synthesizer no longer available for purchase with space bux.

### CODE REVIEW

**Review by Sovexe — APPROVED** [review]
Code is fine

**Comment by flappybatpal** [comment]
Think this is a good move, while it's funny to spam hamburgers on non RP we need to make the chef more valued overall.

**Comment by UrsulaMejor** [comment]
if you wanna dispense infinity burgers, being a borg is fun and good.

**Comment by Flaborized** [comment]
good imo

**Comment by unfunnyperson** [comment]
Inf glass, healing if parried with survivalist, and food buffs. needs to go

**Pull request merged**
