### PR TITLE
Sorted gun.dmi and deleted the old and unused sprites and code

### PR DESCRIPTION
**Pull request by Enderthunder**
## About the PR 
This PR removes old and unused sprites from the gun.dmi file.
aswell as removing the disruptor and the Waltery submachinegun from the game code.

## Why's this needed? 
Cleaning up both in code and in sprites will hopefully make it easier to navigate, find, and edit sprites.
It also removes clutter and unused content.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Should be deleted if not used.

**Comment by Enderthunder** [comment]
> Should be deleted if not used.

welp then youre the second admin saying so, and so it shall be

**Comment by Gannets** [comment]
I'd maybe update your pr description "about this pr" to be more descriptive about what this PR actually involves, that'll make it easier when someone comes to merge/close this.

For example: "This PR removes old & unused icons from gun.dmi"

**Comment by Enderthunder** [comment]
> I'd maybe update your pr description "about this pr" to be more descriptive about what this PR actually involves, that'll make it easier when someone comes to merge/close this.
> 
> For example: "This PR removes old & unused icons from gun.dmi"

yeah no youve got a point there. i was not very descriptive

**Comment by DimWhat** [comment]
I believe you deleted more than you should have. Starting from top to bottom of the icondiffs:

1. The rockit launcher sprite which is currently used but hidden away in the debris field.
2. The staplegun which is used for staple guns in surgery.
3. The teslacannon, this one is a maybe cause it's used for an admin weapon. Might be unused
4. I'm like 90% sure the Tommy Gun sprites are used by the tommy gun admin weapon. 
5. The walthery is for an old weapon. Could probably delete the whole gun in the code as well.
6. Disruptor is an old unusued gun. Again could be deleted
7. The paintball guns were a thing back in the day but I believe they got taken out of player hands at some point. Still in the code.
8. Keep frog. It's for an admin gun
9. You can buy an incapacitator from the flock guys in debris field.
10. NTstun is for the NTSpecO gun. Would be bad if people were to spawn with an invisible gun.
11. You set the Deagle's empty animation to looping by accident. Should only play once.
12. Ecto is for an unused gun that shot ectoplasm. I honestly think this sprite would be better for the ghost gun as that one looks pretty bad.

**Comment by Enderthunder** [comment]
> I believe you deleted more than you should have. Starting from top to bottom of the icondiffs:
> 
> 1. The rockit launcher sprite which is currently used but hidden away in the debris field.
> 2. The staplegun which is used for staple guns in surgery.
> 3. The teslacannon, this one is a maybe cause it's used for an admin weapon. Might be unused
> 4. I'm like 90% sure the Tommy Gun sprites are used by the tommy gun admin weapon.
> 5. The walthery is for an old weapon. Could probably delete the whole gun in the code as well.
> 6. Disruptor is an old unusued gun. Again could be deleted
> 7. The paintball guns were a thing back in the day but I believe they got taken out of player hands at some point. Still in the code.
> 8. Keep frog. It's for an admin gun
> 9. You can buy an incapacitator from the flock guys in debris field.
> 10. NTstun is for the NTSpecO gun. Would be bad if people were to spawn with an invisible gun.
> 11. You set the Deagle's empty animation to looping by accident. Should only play once.
> 12. Ecto is for an unused gun that shot ectoplasm. I honestly think this sprite would be better for the ghost gun as that one looks pretty bad.

probably, then again hard to get feedback when there are so many guns

**Comment by Enderthunder** [comment]
honestly thanks dimwhat, this feedback is priceless

**Comment by Enderthunder** [comment]
fixed all your mentioned points dimwhat, except nr 5, 6 and 12, as i dont really have an executive say in these things

**Comment by Enderthunder** [comment]
im doing this all wrong and i pardon myself if this becomes a mess, i guess its too early for me to be doing code...

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
