### PR TITLE
removes capsaicin from nicotine free cigs

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
## About the PR 

nicotine free cigarettes are no longer full of capsaicin

## Why's this needed? 

improves detective RP. makes them no longer strictly worse than regular cigarettes.

## Changelog 

```changelog
(u)gus
(+)Nicotine free cigs no longer have capsaicin, what the fuck?
```

### CODE REVIEW

**Comment by 444Portal** [comment]
why not just use the Smoker trait?

**Comment by itsloley** [comment]
i’m personally a big fan of this, it feels pretty bad being punished with stuns and drops (especially as a security role) just for trying to look cool without wanting to deal with the repercussions of nicotine addiction if you didn’t build your character with this specifically in mind

**Comment by OfficialSpoodle** [comment]
Eh, it's nice to have capsaicin for hobo chemistry, and plus I like the stupid lil gag. I agree with Minty too. You can either pick the smoker trait, or deal with the nicotine addiction.

**Comment by Glamurio** [comment]
If someone were to add nicotine cigs nowadays everybody would ask "Why does it contain capsaicin?", and following that logic I think this is a good change.

**Review by Glamurio — APPROVED** [review]

**Comment by Sbmhawk** [comment]
git moment.....

**Pull request closed without merging**
