### PR TITLE
Cog1 Upload Adjustments

### PR DESCRIPTION
**Pull request by Wisemonster**
[MAPPING] [BALANCE]

## About the PR 
This pr remodels the Cog1 upload to be a bit more secure.

goonstation  maps_cogmap dmm  - StrongDMM 3_7_2023 1_00_48 PM

## Why's this needed? 
The current upload is rather insecure, especially with the lawrack being next to a wall. This aims to make the upload more secure, and a bit more risky to go into if the AI is rogue.

## Changelog 

```changelog
(u)Wisemonster
(+)Cog1's Upload Chamber has been remodeled to be a bit more secure.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
I'm not too down on the concept of moving it to the middle considering cog1 is getting rogued through the wall constantly on Classic right now but I don't think the glass and door should be removed.

**Comment by Wisemonster** [comment]
I could re-add the thindows and thindow door, although it seems like we've been trying to phase out thindows/thindow doors, that's why I removed them.

**Comment by TobleroneSwordfish** [comment]
The glass door section is weird, since it means that to access the turret controls you have to put yourself in a little airlocked section where you can be shot by lethal turrets and the AI can lock the door behind you, afaik no other map works like this.

**Comment by CheffieGithub** [comment]
I was the one who suggested the thin stuff removal on discord mainly due to what was said about the turrets, and that the thindoor would make unrouging very easy

**Comment by Wisemonster** [comment]
> The glass door section is weird, since it means that to access the turret controls you have to put yourself in a little airlocked section where you can be shot by lethal turrets and the AI can lock the door behind you, afaik no other map works like this. Although since you've moved the turret controls outside it's probably fine to keep it.

Do you mean to keep the glass door and thindows? Do keep in mind that the windows can be unscrewed to act as makeshift barriers against the turrets if they are set to taser mode.

**Comment by CheffieGithub** [comment]
I don't think Toblerone is saying to keep the thindows, reads more like a case against them. Also just a thought, perspective lights would be nice.

**Comment by Wisemonster** [comment]
Alright, added perspective lights, but I had to move them down to prevent the right side's lights from overlapping with the intercom.

**Review by Sord213 — CHANGES_REQUESTED** [review]
Screenshot_222
Could you fix the errant area (red X), and make it so the door is in the AI Upload area (yellow circle)

**Pull request merged**
