### PR TITLE
Adds empty gas tanks to the general manufacturer

### PR DESCRIPTION
**Pull request by TealSeer**
[FEATURE] [GAME OBJECTS] [SPRITES]
## About the PR 

Re-sprites the base gas tank, adds missing worn and inhand sprites, and adds a recipe for it costing 0.1 sturdy metal to the general manufacturer.

Old (left) vs new (right) sprite comparison
image

Worn sprite
image

Inhand sprite
image

## Why's this needed? 

Not being able to get an empty gas tank to use without either having access to a place with a tank dispenser or scavenging one from o2 lockers sucks, and you can already manufacture empty canisters at the general manufacturer. 

## Changelog 

```changelog
(u) TealSeer
(+) Empty gas tanks can now be made at the general manufacturer for 0.1 sturdy metal.
```

### CODE REVIEW

**Comment by DimWhat** [comment]
I'd like to request a monkey version for parity.

**Comment by TealSeer** [comment]
@DimWhat where do those sprites live? I'll do one

**Comment by DimWhat** [comment]
@TealSeer Monkey sprites are found in icons/mob/monkey/back.dmi

**Comment by CheffieGithub** [comment]
I would make a subtype rather than use the tank parent

**Comment by TealSeer** [comment]
> Maybe a sprite for this one when its attached to a TTV?

oh I forgot to include pictures in the OP but it does have a TTV sprite it looks like this:
image

**Comment by TealSeer** [comment]
> I would make a subtype rather than use the tank parent

actually yeah probably a better idea

**Comment by MeggalBozale** [comment]
yum easier ttv production (not really an issue though)

**Review by kbsmilk — APPROVED** [review]

**Review by CheffieGithub — APPROVED** [review]

**Pull request merged**
