### PR TITLE
Rearrange the Oshan Bar

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [QOL] [CATERING]
## About the PR
Moves the oshan bar south a bit so that it hugs the wall, and moves the kitchen entrance up to the north side. The north side of the bar now is much more spacious and is nicer to sit in.
Adds a chemaster and a reagent extractor to the bar against the south wall.
Changed the floor tiling slightly to match the new position.
Made the bar less round and gave it a normal 90 degree corner, for more space/mobility.

## Why's this needed?
QOL for bartenders. More equipment, and more space. Plus people can now sit comfortably against the top edge of the bar and reach stuff like the claw machine without have to squeeze through a 1 tile wide gap.

## Changelog
```changelog
(u)Tyrant, GreenJelly
(+)The Oshan bar has been rearranged to be more spacious.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
I'm not gung-ho about these changes, the bar loses all of its aesthetic appeal to me in favour of homogenising it with literally every other map's bars; especially with squaring off the bar counters and moving it away from its centralised location.

**Review by flrsh — CHANGES_REQUESTED** [review]
I like the current bar layout and would like it to stay as it is. I don't think reagent extractors are necessary, but if you'd like to add a chemaster, I think you could add it to the kitchen nearish the bar entrance (e.g. replace food processor with chemaster, replace crate with peach rings with food processor, put peach rings + misc in one of the crates in the carpeted backroom).

**Comment by CheffieGithub** [comment]
The chemmaster and reagent extractor seems to be for parity with other bars and makes sense since oshan is a high pop map.
I like the layout changes myself, the top section is currently a squeeze and these changes look like it will have better flow. but it does lose uniqueness without the central bar.

There is an accidently removed hazard stripe below the north bar door into the hallway and the glass recycler placement is a downgrade since its no longer public.

Another plus is no disposal pipes under walls.

**Comment by TheTyrant25** [comment]
> I like the current bar layout and would like it to stay as it is. I don't think chemasters are necessary, but if you'd like to add a reagent extractor, I think you could add it to the kitchen nearish the bar entrance (e.g. replace food processor with reagent extractor, replace crate with peach rings with food processor, put peach rings + misc in one of the crates in the carpeted backroom).

might as well start a whole new branch then

**Comment by TheTyrant25** [comment]
sequel in the form of  #15720 has been posted

**Pull request closed without merging**
