### PR TITLE
Fixes being able to see into the Donut 2 AI Upload using cameras

### LINKED ISSUE #12641: Able to see into AI upload with security cameras on Donut 2
### Labels

[BUG][MINOR]

### Description

Recent changes made it so you can't see into AI upload with security cameras, but you still can on donut 2.

### Steps to reproduce

Open the Security Cameras console
Select ''AI Upload''

### Expected Behavior

Not able to see into AI upload with security cameras console.

### Additional Information & Screenshots

I believe this is a bug, since it was changed so you can't see into AI upload anymore in other maps.

Reported by: ThatScarlett
On server: Goonstation 4 Roleplay: Sylvester
Round log date: 2023-01-06-05-10
Reported on: 2023-01-06 05:45:36
Map: DONUT2

### PR DESCRIPTION
**Pull request by goonstation-enjoyer**
[OBJECTS]
## About the PR 
Fixes being able to see into the AI Upload using cameras

## Why's this needed? 
Consistency, can't see into the AI upload on any other station.
Fixes #12641

### CODE REVIEW

**Comment by goonstation-enjoyer** [comment]
Second or third time in a row I forget labels, the machines are making me lazy.

**Comment by goonstation-enjoyer** [comment]
Not sure why the indentation looks every flavor of fucked in the Files Changed but it definitely isn't

**Review by frawhst — APPROVED** [review]
GH defaults to 8-character tabs which makes things look fucky a lot

`/area/station/turret_protected/AIbasecore1` I hate this path what does that MEAN

also doesn't need a changelog

**Comment by goonstation-enjoyer** [comment]
It's the Donut 2 upload (also used in construction maybe?)
Removed the changelog.

**Pull request merged**
