### PR TITLE
Add Turret and remove Mail from Clarion Core

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Adds a turret and removes the mail chute from clarion computer core

## Why's this needed? 
Computer cores should have turrets to protect them, and not mail chute for any old monkey to just waltz in and steal stuff without fear of turret.

## Changelog 

```changelog
(u)JORJ949
(+)Clarion computer core is now protected by a turret.
```

### CODE REVIEW

**Comment by amylizzle** [comment]
Not sure if it'll be merged, but this directly conflicts with #18516

**Comment by JORJ949** [comment]
> Not sure if it'll be merged, but this directly conflicts with #18516 which incidentally also fixes this issue

That PR pointed out to me the lack of turret, it does remove the chute but does not add a turret.

**Comment by amylizzle** [comment]
oooh computer core, not AI core. My bad.

**Comment by Chatauscours** [comment]
Itegrated this into #18516 with @JORJ949 approval over Discord.

**Comment by Tarmunora** [comment]
DMN until #18516 is decided on either way

**Comment by JORJ949** [comment]
Included with #18516

**Pull request closed without merging**
