### PR TITLE
Increases the random antag even frequency

### PR DESCRIPTION
**Pull request by TTerc**
[balance]

## About the PR 

This PR (hopefully) increases the random antag event frequency by changing the alive antag threshold value from 6% to 10% (meaning, if less than 10% of the alive crew are antags, the event has a chance to trigger, if other requirements are met)

The change is exclusive to non RP servers.

## Why's this needed? 

It was actually suggested by mbc, and also, in my opinion, random antag events are currently too rare and I often find myself triggering them manually, if the round feels too slow. With the variety of antag critters we have, I think the change will benefit the game, influencing the round dynamics more often and giving dead players a chance to participate in the round again.

## Changelog

```changelog
(u)TTerc
(+)Increased the random antag event frequency on non-RP servers.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
Can we look at weights too? Some like wrestler and hunter are very rare.

**Comment by TTerc** [comment]
Hmm I can't really find the values for it. And I'd rather wait and see if this PR gets approved, then see how it affects the rounds, then decide if something else should be done

**Comment by BatElite** [comment]
I don't see any weighting in the event anyway, it might just be that the event happens so rarely it feels that way. 6% is so little that most rounds it'd take every antag being dead for this to trigger.

**Review by flrsh — CHANGES_REQUESTED** [review]
There's almost never 20% antags at roundstart, so this means the event would trigger as soon as it was available and continue doing so until it reaches >20%. This means out of a crew of 50 people, at least 10 of them would be some flavor of antag. That's a lot. Especially for RP. 

I'd consider 10%, but not 20%.

**Comment by TTerc** [comment]
Yeah, me and mbc misinterpreted what the value is supposed to be. 10% looks fine to me

**Comment by TTerc** [comment]
after further discussion and considering my experience is solely based on goon classic server, I'm making this change not affect the RP server at all

**Review by flrsh — APPROVED** [review]

**Pull request merged**
