### PR TITLE
New cloning sprites by Flaborized

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
https://forum.ss13.co/showthread.php?tid=13534&pid=153117#pid153117
image

## Changelog

```
(u)Flaborized
(+)Cloning equipment has new sprites. Port-a-Brig and Port-a-Puke now have distinct sprites.
```

### CODE REVIEW

**Comment by pali6** [comment]
I know @flrsh dislikes some stuff about these but I thought I'd make a PR so at least there's some discussion about them.

**Review by ZeWaka — APPROVED** [review]

**Comment by flrsh** [comment]
My thoughts were that the shading on the enzymatic reclaimer was too harsh and dark, same for the bottom of the cloning pod. The cloning pod's empty state could also have a bit more depth.

**Comment by ZeWaka** [comment]
@Flaborized ^

**Comment by Flaborized** [comment]
Updated and got Flourish's Seal Of Approval, I didn't make this PR and I'm not a dev so I can't modify it, but I put the dmi with New Sprites that have Addressed The Feedback in this thread: https://forum.ss13.co/showthread.php?tid=13534&pid=154991#pid154991

@ZeWaka

**Pull request merged**
