### PR TITLE
Resprites autoinjectors

### PR DESCRIPTION
**Pull request by DisturbHerb**
## About the PR 
Resprites the autoinjector sprites in `chemical.dm`. That's it, nothing else has been changed. I have no idea how broken this will be. Credit to @DimWhat for the original version of the VR autoinjectors in this PR.

image
autoinjectors

## Why's this needed? 
People seem to like these. Might as well.

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Probably won't set this as ready for review for now. @BatElite also made some cool autoinjectors.

**Comment by NightmareChamillian** [comment]
I like them, but I do think there needs to be a better way to tell at an instantaneous glance whether or not an autoinjector is empty or not.

**Comment by DisturbHerb** [comment]
> I like them, but I do think there needs to be a better way to tell at an instantaneous glance whether or not an autoinjector is empty or not.

I tried doing that with the cap and a little knobby-bit on the posterior end of the injector, and I'm still unsure how I would edit the sprite to indicate such.

**Comment by frawhst** [comment]
per virva:
>autoinjectors do *not* have a protruding needle in their used state, as that's contrary to their whole design philosophy

**Comment by DisturbHerb** [comment]
#7100 does this better. Closing.

**Pull request closed without merging**
