### PR TITLE
Shotgun requisition balancing + minor requision balancing

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr doubles the price of most requisitions. Due to bandages being highly map dependent on availability + unable to make more of, that specific item has been replaced with defibs that have a higher feemod. The amount of snacks required for the chef requisition order has been reduced in half, so the feemod has quadrupled. The amount of blood needed for the blood requisition has been reduced by 1/3 so the feemod of blood has been increased by 5/2

## Why's this needed? 
Lots of complaints about requisitions being too low, this should make requisitions much more viable as cargo. Some of the requisitions contained too much of an item to be able to be gotten in a cooperative setting, so theyve been reduced, and some items (basically just bandages) were occassionaly practically unable to be gotten so that was fixed.

## Changelog

```changelog
(u)Ikea
(*)The payout of requisitions has roughly doubled
```

### CODE REVIEW

**Comment by pgmzeta** [comment]
You can still make bandages from bedsheets and snipping tools - are there maps where that's not viable?

**Comment by ThatFiveGuys** [comment]
Why are you runtiming you worked a second ago aa, re: making bandages, did not know that however i dont think its fair to expect people to know that considering its very obscure and if you dont know how to do that youre shit out of luck

**Comment by Kubius** [comment]
Some thoughts:

I'd prefer that the bandage issue be tackled by making bandages renewable (either direct manufacture, or manufacture of the towels and bedsheets you can cut up to create them).

$2,640 for a single burger is absolutely comical, and I think this is a smidge overscaled in general. For a comparison, Buford's highest payout per pizza slice is $42; the old value was $100 (over double that maximum) and the new value would be nearly a five times multiplier.

I think expectations from cash-spam techniques like fresh produce sales have somewhat warped the perception of other income sources; broadly speaking, I support the idea of an increase pass to the rewards from requisitions, but I think this has ended up a bit overkill in a few cases.

My inclination would be a significant increase to *most* item-independent payout values (~160-220% between base amount and payout mod), and a lesser increase to item feemods, being more heavy-handed with Aid contracts due to their time-sensitive nature. If you'd like, I would be willing to do such a modification myself to save you the trouble.

**Comment by ThatFiveGuys** [comment]
The main reason why the burger payout and the like is so high is to keep the total payout roughly the same. Currently you get like 20k for stuff that takes the chef like 15 minutes of work, not only that but the very high amount makes actually involving the chef impractical because now the chef has work thats way too much for them. While yes on an individual level its high, the thing thats important about requisitions is the total amount of a specific item you sell is limited.

**Comment by Kubius** [comment]
Truthfully, as comical as the payout is, you're probably right, and it's likely a better idea to overshoot and tune down than to bump it up step-by-step so it acts as a more immediately appealing alternative (since requisitions can get away with this due to finite uses, as you mentioned). If you'd rather not hand the task over to me, these values seem alright to try out.

**Comment by ThatFiveGuys** [comment]
If you want to do fine tuning, then be my guest, this is your thing and these values arent really finely tuned and less shotgun of a balance approach would be better.

**Comment by ThatFiveGuys** [comment]
Closing so krump can do the work for me

**Comment by frawhst** [comment]
I'd probably like to smooth out the big lame money earners (produce, produce, produce, uhhhh) and buff reqs at the same time
~~or just replace all QM sales with requisitions idk~~

**Comment by ThatFiveGuys** [comment]
I think normal cargo and requisitions fill very different niches, for normal selling your being paid for the product while for requisitions its for the labor. But yeah smoothing out the big money earners would be good, adding a buy limit to the infinite mats (graggs char and random traders cloths) would probably help a lot too.

**Pull request closed without merging**
