### PR TITLE
Jailbirds now start in brig

### PR DESCRIPTION
**Pull request by flappybatpal**
[BALANCE][INPUT][WIP]

## About the PR 
Starts Jailbird's in the brig with a orange jumpsuit and Incarcerated status.
Changed to background trait to not conflict with Stowaway, Pilot.
Tested and does not conflict with Wizard and Nuclear Operative start.

- [ ] Decide what to do about mechanic tools.
- [ ] Decide what to do about captain.
- [ ] Decide how to handle late joins.
- [ ] Decide if any antag spawns would be an issue.
- [ ] Update trait icon to match Background.

## Why's this needed? 
Jailbird was often used for trolling sec with Arrest status.

## Changelog

```changelog
(u)Flappybat
(*)Jailbird trait now starts you in the brig with an orange jumpsuit.
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
Could we get the prisoners jumpsuit instead of the orange one? 

Also, I believe starting in Gen pop would be better as the brigs are usually tucked away and this would inhibit RP, while Gen Pop would toss all the jailbirds in a larger, more hallway viewable room together

Big +1 to this for me

**Comment by Zonespace27** [comment]
I always said "goon prisoner role when" but I didn't think it'd actually be a thing!

**Comment by penny64** [comment]
This has been discussed before and was already rejected by devs

**Comment by pitaden** [comment]
What happens if there's no security or if security never lets you out? As far as I can recall, you can't break out with only what's in the brig, so you would just be stuck there until either the round ends or someone decides to break in to let you out.

**Comment by penny64** [comment]
You forgot one on your list, Security Jailbird. Starts with the access to leave.

This applies to all the heads as well, anyone can be a jailbird.

In general jailbird is a nerd trap for sec, if you don't communicate with your team and harass people who happen to be set to arrest, you are making a problem for yourself.

**Comment by flappybatpal** [comment]
While the idea is fun after feedback and more scenarios I feel there are way too many possible issues with this. Even if we spawned them with no gear and shackled with an automatic chute timer (1 min~) there would still be problems.

**Pull request closed without merging**
