### PR TITLE
Roundstart mime... again.

### PR DESCRIPTION
**Pull request by Momoberry**
To note, the mime job colour is default blue for simplicity of PR. The colour I thought looked the best with the current HTML preferences being a white background, which locks out using white, was this. https://i.gyazo.com/70b80ea2d452633b05801786fa5da202.png

## About the PR 
Enables the Mime role as a roundstart/preference job. With that change, antagonist mimes will become more common and we'll see some new interesting gimmicks from that. ❤️

## Why's this needed? 
Community overwhelmingly wanted mime to be a roundstart job last year, but it was originally declined for not having appropriate content to be roundstart, seen with #3884. It now has its own traitor item from #9724, and more content designed for it for clothing, cargo crates, etc. Mime has become an even more frequent pick and is regularly sniped as soon as a round starts because many players adore the job quite a lot.

## Changelog

```changelog
(u)Momoberry, LeahTheTech 🆕⚖📦
(*)Mimes have been enabled as a round start job and job preference. Hooray!

```

### CODE REVIEW

**Comment by t-toasted** [comment]
Finally. I’ve been waiting for this for ages

**Comment by Roninnozlo** [comment]
WOO

**Comment by flappybatpal** [comment]
I'm neutral on this but starting players mute is a bit extreme.
You could say "well put it in the default unwanted jobs" but we have people take Mildly Mutated and then ahelp about getting mute and other bioeffects.

**Comment by TobleroneSwordfish** [comment]
I mean, new players could already randomly pick mime from the latejoin list and have to play most of a round mute. If anything this will probably reduce the number of times this happens due to the mime slot already being filled more often.

**Comment by flrsh** [comment]
The large majority of admins and devs I've talked to do not want to make mime a roundstart role. #3884 was not closed simply because mimes didn't have enough content. The idea that "if mime gets traitor items then it can be made a roundstart role" is not true.  

Roles can be well liked and have role-specific content without being standard, roundstart roles. I'd rather we flesh out some of our gimmick jobs more (coach, actor, lawyer, musician, etc.) and make them more interesting and enjoyable to play.

**Comment by UrsulaMejor** [comment]
Per [#2387:](https://github.com/goonstation/goonstation/pull/2387)

> Less ability to interact with the crew tends to push people into more borderline griefy behaviors.

> Currently, mimes have no unique mechanics and thus don't really have a spot as a full job.

> mimes aren't generally 'good' for the current gameplay, since they don't have good mechanics to interact with other players, which often leads to grief-ish behavior.

Please revisit older PRs closed PRs and make sure you've addressed the issues in those PRs before opening new ones for the same thing.

For my personal opinion, see also [this thread response.](https://forum.ss13.co/showthread.php?tid=19967&pid=187546#pid187546)

**Pull request closed without merging**
