### PR TITLE
human move speed rebalance

### PR DESCRIPTION
**Pull request by mybluecorners**
things this PR does :
- adds a new sprint particle + sound effect when sprint begins
- sprints are now 'instant' - no more waiting until your mob steps to the next tile! (yes, it has compensation code to make sure you dont go faster by mashing sprint)
- lowered base movespeed
- increased the power of sprint when it's counteracting slow effects. It doesn't go faster in general, but the relative difference of sprinting when youre badly hurt for example will be much greater.
- reduced the weight of many 'slow' effects (damage, cold movement, mutant races and chems)
- sprint only consumes stamina when you take a step - will no longer drain stamina by pressing into dense objects
- sprint consumes slightly less stamina and ends slightly earlier on the stam meter

## Changelog

```
(u)mbc:
(*)Movement rebalance : Sprints are more effective at countering slows. Slows reduced across the board. Sprints activate instantaneously on button press instead of waiting for next step. Lower base movespeed. Sprint consumes a bit less stamina. And other small adjustments/fixes.
(*)Note that the rebalance is subject to change after testing!!
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
I think this is generally good, but there are couple things I'm not getting good vibes from

First: instant sprint boost and increased runscaling mean that sprinting (and therefore stamina boosts) are disproportionately effective vs. energy weapons (melee and kinetics stagger, blocking sprinting), and having high stamina already acts to counter energy weapons
Other point of concern is that this makes walk intent slower outright, which I'm not sure it needed.

**Comment by mybluecorners** [comment]
> I think this is generally good, but there are couple things I'm not getting good vibes from
> 
> First: instant sprint boost and increased runscaling mean that sprinting (and therefore stamina boosts) are disproportionately effective vs. energy weapons (melee and kinetics stagger, blocking sprinting), and having high stamina already acts to counter energy weapons
> Other point of concern is that this makes walk intent slower outright, which I'm not sure it needed.

mentioned this in discord already, but you still get the instant boost even when staggered right now.
Possible change : disable the 'instant' boost while you are staggered or disoriented

**Comment by trerri** [comment]
As QoL, this is stellar.
It would actually be really nice if ranged sec didn't stun but instead disorient and block sprinting, so that taser and baton don't "compete" in the same field of stunning. But what do I know about sec

**Comment by Gerhazo** [comment]
Not sure how soon we want movement changes to be live but if this isn't merged until then, I think it'd be a really neat idea to test run this during the jam on the 13th. Although that date is currently quite some time off, so I'm not sure how feasible the idea is.

**Comment by PrimeNumb** [comment]
Tested it briefly on local, with various movement modifying items (space suits, riot gear, etc). Lower base speed felt okay I guess, but it's probably a good idea to do testing on a wider scale (like, via ass jam or something). It's also just a numbers thing so it'd be very easy to adjust after the fact if people ended up disliking it.

It might be the case that the slow reduction when sprinting is a little strong, but again, difficult to say when testing in an isolated environment. Should also just be a numbers thing if it ends up being the case.

In any case, I think the feature in general could be an interesting change.

**Comment by Tarmunora** [comment]
The sound/visual effects could be subtler in my opinion

**Pull request merged**
