### PR TITLE
Edits/resprites some sprites in writing.dmi

### PR DESCRIPTION
**Pull request by TemThrush**
[Game Objects]

## About the PR 
This PR slightly edits or resprites a portion of the sprites in Writing.dmi
Edits are mostly just very slight color changes to (mostly) match pre-existing goon palettes, with outlines added to any sprites that didn't have any! The only sprite that had a real significant change was the clipboard... (and maybe the paperbin)

image
(og on the left, resprite/edit on the right!)

image

## Why's this needed? 
The sprites themselves are perfectly good, but some didn't quite match the current style guide, or I just felt they could benefit from a new palette and stronger contrast!

### CODE REVIEW

**Comment by DisturbHerb** [comment]
maybe check if it's worth altering the pda pen icons as well to reflect the palette changes

**Comment by ZeWaka** [comment]
I don't know why paper is so cold now, paper doesn't look cold IRL, it looks warm

**Comment by TemThrush** [comment]
> maybe check if it's worth altering the pda pen icons as well to reflect the palette changes

I honestly forgot about that oop.. Maybe some other day

**Comment by TemThrush** [comment]
> I don't know why paper is so cold now, paper doesn't look cold IRL, it looks warm

Dang grey-blues and grey-purples chilling up the place... I could definitely change it up to be more neutral or warm tho!

**Comment by DisturbHerb** [comment]
> I don't know why paper is so cold now, paper doesn't look cold IRL, it looks warm

maybe your paper does 😈

**Comment by AXLFAN2000** [comment]
Huge fan of these, especially the sticky notes!  It all looks great, though I feel like the clipboard looks very flat now without the textured shading on it.  It blends in with the tables a lot, and I don't feel like I get the clipboard texture looking at it.

**Review by WALPVRGIS — APPROVED** [review]
Looks great to me! Much better than the older sprites which were looking quite muddy due to the lack of contrast. :)

**Review by Gannets — APPROVED** [review]

**Pull request merged**
