### PR TITLE
Severely reduces brute/burn healing from cryox, increases healing from effects of crit from cryox

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr reduces the brute and burn healing from cryox from 12 to 2. Cryoxadone now has a 50% chance of reducing lose breath however and now reduces the chance of death the same amount as synaptropine (does not stack). This also removes the heating up from cryoxadone as it shouldnt be needed anymore.

## Why's this needed? 
I am personally of the take that generally, ignoring doctors should not be faster and/or easier then going back into medbay and doing it yourself. Not only is cryo insanely easy to access, its also far faster, with some of the highest healing rates in game. This shifts the niche of cryo from a all around amazing healer to something that youll want to use as a stopgap for patients to buy time to heal them. Oh also semi nerfs cryopills but those arent used that much anymore so. This mostly just makes cryo pills less of a mid combat rapid healer and more of a simple and reliable slow healer at the cost of less mobility for things like azones.

## Changelog

```changelog
(u)Ikea, tarmunora
(*)Cryoxadone brute/burn healing has been reduced from 12 to 2, oxy healing also reduced to 2, however it now can combat losebreath, counters radiation, and provides some protection from random death rolls in crit while in effect. Cryoxadone will no longer work when body temp is below -240C or so
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
🤷 might as well go all the way and make it match omnizine in other damage types as well

**Comment by ThatFiveGuys** [comment]
> 🤷 might as well go all the way and make it match omnizine in other damage types as well

I want cryo to have a niche that isnt just lazy mans omnizine, making a change that should make it much more interesting

**Comment by ThatFiveGuys** [comment]
Copy pasting from forums:

Upon further consideration, changed how cryopills work. Cryoxadone will now always heat up, however ice cubes (and cryostalone to a far lesser extent) will now always cool you down. What this means is if youre outside of an ice cube or cold cryo tube without external cooling you get roughly 25-33% as much healing as youd get if you were in one. This means that not only are cryopills basically useless mid combat because the aggressor can just break the ice cube and nullify your healing, this also means that using cryopills on other people means that you cant add additonal meds on them due to them being in an ice cube. This gives using cryopills a strong opportunity cost compared to other medchems due to needing to be immobile to heal a non negligible amount and not being able to get external healing.

**Comment by Tarmunora** [comment]
I am taking this over 🐈

**Comment by ThatFiveGuys** [comment]
Help my pr stolen

Also think tox and oxy should be buffed a bit from 2 to like 3 and 4 respectively, just to make it better at dealing with stabalizing poison flooding. Also assuming you dont like the ice cubes are source of cooling solution, there definitely should be some “antag” counters to the reduced death chance considering how annoying i can see it being with antags assuming the person passed out on floor is dead but they popped a cryo pill and are slowly healing so nope, maybe something like taking brute damage will cause the cryox to cancel out its effects? Dunno.

(only practical way a lot of the time) and deep crit respectively. 
(Also dunno if youre done with changes but remember to alter changelog)

**Comment by ThatFiveGuys** [comment]
Is it intentional that this means that cryostylane will no longer provide enough cooling to where cryoxadone could ever take effect? I assume the intent is to make it to where you can only use cryox inside of a cryotube and practically use it nowhere else.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
