### PR TITLE
npc monkeys now don't attack you if you are wearing the monkey suit. 

### PR DESCRIPTION
**Pull request by Kyle2143**
## About the PR 
Title basically. If you're wearing the monkey suit and try to punch or grab a monkey, they won't attack you. But they will still chase you for a little while. 
Also, it adds a monkey suit to the Monkey Barrel traitor item for you to wear.

Also, while it "tricks" monkeys into thinking you are one of them for this purpose, it doesn't make nearby monkeys aggro you if they see you get attacked. That would like have to be a traitor item or something. 

## Why's this needed? 
When I first saw the Monkey Suit in the genetics dome years ago, I thought it was geneticist gear to a geneticist masquarade as a monkey so that they can grab em and experiment on em without all the other monkeys killing em. 

## Changelog

```changelog
(u)Kyle
(+)Wearing the monkey suit will prevent most monkeys from trying to attack you.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
How's this interact with angry monkeys (traitor barrel)?

**Comment by Kyle2143** [comment]
> How's this interact with angry monkeys (traitor barrel)?

it adds a monkey suit to the Monkey Barrel traitor item for you to wear.

**Comment by BatElite** [comment]
Scope creep but the barrel suit should ideally have a random colour bandana on/with it to fit with the monkeys.

**Comment by Camryn-Buttes** [comment]
Brilliant

**Comment by Azrun** [comment]
> When I first saw the Monkey Suit in the genetics dome years ago, I thought it was geneticist gear to a geneticist masquarade as a monkey so that they can grab em and experiment on em without all the other monkeys killing em.

Thought the same thing. Except more recently of course.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
