### PR TITLE
Make more items scannable and deconstructable

### PR DESCRIPTION
**Pull request by penny64**
[INPUT WANTED]
## About the PR 

We add scanning/deconstruction to the following items
- Cargo Pads
  - Now always scan as a generic automatic cargo pad
  - Set their name based on their location
- SMES Units
  - "CON-2"=30,"INS-2"=50,"MET-3"=30,"CRY-1"=10
  - Only available from cargo atm
  - Built SMES units deploy their own terminal and delete it when they're removed
  - fixes the SMES frame sent by cargo too
  - Pairs with furnaces which already scan
- Port-A-Sci
  - telecrystal"=30, "MET-2"=15, "INS-1"=20, "CON-2"=15
  - no more PDA app so let's do it
  - you also can't set restricted z-levels as home turfs anymore
- ice dispenser
  - "MET-1"=10, "CRY-1"=15, "ice"=5
  - you can't build an entire bar bit right now!
- soldering iron
   - "MET-2"=1, "CON-1"=2
   - same price as the manufacturer
   - Because mechanics are lazy
   - Actually so that we can hand out kits of frames to crew members more easily
- packet sniffer
  - "INS-1"=10, "CON-1"=15, "CRY-1"=3, "MET-2"=2
  - More than one nerd may reside on the station
- health scanners and displays
  - "INS-1"=3,"CON-1"=4,"MET-2"=2,"CRY-1"=5
  - Requested on discord, and I've tried to scan these tons of times
  - We use DECON_DESTRUCT on these so the screens can connect to scanners
- Robustris Pro Cabinet
  - "MET-1"=3,"CON-1"=4, "CRY-1"=3
  - Same price as the other arcade machine
- Security Weapons Vendor
  - "MET-3"=20, "CON-1"=10, "POW-1"=5, "CRY-1"=5
  - requested on discord because these get bombed
  - they don't do much without a token anyway
  - and I made them expensive
  - I didn't make these deconstructable (except when built)

## Why's this needed? 

Making construction more robust by adding more items!

## Changelog

```changelog
(u)Penny
(+)Ice dispensers, the Port-A-Sci, SMES units, soldering irons, packet sniffers, floor health scanners and their screens, Robustris Pro Cabinets, and Security Weapon Vendors can now be scanned with device analyzers. Cargo pads can now be properly scanned and set their name based on their location.
```

### CODE REVIEW

**Comment by penny64** [comment]
This won't build until #5218 is merged, we use DECON_DESTRUCT on the health scanners

**Comment by penny64** [comment]
Alright I just need to merge master into this!

**Comment by ZeWaka** [comment]
rekt

**Review by Tarmunora — CHANGES_REQUESTED** [review]
No to scanned SMES units, the cargo crate exists for a reason.

Hard pass on scanned port-a-sci

Not a huge fan of the packet sniffer being scannable but it's not a dealbreaker

**Comment by penny64** [comment]
The cargo crate has existed forever, we have matsci recipes now that make crafting them an option we can balance.

The Port-A-Sci can't set a home turf as restricted levels anymore so it doesn't let you cheat at puzzles, you need a remote

The more important thing here is that using rare mats to make more extravagant equipment expands mat science, there's not that much use or player experience of it. It even helps build lore, with stuff like needing telecrystals for the Port-A-Sci

**Comment by mordent-goonstation** [comment]
Not a comment/review of this PR, but the comments in here have made me think that it might be neat if we had some material requirements for some recipes require materials that are not covered by common materials but could be covered by common materials if alloyed together. I don't know how feasible that is with the current materials available, just an idle thought.

**Comment by penny64** [comment]
Gonna separate this and add some more stuff

**Review by ZeWaka — CHANGES_REQUESTED** [review]
pending above x

**Comment by penny64** [comment]
aaagh

**Comment by ZeWaka** [comment]
eeeeeeee

**Comment by penny64** [comment]
I'm having brain problems

**Comment by UrsulaMejor** [comment]
no to smes and portasci

**Pull request closed without merging**
