### PR TITLE
adds 7 funktastic songs, and a new record sleeve sprite

### PR DESCRIPTION
**Pull request by aquariofury**
There is a whole lot of music already available for the radio host to choose from, but not an overabundance of fusion funk. I have created 7 funky songs to correct that. These songs span the range of various spaceman activities, such as: Cryosleeping, cuddling with a bee, and of course murdering one another. 
Also a custom sleeve for it, based on the best fusion album out there.

## Why?
Because we all need more saxophone in our life. 

## Changelog
```changelog
(u)Aquario
(+)adds 7 songs, and a new record sleeve
```

### CODE REVIEW

**Comment by Kubius** [comment]
Instrumentation is a bit harsh. If these are MIDI arrangements, BYOND *may* be able to play those directly (though I'm not sure offhand how that interacts with record disks), or you could use an alternative MIDI soundfont on your end; elsewise, not sure what to offer.

**Comment by frawhst** [comment]
!merge_upstream

**Comment by pali6** [comment]
> Instrumentation is a bit harsh. If these are MIDI arrangements, BYOND _may_ be able to play those directly (though I'm not sure offhand how that interacts with record disks), or you could use an alternative MIDI soundfont on your end; elsewise, not sure what to offer.

BYOND can play MIDI files.

**Comment by Kubius** [comment]
Didn't know if particularly radio records could, in their current state.

**Pull request closed without merging**
