### PR TITLE
Fixes the science scanner being called security

### PR DESCRIPTION
**Pull request by Conchuckter**
[bug - trivial]
## About the PR 
Fixes the science scanner being called security

## Why's this needed? 
#7783

## Changelog

```changelog
(u)Conchuckter
(+)Fixes the science scanner being called security
```

### CODE REVIEW

**Comment by Conchuckter** [comment]
I've never changed anything to do with maps before, so I'm not sure if that big of a change is normal.

**Review by pali6 — CHANGES_REQUESTED** [review]
You converted the file from the TGM formatting of dmm files to the default BYOND formatting. Please fix this. If you are using StrongDMM the setting is here in preferences 
image

**Comment by Conchuckter** [comment]
> You converted the file from the TGM formatting of dmm files to the default BYOND formatting. Please fix this. If you are using StrongDMM the setting is here in preferences image

Ah, whoops. Honestly I was just using byonds inbuilt editor. I'll have a look at getting StrongDMM.

**Comment by Conchuckter** [comment]
I did a stinky mistake

**Pull request closed without merging**
