### PR TITLE
[MDB IGNORE] Entirely reworks the Debris Field

### PR DESCRIPTION
**Pull request by Zonespace27**
[Balance] [Feature]
## About the PR 
This PR entirely reworks how the debris field functions from the ground up, which I will cover below.

So, the debris field is no longer static, and is instead a set of prefabs that are randomly placed. However, there is more than just prefabs. The debris field now has completely randomly generated small asteroids and small derelicts, which is a segue into one of the leading factors of the new Debris Field.

## Difficulty Scaling

The debris field is now even more dangerous, but uses a form of scaling difficulty. The closer you get to the center, the more dangerous things get. What I mean is that the drones that spawn will be harder and harder the closer to the center you get, but so does the loot!

## Dangers

The new debris field's dangers are randomly generated, and overall the Z level is much more dangerous than previous. The danger is mostly drones, but there are also drone beacons (#6645) which will attract any drones in the area to any pods or people within range. Taking these down will summon more drones, but are able to give valuable rewards in the form of special loot crates that are unlocked on the destruction of the beacon.

Once all five drone beacons are destroyed, head to the center of the debris field to interact with a mysterious terminal, which lets you fight the final boss of the debris field, which is SWORD! SWORD's been modified slightly to prevent them from leaving z3, in addition to giving more feedback on how damaged they are.

## Random Generation

The new Debris Field generates a variety of things, but first it produces prefabs, which are the currently-existing debris field areas. Some of which will always spawn (radio station, mining outpost, YDrone Area are a few). After that, it creates asteroids randomly, which these asteroids are much smaller and odder shaped than the ones found in z5. After that, it generates random derelicts, which are small ruins with an artifact, loot crate, or general loot in the center. After this, drones are placed, with their overall difficulty scaling the further to the top right you go.

## Load Times

On my local, as of writing this (11/12), the average time between 10 different debris field loads was 4.3 seconds added to the load time of a round. The average asteroid field loading time was 8.3 seconds.

## Why's this needed? 

I originally came at this with the sole goal of randomizing the debris field, but I came up with the idea of making it a bit closer to a roguelike in how it operates, giving valuable loot, ore, and artifacts in exchange for fighting through a large amount of dangers on the way.

Also requested by @Tarmunora 

## TODO:

- [x] Give asteroids scaling ore values
- [x] Give loot crates in small derelicts scaling loot values
- [x] Await #6645 getting merged, add drone beacons and loot
- [ ] Make asteroid & derelict generation prettier
- [ ] Overall generation improvements
- [x] Take a pass of the numbers
- [x] Add asteroid field-like map maybe?
- [x] Investigate SWORD terminal sometimes spawning in walls
- [x] Move Radio Host's job spawn

## Changelog

```changelog
(u)Zonespace
(*)The debris field has been entirely reworked and randomized, teleport in via the radio station's beacon!
```

### CODE REVIEW

**Comment by Eagletanker** [comment]
Highly against. The debris field being a constant and known thing is good. It’s designed in such a way to tell a story too, with a inner and outer belt of debris being marked and separated by the warning beacons. Areas are also grouped roughly together, with areas such as the mining, bee, and radio station being in pretty peaceful spots, allowing for being able to freely Mine off station (and serving as a backup) and allowing the radio host not to be turned into paste if someone spawns in the Y or X drones. This would benefit from being a entirely separate z level, allowing for a good scale of difficulty from 5-3-7 rather than immediately throwing new players into fighting and navigating a unmapped non constant zone. This PR would hinder the environmental story telling and overall area outside of the space station, and as such it should be it’s own separate Z with its own story to tell. (Maybe a syndicate stronghold, or a more dangerous area around X0)

**Comment by ThatFiveGuys** [comment]
Randomizing debris would be great, would curb on a lot of powergaming and fix a lot of the issues with telesci (ie debris scripts). However, while I do like the idea of a geographic progression in difficulty I feel as if its execution leads things to be desired. Removal of access by going off of Z5/Z1. This is mostly for spacing purposes, being spaced into debris was always fun because unlike prefabs, debris tends to have far more spots where you can safely hang out. Pair that with debris loot, and you had a fun challenge of getting out. Getting spaced into Z5 on the other hand is mostly just hope you can make it into space diner in time, because good luck getting to a prefab. 

While I do understand that this is needed to prevent people from just going to the bottom right of a z level for easy access to debris loot, I feel as if there is an alternative to the top right being the most difficult, the center. The center being the most dangerous part seems the most fitting, and it would still allow a geographic progression. Not only that, but it would fix another issue with this execution, the radio station being the only access point to debris. By blowing up one warp beacon, you can prevent every pod from warping to debris, not only that but while unlikely drones can destroy the warp beacon too. This creates a severe reliance on one object, and destruction of said object cuts out people of a major game content for the whole round. 

Really not a fan of mining outpost being unaccessible either without finding it, especially considering we have 6 miner slots now. On highpop miners are expected to use mining outpost nowadays, this prevents them from doing that. Honestly just swap mining outpost and space diner, you still get miners having enough space to do there job, and it fits better there anyways. While I do understand there was lore moving the space diner to Z5, that isnt enough justification for a severe reduction of quality of life for miners and ability for miners to do there job.

**Comment by Zonespace27** [comment]
Having the scaling go towards the center is a good idea, I'll think about & look into potential implementation

**Comment by DimWhat** [comment]
I'm neutral on randomization change but I'm not very keen on bradbury related zones and places with keys being RNG based. Only having a chance to complete puzzles is really annoying.

**Comment by Zonespace27** [comment]
> I'm neutral on randomization change but I'm not very keen on bradbury related zones and places with keys being RNG based. Only having a chance to complete puzzles is really annoying.

Forcing certain ones to spawn is basically a non-issue, I only set the ones I thought of at the immediate moment, will get updated sometime eventually

**Comment by Gannets** [comment]
I've been wanting something like this.

**Comment by Momoberry** [comment]
Exciting 👍

**Comment by Eagletanker** [comment]
Also,

Ikea brings up a good point, it's much more fun to be spaced into the debris rather than the belt. It's a way to get back into the round, and is a way to come back from a fuck up. If your spaced, depending on what side you land on, you have a few options and challenges immediately ahead of you. Do you head to the time ship, securing a weapon, space suit, and air for the exchange of having to take a longer time to find a way to get out? Do you head to the mining outpost, getting a pod and tools along with a area to breathe in to plan your next move, while having to deal with the possibility of someone finding you or running into a mining team at the outpost. Do you risk grabbing the gear in the fermid hive while dealing with a very likely chance of death. There's also a lot of gimmick items in the debris that currently you can get within a reasonable amount of time that saves you TC for more fun things in your uplink, or to spice up the usual tediousness of spies. 

The other thing is that this seems to be because of a small but persistent group of people power gaming the debris with telesci scripts for the loot crates inside of it. Which in that case, the solution is to teleblock those areas ala the medical ship, or deal with those players via administration, as they are actively ruining the game for the majority of people who dont do that. I'd like to point out that most people will learn the debris by spending time in there, and gradually forming a mental map rather than looking at a telesci map and seeing were all the op gear is or were all the crates are, rather than using rather out of the way telesci calculators. You can also use the drone beacons to make the debris overall a harder experience, and have them do a teleblock effect as they cover syndicate deemed important areas, such as those crate caches and stuff.

I'm going to stress again, I think this would be much better as **a entirely new area you can explore, rather than a recycle of a area and assets that is fine on its own**. A Z7 built around the infrastructure of this PR would allow for,

A separate, and mechanically different area than what would be expected from the debris or mining belt, with a NT ship (or possibly the cruisers) being the main drop point that allows for people to actively choose to go there. 

It's own separate design for prefabs which wouldn't clash with the older mapping style of the debris (which I'll note, while not intentional, gets across pretty well that most of these areas are older than the station)

A difficultly level for non telesci, non azone content. Belt - Debris - Z7 would be the scale, increasing in difficulty and resourcefulness needed to succeeded.

No locking of content behind it not being the thing selected in the generator, enhancing the goonstation sandbox and allowing for more enjoyable over all game. 

A whole new area of lore that players can explore and make content for, and which would allow for some current belt prefabs to be moved to, increasing the spawn chance of those.

A expanded play area that does not rely on telesci access or being a scientist/metagaming on RP. 

All of that would not be the case with a randomized debris field as this PR implants it. If you would like to see a alternative proposal to in game stop people from abusing the debris, then after #6645 gets merged, please give me 1-2 days to make one, as I strongly feel that there is a easier and more fun option available that will actively add too instead of merely removing from goonstation.

**Comment by Crystalwarrior** [comment]
This is a good change. While I feel telesci has few ways to give instant benefit to the station outside of loot crates, telesci removing all the loot from the debris field every round is a problem and randomizing the field or at least crate spawn locations is an effective solution to the problem.

I strongly advise against ever involving administration in cases of power gaming unless other rules were broken as it sets a horrible precedent that you are not allowed to take the game mechanics to their fullest, and it pushes blame onto the players for poor game design which SHOULD be the responsibility of the developers. Meaning telesci abusing the static debris field is a logical consequence of the game mechanics.

I did several rounds of teleporting loot crates from debris field by using the telesci calculator and map, and the reason why I did it is because it brought a ton of fun loot for my department and other departments like mining. I dunno how that ruins the rounds of other people when my actions directly benefit several departments?

**Comment by flrsh** [comment]
Can't really think of anything off the top of my head, but I think this would be more compelling for me if the debris field had some cool distinguishing aspect besides "Z5 but maybe more dangerous". Especially because the debris field is actually what people visit far more often. 

>On my local, as of writing this (11/12), the average time between 10 different debris field loads was 4.3 seconds added to the load time of a round.

What was the average load time of Z5?

**Comment by Zonespace27** [comment]
> Can't really think of anything off the top of my head, but I think this would be more compelling for me if the debris field had some cool distinguishing aspect besides "Z5 but maybe more dangerous". Especially because the debris field is actually what people visit far more often.

More to come there, the debris field will be more fleshed out once it's undrafted & ready to review

> What was the average load time of Z5?

8.3 seconds, will be editing that in the main post.

**Comment by ThatFiveGuys** [comment]
Its important to note while telesci is a notable example of debris powergaming, static debris enables other powergaming too. Loot crate rushing, rushing of loot like strelka, etc is all greatly speed up by being able to know the layout of debris, randomising debris would slow this down.

**Comment by ThatFiveGuys** [comment]
If DOC is going to no longer in the same spot and not have a beacon would it be good to readd the robotics fabricator?

**Comment by ThatFiveGuys** [comment]
Suggestion: more central asteroids have harder to mine rock.

**Comment by nefarious6th** [comment]
Gonna miss being able to do neat stuff in the Faint Sig and going to the time anomaly to visit Wally. Seems like it takes away opportunities to engage with lore elements and thematic areas if it's random every round.

**Comment by Zonespace27** [comment]
> Gonna miss being able to do neat stuff/evil cloners/hostage plots in the Faint Sig and going to the time anomaly to visit Wally. Seems like it takes away opportunities to engage with lore elements and thematic areas if it's random every round.

You can still do these, the prefabs are still there. Also, as I have expressed before, I will be making many (if not most) of the large debris prefabs guaranteed to spawn

**Comment by nefarious6th** [comment]
> You can still do these, the prefabs are still there. Also, as I have expressed before, I will be making many (if not most) of the large debris prefabs guaranteed to spawn

Searching for the prefabs for 20 minutes to set up something kinda cuts into the time to actually make a round move and interesting, at least on RP.

**Comment by Zonespace27** [comment]
> Searching for the prefabs for 20 minutes to set up something kinda cuts into the time to actually make a round move and interesting, at least on RP.

There is a debris field map that works nearly the same as the asteroid field one

**Comment by nefarious6th** [comment]
Only other question is whether you've figured out how this'll work with Ainley at the point where people get flung. 
My thoughts were added late after I saw the initial PR, thanks for clarifying.

**Comment by Sovexe** [comment]
> Only other question is whether you've figured out how this'll work with Ainley at the point where people get flung. My thoughts were added late after I saw the initial PR, thanks for clarifying.

If I remember correctly it flings the player to the time ship

**Comment by TDHooligan** [comment]
my main concern is that debris contains a big variety of less powerful but fun gimmick items that will functionally stop existing once they're made awkward or unreliable to get. the powerful items that powergamers flocked were moved to the random Z level for that reason.

there's a lot of value to static spawns as they serve as an incentive for lower-skilled players to actually get involved in telesci, randomized spawns will still get rushed by the smart powergamers when they can. it could literally be a matter of teleblocking the tiles the crates spawn at and having players actually having to overcome some tiny hurdle to get the crate (a safe deposit, some weak critters)

there's good odds that using such large-scale randomization to hide away stuff like crates will just keep the lower-skilled players out of ever receiving them and not change the outlook for the skilled powergamers who are likely the ones that make crates a problem in the first place.

**Comment by Zonespace27** [comment]
> my main concern is that debris contains a big variety of less powerful but fun gimmick items that will functionally stop existing once they're made awkward or unreliable to get. the powerful items that powergamers flocked were moved to the random Z level for that reason.
> 
> there's a lot of value to static spawns as they serve as an incentive for lower-skilled players to actually get involved in telesci, randomized spawns will still get rushed by the smart powergamers when they can. it could literally be a matter of teleblocking the tiles the crates spawn at and having players actually having to overcome some tiny hurdle to get the crate (a safe deposit, some weak critters)
> 
> there's good odds that using such large-scale randomization to hide away stuff like crates will just keep the lower-skilled players out of ever receiving them and not change the outlook for the skilled powergamers who are likely the ones that make crates a problem in the first place.

At this point, the debris field rework has gone past just being a thing to stop powergamers. It's moreso evolved into its own thing, which, I should point out, will have more loot than the previous debris field, just that it's a lot harder to get to.

**Pull request closed without merging**
