### PR TITLE
process_rebuild_select_groups runtime

### PR DESCRIPTION
**Pull request by Azrun**
[bug - minor]
## About the PR 
Resolve runtime that appears to be caused by a race condition where the air_master attempts to regroup and has a listed turf get spaced out from under it.  Solution to limit computational implication is to provide stub function to allow operation to complete.  Conversion to a space turf should automatically cause it to be removed from the group proper, which is unrelated to the air_master actions at that time.

## Why's this needed? 
Runtimes bad mkay

### CODE REVIEW

**Comment by Azrun** [comment]
Removal of as() from for loops iterating over turf_list is a more wholesome solution, as that ensures that lag checks don't cause a turf to get swapped out mid process_rebuild_select_groups()

Removal from assemble_group_turf() loop seems required as parent is not a member of /turf/space and working around that feels like a hack because it wouldn't be the type expected.
Removal from update_air_properties() can be mitigated with stub function so check wouldn't be required.

**Comment by pali6** [comment]
I think I'd prefer moving the `update_air_properties` declaration to `/turf` to having it declared on two different turf subtypes.

**Comment by Azrun** [comment]
Kicked out feature creep to make a separate target PR, as these changes can have performance impacts.

**Review by ZeWaka — APPROVED** [review]
SAD!

**Comment by Azrun** [comment]
@ZeWaka Get glad! 
There any changes you want to see a work-around to maintain performance?

**Comment by ZeWaka** [comment]
> @ZeWaka Get glad!
> There any changes you want to see a work-around to maintain performance?

not that i can think of, other than being more careful with space replacement and stuff

**Comment by Azrun** [comment]
We could queue up turfs transitioning out of simulated and have them handled by ATMOS to ensure this doesn't happen in the first place.

Increase ATMOS rate to 1Hz, have it check for turf transition and then alternate the current air_master.process() behavior to maintain 0.5Hz rate.

**Comment by Azrun** [comment]
Closing in lieu of queuing the spacing of tiles to avoid the behavior I'm working around.

**Pull request closed without merging**
