### PR TITLE
removes arrowheads

### PR DESCRIPTION
**Pull request by ZWRh3**
[QOL]
## About the PR 
removes arrowheads
## Why's this needed? 

they serve no use other than being an extra step in arrow/spear creation

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
Love this so much thank you

**Comment by Tarmunora** [comment]
microcrafting is good
 - this post sponsored by gregoriusT

**Comment by ZWRh3** [comment]
> microcrafting is good - this post sponsored by gregoriusT

is that a joke about the extreme level of microcraftin in gregtech or the actual opinion on this PR?
in mc escpecially with stuff like JEI those middle steps can be fast and even then it often still sucks but in matsci its:
finding arrowheads on the nanofab itself

extremely slowly selecting the material (mostly due to the laggy and bad GUI)

putting the arrowhead on the floor back into the nanofab

putting in 3 metal (steel looted from the nearest nanofab usually or bohrum looted from mining)

finding the spear recipe

selecting the arrowhead part

selecting the handle part

clicking that you want to make 1 spear

spear is now on top of the nanofab

**Comment by ZWRh3** [comment]
+ gregtech microcrafting is often forcing using some other machine for the extra steps not more clicks in a painfully dated and laggy GUI

**Comment by Josephin23** [comment]
> microcrafting is good - this post sponsored by gregoriusT

new goon update: all constructions now require 8 layers of components each created manually with matsci

**Pull request merged**
