### PR TITLE
More inhand sprites

### PR DESCRIPTION
**Pull request by binarysudoku**
[BUG] [QOL] [CLEANLINESS]

## About the PR

Upgrades:
- Mining powertool inhands now update dynamically
- Clipboard inhand now updates dynamically
- Fire extinguisher now updates dynamically

Sprite fixes:
- Saxophone no longer clips awkwardly with your body

Resprites:
- Bible
- First-Aid Kits
- Fire Extinguisher
- Backpack & Medical Backpack + (Inhand and Worn)
- Toolboxes

New sprites:
- Power Pick & Power Hammer off-state inhands
- Slag Shovel
- Power Shovel
- Arms and Legs
- Ouija Board

Cleanliness passes on various inhand files
- Moved books and paper to hand_books.dmi
- Moved storage items to hand_storage.dmi
- Moved tools to hand_tools.dmi

## Why's this needed?

Bunch of bugfixes, visual upgrades and cleanliness, plus being able to see powered state of mining tools is useful and makes toolboxes and fire extinguishers more clearly visible

## Changelog

```
(u)Erinexx:
(+)Added a tonne of new and resprited inhands, including toolboxes, backpacks, and arms and legs!
```

### CODE REVIEW

**Comment by flrsh** [comment]
Nice work. The clipboards look good and like how I imagine people would hold them. I also very appreciate finally having arm + leg inhands (would be neat if there were a grayscale version so we could color them appropriately). 

What changes were made to the multitool inhands? To me they look virtually the same. 

I prefer the old sax inhands (besides the clipping); to me they have more personality. I'm ambivalent about the new medkit inhands; I think it's useful that they'd display the cross regardless of direction. The old backpack inhands also look better to me, and I feel like the north facing state of the new worn ones don't need the extra pixels at the side.

**Comment by binarysudoku** [comment]
> Nice work. The clipboards look good and like how I imagine people would hold them. I also very appreciate finally having arm + leg inhands (would be neat if there were a grayscale version so we could color them appropriately).

I could easily do grayscale versions; I would have to do grayscale sprites for the normal icons too so ill likely submit that as a separate PR for simplicity's sake

> What changes were made to the multitool inhands? To me they look virtually the same.

Multitool inhands have just had a couple pixels tweaked so they sit more naturally in the hands, it's just a minor fix for them sitting slightly weird in some direction states

> I prefer the old sax inhands (besides the clipping); to me they have more personality.

Valid, I can easily solve this when I'm finished with my professional work today

> I'm ambivalent about the new medkit inhands; I think it's useful that they'd display the cross regardless of direction.

Also valid, I can change that relatively quickly

> The old backpack inhands also look better to me, and I feel like the north facing state of the new worn states don't need the extra pixels at the side.

What about the new ones don't you like?

**Comment by flrsh** [comment]
The N/S and the E/W of the inhands and worn states respectively look weird to me. They look saggy and overdetailed. I think that adding pockets makes it difficult to interpret what the sprite actually is, because of the extra lines on such a small space. The item sprite itself doesn't super emphasize the side pockets, so it's not immediately relatable either.

**Comment by Flaborized** [comment]
I think zewaka has said this, but I prefer the medkits having their little cross visible at all times instead of only from certain angles. Even if it's not realistically how the item would be held, I think it's important for visual consistency reasons and looks sorta strange in practice.

**Comment by ZeWaka** [comment]
Heyo, just posting my medkit commentary here on the PR as well.

When I added most of these medkit inhand sprites, I explicitly thought about the realism of having the cross only on two sides vs the more identifiable cross on all sides. The purpose of inhands are not to be realistic, but to convey what the person is holding for quick visual glances, so people don't have to examine you for every little thing.

However, when looking from the side at these medkits, they aren't uniquely identifiable. They could very well just be a lunchbox. This pulls away from the purpose of inhands in the first place.

Also, if you were going for realism, medkits aren't cubes, so the side views would need to be squished in order to make them cubic rectangle tall brick things.

**Comment by binarysudoku** [comment]
@flrsh all firstaid kits are now omnidirectional and backpacks have had several art passes

**Comment by flrsh** [comment]
The backpacks still look off, but I dunno if that's just a me thing. Maybe see what other people in #imspriter have to say? Also, I'd like to have the old sax inhands (besides the clipping).

**Comment by binarysudoku** [comment]
> The backpacks still look off, but I dunno if that's just a me thing. Maybe see what other people in #imspriter have to say? Also, I'd like to have the old sax inhands (besides the clipping).

There have been several review/iteration sessions in #imspriter and people by and large seem to be really happy with the current state of the sprites

I'll revert the saxophone and remove the clipping when i finish work today - itll look weird and wont connect to the mob properly but if its better than the new sprites then thats alright

**Comment by binarysudoku** [comment]
@flrsh submitted old saxophone inhands with clipping fixed, PR should be good to go with your blessing.

**Pull request merged**
