### PR TITLE
Disarm nerfs the threequel

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
see #5337 
Changes from previous:
Stam damage from disarm to 15 
Blocking reduces disarm chance by 100% instead of 80, but if the disarm would have disarmed, it drains an extra 10 stamina from the defender
Base disarm chance 37% -> 40% because I like round numbers

## Why's this needed? 
see #5337 

## Changelog

```changelog
(+)disarm stam cost 10 -> 30
(+)base disarm chance 37% -> 40%
(+)Disarm chance scaled down to 50% of current (20%) at targets with 200 or more stamina, and linerally scaled to current value (40%) on targets with 100 or less.  Blocking prevents disarm (not shovedown though), at the cost of (10) stamina if the disarm would have succeeded
(+)Disarm targets all held items at once
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
One criticism I heard a lot was that the stamina cost for disarming was too harsh. May be something worth looking into

**Comment by Azrun** [comment]
> Blocking reduces disarm chance by 100% instead of 80

Overall I like the counterplay this gives the defender. Maybe it costing some extra stamina absorbing the blow to improve the transaction would spice things up (maybe only if it would have disarmed?).

**Comment by Tarmunora** [comment]
> 
> 
> > Blocking reduces disarm chance by 100% instead of 80
> 
> Overall I like the counterplay this gives the defender. Maybe it costing some extra stamina absorbing the blow to improve the transaction would spice things up (maybe only if it would have disarmed?).

might be interesting to look at, yeah

**Comment by Gannets** [comment]
This reads like it'd be good. I like blocking being more of a hard counter, means it's more likely to be used.

**Pull request merged**
