### PR TITLE
Re-adds a second gardengear vendor to Nadir 

### PR DESCRIPTION
**Pull request by ijustneedaname**
## About the PR 
adds second botany gear vendor to nadir after it was deleted by fishing update

## Why's this needed? 
because it was there before

### CODE REVIEW

**Comment by Kubius** [comment]
This is how I'd personally be inclined to rearrange the area, but if having the vendor inside the planting bay is preferable for convenience I wouldn't object.

image

**Comment by Gannets** [comment]
I'm happy with either of these, apologies for deleting it originally. I thought I'd placed another somewhere but clearly didn't.

**Comment by ijustneedaname** [comment]
> This is how I'd personally be inclined to rearrange the area, but if having the vendor inside the planting bay is preferable for convenience I wouldn't object. Changes in PR as of now look to be properly set up.
> 
> image

i think this would probably be better, close to the plantmaster like the room on the left side - what should I do with this PR, is it possible for you to put in your changes or should I close this and you make one?

**Comment by ijustneedaname** [comment]
> I'm happy with either of these, apologies for deleting it originally. I thought I'd placed another somewhere but clearly didn't.

no worries, it prompted me to learn how to use sdmm & how to make a pr :')

**Comment by Kubius** [comment]
You could do the changes yourself (just make the map match the screenshot), or I could take it over - let me know here or with a ping if you opt for the latter.

**Comment by ijustneedaname** [comment]
I think it might be best if you took over since I am having trouble figuring out how to edit this

**Comment by Kubius** [comment]
Did the thing in #14863

**Pull request closed without merging**
