### PR TITLE
Resprites The Beer Keg

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Game Objects] [Sprites]

## About the PR:
Resprites the beer keg.
image

## Why's this needed?
The beer keg has been on the wanted resprites list for a while now, and the current ingame sprite was meant to have acted as a temporary sprite.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)Resprited the beer keg.
```

### CODE REVIEW

**Comment by Mister-Moriarty** [comment]
> The sprite for the still is very similar to the keg; perhaps that should be changed as well?

The still is on the resprite list, yes, but this PR is exclusively for the beer keg, as to allow for any critique to be solely focused on the keg sprite.

**Comment by WALPVRGIS** [comment]
I'm gonna check out how this looks ingame before properly reviewing, but from a cursory glance this looks great and is much needed, thank you!

**Comment by NightmareChamillian** [comment]
don't get me wrong, this is fucking amazing, but as was brought up the discord, it might be a bit too detailed and eyecatching for the bar.

**Comment by Azrun** [comment]
Cool sprite, but it feels to me like a beautiful focal point and seems a bit of our of place in a futuristic bar or retro-futuristic bar.

I think a steel keg makes more sense as the default sprite.  This one could have a goon style description referencing the fact it is made of wood or possible say it has been painstakingly been manufactured to look like wood.

This would be awesome as a set piece in a prefab or something to make a specific station feel unique.

🪙🪙

**Comment by flappybatpal** [comment]
As above, the sprite is amazing but it's going to be out of place next to any of the other sprites as it has a strong theme.

I suggest using it in a random room or prefab in beer festival style?

**Comment by Mister-Moriarty** [comment]
I'll begin work on a more contemporary sprite for the beer keg then, and use the one above for a subtype.

**Comment by WALPVRGIS** [comment]
I am late but after looking at how it looks ingame I am in agreement with what's been mentioned above; but yeah, would be great having it as a subtype as its still a really cool sprite. :)

**Pull request closed without merging**
