### PR TITLE
Adds Kitchen Dispensers to all maps

### PR DESCRIPTION
**Pull request by Eagletanker**
[MAPPING]

## About the PR 

Adds Kitchen Dispensers to all maps that lack them. 

## Why's this needed? 

Its a useful and good dispenser that should be on more maps. It's especially useful on lower pops. It also allows the bartender and chef to have more ingredients to work with at round start.  

## Changelog

```changelog
(u)Eagletanker
(+)Nanotrasen has allocated enough room allow the chef to install a kitchen dispenser on all maps. 
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Personally, this doesnt seem like a great change. Most of these reagents arent used by the chef, and the ones that are are gotten elsewhere. Doesnt feel great to depromote chef interaction with the rest of the crew and feel like this would pr would do that.

**Comment by Vaskritaya** [comment]
I gotta agree with Five, the dispenser is "nice" but it just has stuff you can get by either asking the bartender or convincing botany to grow you something. If they cannot or will not do that, that's still a desirable consequence of the game being cooperative and multiplayer. This just seems like it's cutting off yet one more avenue for crew interaction and inter-reliance.

**Comment by Eagletanker** [comment]
Any other dev thoughts or should I just close this and be done with it

**Comment by Nexusuxen** [comment]
This is a little late to the discussion but I get where others are coming from with saying this; I like having more ketchup and mustard and condiments as a chef a LOT, and it's one of the big reasons why I love Kondaru so much, but yeah, the contents of them do make Botany a little irrelevant. I'd personally be overall happy if this were merged, since it really makes it easier to be more creative as a chef, given how botany usually doesn't comply, and you can usually just go ask for a botany starter kit from Cargo.

Perhaps a better solution, albeit one that requires a not insignificant amount of coding, would be to make the reagent reserves in the dispenser limited, but able to be refilled automatically by dumping the right produce into it? (e.g dumping tomatoes in would refill ketchup reserves)
Some reagents would start out with a few hundred units, like mustard and chocolate, but others like mint and ketchup which have actual sources (smoking chocolate bars doesn't count imo) would maybe only have 50-100 units initially. Could also allow for adding stuff like hot sauce and other reagents since it'd be far more reasonable to have them as they're limited in quantity.

**Pull request closed without merging**
