### PR TITLE
Adds Status Displays to Kondaru

### PR DESCRIPTION
**Pull request by Wisemonster**
[QoL]

## About the PR 
Adds status displays around Kondaru

## Why's this needed? 
Map Parity

## Changelog

```changelog
(u)Wisemonster
(+)Added status displays to Kondaru, Horizon, and Destiny.
```

### CODE REVIEW

**Comment by flrsh** [comment]
There have been some status displays from your previous PRs that have ended up overlapping with lights / lightswitches / etc. - do you usually double check things by hosting a local server and going through the map?

**Comment by Wisemonster** [comment]
> There have been some status displays from your previous PRs that have ended up overlapping with lights / lightswitches / etc. - do you usually double check things by hosting a local server and going through the map?

Usually, yes. Although, I do sometimes miss some stuff. I'll go ahead and double check my current status display prs.

**Comment by Wisemonster** [comment]
Also, if there's a wall that has something on the other side, but isn't visible from side the status display is on, I'll put them on the same wall, for example the arrivals status display in this pr.

**Comment by Wisemonster** [comment]
> Also, if there's a wall that has something on the other side, but isn't visible from side the status display is on, I'll put them on the same wall, for example the arrivals status display in this pr.

If this is the issue you're talking about, let me know so I change these prs to stop that, and for future status display prs.

**Comment by flrsh** [comment]
> > Also, if there's a wall that has something on the other side, but isn't visible from side the status display is on, I'll put them on the same wall, for example the arrivals status display in this pr.
> 
> If this is the issue you're talking about, let me know so I change these prs to stop that, and for future status display prs.

Nah, that's fine. Just talking about overlaps on the same side. Thanks for double checking these PRs!

**Pull request merged**
