### PR TITLE
Reskin meteor showers on underwater maps to cybershark attacks.

### PR DESCRIPTION
**Pull request by BenLubar**
## About the PR
[feat]
Changes the meteor shower random event to be a cybershark attack instead. This changes the name of the event, the appearance of the big meteors, and the name of all the meteor chunks, but there are no actual mechanical changes.

## Why's this needed?

It's always weird getting hit by meteors while you're deep under the sea. Now it will still be weird, but in a different way that's possibly more fun to roleplay.

### CODE REVIEW

**Review by flrsh — APPROVED** [review]
Feature request: instead of the `pick_shatter_type()` proc, pick from a `shatter_type` list so I can var edit more things into it.

**Comment by Emcee-Gore** [comment]
Hey - would you be so kind to post pictures or a small video of how the event looks now in action?

**Comment by BenLubar** [comment]
https://youtu.be/NQN4U9DFDpY

**Review by ZeWaka — APPROVED** [review]
lol

**Pull request merged**
