### PR TITLE
Removes atmospheric dir types

### PR DESCRIPTION
**Pull request by Laboredih123**
[CLEAN][INTERNAL]

## About the PR 
Removes atmos dir types from the code.

Also adds the UpdatePaths tool from /tg/station, a great tool for PRs to put vast changes to multiple maps they make in a reproducible way. See https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths for more details, or the README added. 
This tool is under the AGPL license.

## Why's this needed? 
Dir types are very ugly and no longer needed.
The UpdatePaths tool is pretty nice.

### CODE REVIEW

**Comment by Laboredih123** [comment]
might need to be checked if it doesn't compile on secret

**Comment by TobleroneSwordfish** [comment]
Yeah no secret hates this, is there a particular regex or something that was used to remove them from the rest of the maps?

**Comment by Laboredih123** [comment]
I used various regexes to remove them in a previous pr

**Comment by Laboredih123** [comment]
Lemme find em

**Comment by Laboredih123** [comment]
image
It takes a fair amount of them. For the last one, your gonna need to swap in every dir. Might be better to do it manually.

**Comment by Laboredih123** [comment]
And for var edited named pipes, you'll need to do it manually.

**Comment by Laboredih123** [comment]
[dirtypekiller8000.txt](https://github.com/goonstation/goonstation/files/10819915/dirtypekiller8000.txt)
Made this for the UpdatePaths tool. Will remove all dir types in maps that have not had their dir varedited. The ones that have been edited will need to be removed manually.

**Comment by ZeWaka** [comment]
> The ones that have been edited will need to be removed manually.

one can do this manually by going through every type in the updatepaths script and searching for them in dmm files

**Pull request merged**
