### PR TITLE
Manta inner engineering revamp

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
[INPUT]

## About the PR 
This change expands inner engineering, the CE office, engineering control room, and some of engineering storage has been compressed to accommodate some of this. Inner engineering was previously ~110 tiles, it is now ~270.
image

## Why's this needed? 
Manta as a map wasnt designed for a singularity, previously inner engineering was way too small to practically work on one. Staying in the engine room would lead to you getting emped, not allowing you to hear comms. This PR should make managing a singularity on manta nicer, and should make doing singularities larger then 5x5 somewhat viable on manta.

## Changelog

```changelog
(u)Ikea
(*)Inner engineering on manta has been expanded.

```

### CODE REVIEW

**Comment by Eagletanker** [comment]
Probably should switch the consoles and the plant  near the CE windows. They don’t seem like someone would actually build them there when the space taken up by the plant pot is closer and works better.

**Comment by Eagletanker** [comment]
Also, I suggest moving that locker *anywhere* else from the CE’s room as where it stands with the PR it’s stupidly easy to just hack in the door, grab it, and go. Try to move the light switches and APCs off the south facing walls of the offices to, it’s going to look off in game. Also, why is there a Mop in the CE’s locker? The whole office kinda just seems cramped in general. You could probably remove the wall separating the office and the bedroom to open it up more if space is a issue. That human is the wrong spawner by the looks of it, might need to go back and fix it. Add some form of way to move between maintenance and the aft most air locks out of the sub (I suggest pipes if you don’t want to make a 1 tile maintenance) 

On a bigger note, probably shouldn’t encourage Bigulos on Manta due to its proximity to Escape and not many people understanding how to use the SRB now (you need to compensate for its pull. Aim off to the side, not directly at the middle) it seems this PR has good ideas (there needs to be a solid loop) but imo this isn’t the direction to head. From a gameplay perspective it works and it’s good for making bigulos which can’t do anything cause there’s not a PTL on Manta and reduces the difficulty of stealing from a head and overall gives too little room for too much being lost. **I would also like to remind you that this isn’t the first time a singulo chamber was built like this. Mushroom and the older Singulo maps aside from donut 2 are all pretty close to the singulo** again, I think it’s a good idea to fix the EMP thing (maybe remove it) but I don’t think this is a correct way to go about it. From a In Universe perspective this makes no sense at all. Why would the engine room be expanded when it’s clearly producing enough power to move Manta? Why would a head give up their room and make it harder to reach and work in their office from what it was before? 

Sorry if I come off as hostile, I think a better idea is just to make the Junction boxes take off more power, or add a TEG/Something Engineering like sub ala Mushroom if you want a stronger Engineering gameplay loop or more power.

**Comment by Eagletanker** [comment]
Also you might want to clean up that fire alarm in one of the manta propellers

**Comment by ThatFiveGuys** [comment]
"Probably should switch the consoles and the plant near the CE windows."
Done

"Also you might want to clean up that fire alarm in one of the manta propellers"
Oops also done

"Also, I suggest moving that locker anywhere else from the CE’s room as where it stands with the PR it’s stupidly easy to just hack in the door, grab it" 
That doors intent from a gameplay pov is crime (hence why it’s not an easy door for the CE to use to leave there office), and to easily steal the SRB when there’s a singuloose, however your right it is a bit too easy, the SRB has been swapped with the locker. This should make it a bit harder to steal the locker, needing to deconstruct the tables, and you can now more easily hack to get the SRB because there’s no CE and oh god oh fuck its loose.

"Add some form of way to move between maintenance and the aft most air locks out of the sub"
Dont see the need, I changed the airlocks just next to the propellers to not be blocked by shields, to compensate for the most southern ones being locked behind engineering access. Even then I don’t see an issue with requiring someone to let you through engineering to go to the rest of the ship, considering the ship is moving I dont foresee any life or death situations (considering they’ll likely get to the air lock in a sub) where someone needs to be back onto the ship now.

"Try to move the light switches and APCs off the south facing walls of the offices to, it’s going to look off in game."
Most of this one was a hangover from original engineering, however fair point, changed.

"That human is the wrong spawner by the looks of it, might need to go back and fix it." 
That is just the icon for the rathen’s spawner, works in game.

"From a In Universe perspective this makes no sense at all"
Personally, I do not really see this change as something in universe supposed to be a change per say, this is just how manta was designed lore wise. Several of the details I added would not make sense if this were to be viewed as a renovation.

"Also, why is there a Mop in the CE’s locker? The whole office kinda just seems cramped in general. "
These two are related, and it is cramped on purpose. the joke is that the CEs office was the previous secondary janitor’s office, hence the mop. The office being cramped shouldn't affect the CEs playstyle too much, they can still get anything they want from there office. 

"On a bigger note, probably shouldn’t encourage Bigulos on Manta due to its proximity to Escape and not many people understanding how to use the SRB now"
This change is mostly to make it nicer to increase the power of 5x5s, on manta it is practically only increase power or new construction as engineer work (considering no toxins + air not really leaking on ocean maps  + a lot of reinforced walls means repairs tend to be far less), and the former part is terrible to do on manta compared to donut3. Changes to better accommodate the latter on manta considering there's only one construction area now would be good however again this isn't that pr. More advantage to increasing power/increase in power drain in general would be good however that is less of a map issue and more of a mechanic issue, which is outside of the scope of this pr.

**Comment by Eagletanker** [comment]
Imo I don’t like it but the errors have been cleaned up. Still think the mop should be removed cause it doesn’t make much to your average player....

**Comment by ThatFiveGuys** [comment]
I like the mop because I find it funny, and it doesn't really detract anything. Its like the clown suit in captains locker on horizon.

**Comment by ThatFiveGuys** [comment]
Fuck it, going a different route, and dont want to deal with the merge conflict mapping issues that'll cause. Reliable bigulo would kinda fuck up what I got planned so Im going to leave bigulo unsafe on manta.

**Pull request closed without merging**
