### PR TITLE
Add missing security hangar remote door controls

### PR DESCRIPTION
**Pull request by FlameArrow57**
[QOL]

## About the PR 
This PR adds security hangar remote door controls that were missing on a few maps, as well as makes some directly related changes regarding the door type, hangar button object type, and pod types used on those maps as needed.

## Why's this needed? 
They were missing and changing the object paths helps for consistency across maps and standardization.

### CODE REVIEW

**Comment by nefarious6th** [comment]
I always assumed the hangar door controls being missing was very intentional so that no one could steal  secpod/communications array and get in that way.
Regardless, the lack of the hangar controls on Destiny and Clarion are intentional and I'd prefer to keep it that way. I can't guarantee this for the other 2 maps since I didn't have a hand in placing those.

**Comment by FlameArrow57** [comment]
> You beat me to it with this PR, however this PR changes only four of nine maps needing remote door controls added (that don't have missing object types). For reference, the nine I changed were Clarion, Cogmap, Cogmap2, Destiny, Donut2 (`donut2_new_walls.dmm` specifically), Donut3, Horizon, Kondaru, and Oshan.
> 
> The maps, excluding the above, that still need the door controls, however are missing object types, are listed below: `donut3_xmas.dmm`, `fleet.dmm`, `horizon_xmas.dmm`, `linemap.dmm`, `oshan_xmas.dmm`, `samedi.dmm`, and likely some others such as Icarus. I feel rather than attempt to resolve the broken objects myself, that judgement is best left to a developer.
> 
> I hope this helps!

I only changed maps that were in rotation, wasn't sure if the maps out of rotation needed it or not, I was not focusing on that. I was a little confused though, I think maps like Cogmap and the others in rotation do have remote door controls already?

image

Also, I believe the xmas maps are autogenerated (heard from TTerc), so I didn't touch those.

Thanks!

**Comment by Conchuckter** [comment]
Isn't there special radios on the secpods that are so only secpods can open the security podbay?

**Comment by Mister-Moriarty** [comment]
I think there has been some confusion about this PR on my behalf; it adds the remote door controls to the _inside_ of the hangars, my own changes adding them to the outside.



> Isn't there special radios on the secpods that are so only secpods can open the security podbay?

Yes, `r_door_control/podbay/security` uses `access_type = POD_ACCESS_SECURITY`, so only Security pods (or pods with Security comms modules) can interface with them.

**Comment by nefarious6th** [comment]
> Sure, I'm a little confused though, it seems a little trivial to do on the other maps anyways? Like on Cogmap 2 and Horizon if you wanted to you could hack into the security podbay and take off with a sec pod. For the maps that do have the door controls, it's a little harder, but you can still thermite your way in or deconstruct a wall to get in. It happens occasionally, but I don't usually see a whole lot of people hacking into the security podbay.

Yeah, it wasn't apparent to me from the PR desc. these were internal controllers only. Seems fine, randomly curious if you're able to access the controllers externally if you happen to have XRay vision.

**Comment by FlameArrow57** [comment]
Uh sorry, I don't even know what happened

**Review by pali6 — APPROVED** [review]

**Pull request merged**
