### PR TITLE
New AI expressions/faces

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 
This adds 20 new expressions/faceplates for AI players to choose from;
AIfaces
(Here are the 5 additional faces; Wink and Smug by me to round the total up to 20, and Tired, Content and ZZZ by BatElite!)
AIfaces2

The loading bar and glitched faces have small animations;
GIF 27-06-2021 20-21-03
GIF 27-06-2021 20-22-12

They work pretty well on AI Status Display screens too!
GIF 27-06-2021 20-20-26

## Why's this needed? 

- AI players don't get much in the way of personalization, I figured they could use some fun new customization content.
- Giving AIs some more silly or themed options makes for more fun AI gimmicks. Also great for use of status displays etc to show reactions to round happenings!
- Sometimes you're AI and you just feel like this; 
GIF 27-06-2021 20-26-59

## Changelog

```changelog
(u)Walpvrgis and BatElite
(*)AI players now have 20 new faces to choose from, so you can more effectively simulate just how disappointed you are in the crew.
```

### CODE REVIEW

**Review by Gannets — APPROVED** [review]
lovely as usual

**Comment by DimWhat** [comment]
😔

**Comment by Sovexe** [comment]
There's a single white pixel in glitched that appears for a frame in the top left corner

**Comment by WALPVRGIS** [comment]
> 
> 
> There's a single white pixel in `icons/obj/status_display.dmi` `ai_glitch` that appears for a frame or few in the top left corner

Sorry for the trouble, but could you grab a screenshot of it? I can't see this ingame and it doesn't appear to be in my current dmi, not sure what it could be 😱

**Comment by BatElite** [comment]
It's in the diffs for icon diff bot, but only on the actually glitchy frames it looks like.

Were we going to save ZZZ for braindead AIs?

**Comment by WALPVRGIS** [comment]
> 
> 
> It's in the diffs for icon diff bot, but only on the actually glitchy frames it looks like.
> 
> Were we going to save ZZZ for braindead AIs?

OH I SEE. Very strange as it doesn't appear in the dmi or the game itself while testing, and attempting to fix it just now didn't make a difference, screams!

I was going to, but it might be good for AI's to have a "I'm afk/not here" face option that they can choose, and then we make something more akin to a missing boot drive icon for braindead ais maybe? Lemme know if you'd rather I make it inaccessible for now! :)

**Comment by WALPVRGIS** [comment]
I'm not sure why the ai_glitch faces have those white pixels in the icon diffs, I remade the animations from scratch with different timings and triple checking everything and it's STILL THERE in the diffs. Extremely cursed. It looks like this ingame currently;

aiglitch

😭

**Comment by Gannets** [comment]
I think diff not has had issues like this before

**Comment by WALPVRGIS** [comment]
> 
> 
> I think diff not has had issues like this before

Seems so, it REALLY does not like that animation, for whatever reason. :'S

**Pull request merged**
