### PR TITLE
Reduces max holy water damage against vamps from 110 to 40

### PR DESCRIPTION
**Pull request by unfunnyperson**
[INPUT WANTED] [BALANCE]
## About the PR 
Reduces holy water damage against vampires to 40 down from 110.

## Why's this needed? 
Holy water is wayyyy too hard of a counter to vamp than it needs to be.

## Changelog

```changelog
(u)UnfunnyPerson 
(+)Holy water only deals a max of 40 damage against vamps
```

### CODE REVIEW

**Comment by BatElite** [comment]
labels please

**Comment by unfunnyperson** [comment]
oops forgot those

**Comment by PrimeNumb** [comment]
I don't think this solves much since you can just stagger your holy water glasses for the same effect (although it's a decent band-aid I suppose).
Suggestion: make holy water apply a damage-over-time effect capped at some maximum value. This would need audio feedback (maybe a sizzling sound) and possibly visual feedback.
Why is that better? It allows some extra wiggle room for damage ranges (you can have the maximum damage of a DOT at a fairly high value and then just increase the duration), and it gives vampires the option to retreat instead of being instantly owned by any nerd that figured out that you can just throw multiple glasses.
The implementation could be re-used for an acid rework as well.

**Comment by Tarmunora** [comment]
🤔 subtype of burning status that drains vampire blood in addition to burn damage?

**Comment by PrimeNumb** [comment]
> 🤔 subtype of burning status that drains vampire blood in addition to burn damage?

could use a visual change to better distinguish it from actual burning

**Comment by TDHooligan** [comment]
i still think you might want to leave some of the up-front damage there, both as a tell of roughly how much water there was in a container & to put extra immediate pressure on said vampire, since they can still close out fights pretty quick

**Comment by wsock** [comment]
Holy water is already unrobust and can be countered by healing chems, I can't see how this would this benefit anyone besides make Chaplin even more useless. Unless you can have 2 versions of holywater, True Holywater and Holywater.

Chaplin should come and be the only one who can make True Holywater by blessing normal Holywater.

**Pull request closed without merging**
