### PR TITLE
ChemMaster use local cache

### LINKED ISSUE #12815: oops! all pent
### Labels

[BUG][MINOR]

### Description

chemmaster pill/bottle names are stuck on the first thing you set them to

### Steps to reproduce

1. make bottles of pent in the chemmaster, label them pentetic
2. make bottles of perf, label them accordingly
3. they are labeled pentetic

### Expected Behavior

no mislabeling bottles

### Additional Information & Screenshots

Reported by: RDCB
On server: Goonstation 3 Roleplay: Morty
Round log date: 2023-01-19-05-19
Reported on: 2023-01-19 06:31:15
Map: COGMAP

### LINKED ISSUE #12858: Chem Master 3000 keeping name of previously inserted chemical
### Labels

[BUG][MINOR]

### Description

CM3000 isnt changing the name of chemicals

### Steps to reproduce

1. Put one chemical into the CM3000 to make patches, pills ect (ex water)
2. Put a NEW chemical into the CM3000 (ex strange reagent)
3. SR pills now named water unless you specifically change the name first.

### Expected Behavior

Change the name of the chemical. It did this before so.

### Additional Information & Screenshots

Reported by: Shiiba
On server: Goonstation 3 Roleplay: Morty
Round log date: 2023-01-24-04-44
Reported on: 2023-01-24 05:57:32
Map: COGMAP2

### LINKED ISSUE #12912: Chem master
### Labels

[BUG][MINOR]

### Description

chem master saves the previus chemicals name causing misslabeling

### Steps to reproduce

make a pill ,bottle etc.
then make another pill, bottle etc. but with a different chemical
both of them named same but diffrent chemicals

### Expected Behavior

it shouldn't sacve previus chemcals name

### Additional Information & Screenshots

Reported by: Wantilathor
On server: Goonstation 3 Roleplay: Morty
Round log date: 2023-01-28-14-17
Reported on: 2023-01-28 14:49:10
Map: KONDARU

### PR DESCRIPTION
**Pull request by Saicchi**
[FIX]

## About the PR 
Removes cache saved in the ChemMaster to a cache saved in a user local session that gets deleted when the UI window is closed.
I added the cache as a QoL feature but it seems to have caused people more headaches than helped.

## Why's this needed? 
Fix #12815
Fix #12858
Fix #12912

### CODE REVIEW

**Comment by CaioFrancisco** [comment]
BTW, you don't need to make changelogs for bugfixes. Specially when it looks cryptic to whoever isn't aware of git.

**Comment by ZeWaka** [comment]
!merge_upstream

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Looks like if you clear the name it just becomes blank instead of displaying what the name of the bottle will actually default to. Re-opening the UI fixes this.

**Comment by Saicchi** [comment]
> Looks like if you clear the name it just becomes blank instead of displaying what the name of the bottle will actually default to. Re-opening the UI fixes this.

Didn't think it was necessary, but now I added it to the placeholder, should show the default name when empty now.
(Now there is a really cool effect where the placeholder updates when the main reagent becomes a minor one by removing units off it ).

image

**Comment by ZeWaka** [comment]
!merge_upstream

**Pull request merged**
