### PR TITLE
Mining borg buffs

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Someone asked me how mining borgs can upgrade their mining tools, and they kind of can't, which seems a bit sad?
So I thought I'd change that and also found some other annoying things while doing it that I thought could use a change.

- Gives mining borgs an item_holder device that can hold and use a mining_tool or mining_tools object.
- Gives mining borgs a free meson upgrade along with their jetpack, because going mining without meson vision is kinda wack.
- Allows direct emptying of mining satchels and ore scoops into normal ore refiners.
- Allows mining satchels to also hold refined materials, so you can move them.

Some small adjacent changes:
- Borgs should now be able to use ladders. (Some prefabs have them!)
- Borgs could open the nanofab window from a distance, but not actually do anything in the window, should now be fixed.
- Rechargers now check for can_drop on the item, instead of issilicon() on the user, so borgs can put mining tools that are out of charge into the recharger with their item_holder, if they want to.

## Why's this needed? 
- A borg having to user their mining drill all round without being able to share in the joy that is matsci mining tools is kinda of sad and boring.
- Making a custom mining tools is kind of hard if you can't move the refined ores around properly, so that had to change too.
- Mining without mesons makes little sense, you can't even see most of the readouts of the scanners. And human miners start out with both jetpack and meson goggles, so I felt it was ok to give borgs both as well.

If you think this buffs borg mining too much, please comment! I felt it was fine, but I may be mistaken.
## Changelog

```changelog
(u) zjdtmkhzt
(+) Mining borgs should now have a new mining tool holder to allow them to use custom mining tools.
(+) Mining tools now get a free meson upgrade as well.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Why dont the held tools draw from the borgs charge (ideally at an increased rate compared to normal)?

**Comment by Hypertripp** [comment]
> Why dont the held tools draw from the borgs charge (ideally at an increased rate compared to normal)?

i imagine it would require rewrites of the actual mining tools to take from the battery in combination with when there held, a lot of work and this seems like a effectint fix

**Comment by ThatFiveGuys** [comment]
> > Why dont the held tools draw from the borgs charge (ideally at an increased rate compared to normal)?
> 
> i imagine it would require rewrites of the actual mining tools to take from the battery in combination with when there held, a lot of work and this seems like a effectint fix

Surprisingly easy to do, see RCD code and light replacer code for an example of code which takes from a borgs batterie when used by a borg

**Comment by zjdtmkhzt** [comment]
Would be possible, tbh, the main reason they don't is ~~that I didn't feel like doing components or processing code~~ balance concerns.

**Comment by vocalpocal** [comment]
This is t-down for me. Mining borgs are already ridiculously efficient at mining, and make miners seem like a joke in comparison. They are extremely fast, immune to rads and can carry a lot of materials. They have only one real weakness and it is that their mining drill does not work on some materials, like pharosium, but works just fine on almost everything. When you run to a tough ore deposit your super high speed drills it 10 times a second, so as long as you can make a dent any tough material is not a problem.

**Comment by zjdtmkhzt** [comment]
May be true, it did feel very fast in testing.
It still makes me 😔 though that mining borgs can only use a drill and have no way of diversifying their mining tool.
Maybe it could be some kind of more difficult to obtain upgrade or something, idk.

**Comment by Crystalwarrior** [comment]
I say no to holding matsci tools, and yes to everything else. Maybe split up the matsci tools update in a different PR?

**Comment by Momoberry** [comment]
Borgs should be better at mining than miners. Miners get additional bonuses to compensate, like having hands and a bunch of explosion resist. They can also throw and come back from spacing themselves by accident, a borg without jetpack can't tbf. Miner borgs are also basically required to have jetpack/mesons/speed, so they're locked out of other upgrades until they mine for a while. Personally fine with this going through and seeing how it affects things over a week or two, and THEN making changes if they need it, not gonna complain if we get ores quicker, after all.

**Comment by zjdtmkhzt** [comment]
Even for borgs without a propulsion upgrade (which miners get by default) they usually have some means of changing directions in space, I think? Like fire extinguishers and stuff.

**Comment by vocalpocal** [comment]
> Borgs should be better at mining than miners.

They already are, easily, imo.

**Pull request closed without merging**
