### PR TITLE
Changes a line in the port-a-brig manual about beating criminals

### PR DESCRIPTION
**Pull request by Merlin1230**
## About the PR 
Changes the line in the port-a-brig manual from "as easy as beating a criminal to death" to "as easy as arresting those criminals" 

## Why's this needed? 
The old line made it sound like it was okay to beat criminals _to death_. We shouldn't really be saying this cause it could make new sec players think its okay.

### CODE REVIEW

**Comment by penny64** [comment]
That is definitely just a tongue in cheek joke that you shouldn't do that

**Comment by Merlin1230** [comment]
> 
> 
> That is definitely just a tongue in cheek joke that you shouldn't do that

Well, I've had a new player that saw it ask why we beat people, so some do definitely get the wrong idea from it

**Comment by getbrecked** [comment]
honestly i think new players have enough common sense to understand "beating criminals = bad", this is just a joke and it shouldn't be removed

**Comment by Merlin1230** [comment]
Giving it some thought, it probably wouldn't do much if the line was kept. But I'll leave this PR open in case some other people think it should be changed.

**Comment by Tarmunora** [comment]
To me "simple as beating to death" reads more as saying that one should consider using the port-a-brig in situations where otherwise it would be simpler to beat to death (e.g.: people with a missing arm that cannot be cuffed)

**Pull request closed without merging**
