### PR TITLE
Changes to Traitor Generic Items

### PR DESCRIPTION
**Pull request by Momoberry**
## About the PR 
The PR swaps around several items from the syndicate buylist for traitors. I specifically targeted items that I felt either didn't really make proper sense to be job locked, and are rarely seen and entertaining. Most should make sense, although there may be a few that I added because I think they would bring a lot of gameplay potential, as well. I went over the list with several people to curate it to items that people agree on, and items that weren't agreed on were not added.

I also fiddled with the surplus items a bit and added weaker variants of surplus items that were exclusive, or just swapped things from exclusive. The only swapped gear from surplus were banana grenades, and I job-locked them to clown, because I think it's super thematic. I made single item versions of bear traps and breaching charges and upped their cost to reflect the gamemode balance.

EDIT: Ikea made a really good point about not listing out the actual items added to the generic list in the description, so the items added are as followed.
**GENERIC**
Decided to revert several after getting input. These are the current ones. It's a smaller list but I'm still confident that this would give a lot more gameplay variety, so I'm happy with it.
Single Bear Trap (2TC) Modified from original surplus option
Standard Breaching Charge (3TC) Modified from surplus option
Chameleon Bombs (4TC)
Moustache Grenade (3TC) - 
Pickpocket Gun (3TC)
**JOB LOCKED**
Banana Grenade was removed from surplus only and given to Clown as a job specific item.
Telegun was given to scientist, but I've realized it just has too many barriers for a scientist versus a head of staff so it's reverted.
Syndicate Cargo transporter access was also given to the Chief Engineer.

I was interested in a few other items such as poison bottles, but decided against it since it seemed controversial since sleepy pen with poison bottles objectively outperforms syringe gun.

## Why's this needed? 
Goal of the PR is to make the traitor gamemode a little more varied, and to spice it up by giving more options to players. A lot of players have talked about wanting more generic items because there's a large amount of job locked items, and not all of them are very thematic to their jobs. The only thing that was added that is pure rampage focused was Stimulants, but as those got their TC upped to six and underwent some changes, I think they should be made generic as they no longer are the show stopper combo that wins the game for a scientist. 

Traitor is the best game-mode because of the variety, but I think a lot of people have gripes about the amount of limited items that traitors have access to despite many cool items existing, and this just aims at making it more varied and having more gameplay opportunities, especially for gimmicks. I think a lot of people feel like they HAVE to take surplus to get a chance at any fun gimmick items if they aren't a popular job. The issue with that is there are a lot of items excluded from surplus that you have to code dive to find out, because most people assume that surplus has access to every item. I knew it didn't have boomboots and the syndicate hat, I didn't know it didn't have csabers, powersinks, shotguns, maneaters, butcher knife, hotdog cart, red saw, trash compactor, wasp crossbow, powergloves, conversion chamber, etc etc without codediving, and you can roll duplicates of crappy items on top of that. While I kind of want to work on that in a different PR, I think giving more items to the generic list will also help significantly with gameplay variety and make people more interested in trying new routes.

Don't think I missed a label, please don't kill me Zewaka, I looked at every label 😱 
## Changelog

```changelog
(u)MomoBerry
(*)Shuffled around several items to the Generic traitor List, and changed some job restricted traitor gear access.

### CODE REVIEW

**Comment by Tarmunora** [comment]
pickpocket gun and syndicate cargo teleporter changes are good

Everything else can go though imo

**Comment by ThatFiveGuys** [comment]
The changes should be better listed in the about the pr section instead of just a list and saying good look for those who dont know how to look at that. Some of these changes Im eh about but a lot of these changes seem like they wouldnt fit as a generic item. This list will roughly be ranked from items i think would be the worst to be available to all to the ones im more eh about

Vuvuzela gun: This item is just really boring and strong, its an in almost all cases better taser. Im fine with it as a staffie item because its good for stealing stuff which is fitting, however I think having it be something people can always get will promote more boring pure rampagey playstyles instead of more creative and interesting ones.

Arczapper implant: This implant was specifically made to give engineers a cool microbomb variant (and was intended to come with more micro variants for other jobs). Having it be something everyone can get ruins the whole point of it being a cool unique item for engineers to fit them thematically (plus the fact you can hotwire the grid for extra arczapper damage doesnt fit all jobs)

Guardbuddy ammo replicator: This just doesnt really fit with most jobs, while all jobs can do guardbuddy stuff this requires hacking and extra work, and guardbuddy is part of rd’s thing with them being one of two people with su access roundstart. 

Donk pockets: In there current state these things are laughably strong, two credits for seven donk pockets that will last you the whole round and make you practically unkillable. I think these things could be balanced if it was only one donk pocket for 2 tc, however i think giving all traitors an amazing healing item would discourage theft of supplies from doctors which i dislike. 

Breaching charge: The only gameplay function this serves is breaking into armory (leaving a 5 wide hole for people to come into upload doesnt seem complimentary to keeping the thing rogue). Having an item thats only purpose is break into armory easy is just really boring and doesnt fit with traitors generally more emergent items.

Stimulants: this thing is just not that interesting of an item and while im fine with it as is i dont want to see it that much as i think itd get boring quickly.

Thermal scanner: this item just seems too strong to have as a generalist item that everyone can get, knowing what people are nearby is very strong.

Banana grenades: Im pretty eh about giving it to them but clown already has a shitload of traitor options (also unrelated but these things are laughably weak and the traitor ones could definitely go with a buff)

**Comment by Momoberry** [comment]
> The changes should be better listed in the about the pr section instead of just a list and saying good look for those who dont know how to look at that. Some of these changes Im eh about but a lot of these changes seem like they wouldnt fit as a generic item. This list will roughly be ranked from items i think would be the worst to be available to all to the ones im more eh about
> 
> Vuvuzela gun: This item is just really boring and strong, its an in almost all cases better taser. Im fine with it as a staffie item because its good for stealing stuff which is fitting, however I think having it be something people can always get will promote more boring pure rampagey playstyles instead of more creative and interesting ones.
> 
> Arczapper implant: This implant was specifically made to give engineers a cool microbomb variant (and was intended to come with more micro variants for other jobs). Having it be something everyone can get ruins the whole point of it being a cool unique item for engineers to fit them thematically (plus the fact you can hotwire the grid for extra arczapper damage doesnt fit all jobs)
> 
> Guardbuddy ammo replicator: This just doesnt really fit with most jobs, while all jobs can do guardbuddy stuff this requires hacking and extra work, and guardbuddy is part of rd’s thing with them being one of two people with su access roundstart.
> 
> Donk pockets: In there current state these things are laughably strong, two credits for seven donk pockets that will last you the whole round and make you practically unkillable. I think these things could be balanced if it was only one donk pocket for 2 tc, however i think giving all traitors an amazing healing item would discourage theft of supplies from doctors which i dislike.
> 
> Breaching charge: The only gameplay function this serves is breaking into armory (leaving a 5 wide hole for people to come into upload doesnt seem complimentary to keeping the thing rogue). Having an item thats only purpose is break into armory easy is just really boring and doesnt fit with traitors generally more emergent items.
> 
> Stimulants: this thing is just not that interesting of an item and while im fine with it as is i dont want to see it that much as i think itd get boring quickly.
> 
> Thermal scanner: this item just seems too strong to have as a generalist item that everyone can get, knowing what people are nearby is very strong.
> 
> Banana grenades: Im pretty eh about giving it to them but clown already has a shitload of traitor options (also unrelated but these things are laughably weak and the traitor ones could definitely go with a buff)

I agree on the donk pockets comment, it was an oversight and it should only be a single donk. Arc-zapper I specifically asked aloe if they were ok with it being generalized as they were the one who made it, and that's why it's in even though it has some themes with engineering. It's not overly thematic, and since several bomb implant adjustments have happened, I feel like the general player deserves options.

 Vuvuzela is pretty fun for the majority of people I would think, it's likely just burn out and not seeing the things in the light of the standard player. Same with the breaching charge comment being only for breaking into the armory, which isn't true at all. Banana grendes are very thematic for clown and aren't really supposed to be a strong item, hence 1tc. They are meant as a goofy gimmick item and more for flavour, and they still have their use. If anything I feel like they are more deserving of clown traitor gear than several items on their list, including chameleon bombs, which is why they were swapped.

Thermal is strong but it doesn't win the game automatically, by any means. It seems like this is peak traitor gear since they're supposed to be more tuned towards stealthy nowadays? I don't really understand. They're also fairly notable if you see someone wearing thermals as they are in very short supply. The crew don't really have wall piercing marksman rifles, so I don't think things will be THAT absurd, although they will absolutely give an edge. 

I'm more than willing to edit some values, like I did with beartrap and the breaching charge, I just didn't want to over complicate the PR.

Also you're totally right and I should list the actual items.

**Comment by nefarious6th** [comment]
most of these are okay; vuvuzela gun is beefy af and i wouldn't give it out to everyone for as low a TC cost as it is. it DOES outclass a taser, imo. not sure how i would feel about the potential for nerds to get a sabre or katana and a vuvuzela gun and then just stun and slash.
would love to see more cham bombs though; this seems fun for that.

**Comment by Momoberry** [comment]
> most of these are okay; vuvuzela gun is beefy af and i wouldn't give it out to everyone for as low a TC cost as it is. it DOES outclass a taser, imo. not sure how i would feel about the potential for nerds to get a sabre or katana and a vuvuzela gun and then just stun and slash. would love to see more cham bombs though; this seems fun for that.

Hm, I guess I havent ran into vuvuzela lately, I didn't realize it was consistently that strong. What do you think should be done with it, higher TC cost if it's going to be generalized? 6tc? Little pricey but it is basically just getting a taser gun, and since duct tape exists it could probably be a good combo

**Comment by nefarious6th** [comment]
just what you said, i think no vuvuzela + rampage weapon does a pretty bang-up job of handling it. 6tc is pretty steep for the funny honk horn gun thematically, but im not sure what else to do for it mechanically since it's kind of whack. i do like a general availability stun for antags though, that seems nice, people just have to be ready to dish out for them

**Comment by Flaborized** [comment]
as the person who made the syndie thermals, I don't think they make much sense as a general item since they're like, a dead giveaway unless you're a job that already has access to thermals. they're meant to be sneaky things you could wear if you normally could be caught wearing them, and making them generalized pushes them away from that design goal!

**Comment by ZWRh3** [comment]
making stims more common wont fix them being just bad nowdays

**Comment by ThatFiveGuys** [comment]
I think you can get it to a state to where vuvuzela is balanced to use with a rampage item (probably just like 4 tc), however just because its balanced doesnt mean its fun. I feel like generalizing it will shift the point of the item being something staffies can use for theft to something that pairs for early rampages and the former is far more interesting and fun of an application and i dont want to see that application dampen due to it missing the thematic connection to staffies.

**Comment by UrsulaMejor** [comment]
Advanced Thermal Scanner - No
Single Bear Trap - Funny, so sure
Standard Breaching Charge - Could see some good use, sure
Chameleon Bombs (3TC) - Sure, probably raise the price since them being clown-only (a job with no access) was why they were discounted. No ready-made explosion that can break tiles should be available for under 4TC imo.
Fly Zapper Implant - No; this thing isn't good enough for general use and mostly gets its charm from being electricity themed and belonging to the electricity themed jobs.
Guardbuddy Ammo Replicator - No; this stuff should stay with the jobs that most benefit from it (those with easy access to the guardbuddy docks so they can mod them without it being suspicious)
Moustache Grenade - AOE mask/internals denial for only 1 TC? Again, this is at a discounted price because it's locked to jobs without access to more dangerous stuff to combo it with.
Pickpocket Gun - Sure
Stimulants - No. Scientists get access to this item because of the "nerd rage" joke, and because it's not that huge of an improvement over the chems they can naturally make at their own job. The most I could see expanding this to is doctor.
Syndicate Donk Pockets - Not at this price; the healing on these is redonkulous and their price has been discounted because of which jobs get them.
Amplified Vuvuzela - No; annoying items should stay with the annoying jobs. These are also discounted because it gives stuns to a job that doesn't have much on its own to combo them with.

**Comment by Momoberry** [comment]
> Advanced Thermal Scanner - No Single Bear Trap - Funny, so sure Standard Breaching Charge - Could see some good use, sure Chameleon Bombs (3TC) - Sure, probably raise the price since them being clown-only (a job with no access) was why they were discounted. No ready-made explosion that can break tiles should be available for under 4TC imo. Fly Zapper Implant - No; this thing isn't good enough for general use and mostly gets its charm from being electricity themed and belonging to the electricity themed jobs. Guardbuddy Ammo Replicator - No; this stuff should stay with the jobs that most benefit from it (those with easy access to the guardbuddy docks so they can mod them without it being suspicious) Moustache Grenade - AOE mask/internals denial for only 1 TC? Again, this is at a discounted price because it's locked to jobs without access to more dangerous stuff to combo it with. Pickpocket Gun - Sure Stimulants - No. Scientists get access to this item because of the "nerd rage" joke, and because it's not that huge of an improvement over the chems they can naturally make at their own job. The most I could see expanding this to is doctor. Syndicate Donk Pockets - Not at this price; the healing on these is redonkulous and their price has been discounted because of which jobs get them. Amplified Vuvuzela - No; annoying items should stay with the annoying jobs. These are also discounted because it gives stuns to a job that doesn't have much on its own to combo them with.



> Advanced Thermal Scanner - No Single Bear Trap - Funny, so sure Standard Breaching Charge - Could see some good use, sure Chameleon Bombs (3TC) - Sure, probably raise the price since them being clown-only (a job with no access) was why they were discounted. No ready-made explosion that can break tiles should be available for under 4TC imo. Fly Zapper Implant - No; this thing isn't good enough for general use and mostly gets its charm from being electricity themed and belonging to the electricity themed jobs. Guardbuddy Ammo Replicator - No; this stuff should stay with the jobs that most benefit from it (those with easy access to the guardbuddy docks so they can mod them without it being suspicious) Moustache Grenade - AOE mask/internals denial for only 1 TC? Again, this is at a discounted price because it's locked to jobs without access to more dangerous stuff to combo it with. Pickpocket Gun - Sure Stimulants - No. Scientists get access to this item because of the "nerd rage" joke, and because it's not that huge of an improvement over the chems they can naturally make at their own job. The most I could see expanding this to is doctor. Syndicate Donk Pockets - Not at this price; the healing on these is redonkulous and their price has been discounted because of which jobs get them. Amplified Vuvuzela - No; annoying items should stay with the annoying jobs. These are also discounted because it gives stuns to a job that doesn't have much on its own to combo them with.

Thanks for explaining each one, I appreciate it. I've dropped vuvzela, donks, ammo replicator, thermals, and stims. Donks I realized are just budget stims and even if I increased the price to 3TC, it just doesn't really fit what the original niche i wanted was, which was just healing. 

You're right about ammo replicator, the main reason I added it is because it's rarely seen and honestly a very fun item WHEN someone gets it setup, but it's also fairly thematic and it was more of a personal bias decision over a theme decision. Vuvuzela is cracked more than I realized, since I haven't seen it in a while, so I was debating 6TC but realized that's just making the item try to fit in a place where it honestly doesn't need to be, so it got cut too. Thermals were in because I wanted traitors to have another stealth option that was more sneaking into guarded areas, but I'm not very attached to the idea so I don't have an issue cutting it.

Moustache grenade is something I'd still like to be in, so I'll probably raise it to 3TC since it actually has some real utility to it. Fly zapper is still something I want in just because microbombs have seen a lot of changes recently which have made them a lot less efficient than they once were, and now that they are more in line with flyzappers, I kind of wanted to give players an option between the two. But I agree that it actually is an item that's fully in theme like ammo fab, so it should probably stay where it is.

Also raised chameleon bombs to 4TC, so you can only get 3 purchases. 
That makes the current list Chameleon bombs, moustache grenade, breaching charge, bear trap, pickpocket. And Syndicate transporter added to CE, as well as banana grenade swapped from surplus to clown only.

**Comment by Momoberry** [comment]
> On addition to everything said here, I'd also like to mention that the Syndicate Device Analyzer should be made available to the CE as well, considering he's given cargo transporters in this PR, and that the RD gets all the items scientists get

It's something I've brought up before and was told no, which is why I didn't add it to the list, since I don't really want any controversial stuff that was already denied to drag the PR down.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/9c66802b893f7359ccd0af98f79296b64d00eb79

**Pull request closed without merging**
