### PR TITLE
Adds southern trait

### PR DESCRIPTION
**Pull request by Xetanai**
[FEATURE]

## About the PR 
Adds a new frontal gyrus mutation, and accompanying trait, to the game. The mutation will cause you to speak with a southern drawl. It's hard to explain simply, so I've fed this description into it to demonstrate.

Adds a new frontal gyrus mutation, n' accompanyin' tra't, t' th' game. Th' mutation will cause y'all t' speak with a south'rn drawl. It's hard t' explain simply, so I've fed th's description int' 't t' demonstrate.

Overall, it's pretty light as far as text mangling goes. Most words should survive largely unchanged.

## Why's this needed? 

Space Station 13's speech mutation system is interesting, but there aren't many options for mutations that leave the majority of your input unchanged. This aims to offer an option for that while also filling a gap that some players are currently filling by hand on the RP servers.

## Changelog

```changelog
(u)Xootdoot
(+)Added a southern language mutation and trait. Cowboy hat not included.
```

### CODE REVIEW

**Comment by flrsh** [comment]
Adding the `input wanted` tag because I don't think many devs are that familiar with Southern American accents and it'd be good to get input from people who are familiar.

**Comment by Xetanai** [comment]
Thank you for the input I've already gotten so far on the thread, I'll be tweaking to try and address it later today

**Comment by flrsh** [comment]
Hey @Xetanai, still planning on working on this? If so I can add the ORGANIC tag!

**Comment by flrsh** [comment]
Closing but feel free to make a new PR when you have the time!

**Pull request closed without merging**
