### PR TITLE
Resprites drinks.dmi

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
[ADD TO WIKI]
## About the PR 

Makes reagents in a drinking glasses visually decay same way they do in beakers and resprites most stuff in drinks.dmi to be in correct perspective. I didn't touch most unused sprites.

## Why's this needed? 

Correct perspective good and visually decaying reagents are also very cool.

## Changelog

```changelog
(u)Arthur Holiday
(*)Resprited various drinking glasses and made them show the amount in them better.

### CODE REVIEW

**Comment by Carbadox** [comment]
Pics to show off how it looks in the PR description would be dope

**Review by Carbadox — APPROVED** [review]

**Comment by Flaborized** [comment]
these are good

**Comment by mordent-goonstation** [comment]
Below refer to the icon states:

- `rum` seems a bit too cartoony, second opinion from someone?
- `glass-round` seems too rounded to me, i.e. curves back in too far.
- `tea0` and `tea1` are both very tall cups, prefer a little squatter (or at least the ratio made so that they're wider)
- glass-cocktail` could use being sharper at the rim of the glass, looks like it sort of curves up at the top as-is.

**Comment by MatheusIsNotAvailable** [comment]
Sprite-0002

**Comment by MatheusIsNotAvailable** [comment]
tried to make "rum" look more like a bottle, changed the glasses based on feedback and made the tea cups 1 pixel shorter, they were only 2 pixels bigger than the current in game one, so I don't think they were too big, they need to be a little bigger to fit the wizard image too. hopefuly it is all better now. I am also posting images as requested. @mordent-goonstation

**Comment by mordent-goonstation** [comment]
@MatheusIsNotAvailable I've added a changelog entry to the PR's description, using the name added to some of your other PRs. If this was wrong or whatever let me know and I'll get alter it.

**Pull request merged**
