### PR TITLE
Resprites things from nuclear.dmi

### PR DESCRIPTION
**Pull request by nefarious6th**
[sprites][cleanliness]

## About the PR 

Resprites things from nuclear.dmi to be in perspective; does a little file shifting to make them be in order.

Sets up a new environmental_objects.dmi with copies of all the nuclear sprites because I'd like to re-path the 60-ish files that use those sprites to there. 
- It's intended for decal-like fake objects, which I also want to add more fake machines and stuff since the nuclear engine sprites seem to be used maybe a bit too often. 
- I'll probably re-path some other things to here soon too, namely I was thinking of moving tombstones from halloween.dmi since they're used as environmental decals in a lot of azones and I wanted to resprite + expand on those.

Also adds directional sprites for the different engine states but not the neutron thing-y. They're there if anyone ever wants to pick up the engine again. If not, because all the things are saved in environmental_objects, if pruning of icons one day happens and there's no reason to keep nuclear.dmi around anymore, then nothing unique would be lost by removing it.

Sprites below
nukedmisprites

## Why's this needed? 

I didn't know at first, but this was actually on the project list, so I guess it resolves that. Perspectivizes some old assets and makes a space for expanded and new environmental sprites.

### CODE REVIEW

**Comment by Azrun** [comment]
States in `icons/obj/machines/nuclear.dmi` look odd in dmi diff, that just the bot?

Look sweet though! Hopefully all nuclear curses are not applicable to the sprites. 😉

**Comment by nefarious6th** [comment]
> States in `icons/obj/machines/nuclear.dmi` look odd in dmi diff, that just the bot?
> 
> Look sweet though! Hopefully all nuclear curses are not applicable to the sprites. 😉

Should be all good! There were like 3 things named stuff like "0,1", varying from radiation suit pieces to wall tiles to lockers. Because they were all marked as duplicate and I didn't touch the wall tiles that were marked as the "primary" icons with those names, I assume the pathing for them was never valid in the first place 🤷 

Thank you!

**Comment by BatElite** [comment]
I don't think you need to keep the old icons around separately BTW.

**Comment by nefarious6th** [comment]
> I don't think you need to keep the old icons around separately BTW.

I just feel bad deleting old work 😔 But I can remove them.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
why are the sprites in duplicate places

also what's with the `0,1` stuff, those are just autogenerated sprite icon state names

**Comment by nefarious6th** [comment]
> why are the sprites in duplicate places
> 
> also what's with the `0,1` stuff, those are just autogenerated sprite icon state names

I duped them since I wanted to re-path all the instances to the decal dmi later since I think having it all pathed to the scrapped engine dmi is kind of weird + adding new objs and sprites there seems odd. This isn't something I can immediately do, I think, since Clarion has some instances on the map Z-Level.

I have no idea about the 0,1 stuff, that's part of the original dmi, but I can clean those things out too, since a lot of it is sprites that exist in other dmis?

**Comment by BatElite** [comment]
x,y sprites are normally autonames from importing a sheet, so they're probably just not cleaned out.

Small note for whoever merges this to also move nuclear.dmi in the wanted resprite project.

**Comment by nefarious6th** [comment]
Okay, I went ahead and cleaned the weird sprites out of nuclear.dmi; I checked all instances of where nuclear.dmi was referenced and it's only used for the machines and fuel rod sprites, so those are the only things I kept in the dmi.

I also deleted the environmental_objects.dmi and will save re-pathing sprite stuff for another PR once I can move everything over in one go.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
