### PR TITLE
[Donut 3] Listening Post Fix

### PR DESCRIPTION
**Pull request by comradef191**
[MAJOR]
## About the PR 

Adds the Central Ring of Donut 3's Listening Post to the Listening Post area, preventing people being able to teleport into it and remove a window for easy access to the Listening Post

## Why's this needed? 

Getting into the Listening post THIS easily should **not** be possible

### CODE REVIEW

**Comment by ZeWaka** [comment]
what's with the random assorted unrelated changes

**Comment by comradef191** [comment]
thats uhhh
what the fuck??
i never touched any of that shit???
bleugh

**Comment by comradef191** [comment]
working on fixing the random changes? genuinely dont understand how the fuck or why those got changed

**Comment by comradef191** [comment]
darn github closing it cause i force pushed the branch >:C shouldn't change random shit this time

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
