### PR TITLE
resprites AI eyebots

### PR DESCRIPTION
**Pull request by Paaiii**
## About the PR 
Cleans up the sprite for the AI eyebot shell!
aishellchange

## Why's this needed? 
New sprites good!

### CODE REVIEW

**Comment by Xkallubar** [comment]
I don't like how it's fatter.

**Comment by Gannets** [comment]
I think this is an oppertunity for a bigger redesign of the eyebot.

**Comment by Glamurio** [comment]
Yeah, I agree. The visual changes are barely noticeable, I think an entire redesign may be better.

**Comment by 444Portal** [comment]
return of screenhead eyebots??

**Review by flrsh — APPROVED** [review]
The touchups seem fine to me, though I also agree with Gannets and would support a general redesign as long as the floaty drone aspects remained.

**Comment by ZeWaka** [comment]
sure

**Pull request merged**
