### PR TITLE
Adds the Diner Waitress's Dress in two colors, a matching hat, and four colors of Mary Jane shoes

### PR DESCRIPTION
**Pull request by jan-antilles**
[sprites][clothes]

## About the PR 
This PR adds some cute new clothing based on the look of a waitress at a 1950s-style diner. It's a fun retro look! These new items spawn in the Formalwear Closet, the Clothing Booth, and (thanks to @DimWhat !) the Space/Sea Diner!

The first thing is new formalwear dress, the Diner Waitress's Dress, in both Pink and Mint. This was initially based on the sprite for the Maid Dress, and inherited its price and placement in the Formal section of the Clothing Booth as well.

This also includes a matching hat, the Waitress's Hat! It is plain white and black, so it matches not only the diner dresses but other outfits as well. 

Finally, this adds Mary Jane shoes in four colors: Black, White, Navy, and Brown. These all spawn in the Clothing Booth and have the same clicky footstep sounds as the high heels, but have a dainty unobtrusive look. The black and white colors especially are easy to paint/electroplate to make them match any outfit.

https://cdn.discordapp.com/attachments/585526776550391819/846584433787142164/unknown.png

## Why's this needed? 
Cute clothes are fun and add more customization to our silly spacepeople. 

## Changelog

```changelog
(u)Jan.antilles
(+)Added a new Diner Waitress's Dress in two colors, a matching hat, and four colors of Mary Jane shoes. Look for the new dress and hat in the Formalwear Closet, the Clothing Booth, and of course... the Diner!

### CODE REVIEW

**Comment by nefarious6th** [comment]
👀 wiki?

**Comment by Gannets** [comment]
These look really nice! Fix up your conflict and we'll get these in.

**Review by flrsh — CHANGES_REQUESTED** [review]
I don't think retro diner dresses match the sketchy vibe of the space diner or really count as formalwear. Could you include them just in the booth? You could also add an "alternative" diner prefab (nicer floors, working coffee machines, rollerskates?) and include them there, but that'd probably be another PR if you were up for it.

**Comment by jan-antilles** [comment]
Working on fixing the merge conflict and the spawns! I think I'll move the dress to the Costume section of the clothing booth. 

My original intent for the color was a nearly-black charcoal gray, but what do you think of this instead, @flrsh? All I did was move all the dark colors up a shade in the palette. 

image

**Comment by flrsh** [comment]
That looks nice! Maybe apply the lighter shade on the bottom of the apron on the north facing sprite also to the east and west facing sprites?

**Comment by jan-antilles** [comment]
Updated to reflect all of Flourish's suggestions!

The diner prefab will be a separate PR. :)

**Review by flrsh — APPROVED** [review]

**Pull request merged**
