### PR TITLE
Add accessibility options for colorblindness

### PR DESCRIPTION
**Pull request by FlameArrow57**
[UI][QoL]

## About the PR 
Adds accessibility options for protanopia, deuteranopia, and tritanopia colorblindness, which works by applying a view tint for the user

Uses color matrix values from https://github.com/ParadiseSS13/Paradise/pull/17933 (not sure if i needed to ask for permission to use them?)

image

Protanopia - 
image

Deuteranopia - 
image

Tritanopia - 
image

## Why's this needed? 
QoL (also I have no experience with colorblindness, so this is really up to those with colorblindness to say how helpful it is. assumed it was helpful per the paradise station PR)

## Changelog 

```changelog
(u)FlameArrow57
(*)Added colorblind accessibility options for protanopia, deuteranopia, and tritanopia colorblindness under Game -> Accessibility
```

### CODE REVIEW

**Comment by Carton171** [comment]
I would like to say, as a colourblind person:
Fuck. Yes.

**Comment by Valtsu0** [comment]
As i understand it, Paradise is GPLv3 by d efault and i don't think it is compatible with our license.

You should probably ask the author for permission, even if it is definitely fine

**Comment by Valtsu0** [comment]
Does this work even if view tint is disabled?

**Comment by FlameArrow57** [comment]
> Does this work even if view tint is disabled?

Yeah

**Comment by Kyle2143** [comment]
I feel like it would be more clear to put those three options in a submenu like "accessibility -> colorblindness" or something like that instead of just putting the 3 terms directly under "accessibility"

**Comment by FlameArrow57** [comment]
> I feel like it would be more clear to put those three options in a submenu like "accessibility -> colorblindness" or something like that instead of just putting the 3 terms directly under "accessibility"

Would agree, but that would be a single category under accessibility for the moment, so I went without it. I would think it'd be more preferrable in the future if more categories are added under accessibility?

**Comment by Kyle2143** [comment]
That's a fair point, but I would think it would have to be done at some point though if there are more varied accessibility things we end up adding. I suppose we could leave it until that time.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
