### PR TITLE
adds pens to the general fab

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
[QOL]

## About the PR 
adds pens to the general fab
## Why's this needed? 
Cargo can sell pens and QM players are complaining they can't make pens, also, it is a nice way to get more pens.

### CODE REVIEW

**Comment by penny64** [comment]
There aren't any other office supplies, this sounds a bit too niche when office supplies are readily available all over the station

**Comment by Carbadox** [comment]
There's plenty of grey officer stationery lockers all over the station, you can grab on there. They're not really in high demand anyways. Putting it in the general fabricator doesnt make any sense anyways

**Comment by Momoberry** [comment]
I think it's fine and it makes sense that a basic writing tool is in a general manufacturer, at the very least it makes more sense than fully fueled welders, extinguishers and tools in a general fab and not having an engineering fab instead. I'm kind of tired of cargo having literally one-two meta ways to make money, so having less restriction and more ways would be nice, cause we actually have to rush on classic since the rounds are average 45 minutes in length and we only get 4-5 market shifts total?? 

Especially since the wire fix gutted cargos best way to make money recently by fixing the mats gotten from wire reclaiming. Instead of 30 (15 crates, or the value of cargos initial 30k budget) boxes of wires giving 6300 rubber, they give 210, which is a very big nerf even if it wasn't intended to nerf cargo

. (For context, a haggled price of jumpsuits is usually 200ish, and the peak ive ever gotten was like 550 per jumpsuit with perfect haggling and smooth talker. In order to even break even now for buying wires to make jumpsuits, you'd need to have haggled them to at least 430 per jumpsuit, which is like quadruple the initial price and rare to do.)

 The only viable ways of making money now in a timely(ish) manner are cargo holds and spamming food and that's really lame. it's a small change but tbh i wouldnt mind a discussion change for it, i personally requested this so i'll defend it to the death.

**Comment by Tarmunora** [comment]
Gonna go with no on this

**Pull request closed without merging**
