### PR TITLE
Fixes eyewear layering bug on lizards.

### LINKED ISSUE #4563: Lizard head crest layers poorly.
[BUG - Minor]

**Describe the bug**
Lizards have their crest thing on their head overlap all glasses, and specific suits that cover the head.

**To Reproduce**
1. Be a lizard
2. Put on glasses or specific outersuits
3. Be confused as the weird crest thing on your head overlaps them

**Expected behavior**
To have the crest be layered under all of these clothing items.

**Screenshots**
image
image
image

**Additional context**
It is most likely tied to #4540 but is also much more noticable on lizards than humans.

### PR DESCRIPTION
**Pull request by DimWhat**
[Bug - Minor] [Help Wanted]
## About the PR 
Makes the crest layer of lizards to be on a layer much lower than glasses which would fix #4563 that entails lizard crest layers being layered improperly.

**NOTE**: The crest thingy, despite being told to be on the face layer, is still overlapping glasses. This appears to be due to the update_icon setting all "special hair" to be on HAIR_LAYER_2. I am uncertain if I'm capable of fixing this.
## Why's this needed? 
Bugs stink. Especially visual ones.

### CODE REVIEW

**Comment by DimWhat** [comment]
This worked yesterday... well this is gonna be annoying to fix

**Review by flrsh — CHANGES_REQUESTED** [review]
Would be better addressed by changing `special_hair_1_layer` and `special_hair_1_layer_f` on the lizard mutantrace datum to `MOB_FACE_LAYER`.

**Comment by DimWhat** [comment]
By god it would. Thanks flourish I knew there was an easier solution than what I was doing.

**Comment by flrsh** [comment]
Oh wait it may be a detail and not a special_hair. Just compare with the DMI to find what var the crest matches up with.

**Comment by DimWhat** [comment]
> Oh wait it may be a detail and not a special_hair. Just compare with the DMI to find what var the crest matches up with.

That's the tricky thing, What you suggested are the variables the crest matches up with crest but it just doesn't seem to accept any alterations. It's weird.

**Comment by DimWhat** [comment]
Batelite from the gooncord has diagnosed the problem to be in update_icon.dm specifically in line 624 where it automatically sets the layer of all special mutant "hair" to HAIR_LAYER_2. This would mean that cow snouts and squid heads are also set to HAIR_LAYER_2 and suffers the same problems that lizard crests do.

**Comment by DimWhat** [comment]
Further talking with flourish has lead me to believe that the solution would be refactoring the code for update_icon. I do not think I am capable of this.

**Pull request closed without merging**
