### PR TITLE
Adds Lasagna as a new food item and cooking recipe

### PR DESCRIPTION
**Pull request by jan-antilles**
[Feature][Sprites][Add to Wiki]

## About the PR 
Adds Lasagna as a tasty food item and a new recipe for the Chef.

image

To make lasagna, load the oven with a Pasta Sheet, Ketchup, and Cheese, and cook it on High for 8 seconds. It contains 10 units of omnizine, and gives bonuses to max health and stamina, along with healing for brute and burn damage, consistent with spaghetti and meatballs. You need a fork to eat it.

## Why's this needed? 
Lasagna is delicious! 

This also gives another use for the Pasta Sheet ingredient. It's only obtainable by using the rolling pin on Semolina Dough, which requires Semolina Flour from a mutated variant of wheat grown in Hydroponics. This gives the Chef another reason to coordinate with Botanists to make food that you can't get without inter-departmental cooperation.

## Changelog

```changelog
(u)Jan.antilles
(+)Added Lasagna as a tasty new food item for the Chef to cook.
```

### CODE REVIEW

**Comment by virvatuli-gh** [comment]
lasaga

**Review by ZeWaka — APPROVED** [review]
lasag

**Comment by Carbadox** [comment]
For something that gives omnizine, I think it'd be good if the recipe also required meat paste so that it isn't too easy

**Comment by jan-antilles** [comment]
> 
> 
> For something that gives omnizine, I think it'd be good if the recipe also required meat paste so that it isn't too easy

I wouldn't be opposed to it, but it already requires a Botany-exclusive ingredient in the semolina dough, and adding meatpaste wouldn't make the recipe inherently more difficult. Besides, omnizine is already easier to get from Warm Donk Pockets. Its inclusion here is more of a fun bonus and a reference to spaghetti arrabbiata (which contains both omnizine and synaptizine, and which you can make by getting hot sauce from botany or cargo) and spaghetti and meatballs (which you can make with things you dispense from the FoodTech and contains 10u of synaptizine).

**Review by flrsh — APPROVED** [review]

**Comment by nefarious6th** [comment]
Very cute, lovely spritework and good recipe. Looking forward to making this!

**Review by Gannets — APPROVED** [review]

**Comment by DimWhat** [comment]
GAAAAAAAAAAAAAAARRRRRRRFIIIIIIEEEEEEEEEEEEEEEEEEEEEEEEELLLLLLLD!!!!!

**Pull request merged**
