### PR TITLE
Ports the Moth mutantrace to Goonstation

### PR DESCRIPTION
**Pull request by Kapu1178**
[FEATURE]
## About the PR 
Its moth time. Everybody knows April 1st is international moth day. I love moths. You love moths. Varshie loves moths. Everyone loves moth.

This pr adds moths as a mutantrace and a roundstart trait for them.

## Why's this **NOT** needed? 
There is no reason this is not needed. EVERYBODY NEEDS THIS

## Changelog

```changelog
(u)Kapu1178
(*)Ports TGStation moths to Goonstation. Adds roundstart trait.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
möff

**Comment by mathis650** [comment]
möff

**Comment by unfunnyperson** [comment]
möff

**Comment by comradef191** [comment]
möff

**Comment by NotDucc** [comment]
möff time

**Comment by Johann-Strauss** [comment]
I want to be a fluffy moth!

**Comment by millichips** [comment]
Millicent Moffman?

**Comment by Kapu1178** [comment]
mergemyfuckingpr

**Comment by Boxlta** [comment]
speedmerge this

**Comment by mopcat** [comment]
yes...........YES........

**Comment by alexeric123** [comment]
We need this

**Review by ZeWaka — APPROVED** [review]
BIG approve

**Comment by Xkeeper0** [comment]
i would squash and merge, but i do not want to squash moff

**Comment by geneva-breaker** [comment]
ok m gona do iit

**Comment by Kapu1178** [comment]
> 
> 
> ok m gona do iit

mergemyfuckingprdance

**Review by Sovexe — CHANGES_REQUESTED** [review]
Due to licensing and rights issues this would require permission from the original artist to be implemented into our code base

**Comment by Kapu1178** [comment]
> 
> 
> Due to licensing and rights issues this would require permission from the original artist to be implemented into our code base

give me 4 days and a bottle of hard liquor

**Comment by maxymax13** [comment]
ccybsa

**Pull request closed without merging**
