### PR TITLE
ButtScanning and ASS_DAY stuff

### PR DESCRIPTION
**Pull request by TiberianEuan**
[A-Medical] [A-Game-Objects] [Ass Day] [ANGRY]
## About the PR 
- Health scanners now scan the user's buttocks to let them know if they still have one or not
- Zomb**ees** show how ass they act on ass day
- 
## Why's this needed? 
Buttscan - So people can detect if their ass is missing without examining themselves
Angry Zombees - ASS JAM

## Changelog

```changelog
(u)TiberianEuan (ckey: Compu)
(*)Angry Zombees on Ass Day
(*)Buttscanning
```

### CODE REVIEW

**Comment by TiberianEuan** [comment]
im undrafting this when the feature freeze is over and i know that there are no bugs in the code

**Comment by ThatFiveGuys** [comment]
Ass Jam is no longer a thing by the way

**Comment by Wisemonster** [comment]
This pr would probably be better atomized.

**Comment by TiberianEuan** [comment]
sad :(

**Pull request closed without merging**
