### PR TITLE
Burner / damager helpers with just the helper this time

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Adds two new helper objects a turf burner and a turf damager these use `break_tile()` `burn_tile()` and work on a tile as long as its a floor and the `can_break` / `can_burn` variables are `TRUE`.
These have logging for when placed on a tile they can't act on.

 `break_tile()` `burn_tile()` `restore_tile()` moved up to /turf along with related variables.

## Why's this needed? 
image

Map editor view from left to right:
Normal floors, damaged subtypes, floors with burner/damager, varedited floors (broken)

Its impossible to tell which tiles are damaged at a glace if varedited to make it visible the tiles break in the editor and in-game.

The damaged subtypes only look like default floors / plating.

### CODE REVIEW

**Comment by MeggalBozale** [comment]
image
Abstract types are showing up in strongDMM

**Review by MeggalBozale — APPROVED** [review]
LGTM hopefully future PR where the ugly damaged turf subtypes get axed

**Review by frawhst — APPROVED** [review]
Seems good- one concern, does removing the 'broken' and 'burnt' vars mess up the behavior of crowbarring up broken tiles, or is that tracked in some other way?

**Comment by MeggalBozale** [comment]
To address the concern - No, prying up broken tiles works perfectly fine.

**Comment by CheffieGithub** [comment]
Yeah they aren't removed they are just up on turf now

**Pull request merged**
