### PR TITLE
Adds the science alert from #18352 to general PDAs.

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
Atomises the Science alert from the closed #18352 to the crisis alert PDA app.

## Why's this needed? 
Science while not in demand very much right now should have the ability to be called over for things like kudzu and artifacts for now and hopefully more in the future. This PR doesn't have the PDA intermal alerts of the original PR so I assume at least that this addition is fine.

## Changelog 

```changelog
(u)Pgmzeta
(+)Adds a Science alert to the Crisis Alert PDA app.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Why not just PDA message the group

**Comment by cheekybrdy** [comment]
> Why not just PDA message the group

I may be missing something, but isn't the mail group variable doing that here?

**Comment by ZeWaka** [comment]
as in, why can't people just message the mailgroup using the pda functionality
seems fine for
>  things like kudzu and artifacts

**Comment by cheekybrdy** [comment]
oh in that regard the intent was more cultural and more for future proofing science. Being the only department without a alert could be seen as another sign of science lacking responsibility, even though in present there aren't too many reasons for a callout.

**Comment by Glamurio** [comment]
> as in, why can't people just message the mailgroup using the pda functionality seems fine for

Maybe this is just me, but I pretty much ignore mailing via PDA because they just get buried in chat logs, do not stand out and are awkward to use.

I think this is a cool addition in theory, the main issue is actually that Science has little reason to ever leave Science, so there wouldn't ever really be a reason to hit the alert button. It's more of an issue with Science's design than the alert being a bad idea.

**Comment by Tarmunora** [comment]
Science PDA alerts aren't something we need at this time

**Pull request closed without merging**
