### PR TITLE
Requisition adjustment oct23-01 (new pod-based civ requisition + some fixes)

### LINKED ISSUE #16192: Wooden Sheet Requisition Order Doesnt work
### Labels

[BUG][MAJOR]

### Description

I tried to sell Wooden Sheets (yes, wooden sheets not logs) as the order requested and it did not fulfill it

### Steps to reproduce

Obtain wooden sheets
Attempt to fulfill the "New Construction" order for wooden sheets
watch it not fulfill 

### Expected Behavior

I expected the order to be fulfilled and for money to be recieved 

### Additional Information & Screenshots

Reported by: Drasher456
On server: Goonstation 1 Classic: Heisenbee
Active test merges: #15259
Round log date: 2023-10-02-00-46
Reported on: 2023-10-02 01:46:14
Map: COGMAP

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT][FIX]
## About the PR 

Another set of improvements and fixes for requisitions.

- Introduces a new Civilian requisition for a set of pod components. These will most commonly be readily accessible components, but can sometimes require slightly or significantly rarer counterparts, which boosts the payout in kind.
- The Scientific requisition that requires specific seeds has had its rewards altered to be more appealing for botanists; instead of always rewarding a GardenGear refill cartridge and rewarding a strange seed for 3-requirement contracts, it now has a 70% chance to reward a strange seed and a 30% chance to reward a UV lamp frame, with the refill cartridge becoming the 3-requirement reward.
- Fixed the wood sheet requisition to use new material sheets (it was designed when wood sheets were a distinct unstackable item and apparently not fixed since then).
- Wood and rock requirements in requisitions now pay out less outlandish amounts of credits (wood in particular was vastly over-rewarded). As wood can now be purchased from the shipping market, quantities in the associated requisition have been increased tenfold to match.

## Why's this needed? 

Makes requisitions better and adds another variant for variety. Wood change fixes #16192.

## Changelog 

```changelog
(u)Kubius
(+)Introduced an additional new civilian requisition centering around pod components and adjusted the seed requisition item rewards.
```

### CODE REVIEW

**Comment by UrsulaMejor** [comment]
To keep requisitions feeling "strong", the default minimum payout for requisitions is PAY_RELATEDJOB*10; if there is a reason for this to be lower than PAY_TRADESMAN*10, please comment in the code so we know why this was done if we do a rebalance later (i haven't always done this, but since we're adding more requisitions more frequently, I'd like to start)

**Comment by Kubius** [comment]
Thought process was that there are relatively few total components compared to some other counterparts and larger payout would stem from the fancier individual components, but in retrospect I think it's probably sensible to stick with the standard base payout, since there's a fair bit of custom production involved in fulfillment.

**Comment by UrsulaMejor** [comment]
Looks good, will merge as soon as checks pass

**Comment by UrsulaMejor** [comment]
fixes #16217

**Pull request merged**
