### PR TITLE
Upgrade Nadir armory with immersion-ready heavy armor

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT][BALANCE]
## About the PR 

Gives Nadir's armory two sets of acid-tight heavy armor instead of the previously not acid-tight equivalent. Implementational overview:

- Added a new "nt_acid" heavy armor variant, underlaid with a blue Nanotrasen immersion-tight suit. It has an acid survival time of twelve minutes.
- Adjusted the riot helmet; its east and west sprites now have a small "coif" that goes down the neck (suits its BLOCKCHOKE capability), it seals hair, and on Nadir it is now reflavored to a "heavy immersion helmet" that is immersion-tight with an acid survival time of twelve minutes.
- Added these to Nadir's armory, also adapting some layout and contents adjustments previously contained in #11592, rolled into here as part of the overall armory upgrade.

One change I was considering is making the riot helmet count as immersion tight / spacetight globally, but I opted against it for the moment.

## Why's this needed? 

While Security having to choose between armor and immersion-tightness is in general an interesting part of Nadir's security/antagonist interaction, the threat posed by robust and destructive enemies like nuclear operatives demands no compromise between those two.

The new acid-tight heavy armor preserves the considerable slow-down from its ordinary counterpart, which acts as a different avenue of compromise that should hopefully prevent people from busting out the armory gear on the regular.

## Changelog 

```changelog
(u)Kubius
(*)The two sets of heavy armor in Nadir's armory are now immersion-tight.
```

### CODE REVIEW

**Comment by Kubius** [comment]
Do not merge until hat thing stops freaking out and the map diff can render.

**Comment by Kubius** [comment]
Mapdiff now appears correct.

**Comment by flappybatpal** [comment]
I don't think this should use NTSO sprites.

**Comment by Kubius** [comment]
Setting to draft pending a distinct body armor sprite and fixes for other flukes.

**Comment by Kubius** [comment]
Icons are taking longer than expected; closing for the moment.

**Pull request closed without merging**
