### PR TITLE
Turn on Spooktober

### PR DESCRIPTION
**Pull request by Kyle2143**
## About the PR 
Spooktober is back. With all the fun and spookiness of last years spooktober. Some random events, special abilities for ghosts, and more! 
Will be on from October 1st at ~12AM EDT until October 31st at ~11:59PM EDT.

## Why's this needed? 
It turns on spooktober. 

## Changelog

```
(u)Spooktober:
(*)We are officially in the happiest and spookiest of seasons, Spooktober!
```

### CODE REVIEW

**Comment by Kyle2143** [comment]
Don't merge until October 1st at ~12AM EDT. I'll probably be the one to do it, but I thought I'd put this up for fun.

**Review by pali6 — CHANGES_REQUESTED** [review]
This doesn't actually do anything because the actual server overrides __build.dm.
I recommend maybe adding code into _setup.dm and toggling HALLOWEEN automatically based on build date.

**Comment by Kyle2143** [comment]
I am sad.

**Comment by ZeWaka** [comment]
> This doesn't actually do anything because the actual server overrides __build.dm.

I can inject if needed.

**Pull request merged**
