### PR TITLE
Resprites nanite critters

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 
nanites2
Makes nanites easier to see. Also adds a particle effect for fun, though I'm not sure if I added that correctly/if its something that'll cause issues, so PRing for now, aha. Feel free to correct my code if it's incorrectly done. 👍 

## Why's this needed? 
Current nanites are very difficult to see. These look wackier and more fun, imo.

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
honestly, not the hugest fan of this resprite- it makes them look more like a cartoony smoke or bubbling effect rather than a bunch of very small robots.

**Comment by Bartimeus973** [comment]
While this is certainly a lot more readable, it looks a bit more like smoke than nanites. I do agree with chamilian that perhaps individual nanites should be bigger instead.

**Comment by WALPVRGIS** [comment]
I'm not really attached to the sprite, but to explain the design direction; it looks like a cloud as nanites are meant to be tiny! Considering that we can inject them as a reagent, and that they act like liquid, a swarm seemed like it would be cloud or dust-like to me. Them being big visible chunks defeats the purpose of what they are imo.

(But saying that I PR'd this for feedback in general, so if folks aren't sold on them, I'm not gonna merge it, aha. I have a potential other use for the sprite, hmm.)

**Comment by WALPVRGIS** [comment]
I'm actually going to steal my own sprite for a different project it's more suited for 👁️

**Pull request closed without merging**
