### PR TITLE
Human Resprite: Pathology gear, janitor cap

### PR DESCRIPTION
**Pull request by Flaborized**
## j 

Pathologist jumpsuit and labcoat(s) by me, janitor cap by Matheus. Made to fit the base of [human resprite] . keeps the branch updated with master

### CODE REVIEW

**Comment by BatElite** [comment]
yay peach

**Comment by zjdtmkhzt** [comment]
image

I would prefer the view from the back to be a little less narrow, personally.
But my opinion doesn't count for much, since I just made the job, not the sprites, so feel free to ignore!

**Comment by Flaborized** [comment]
Made the shading a bit... less. It was made to mimic the way new labcoats are originally but this should ideally make it look less Thin

**Comment by mordent-goonstation** [comment]
I'm personally not a fan of the lab coat shape from the back (so I expect this applies to the other labcoats), as it looks like a tube that flares out at the bottom. I'm fine with this being merged (some human-respriter-person tell me to do so) for the sake of project completion, but think labcoats from the back could use another pass.

A quick Google of lab coat images showed even the long ones barely get to the knee of the wearer, this looks to be ankle/mid-shin.

**Comment by Flaborized** [comment]
Shortened it a bit and tweaked it more, though considering the original one is pretty long I don't really wanna shorten it any more to not lose the Identity of 'long labcoat item' even if real labcoats don't actually go down to ankles/mid-shin

**Review by ZeWaka — APPROVED** [review]
Much better

**Pull request merged**
