### PR TITLE
Adds new ghost critter Spacebux purchase (small birbs)

### PR DESCRIPTION
**Pull request by WALPVRGIS**
[WIKI] [SPRITES] [FEATURE]

## About the PR 
This adds two new ghost critters (technically one is just a variation on the other), sparrows and robins. They're available as a spacebux purchase (just like the boogiebot/figurine purchase) for 1000 sb. They're also both colour-keyed so they'll use your character's colours, yay! 

sparrow
birbs

## Why's this needed? 
More options are fun, and I always wanted a bird ghost critter. 🐦 

## Changelog

```changelog
(u)Walpvrgis
(*)Added a new spacebux ghost critter purchase; Lil Bird Ghost Critter. It costs 1000 spacebux and lets you play as a little sparrow or robin if you decide to respawn after tiring of the afterlife!
```

### CODE REVIEW

**Comment by Flaborized** [comment]
sprites look very nice though this appears to be using a version of critters.dmi before PR #5846 and thus reverts the change that one made

**Comment by WALPVRGIS** [comment]
> 
> 
> sprites look very nice though this appears to be using a version of critters.dmi before PR #5846 and thus reverts the change that one made

Oh dangit, not sure how that happened. Lemme fix that up. 👍

**Comment by flrsh** [comment]
These are very cute sprites! Can you add sparrows as a spacebux option though? They're kinda too cool to be with the mice and roaches (sorry mice and roaches).

**Comment by WALPVRGIS** [comment]
> 
> 
> These are very cute sprites! Can you add sparrows as a spacebux option though? They're kinda too cool to be with the mice and roaches (sorry mice and roaches).

Ooh, that's a great idea actually. I'm down to do this. :)

**Review by Gannets — APPROVED** [review]

**Review by flrsh — APPROVED** [review]

**Pull request merged**
