### PR TITLE
adds some transparent glass floor sprites

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 
Requested for mapping. These show space objects through them (planets etc) but not stars (probably not sand either?). Would be cool to have space tiles visible through these but idk how to do that. 😹 
image

## Why's this needed? 
Fun stuff for mappers!
(Also I said I would make these for #11401)

### CODE REVIEW

**Comment by trazodont** [comment]
god bless i was just thinking about how these would be incredible with the planets and stuff now.

**Comment by BatElite** [comment]
Since you can't stack turfs, the only way to get stars or sand under them is to underlay them yourself.

I imagine that if parallax space gets in, this would cease to be an issue.

**Comment by ThatFiveGuys** [comment]
These are lovely, thank you

**Comment by Conchuckter** [comment]
Do these show plating when pried up?

**Comment by WALPVRGIS** [comment]
> Do these show plating when pried up?

Yup, these exist just to be Fun Decor and do not include any new functionality. We can just say that they're actually just screens lol. 😎

**Review by Tarmunora — COMMENTED** [review]
They're a bit visually loud, I feel. Might be nice to have a more visually subdued version? ~~Also a greyscale one for materials~~

**Comment by WALPVRGIS** [comment]
> They're a bit visually loud, I feel. Might be nice to have a more visually subdued version? ~Also a greyscale one for materials~

I can defs add that! these stand out a bit as theyre only intended for Feature Floors and not for large areas, but I'll make a less intense version too 👍 (And also a greyscale one bc thats a fun idea lol)

**Comment by ThatFiveGuys** [comment]
The material should be glass as well (did it on the donut2 pr if you want to take that code).

**Pull request merged**
