### PR TITLE
adds support for round caps, roundcap secass to 30 rounds played

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
Restricts security assistant job to players who don't have enough rounds played to play security officer.

## Why's this needed? 
Secass is for newbees, other admins asked for this.

## Changelog

```changelog
(u)tarmunora
(+)secass can only be played if you have less rounds than the secoff round requirement
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Considering that players can still have over 30 rounds and still need an introduction to security due to not previously playing it, Id much prefer it if it used the amount of security rounds played then the amount of general rounds played. Something like ten security rounds and no more being able to play secass (this should probably come with you being able to play secoff if you exceed the secass security round limit as an additional way to gain access to playing sec off).

**Comment by wolfolotl** [comment]
worried this will lock new players out of having a low-stakes role to learn sec if they spend their first 30 rounds learning a different department (medical, engineering, et cetera) first

**Comment by Merlin1230** [comment]
Isn't rounds played based off ALL rounds, so people that wanna learn sec way later in their playetime won't have access to the role thats made for people that wanna learn sec?

And, isn't the whole reason its named "Security Assistant" was because people wanted to have a less stressful security role (which, I will say is nice to have)?

**Comment by FlameArrow57** [comment]
Though it's pretty much a more relaxed form of security officer, it could make someone who's never played the role never able to play it again, if that's a worry. Also, there's the medal for security assistant, dunno if that should be removed

Alternative could be prioritizing for round start selection for security assistants newer players?

**Comment by Merlin1230** [comment]
> Alternative could be prioritizing for round start selection for security assistants newer players?

You could also just make it a separate role like "Sec Trainee" and lower the slots of sec assistants down (Since I believe the point is to lower how many people are in security)

**Comment by colossusqw** [comment]
Could we get a forum thread on this, please?

**Comment by MitchTheUser** [comment]
I personally believe that this is a terrible change. Imo, Security assistant brings a lot of good interactions to the game by allowing someone to assistant the lesser duties of Security (records, handling, minor issues, tickets, etc...) as well as allowing people to roleplay more than a Officer can since they are often busy with arrests and antagonists. Many people including myself enjoy a low responsibility security role when we don't want to have the full duties of a Officer while still contributing to the station. Preventing people from playing a role because its viewed as a noob job is bad.

**Comment by Connie-Dun** [comment]
I prefer the current duality of security assistants generally being experienced players chilling in a lower-stress, lower-consequence role OR being new players learning the ropes. It's easy to feel like you're being wasteful or a drag to go full officer when you can't commit what you want to it, and security assistant provides a good outlet for that situation.

I am also concerned about how security assistants would be viewed if it were a certain sign of "new player with useful loot here". This change, imo, would hurt the new player experience more than it would help it. The lockoff occurring after a number of rounds overall played just worsens this, as multiple before me here have mentioned.

**Comment by Bartimeus973** [comment]
My opinion in short: This allows newer players to be pretty much guaranteed to get a slot to learn at their own pace. It also allows other players to instantly spot them as a player less acquainted with sec and a good target for teaching and mentoring, and lets antags breathe without having 10 well trained people breathing down their neck at all times. My concerns are similar to thatfiveguy's. If someone played a good while and decides to play security after a long time playing other jobs, they will not have the luxury of trying out secass. Playing secass should be limited after a certain amount of sec rounds and not regular rounds in my opinion.
Additionally, security assistants will likely be seen as "easier targets" by antags from now on, which is something to consider, but who wouldn't expect assistants to fall first in the face of danger?

**Comment by Wisemonster** [comment]
As has been mentioned by others, the idea of restricting security assistant to players learning security is good to prevent experienced security officers/robust players from choosing security assistant as an extra sec slot. However, as was also mentioned, restricting it to overall rounds played rather than security rounds played runs the risk that players that take awhile to decide to learn security not having access to security assistant, defeating the point of the role. It'd be preferable if it checked how many rounds of security where played.

**Comment by MylieDaniels** [comment]
I do know my situation was an outlier, but I played a security assistant as part of an RP arc such that a character could undergo training.  I feel this is not a change in the right direction, or should maybe be limited to the classic servers
.

**Comment by meow-jpeg** [comment]
I understand why this is a suggestion but I can’t see how this benefits long or short term. “Secass is for newbies and admins want it” is a very short and lacking explanation for a change to rp and classic. RP at least it changes types of stories or characters someone can has for…. No reason? 

At least let players know why this wanted.

For me personally it helps with a still security role that is less intense and demanding. In a way it’s more accessible! Especially if you’re still learning controls which can honestly be at any point or number of rounds played. For others, this would be an issue if they’ve played 30 rounds but none of them are security in the first place. Ie. 30 medic rounds will no way prepare you to being an officer. 
giving preference to new players is fine and encouraged.

 I’d much rather see this be a change that reserves a spot or two to new players if not at least give preference to someone with less security assistant shifts than another person.  Taking it away entirely is just a large change that doesn’t need to happen

**Comment by Glamurio** [comment]
This is clearly a controversial change that needs a forum discussion thread.

I'm also very heavily in agreement that there's a plethora of SecOffs that really still need to learn how to play Security, the round requirement should be based on rounds played as Assistant, not literally anything, even worse if this locks you out of Security Assistant altogether. I was glad to have been able to play as an assistant for a while before I dipped my toes into playing as an officer, and I had well over the required rounds required to try officer.

**Comment by frawhst** [comment]
Not gonna bother with a forum thread due to the volume of discussion on here.

I personally don't like this as currently implemented, would rather add support for round locks based on specific roles first and use that, if we decide to go this route at all.

Also minor gripe that it would make the "I Helped!" medal unobtainable to anyone with more than 30 rounds

**Comment by nefarious6th** [comment]
not a fan.
I think there is something at odds here. Administration says to play security relaxed and enjoy time doing it, you dont always have to play at yr highest level, etc. Why force people to do exact opposite and play at higher level? more apathetic/lazy/low-effort sec offs does not seem good, not from a "how are we going to kill antags now?!?!" stance; but because that usually results in animosity between team and player and goofing off as sec off on RP gets you chewed out by HoS pretty fast. short is that there is something culturally not fitting about what goon sec is/strives to be, and what this change does

just remove one slot or extra tokens or something if sheer numbers are problem. would not b sad to see one officer and one assistant slot go on most maps + any bonus tokens in armory.

**Comment by ThatFiveGuys** [comment]
> not a fan. I think there is something at odds here. Administration says to play security relaxed and enjoy time doing it, you dont always have to play at yr highest level, etc. Why force people to do exact opposite and play at higher level? more apathetic/lazy/low-effort sec offs does not seem good, not from a "how are we going to kill antags now?!?!" stance; but because that usually results in animosity between team and player and goofing off as sec off on RP gets you chewed out by HoS pretty fast. short is that there is something culturally not fitting about what goon sec is/strives to be, and what this change does.

As someone who used to play office sec on roleplay before secasses were a thing, im pretty sure that this attitude only exists due to there existence as something all jobs can play, and reverting that will lead to that attitude fading away

**Comment by TDHooligan** [comment]
i think that avoiding SecOff when you want to play unserious sec character isn't an unreasonable line of thought. On RP1 I've had a few rounds where we've had an oppressively strong group of veteran sec assistants, but even moreso I have had rounds where we've only scraped by as all our secasses have been new or wanted to play a role in the petty-crimes division.

there's probably room to make combat less accessible to SecAsses and remove tools that aid their ability to independently hand out the law. IE removing crisis alerts from their PDAs. Maybe even downgrade their headset so they have to tether themself to an officer or an intercom.

**Comment by Vaskritaya** [comment]
Echoing sentiments about people who played more than 30 rounds but who are unfamiliar with security. I personally played on and off for upwards of a year before even considering playing sec due to it feeling personally intimidating. It wasn't until several breaks and the introduction of secass that i felt comfortable selecting that job and actually trying to figure out what the whole sec thing was about.

If this PR was implemented as-is from the beginning of secass' introduction, I probably wouldn't have been willing to try security to begin with.

**Comment by MetricDuck** [comment]
Secass is admittedly power-creep but it makes me wonder about dynamic job cap logic

IE for every secass who joins the with over 30 rounds reduce the secoff slots by 0.5, if sec-off slot can't be reduced further choose a different job

**Pull request closed without merging**
