### PR TITLE
Forbids deep copying mobs via admin buttons

### PR DESCRIPTION
**Pull request by TTerc**
[removal]

## About the PR 

Forbids deep copying mobs via copy paste build mode and "copy here" verb

## Why's this needed? 

Copy pasting mobs is a very reliable way to cause a server crash. It's safer to not have that.

### CODE REVIEW

**Comment by MatheusIsNotAvailable** [comment]
I thought issues only happened if the mob had a client? Why not check for that instead

**Comment by TTerc** [comment]
Tested it, making deep copies of NPC mobs were causing issues on my local server aswell.

**Comment by Sovexe** [comment]
Not a proper fix. Issue with copying mobs only began recently

**Comment by Sovexe** [comment]
Other bugs aside the crash issue has been fixed as of yesterday

**Pull request closed without merging**
