### PR TITLE
New spacelubed floor animation

### PR DESCRIPTION
**Pull request by WALPVRGIS**
[BALANCE] [FEEDBACK] [SPRITES]

## About the PR 
Adds a new animation for lubed floor tiles. This is in response to some discussion when the floor tile resprite went through, and also a previous thread on the forums.

I've modified this quite a bit based on feedback, however there is still a shine animation; this is to give it some visibility over lighter tiles (such as medbay, etc).

lube_v4_01
lube_v4_02
lube_v4_03
lube_v4_04
lube_v4_05

(Keep in mind these gifs aren't perfectly timed, so any stuttering/weird timings is probably just where the gif loops, oops)

## Why's this needed? 
Some players mentioned that lube was hard to see on the new floor tiles, also player feedback in general re: spacelube visibility.

This might not be the right solution to the presented issues [here](https://forum.ss13.co/showthread.php?tid=17421), but I actually started this a couple of weeks ago and figured I'd PR it as an option!

## Changelog

```changelog
(u)Walpvrgis
(+)Replaced the spacelubed floor tile effect with new art; should be easier to see on resprited floors now.
```

### CODE REVIEW

**Comment by WALPVRGIS** [comment]
Current feedback:

- Less opaque
- Slower animation
- And/or keep pulse animation from original sprite

Will work on these tomorrow. 😺

**Comment by ZeWaka** [comment]
yeah the above

**Comment by WALPVRGIS** [comment]
Updated gifs above with new changes. Lemme know what you think!

**Comment by BatElite** [comment]
wow icon diff bot really shat the bed on that one

Aside from the white floors that looks pretty clear, I just feel like the sheen pops in rather suddenly.

Second, if you have the non-sheen phase of the loop fade in a bit stronger than the sheen one maybe that'd make it stand out on light floors

**Comment by Azrun** [comment]
Might consider using additive coloration to provide more consistent color shift regardless of original color.
```
var/image/wet = image('icons/effects/water.dmi',"wet_floor")
wet.blend_mode = BLEND_ADD
wet.alpha = 100
```
Using additive coloration could provide more consistent color shift regardless of original color.
FloorLube01
FloorLube02
Left is additive blending with alpha of 100.
Right is additive blending.

**Comment by WALPVRGIS** [comment]
> 
> 
> Might consider using additive coloration to provide more consistent color shift regardless of original color.
> 
> ```
> var/image/wet = image('icons/effects/water.dmi',"wet_floor")
> wet.blend_mode = BLEND_ADD
> wet.alpha = 100
> ```
> 
> Using additive coloration could provide more consistent color shift regardless of original color. 

This is perfect, thank you so much!! 😸 I'm going to tweak the animation a bit and experiment with adding this effect, I think it solves all of the visibility issues I was struggling with! TwT

**Review by Tarmunora — APPROVED** [review]

**Review by ZeWaka — APPROVED** [review]
note for future cool addition:
for non-'tiled' turfs (should just be an istype), have a generic full tile square wet animation instead of the one with the 4 small tiles

**Comment by WALPVRGIS** [comment]
For sure! Would look much better, I’ll definitely poke around with that
during the feature freeze. 😊👍

**Pull request merged**
