### PR TITLE
Updates Cogmap2 mostly up to window standards

### PR DESCRIPTION
**Pull request by Laboredih123**
## About the PR 
Changes almost all full windows into a wingrille_spawner.
Does not change non-reinforced windows, as they spawn thindows.
Nor does this PR change thindows, as that's for a later time.

## Why's this needed? 
Having maps still not follow standards is bad so why not begin by updating one of the most used.

## Changelog

```changelog
(u)Laboredih123
(*)Changes a majority of windows into wingrilles
```

### CODE REVIEW

**Comment by Laboredih123** [comment]
Hopefully I didn't miss anything this time

**Review by TTerc — CHANGES_REQUESTED** [review]
Looks like somehow you removed all the catwalks. Please fix

**Comment by Laboredih123** [comment]
How the fuck

**Comment by Laboredih123** [comment]
Fixed

**Review by TTerc — COMMENTED** [review]
It also looks like you messed with grilles, judging from the map diffs

**Comment by Laboredih123** [comment]
Only the ones that are under windows I believe, if I fixed my error correctly

**Comment by Laboredih123** [comment]
But I probably didn't so I'll ckeck

**Comment by Laboredih123** [comment]
I was correct to check

**Comment by Laboredih123** [comment]
please wait

**Comment by TTerc** [comment]
I still see that things that shouldn't be removed are missing. Please fix it, you can easily see them via map diff bot

**Comment by Laboredih123** [comment]
Can you please tell me what they are, apart from the dirt that SDMM has magically yeeted.

**Comment by Laboredih123** [comment]
Not even copying is making the dirt come back.

**Comment by Laboredih123** [comment]
I'm starting to doubt the reliability of my copy of SDMM 
image

**Comment by Laboredih123** [comment]
I have yet to figure what is causing this

**Comment by Laboredih123** [comment]
Setting to draft until I can find why this happens.

**Comment by Laboredih123** [comment]
This is annoying, I'll just redo this

**Pull request closed without merging**
