### PR TITLE
Bumps Rust-G Dependency Version to 1.0.2

### PR DESCRIPTION
**Pull request by san7890**
## About the PR 

Hey there,

I was bored, and I found out that the rust-g minimum version you had listed was a bit out of date. I added the DM side fix done in https://github.com/tgstation/rust-g/pull/112 (https://github.com/tgstation/rust-g/commit/b6afd895ff0f77d0ae6cdda5bda9689fadd8e002), and this should also have the patch for the Pallette Information https://github.com/tgstation/rust-g/pull/107 (https://github.com/tgstation/rust-g/commit/c19cdfba9f864f1c55808fd9c0ffa3b46bacefa6).

I'm not certain how often you use this stuff over here, but I figured I should be a friendly neighbor and get you guys up-to-speed before something conks out down the line.

## Why's this needed? 

Gets you guys up to speed for patches for bug fixes that completely break some stuff.

## Changelog

I don't believe this is needed since this is purely code-side.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Did you compile the DLL with the listed feature flags? Also, since we run Linux, our host needs to update rust-g manuallyish so a bit of work is required.

**Comment by san7890** [comment]
> Did you compile the DLL with the listed feature flags?

It took a bit of fiddling with several dependencies, but I got it to work. Should now be compiled to the same specs given in the comment.

> Also, since we run Linux, our host needs to update rust-g manuallyish so a bit of work is required.

Is there anything I need to do for this?

**Comment by ZeWaka** [comment]
> > Also, since we run Linux, our host needs to update rust-g manuallyish so a bit of work is required.
> 
> Is there anything I need to do for this?

nope but this could sit here for a long time

**Comment by ZeWaka** [comment]
done on server side

**Pull request merged**
