### PR TITLE
New furniture store prefab, now with swedish meatballs!

### PR DESCRIPTION
**Pull request by SirSnek**
UPDATED VERSION: Walls are now perspective versions, the moth has been replaced, swaped out the thindoors, fixed an issue where i used an airless version of some tiles by accident, both pieces of the purple space suit have been moved to the same rack
and some metal was put onto the other one so it isn't empty
obraz_2021-06-14_151145

[MAPPING] 
## About the PR 

Adds a new prefab in the form of a furniture store (Totally not just space IKEA)

## Why's this needed? 

-We have a lot of neat furniture and the backroom allows for them to be more easily found without needing to go to cargo
-From my understanding the purple spacesuit and construction worker module for cyborgs is unobtainable on space maps, this helps with that

## Changelog

```changelog
(u)Danger Noodles
(+)Adds a prefab which lets you shop in space IKEA today!
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
post pics pl0x

**Comment by DimWhat** [comment]
Not really confident in putting varshie's moth/bee here.

**Comment by SirSnek** [comment]
i wasn't sure but if varshie wants it replaced it's an easy fix

**Comment by Eagletanker** [comment]
Do you have a in game screen shot? A bit worried about the lights being on top of those tables and plants, also, get rid of the thindoors. it’s against the current mapping regulations. Windoors are in prespective and accomplish the same thing, so it will blend better with the perspective walls. I feel the same way about the non prespective doors, but I don’t think that goes against anythingThe Purple Space Suit looks awkward on the  shelf racks imo,  might be better to set them on one rack with a  offset. The wall lights need to be offset on the wall too, but I don’t know if your using the auto ones. It’s good for what I am assuming is your first thing, just check your offsets and post some screenshots and I think it’d be fine imo.

**Comment by Eagletanker** [comment]
Also check to make sure access works

**Comment by nefarious6th** [comment]
Bug tested and QA tested this:

- Lights spawn under the tables okay and give a lot of under floor blue-brightness since it was a little yellow and dark prior to adding those lights
sirsnekprefab2 (w/o under-table lights)
- All access on doors works as intended (Engi doors are meant only for those with access, clarified specifically with Noodle on this because same question)
- Lights are autos and manage the offset
- The RWwalls used on this are the non-perspective debris field ones; most of the prefab turfs and doors are top-down vs. 3/4
- Not sure on people's thoughts about the thindoors aesthetically; I have a similar problem with the railings being non-perspective if everything is made perspective and then putting perspective things like windoors in the middle of them them but fixing sprite problems is obvs out of scope, so I think there's going to just have to be settling on something looking a little silly somewhere, but IDK
sirsnekprefab1

**Review by flrsh — CHANGES_REQUESTED** [review]
The thin windows look out of place. Consider replacing the railings (which, imo, generally don't look good anyways) with full walls or windows.

**Comment by SirSnek** [comment]
I removed both thindoors since they did clash with their surroundings a bit, I also tried replacing the railings with windows but it looked quite odd so i left them alone.

quick fix bathroom
quick fix botanical

**Pull request closed without merging**
