### PR TITLE
Allow rev flash to convert through sunglasses

### PR DESCRIPTION
**Pull request by flappybatpal**
## About the PR 
Allows revolutionary flash to convert (NOT BLIND) through eye protection.
Refactors some of the rev flash code.

## Why's this needed? 
Head revolutionaries would attempt to convert normal crew without being aware of sunglasses or miss them due to gas masks.
I do not feel there is much gameplay reason to almost randomly have crew members who were immune, either due to looting the map glasses or starting with a trinket.
Key jobs are already protected from conversion and are unaffected.

I could not identify any reason for convert(M,user) to exist in the parent level flash_mob().
Took more advantage of calling the flash_mob() parent to handle things instead of doing it elsewhere.

## Changelog 

```changelog
(u)Flappybat
(*)Revolutionary flash can now convert through eye protection. This does not change the blinding behavior.
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
this takes away protection from the captain (who spawns in with sunglasses) though doesn't it

**Comment by flappybatpal** [comment]
> this takes away protection from the captain (who spawns in with sunglasses) though doesn't it

This only changes conversion, it does not change flash protection.

**Comment by RelentlessGarbage** [comment]
We should probably make a forum thread for this one.

**Comment by mc-oofert** [comment]
ided pr

**Comment by CheffieGithub** [comment]
while we're at it can we remove the clown fumble chance from revflash in particular

**Comment by TDHooligan** [comment]
it seems a bit counterintuitive given that the current behaviour consistent with sunglasses blocking flash (and the only way to not be revved without getting an implant). but i've not played rev in a long while.

**Comment by Tarmunora** [comment]
This change would make beating people to de-rev basically always a worse option than spacing them and removing them from the round entirely. Not sure I'm a fan.

**Comment by flappybatpal** [comment]
> This change would make beating people to de-rev basically always a worse option than spacing them and removing them from the round entirely, because if you don't have a loyalty implant for them there's no way to stop a revhead from instantly re-revving them. Not sure I'm a fan.

I don't completely agree because I'm not aware of security really giving out eye protection, other than when they deputize players and give them sec gear. From my experience they usually just rely on loyalty implants. After all there are not many sources of eye protection, like half a dozen on most stations.

Could keep rev immunity on sechuds or just ditch it and keep the refactor of rev flash code.

**Comment by flrsh** [comment]
This feels weird to me because I'd expect sunglasses to block flashes. I'm not necessarily against this if you think we need this balancing (but also why not just output a message like "x is wearing eye protection, remove their sunglasses to convert them"). But I also think if we do this, it'd make sense to have a follow-up where we just change the rev flash to, I dunno, a rev hammer. Or a rev launcher. Or whatever.

**Pull request closed without merging**
