### PR TITLE
Relocate Horizon's Paramedic Suits and Medical Belts

### PR DESCRIPTION
**Pull request by FlameArrow57**
[MAPPING][QOL]

## About the PR 
This PR puts the paramedic suits and medical belts for the medical department on Horizon in an accessible and easy to spot location.

Old:
Paramedic suits (2) and medical belts (3) (deleted) are located in these closets, in the ship behind medical:
image

There is also a belt here (deleted):
image

New:
2 paramedic suits and belts have been put here on a rack, in line with other maps:
image

Also a side note, a medibot previously started there, it was moved to just below the cryo-tube.

## Why's this needed? 
The current locations of the paramedic suits and medical belts are in an obsure location in closets which is unintuitive when all other maps commonly played use racks to hold the paramedic suits and belts, and the locations are hard to find. I haven't seen anyone use a paramedic suit when playing on Horizon, and had to open up the map to find the paramedic suits.

## Changelog
```
(u)FlameArrow57
(+)Horizon's medical department's paramedic suits and medical belts have been relocated to just below the cryo-tubes.
```

### CODE REVIEW

**Comment by FlameArrow57** [comment]
Also, there is a medical belt that starts on the MD's table, which probably isn't needed since the MD has one that spawns in their locker. I didn't delete it though since that wasn't the goal of the PR, but I can if requested.

image

**Comment by Zonespace27** [comment]
Changelog is formatted incorrectly, missing code block formatting indicating a changelog

**Comment by FlameArrow57** [comment]
> Changelog is formatted incorrectly, missing code block formatting indicating a changelog

Fixed

**Review by TTerc — APPROVED** [review]
The changes to xmas horizon are unnecessary, since we don't really use xmas map variants anymore, due to the fact that the decorations are automatically generated but it's whatever :iiam: Looks good 2 me

**Pull request merged**
