### PR TITLE
Botany Request Console

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [FEATURE]
## About the PR
Similarly to the chemical request console: a botany request console.
## Why's this needed?
Allows people (i.e. the kitchen, cargo and the general public) to place orders, ideally facilitating interactions and gives botany a list of things to do if they're bored. Same logic as chem requests. But for botany.
## Changelog
```changelog
(u)Tyrant
(*)The Botany Request Console has been added.
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
image

**Comment by Kubius** [comment]
I'm a little worried about continual "request console creep" taking up more and more map floor space; there are several more departments that could feasibly have an associated request system (mining, robotics and potentially even engineering) and that'd start to get out of hand fairly quickly.

My thought would be a PDA-based system that lets anyone make requests of any mailgroup, with members of that mailgroup able to mark the request fulfilled or denied, and a computer in the HoP's room that tracks request history (as well as potentially a computer in each pertinent department that shows active and past requests to it). This would take care of *every* department at once, with minimal infrastructural requirements.

**Comment by TheTyrant25** [comment]
well, if a mail PDA system is ever added, it could possibly also connect to a single console which replaces both the botany and chemical requesters later on down the line.

**Comment by M-Earthfire** [comment]
Does it add a request console board? (wait, does the chemical request console got one?)

**Comment by Glamurio** [comment]
I'm myself still working on a dispensary interlink between botany and kitchen, I'm almost done with it. This would work well with this change.

> I'm a little worried about continual "request console creep" taking up more and more map floor space; there are several more departments that could feasibly have an associated request system (mining, robotics and potentially even engineering) and that'd start to get out of hand fairly quickly.

There's a fine difference between Science and Botany and their necessity for request consoles. Nothing's wholly dependent Robotics and Mining, however the chef and a large part of the crew simply cannot obtain many of the things that are behind Botany and Science.

Very rarely do you have need of a specific mineral, most of the time you can get the required resources by recycling existing items (fabric, rubber, etc.). Compare that to Botany, where if you want 1 of the 20 different fruits available to make juice, you simply can't unless Botany makes it for you. That's good, because interdepartmental dynamics and such, but Botany is often structured in a way where nobody mans the front desk and it can be really hard to communicate with them.


> My thought would be a PDA-based system that lets anyone make requests of any mailgroup, with members of that mailgroup able to mark the request fulfilled or denied, and a computer in the HoP's room that tracks request history (as well as potentially a computer in each pertinent department that shows active and past requests to it). This would take care of _every_ department at once, with minimal infrastructural requirements.

I will however cede, should such a system be implemented, it may very well be superior. My only concern is that it is difficult for players who don't know. A large majority of players that aren't veterans don't even know you can order cargo via your PDA, hence why we have a "needless" cargo supply console. I don't think of it so much as "feature creep", as much as QoL that makes it easier for anyone to get what they want, and for nobody to be left out.

**Comment by TheTyrant25** [comment]
yeah i cannot be fucked to do ui design nevermind

**Pull request closed without merging**
