### PR TITLE
An assortment of LGBT themed socks

### PR DESCRIPTION
**Pull request by penny64**
[FEATURE] [INPUT WANTED]
## About the PR 

This adds striped socks to the clothing booth in pink and white and LGBT colors.
You can wear them above or below your clothing by pressing C while holding them, and hitting them with a pair of shoes while worn will equip the shoes over the socks!

image
I was told these should look more like :socks: so we'll see about that
image
image

Currently unimplemented
- LGBT Colors
  - Aro
  - Poly
  - Intersex
  - Ace
  - Pan 
  - BI
  - Trans
  - Rainbow
  - NB
  - Lesbian
- Wearing shoes over socks
## Why's this needed? 

LGBT positivity and culture is always a great addition to Goon's culture, and this adds fun colorful customization options that are pretty unique from existing ones!

And a general community positivity to this feature!
## Changelog

```changelog
(u)Penny & Ludolf
(*)Striped socks are now available in the clothing booth, customization yay!
```

### CODE REVIEW

**Comment by penny64** [comment]
[INPUT]

**Comment by penny64** [comment]
[INPUT WANTED]

**Comment by Cboyjet4** [comment]
the coder socks....

**Comment by Kyle2143** [comment]
Yeah, I think the socks sprite should look less like the standard boots sprite. Also, I'm not really sold on a reason to add socks to the game, as a shoe slot item. For one thing they shouldn't really prevent glass shards from stabbing your feet. 

But just in general, socks don't make sense to me as being a distinct article of clothing here.

**Comment by penny64** [comment]
@Kyle2143 

> But just in general, socks don't make sense to me as being a distinct article of clothing here.

There's no depth to this other than adding flavor and a buttload of personality- even in the preview image I get to combine the communist top with LGBT socks, socks are a fashion frontier!

I haven't looked at the mechanical aspects of course I'll iron all of that out, this draft mostly exists at the moment to gague community interest.
Which has been quite positive!

**Comment by Nebulacrity** [comment]
The item sprite makes them look more like boots than socks. I suggest you redo it. (for example, try using an obtuse angle rather than a right angle)

**Comment by penny64** [comment]
@Nebulacrity mentioned in the PR!

**Comment by penny64** [comment]
Outta my drafts bot this is a long project

**Comment by Camryn-Buttes** [comment]
Oi, @penny64, this still an active draft?

**Comment by penny64** [comment]
@Camryn-Buttes it's kinda on hold I'm not sure if it matters if it goes organic

**Pull request closed without merging**
