### PR TITLE
Fish 2 - Koi + Water Edition

### PR DESCRIPTION
**Pull request by Fungal-Infection**
## About the PR 

adds a poorly sprited koi and a fishing spot in the funny workshop

## Why's this needed? 
I Like Fishe

https://github.com/goonstation/goonstation/assets/125216648/680215d2-6584-485b-ac52-24e561e28fe4

Koi
(the bad sprite by the way)

### CODE REVIEW

**Comment by Fungal-Infection** [comment]
fishey

**Comment by CheffieGithub** [comment]
Can you make the title more descriptive?

**Comment by ZeWaka** [comment]
Yeah not a big fan of the sprite. Would definitely be stopping the merge of this in my personal opinion

**Comment by Gannets** [comment]
Hello! I've been updating fishing content under #13460, which i'll reopen once I have all the sprites for. Koi in the dojo was something I'd wanted for that, but I'd really need the sprites to be of the same style and standard as those in my PR to accept this.

**Pull request closed without merging**
