### PR TITLE
Adds spacecillin cure to food poisoning description

### PR DESCRIPTION
**Pull request by Wisemonster**
[QOL] [MEDICAL]

## About the PR 
Adds spacecillin to the list of cures on the medical scanner for food poisoning.

## Why's this needed? 
Considering it is a cure, might as well let people know through the scanner.

### CODE REVIEW

**Review by Tarmunora — CHANGES_REQUESTED** [review]
That's not how this works - that var isn't for description, that's what actually checked by code to see if sleeping etc. should cure the disease [`code/datums/disease.dm:187`](https://github.com/Tarmunora/goonstation/blob/7d59a73235c36a5497d635fc8af07f53eafdcd6e/code/datums/disease.dm#L187)

**Comment by Wisemonster** [comment]
Odd, that appears to be how it works for code\modules\medical\diseases\avian_flu.dm

**Comment by Tarmunora** [comment]
> Odd, that appears to be how it works for `code\modules\medical\diseases\avian_flu.dm`

That one isn't curable by sleep though - current malady behaviour for sleep curing is an exact string comparison on the `cure` var for the string `"Sleep"`, if you have a cure of `"Sleep, foo"`, it will no longer be curable by sleep without also fixing that lmao

**Comment by Wisemonster** [comment]
Buh

**Comment by Wisemonster** [comment]
> That's not how this works - that var isn't for description, that's what actually checked by code to see if sleeping etc. should cure the disease [`code/datums/disease.dm:187`](https://github.com/Tarmunora/goonstation/blob/7d59a73235c36a5497d635fc8af07f53eafdcd6e/code/datums/disease.dm#L187)

What I could do is add a check for "Sleep, foo" on that line, although that seems to be more of a quick fix rather than a proper solution.

**Comment by frawhst** [comment]
(This isn't really your fault, disease cures are awful)

**Comment by Wisemonster** [comment]
Ok, this seems more like something that a refactor is needed for, rather than a simple fix

**Pull request closed without merging**
