### PR TITLE
Clarion2

### PR DESCRIPTION
**Pull request by Cherman0**
## About the PR 

Design doc here: https://hackmd.io/@S5HXVeZISEuSkn6QQVlKVA/Cherman0

WIP image, still lots to do: 
Clarion2WIP

Adds a new map intended as a successor to clarion designed for better space management, modern features, and being prettier in general.

## Why's this needed? 

Clarion2 is a rather old map, and complaints about it feeling cramped even on medium populations are common. This redesign seeks to address those issues as well as make it more intuitive to navigate and nicer looking, while maintaining its niche as a medium population ship map.

## Changelog 

```changelog
(u)Cherman0
(*)Replaces clarion from active rotation with clarion2, a modern take on clarion that fills the same niche of a medium-population ship map.
```

### CODE REVIEW

**Comment by RelentlessGarbage** [comment]
I'd suggest bringing this issue to the forums for greater review.

I'm not too familiar with Clairon, so I can't say I've found anything particularly wrong with it...but in my limited experience with the map, I can say it FEELS cramped. Medbay lobby in particular has gotten awfully messy and sometimes hard-to-navigate, given the glut of people and bodies in it by the time I show up. So I could see the appeal for a slightly larger, but still mid-population, version of the map.

**Comment by nefarious6th** [comment]
I really like clarion, so I say this with a lot of love in my heart but I think this approach and retiring clarion is much better than individually butchering bits and pieces of the map to force it to fit into current goon needs. maps are funny in a way, they can accommodate some changes but are signifiers of their specific time + needs-case. 

I would only caution two things here, stuff learned after redoing destiny: 1. feel free to be unbound by map history or legacy with regards to layout and such. I'd personally rather see a new map than a new clarion, and 2.) be mindful about ship shape on symmetrical and constrained silhouettes since they're harder to modify and adapt down the road

**Comment by wolfolotl** [comment]
something about the arrangement of the departments here rubs me the wrong way. one of the greatest strengths of clarion, at least in my rp-minded opinion, is how front-facing a lot of the departments are. while clarion medbay having more room to breathe is, well, greatly needed, this seems like a pretty big step back for the bridge, research, and security. combined with the lack of distinct character in the halls and maints and the fact that botany is STILL cramped as hell makes me... not exactly fond of this approach

**Comment by Chatauscours** [comment]
I like the idea of remapping Clarion entirely, however, I have a few of things to suggest/comment about:

- 4 turrets in the upload seem way too much to me. Most of the uploads, even on the bigger maps use only 1, maximum 2 turrets.
- I only see 2 docking spaces, meaning there is either the dock for the escape shuttle, the mining shuttle or the traders missing.
- The 5 beds and 5 lockers  in the equipment room in security feel odd. Perhaps the room could be separated into 2 : One part with 3-4 lockers and a couple of tables, and another part with 2-4 beds (perhaps even taking a few tiles from the table room and the hangar).
- I don't think the captain and HoP rooms should turrets outside, as none others get those.
- I'd suggest putting at least 1 space telescope computer inside of mining, as using those outside might mean more oxygen expanses for the miners.
- I would remove the table between brig genpop and sec front office, because Stirstir and brigged monkey players will use it, and it will be tiresome for sec.
- Brig cell release flushers should be orthogonally adjacent to the doors rather than diagonally.

Otherwise, as I and other said, I find this a good idea, that i find to be much better than just remapping small bits of Clarion into what we want it to be. Good luck!

**Comment by Kapu1178** [comment]
No maintenance tunnels running behind/adjacent to any of the departments is going to be a problem

**Pull request closed without merging**
