### PR TITLE
Adds forensic scanners to Sec Tech vendors

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Adds forensic scanners to Sec Tech vendors

## Why's this needed? 
Good to have a consistent location for acquring forensic scanners, regardless of map

## Changelog

```changelog
(u)Carbadox
(+)Added forensic scanners to Sec Tech vendors
```

### CODE REVIEW

**Comment by flrsh** [comment]
I like this change! Maybe consider decreasing the amount to, like, 2 though? Generally there's at least two vendors in security, and more throughout the station.

**Review by flrsh — APPROVED** [review]

**Comment by Tarmunora** [comment]
Hm. Personally I'd rather have forensic scanners be more of a thing for the detective as opposed to sec proper. I kinda like the difference between detective having a dedicated all-in-one tool, and sec asking another officer/det/AI to run a set of prints they picked up with the PDA etc etc

**Comment by Tarmunora** [comment]
possibly superseded by #3413

**Comment by Sord213** [comment]
Got told about this while doing #3413 . I'm personally not against them being in sectech vendors, but I'd rather see them as a utility item that is optional. Detective scanners are pretty strong, what with built in bloodtrak and DNA lookups. It would devalue the scanner if every officer got one as opposed to being a conscious choice to get an extra one, imo. 

I also like the idea of it being in the Sec Equipment Vendor because it allows late join officers to always have the choice of receiving one. We all know how empty vendors can get on busy rounds.

**Pull request closed without merging**
