### PR TITLE
Clone scanning now makes a ping noise

### PR DESCRIPTION
**Pull request by BatElite**
[qol][input]
## About the PR 
This PR makes the cloning computer make a ping noise if it successfully scans someone.
Update: toggling genetic analysis also pings, so that you can pretend to scan someone without raising suspicion.

## Why's this needed? 
Scanning currently has no feedback for the occupant, so people getting scans frequently have to awkwardly wait for the other person to tell them it's done.

### CODE REVIEW

**Comment by DimWhat** [comment]
While I think this would be a nice thing for doctors,I have the issue that it would functionally remove the tactic of faking a clone scan as a traitor.

**Review by mordent-goonstation — APPROVED** [review]
Approving the technical side, happy to have the "fake scan" balance conversation before merging.

**Review by flrsh — APPROVED** [review]
Very nice QoL!

**Comment by BatElite** [comment]
I suggest we have that conversation in the forum thread then.

**Comment by pali6** [comment]
Imo fake scanning is a non-issue. For alive people they already see the split health indicator and for dead people you can just delete the record. Actually you can also do it for alive people too.

**Pull request merged**
