### PR TITLE
Spatial Interdictor (a Thing for Engineers)

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT]
## About the PR 

Adds a new machine called the Spatial Interdictor that is capable of mitigating or stopping certain random events within its range of influence, several blueprints and components used in its construction, and code in aforementioned events to enable interdiction. **Does not introduce the interdictor ingame.**

interdictorshow

Interdictors are not available at round start, and must be constructed manually, requiring the following components:

- An interdictor frame and rod. The manufacturer blueprints for these should be found in Engineering. The rod is the primary resource "gate", requiring both high-conductive and energetic material.
- An interdictor mainboard. Two to three of these should be found in Engineering next to the blueprints and interdictor assembly and use guide. They can be scanned by Mechanics.
- An internal power cell. After the wiring is installed, this cell is not removable.
- Four pieces of wire and a soldering iron.
- Four sheets of metal for casing (currently set up to change the material of the completed interdictor).

The Interdictor has two separate types of power consumption: charging the internal buffer cell, and a baseline cost for sustaining the interdiction field. **These consumptions can and will occur concurrently**. Additionally, the Interdictor **must be installed over an electrical cable** by someone with Engineering access, and **will not interdict unless it is both anchored and has reached full charge while anchored.**

Interdictions I've prepared initially are as follows.

- Biomagnetic fields: Nullified at a moderate cost. Opposite charge interaction consumes twice as much cell power compared to same charge interaction.
- Black hole: Minor mitigation at a very heavy cost (inbuilt cell must have at least ~10k capacity). Feedings are normalized to a slightly lower range, lifespan is increased a bit, and the interdictor makes a large ruckus to let you know what's up.
- Radiation blowout: Nullified at a heavy cost. Each individual within range is protected from radiation, consuming cell charge each time they would be irradiated; having several individuals in radius will cause an interdictor outfitted with a standard high-capacity cell to fail before the blowout is complete.
- Radiation pulses: Nullified at a moderate cost. Tiles affected by the irradiation flash within the interdictor's radius will not irradiate mobs, and will flash a spiffy yellow hue.
- Solar flare: Stacking mitigation at a moderate cost. (Not sure about this one.) Reduces the signal loss rate for each active interdictor, and interdictors will announce a new estimated loss rate once the flare kicks in.
- Spatial tear: Locally mitigated at a heavy cost. Spatial tears created in the radius of an interdictor will become "stabilized spatial tears", which renders them non-opaque and permits crew to push through them at a cost of slight brute damage. See later note.
- Wormholes: Reactively nullified at a low cost. When a wormhole in interdiction range is bumped, the interdictor brings it out of phase with a noise and flash, rendering it no longer navigable. This has been done in a manner that should be friendly to pooling.

A note on the spatial tear behavior: It's a possibility to make the new push-through something that's default to spatial tears at a slightly heavier cost of brute damage, and instead cause the interdictor to nullify that brute damage. Not sure how much I'm a fan of that concept, but I figured I'd raise the possibility.

## Why's this needed? 

Provides an interesting means for engineers to proactively protect the station instead of just starting the engine and then waiting patiently for something to go wrong.

(Changelog absent due to lack of immediate addition to maps.)

### CODE REVIEW

**Comment by virvatuli-gh** [comment]
Neat idea! Not sure on how you plan on playing the interdictor audio but they're very heavy on the lows, but other than that sound really cool. I'd be a little worried about hurting some headphone user's ears who use cheap bass-heavy ones.

**Comment by Kubius** [comment]
Interdictor audio doesn't use full volume ingame; the loudest any of the new effects are set to play at is 40% of regular volume. The files are left at high volume to preserve the sound through compression. I'd be willing to fuss around with equalization now or down the line if it ends up being a definite problem for someone.

**Comment by virvatuli-gh** [comment]
> 
> 
> Interdictor audio doesn't use full volume ingame; the loudest any of the new effects are set to play at is 40% of regular volume (quieter than my last WIP demonstration). The files are left at high volume to preserve the sound through compression. I'd be willing to fuss around with equalization now or down the line if it ends up being a definite problem for someone.

40% sounds good to me, shouldn't be an issue at all at that level. Just wanted to check!

**Comment by ZeWaka** [comment]
What's the point of adding something if it isn't used...

**Comment by Kubius** [comment]
In progress.

**Review by Tarmunora — APPROVED** [review]
pog

**Pull request merged**
