### PR TITLE
Replaces 9mm Frangible Magazines With Plastic Ones, Alongside Stat Changes

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Balance] [Wiki]

## About the PR:
Renames 9mm frangible magazines to 9mm plastic magazines, prevents them from embedding shrapnel, and slightly reduces their kill/stun ratio from 0.9 to 0.75 (each bullet now does 4.5 brute and 1.5 STAM, alongside the slowdown). They also have a new sprite.
9mm_magazine_plastic

## Why's this needed?
Currently as 9mm frangible magazines embed shrapnel, and do brute damage that rapidly stacks up with each bullet, I find them fairly extreme for use as a stun weapon, and thus never use them for that purpose. On the flip side, they are also fairly poor as a method of execution, requiring the raw damage of 20 bullets to place an unarmoured foe into critical, used more as a coup de grâce after several shots from the Signifer.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)NanoTrasen has opted to replace Security's 9mm frangible magazines with plastic ones, following several complaints regarding the use of frangible bullets for less than lethal purposes. Plastic bullets do not embed, and have a lower kill to stun ratio.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
Since they no longer embed, do you think you could delete the old embedded frangible bullet implant sprite and implant? The implant sprite should be in the recycling/junk DMI with the other shrapnel sprites (as silly as that is) and the implant itself, last I remember, isn't anywhere too obtuse.

**Comment by Mister-Moriarty** [comment]
> Since they no longer embed, do you think you could delete the old embedded frangible bullet implant sprite and implant? The implant sprite should be in the recycling/junk DMI with the other shrapnel sprites (as silly as that is) and the implant itself, last I remember, isn't anywhere too obtuse.


Certainly, although frangible bullets used the `"bulletplastic"` implant sprite, located in `icons\obj\scrap.dmi`; I've already deleted the code pertaining to that implant.

**Comment by ThatFiveGuys** [comment]
Removing the shrapnel seems fair regardless, Im pretty sure the heavy smg nukie thing doesnt get schrapnel as well because cutting out 20 rounds isnt fun

**Comment by Mister-Moriarty** [comment]
> This is not warranted, all of this was reworked recently specifically to be this way. They are not supposed to be flat stun rounds. Additionally, the NTSC no longer has a Clock (nor is the ammo available in Secvends anymore), and the use for these rounds will be reworked for whatever the Clock 188 is repurposed to, likely lethals.

While I strongly disagree that these changes were unwarrented, considering that the Clock was removed from NTSCs, that matters little now; these changes were aimed as a rework/sidegrade of the NTSC's 9mm frangible rounds. I'll close this now, but feel free to reuse the `9mm_magazine_plastic` icon for something else.

**Pull request closed without merging**
