### PR TITLE
Changes Audio Log icon_state to be audiolog_newSmall

### PR DESCRIPTION
**Pull request by 444Portal**
[SPRITES] [OBJECTS]
## About the PR 
We had a newer, nicer looking verison of the Audio Log in use in places like the Syndicate Battlecrusier, but, for some reason, it wasn't being used universally, this changes that! Oh, and, it removes the original sprite, as it wouldn't be in use.

## Why's this needed? 
Consistency and improved sprites are a positive.

### CODE REVIEW

**Review by TobleroneSwordfish — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
warning: may break secret

**Comment by 444Portal** [comment]
> warning: may break secret

Oh, sadly that's outside of my control

**Comment by 444Portal** [comment]
Don't merge I forgot lightbreaker (Thanks for pointing that out, Katz!)

**Comment by 444Portal** [comment]
Okay it shooould be fine? I can't test ingame due to a lack of having Windows though.

**Pull request merged**
