### PR TITLE
Cigarettes now produce light when lit

### PR DESCRIPTION
**Pull request by Zonespace27**
[QoL]
## About the PR 
While lit, cigarettes produce a warm glow.

## Why's this needed? 

I think it adds some nice flavor to smoking, also requested by Cal on the forums.

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
I think actual cigarettes don't really provide any noticeable light for surroundings just the glow, similar to how it was proposed borg eyes are done?
Maybe that would make more sense, but maybe this is nice too. It would be easier to judge if you added an image or video? :)

**Comment by Zonespace27** [comment]
image
In full darkness. Might be a bit bright, but will leave that up to feedback.

**Review by pali6 — CHANGES_REQUESTED** [review]
Very strong no on using RL lights for this. Performance of moving with those is bad. Use simple lights instead please. There's a component that handles the picking up part for you too.

**Comment by Zonespace27** [comment]
Had no idea that they were so expensive, updated PR. Will likely PR a change to lighters and matches (who use the system i was formerly using) sometime eventually

**Comment by Kyle2143** [comment]
As stated in the forum thread, giving lit cigarettes such illumination properties doesn't really make sense. 
I think the ideal solution here is to move the "ember" parts of the lit cigarette sprite to the "self illumination" plane so they are bright even in the dark like cyborg eyes.

**Pull request closed without merging**
