### PR TITLE
Replaces manta mining outpost with tunnel snake with modifications

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr reintroduces the tunnel snake, this pr also made some minor alterations to the tunnel snake. The tunnel snake no longer has job spawns on it, due to issues with revs. The tunnel snake no longer has spacemas decorations. The tunnel snake hangar has been expanded slighlty to better accomadate for large pods.

image

## Why's this needed? 
wtf this thing is so cool why did we remove it initially?

## Changelog

```changelog
(u)Ikea
(*)Nanotrasen has decided to reconstruct the Tunnel snake with some design modifications, and has decommissioned the old mining outpost for manta.
```

### CODE REVIEW

**Comment by Sovexe** [comment]
The last time I brought up bringing back the tunnel snake the response from other admins was a hard no

**Comment by ThatFiveGuys** [comment]
> The last time I brought up bringing back the tunnel snake the response from other admins was a hard no

May i ask why so? General opinion ive seen is that people miss it.

**Comment by Sovexe** [comment]
I don't remember all the reasons but I think it came down to its size, bugs, and its destruction being part of the deep lore

**Comment by ThatFiveGuys** [comment]
Size im not too worried about considering massive prefabs like the portagene prefab that are larger exist (there is like 6 unused tiles for this prefab that can be shaved off though). Only bug im aware of with this prefab is miners spawning as revheads, job spawners have been removed so that one should be fixed. Let me fix the lore issue real fast and edit the changelog.

**Comment by ThatFiveGuys** [comment]
Reduced size to 43x13. For a size comparision the largest prefab is Von Ricken, which is 48 x 40, largest ocean prefab by area which is the sea monkey prefab, which has an area of 875 tiles (snake turtle is now only 559)

**Comment by UrsulaMejor** [comment]
Add a rockbox near the cargo pad

**Review by UrsulaMejor — CHANGES_REQUESTED** [review]
Add a rockbox near the cargo pad

**Comment by ThatFiveGuys** [comment]
Done!

**Review by UrsulaMejor — APPROVED** [review]

**Comment by UrsulaMejor** [comment]
arise, tunnel snake. you rule.

**Pull request merged**
