### PR TITLE
Adds french bread... and french toast

### PR DESCRIPTION
**Pull request by tanker4390**
[CATERING] [OBJECTS]

## About the PR 
Baguettes now slice into their own bread slice instead of default bread. This bread can be toasted, or cooked into actual french toast.

Screenshot_20221223_094137

## Why's this needed? 
Makes more sense, expands on the baguette with a new dish on the side.

## Changelog 

```changelog
(u)Tanker
(*)Adds french toast. Simply combine bread, two eggs, and milk in the oven.
(+)Baguettes will now produce french bread slices when sliced.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
the slices of baguette don't seem to be in 3/4 perspective, i think they'd look better if they were

**Comment by tanker4390** [comment]
> the slices of baguette don't seem to be in 3/4 perspective, i think they'd look better if they were

If you look at the bottom, they kind of are; it's just the shape.

**Comment by TobleroneSwordfish** [comment]
So the french toast requires the baguette slice, but looks like normal bread? Would probably make more sense to just let it be made with any bread type anyway since people make french toast out of other bread too.

**Comment by tanker4390** [comment]
It's french bread how I remember it, and a pun; ironic how we went full circle from baguettes slicing into loaf shaped slices to cooking french bread into a loaf shape.

**Comment by ZeWaka** [comment]
> So the french toast requires the baguette slice, but looks like normal bread? Would probably make more sense to just let it be made with any bread type anyway since people make french toast out of other bread too.

yeah this is a bit confusing

**Pull request merged**
