### PR TITLE
 Attempt to merge master into human resprite again, take 2

### PR DESCRIPTION
**Pull request by BatElite**
## About the PR 
This PR should merge master into the HR branch. Resolving the conflicts didn't go entirely smoothly, but the dmi files look fine.

In fun news, I found out the perspective scrub PR renamed a few of the scrub colours. That looks slated to cause problems for maps that spawn with those when we get to merging the resprite into master. Probably not huge problems, but worth keeping in mind.

## Why's this needed? 
The human resprite branch was lagging behind master a bit.

### CODE REVIEW

**Comment by ZeWaka** [comment]
you have compile errors.

**Comment by AffectedArc07** [comment]
Congratulations, you crashed IconDiffBot

**Comment by ZeWaka** [comment]
what does `Resolving the conflicts didn't go entirely smoothly` mean

**Comment by Iamgoofball** [comment]
there is unironically 1000 commits in here
someone who's actually on the repository should be the one catching the HR branch up to master, this cannot be handled through a pull request safely and speedily

**Comment by BatElite** [comment]
Not entirely surprised the bot can't handle 1000+ commits worth of differences tbh

With the "not entirely smoothly" thing, it meant that after the merge I had to go rename some icon states for the cap armour and sec assistant jumpsuit that were along the lines of "[name] CONFLICT [base/left/right]". Like I could pick between the old and perspective ones. None of the other files looked off but I can't really tell what VSC does with dmis. Certainly the cap's armour and sec assistant suits showed up fine in testing afterwards.

You know if this branch ended up fucky (or suspected to be) and isn't suitible anymore I'm fine with just writing it off and letting someone else try. It's more that people kept agreeing it needed doing but nobody did it.

**Comment by ZeWaka** [comment]
yeet

**Pull request closed without merging**
