### PR TITLE
Makes windoors hackable.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Title, windoors now have a panel you can access.

## Why's this needed? 
Manta uses thindoors in its AI upload, and while it does look good it offers an easy way for the AI to shut down upload access without teleportation/going through walls. (wonderful panel open sprites were done by bat)

```changelog
(u)Ikea
(*)New-style windoors are now hackable.
```

### CODE REVIEW

**Comment by penny64** [comment]
These were already network hackable for the record

**Comment by ThatFiveGuys** [comment]
Aware, still should be normal hackable for context of manta AI upload.

**Review by Tarmunora — CHANGES_REQUESTED** [review]
should also change for `/obj/machinery/door/airlock/pyro/glass/windoor/alt`

**Comment by Tarmunora** [comment]
note: this does not change old-style windoors (`/obj/machinery/door/window`)

**Comment by BatElite** [comment]
Will need an open-panel sprite for clarity

**Comment by ThatFiveGuys** [comment]
> Will need an open-panel sprite for clarity

Think an open panel sprite wouldnt look good with current design, these things arent primarily used as main entrance doors. Not to mention dont think itd add too much gameplay wise, you can tell the panel is open by clicking on it.

**Comment by ThatFiveGuys** [comment]
> note: this does not change old-style windoors (`/obj/machinery/door/window`)
Considering those doors cant be bolted (or electrified) dont see a need for that currently. Unsure if you were suggesting I change it but I consider that out of the scope of this pr

**Comment by ThatFiveGuys** [comment]
> should also change for `/obj/machinery/door/airlock/pyro/glass/windoor/alt`

Done!

**Comment by MatheusIsNotAvailable** [comment]
It should definitely have something to visually indicate it's panel is open.

**Comment by ThatFiveGuys** [comment]
> It should definitely have something to visually indicate it's panel is open.
> 
> And I think old style windoors can be bolted by the AI

Tested in case, old style cant be bolted by AI.

**Review by Tarmunora — APPROVED** [review]

**Comment by penny64** [comment]
There needs to be a panel open icon because it's how you tell someone was trying to hack a door

**Review by UrsulaMejor — APPROVED** [review]

**Pull request merged**
