### PR TITLE
Adds more TTV tank sprites.

### PR DESCRIPTION
**Pull request by DimWhat**
[game objects] [sprites]
## About the PR 
Adds a a pair TTV versions of mini oxygen tanks and extended oxygen tanks, renames a few sprites to actuallly work with the current pocket oxygen tank, as well as monkey versions of the empty tank by TealSeer. Also fixes a couple name bugs for chimps that made certain worn air tanks not show up.
image

## Why's this needed? 
It let's cursed TTV set ups be visible to the world also buggy bugs bug me.

### CODE REVIEW

**Review by TealSeer — APPROVED** [review]

**Review by MeggalBozale — CHANGES_REQUESTED** [review]
Backpack sprites are null when only one tank is added. Works fine when two tanks are on though. I LOVE THIS, just please fix the one-tank backpack TTVs.

**Comment by DimWhat** [comment]
> Backpack sprites are null when only one tank is added. Works fine when two tanks are on though. I LOVE THIS, just please fix the one-tank backpack TTVs.
> 
> EDIT: Also if you feel like it, you could resprite the inhand... :O

One-tank TTVs going null seemed to not actually be caused by this PR but a preexisting behaviour.

**Comment by MeggalBozale** [comment]
Should probably still fix that? Either way that's on my todo if you don't end up doing it (that's perfectly fine) which can be made as a separate PR. I think the sprites look great.

**Review by MeggalBozale — APPROVED** [review]

**Comment by MeggalBozale** [comment]
Ok the issue is just that it doesn't update the wear image when removing a tank so

**Comment by MeggalBozale** [comment]
Alright a PR is opened to fix the issue with TTV overlays

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
The back sprites are really indistinct, which is very bad for something like a worn TTV which should stand out like a sore thumb: 
image
Regular TTV for reference: 
image
I think if you want to make the back sprites accurately reflect the tanks then the base sprite needs to be more identifiable, ideally with the big red valve in the middle as shown on the item sprite:
image

**Comment by DimWhat** [comment]
> The back sprites are really indistinct, which is very bad for something like a worn TTV which should stand out like a sore thumb: image Regular TTV for reference: image I think if you want to make the back sprites accurately reflect the tanks then the base sprite needs to be more identifiable, ideally with the big red valve in the middle as shown on the item sprite: image

Yeah the base TTV worn sprite is not ideal. There does seem to be a valve but its at the top of the little black box and also hidden by your hair. (even less ideal) I can try to make the tanks a bit larger, I just took the belt tank's worn sprite and just plopped it onto the TTV when I initially added all those sprites a while back.

**Comment by TobleroneSwordfish** [comment]
Okay for now I've gone ahead and just made the smaller tanks incompatible with TTVs.

**Comment by MeggalBozale** [comment]
Unfortunate. Would this be undone if the resprite is completed?

**Comment by TobleroneSwordfish** [comment]
Maybe if someone can come up with a way of making them easily readable while on your back 👍

**Pull request closed without merging**
