### PR TITLE
Removes the 20% probability for Chefs to have a Swedish accent 

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Removes the 20% chance of the chef starting with the Swedish accent.

## Why's this needed? 
Accents can often be debilitating to social interactions and should be entirely up to the player whether or not they want one. The joke isnt really enough to warrant the inability to communicate normally with everyone.

### CODE REVIEW

**Review by Tarmunora — APPROVED** [review]
contentious, but imo the reasoning is valid. chefs can always just take the trait

**Comment by Emcee-Gore** [comment]
I like the flavor. I disagree with this change.
When I choose Chef it is partly because I like the role and what it offers. I do not think standardizing each little flavor they got and making it all trait dependant would solve anything.
After all there is a trait max-limit and I got it reached at all times.

I would rather see a trait that disables job-specific traits like these.
Spawn in as security without security training.
Spawn in as Captain or Detective without alcohol tolerance.
Spawn in as a Miner that can never be a Dwarf.
Spawn in as a Doctor without medical training.

**Review by flrsh — APPROVED** [review]
Fine by me. Definitely seen numerous chefs mentorhelp and adminhelp about their accent and how to get rid of it.

**Comment by Scaltra-Volpe** [comment]
I think it can give players who don't  know what is going on a lot of grief and doesn't  really effect people who know what is going on and don't  want it. 

I think this would be a great change for reducing grief for newer players which in my opinion is more important then the neat flavor it sometimes adds when people decide not to remove it. I can't  recall if any of the foods give permanent speech modifications but I would prefer giving players the option instead of a randomly assigned default.

**Review by mordent-goonstation — APPROVED** [review]

**Comment by mordent-goonstation** [comment]
My main issue with random Swedishness is that it makes you essentially unintelligible if you pick another accent trait as well, as both are applied (whereas ordinarily you're limited to one roundstart accent).

As long as I can pick it if I want it, this seems fine to me.

**Comment by Gannets** [comment]
I mirror Tarm's sentiment. Why not put the choice in the hands of the player?

**Pull request merged**
