### PR TITLE
resprites of some things in device.dmi

### PR DESCRIPTION
**Pull request by nefarious6th**
[wiki]
## About the PR
resprites some stuff in device.dmi to match other things in there, namely: flashlights, audio recorders and tapes, material analyzer, locator, pbrig remote (new unique sprite), emeter, and holo disguiser
devices

removed all unused old icons (old voltron, old hand tele, old securotron)

## Why's this needed?
just some clean-up work on odds and ends in the dmi idk i was bored.
pbrig remote sprite is unique because i thought it'd be cool if it matched some of the stuff in sec and looked less like the mat analyzer. i guess it's also weird the pbrig remote and syndie teleporter share a sprite.

### CODE REVIEW

**Comment by WALPVRGIS** [comment]
These are lovely! I especially like the changes to the empty recorder strangely, even though it's a subtle change, the shine adds a lot. The material analyzer and the devices around it are awesome too! I have some critique for the torch if you were open to feedback? I think the new shape is a little too organic and not immediately recogniseable as an industrial/heavy duty torch; I'd love to see a version with the more boxy shape, it would show off the newer 3/4 perspective better too imo!

Here's an example of what I mean, and very similar to what the original is based off of, I presume;
heavy-duty-led-lantern

I think the glass in the off-state could use a different reflection, but that's something I could explain in discord as i think i need to make visual reference of how the lighting in a torch lens with the reflections would work (if u were up for me babbling art and lighting theory lol) 💭 

Aside from that these are lovely, and I'm sorry I have to write a wall of text any time concept design and art theory pops up 😿

**Comment by BatElite** [comment]
Not a fan of those flashlights, but the others are good

**Comment by nefarious6th** [comment]
here is another quick doodle i tried while looking at my actual torch irl; it's definitely too small to try and fit the details in and i messed up something with the curve highlight on the bottom, but does the shape seem more of what you were thinking?
flashlights

**Review by ZeWaka — APPROVED** [review]

**Review by flrsh — APPROVED** [review]
Really nice!

**Comment by WALPVRGIS** [comment]
> 
> 
> here are some other quick doodles i tried while looking at my torch irl; i didn't finish the lenses at all, but does the shape of either of these seem more of what you were thinking?

I love the bottom right sprite, definitely looks much improved in the right direction imo! I'd be happy to see it ingame >:3

**Pull request merged**
