### PR TITLE
Capybara

### PR DESCRIPTION
**Pull request by amylizzle**
## About the PR 
Capybara

## Why's this needed? 
Capybara

## Changelog

```changelog
(u)wolfolotl & amylizzle
(+)Added a capybara to the game.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
amy I am begging you please show us the capybara sprites this is highly important

**Comment by amylizzle** [comment]
Note the sprites are entirely wolfolotl's, I just did the basic coding for it
capybara

**Comment by Glamurio** [comment]
Coconut doggy

**Review by TobleroneSwordfish — APPROVED** [review]
Capybara

**Review by pali6 — APPROVED** [review]
yes

**Pull request merged**
