### PR TITLE
only autoclick asteroids if mining tool is available

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
[ENHANCEMENT]
## About the PR 
This changes the effect of bumping into an asteroid tile so it is only automatically clicked if the person is holding a mining tool in their active hand or their active hand is empty and they are wearing concussive gloves or have hulk.
## Why's this needed? 
This prevents accidentally using things like ore satchels or artbeakers on asteroids when bumping into them.

## Changelog

```
(u)zjdtmkhzt:
(+)Only mining tools will now be automatically used when bumping into asteroid tiles. (This prevents things like emptying ore holders on accident.)
(+)Borgs can now also automatically use their mining tools without having to click.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Oh, right, so that is for critters like that, I was wondering why it was using mob!
Also, yee, mining_tool are the default ones and mining_tools are the custom ones. 😄

**Comment by Tiggersaurus** [comment]
Would this allow Borg to do this? Currently we have to spam click manually.

**Comment by zjdtmkhzt** [comment]
This won't allow borgs to do it, I think, since I exclusively add more conditions to trigger the click. I can look into how that would work, though.

**Comment by zjdtmkhzt** [comment]
I tested the borg change and it seems that they can now mine by bumping. 
Bumping into airlocks and moving fuel tanks by bumping into them still seemed to work as well and I had no runtime errors.
Not sure if this change has any other ramifications I am not aware of, please comment!

**Comment by zjdtmkhzt** [comment]
I kind of assumed it's the type of thing that people will notice anyway when mining, but I can add a changelog!

**Pull request merged**
