### PR TITLE
Resprites VR Headsets, Sprite Variants + Other Minor Resprites

### PR DESCRIPTION
**Pull request by MitchTheUser**
[CLOTHING]

## About the PR 

Resprites the Virtual Reality Headset found in multiple places on and off station, and adds new variant sprites for each of the unique headsets.

The Headset has had a complete overhaul, looking less like a weird pair of goggles and more like a combination of a Modern and Retro-Futuristic VR Headset, along with having similar goggles to Visors, and a similar overhead strap to Night vision goggles.

The Standard arcade pair comes in beige/cream, similar to the color of old school Commodore 64 Computers, and the VR Dungeon Pair comes in a vibrant red, as a throwback to the old Virtual Boy Headset. The other pairs have colors related to what department/job/item uses them

VRDisplayBleh
VrHeadsetBeigeVRHeadsetGreyVRHeadsetPurple
VRHeadsetBrownVrHeadsetVRHeadsetCyan

**- Standard (For Arcade headsets)**

**- Detective (For the Detective's private office headset)**

**- Bomb Test (For Science's bomb test headset)**

**- Scuttlebot (For the Scuttlebot remote control headset)**

**- Dungeon Entrance (For the dungeon entrance headset)**

**- Dungeon Exit (For the dungeon exit headset)**

The new VR Headset and it's variants each come with their own snazzy, detailed, and best of all, animated worn sprites. ("Standard" Beige Headset animated for demonstration)

VRHeadsetAnimated

As a bonus, the Blindfold, Superhero Mask and Eyepatch have also received sprite updates, improving shading/shape for the Blindfold/Mask, removing some pixels on the strap of the eyepatch to make it look less blocky and replacing the grayscale color scheme for the Blindfold and Eyepatch with a more vibrant color set. The Blindfold/Mask worn sprites have also been changed to be more accurate/have slightly more detail.

VRDisplayExtra

## Why's this needed? 

Current sprite is not up to Spriting Standards, looking quite messy, using lots of messy grayscale shading and having a slow, jagged animation. The new sprites are a lot more modern and add sprite variants to help distinguish what type of Headset you are seeing/using. Blindfolds, Superhero Masks, and Eyepatches were also in need of improvement, getting rid of dull grayscale coloring and improving design.

## Changelog 

```changelog
(u)Mitch Smith
(+)VR Headsets and other minor eyewear have been resprited, and VR Headsets now have variants!
```

### CODE REVIEW

**Comment by Glamurio** [comment]
Love the new sprites, especially worn. Not too keen on the new muzzle / super hero sprites, the string part looks too thick.

**Comment by Glamurio** [comment]
> > Love the new sprites, especially worn. Not too keen on the new muzzle / super hero sprites, the string part looks too thick.
> 
> Made the strings a little longer and cut out some of the middle pixels to make it hopefully look a little less thick.
> 
> NewMasksDisplay

Not a spriter so don't bend to my every whim, but I suppose I just prefer the squiggly line they used to have before which made the "stringyness" very apparent. Arguably you could also atomize the PR and make a separate one for the blindfolds etc. anyway, because thematically they're not exactly related to VR Headsets.

**Review by TobleroneSwordfish — APPROVED** [review]
Normally I support atomization grumbling but also I really like these sprites sooo

**Review by Sovexe — CHANGES_REQUESTED** [review]
eyes.dmi for monkey and lizards

**Comment by MitchTheUser** [comment]
> eyes.dmi for monkey and lizards

Done. I didn't really change much for the East/West Lizard Worn Sprites. In my opinion, the worn sprite looks fine on the lizard in it's current state, and removing parts of it to not obstruct the snout makes the worn sprite look weird since it's a lot more complex than most eyewear and is hard to read if not covering the snout since you'd have to remove a lot of the sprite.

**Pull request merged**
