### PR TITLE
Reworks oshan ranch

### PR DESCRIPTION
**Pull request by CalliopeSoups**
[A-Mapping]
## About the PR 

Flips and moves the sea elevator to make way for a larger ranch without sacrificing present maintenance. Also the detective gets a comfy chicken viewing seat.

## Why's this needed? 

Oshan ranch can only hold one rancher currently, this also gives them the much asked for ranch closet.

## Changelog 

```changelog
(u)CalliopeSoups
(*)Oshan's ranch has been renovated for cooperative rancher action.
```

### CODE REVIEW

**Comment by CalliopeSoups** [comment]
StrongDMM_PgNsz0JVSQ

Preview image.

**Comment by CheffieGithub** [comment]
the detective now has no locker?

**Comment by CalliopeSoups** [comment]
Could have swore I put that in there. Detective's Office might be a slight squeeze now but I think it looks good to me.

**Comment by BatElite** [comment]
image
It looks like you reverted something with that fishing hole

**Pull request merged**
