### PR TITLE
Adds a fade for the curly bob

### PR DESCRIPTION
**Pull request by klushy225**
[OBJECTS]
(I didn't really know what to label this for the area, so I just chose objects. That is the closest lable I could think of)
## About the PR 

Adds a simple fade for the curly bob that applies well to other hairstyles.
image
image
image
image

## Why's this needed? 

I think the amount of fades available for the shorter hairstyles are quite lacking, so I decided to make one. If people like this one then I'll probably make fades for the rest of the short hairs later on down the line.

## Changelog 

```changelog
(u)Klushy225
(+)Added a fade style for the curly bob
```

### CODE REVIEW

**Comment by klushy225** [comment]
realised I accidentally left the unfinished jelly fade I was making in there- that was not meant to be in the PR, just the curly bob

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Fades should be blocked from random character generation, otherwise looks good 👍

**Comment by klushy225** [comment]
mh I don't like the east facing sprite, I'm redoing it /:

**Review by TobleroneSwordfish — APPROVED** [review]

**Comment by frawhst** [comment]
!merge_upstream

**Pull request merged**
