### PR TITLE
Removes Oshan Pathology

### PR DESCRIPTION
**Pull request by TheTyrant25**
## About the PR 
This is the second time this PR has been posted. This was in order to fix a merge conflict.
This PR moves the test chamber down a bit, and adds a toxins storage room. This makes use of the space vacated by removing pathology.
## Why's this needed?
Pathology is no longer in service
## Changelog
```changelog
(u)Tyrant
(*)Pathology has been removed from Oshan, and has been replaced with a toxins storage room.
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
dunno why the old branch conflicted but i've ported the change to this newer branch

**Comment by flappybatpal** [comment]
IMO lower room should at least have blinds or solid walls to allow it to act as a crime room.

**Comment by TheTyrant25** [comment]
I can do that. I meant it as an observation deck, but the main room can fulfil that purpose too. Doing it now

**Comment by TheTyrant25** [comment]
this merge conflict is pretty much unfixable. I'll redo this another time

**Comment by TheTyrant25** [comment]
okay this might fix the problem

**Comment by TheTyrant25** [comment]
okay so i have some merge conflict objects in the map itself
i'll fix that when i get ahold of a mouse
PROGRESS!

**Comment by TheTyrant25** [comment]
fully ready for review now

**Comment by TheTyrant25** [comment]
you're kidding. Again?

**Pull request merged**
