### PR TITLE
Multi-Pod Cloning!

### PR DESCRIPTION
**Pull request by BenLubar**
[FEATURE][BALANCE]

## About the PR

Allows cloning consoles to connect to up to 3 cloning pods at once.
Cloning pods must be within 4 tiles of the console (same as before).

Gene Power Module, the (currently unused) Mind Wipe Module, and the
genetics setting have been moved from the pod to the console. They were
already added and removed via the console, so this only affects
scenarios where one part of the cloning system is completely destroyed
and needs to be replaced.

Pressing the clone button will use the cloning pod with the highest
amount of stored material, avoiding cloning pods that are currently
working on a clone. (Pods preparing a body are fine, however.) If that
pod is unsuitable for a different reason, tough.

Moves cloning pod status to its own tab of the cloning console UI. The
names of pods can be changed using a hand labeler.

The Syndicate UI theme will be used if *any* of the attached pods have a
mindslave module attached.

## Why's this needed?

I've seen several rounds where a second cloning pod is built, only to leech resources from the reclaimer and never actually activate because the cloning console can only talk to one pod.

## Changelog

```changelog
(u)BenLubar:
(*)Cloning consoles can now communicate with up to 3 total cloning pods.
```

### CODE REVIEW

**Comment by BenLubar** [comment]
Note: I haven't been able to test the actual cloning part since I can't clone NPCs.

**Comment by ZeWaka** [comment]
> Note: I haven't been able to test the actual cloning part since I can't clone NPCs.

then disable that check, or log in to the server twice

**Comment by virvatuli-gh** [comment]
Correct me if I'm wrong, but I thought the cloning console only being able to talk to one pod was an intentional balance thing? Mass producing cloning pods is stupidly easy, having multiple pods effectively takes away the one thing that makes building a cloning system take any effort whatsoever.

**Comment by BenLubar** [comment]
> Correct me if I'm wrong, but I thought the cloning console only being able to talk to one pod was an intentional balance thing? Mass producing cloning pods is stupidly easy, enabling multiple pods effectively takes away the one thing that makes building additional cloning systems take any effort whatsoever.

I'm not absolutely sure, but I think multiple cloning consoles can talk to the same scanner, and one reclaimer can definitely talk to unlimited (well, limited by distance) pods, so the difference between running a 3-pod cloner before versus with this change is that there's less fiddly micromanagement of cloner records. You don't have to put it on a disk and swap to a different console, but as a downside to not having more consoles, you can't easily have multiple copies of the record stored.

This definitely does change balance, but based on what I've seen mechanics do, it seems like a lot of people already think the game works like this. The limit of 3 pods per cloner can also be reduced if needed. (Even with a limit of 1, the changes to which device module data is stored in and the addition of cloning pod labels to the UI might be worth adding.)

**Comment by PrimeNumb** [comment]
What's stopping mechanics from plopping down two extra pods in med every round?

**Comment by BenLubar** [comment]
> What's stopping mechanics from plopping down two extra pods in med every round?

A lot of the time, all that would accomplish is dividing the output from the reclaimer by 3.

**Comment by BatElite** [comment]
You'd be surprised how often mechlab doesn't bother scanning the cloner when that's all they're expected to do in a round, but I do see the concern

It's easy for me suggest things since I'm not coding, but we could do a console board that expands the amount of pods the console can handle (from 1 to 3)
That'd require mechanics to at least go fetch that. :P

**Comment by BenLubar** [comment]
> It's easy for me suggest things since I'm not coding, but we could do a console board that expands the amount of pods the console can handle (from 1 to 3)

Hmm, do I smell a new trader/debris field item?

**Comment by pali6** [comment]
I haven't looked too deeply into this yet but I like the idea of multi-pod cloning. If there's concern for too many pods we can always change mechscanning material requirements to include some rarer material now that we have that technology. Like idk, organic metal with low stability or something, dunno!

**Review by flrsh — CHANGES_REQUESTED** [review]
> I haven't looked too deeply into this yet but I like the idea of multi-pod cloning. If there's concern for too many pods we can always change mechscanning material requirements to include some rarer material now that we have that technology. Like idk, organic metal with low stability or something, dunno!

I would be fine with multi-pod cloning if pods were significantly more difficult to manufacture, like Pali suggests. Otherwise, I also think this makes building cloning systems too easy.

**Review by pali6 — APPROVED** [review]
Code looks ok and overall I like the feature. I think cloning pod build cost can be tweaked later based on how this feature is or isn't used.

**Comment by BenLubar** [comment]
increasing pod manufacture cost, requiring a cloner console module, and adding other drawbacks are all things to look into if this ends up being too strong.

note that having multiple pods and only using one is already a slight drawback as the enzymatic reclaimer splits biomass evenly between all nearby cloning pods regardless of whether they're already full.

**Comment by pali6** [comment]
I'll merge once the conflict is fixed. We can tweak clone pod materials later.

**Pull request merged**
