### PR TITLE
Perspective ID cards

### PR DESCRIPTION
**Pull request by binarysudoku**
## About the PR 

yes this is real no i am not sorry blame whoever it was in discord who said this was a good idea

## Why's this needed? 

consistency + art update

## Changelog

```
(u)Erinexx:
(*)New ID card sprites
```

### CODE REVIEW

**Comment by trerri** [comment]
:sheltersweat:

**Comment by ZeWaka** [comment]
Yeah... I really don't like these. If we were to go with horizontal IDs, I like Cameron's but I still don't like them at all in comparison to the current sprites.

**Comment by UrsulaMejor** [comment]
I like the look of the horizontal IDs; they seem a lot cleaner and like it'll be easier to to make more new fun ID sprites for adventure zones and other random shenanigans.

That said, I do think that they could stand to be a lot bigger; comparable in size to the old ones. IDs are pretty important, so they should be :beesassy: big.

**Comment by MarkNais** [comment]
I'm on the fence. Mostly because I think diagonal sprites could make for a good way for sprites to stand-out, and imply that they go in-hand (like the screwdriver). But these aligned sprites are easier to read and seem to allow more/clear detail.

**Comment by ZeWaka** [comment]
Here are Cameron's sprites, the ones I like more. I do still prefer the current diagonal sprites though tbh, but I wouldn't be /too/ opposed to these:
image
image
square:
image
also smaller version here:
image

link: https://forum.ss13.co/showthread.php?tid=6627&pid=92761#pid92761

**Comment by Flaborized** [comment]
I prefer the diagonal ones greatly, I think that they're much more noticeable when looting people (which is important!) and that the new ones are too small for what they are. I think it'd be difficult to actually accomplish what our current IDs do mechanically without them being diagonal, and I feel that they don't specifically break the aesthetic _super_ badly, so I'm in favor of keeping the current

**Comment by mybluecorners** [comment]
minority opinion here i guess but I like the new ones, they look like tasty little candybars. I would say icon size is important for clickability but thats less of an issue now because rightclick lag is dead.

**Comment by Gannets** [comment]
I like these new cards personally, the colours convey all the required information and nothing is lost compared to the diagonal sprites aside from some surface area for clicking (which could be retained by adding a 1 alpha border around the the cards.)

**Comment by binarysudoku** [comment]
if no-one has any more to add to the discussion i'm likely going to close this PR as it's not likely to reach a conclusion any time soon and I want to tidy up my branches

**Pull request closed without merging**
