### PR TITLE
Pathologist job

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Adds a dedicated pathologist job, with 1 slot for them.
Pathology now has its own dedicated access level.
On maps where pathology is in science, they have scientist level access + pathology.
On maps where pathology is in medbay, they have medical doctor level access + pathology.

Should pathology be disabled, there are instead 0 pathology slots.
Pathology will then need either medbay access, research access, or genetics access (on destiny).

Due to most of the chemistry equipment in cog1 being in pathology, the cog1 pharmacy has been remodeled to actually have chemistry equipment there.
## Why's this needed? 
Having a dedicated Pathologist job will make it easier to assign responsibility if there is a disease on station.
It will also lead to less people rolling Medical Doctor to do pathology and then basically going afk when the equipment is already in use.
Restricting access to pathology will make it so that less random people run through it each round, decreasing both the risk of infection and the general level of annoyedness of the people trying to work there.
## Changelog

```changelog
(u)zjdtmkhzt:
(*)Cog1 now has chemistry equipment in the actual pharmacy.
(+)Added a dedicated Pathologist job. Snazzy clothing sprites made by nefarious6th!
(+)Medical Doctors/Geneticists/Roboticists/Scientists no longer have access to the pathology facilities when Pathology is enabled.
(+)Which it is not.
```

### CODE REVIEW

**Comment by Ley-bunned** [comment]
Is it really hard to do pathology with two people?

**Comment by zjdtmkhzt** [comment]
Most maps do not have two Pathogen Manipulators, so one person would mainly be sitting there twiddling their thumbs.
I think only Kondaru has two right now?

If you want an assistant, you can always just let them in, though. (:

**Review by UrsulaMejor — APPROVED** [review]

**Comment by zjdtmkhzt** [comment]
Going to add the new sprites to this, so please no merge yet.

**Comment by zjdtmkhzt** [comment]
ok, all done!

**Comment by Sovexe** [comment]
I had offered to make a pathologist job but was told not to because people didn't want pathology to became an "every round thing"

I am unsure if these feelings have changed

**Comment by zjdtmkhzt** [comment]
Hmm, I remember that conversation, but I can't seem to find it now.
So I am not sure who said it.

**Comment by zjdtmkhzt** [comment]
If someone feels like merging this, just ping me on discord or something and I'll update the map files, but I won't keep updating them every time they get a change until then, lol.

**Comment by ZeWaka** [comment]
down to merge

**Comment by zjdtmkhzt** [comment]
Alright, I think we're good to go now!

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
