### PR TITLE
New portal sprites.

### PR DESCRIPTION
**Pull request by Nebulacrity**
## About the PR 

Here's how they look:
ss13PortalBlue
ss13PortalOrange

## Why's this needed? 

The old portal sprites look like stretchy pancakes that have been coated in blue/orange paint. The new ones look better.

## Changelog

```
(u)Nebulacrity:
(+)Updated portal sprites.
```

### CODE REVIEW

**Comment by mybluecorners** [comment]
this patch looks good
there is also a 'fatportal' sprite in objects.dmi (used for the pod portals that will damage humans, they need to be visually distinct) 

doesnt need to be changed, but it does follow the old flat pancake style
image

**Comment by Nebulacrity** [comment]
I suppose I'll leave the "fat" portals as is for now. If someone'll want to use & modify my new portal sprites for replacing the "fat" ones, they can feel free to do so at their own accord.

**Comment by ZeWaka** [comment]
Portals should just be all using the new keelin technology where you can actually see through to the other side

**Comment by Nebulacrity** [comment]
Yeah well that also sounds annoying to make.

Plus if someone'll even want to add that in the future, better have fancy borders from these new sprites rather than oval ones.

**Comment by ZeWaka** [comment]
...it literally already exists and you just need to change one proccall to another but ok

**Pull request merged**
