### PR TITLE
Surgery omnitool

### PR DESCRIPTION
**Pull request by Luxizzle**
[INPUT WANTED] [FEATURE] [WIP]

## About the PR 

Adds a new multi/omnitool. The surgery omnitool!

The tool has 4 modes. Scalpel, saw, spoon and scissors. You can switch through these just like any other multi/omnitool.

https://cdn.discordapp.com/attachments/168421568387612672/774365664210976768/ZhGyH8NfYI_Trim-output.mp4

## Why's this needed? 

We have one for the engineering tools, why can't medbay have some fun too?

## Input

I don't really have a place to put these. I thought about making it a medical doctor / director job reward. But it's too much of an upgrade to be a job reward. We could also hide it somewhere in the debris field like the special janitor tools?

## Sprites

Yeah, this thing doesn't look that pretty. The scissors especially.

Uses the same in hand sprites as the normal tools right now.

dreammaker_RnvFl4z0xx

## Changelog

N/A

### CODE REVIEW

**Comment by Gerhazo** [comment]
The omnitool for engineering tools is (as far as I know, maybe something changed) exclusive to cyborgs, to lower the amount of slots occupied since they're not constrained by inventory space in their gameplay and there's no point in splitting it into multiple items.

Perhaps this could serve a similar purpose, but for medical cyborgs?
Albeit perhaps it could benefit from an unique sprite to not be confused and look more medical equipment-esque.
just my personal thoughts

**Comment by Carbadox** [comment]
Sprite could probably be better, thats my biggest grip tbh

**Comment by SimianC** [comment]
Personal opinion, but I think a surgical omnitool would make surgery slower and more difficult since you're cycling through 4 different modes. Most surgeries require only two tools so swapping active hands would be faster. 
Though I suppose that's a trade-off for convenience and maximizing inventory space.
I think removing the spoon mode would make the tool more efficient since it's only used for one specific surgery.
As for a sprite suggestion, maybe a laser surgical tool?

**Comment by Luxizzle** [comment]
Yeah i agree the sprites look awful. Its quickly put together with the original surgery tool sprites and the multitool base. 

Maybe another good place to put this is one of the merchants?

**Comment by Tiggersaurus** [comment]
Personally I have 2 tools in slot 1 and 3 with hemostat in the middle when doing Borg surgery.

**Comment by Luxizzle** [comment]
Closing this for now as my focus is on some other things right now. Feel free to take a shot and/or copy the code if you want.

**Pull request closed without merging**
