### PR TITLE
Updates/Remaps/Adds to Wizard Shuttle

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

Hi this PR remaps and adds some new junk to the wizard shuttle. Here's a bullet point list followed by some pictures:

- The walls are now made of wood. Made to look home-y and low-tech.
- All the lights are a new item, 'magical lanterns.' They're basically anchored warm lights that are animated to look more magical and less light fluorescent light tubes.
- Adds a new purple carpet unique to the wizard shuttle. I just wanted to draw carpet sprites
- Takes all the stuff in the wizard locker and lazily stacked items and tries to present them on racks, ideally making it easier to see what's left and pick out what you want. The contents are the same but more spread out.
- Recolored the magix computer to be purple. Added a '<- TELEPORT' sign next to it. Hopefully both make it stick out far more.
- Gave the medibot a special name (Hippocrates the Cleric) and a wizard hat. He's not a normal robot, he's an aspiring healing mage! Who is a robot.
- Added a persistent noticeboard to the southmost room, along with a fancy pen and a paper bin. Seems like fun, can write little tips or practical jokes.
- Added a phone frame and soldering iron to deploy it. Meant to fix the issue of 'there's always a phone in the wizard den clogging up the call list' while still giving them a phone, if they want to deploy it and use it.
- Added a closet that contains a magic 8 ball, DnD nerd kit and saxophone. Also there's a hidden skeleton with a bong outside in space. Made to facilitate creative gimmicks people might come up with.
- A portrait of a wizard on the wall. Wow

Otherwise I intended to keep things mostly the same. Utensils are still there for self surgery stuff, the harmonica stays as a Black Sabbath song reference. The chili is now oatmeal. The sink is gone because I don't think our wizards would ever wash their hands, they're chaotic like that. The window placement is meant to make every part of the shuttle roughly visible to every other part, so you can see what your fellow wizards are doing. Pictures:

unknown

unknown

unknown

wizard_light

## Why's this needed? 

So almost two years ago I made PR #711 which remapped the wizard shuttle, but I left this fantastic comment:

unknown

I think that my initial PR was bad and didn't really 'get' it. This one aims to update the wizard shuttle while adding new things to it while also trying to make it more wizard-y. Idea is to allow people to do new silly fun things and make it easier to generally easier to setup and figure out what exactly you're on the shuttle to do. Also cute little details and touches. Also a more Current Goon looking presentation (no more thindows).

I also haven't touched mapping myself since I made that PR so I hope this one doesn't suck, I'm learning! Also also I'm aware there's perspective-related z2 PRs happening/there was one so, I hope there's not merge conflicts and stuff. Wizards

## Changelog

```changelog
(u)Flaborized
(*)Updated the wizard shuttle.
```

### CODE REVIEW

**Comment by Eagletanker** [comment]
Why not use the wizard walls?

**Comment by SirSnek** [comment]
I'm pretty indifferent on most of the changes, I really like the lamps, the wizard bot is cute but that pink floor doesn't look very good imo. it clashes with the home-y style you're going for and it pops out a tad too much.

**Comment by Flaborized** [comment]
Didn't use the wizard walls because I think they look bad. 👁️ 

Pink tiles are a holdover from current. People seemed to like them and I want to maintain a purple motif for the main room at least

**Comment by frawhst** [comment]
The removal of the water cooler is slightly significant balance-wise since a Gamer strategy is pouring the tea in the cooler for a larger supply of heals. 
Not really for or against it, just pointing out.

**Comment by Flaborized** [comment]
Makes sense, didn't really wanna change the 'meta' of the shuttle much so readded the water cooler. 
unknown

**Review by Gannets — APPROVED** [review]
This looks so good!

**Pull request merged**
