### PR TITLE
Typecheckless by_type[] & friends

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

Converts all for loops using by_type to be typecheckless for loops, as well as applicable machine_registry cases, and a bunch of other ones

https://hackmd.io/@ZeWaka/gooncode#typecheckless-for-loops - tl;dr: 33-50% speed increase

## Why's this needed? 
server go fast I don't lag so I can actually play.

[chore][perf]

### CODE REVIEW

**Comment by ZeWaka** [comment]
either: add null protection where it's needed, or prevent adding null in the first place

**Comment by pali6** [comment]
Macro for the `by_type` loop maybe?

**Comment by ZeWaka** [comment]
> Macro for the `by_type` loop maybe?

I think that might be neat, this `as()` syntax can't be used until a suite update for spacemandmm because CI linter

**Comment by ZeWaka** [comment]
haha nobody else will review this anways

**Pull request merged**
