### PR TITLE
Assjam: Spatial Disassociator

### PR DESCRIPTION
**Pull request by Kubius**
[ASS-JAM]
## About the PR 

**Ass Jam**

Adds a thingy that creates a "parallel dimension" inside the station, altering a Z2 area to match the region's physical configuration and transporting mobs to it for the duration of the dimension. Mobs retain any position change they make while inside this parallel dimension, making it interesting for circumventing (or getting trapped inside) solid objects.

To support this, the necessary Z2 void zone has been added (this can be relocated at will), sound and icon have been added, and an option to purchase the device has been added to Vurdalak's trade inventory, enabled only during Ass Jam.

## Why's this needed? 

It's a thing that does cool stuff on ass jam

### CODE REVIEW

**Comment by geneva-breaker** [comment]
this sounds bonkers do you have a video?

**Comment by Kubius** [comment]
Yep. Range increased by one after this video, but otherwise accurate to its current state.

https://www.youtube.com/watch?v=dcBYQR_m7L0

**Comment by trerri** [comment]
This seems like bluespace but with extra steps.
Wait no, this looks like moonlol's empowered dimshift but with extra steps.
Jokes aside this is really cool and I love how you got it to work by respecting the station geometry.

**Comment by pali6** [comment]
Hmm, we should / could probably add a new z-level for ass-jam stuff. Or rather take the Urs Dungeon z-level and expand it, then move stuff like this there.

**Comment by pali6** [comment]
Let me know if you'd like to maybe incorporate this into such z-level.

**Comment by Kubius** [comment]
Would be interested in doing such a thing, but not sure about the details of implementation. Probably contact on Discord?

**Comment by pali6** [comment]
Yep. Another alternative is to make an empty z-level and let code allocate and load area into it dynamically as needed.

**Comment by pali6** [comment]
Oh right, some time ago I started working on a map allocator thing. When it's finished I'll let you know.

**Pull request closed without merging**
