### PR TITLE
Adds Blue HoS clothing as a level 2 Job Reward

### PR DESCRIPTION
**Pull request by Zonespace27**
[QoL]
## About the PR 
**First of all, a big thanks to Jan.Antilles for making the sprites!**
This PR adds blue HoS clothes as a level two job reward!
The clothes with a recolor:

- HoS Beret
- HoS Hat
- HoS Jacket
- HoS Jumpsuit
- HoS Suit
- HoS Cape
- Sylvester (when wearing a blue beret!)

image
image
image
image

## Why's this needed? 
Security having blue clothes is a good fashion choice, which this PR helps support. In addition, it helps add more content between the level 1 reward and the (unobtained as of yet) level 5 reward.

## Changelog

```changelog
(u)Jan.Antilles, Zonespace
(*)The Head of Security now has a level 2 job reward, blue clothing!

### CODE REVIEW

**Comment by Flaborized** [comment]
Some issues that I personally(just me) have: I don't really like how this would make it so adding anything new relating to the HoS would require an additional sprite and code to work out the color swaps, the additional work has already been annoying to me when making new stuff for the captain, I think it'd be annoying here. Take even like an existing item like the security backpack, which the HoS spawns with and has red on it. Even if everything that's already red and would mismatch is taken care of, it still adds work down the line for anybody adding HoS/Generalized Security stuff.

Secondarily, I think it muddies the communication of the job, and particularly the HoS beret which is a pretty significant item to be able to immediately spot as it's very good armor and spacewear. To me, the black makes it look like a different item, and I think this hurts the visual clarity of the item. Thinking of the existing blue beret item here, and how it reads as a totally different item. The whole outfit reads as 'NTSO' more than HoS to me, since it pretty much uses the color palette that the NTSO does. Even in the pictures provided, the background tiles themselves are red, and when the colors match, it efficiently visually communicates that this is where the HoS works, since the color of their gear matches the color of the department. Currently it's (almost) a cohesive visual through-line, and this change makes that weaker.

I don't totally hate this though, it does look cool. I could see that being enough for it to be added even with these complaints in mind, and it might indeed be worth it, but I personally feel like the visual clarity of the job is more important, and keeping a clear and consistent color palette that matches existing assets is more important than adding cool looking color swap items.

**Comment by jan-antilles** [comment]
Thank you Zonespace for PRing this!! 

The palette actually does match existing assets. The blue button-down suit is already available in game for the Head of Security, and the matching dress is in game as well, just not obtainable. The colors for the rest of the items were based on the existing palette for that jumpsuit and dress.

Identifiability was actually the reason that the changes to the more visually-dominant outerwear pieces (the jacket and cape) were as light as they are. Both are black/dark gray by default, and only the patches on the jacket and the lining/border of the cape pick up the blue. The beret is the biggest change, just because I wanted it to be distinct from the regular NanoTrasen Beret, but the default hat also has a change only to the band above the brim. My personal feeling is that the most recognizable things about the HoS is the sound of the boots and the silhouette of the cape/jacket, as well as the loud-voiced Lawbringer, but I know others may see that completely differently.

Based on the way that Head of Security XP is calculated, this would currently be a reward available to 26 players, as it requires 100 rounds played as the HoS. I like the idea of having something that's been so commonly requested set to a really high bar, but not as high a bar as the Antique Lawbringer that currently _no one_ has earned. 

As far as raising the barrier to adding additional assets in the future, I think that's a valid concern, but honestly due to the amount of clothing available to Security in general and the HoS in particular, I don't know how much extra clothing and assets are really going to be added going forward. Maybe that's not very forward-thinking of me, but this has been (as far as I have observed) the mostly regularly requested feature for HoS, and I would be very happy to help any future spriting efforts that need to adapt to a blue palette.

**Comment by Zonespace27** [comment]
> Take even like an existing item like the security backpack, which the HoS spawns with and has red on it. Even if everything that's already red and would mismatch is taken care of, it still adds work down the line for anybody adding HoS/Generalized Security stuff.

Quite a few people already play bluesec (alt jumpsuit, NT beret, blue backpack/satchel) and it looks quite good, it's not necessary to make everything added to security blue, but it is certainly nice for color matching and QoL.

Also, the security clothing locker has a pile of clothes that do not match the red coloration of security (police uniform, shitty bill's jumpsuit, and the Hawaiian shirt are three), by this logic, should these be removed?

> Secondarily, I think it muddies the communication of the job, and particularly the HoS beret which is a pretty significant item to be able to immediately spot as it's very good armor and spacewear.

The HoS has a large amount of unique-looking clothes (they have the only dark beret on station, not counting the black one that you see once in a blue moon), such as the cape and jacket, both of which are highly distinctive and are hard to confuse for. Also, they have the stompy boots, which are both visually distinctive AND have a sound that no other boots play. As such, I feel the communication of the job is still fine even with these changes.

>but I personally feel like the visual clarity of the job is more important, and keeping a clear and consistent color palette that matches existing assets is more important than adding cool looking color swap items.

I feel that the alt sec/HoS jumpsuit colors ontop of the NTSO have already made the palette expand into blue, and as such this change would not be incredibly jarring, especially considering that a future PR may add blue options for things like SecHUDs and secpouches.

**Comment by Nihisohel** [comment]
I don't agree with the statement of it muddling the identification of Head of Security.

Reason 1, 
Other heads of staff, most notably the Captain, have many different forms of their own clothing, I fail to see how a simple color shift would change the HoS to look like an NTSO when the Captain themselves have two other unique color palettes which is what this PR is aiming for, a color shift, not a role shift.

Hell, I find the Captains alternate gear to be more troublesome as each color has their own unique corresponding name, 
eg. Centcomm Administrator Jumpsuit versus Captain Jumpsuit

Reason 2, 
Security players as is already switch out their standard equipment for other pieces of clothing found in AND out of security. 
I have always encouraged other sec players and even in my own HoS application to dress to impress. 
Standing out is a good thing, you would want to get the attention of others as a Secoff, not deprive it.

Even if this is an issue, we already have a Unique Security backpack to convey that they are of Security.
Hell, we even have a badge, that badge is used as proof that you are from security.

It would be very contradictory to even keep the costumes locker in security because half of the clothing don't even scream security or is some outdated reference that barely anybody can figure out anymore, 
eg. Hawaiian Suit, Poncho Suit, Flat Cap

Reason 3,
Visual clarity is irrelevant when the specific outfit already screams "important person" and the palette shift is specifically tied to only the Head of Security equipment.

This sums up my first two reasons, the palette shift is already unique themselves, if the Captain gets three unique palettes, then so should the Head of Security. 
Even the Head of Personnel is looking very desolate.

Even if the palette shift muddles with the visual clarity of the Head of Security, the Head of Security is already given plenty of unique items to show that they are special, Heavy boots, Lawbringers, and even their own medal for the rare player that uses it.

This should be in the game, I 100 percent support it.

Please, at least a comment before it closes.

**Pull request closed without merging**
