### PR TITLE
More Food Resprites: meatloaf, fish fingers, icing tube

### PR DESCRIPTION
**Pull request by jan-antilles**
## About the PR 
Resprites a few items in food.dmi, including the awful Meatloaf. (Its jpeg soul still exists in food_shitty.dmi, don't worry.)

image

## Why's this needed? 
Icing tubes were nigh impossible to click on, fish fingers were old and out of perspective, and meatloaf was *a shrunken jpg.*

And meatloaf was on the wanted resprite list, yay.

### CODE REVIEW

**Comment by nefarious6th** [comment]
Very cute, meatloaf looks delicious and especially good

**Review by ZeWaka — COMMENTED** [review]
better than before!

**Review by ZeWaka — APPROVED** [review]

**Comment by NightmareChamillian** [comment]
as godawful as the meatloaf sprite was, it has an odd sort of charm. Regardless, glad to have something that respects any sense of artstyle.

**Comment by CaioFrancisco** [comment]
i will miss the meatloaf sprite. may the legacy of being the only sprite that was just a photo of it's real life counterpart live on.

**Review by WALPVRGIS — APPROVED** [review]

**Pull request merged**
