### PR TITLE
Adds a new snack to the vending machines: Carapace Cream

### PR DESCRIPTION
**Pull request by DisturbHerb**
## About the PR 
Carapace Cream is a frozen dairy product made with real roach pieces. It contains 30u of hemolymph and is functionally identical to frozen yoghurt in all other respects. It can be bought from snack vending machines.

image

## Why's this needed? 
i like snowpiercer, i like ethically and morally dubious foods in the context of space station 13

### CODE REVIEW

**Comment by DisturbHerb** [comment]
After some careful deliberation and a much-needed sanity check, this product will no longer be stated as being comprised of sapient roaches or executed political prisoners.

**Comment by flappybatpal** [comment]
The line of "What is too far?" is a little hard to define in a world where the chef chops up monkeys and humans as a regular thing but having a vended ice cream made out of roaches crosses the line IMO. Player driven weird/gross food is different to "official" and presumably lore approved packaged food

**Comment by NightmareChamillian** [comment]
honestly I like the fact that it could easily be made with bug cockroaches or normal cockroaches. Up to player interpretation.

**Comment by WALPVRGIS** [comment]
Hmm this is probably out of scope, but I think I'd be more inclined to merge this if it was just one out or a set of several random and odd flavours, kinda like grones soda. Then the random weirdness of having icecream made of insects is just like rng being merciless lmao.

**Comment by DisturbHerb** [comment]
Think about the rabbits, Lennie.

**Pull request closed without merging**
