### PR TITLE
Adds A Chance for Wraith On Spy-Thieves

### PR DESCRIPTION
**Pull request by Wisemonster**
[GAMEMODE] [FEATURE] [INPUT WANTED]

## About the PR 
This pr adds a chance (10%) for a wraith to spawn on the spy-thieves game mode if there is at least 3 round-start spies.

## Why's this needed? 
This should increase the chance that players get to play wraiths, while also giving sec something to do while the spy-thieves setup.

## Changelog

```changelog
(u)CodeDude
(*)Round-start wraiths can now appear on the spy-thieves game mode if there is at least 3 spies.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
gotta consider how this plays on both server sets, not just classic

busier round + adding another antagonist for a higher antag threshold (?) is a strong no.

not sure how I feel about the potential for a roundstart wraith and then potentially later having a major event type wraith too.

**Comment by CaioFrancisco** [comment]
isn't 5 spies a bit excessive at round-start? at maximum 2 would be nice for servers with lower than 80 pop.

**Comment by Wisemonster** [comment]
Wasn't sure how high to set the pop, so I just set it to high just in case. Gonna lower it.

**Comment by Wisemonster** [comment]
> gotta consider how this plays on both server sets, not just classic
> 
> busier round + adding another antagonist for a higher antag threshold (?) is a strong no.
> 
> not sure how I feel about the potential for a roundstart wraith and then potentially later having a major event type wraith too.

Fair enough, I'll make a pr that prevents a wraith from spawning if there's a wraith already alive.

**Comment by Wisemonster** [comment]
> gotta consider how this plays on both server sets, not just classic
> 
> busier round + adding another antagonist for a higher antag threshold (?) is a strong no.

How a wraith is added is that it replaces a current antag (in this case, a spy) with a wraith. I could increase the amount of spies replaced by a single wraith if this is considered too much.
Also, according to this forum post (https://forum.ss13.co/showthread.php?tid=19734), people are interested in having wraith more common on rp.

**Comment by Tarmunora** [comment]
Mm, not huge on this
Wraith has a tendency to dominate (the perception of) a round, and is the kind of thing that risks getting stale if it's not kept pretty rare

**Pull request closed without merging**
