### PR TITLE
Actionbar for eating non-food things

### PR DESCRIPTION
**Pull request by Superlagg**
[FEATURE]
## About the PR 

Adds an actionbar for eating things that aren't explicitly food, such as organs and things made out of flesh.

The action is pretty short, but gets longer if you're trying to eat an organ and/or feed someone else.

Most organs can be bitten multiple times. Each bite damages the organ, typically enough to break it. They'll still give organ points, but now there's a chance that you just don't get any points out of it, based on the point worth of the organ.

Also fixed brains being inedible.

## Why's this needed? 

I only want to eat my own liver if I actually want to.

## Changelog

```
(u)Superlagg:
(+)Added an action bar to eating things that aren't food.
```

### CODE REVIEW

**Comment by BenLubar** [comment]
See also #3382

**Comment by Superlagg** [comment]
> See also #3382

I tried doing something like that, but the end of the Eat proc has a qdel inside a SPAWN_DBG(1 SECOND), which allowed the thing to be eaten again before the thing was deleted. This gets around that a bit more cleanly.

**Comment by BenLubar** [comment]
> 
> 
> > See also #3382
> 
> I tried doing something like that, but the end of the Eat proc has a qdel inside a SPAWN_DBG(1 SECOND), which allowed the thing to be eaten again before the thing was deleted. This gets around that a bit more cleanly.

I meant in the sense that they're both adding action bars to force-feeding things.

**Comment by Superlagg** [comment]
Hey I actually have a better PR that does this, but better and such. I'll close this and open that!

**Pull request closed without merging**
