### PR TITLE
Random Room: 3x5 NT Marching Band Storage (w/ 5x5 Rotated Variant)

### PR DESCRIPTION
**Pull request by DisturbHerb**
## About the PR 
An abandoned storage room full of tacky marching band uniforms, musical instruments, and an ornate baton to twirl around.

image

This PR also adds a 5x3 version, which is just that but rotated.

## Why's this needed? 
random room :)

### CODE REVIEW

**Comment by DisturbHerb** [comment]
here's what the uniform set looks like by the way
image

**Comment by ThatFiveGuys** [comment]
The hat item sprite does seem like double the size it should be, besides that all very lovely work, good job.

**Comment by DisturbHerb** [comment]
> The worn uniform looks great, could you adjust the hat item sprite and make it a bit smaller?

one day. i'll get around to it

**Comment by DisturbHerb** [comment]
!merge_upstream

**Pull request merged**
