### PR TITLE
Emaggable cybereyes

### PR DESCRIPTION
**Pull request by Mobilfan**
[INPUT-WANTED][WIP]
## About the PR 

As the title says, it makes it possible to EMAG cybereyes. 

I implemented this for a few cybereyes already, but I'm not sure about what to do about a few of them. I'm also not sure if the things I implemented are actually good. 
In case someone doesn't want to decipher the code first, I noted the changes below:
- Thermal Eyes: Heats you up slowly
- Nightvision Eyes: Makes you able to see through walls, can't see people though
- Laser Eyes: Makes the laser shot stronger, with random drawbacks (from basically nothing to literally exploding) and can burn out with a 10% chance.
- Spectro Eyes: Makes you absorb 10% of reagents within things you examine
- Camera Eyes: Whenever you slip on a banana peel, a laughtrack will play. 

The eyes I am still missing:
- Polarized Eyes
- Meson Eyes
- SecHUD Eyes
- Ecto Eyes
- ProDoc Eyes
- Basic Cybereye (though I don't think this is needed at all)

## Why's this needed? 

It is already possible to emag almost all of the cyberorgans, except for eyes. I think eyes are epic, so it should be possible to emag them.

## Changelog

```changelog
(u)Mobilfan
(*)Made it possible to emag cybereyes.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
I like the idea, dont like the effects personally. Emagged cyberorgans tend to have stronger benefits with stronger drawbacks. Both the night vision eyes and the laser eyes have way too strong drawbacks to ever be used, and both the polarized and thermal ones are just worse.

**Comment by Mobilfan** [comment]
I agree about the effects being a bit bad. The night vision eyes don't have any drawback at all, so I'm not sure what you mean by the drawback being too large. I could change the laser eyes so the benefit is larger and that they only set you on fire for a bit. Not entirely sure what to do about the polarized eyes, since the flash resistance is already at a maximum. The thermal eyes could maybe be just essentially ecto eyes (since ecto eyes are way harder to obtain).

**Comment by SirSnek** [comment]
Like Five said the drawbacks and benefits aren't very well balanced right now, a couple of them have no use for upgrading yourself but they don't focus on killing/maiming the implantee. 

Polarized - Maybe they could passively reflect and amplify flashes but would break after a couple uses and leave you more vulnerable to disorient based stuns.
Thermal - Give the cloaker overlay to random people. Might be a pain in the butt to code though.
NV - Take high damage in bright areas but get stronger in the dark. How does it work? Ma- Technology.
Laser - An alternative to the current iteration could be a very strong but very unpredictable (multiple richochets, high variance in accuracy, random speed changes) but very powerful laser (decent burn + brute and a short stun).
Camera - Upon implanting the player gets a new ability that makes their eye pop out of their head and start walking like a robotic eyespider. The main drawback is that it is very obvious to anyone that's observant, switching takes a bit of time and if the eye is destroyed you can't get place it in your socket again or get a new eye in that slot.
ProDoc - For the first 7-13 minutes it acts like a normal prodoc eye but after that timer runs out it violently explodes.
Ecto - You gain the ability to harness GHOST MAGIC and live out your evil wizard dreams. Basically you get a slightly modified raise skeleton ability but to be a necromancer you must sacrifice a small amount of your max HP every time you do it.
SecHUD - Give you unarmed combat training that lets you deflect projectiles by blocking csaber style and heavily improves your punch and kick damage but disallows you from using batons, flashes or any form of ranged weapon. So a mix of wrestle belt and csaber that is probably worse in every way but more fun.
Spectro -  Allows the user make an evil clone of themselves that will be passive to their master but doing so will heavily damage the eye and weaken the original (either inject a bunch of chems that slow and weaken or make a new status effect which does just that)
Meson - Opens your third eye (Get it?) and makes a frickton of fake objects and holograms appear near the subject, these holograms are real and will beat the shit out of whoever has it installed but they won't be seen by those that haven't opened their mind. Effect starts to occur 3 minutes after installation and it ramps up over time.
Standard - Modified version of clown disbelief that makes both clowns and assistants invisible to you. If the sechud effect is too much to code this could go in it's place.

**Comment by Mobilfan** [comment]
Those are some amazing ideas, though very ability focussed (then again, you can only get 2 so I think it's fine). I'll have to see how much of it I can actually do my self, as this is my first contribution.

**Comment by coolbugcoder** [comment]
Whilst SirSnek's ideas are great, I love the concept of:

Spectro Eyes: Makes you absorb 10% of reagents within things you examine

a ton, this is a great idea that should be kept IMO.

**Comment by Mobilfan** [comment]
i want to note that i edited the original comment so its up to date to the changes i made. see the old versions of it for how it was bad

**Comment by amylizzle** [comment]
Potential:
Mesons - Give you full X-ray but slowly irradiate you
Ecto - You can't see ghosts, but you can hear them if they're very nearby (ie, on top of or next to you, further away is like overhearing a whisper)
Spectral - Shows you the temperature of the reagents too, but also slightly heats them up.
SecHUD - randomly sets arrest status if you examine someone stood next to you?

**Review by pgmzeta — COMMENTED** [review]
To me, cyberorgans generally live in the higher-risk, higher-reward neighborhood.

You can get powerful abilities you wouldn't otherwise have with emagged organs, but their use often wrecks the organ/yourself.  For passive cyberorgan benefits, once they're too damaged they are hazardous.

Vague suggestions / ideas to play with:

* Use `FAIL_DAMAGE` more for passive-effect style eyes. For example, an emagged mesonic eye that begins to fail could add a color matrix like colorblindness does, making it harder to see
* Thermals could set the upgrade flag on emagging. Maybe apply nearsighteness on failure?
* Spectros could use `PROP_MOB_BLOOD_TRACKING_ALWAYS` (maybe? I should play with that, but i think it's a thematic fit)

For any eye implants that don't have a dedicated emag effect, they should still indicate an action was taken, but it did not do anything. For example: "The implant beeps and flashes... but it doesn't seem to do anything on this model. Huh.".

**Pull request closed without merging**
