### PR TITLE
Patho fix two

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Readds pathogens from poor hygiene, but at 1/4th the rate and always non-contagious.
Makes pathogen-cloud-symptoms trigger less, because I severely underestimated how much stuff would spread.
Also, plasma farts is now a T4 symptom and smoke farts a T3.
Also fixed the incubator sprite because I am bad.
Pathology machines are now scannable.
Also, they now actually stop working when broken or when their power is out.
Putting vials into the manipulator should now automatically update the UI.
An old help message was outdated.
## Why's this needed? 
To make things less terrible.
## Changelog

```
(u)zjdtmkhzt
(*)Pathology fixes: cloud-based pathogens should now spread less and pathogens resulting from poor hygiene are now rarer and always non-contagious.
(+)Plasma farts is now a higher tier symptom, trading places with Smoke farts.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Uh, I have no idea what's up with the linter there?
I'll check it out later.

**Review by flrsh — CHANGES_REQUESTED** [review]
I don't think pathology equipment should be scannable, as this allows you to build a lab in the middle of nowhere and create some deadly pathogen without any oversight. You should be forced to work in either the path lab or the dangerous debris field location.

**Comment by zjdtmkhzt** [comment]
The same is true for pretty much all the other dangerous stuff though, like chemistry?
And setting up a lab takes a lot of time too, and not being able to scan the machinery seems very inconsistent.

Besides, it's not like people are going to check what you are doing in the actual pathology lab.

**Comment by Kapu1178** [comment]
If I may, currently, I do not see the issue with scannable pathology machines on main. Chemistry is equally if not more lethal, and currently, the only successful Tier 5 "rampage" virus took 45 minutes to create in the normal Pathology lab.

**Comment by flrsh** [comment]
> The same is true for pretty much all the other dangerous stuff though, like chemistry?
> And setting up a lab takes a lot of time too, and not being able to scan the machinery seems very inconsistent.
> 
> Besides, it's not like people are going to check what you are doing in the actual pathology lab.
> And you still need to gain access to both scanning stuff and to the pathology lab itself.

I also think chem labs in the middle of nowhere are bad. Maybe make the equipment purchaseable through QM instead of scannable? At least that way there's another layer of people and interaction you have to go through. 

This isn't a thing I'm 100% set on though, so if other devs think it's fine, I'll defer to them. We can always make them unscannable if they prove to be an issue.

**Comment by UrsulaMejor** [comment]
I'm seconding Flourish that pathology stuff shouldn't be scannable

The difference between a chemlab and pathology is like the difference between a chemlab and canbombs.

Chemistry tends to be local, area-affecting, and mostly instantaneous. They can be scanned and hidden, but rarely deployed very far from their targets without significant setup.

Canbombs can totally, irreversibly alter the round. They can only be made in specific places, but can be deployed basically anywhere and affect everyone.

Pathology is more like a canbomb than a chemical mix. You can deploy it quietly and let it spread, and it fundamentally alters the whole round if it's a powerful one. You shouldn't be allowed to make one with a total lack of scrutiny.

**Comment by zjdtmkhzt** [comment]
Alright! Not like it matters much, especially if Pathology access will be restricted to fewer crewmembers in the future.
This was mainly intended for something like rebuilding in case patho gets blown up (which seems to happen a lot in the past few days, lol).

Maybe in the future we could make all the stuff that is not the Pathogen Manipulator scannable, since it's not needed for curing and you need it to make plagues.
Alternatively, we could add a QM construction crate that is ID-locked for pathology machines, seeing as those require QM access, head access, and are also prohibitively expensive.

**Pull request merged**
