### PR TITLE
Slamgun available 24/7, modify zipgun

### PR DESCRIPTION
**Pull request by polivilas**
[BALANCE] [ENHANCEMENT]
## About the PR 
Slamgun bugfixes, makes it available 24/7, zipguns can only fire any ammo during assjam, backend work in kinetics to allow easier implementation of slightly-more-advanced kinetic weapons.

## Why's this needed? 
Strongly positive reception to original slamgun concept, kinetics having their long-overdue additions, and more choice to spice up combat.

## Changelog

```
(u)2027:
(+) Zipgun no longer accepts all ammo during non-assday.
(+) Slamgun and nail ammo makes a comeback from ass-jam!
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
I have concerns about the balance of the nail ammo type, especially when you consider that the barman can load it into their riotgun, or hacking into the armory for riotguns. When pointblanking an unarmored target, the nail spreader does 80 damage - more than the SPES-12. I'd want to see this addressed in some manner before merge.
Removing the explosion chance from the zipgun is somewhat concerning, because this further devalues the .22lr that you can get as a traitor, especially considering the ammo is fairly easily printed, taking no special resources. Might be worth seeing how adding a bit of spread to the zipgun feels, but I think that this should also be addressed before merge.

**Comment by polivilas** [comment]
Nail ammo type is very easy to counter - even a basic emergency suit will curb the damage to a hilarious 21.333 brute, moreover, the extreme loudness of ammo should very quickly clue in into what's happening.
A entire box of nailshot to a target equipped with a emergency suit will be 123.333 brute, and that is absolutely laughable compared to egun's 240 burn.

Regarding .22, zipgun has a pretty big downside of fully advertising your name every shot, and more than that, you need to reload every two shots, severely slowing the firerate down.

**Comment by Tarmunora** [comment]
Good points re: zipgun.
I still feel that `D_KINETIC` would be a better choice for the nailgun ammo, as well as making the pointblank the same strength as having all projectiles hit and making it properly cause bleed. (override `on_hit()`, see `bullet.dm` for reference)

**Comment by polivilas** [comment]
Switching it to `D_KINETIC` would bring it too close to just discount-buckshot I feel, while current nailshot has a clear niche where it shines.
Second point, #409

**Comment by Flaborized** [comment]
Nails seem weird to me design-wise. Doing 80 damage at point-blank but only 21 when someone puts on a non-armor item seems a little extreme? It's true that the _crew_ would be quickly clued into an antag killing a bunch of people with it, but I think the far greater use-case is nonantags using it to kill antags. In that case it ranges from horrifyingly effective at deleting antags to pretty awful, with preparation that feels mostly arbitrary on the part of the antag. (get *some* outer suit that protects you and wear it, *just in case* someone slamguns/riotguns you) 

I also think the low ammo capacity and low range but potentially high damage output of the slamgun will lean it into being used as a finisher in fights, after you've already stunned someone. Load up like four of them in your bag and then unload all of them into Whatever Antag when they've slipped or been stunned, and then point-blank them to death.

Specifically nasty for wizards, as wizard robes don't count as armor. Instant brute damage death in five shots, 160 brute in 2. Still appears to be highly lethal at ranges even. Should likely be toned down a little considering they can be so easily accessed by nonantags.

Also it's really loud! when not pointblanking. The point-blank noise seemed fine to me, decently loud considering it's a gun, but still respecting my settings, but the non-point-blank firesound made the audio clip for me when testing. This is Too Loud imo. Sort of weird that the ammo makes different sounds at all, shouldn't they be the same either way? To help with identifying what ammo is being used from a distance.

**Comment by Enfaeutchie** [comment]
What's the reason for the zip gun change? This would remove most of the item's gimmick and features and leave it as a fairly plain improvised gun.

**Comment by polivilas** [comment]
Nails, design wise, are meant to be to be used as hollow points, something that is great for staffie vs staffie combat, yet absolutely horrible when security comes to shut it down.
Secondary priority is to push more combat to kinetics, instead of current 'taser & egun' combat that we have, that is, let's be honest, not fun.

Regarding wizards - Great! There is currently zero impact a crew can do to a wizard without getting a taser or making hellchems, and I'm sure neither of aftermentioned are too fun for either party, and a wizard has plenty of spells to keep such attackers at bay, for example, arse nath, sticks to sneks, etc.

Zipgun change - currently the zipgun is a huge dealbreaker for any easier-access kinetic weapons, namely because any ammo can be used - for example, I have seen .308 AP ammo being speedran from adventure zones and then slammed into zipgun & used from there. Removing such headaches would allow easier kinetic weapon implementations down the line.

**Comment by Flaborized** [comment]
Nails seem to be great against every that _isn't_ sec. I don't see a huge use-case for "staff vs staffie combat" when the far bigger use-case is blasting any antag who's not wearing a spacesuit into 160 damage with two slamguns in your bag. The counterplay for it (wearing a spacesuit) is pretty irrelevant imo, because once you've been hit by more than one (or even just one if you're already weak) nailgun shot, you're already dead. You basically gotta wear one "just in case" at that point. 

I don't feel the crew needs easy access to a type of ammo that does 80 brute damage on point-blank to the majority of antags unless those antags prepare against it specifically. Seems like just pushing for a strong kinetic weapon that anybody could have on them for the sake of it, when I feel that strong kinetics being rarer is part of the draw of them.

**Pull request closed without merging**
