### PR TITLE
Cogmap 1 Armoury changes

### PR DESCRIPTION
**Pull request by comradef191**
[ENHANCEMENT]

## About the PR 
This brings back some items to the Cogmap 1 Armoury people seemed to be complaining about being removed, alongside adding an additional Set of NVGs due to the darkness changes and switching the Anti Biological Crate to not need HoS level access now that its outside the Armoury.

## Why's this needed? 
The Armoury had several things needlessly removed during its last update, this brings some of those items back so HoS' (Or Antags) have more options to choose from.

## Changelog

```
(u)Comradef191:
(*)Added some additional items to the Cog1 armory; an EOD suit, a N2O canister, a tranq crate, and a box of stinger grenades.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Access change isn't major imo, and lattice shouldn't be on there

**Comment by flrsh** [comment]
When possible, please try to condense your changelogs and keep them brief.

**Comment by Gannets** [comment]
As the person who last touched cog1's armory, at the time I had players telling me those items were useless and would be better replaced with tools and weapons that game security a little more teeth when in combat.

I'd ask that if people are happy with the state of the armory post this PR, that those changes be made to our other maps in rotation as well.

**Comment by ZeWaka** [comment]
@comradef191 said they had a fix

**Comment by comradef191** [comment]
Its 0130 right now but i'll have it up soon

**Pull request merged**
