### PR TITLE
Derelict Medibot antagonist critter

### PR DESCRIPTION
**Pull request by mc-oofert**
[FEATURE]

## About the PR 
_**Path: /mob/living/critter/antag_medibot**_
Adds a new antag critter; a Derelict Medibot. (You know, the ones that you find in the debris field!)
Has two limbs, one is a "Hypospray" hand and the other is a normal hand, which spawns with a scalpel.
The hypospray arm can inject people (an action bar of 5 seconds) at close range with random awful chemicals, or at longer ranges unleash a smoke cloud of horrible chemicals. These have a cooldown of 35 seconds, and if the target or you move during injection, it gets cancelled. Also you can unleash a smoke cloud while moving.

Vulnerable to burns. Also can grab people to put them on operating tables (or whatever other surface).
Has thermal vision, and can see peoples health (like ProDocs), and cannot sprint.

2022-01-03 14_48_07-Goonstation Development_ Home Site 9000

## Why's this needed? 
We have (apparently derelict) gunbots, so another mechanical danger probably would fit
Gunbots are the "shoot everyone" while medibots are the "poison and stab" everyone

## Changelog

```changelog
(u)Jimmyl
(*)Added derelict medibots as antag critters
```

### CODE REVIEW

**Comment by DimWhat** [comment]
Would prefer the sprite be perspectivized before it's able to be player controlled. It looks really bad and is based on the old light borg frame.

**Comment by mc-oofert** [comment]
> Would prefer the sprite be perspectivized before it's able to be player controlled. It looks really bad and is based on the old light borg frame.

i dont do spriting

**Comment by NightmareChamillian** [comment]
> Would prefer the sprite be perspectivized before it's able to be player controlled. It looks really bad and is based on the old light borg frame.

Frankly, I'd argue you don't want to redo it, since it looks glanceably different from a current friendly. Also, respriting the playable critter wouldn't make much sense considering the ingame NPC critter isn't resprited either, and there'd be be dissonance

**Comment by flappybatpal** [comment]
A five second injection sounds nearly impossible to use unless they find someone already in a bad way.
Smoke cloud is not bad idea.

Not sure how this will work out in practice as an antag critter as it's not really combat capable or mobile.

**Comment by DimWhat** [comment]
> Frankly, I'd argue you don't want to redo it, since it looks glanceably different from a current friendly borg. Also, respriting the playable critter wouldn't make much sense considering the ingame NPC critter isn't resprited either, and there'd be be dissonance. If you want him to redo the old mediborg, then there's be an argument for the gunbots as well, and so on and so forth.
But gunbots already got resprited :thinking:

**Comment by mc-oofert** [comment]
> A five second injection sounds nearly impossible to use unless they find someone already in a bad way. Smoke cloud is not bad idea.
> 
> Not sure how this will work out in practice as an antag critter as it's not really combat capable or mobile.

probably if i change it to 2 seconds it should be good enough

**Comment by mc-oofert** [comment]
the inject attack probably could be used after someone is downed by smoke

**Comment by alexeric123** [comment]
the smoke would be trivialized with a gas mask though, unless its made to skinpen somehow

**Comment by mc-oofert** [comment]
> the smoke would be trivialized with a gas mask though, unless its made to skinpen somehow
> 
> also, with the cleanbot, its the exception, as their gimmick is lube and run, the rest of the antag critters still have some method to deal damage, even if they are countered by some items.

if they have gasmasks just shank them with a scalpel

**Pull request closed without merging**
