### PR TITLE
Adds unique PDA emergency alert variants (font color, jingle)

### PR DESCRIPTION
**Pull request by Glamurio**
[Objects] [QoL] [Rework]

## About the PR 
This adds proper distinction between all alert variants in the game. Every alert now has a unique font associated with the department that the alert is for, as well as a new jingle to differentiate it from the Security alert, which has been unchanged.

image

Engineering Alert:
https://pixabay.com/sound-effects/red-alert-nuclear-buzzer-99741/
Medical Alert:
https://freesound.org/people/SpliceSound/sounds/369848/
Janitor Alert:
https://freesound.org/people/milton./sounds/81165/

All three of them were slightly altered in either pitch or speed to be more fitting.

PixaBay License:
https://pixabay.com/service/license-summary/

FreeSound ToS:
https://freesound.org/help/tos_web/

## Why's this needed? 
To avoid confusion about the kind of alert that has been sent in any given situation.

## Changelog 

```changelog
(u)Glamurio (Ryou)
(*)PDA Emergency Alerts now have distinct visuals and jingles.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
that font is pretty unreadable

**Comment by deathrobotpunch** [comment]
i would also like a medical alert module for medic pda’s

**Comment by deathrobotpunch** [comment]
and the font has always been unreadable

**Comment by Glamurio** [comment]
> that font is pretty unreadable

> the font has always been unreadable

Yeah, I was going to mention. The font hasn't been changed, just the color.

**Comment by pgmzeta** [comment]
I think only dedicated modules should get the big alert text, but different jingles are very good.

A key difference to me is that PDA Program alert can be issued by any random crew member, and PDA Module alert is (presuming no theft) a person asking *their team* for backup. This is why the alert button is worth sacrificing a PDA flashlight for - as Security, you have a button that tells the rest of Security shit's fucked. Other non-sec crew around you can hear/see/react to security calling security for help.

Adding a medical alert module and engineering alert module ala the security ones but placing them in their respective equipment vendors makes sense, and can use the jingles/text. It would be a good default for the Medical Doctor PDAs too, I think.

**Comment by DisturbHerb** [comment]
i just think it's funny when i call for a janitor and everyone looks at me funny

**Comment by flappybatpal** [comment]
Where are these sound effects sourced from?

**Comment by Glamurio** [comment]
> Where are these sound effects sourced from?

They're royalty free sound effects sourced from, [Pixabay](https://pixabay.com ), [TunePocket](https://www.tunepocket.com) and [FreeSound](https://freesound.org). I've then tweaked some of the sounds to make them more fitting. Should all be legal under Creative Commons.

**Comment by DisturbHerb** [comment]
Explicitly crediting the sources is best practice, especially for reviewers.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
since these are CC-BY licensed sounds, you need to provide attribution. please attribute all sounds in the description.

**Comment by Glamurio** [comment]
Okay, I goobered and lost the original links, but by spending a few hours browsing my search history, I managed to find the exact files in question:

Engineering Alert:
https://pixabay.com/de/sound-effects/red-alert-nuclear-buzzer-99741/
Medical Alert:
https://freesound.org/people/SpliceSound/sounds/369848/
Janitor Alert:
https://freesound.org/people/milton./sounds/81165/

All three of them were slightly altered in either pitch or speed to be more fitting.

PixaBay License:
https://pixabay.com/service/license-summary/

FreeSound ToS:
https://freesound.org/help/tos_web/

**Pull request merged**
