### PR TITLE
Implements a limit to how much can be eaten at once.

### PR DESCRIPTION
**Pull request by Wisemonster**
[BALANCE] [CATERING] [INPUT WANTED] [STATUS EFFECT] [EXPERIMENTAL]

## About the PR 
This pr adds in a system for tracking how much mobs have eaten. in this pr, if a mob takes 11 bites (about the equivalent of 2 hamburgers) of food, they'll become "full", meaning eating any more while full will result in damage to the stomach, eventually killing the stomach. This damage is only applied to the stomach if they aren't a mob critter, so the mobs themselves won't take any direct damage from over-eating, except mob critters, which will take direct damage due to not having a stomach.

They are 2 status effects tied in with this system, a "recently eaten" status effect, and a "over-eaten" status effect. Upon the status effects expiring, the mob's bite count is reset to 0, allowing them to eat more without taking stomach damage. I've made the over-eaten status effect take longer to expire to disincentive over-eating even more. If this is deemed more appropriate for rp, I can change some things to restrict this to rp.

## Why's this needed? 
Currently, it is possible for a staffie to come to the kitchen and gobble up all of the chef's food in a minute. This will prevent the chef's hard work from being devoured by a single person, and also give more use to the stomach cyber organ, which currently does very little. This also allows for ways to alter the mobs stomach capacity in future prs, such as some antags having higher/lower capacities, or organ types changing capacity

## Changelog 

```changelog
(u)Wisemonster
(*)There is now a limit on how much a mob can eat at a time, check minor changes for details
(+)You can only eat around 11 bites of food before the next bite will make you "over-eaten", if you eat more while in this state, you will damage your stomach.
(+)Waiting out the "recently eaten" and "over-eaten" status effects will reset you eat count.
```

### CODE REVIEW

**Comment by M-Earthfire** [comment]
How does that interact with non-ghostcritter mobs? Especially chickens.

**Comment by Wisemonster** [comment]
I guess I need to clarify in the pr, but basically the damage is applied to any mob critter that doesn't have a stomach, so it'll affect any critters that aren't still obj . I'd change the stomach capacity of the chicken mobs to make sure this isn't an issue, but that's secret stuff.

**Comment by M-Earthfire** [comment]
I have written it in the forums, because their whole evolution mechanic is food based, so that was just the most possible situation i could think off where this could break.

**Comment by MylieDaniels** [comment]
This PR would make it such that your stomach takes 10 organ damage per bite, with no cooldown, after eating a pair of sandwiches.  However, you could also eat 11 cookies, or 11 MONSTERs to get to this point.  Then, you get 5 minutes of cooldown every bite you take, which refreshes itself with every bite you take, and can also kill your entire stomach in two more burgers (about 5 seconds).
This hurts chefs way more than it helps them, speaking as someone who plays chef, and loves when people can actually eat my food without.  This is a massive change, with massive consequences, which relies on the fact that stomachs are one of the few organs that can currently die with no consequences.
Also, on the RP servers, there is a food motive.  It can take upwards of 15 bites to fill this motive.  That, with this change, would deal 40 organ damage to your stomach.

**Comment by Wisemonster** [comment]
I could increase the stomach capacity to around 21, if it's necessary. I'm also making a sister pr that changes how many bites it takes to eat a monster burger. I also am having trouble finding instances where you would need to eat more than 15 bites, outside of completely neglecting your hunger motive to the point where your getting debuffs.

**Comment by Wisemonster** [comment]
Also, I'm having trouble recreating a soup bowl that takes 20 bites to eat.

**Comment by Wisemonster** [comment]
Important note: The damage dealt to the stomach does NOT deal direct damage to the mob, so you are not gonna go into crit if you eat 10 extra bites .

**Comment by MylieDaniels** [comment]
> I could increase the stomach capacity to around 21, if it's necessary.

The concept, not the numbers, is the root of the issue.

> I'm also making a sister pr that changes how many bites it takes to eat a monster burger.

Multiple unneeded changes is not the answer.

> I also am having trouble finding instances where you would need to eat more than 15 bites, outside of completely neglecting your hunger motive to the point where your getting debuffs.

... eating when you get the hunger debuff is pretty much how 50% of the playerbase handles motives.

> Also, I'm having trouble recreating a soup bowl that takes 20 bites to eat.

To make a soup that takes 20 bites to eat, simply add standard edible items until the pot is full.  It's the most basic soup.

> Important note: The damage dealt to the stomach does NOT deal direct damage to the mob, so you are not gonna go into crit if you eat 10 extra bites .

I'm aware.  But you will KILL an organ in 20 bites, which takes sub-10 seconds.  The fact that this doesn't put you into crit or damage your health bar instantly is not a saving grace.

**Comment by nefarious6th** [comment]
Admire that you want to approach the issue of the over-indulging staffy; cant say I like implementation of this though. I generally greatly dislike "full" mechanics on any servers, whether it gives slowdown or here where it gives stomach damage. Other people mentioned issues with mobs; I think of issues of healing or on RP, trying to raise hunger stats to avoid debuff. The way this works would imo be too limiting to other aspects of gameplay (healing via food, eating 4 donuts to max hunger) to solve just the one issue of staffies eating too much  for their take.

**Comment by TDHooligan** [comment]
i'd rather a hard limit of being physically unable to stuff yourself rather than "you die by eating too much". i think the soft-limit could make it *more* entertaining for staffies and encourage destroying the chef's round as a half-assed suicide rather than a deliberate gimmick.
TBH i think a better approach would be to add a proper 'limit' variable to the stomach, then the limit could be multiplied/decreased by stuff like robotics, lipolicide and weed. I think intestines already adjust processing speed, so stomachs are your 'capacity'.

**Comment by Wisemonster** [comment]
Killing your stomach only prevents you from eating. It will not cause tox damage, or brute damage, or any damage to the mob itself (unless it's a critter). I didn't include any stomach modifying stuff in this pr to prevent feature creep, however the way it's set up would allow things in the future such as cyber organs modifying stomach capacity. It's also a soft limit, into a hard limit, due to how a dead stomach works.

**Comment by flappybatpal** [comment]
Agree with TDHooligan here. As a developer I'd rather this be a (well communicated) hard limit and not involve organ damage at all.
Bites is not an unreasonable metric to use but it's too arbitrary with food sizes, packs of candy would fill your stomach like a burger. I don't think there's any getting around an additional variable on food that defines how stomach filling it is.

**Comment by flrsh** [comment]
> Admire that you want to approach the issue of the over-indulging staffy; cant say I like implementation of this though.

Basically my thoughts as well. I feel like something like this at least requires adjusting bites and heal amounts for all food items.

**Pull request closed without merging**
