### PR TITLE
Adds apply view tint option under Game->Effects menu

### PR DESCRIPTION
**Pull request by Shroopy**
## About the PR 
Adds an option to apply view tint. It's on by default, and when unchecked, glasses, masks, etc. don't change the color of the screen.
## Why's this needed? 
Having more accessibility options is good. For example, taking on and off colored glasses like the health or reagent goggles can make people sick (like myself).

## Changelog

```
(u)Shroopy:
(*)Added an option in Game->Effects to enable or disable view tinting from glasses, masks, etc.
```

### CODE REVIEW

**Comment by TTerc** [comment]
I can understand the accessibility thing but I'm almost certain people will make use of this feature to get rid of welding mask penalty

Perhaps the welding mask view should be reworked too?

**Comment by Shroopy** [comment]
Ah, I thought the welding mask worked differently than it did, I'll work on creating an exception list

**Comment by Shroopy** [comment]
Alright, the welding mask is no longer affected.

**Comment by Flaborized** [comment]
I don't personally care about the "balancing" of the welding masks and sunglasses being darker. IMO the added accessibility of being able to turn the feature off outweighs the concern that people might use the feature to alleviate the downside of them making the game uglier; I'd rather welding masks have a unique balancing factor separate from this. (I think they do already though, iirc they have more armor when you flip them up? So there's a reason to leave them flipped up)

**Comment by ZeWaka** [comment]
One of the things we've wanted to do to make welding masks better was to make them my realistic by applying a restriction on the view size, without changing .view:
image

**Comment by Shroopy** [comment]
In that case, I'm going to remove my exception code and let tint affect everything, especially since I realized my exception code had a loophole

**Comment by Shroopy** [comment]
Reverted, ready for merging pending further requests!

**Comment by ZeWaka** [comment]
For posterity, https://github.com/goonstation/goonstation/pull/1746 implements the welding mask thing.

**Comment by pali6** [comment]
@ZeWaka The shortsightedness effect basically does that except with a checkered white sprite instead of a full black overlay. Could be repurposed for this too.

**Comment by ZeWaka** [comment]
@mybluecorners did you want this to be able to turn off the welding mask darkening color thing?

**Comment by pali6** [comment]
Relaying mbc's comment:

> yes
> should disable weld mask bc the weld mask effect should not have a mechanical downgrade for like, your sight
> only in its armor values and protections
> (like it does last i checked)

so I assume this is good to merge.

**Review by pali6 — APPROVED** [review]

**Pull request merged**
