### PR TITLE
Martian Critter Resprite

### PR DESCRIPTION
**Pull request by ThatFancyGent**
## About the PR 
Martian Mob sprite updates

## Why's this needed? 
The current martians look unfitting to the game's current artstyle, this will change their appearance so that they do.

## Changelog

```changelog
(u)ThatFancyGent
(+)Updated martian sprites.

### CODE REVIEW

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
Nice work! Just a heads up, there is a big player-run martian re-imagining happening, that would move our sprites away from the Metal Slug-inspired designs. However, if you're ok with that change happening in the future, I'd be down to merge this as a sprite replacement for now as current martians are defs crusty, lol.

In regards to changes; I like these a lot, but are you able to do a simple 2-frame animation for them? Akin to hmmm the rockworm, or robin/sparrow sprites as an example. I've been trying to move away from static critters with recent resprites, and a simple lil 2 frame bop animation adds a lot of life. If you're not able to, would you be ok with me adding it in after these are merged?

**Comment by ThatFancyGent** [comment]
martian
alright, i gave the martians a 2 frame headbob animation (the warrior's being a bit faster and the purple one's being a bit slower)

**Comment by flappybatpal** [comment]
Looks good to me.

**Review by WALPVRGIS — APPROVED** [review]
Looks great! 😸

**Pull request merged**
