### PR TITLE
Adds monkey bell, which pacifies nearby monkeys

### PR DESCRIPTION
**Pull request by tanker4390**
[AI] [OBJECTS] [BALANCE] [FEATURE]
## About the PR 
Adds a "monkey bell" which, when used (by a non-monkey), pacifies all monkeys within hearing range. The bell may break on use, but can be repaired. The bell can be EMAGged to produce the opposite effect, as well as increasing it's chance to break and removing it's ability to be repaired. The bell has no effect on monkeys that are always aggressive.

## Why's this needed? 
Monkey outbreaks are often difficult to deal with, especially when intentionally caused. The bell reduces the danger and makes it easier to deal with. Its 2 effects make interactions with monkeys more interesting.

## Changelog 

```changelog
(u)Tanker
(*)Added a "monkey bell" which can be used to pacify monkeys; but watch out for breakage, and EMAGs!
```

### CODE REVIEW

**Comment by muzcl** [comment]
I think this approach is a bit too easy, since it doesn't really have an explanation. A better way to go about it IMO would be having the option to give monkeys bananas (or other food too, but bananas would work best) to pacify them, and putting poison or bad tasting things in the bananas via injection to anger them.

**Comment by flappybatpal** [comment]
Misread as "monkey ball", disappointed.

**Comment by tanker4390** [comment]
To be clear, this references cowbells or _Almglocken's_ use on cows as livestock (but here the livestock is monkeys).
As for the function, this simply instantly makes them passive, and does not prevent them from becoming aggressive in the near future, but is useful if you want to stop a monkey from beating you into crit.
The chance for the bell breaking was designed to prevent a human from being able to infinitely robust monkeys (aggravate, ring bell, repeat) but looking at it again, it might be too easy to repair.
The banana route could work as well as a more permanent way of pacifying them/make them less aggressive, as well as being a good way of manipulating them as antagonists.
Too many times have I seen some jerk with kitchen/research access vend 15 monkeys into an area!

**Comment by amylizzle** [comment]
I'mma go ahead and slap the controversial tag on this, based on all the :confused: emojis and the questionable balance.

**Comment by tanker4390** [comment]
Now, this can be rebalanced as needed, with several variables.

**Comment by M-Earthfire** [comment]
How will this interact with monkey-barrel-monkeys?

Overall, though, i'm not that much of a fan of the idea in general. Mass monkeys should be a threat and i don't think having an option to mass pacify monkeys is good. If it would be targeting a single monkey on melee use, i would be more positive on it.

**Comment by tanker4390** [comment]
> How will this interact with monkey-barrel-monkeys?
It has no effect on those, Oppenhiemer, or other monkeys without `ai_calm_down` set.

**Comment by tanker4390** [comment]
Hmm. Perhaps the monkey bell should be an endgame/RD item.

**Pull request closed without merging**
