### PR TITLE
Material property cleanup

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
Gives abstract material parents some (hopefully reasonable) defualts for properties, and squishifies properties down to a 1-9 range (from 1-120)
Additionally axes a bunch of older and unmaintained material-related stuff, and generally simplifies the numbers involved.

does not remove arbitrary material alloying (yet)

Might break everything.

## Why's this needed? 
material code is a mess of reworks and half-realized dreams. This PR seeks to fully unrealize some of those dreams and provide a jumping-off point for further not-reworking of materials.

## Changelog

```changelog
(u)tarmunora
(*)materials have (hopefully) reasonable defaults for properties, and property values have been squisified down to the 1-9 range.
(*)Some things, especially with respect to fabrication, may not work as they did before/as expected. If there are any serious problems, make a bug report or something so it can be looked at.
(+)neutronium recipe disabled
```

### CODE REVIEW

**Comment by ZWRh3** [comment]
im propsing a multiplier: material_amt * amount
for stuff like radiation power currently 40 unstacked floor tiles are as powerful as 40 unstacked ores despite a singular ore allowing for the creation of 40 of them

also stacked items are treated as one when it comes to this

obviously you cant use this exact mult for all properties but for radioactivity its likely good

**Comment by amylizzle** [comment]
How come 0-10? I ask because if it's 0-100 I don't have to change my thing :D

**Comment by ThatFiveGuys** [comment]
Basically it makes differences in materials feel much more distinct, right now things like starstone and iridium feel basically the same.

**Comment by ThatFiveGuys** [comment]
if everything has default values, does that mean that material analyzers now print out every single value even when those values dont really matter? It seems good to have things not print out when materials have a reflectivity of 1. Removing stability seems good considering that there is no longer any counterplay to it considering no null values, and having batteries randomly just delete themselves for no reason related to there proc seems bad. Considering how niche corrosion resistance and permability are merging those two stats doesnt seem like a bad idea as well. Also I think itd be good if flammability was distinctly only used for if things would catch fire (and things like furnace effectiveness) by having no very fireproof/fireproof values, and have thermal conductivity stat be used for things like fire resistance. This would make these two values feel much more distinct and clarify what those stats exactly do.

**Comment by maybeserendipitous** [comment]
I'd prefer just 0 to 1, since that forms a ring which lets us do nice things like multiply properties together but stay within range. -1 to 1 is also a ring and would work too, and might even work better for some properties. Other ranges like 1 to 9, 0 to 10, and so on aren't rings and tend to need to be "scaled down" into rings anyways, e.g. in `teg_transform.dm` and the corresponding `get_efficiency_scale` in `TEG.dm`, where `efficiency_scale` is scaled down by a magic constant `0.01`, which could probably be avoided by using 0 to 1 or -1 to 1.

**Comment by maybeserendipitous** [comment]
Also, something that's bothered me about current matsci is that smelting sometimes acts like it's "averaging" materials and sometimes acts like it's "summing" materials. For example, with n_radioactivity, combining it with anything besides neutronium results in a single material piece with the same neutron radioactivity, so it's like it's "summing" the two materials. But if the other material has density, then the resulting density is the average of the two even though we're only getting one material piece, so it's like it's "averaging" the materials. It would be nice if it EITHER summed or averaged, and it'd be even nicer if we had an option to choose between the behaviors, but "averaging" is probably the more sane/realistic of the two, if I had to choose one.

**Comment by ZWRh3** [comment]
> Also, something that's bothered me about current matsci is that smelting sometimes acts like it's "averaging" materials and sometimes acts like it's "summing" materials. For example, with n_radioactivity, combining it with anything besides neutronium results in a single material piece with the same neutron radioactivity, so it's like it's "summing" the two materials. But if the other material has density, then the resulting density is the average of the two even though we're only getting one material piece, so it's like it's "averaging" the materials. It would be nice if it EITHER summed or averaged, and it'd be even nicer if we had an option to choose between the behaviors, but "averaging" is probably the more sane/realistic of the two, if I had to choose one.

that was probably just null stats

erebite (75) rad + steel (null rad) = 75 rad alloy
if steel has 0 instead of null its an average of the 2 or in other words 38

**Comment by Tarmunora** [comment]
> I'd prefer just 0 to 1, since that forms a ring which lets us do nice things like multiply properties together but stay within range. 

Hm, that's a neat idea. But on the other hand I really don't want to go back and re-adjust it all again 😥

**Comment by Tarmunora** [comment]
yolo

**Comment by maybeserendipitous** [comment]
> > I'd prefer just 0 to 1, since that forms a ring which lets us do nice things like multiply properties together but stay within range.
> 
> Hm, that's a neat idea. But on the other hand I really don't want to go back and re-adjust it all again 😥

I'm tempted... may take a look later.

**Comment by ThatFiveGuys** [comment]
While nicer on a coder side i think the lower numbers will make higher stats feel worse on the gameplay side

**Comment by maybeserendipitous** [comment]
> While nicer on a coder side i think the lower numbers will make higher stats feel worse on the gameplay side (ie 2 to 4 feels much more different then .2 to .4)

The Material Analyzer can just scale the numbers up when displaying them if that's an issue.

**Comment by ThatFiveGuys** [comment]
I mean at that point that just seems like the old system (assuming you dont explicitely say no to numbers in the hundredth place)

**Pull request merged**
