### PR TITLE
Kills off trace gases

### PR DESCRIPTION
**Pull request by Laboredih123**
[ATMOSPHERICS][REWORK]

## About the PR 
Removes trace gases as much as possible, moving them to the APPLY_TO_GASES system.

## Why's this needed? 
The original purpose of trace gases of being modular has been rendered useless by the APPLY_TO_GASES system, now only really slowing down the game and ruining readability.

### CODE REVIEW

**Comment by Laboredih123** [comment]
Hm, that should be pretty easy. If it equals zero, just don't show it.

**Comment by Laboredih123** [comment]
but feature creep...

**Comment by Laboredih123** [comment]
never mind adding that var is not so easy due to shifting the arguments in every single macro. ill just switch the analyser to simple output.

**Comment by Laboredih123** [comment]
this seem good?
image

**Comment by Laboredih123** [comment]
Same as always, if it has zero gas it says there is no gas. I didn't modify that part, I just switched it into simple output so it only shows gases that actually are there.

**Comment by Laboredih123** [comment]
find any bugs please

**Review by pali6 — APPROVED** [review]

**Pull request merged**
