### PR TITLE
Automatic NanoMed Plus

### PR DESCRIPTION
**Pull request by Superlagg**
[WIP][FEATURE][HELP WANTED][SPRITES][DNM]

## About the PR 

Adds in a form of medbot built out of a NanoMed Plus vending machine! It can't move on its own, but it has access to a much wider range of medical treatments designed to fill in for an understaffed (or undertrained) medbay.

Simply toss someone in front of the machine and it'll do the rest! Typically just injecting them with painkillers and crit drugs, that is.

Its a work in progress, the main *thing* is put together, but it still needs a lot of work.

Some stuff of note!
 - The bot blurts out both the "found patient" and "stabbing patient" lines at the same time. 
 - The bot is set to be dense, but pushing it results in it being pushed, and you teleporting to where it ends up.
 - The bot tends to ignore people until they've moved away then moved back next to it.
 - The server seems to crash after a while and I dont know why
 - I couldnt get the vending machine proc to read the right var from the arm assembly thing, so I just set it to read if its pixel_x is the same as the completed arm thingy. Seems to work?

Todo:
 - Get the machine stored in the bot to be usable while in bot form.
 - See if the bot drops the machine it contains.
 - Get the bot to slow down and enunciate.
 - Get the bot to make noise and beep and yell and stuff.
 - Work out the healing logic so it works good and not just sorta-good.
 - Get the bot to be actually solid
 - Find out why it keeps crashing everything??

## Why's this needed? 

I've noticed something from the Streamertide; people die a lot from things we take for granted! Part of it comes from Medbay either not having enough stuff to keep everyone alive (especially if people keep eating all the salb!), or not enough medics know how to treat people! While it would be nice to have someone who knows what they're doing to teach them how to Medbay, that's not always possible.

This thing's not supposed to replace a decent medic, it's there to more actively supplement a medbay lacking decent medics. 

## Changelog

```
(u)Superlagg:
(*)NanoMed Plus machines can be turned into robots!

```

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Hard disagree; this thing will be a better doctor than most doctors, and completely break the need to even remotely ration your rarer medical chems.

**Comment by F-OS** [comment]
I like it conceptually, however I think it needs serious balancing. Having some kind of rarer and better medbot is good in theory, but it should never be better than an experienced doctor. A possible change to make this more balanced might be removing chems like synaptizine, atropine, and salicylic acid, limiting the bot to simpler chems. This'd still make it much better than your average medbot, while not crowding out doctors. Thoughts?

**Comment by MarkNais** [comment]
I also don't much like ideas that "replace players". I appreciate this is trying to help an often bust department, but I don't agree with the direction.
I say cryotubes already work pretty well as an under-staffed stop-gap for medbay.

Here's an idea, that I don't 100% like, but could reduce mental-load on doctors some:
Make health-scanners remember the last reading.
Slapping a health-scanner on a nano-med will have the nano-med spit out the relevant chem/salve for the highest-scanned-damage of the main-four. Only recognizes the main four.

**Comment by Emcee-Gore** [comment]
There are various ways of dealing with hurt people and even more ways to revive them as is. You can use Strange Reagent, clone them or borg them. I see no reason to make it harder for people to die.

Imagine this - you as a traitor have nearly finished off a victim; now they lie somewhere far away in a maintenance shaft and the AI can simply warp your machine to that person. Part of the fun is to call out where someone needs help, to direct PEOPLE to do stuff. Automating such a vital part of the medical staffs job seems off.

Regarding the problem that medbay might be understocked at some point...well there is QM. They can order lots of medical supplies.
Most rounds I see the sweet lollipops that grant random medical chems when eaten unused. Cryotubes are also not always in use...there are many tools at the medical staffs disposal already...I feel like this is just too much.

---

What I'd perhaps rather see would be a new kind of roboter that robotics could build. A medical spider. A small robot wandering around the station and use itself up on anybody hurt badly.
These medical spiders could be crafted with various different components to get different uses out of them...but at least that would be a limited appliance and not a sheer automatic one.

P.S. Robotics could seriously use more tools to play with - some to support medbay perhaps.

**Pull request closed without merging**
