### PR TITLE
Makes atmos constructable and stuff

### PR DESCRIPTION
**Pull request by Laboredih123**
[ATMOSPHERICS][FEATURE][INPUT WANTED]
## About the PR 
Atmos is now constructible using a welder on harm intent and a atmos construct. Can't wait to see engine setups.

def not ready since i am slow
like dont expect this to be fast

## Why's this needed? 
New atmos content is good.

## Screenshots
image
image
image
image
image

```changelog
(u)Laboredih123
(*)Atmos is constructible using a welder on intent.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
I feel like the atmos pipe dispensing would be better if it was just a second function of the already existing pipe dispenser instead of its own thing

**Comment by nefarious6th** [comment]
Finally...we will poolburn again

**Comment by Laboredih123** [comment]
> I feel like the atmos pipe dispensing would be better if it was just a second function of the already existing pipe dispenser instead of its own thing

seems ill need to adapt the dispenser to tgui and multiple constructs then

**Comment by Laboredih123** [comment]
Might need to rewrite how disposal constructs work to have the same code for both constructs and I'm not sure I want to touch disposal stuff in a atmos pr.

**Comment by thegrb93** [comment]
I was just browsing the wiki the other day trying to see how to edit pipes. Can't wait

**Comment by Laboredih123** [comment]
i havent forgotten about this, just distracted by other atmos stuff in other codebases

**Comment by Laboredih123** [comment]
should probably atomise this pr

**Comment by Laboredih123** [comment]
might close this pr, atomise some things, and reopen a new one thats more focused.

**Comment by Laboredih123** [comment]
Gonna close this pr, reopen a new one after I atomise some things to make the next pr better.

**Comment by ZeWaka** [comment]
:feelsgood:

**Comment by Laboredih123** [comment]
#21509 hehehehehehe

**Pull request closed without merging**
