### PR TITLE
Remove Katana and Wrestling Belt from surplus crates

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Removes both the katana and wrestling belt from surplus crates

## Why's this needed? 
The wiki states "some items cannot appear in them, primarily those geared towards murder" and these 2 items in particular are if anything stronger at rampaging than a csaber, let alone them appearing with other items like stimulants.

## Changelog 

```changelog
(u)JORJ949
(+)Removed Wrestling Belt and Katana from Surplus crates.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
I agree with taking out the katana and wrestling belt but I think the megaphone is going to be a pretty big disappointment for 5tc worth of your crate most of the time.

**Comment by klookiyam** [comment]
The blowgun looks like an interesting weapon, maybe you can get one of the variations of those?

**Comment by frawhst** [comment]
Not sure about this— as far as I understand the removal of certain rampage items from the surplus crates is just to reduce the odds of getting some crazy weapon setup from the crate. We don't necessarily want to remove all weapons from the crate, but we do want to remove *some* of them so that the odds of getting rampage items are skewed a bit lower.

**Comment by JORJ949** [comment]
Removed megaphone changes, those are not what this PR is for

**Review by TobleroneSwordfish — APPROVED** [review]
Thinking about it, if the point of taking c-sabers and revolvers out is to prevent busted combos with other items then it should include the other "this is 7TC because otherwise you could also buy stims/cloaker" items like the katana and wrestling belt.

I like the idea of the surplus crate being a box of random gimmick supplies rather than "you rolled a wrestling belt, so now you have to go LOUD and do WRESTLER THINGS"

**Pull request merged**
