### PR TITLE
Nuke Ops balance pass + additional utility items

### PR DESCRIPTION
**Pull request by Gannets**
## About the PR 
A variety bag of nuke ops fixes, rebalances and features.

Adds:

- Added non-slip combat boots as a utility purchase from syndicate weapons vendors.
- Added an inflatable decoy nuclear bomb as a utility purchase from syndicate weapons vendors.
- Added high-capacity brute and burn auto-menders to the Field Medic kit. They contain 500 units.

Changes:

- Operative's now spawn with sunglasses and a breath mask equipped and an emergency O2 tank in their pocket.
- The Combat Medic class is now named Field Medic.
- Field Medic specialist armor now acts as a bio-suit.
- Von Braun, the Cairngorm resident monkey has been retired and replaced with Oppenheimer, who's namesake is still pretty bad but doesn't give me the same nazi vibes.

Removes:

- Operative's no longer spawn with helmets or body armor.
- The Field Medic kit no longer includes several unnecessary autoinjectors, bandages and patches.
- The Field Medic kit no longer includes the syringe gun or it's associated tanks.

## Why's this needed? 
More powerful utility purchases give players more meaningful choices when assembling their kit. The medic class suffered from an overabundance of tools that had limited use in most firefights. This PR consolidates their options to only what is needed, hopefully reducing the amount of time spent fiddling with gear and improving medical efficiency. They no longer carry a primary weapon, to encourage a focus of healing, but there's plenty of newly-empty space in their bags for a sidearm.

## Changelog

```
(u)Gannets:
(*)Added non-slip combat boots and an inflatable decoy nuclear bomb as utility purchases from syndicate weapons vendors.
(+)- Operative's now spawn with sunglasses and a breath mask equipped and an emergency O2 tank in their pocket.
- The Combat Medic class is now named Field Medic.
- Field Medic specialist armor now acts as a bio-suit.
- Added high-capacity brute and burn auto-menders to the Field Medic kit. They contain 500 units.
- Von Braun, the Cairngorm resident monkey has been retired and replaced with Oppenheimer.
- Operative's no longer spawn with helmets or body armor.
- The Field Medic kit no longer includes several unnecessary autoinjectors, bandages and patches.
- The Field Medic kit no longer includes the syringe gun or it's associated tanks.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
perhaps 'high-capacity automenders' (500u?) or a single high-capacity synthflesh mender, to make medic healing notably better than just grabbing stuff from the cairngorn medbay?

**Comment by Gannets** [comment]
Agreed and added.

**Comment by Retrino** [comment]
idea by mbc: have an eyewear section on the loadout venders. 1 point that can be spent on sunglasses/mesons/nvg rather than spawning ops with something already worn

**Comment by Gannets** [comment]
> 
> 
> idea by mbc: have an eyewear section on the loadout venders. 1 point that can be spent on sunglasses/mesons/nvg rather than spawning ops with something already worn

Worth considering for a future pr.

**Pull request merged**
