### PR TITLE
Slight Rearangement of Debris Field 

### PR DESCRIPTION
**Pull request by Eagletanker**
[Mapping] [Balance] [Input Wanted]
## About the PR 

In the current debris field, it is way too easy to get Strelka and a MK3 Disruptor. Some areas like the Santa ship are weirdly well protected, and drones regualarly camp the mining outpost, harrassing people moving in that area when they should be in the debris field proper. I've moved the Strelka carrier farther into the debris field, and also moved the Strelka hanger beacon into the ship itself, so you have to go past the saw drone in order to reach strelka. I have moved the Santa ship to near the mining outpost, so drones wont harrass the outpost anymore, leading hopefully to more use in general gameplay. The MK3 disruptor has been moved to near the asteroid field around the Prisoner Transport, so you have to fight for a very powerful pod weapon.

## Why's this needed? 

Moving the aformentioned things adds a layer of freshness to the Debris Field, along with making the good loot harder to get consistantly.
For Reference, here is the times it took me to get strelka on the current Debris and the new one, with the starting point being Cog 1's crew quaters.

CURRENT TIME: 49.82

NEW TIME: 1:17.51 

## Changelog

```changelog
(u)Eagle

(+)Rearanged the Debris Field a bit. Have fun!
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Id like to point out that the disruptor 3 isnt too strong compared to other options, moving it seems eh.

**Comment by ThatFiveGuys** [comment]
Also this pr does change the build.dm file a bit, Id reccomend reverting build.dm changes.

**Comment by Eagletanker** [comment]
> Also this pr does change the build.dm file a bit, Id reccomend reverting build.dm changes.

It seems that there's a - being deleted. I dont know why but I'll add it back

**Comment by Eagletanker** [comment]
Closing due to checks failing. Going to figure out why and then repr

**Comment by Azrun** [comment]
> Closing due to checks failing. Going to figure out why and then repr

_std/__build.dm:124:error: : empty type name (indentation error?)

Should be able to revert changes to __build.dm and re-open the PR . But follow your heart.

**Comment by Eagletanker** [comment]
> > Closing due to checks failing. Going to figure out why and then repr
> 
> _std/__build.dm:124:error: : empty type name (indentation error?)
> 
> Should be able to revert changes to __build.dm and re-open the PR . But follow your heart.

It might be due to the - but I don’t have any clue.

**Pull request closed without merging**
