### PR TITLE
Cyborg cell cables usable on other cyborgs

### PR DESCRIPTION
**Pull request by kbsmilk**
[SILICONS] [FEATURE]
## About the PR 
* Cyborg cell cables can now donate charge to other /mob/living/silicon.
* You cannot siphon power from silicons.
* It's a copy of the original's action bar with adjusted messages, and removed interrupt_flag INTERRUPT_ATTACKED to allow for silly business.

## Why's this needed? 
Has some niche usage in off-station ops, like azones. Also, sensible that jumper cables would work on anything with a cell.

Silly Business:
dreamseeker_SFqIFGTCvG

## Changelog 

```changelog
(u)Smilg
(+)Cyborg cell cables can now be used on other cyborgs.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Not a fan of having an EMAG interaction in here. Emagged cyborgs are just cyborgs with no laws, without changing anything in the modules themselves, and I'd rather not open up that can of worms

**Comment by kbsmilk** [comment]
> Not a fan of having an EMAG interaction in here. Emagged cyborgs are just cyborgs with no laws, without changing anything in the modules themselves, and I'd rather not open up that can of worms

Ya, I wasn't sure whether to permit/block draining other cyborgs, so, I settled on that. Thoughts? I lean towards block entirely, but no strong feelings, here.

**Comment by Tarmunora** [comment]
> > Not a fan of having an EMAG interaction in here. Emagged cyborgs are just cyborgs with no laws, without changing anything in the modules themselves, and I'd rather not open up that can of worms
> 
> Ya, I wasn't sure whether to permit/block draining other cyborgs, so, I settled on that. Thoughts? I lean towards block entirely, but no strong feelings, here.

I'd lean towards block. Alternatively, could rework the jumpers in such a way that they can only reach an equilibrium of charge (i.e.: can't easily drain to 0)

**Comment by kbsmilk** [comment]
Block it is. Noting that idea down though, might fold it in for future ideas.

**Review by Tarmunora — APPROVED** [review]

**Review by pgmzeta — COMMENTED** [review]
pronoun function suggestions

**Pull request merged**
