### PR TITLE
Airbridge refurbishment

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Airbridges are old. This PR makes their animations smoother and less intensive, makes them use regular lighting, spawns floor lights in them and gives them new sprites of questionable quality. (If you have better sprites please let me know.) I'd like to improve other stuff about them later but this is a good first step.

How it looks: https://gfycat.com/ringedbruisedilsamochadegu

## Why's this needed? 
Fullbright areas look ugly and so do the old airbridge sprites.

## Changelog

```
(u)pali
(*)New airbridge visuals and other minor improvements.
```

### CODE REVIEW

**Comment by trerri** [comment]
I like it but I think you should:
Remove the smoke effect
Give the walls terminus sprites and make them segmented like the floors
Use the lamp animation Kubius posted on Discord (can't find it aaaaa but it was basically the floorlight starting from the middle line of pixel and then adding a line above and below it every frame which I think looked less cartoony)

**Comment by pali6** [comment]
I also dislike the smoke and I toned it down quite a bit. I can remove it fully, sure.
If you want better sprites get me a person to make those. Segmented walls would be neat.
I'll think about the floor animation.

**Comment by pali6** [comment]
Removed smoke completely, changed the animation to something similar to Kubius's (just done through code instead of it being a sprite).

**Comment by pali6** [comment]
New light animation: https://i.imgur.com/gswAgqp.mp4

**Comment by pali6** [comment]
I'll just merge current version of the walls and when someone decides to make better ones I'll make a second PR.

**Pull request merged**
