### PR TITLE
(RP) Gang Mode - Min 20 Readied Players - Max 2 Teams, Max Tot' 4 Each

### PR DESCRIPTION
**Pull request by MarkNais**
[FEEDBACK][FEATURE]
## About the PR 
Adds potential for Gang to the Intrigue picklist. 
**The numbers below are just me slapping numbers around, please share thoughts in the PR comments.**
For gang to be pick-able on intrigue, 20 clients must be _readied at round-start_.
When the server is in `RP_MODE`:
- There is a single gang, unless there are 35 players _readied at round-start_, then there is the maximum of 2
- There is a maximum of 3 gang members per team (plus the gang boss per team)

Successor of #1229
## Why's this needed? 
Gang seems like it has the potential to be a good game mode for the RP server, but it's population-scaling is not suitable for Goon1 without some adjustment.

## Changelog

```
(u)MarkNstein:
(*)RP server: Gang is added to the Intrigue gamemode picklist if >=20 players are ready at round-start.
```

### CODE REVIEW

**Comment by MarkNais** [comment]
Per Mordent's experiential feedback in #1229, I'm starting the PR at a minimum player requirement of 20.

However as part of this PR I've changed the max team-size to a total of 4, and I think this means that the minimum player requirement could be brought down to 15 or lower. (single team of 4 ""vs"" 11 crew)

Additionally, the population-triggers are based on clients readied at round-start. Personally, I like to pick my role after-start. For this reason I'm more tempted to count clients, but that risks counting AFK / observers, and I don't like that. I could decrease my idea of 15 to *try* to account for latejoiners, but I don't like either. So bleh, counting readied.

**Comment by MarkNais** [comment]
Also: at the time of opening this PR, the RP server is experiencing much higher traffic than normal. I made this PR, and my comment above, assuming traffic returns close to previous levels, and that it would take time to receive some feedback before merging.

**Comment by Ley-bunned** [comment]
At 20 pop it should be 2 gangs with 4 people, I think. Otherwise it's gangs vs sec. From experience on 2, gangs vs gangs is a lot more fun for everyone because the rest of the crew can focus on dealing with gang fights.

RP gangs might need a different rule pop up to remind them this is actually on RP and the RP rules apply.

**Comment by Kyle2143** [comment]
We're gonna try it out.

**Pull request merged**
