### PR TITLE
Adds a playable flute

### PR DESCRIPTION
**Pull request by Mantweerp**
[GAME OBJECTS] [SOUND]

## About the PR 
Adds a playable flute, which can be stored in your pocket, with a range from C4 to C7, which can be obtained by hacking a general fabricator. The sprites were made by Mcdangus. 

The sounds were sourced from the Philharmonia Orchestra, we have previously used their sounds for a variety of instruments (all of the percussion instruments), but most of those seem to be unedited. These sounds are pretty edited to adjust the volume, the length, and the amount of vibrato (and also just general clearing up of some bad sounds), which, like has been said in the music instrument overhaul project on the  discord, would clear up copyright issues.

## Why's this needed? 
The flute is played in a lot of different genres of music, and thus, opens up a lot more versatility in ingame musicality.
 (music variation = 😃)

sound and sprite preview (video is compressed to have it be under 10mb)

https://github.com/goonstation/goonstation/assets/112985775/a58a2197-cf71-47d7-81ed-1347ab5236ad

## Changelog 

```changelog
(u)Mantwerp and Mcdangus
(*)Added a flute. Hack a general fabricator to get one! Sprites by Mcdangus.
```

### CODE REVIEW

**Review by frawhst — APPROVED** [review]
Can't comment too much on the sound quality but lgtm

**Comment by Mantweerp** [comment]
I've changed the sounds to be 0.1 second shorter as to make them faster (please please its been two weeks since the approval my flute is getting lonely)

https://github.com/goonstation/goonstation/assets/112985775/6e17228d-9560-421c-a619-f9bfb8a3a615

**Comment by TobleroneSwordfish** [comment]
The sprite is pretty indistinct, maybe making it diagonal would help?

**Comment by Mantweerp** [comment]
image

the barfer has a made new icon sprite (the bits on the side are because hes using the freeform snipping tool)

**Comment by TobleroneSwordfish** [comment]
Sorry no, after consulting with people who can actually sprite: it's too low contrast, doesn't have an outline and doesn't use our metal palettes. Maybe ask in #imspriter for help? Also the version you've posted there isn't the one that's in the PR.

**Comment by Mantweerp** [comment]
I'm closing this for now

**Pull request closed without merging**
