### PR TITLE
New Janitor job rewards + changes.

### PR DESCRIPTION
**Pull request by Carbadox**
##About the PR 
Added-
The red bucket is now a level 5 janitor job reward instead of being consolidated to being just a medal reward.
Added the orange mop, a reskin of a regular mop, as the new level 15 item
Added the Head of Sanitation beret, as the level 20 item.

## Why's this needed? 
Janitor has been missing job rewards for a while now, sucks that they were gone so now there's something to fill in the hole.
It would be nice to see the tsunami and antique mop again.

## Changelog
```
(u)Carbadox
(*)Added 3 new Janitor job rewards. Red bucket, orange mop and Head of Sanitations beret as level 5, level 15 and level 20 rewards respectively.
```

### CODE REVIEW

**Comment by monochromatism** [comment]
Not a reviewer, but the tsunami and antique mop are in a fairly accessible area at the edge of the debris field.  Are you sure that's not enough?

**Comment by Carbadox** [comment]
isnt that prefabs location random? I think that just makes it more annoying to find.
Idea for it wasn't original, Kyle originally suggested it when the JaniTech got added. 
To quote "We'd been meaning (sorta) to remove the tsunami bottle from the xp rewards and make it on the janitor ship in the debris level. I think it could also be good to have it chance be in the hidden tab of the vendomat."

**Comment by monochromatism** [comment]
I've always found it in the same spot.  Getting insulated gloves and hacking tools as janitor is already only about as hard as getting the tsunami and antique mop normally, so this does seem balanced.  I was just worried that it may not be worth the trouble.

**Comment by Kyle2143** [comment]
These seem good to me. Fun, items that are cosmetic or sidegrades from normal items is what the general consensus of job xp rewards are for and I think these fit.

**Review by Kyle2143 — APPROVED** [review]

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
Approved a bit too quick before reading everything. I'd remove the old mop and tsunami bottle. They are in the debris field janitor shuttle on the ground I believe.

**Review by Kyle2143 — APPROVED** [review]
This is good. Just need to resolve merge conflicts, then good to go.

**Comment by Carbadox** [comment]
the conflicts are resolved though? or am I not seeing something?

**Comment by Kyle2143** [comment]
I cant read apparently... I'll merge when I get home if someone doesn't beat me to it.

**Review by pali6 — CHANGES_REQUESTED** [review]
You seem to have accidentally reverted the ntso helmet sprite. Please fix.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
helmet

**Pull request closed without merging**
