### PR TITLE
Breaching charge sound and fx

### PR DESCRIPTION
**Pull request by flappybatpal**
[QOL][BALANCE]

## About the PR 
Adds an explosion effect and sound to breaching charges.
Gives NT breaching charges a long range explosion sound and screenshake to reflect it's power.
Increase the volume of the thermite charge.

https://user-images.githubusercontent.com/70909958/123425839-86f88780-d5ba-11eb-96b4-5e42aafc7110.mp4

## Why's this needed? 
Despite being a wall clearing explosive breaching charges were surprisingly subtle.
They now have a standard explosion and bang (not a loud, station shaking explosion).
NT Breaching charges will have a loud, station shaking explosion to reflect the fact these are heavy explosives.
Regular mining charges and hacked mining charges used for asteroid mining will act as normal, these already had a flashbang sound,

## Changelog

```changelog
(u)Flappybat
(+)Breaching charges now have an explosion effect and sound.
```

### CODE REVIEW

**Comment by Sovexe** [comment]
was thinking of doing something similar just yesterday actually

**Review by virvatuli-gh — COMMENTED** [review]
I'm not really a fan of the smaller and mining charges having that explosion effect. They're not large and it doesn't fit at all, the mining charges are concussion based and the explosion effect is a big fireball that's more fitting for something like a big BP bomb or a pod exploding. This is also why the effect was removed from grenades a long while back if I'm remembering right, it doesn't portray the actual damage/size of the explosion well. (This would be a great project for someone with some animation skills, making more different sized and looking explosion effects)

Looks and feels good on the big N7 charge though. Sound is an excellent idea too.

**Comment by flappybatpal** [comment]
TBH I didn't intend to change mining charges and would be fine leaving them unchanged but they inherit the after attack.

This is actually buggy because if you used hacked mining charges on an asteroid they produce incorrect flooring.

**Comment by flappybatpal** [comment]
Added a type check. Mining charges are now unaffected.
However they feel too sterile, noticed that they wouldn't go through their typical flasbang sound call and added it.
Think a close proximity screen shake would also be appropriate?

**Comment by flappybatpal** [comment]
Found a slightly smaller explosion (from yeet) for the standard charge.

**Review by Gannets — APPROVED** [review]

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
