### PR TITLE
Resprites the glacial abyss (icemoon caves)

### PR DESCRIPTION
**Pull request by TemThrush**
[Sprites]

## About the PR 
Resprites turf walls and floor found in the ice moon caves, I also added a few extra ice-floor turfs just for variety.

icemoon comparison
[Comparison, new sprites on the right]

image
[How it looks from a player view, VERY dark!]

Now to change the ice-lake and ice overlay 🥲

## Why's this needed? 
Requested in imspriter! Icemoon's sprites have been in need of an update for a long while now, especially the floors 😥

### CODE REVIEW

**Review by frawhst — APPROVED** [review]
sprited like a dark, fucked up version of the ice moon caverns... just a glimpse into your dark reality

**Comment by TemThrush** [comment]
> sprited like a dark, fucked up version of the ice moon caverns... just a glimpse into your dark reality

A full stare into my twisted perspective would make most simply go insane 😈

**Review by Gannets — APPROVED** [review]
This is like 100 times better

**Review by MyNameIsRomayne — APPROVED** [review]
Been following the sprite progress on the discord and this is so amazing i have to say

**Pull request merged**
