### PR TITLE
Replaces the baton in the "baton only" weapon vendor with a throwable one.

### PR DESCRIPTION
**Pull request by Wisemonster**
[BALANCE] [FEATURE] [GAME OBJECTS] [INPUT WANTED]

## About the PR 
Replaces the baton in the baton only loadout with a baton that can stun people when thrown (similar to the ntsc's).
Credit to Karma (Keiro) for the sprites.

Goonstation Development_ NCS Atlas 4_2_2023 8_29_38 PM

## Why's this needed? 
People in the discord seemed to think it would be nice if the baton only loadout served some kind of function other than a bad baton refill.

## Changelog 

```changelog
(u)Wisemonster, Karma (Keiro)
(*)Replaces the baton in the "baton only" loadout in the sec vendor with a baton that can stun people when thrown. (spritework by Karma(Keiro) on the Discord)
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Not a big fan of the batong. The baton only loadout is what it says - and gives you the extra utility token to compensate.

**Comment by M-Earthfire** [comment]
Givng every secoff a spreadless ranged weapon with spot-concentrated 130 stam damage and an up to 15 second stun duration sounds like a really bad idea.

**Comment by CheffieGithub** [comment]
will be worse than any taser option

**Comment by M-Earthfire** [comment]
But we are not talkin about point blank here. That's the point.

**Comment by CheffieGithub** [comment]
Any amount of stun and its pretty much over for you with 2 second cuffs and stacked stuns. Throws are much less reliable than tasers

**Comment by M-Earthfire** [comment]
Stun resist and stam regen in ranged combat is extremly important. Stun resist and stam recovery in melee is useless.

The throwable stun baton brings the problem of melee stun combat into ranged combat.

**Comment by CheffieGithub** [comment]
this seems more like an issue with stuns themselves than it being throwable. While your concerns about it potentially being too powerful are valid, there is big risk in using it to throwstun and I personally can't see it replacing a taser for most people since in most cases stun duration isn't an issue since you just run up and bonk them with the ~15 second taser burst/baton/taser shotgun and cuff. 
I would use this loadout sometimes if it was added but it won't beat the other options. Especially since the throwable baton hasn't got any extra throw range or speed and again the nature of throws themselves is very inconsistent.

**Pull request closed without merging**
