### PR TITLE
Touch nettle

### PR DESCRIPTION
**Pull request by vocalpocal**
[Hydroponics]

## About the PR 
This makes the stinging nettle's HYPspecial apply its reagents with TOUCH, rather than just straight up injecting them inside.
I also changed how much of the reagents are applied to mobs based on potency. I am not sure if it is a buff or nerf but at least I can now understand it 🦖

## Why's this needed? 
It allows some funny interactions, such as turmeric + nettle or useful healing with synth flesh. All in all it just makes more sense as nettles just brush over you. Nettles are not like jellyfish needles or snake fangs which actually inject you with stuff.

## Changelog 

```changelog
(u)Vocalpocal
(+)Stinging nettle now applies its associated reagents with TOUCH reactions.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
I mean nettles do have needles on the edges of the leaves, so it kind of makes sense for them to directly inject? Maybe they could do both if you want to be really mean.

**Comment by RelentlessGarbage** [comment]
I would agree that making nettles apply chems via TOUCH might allow for more interactions than they have now. However, nettles technically DO inject you with things in real life - they have tons of tiny silica hairs on their surface that break inside the skin and fill you with histamine and other stuff. It's not like poison ivy, where you're having an allergic reaction to the plant's surface oils.

**Comment by CheffieGithub** [comment]
why not both? maybe also make it trigger when walking over/getting attacked by the item versions if they don't already.

**Comment by colossusqw** [comment]
I have to say, i'm not a fan of this. As the person who made the originals, they were made to ignore the skinpen, as that would severely limit which chemicals you can even use with the nettles. Also irl nettles do have tiny needle-like structures that deliver the irritants under your skin.
I can see this being cool IF it injects the chemicals into you independent of skinpen, but otherwise it's a hard no from me.

**Comment by vocalpocal** [comment]
Sorry if I did not explain this well enough: Nettle is exactly the same, except chems with TOUCH effect also apply, so it is basically what a medical patch does. So you can still have ricin or whatever nettle, but you can also make turmeric clown nettle.

**Comment by CheffieGithub** [comment]
Another way to go about this is to just add a nettle mutation that does touch or touch/inject reactions. Like a nettle/ivy hybrid.

**Comment by colossusqw** [comment]
You've removed the ** 0.5 in the division by amount of associated reagents, i can't say i'm onboard with this considering this massively nerfs nettles.

**Comment by ZeWaka** [comment]
> You've removed the ** 0.5 in the division by amount of associated reagents, i can't say i'm onboard with this considering this massively nerfs nettles.

x

**Pull request closed without merging**
