### PR TITLE
Cogmap 2 Random Rooms

### PR DESCRIPTION
**Pull request by Sord213**
## About the PR 
Adds 6 3x3 rooms, 3 3x5 rooms, and 5 5x3 rooms to Cogmap2. Any special items that were displaced were moved nearby. This PR also turns the hidden chapel room into its own random room with a low spawn weight.

Screenshot_135
Screenshot_136
Screenshot_137
Screenshot_138
Screenshot_139
Screenshot_140
Screenshot_143

## Why's this needed? 
v a r i e t y

## Changelog

```changelog
(u)Pali and Sord
(+)Added randomized rooms to Cogmap2
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
No more medbay couch 😔

**Comment by Eagletanker** [comment]
Can you leave the chapel secret room?

**Comment by Eagletanker** [comment]
Also can you leave the disposals den? That’s a nice area to hang out in and is good for lurking

**Comment by arborinus** [comment]
To echo some sentiments that seem to be here, some distinctive rooms are being removed. In my opinion, these new rooms should lean towards filling empty space rather than be replacing areas, similar to the recent Kondaru changes.

Another note - is the photo camera in the owlery room moved somewhere nearby? IIRC it's the only place to get a camera on Cogmap 2.

**Comment by frawhst** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
> To echo some sentiments that seem to be here, some distinctive rooms are being removed. In my opinion, this new random room system should lean towards filling empty space rather than replacing areas, similar to the recent Kondaru changes.
> 
> Another note - is the photo camera in the owlery room moved somewhere nearby? IIRC it's the only place to get a camera on Cogmap 2.

^

**Comment by frawhst** [comment]
I'd like the disposals couch room to stay, other ones I don't mind

**Comment by flrsh** [comment]
Superseded by 6384f1afc6f03ae4b8ceb45f9b3e7fe7f1bf18dd.

**Pull request closed without merging**
