### PR TITLE
Station Floor Tile resprite

### PR DESCRIPTION
**Pull request by WALPVRGIS**
[SPRITES]

## About the PR 
I've been working on this on and off for a couple of months, and decided it was done enough for some feedback. :) This PR updates station floor tiles to fit more closely to our own spriting guidelines. It mostly just involves the kind of floor tiles that are 2x2 metal tiles like the basic station floors (not terrain etc), including some er, effect tiles like damaged/grimey. They're a bit more minimal compared to current floor tiles, but this is intended, as I tried to match the style used on station walls.

**Completed as of 13/10;**
- [x] Update floor tiles on Syndicate Battlecruiser decal turfs
- [x] Circuit tiles
- [x] Mars Outpost floor decal tiles (aka the outpost name tiles)
- [x] Diamond plate tile
- [x] Those weird tile decals that aren't actually turf tiles
- [x] Need to update stairs to match new tiles a little more closely
- [x] Not happy with the "Bar" and "Arcade" tiles, need more work
- [x] Meatstation Things
- Void tiles (animated) and other effect tiles, (Actually I'm going to work on these at a later date, ignore this being incomplete)

And some example screenshots, though this is probably the kind of thing that you would want to check out ingame;

image
image
image
image
image
image
image
image
image
image
image
circuit2

## Why's this needed? 
Current floor tiles look dated and do not match Goonstation's current spriting guidelines or art direction.

I figure this may be a subjective resprite, so wanted to get a draft up for people to check it out before I bother finishing it up, aha. :) 

## Changelog

```changelog
(u)Walpvrgis
(*)Station floor tiles have been resprited (and the floors available in the Floor and Wall Planner have been updated to match). Lemme know if you notice any weirdness with them!
```

### CODE REVIEW

**Comment by Flaborized** [comment]
These are pretty rad and would make the game look a lot better IMO ⭐

**Comment by Zonespace27** [comment]
Absolutely wonderful!

**Comment by Gannets** [comment]
A long needed update, good work!

**Comment by Mister-Moriarty** [comment]
They're resplendent! My only qualm is that I fear it may mess with some floor art in places, but otherwise a long awaited resprite.

**Comment by ZeWaka** [comment]
👁👄👁

**Comment by ZeWaka** [comment]
Love the damaged and circuit floors

**Pull request merged**
