### PR TITLE
Reduce chance of singularity engine on cogmap1 to 0.

### PR DESCRIPTION
**Pull request by pgmzeta**
[mapping][removal]
## About the PR 
Removes the random chance for singularity engines on cogmap1.

## Why's this needed? 
* It's difficult-to-impossible to push the cogmap1 singularity engine without destroying and irradiating the control room.

## Changelog 

```changelog
(u)glowbold
(*)Cogmap1 will no longer spawn the singularity engine by default. It can still be selected from the engine control computer.
```

### CODE REVIEW

**Review by TheTyrant25 — APPROVED** [review]
Could probably just delete the file too but this also works.

**Comment by pgmzeta** [comment]
It's possible to mitigate nuclear engine radiation with e.g. bohrum-glass windows, but this does not work for singularity radiation, which uses different logic. A feeder setup de-plates the outer engineering walls, meaning mechlab and the control room get mezzer stuns and radiation due to the line-of-sight.

**Comment by Glamurio** [comment]
I'm with Earthfire here. Making it easier to mitigate and creating gameplay variety is better than removing it.

**Comment by Sord213** [comment]
Yeah I'd rather see changes to how the radiation works if that's the issue than just removal outright. I like setting up the sing on cog1.

**Comment by pgmzeta** [comment]
will think on a hawking rad rework.

**Pull request closed without merging**
