### PR TITLE
End of hos locker

### PR DESCRIPTION
**Pull request by DimWhat**
[Mapping] [Sprites]

## About the PR 
Adds a new type of locker for busted command lockers and replaces the HoS locker in Z2 with a busted one containing very little.

## Why's this needed? 
People are consistently impersonating the HoS and rushing the place that has the original locker. It's happened on all servers and it's not very cool.

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
Nothing but shoes? That's just unreasonable, you gotta put at least *something* nice in there, otherwise it's just a bummer.
Might as well remove it completely then.

**Comment by alexeric123** [comment]
The shoes are the best reward.

**Comment by DimWhat** [comment]
> Nothing but shoes? That's just unreasonable, you gotta put at least _something_ nice in there, otherwise it's just a bummer.
> Might as well remove it completely then.

I mean that's kinda what I'm doing here. People always raid the locker of everything it has, except the brown shoes that are woefully left behind.

**Comment by zjdtmkhzt** [comment]
Shoes aren't really something though, just a joke.
I just think it's super lame to put in a locker like that in an HoS office and then not have any weapons or anything in it.
That'll feel terrible to people exploring the area.

**Comment by DimWhat** [comment]
If you recall what azone this is tied to I don't think weaponry is really what should be given to them.

**Comment by BenLubar** [comment]
I agree that it shouldn't contain HoS stuff, but it should contain *something* unique. Put an IOU in there.

**Comment by ZeWaka** [comment]
IOU!

**Comment by flappybatpal** [comment]
I've encountered this as sec and it was annoying because it's difficult for me to check if they have actually been at the HoS stuff due to access. They claimed it was from the zlevel and another sec backed them up

Turned out they were a traitor, lying and had actually been at the HoS stuff.

**Comment by Serrano9** [comment]
How about remove the cape, jacket, boots, radio, 
and maybe the uniforms too, but keep the rest. I'd still like for there to be a way to get an egun for the tougher azones since you can recharge it unlike other weapons from azones

**Comment by nefarious6th** [comment]
I would be more than happy to see this thing go. It's caused actual confusion and just sets bad standard. I can work on unique gear for it, including maybe a new gun, but I need time to work on spriting things and figuring out how to code something more balanced. I'd be happy to throw that in for Dim under this PR or a second one to follow, if this one just contains an IOU for now.

**Comment by DimWhat** [comment]
It now contains an IOU

**Comment by Boxlta** [comment]
Add 5 pairs  big stompy boots and this is a good PR

**Comment by zjdtmkhzt** [comment]
If we wanna have it usable for azones why not just put a laser gun in there in the meantime.
That's both rechargeable and has no issues with being able to be used as stun weaponry.

**Comment by DimWhat** [comment]
Cause the zone this comes from REALLY doesn't need another lethal weapon.

**Pull request merged**
