### PR TITLE
Cog1 TEG purge line tweaks

### LINKED ISSUE #3585: Unrobust Canisters and Hot Air
[BUG]

**Describe the bug**
Observing #2808, it seems like it did a good job on needing to rely less on the RCD. Though a new issue has arisen where canisters have the tendency of bursting. Not even canisters that have like a 200000°C mix in them but regular 20°C canisters (composing of any mix) just like to blow up when it's near hot pipes.

**To Reproduce**
1. Make a hot mix in some pipes (toxins or the engine room will work)
2. Put some canisters near the pipes.
3. ???
4. Burst

**Expected behavior**
For canisters to not burst

**Screenshots**
image
Obligatory screenshot 

**Additional context**
Pipes are funny, Tagging @Azrun

### PR DESCRIPTION
**Pull request by TTerc**
## About the PR 
This PR adds additional purge pipes, at the south side of the TEG room, moves the reactor statistics computer (so it's no longer above any pipes) and replaces the hot loop tables with transparent glass ones
Also, fixes one misplaced intercom and removes the platings from the purge vents. Hopefully it'll make them safer, since the plating won't emit as much heat anymore (hopefully?)

## Why's this needed? 
Right now you can only control the sauna loop gas pressure and it never occured to me that the engine has such a design flaw, until very recently when I was messing with the new burns. This change will basically let engineers control the outlet gas pressure easier, making the purge line much more useful and increasing the customizability of the engine setups.

Also fixes #3585 

## Changelog
```changelog
(u)TTerc
(+)Cog1: Added extra purge pumps to the TEG and moved the reactor statistics computer to the engine control room. 
```

### CODE REVIEW

**Comment by Azrun** [comment]
This change seems inconsistent with all the other TEG maps.  Atlas, Clarion (this has no pump though...), Cog2, Destiny, Horizon (uses a Volume Pump), and Kondaru all have a pump on the TEG Hotloop Inlet side (post-chamber) that allows for player control that is vented to space.

Only Cog1 and Horizon have an control over post Engine Outlet.  Cog1 was pre-passive gate and had no control over pressure.  Horizon has it post passive outlet, but there is after a volume pump.
**Horizon**
image


I think the addition of the pump is interesting as it gives players another lever to pull to control the system.  Removing the pump from the top is going to be a little goofy as opening the valve will equalize the pressure in those pipes over an additional ~50 segments of pipe.  _Technically_ engineering does have control the amount that is going to purged from that length of pipe but I'm not sure anyone would think to go out and mess with the volume pump...
image

...

Why remove the pumps leading to sauna?

>And, it upgrades the cog1 TEG to modern standards, since on other maps you usually can control the purge pipeline pressure.

What is being upgraded to "modern standards"?  That means of removing gas is only present in Horizon, but that feeds  to their pool.

Atlas valve is called "purge" 
Clarion valve is called "pressure release".
Cog2 valve is called "manual".
Clarion valve is called "purge" 
Destiny valve is called "pressure release"
Kondaru valve is called "manual".
☹️

**Comment by TTerc** [comment]
I admit I haven't really studied each and every map TEG setup when making this PR originally.

What prompted me to make this PR was several round of perfecting the pipeburn, when I realised it'd be really cool if you could actually control the amount of outlet gas you're venting,  as eventually you'll want to remove the excess gas. But the lack of pumps makes things kinda difficult, as you have little control over gas you're getting rid of

And the thought process happening in my head when writing the PR description was mostly referring to kondaru which actually has a similar feature, or at least it did, in my eyes: means to reduce the hot loop gas amount



As for sauna loop, the reason for removal was simple: nobody ever uses that thing and if someone does, it rarely ends well. But if you feel they should stay there, let me know. Everything in this PR I did was based on the ingame experience with the new burns, not actual mapping/coding/TEG theory based

**Comment by Azrun** [comment]
I think the addition of pumps to the post-TEG outlet/pre-Passive Gate is interesting and gives the greatest amount of control, especially in regards to mitigating pressure building up right there.  This will allow you to bleed off pressure.

I feel like removal of the "northern" pumps makes it inconsistent with other maps.

image

**Review by Azrun — CHANGES_REQUESTED** [review]
Return northern pumps and ensure they can be correctly identified from pump computer.

**Comment by TTerc** [comment]
Readded the northern pumps, moved the reactor statistics computer. Pump computer recognizes the new pumps, checked the different setups. Should be good now

**Review by Azrun — APPROVED** [review]
Looks good.

**Comment by Azrun** [comment]
Can you slap "Fixes #3585" in the description?  I feel this issue addresses only actionable aspects of that issue.

**Comment by pali6** [comment]
Do the south exhausts work properly even with the floor tiles removed?

I think this removes a bunch of powercells. Shouldn't they be moved somewhere? (Sorry if I missed that if they were.)

**Comment by TTerc** [comment]
Yes @pali6 
Other maps (Kondaru for example) don't have floor tiles under vents
As for powercells, they were simply moved to the south side of the room

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
