### PR TITLE
Resprites the Cake Hat

### PR DESCRIPTION
**Pull request by MitchTheUser**
[Clothing]

## About the PR 

Resprites the Cake Hat, and adds a snazzy candle flame animation to it's lit state. The cake now better matches it's worn sprite, and is now in 3/4th, while still keeping the original color scheme, general design, and cute blue plate underneath. The inhands have also been resprited and are in all 4 directions. The lit inhands are animated as well.

_Shoutout to Mr. Moriarty for being a big help in redesigning the cake hat from a overly realistic cake to a more compact, hat-like state, and for letting me use and improve on the sprite concept he made._

CakeHats

## Why's this needed? 

CakeHatHold

The current sprites are old and flat, and don't hold up to current spriting standards. This (hopefully) keeps the soul and style of the old cake hat while shifting to 3/4th and improving the colors, design, and flame. The inhands were also just as old, not appearing in some directions, and the lit inhand wasn't animated.

### CODE REVIEW

**Comment by Laboredih123** [comment]
SOULLLLLLLLLLLLL

**Comment by Retrino** [comment]
shading on new sprite seems more gradient-y than it should, would suggest working it a bit more

**Comment by MitchTheUser** [comment]
> shading on new sprite seems more gradient-y than it should, would suggest working it a bit more

Can see what you're saying, I based it on the worn sprite, which just had 3 layers of gray darkening as it went down, so I just translated the color scheme and design onto a modern cake.
cakeworn 
Personally I think it looks alright, since the gradient only looks weird if you look at it close up imo, which a lot of sprites suffer from.

**Comment by MitchTheUser** [comment]
> shading on new sprite seems more gradient-y than it should, would suggest working it a bit more

Updated sprites (and PR image) to incorporate the texture of actual cakes into the cake hat while still keeping the same color scheme, just more advanced and textured. Hopefully that makes the gradient less problematic.

**Comment by wolfolotl** [comment]
really busy new sprite with a lot of unnecessary low-contrast gradients to it, which makes it look kind of mushy. it clashes with the art direction the codebase is going for nowadays. and, on a purely personal level, I honestly think the current sprite is much more charismatic than this new one

**Comment by MitchTheUser** [comment]
Huge overhaul of the sprite, hopefully this should be a sweet new sprite that everyone likes
CakeHats

**Comment by MitchTheUser** [comment]
Last minute edition, resprited inhands in all 4 directions. The lit inhand is animated as well.

CakeHatHold

I can now say with confidence that this Pull Request is complete, barring any bugs or issues.

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by MitchTheUser** [comment]
Shit, wrong command, will fix in a sec

**Comment by MitchTheUser** [comment]
"Should" hopefully be fixed now, and merge conflict should be resolved as well.

**Pull request merged**
