### PR TITLE
Adds a new robotics category/organ, Augmentations!

### PR DESCRIPTION
**Pull request by Zonespace27**
[Balance] [Feature]
## About the PR
This PR adds a new type of organ for robotics to play around with, Augmentations.
Fundamentally, Augmentations are meant to be a risk/reward type system, with them giving an upside, along with some form of a downside.
They can be installed in a person by: Get them in surgery mode, use a saw on help intent on head, then use a scalpel on help intent on head, then install the module. To remove, follow the previous steps, except that you need to use surgical scissors after the saw + scalpelling.

Augmentations Added:
- Pain Reducer: The user gets a permanent -35 health deficiency adjustment, meaning they will take an extra 35 damage before starting to be slowed from pain. (Salicylic does -25, morphine -60) However, the cost is that the user is completely unaware of their own health, meaning the indicator in the top right gives no information on your health. On being destroyed, the health deficiency adjustment becomes +45, meaning the user will be as slow as if they had only 55 health remaining. In addition, the Pain Reducer reverses in pain levels as well, where now you have a chance to be paralyzed for a short time on taking damage, the chance scales with damage.
Can be produced at a robotics fabricator, cost is: 8 Cry-2, 5 Met-2, 5 Con-2, 3 Ins-1, 5 uqill.

- Stamina Enhancer: The user gets +200 maximum stamina, at the cost of -6 stamina regen and -20 max health. When destroyed, the stamina bonus is lost, and the now-faulty Augmentation thinks you're in the negative for stamina, continuously producing bath salts and methamphetamine endlessly, at the cost of your blood. Needless to say, it will be very lethal very quickly.
Can be produced at a robotics fabricator, cost is: 15 Cry-2, 5 Met-2, 5 Con-2, 8 Ins-1, 5 plasmastone.

- Wireless Interactor: The user gains the ability to interact with objects at range, akin to cyborgs. However, there are some caveats with this. They can only interact with objects, so no remotely attacking mobs, and items cannot be touched, so remotely picking up items won't work either. The downside of this augmentation is that, like borgs, The user gains a form of flash vulnerability. When flashed, you take 25 stamina damage regardless of if you're flash-proof or not, along with to any additional stamina damage/disorient from the flash itself. In addition, your ranged interaction abilities are disabled for 15 seconds after being flashed, and finally, the augment takes 10 damage each time it's flashed. On breaking, the ranged touch is disabled, the flash stamina damage is upped to 40, and nanomachines are leaked into the user at 0.5u / life cycle.
Can be produced at a robotics fabricator, cost is: 8 Cry-2, 5 Met-2, 5 Con-2, 3 Ins-1, 10 telecrystal.

- Surgery Assistant: The user gains a slightly better version of the Medical Training trait for surgery, in addition to having an Organ Ability allowing them to get a guide to any surgery. The guide will tell someone the steps to remove whatever organ they chose, waiting for them to complete the current step before giving them the next. All in all, this is meant to be a good Augment for doctors, and especially new ones. The downside of this Augment is that you are completely unable of doing self surgery (suturing excluded). When the Augment is destroyed, you will also be unable to do surgery with less-than capable tools (glass shard instead of scalpel, plastic fork instead of saw, and so on).
Can be produced at a robotics fabricator, cost is: 7 Cry-1, 5 Met-2, 5 Con-2, 3 Ins-1, 5 cobryl.

- Neural Jack: Traitor roboticist 7 TC item. The user gets a pile of buffs and abilities, as detailed below. (Absolutely not a Matrix reference)
   - Passive: You can parry attacks while blocking, meaning that the attacker will be shoved to the ground with 4 seconds of knockdown. The odds of a parry happening start at 20% per attack (an extra 10% is added for unarmed attacks), and increases by 7.5% for each attack not parried while blocking. The parry chance decays at 2.5% per life loop, and is reset to 20% on a successful parry.
   - Passive: You have a better version of Matrix Flopout, giving you 0.5 seconds of bullet dodging when flipping at a 12.5 stamina cost.
   - Passive: Your kicks do an extra 2 damage.
   - Passive: You gain an extra 50 stamina, and +5 stamina regen. (Iffy about this one, but testing shows that you lose most of your stamina pretty quickly)
   - Ability: You can execute powerful "combo" attacks based on what intents you attack someone with. The "combo" list decays after 10 seconds, or a switch of targets.
      - Heavy Punch: Grab -> Harm, send someone back 3 tiles, dealing around 15 brute damage, and stunning them for 2 seconds.
      - Leg Sweep: Grab -> Disarm -> Harm, knock a person onto the ground for 7 seconds, then staggering them for 4 seconds once they get up.
      - Rapid Kick: Harm -> Harm -> Disarm -> Disarm, kick a person 4 times for 12 damage per kick, before applying a 2 second stun.
      -  Fling Pin: Grab -> Grab -> Disarm -> Harm, you and the target go 3 tiles in the direction you were hitting them, before the user instantly locks them in a pin.
      The above 4, along with a way to enable/disable combos, are in a pair of organ abilities attached to the Neural Jack.
      On being destroyed (The Neural Jack only takes 10 damage from EMPs), the combo abilities and parrying are disabled, the stamina boosts are removed, and the Neural Jack will leak 2 welding fuel, 2 lithium, and 2 uranium per life loop into the body, in addition to any further EMPs adding an extra 10 of each.

## Why's this needed? 
It'd be nice for robotics to have more voluntary organs they can shove into people, possibly giving them some business once in a while. In addition, it provides yet another sink for materials, requiring cooperation from mining, especially on the front of getting electrum. Also, it gives the player some agency in how they want to modify their character, if at all, unlike regular (cyber)organs.

## Changelog

```changelog
(u)Zonespace
(*)Added a new kind of modification, found at robotics fabricators, Augmentations! More details in minor changes.
(+)Augmentations are a "risk/reward" kind of deal, with a tradeoff.
(+)Pain Reducer Augmentation: Move at a more regular pace while damaged, at the cost of accumulating brain damage.
(+)Stamina Storage Augmentation: Double the max stamina, at the cost of -6 stamina regen and -35 max health.
(+)Wireless Interaction Augmentation: You can interact with objects at range, at the cost of flash vulnerability.
(+)Surgery Assistant Augmentation: You have a better version of Medical Training, and you have a built-in guide to all surgeries.
(+)Neural Jack Augmentation: 7 TC traitor roboticist item, gives you increased martial prowess in the form of powerful Combo attacks.
```

### CODE REVIEW

**Comment by vocalpocal** [comment]
Looks very cool! Love content like this. Enhancement is an alright name, but would an "augmentation" be a better term? I am not sure if this steps on geneticist toes too much

**Comment by alexeric123** [comment]
Just wondering, are they able to be removed after emp'ed/destroyed, and are you able to have multiple at once?

**Comment by Zonespace27** [comment]
> Just wondering, are they able to be removed after emp'ed/destroyed, and are you able to have multiple at once?
> 
> +1 to the augmentation rename, as enhancement implies only good effects, at least to me.

Yes, and no.

**Comment by Flaborized** [comment]
Independent of the feature itself, not a big fan of the sprites used for these, especially as they're pretty minimally modified headset sprites. Strikes me as something that would add spriting work later if somebody decides to improve them, and also doesn't set a good base for if people code new augments down the line. 

Related to the feature: I think the brain damage negative of the pain reducer implant is almost completely negatable by taking a few mannitol pills, but is otherwise very deadly. This makes for a poor balance imo where you either negate the effect entirely by taking a bunch of mannitol pills or get punished disproportionately hard and maybe die for... not doing that.

**Comment by Crackaduck** [comment]
love it, goon roboticists need more, while its not mechs like TG codebases have, its certainly unique and looks fun

**Comment by Supermichael777** [comment]
are these toggles? its not clear.  These seem somewhat appropriate downsides for toggled stuff, but way to extreme for long term implants.

Stun Resist: if its always on that 10% is going to make you trip annoyingly often. Its still going to happen annoyingly often on a toggle but hey thats what you get for power-gaming.

pain reducer:  hiding how much damage you've taken seems thematic, and I would cap the brain damage (unless its toggled) because dying in ~3 minutes is kinda harsh while being fully mitigable by easily acquirable supplies.  I would change the downside to zero health awareness, overriding the health implant for the user.

Stamina Enhancer:  Commit die the item.  The concept probably needs a total rework if its not toggled.  Putting this in someone is basically assault.  If its on a toggle seems totally fine, the kind of thing you turn off if you expect to fight.
  
Traitor one seems fine for traitor gear that has hard to see/remove effects.  price is in line with other primary gimmick gear

**Comment by ThatFiveGuys** [comment]
Overall this idea is really cool and I like it, however Im concerned about a few of these being too underpowered. Considering how costy these things are these should be overall decently powerful. Take pain reducer for example, it has a pretty severe downside for its minor upside. Overdosing on saly acid v mild tox, with a cyberappendix this tox will now be constantly healed with no need for input (Also you still get other heals from saly and cyberappendix). Now, compare this to pain reducer, its arguably only slightly better then oding on saly acid and far more of a pain in the ass to manage with needing to constantly take mannitol. Stun reduction seems a little bit harsh with being tripped (considering you drop your items), probably would be best as a flat out stun.  Neutral Jack seems fairly weak compared to alternative 7 TC items, 4 hits with a katana will turn you into a nugget, 4 hits with a c saber will give you over 200 damage, 4 hits with a neutral jack will do at most 48 damage. Either reduce the price (concern here is that being paired with wrestler belt) or buff it. Only one that's in a fine place to me is Stamina enhancer, its a fairly strong one with a fairly big downside.

**Comment by Zonespace27** [comment]
https://forum.ss13.co/showthread.php?tid=17007

**Comment by Tarmunora** [comment]
I'll get around to reviewing this in a bit probably

**Comment by Zonespace27** [comment]
Update:
Additions:
- Wireless Interaction Augmentation, allows you to interact with non-item objects at range. See more in the body of the PR
Changes:
- Pain Reducer Augmentation, on being destroyed, now amplify pain in the user, adding a chance for them to get temporarily paralyzed on taking damage, scaling % chance with the amount taken
To Do:
- Mess with the stun resist augmentation's downside, will get done sooner or later
- Unregister a signal, I'll fix it in maybe 10 minutes

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
I mentioned this in discord, but the surgery steps could do with changing. Intent based surgery is something we'd prefer to not add to, especially where one step requires harm intent which doesn't really make sense here since it is not a really "harmful" surgery like heart removal or **** removal.

Surgery is rather arbitrary, but that's all the more reason to try to make the steps be intuitive if we can.

**Review by Tarmunora — CHANGES_REQUESTED** [review]
High-level stuff for now, not going too much into the code in detail:
Conceptually, I think the only one in here I think I'd consider would be the wireless interaction one.
The surgical assistant one seems very... messy to me - the concept of a ~~neuromod~~ augmentation to take the place of a job-based trait bonus is interesting, but I think that as it's presented, I'm not a huge fan

Re pain reducer, stamina storage:
As others have said, both of these are essentially combat bonus/tradeoffs, Very lukewarm to it

Re Neural Jack:
Looks like it's trying to be a surgically grafted wrestlebelt+, and again, I'm pretty lukewarm to the concept

**Review by flrsh — CHANGES_REQUESTED** [review]
I think you should PR these augments one at a time for more in-depth discussion and workshopping.

**Comment by Zonespace27** [comment]
Closed for PR Atomization -
I will be PRing them one at a time.

**Pull request closed without merging**
