### PR TITLE
Changes morphine to only KO on overdose + stam tweaks

### PR DESCRIPTION
**Pull request by colossusqw**
[LABEL][chemistry][balance]
## About the PR 
This PR changes morphine to only KO on overdose.

## Why's this needed? 
This keeps the dose of morphine that will cause tou to fall unconcious the same(close to 15 units), while making low dosage use relatively safer.

In effect, this differentiates morphine from more KO oriented downer chemicals such as Ether and Capulettium, and puts emphasys on it's painkiller usage.

It's now more effective and efficient to use in no KO surgery, once it's buffs are applied independent of the patient being knocked out or not, and can be used as a first option pain reducer for twice as long without making the user fall unconscious.

```changelog
(u)Hans
(+)Made it so morphine's adverse effects only happen on overdose, reduced it's stamina regeneration debuff from 3 to 2.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
would this then also require less morphine technically to deplete stims (since slower depletion of morphine?)
Not that I feel it's a major balance factor, just making sure I'm understanding yhe effects of this in full

**Comment by colossusqw** [comment]
> would this then also require less morphine technically to deplete stims (since slower depletion of morphine?) Not that I feel it's a major balance factor, just making sure I'm understanding the effects of this in full

Oh yeah, i could change how much it depletes but all chems deplete SO MUCH stims that it's pretty much game over in seconds with them, generally what matters most is speed since 5 us of morphine would pretty much delete all the stims in you.

**Comment by wolfolotl** [comment]
kind of against this, mostly because it makes the sec morphine injectors harder to use as a tranq for The Squirmy Ones. not many strong feelings either way though

**Comment by colossusqw** [comment]
> kind of against this, mostly because it makes the sec morphine injectors harder to use as a tranq for The Squirmy Ones. not many strong feelings either way though
> 
> I also think it's kinda Ehh to make it less efficient than ether, which itself is kinda notably inefficient. I think a buff to how fast ether works would be cool but I also don't get into many of the situations where these chems are juiced to their fullest deadly potential

Oh, the thing with ether and morphine is
A- they are almost the same
B- they're plain worse at KOing than capu

This i feel is a buff to morphine in small doses if anything, it's way more efficient for when you just got shot and need to get away/stay in a fight(like a painkiller would be). I'm also not sure the intended use of morphine auto injectors is to KO people, they seem to be propped up as a combat scenario drug to keep you going.

**Comment by RelentlessGarbage** [comment]
I'd actually be for this. Morphine has always seemed to me to be meant more as a utility chem rather than a knockout chem - something you can take in an emergency if you have to limp away from a newly-formed hull breach or to conduct emergency surgery on yourself. Going unconscious and getting a stamina penalty has always seemed like an unfortunate side-effect/balancing measure.

I also don't see anyone using ether, so making it more distinct from morphine might have it see more usage. On the topic of the morphine auto-injectors, maybe give sec a bottle or two of ether plus a dart pistol (or some other administration method) if you want them to give them a way to deal with crazed lunatics that doesn't require armory authorization. In either case, morphine auto-injectors are never going to be as effective as tasers in terms of stunning and rendering people unconscious.

**Comment by TDHooligan** [comment]
happy if you just increased the knockout time. the doubled depletion time just makes overdoses 2x as painful. 
it would probably help if security's morphine syringes got changed to a split of morphine and ether injectors, as right now they're just bad at both jobs (knocks you out so pain res is too risky/ doesn't knock bad men out in time to be useful)

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
