### PR TITLE
Cog1 Medsci Lobby Overhaul

### PR DESCRIPTION
**Pull request by Nexusuxen**
## About the PR 

This PR significantly reworks the Medical Waiting Room, Chemistry, and Robot Depot, with minor tweaks to surrounding areas.

I'm very eager to hear feedback, particularly regarding anything people think needs changing/adding/removing. I'm not completely satisfied with this, but I'm unsure where to go from here, and I still think this is complete enough to be merged at the time of writing this, but I definitely want to improve these changes as much as I can.

General preview of main changes in-game (Map editor views for each major room change further below)
image
Note: There may be a couple minor oversights like a floating light present in the images presented. Feel free to say any that you see in the images regardless, though I'll make note of any fixes in commits, and try to keep the above preview updated!

**Additions:**
A new section of maintenance between Medical and Science and the Main Hall, including 2 air hookups to Chemistry and the Science Lobby (no other rooms are connected to these new air hookups). Includes Science access to the maintenance doors.
A single regular GuardBuddy to the Robot Depot

**Removals:**
Empty space between Med and Sci
Thindows from Medical Reception
Large sections of the Robot Depot, including 1 of the 8 existing robuddy docks in the Depot, and the tank dispenser

**Notable Changes:**
Chemistry's layout has been moderately reworked, now including a reception area for interfacing with the public via the Medical Waiting Room. No new Chem Dispensers have been added; however, one has been moved to this reception desk, as well as the addition of 1 new ChemMaster and 1 new Reagent Heater. The positioning of this is to encourage scientists to interact with people while they sit right at the front desk. An office supply cabinet has also been added for \~roleplay purposes~. A beaker cabinet has been added to Chemistry as well. Additionally, the ValuChimp has been moved to the Testing Chamber, and in its place, an air scrubber has been added to Chemistry. The monkey spawn in Chemistry has also been moved to ~inside the shower cubby in Chemistry, with said shower door now requiring Science access.~ As of Commit 6957083, the monkey has been moved to the Medsci router, and the windoor no longer has access requirements (it kept turning on the shower which leaked under the thindows and made constant gurgling noises from the drain) - the monkey will no longer make an absolute fucking mess of Chemistry within minutes. Finally, the Reagent Extractor has been moved to the bottom left of Chemistry. Minor tweaks may be unlisted here. See below:
image

The Medical Waiting Room has been adjusted significantly to fit the new air hookups while attempting to maintain a semblance of aesthetics. It now has access to Chemistry's new front desk, allowing the public to (possibly in vain) request chems from Chemistry (may facilitate illicit sale of narcotics). Additionally, a plasmaglass window separates the waiting room from the Science Lobby, allowing the public to ~~point and laugh at the nerds~~ look at the scientists and see what they're up to. Note: The coffee vending machine stress testing system previously in place is still present; please enter the Gene Booth from the right side to avoid participating in this test. See below:
image

Medical Reception has been tweaked slightly, moving the computer, removing a doctor spawn and chair, moving the telephone and intercom slightly, and reworking the health status screens to be interactable by people manning the front desk, rather than having to walk South a little. The Lobby desk has been squished down from 2 tiles tall to 1 tile tall; the storage area and break room below were also moved down by 1 tile.
image

The Robot Depot has received significant budget cuts, and as such has been confined to a more reasonable size. It now only includes 7 docking ports instead of the previous 8, and no longer contains a tank dispenser, but also includes a new regular GuardBuddy. It is also significantly smaller, and its layout has been significantly adjusted, shoving the 4 signallers in the room into the storage crate. No further objects or features were removed, nor added. See the image for the Air Hookups room, as it includes the robot depot.

Research now is fitted with an Air Hookups maintenance room, complete with an air reserve tank, spare high pressure air canister, space HVAC, firefighting closet, and wrench. Atmospheric system follows standard set by the rest of the map: The Air Reserve is connected via valve to the pipe segment including the canister port, and said segment is connected to the air injection pipes via a valve. Scientists may access all 3 doors in this new area. However, the area has not been cleaned in a while. See below:
image

The Science Lobby has finally moved its scanner from the dirty floor onto a slightly less dirty table. Additionally, management has seen fit to install a new DWAINE terminal, as there were previously only 2 terminals in the entirety of the department, excluding the Research Director's office. There is also a table with a box of blank data disks, a wireless card, and a wired network card. (The addition of this is also largely intended to make it more difficult to screwdriver+crowbar your way into Science from the waiting room.) See below:
image

Pathology has been slightly compressed, as a moderately sized chunk of Medbay had to be moved downwards to make room for the new lobby. No additions or removals have been made to Pathology, but it is slightly more claustrophobic now. See below:
image

**Other changes:**
The Chemistry and Telescience blast doors have been adjusted to have their blast door layers be above everything else on their tile (unfortunately the firelock spawners seem to automatically layer themselves on top of the blast doors, however), instead of being weird and ugly and leaving tables and windows visible above them when closed.

The Medbay Reception mail pipe has been adjusted in 6957083 to go through the lobby and waiting room instead of under a wall.

A good chunk of lights in the surrounding area have been adjusted to match perspective.

## Why's this needed? 

Reducing the isolation of Chemistry and Science in general from the rest of the station, by making large sections of Science visible from a public area, and more importantly, adding a way for scientists to directly interact with the public without having to crawl out of their lab.

Additionally, Science and Chemistry tend to get breached **a lot**, and as such an air hookup helps to alleviate this issue. Recent atmos optimizations also give room for some more atmos systems to be present.

Finally, there are very few areas in the MedSci region without camera coverage - it is very difficult to even temporarily hide from the AI while in MedSci. This helps to resolve that missing niche. After testing, I have confirmed that camera coverage in the surrounding areas is perfectly fine, but you cannot see into this new maintenance area at all, even if you open the door. (Beepsky now favors this route in his patrols when leaving Research, instead of going through the front door, so the AI will still occasionally be able to glimpse into the area if they time it right)

## Changelog

```changelog
(u)Nexusuxen
(*)Significant changes to parts of MedSci on Cogmap1. Chemistry now has a front desk in the Medical Waiting Room, and an air hookup room has been installed for Science.
```

### CODE REVIEW

**Comment by pali6** [comment]
Overall I like this, especially the chemistry desk. Can non-scientists enter the new maintenance through the public doors? (They should be able to.)

**Comment by Nexusuxen** [comment]
Maint access spawners & several tweaks/improvements added; see Commit 6957083 for more details.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
Did a comprehensive review, only one note:
* I really think the robot depot should have more terminals - I have seen them fill up. You could move the air hookup port to be in the hallway to get at least one more.

**Comment by Nexusuxen** [comment]
> You could move the air hookup port to be in the hallway to get at least one more.

Got it! I'll see what I can do in regards to that, if I can't find another way to make room

**Review by ZeWaka — APPROVED** [review]

**Comment by pali6** [comment]
I personally feel like these floor markers could go as they aren't used elsewhere on the map and arguably not look that great currently:
image
I can't quite tell from the mapdiff view - does the chemistry desk have thindoors / windoors on the outside? (It should have them.)

**Comment by Nexusuxen** [comment]
> I personally feel like these floor markers could go as they aren't used elsewhere on the map and arguably not look that great currently: image I can't quite tell from the mapdiff view - does the chemistry desk have thindoors / windoors on the outside? (It should have them.)

That seems reasonable, sure!

And yes, the tables do have windoors on the North edge of them; specifically with Chemistry access spawners

**Review by flrsh — CHANGES_REQUESTED** [review]
* Please don't add more thindows
* The shape of chemistry is pretty weird; I get wanting to give them a public facing desk, but consider smushing that area down by one tile
* Sliding glass windows are meant to go on top of tables; please replace them with actual airlocks
* Please remove the two windows between the nanomed and chemistry and the plasma reinforced windows between the research lobby and the medbay waiting room; they're not super necessary and would just make breaches and breaking in earlier

**Comment by Nexusuxen** [comment]
- I replaced the existing Medical front desk thindows with regular windows, though if you're referring to the thindoors, I did genuinely try to use the updated ones; however, their North-facing sprites look kinda awful on a desk (why does it obscure the desk??) and makes it impossible to use. If you're set on this I can change it to them but I personally don't think it'd look or feel great, unless the sprites were fixed.
- Not crazy about that but it seems reasonable, I'll see what I can do. Would also give the lobby a more interesting shape, hopefully.
- Also yeah good point, will swap those out now.
- I can remove the ones between the two desks, especially when I squish the lab down a bit. However, the plasmaglass windows were intended to make Sci less hidden from public view - I personally greatly prefer maps with more open feels to them - so I'd be reluctant to remove them. I preemptively designed it to make it difficult to break into through; you'd have to disassemble one or two things on top of the windows, or just two windows, which are electrified (though honestly plasmaglass should NOT be as trivial as it is to get through). I can probably move things around and add stuff - namely moving the chair to the northwest and making the terminal face west, and add another table or something to the empty space - to further reinforce the area against breaking and entering. As a note regarding breaches, the lobby is sealed from the rest of medbay via glass & airlocks, so it being breached isn't as much of a concern, but yeah, still not a non-issue.

I'd appreciate some more feedback regarding some of the requested changes I have pushback against, but again if there's no further input requesting otherwise then I'll make the rest of the changes.

**Comment by Nexusuxen** [comment]
I have not been maintaining this due to the combination of:
- Semi-frequent updates to Cog1 requiring consistent merge conflict resolution
- Lack of response to requested re-reviews and lack of further reviews

I am still interested in keeping this open, so I'll try to resolve the merge conflicts later today to avoid the conflicts becoming too severe.

**Comment by Nexusuxen** [comment]
> 
> I assume these changes were never made?

They were not, as I was awaiting a response from Flourish. Admittedly though I did forget to remove some of the excess windows. I'll get that done later today.

**Comment by TTerc** [comment]
!merge_upstream

**Review by TTerc — DISMISSED** [review]

**Comment by virvatuli-gh** [comment]
This is being closed as part of some PR spring cleaning. Feel free to remake this PR if you ever feel like finishing it.

**Pull request closed without merging**
