### PR TITLE
allow all canisters to spawn empty

### PR DESCRIPTION
**Pull request by TheTyrant25**
[QOL] [MAPPING] [INTERNAL]
## About the PR
Adds a new var to each canister which lets it start empty.
## Why's this needed?
When mapping azones, it was previously not possible to spawn in plasma canisters or any other kind that were empty, as the gas contents are set in `New()`. This new var lets you start them off empty for derelict areas and such.

### CODE REVIEW

**Comment by BatElite** [comment]
If we're talking azones, isn't it just as easy to varedit a regular blank canister rather than do all this?

**Review by Azrun — COMMENTED** [review]
Consider use of `src.air_contents.vacuum()`

**Comment by TheTyrant25** [comment]
> If we're talking azones, isn't it just as easy to varedit a regular blank canister rather than do all this?

nope, it isn't, because the contents get overwritten in New() to be full.

**Comment by TheTyrant25** [comment]
> Consider use of `src.air_contents.vacuum()`

will do

**Comment by BatElite** [comment]
> nope, it isn't, because the contents get overwritten in New() to be full.

No I mean, you take a `/obj/machinery/portable_atmospherics/canister/empty` and you change the name, icon_state, casecolor

**Review by Tarmunora — APPROVED** [review]
I do wonder if a more general solution would be better, e.g.: `var/spawn_filled = TRUE` (and associated handling in `New()`) on the canister parent, letting mapmakers spawn any canister as empty with a single var override

**Comment by TheTyrant25** [comment]
yeah that was an odd choice by me. Changed it to use a var instead: `isempty`

**Comment by ZeWaka** [comment]
You don't need to vacuum if there's no contents...

**Comment by TheTyrant25** [comment]
i wasn't sure, played it safe. I'll remove that line then

**Pull request merged**
