### PR TITLE
Cable Network Colour Coding

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [SYSTEMS] [QOL]
## About the PR 
So the cables that connect the TEG to the SMES units on cogmap 1 are brown, while the rest are red, and having some snazzy yellow solar cables. Donut2 does a similar thing with the brown, plus black cables leading to the PTL.

This PR applies this colour scheme to almost every other (in rotation) map, for consistency and style reasons:
- Brown for engine connections
- Black for PTL cabling
- yellow on solars
- orange on nadir's nuclear engine because kubius said so
- red everywhere else

Oshan is not included, though, as they have their reinforced cables for undersea hotspot thingys.
## Why's this needed? 
Lets you see at a glance which cable network is which. Plus, it's weird that only two maps have it that way, might as well.

## IN ADDITION
I have removed every instance of d1 and d2 usage in every cable across the rotation maps. The regex used is in the conversation, and it's quite handy.
## Changelog 
```changelog
(u)Tyrant
(+)Engine room cables are now brown, solar cabling is now all in a consistent yellow, and PTL cables are black across all maps.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
why not yellow 🥺

**Comment by TheTyrant25** [comment]
because i would have to start over 🥺

**Comment by TheTyrant25** [comment]
hollup why is workflow failing
this is a purely mapping change

**Comment by TheTyrant25** [comment]
nvm

**Comment by TheTyrant25** [comment]
[CONTROVERSIAL] alert: in the interest of having separate yellow cabling networks, donut3 now has SMES units plus fully connected solars. Donut2 similarly has connected up solars.

**Comment by Azrun** [comment]
If personally prefer that the be atomized!  Color change is easier to evaluate.  The value and need of the SMES change feels quite different.

**Comment by Azrun** [comment]
What is the benefit of being able to differentiate between the PTL cable and the high power (brown cables)? It is going to be tied to the high powered generator side.

**Comment by Sord213** [comment]
My personal reasoning on donut 2's wiring was I wanted the wire to be different leading to PTL so I made it black. Then I was like "hmm, I should make the engine wire colors different" so I made them brown. Using black or brown for all high-power would be fine, or keep them separate. Could say the black is for high-power out of engineering, or whatever. I do not care either way. *shrug

**Comment by TheTyrant25** [comment]
the difference for the black PTL cables is that it looks nice

**Comment by TheTyrant25** [comment]
merge conflict :(

**Comment by TheTyrant25** [comment]
we are once again ready for review

**Comment by Azrun** [comment]
Wasn't there an effort to remove direct assignment of d1 and d2? Also why not use #11962?

**Comment by TheTyrant25** [comment]
Should I make clarion's nuke engine vables orange as well? colour coding by engine type?

**Comment by TheTyrant25** [comment]
> Wasn't there an effort to remove direct assignment of d1 and d2? Also why not use #11962?

Didn't use cable spawners because they look kinda ugly on the mapping view in strongdmm. They also don't really preserve some of the diagonal cable art and generally go for 90 degree angles. And I know for a fact that a part of the code matches d1 and d2 to the iconstate but I forgot avout it :P

**Comment by TheTyrant25** [comment]
Current Overview
- All solars are connected with yellow networks, all engines (apart from nadir nuclear engine, which has orange, and oshan reinforced cables) have brown cabling, and maps with PTLs have the PTL transmission cables in black.
- Donut3 solars no longer have SMES units, the yellow cables simply connect directly to the red.
- Nadir has had its melty update, and merge conflict in that area has been resolved.
- Cable spawners are not being used despite the fact that it would have made it significantly easier, simply because i forgot they were merged

**Comment by Azrun** [comment]
> And I know for a fact that a part of the code matches d1 and d2 to the iconstate of a cable but I simply forgot about it :P

Are you planning on removing the instances where d1 and d2 now appear to explicitly set?

**Comment by TheTyrant25** [comment]
> > And I know for a fact that a part of the code matches d1 and d2 to the iconstate of a cable but I simply forgot about it :P
> 
> Are you planning on removing the instances where d1 and d2 now appear to explicitly set?

Does it have a significant impact? Will it break if they're left in? If so, I'm happy to, but otherwise not really. I've seen a couple of examples of odd leftover varediting in other maps and they seem to work just fine.

**Comment by TheTyrant25** [comment]
ah bloody gell donut2 is merge conflicting i'll fix that in a bit

**Comment by TheTyrant25** [comment]
From what I can tell, only the brown cables have the d1 and d2 set, the yellows simply use the icon and rely on the code to change their directions later. A lot of maps have certain red cables popping up with d1 and d2 though, which you can see by scrolling through the prefabs in strongdmm.
I don't think it's really a huge issue, seeing as there's so many red ones like that, but if you like, I can systemically go through each map and eliminated all of the oddly var edited cables in an atomized pr.
Also, in hindsight, cable spawners directly assign d1 and d2 I think. The `New()` of the cables should assign them anyway though, so it's a little pointless.

**Comment by TheTyrant25** [comment]
on second thought lets remove em lol

**Comment by TheTyrant25** [comment]
Because I am an utter lunatic, I'm going to go through EVERY cable in every map and fix the d1 d2 thingys.
Yes it is scope creep, i do not care, it's the most efficient way (i'm using ctrl f)

**Comment by TheTyrant25** [comment]
i've done atlas so far
if this merges before im done doing the d1 d2 things (which is perfectly okay), i'll throw it in a new pr

**Comment by TheTyrant25** [comment]
find using regex `/(\/obj\/cable(\/.*)?\{\n\t)((d1)|(d2))/` has saved my life, i no longer have to check all 3000 cables manually. Now i only have to edit around 200 cables per map.

**Comment by TheTyrant25** [comment]
cogmap2 has 2413 faulty cables, I'm going to do some vigorous regex replacements, possibly using a variant of `(\/obj\/cable(\/.*)?\{\n\t)(((icon_state \= \"\d-\d\d?\")|(d1 \= \d\d?)|(d2 \= \d\d?)|(dir \= \d))\;?\n\t)*\}`

**Comment by TheTyrant25** [comment]
got a winner:
`(\/obj\/cable(\/.*)?\{\n\t)(((d1 \= \d\d?)|(d2 \= \d\d?)|(dir \= \d))\;?\n\t)*(icon_state \= \"\d-\d\d?\"\;?\n\t)(((d1 \= \d\d?)|(d2 \= \d\d?)|(dir \= \d))\;?\n\t)*\}` to match each cable
then `$1$8}` as the result

**Comment by Azrun** [comment]
image
Odd knot on Cog2

**Review by Azrun — CHANGES_REQUESTED** [review]
Concerns listed previously.

**Comment by TheTyrant25** [comment]
that should be everything i think

**Review by Azrun — APPROVED** [review]

**Pull request merged**
