### PR TITLE
Enable motives on Goon2

### PR DESCRIPTION
**Pull request by binarysudoku**
## About the PR

Might be controversial, but this PR adds motives like hunger to Goon2

## Why's this needed?

Currently there's really not much point in the kitchen or bartender, meaning they mostly just serve to provide reskinned floorpills for the station; enabling motives (or at the very least hunger, like other L/MRP servers) would give people more of a reason to interact with eachother (ie getting food or phoning the kitchen to demand food deliveries to their department)

### CODE REVIEW

**Comment by polivilas** [comment]
Disagree - I don't want to deal with yet another bar that only really comes into use when the station is already blown up to fuck and beyond.

**Comment by Gannets** [comment]
I personally always liked the idea of the hunger motive on #2, to encourage interaction with the catering staff. But this requires more community discussion before it can be considered.

**Comment by Carbadox** [comment]
Motives would be fine but not as a direct port from the RP server. Adjust the values so that they're not essential to survival and I think it would be fine. Though I think maybe a rework of the UI for motives would be needed, its a bit big and wasn't that bad for RP since everything is alot slower there so screenspace isnt that big of an issue.

**Comment by trerri** [comment]
Seems legit but only add food motive. Not the others, I don't wanna die because I didn't waste time unconscious.
As long as it doesn't megakill you on the spot and it actually slightly incapacitates you before running out it's good.

**Comment by trerri** [comment]
make it kinda like minecraft is my final verdict

**Comment by binarysudoku** [comment]
Will adjust to enable only hunger on goon2 when I have lunchtime

**Comment by Flaborized** [comment]
I think that a hunger motive would be more likely to lead to people using vending machines or some other means (space diner kitchen maybe?) to satiate the motive rather than using the chef, because the chef is always allowed to make food that Kills You. Even without the Floorpills Rule in place hypothetically, it'd be much much more dangerous to eat from the kitchen with traitor chefs. Think Syndicate Sauce. 

I'd rather food give more substantial buffs that "felt more important". Currently food is actually sleeper amazing but the effects are mostly number changes. Gaining more max health or stamina is _strong_ but it's a sorta unnoticeable numbers buff. I'd like more stuff like how spicy chili can make you burp fire, carrots can make you see further in the dark and beans let you propel yourself with farts in space. It's more work, but it'd lead to a much more engaging catering department IMO.

**Comment by AwkwardDryad** [comment]
I'm ok with a modified and less ouchies form of motives on goon 2 :)

**Pull request closed without merging**
