### PR TITLE
Construction progress bars & Engineering Training trait

### PR DESCRIPTION
**Pull request by ThePotato97**
## About the PR 

Adds progress bars to wall and window deconstruction.

Each action takes 5 seconds but anyone with "Engineering Training" can do each action in 2.5 seconds

Jobs that get the trait are;

- Chief Engineer
- Construction Worker
- Mechanic
- Engineer
- Station Builder

## Why's this needed? 

Adding progression bars will make it clearer to the user when they're deconstructing/constructing something.

The engineer trait will make it faster for skilled workers to do their job while making it slightly slower for others.

## Changelog

```
(u)ThePotato97:
(*)Added progress bars to Window & Walls construction / deconstruction
(+)Added engineer trait for engineer related jobs which makes them do certain engineering actions 2x faster.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Hot

**Comment by zjdtmkhzt** [comment]
Looks pretty sick to me!
Any confuse emoji people wanna weigh in with what they think may be issues that we are overlooking?

**Comment by ThePotato97** [comment]
People have told me that progress bars can sometimes be seen through walls

**Comment by RSG250** [comment]
Why not give Miner the trait since they have access (possible access rather) to larger amounts of material?

**Comment by Tarmunora** [comment]
If anything I'd remove the trait from mechanics - they deal with the internal stuff like machines rather than the external structure of the station

**Comment by ThePotato97** [comment]
Removed from mechanics, not adding to miners

**Review by ZeWaka — APPROVED** [review]
If progress bars are visible through walls, that's an issue to be addressed in another PR.

**Pull request merged**
