### PR TITLE
FIRST!

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by tinbeast** [comment]
yes hm i like this

**Comment by Iamgoofball** [comment]
oh hold on i put the var in the wrong spot, fucking relative pathing

**Comment by Iamgoofball** [comment]
fixed

**Comment by F-OS** [comment]
Suggestion, make this trigger when a cart crosses the finish line first

**Comment by MystLeissa** [comment]
Irony thick, the first OS PR is for a "First" Place Reagent....

**Comment by ZeWaka** [comment]
Doesn't really serve a purpose other than being a meme PR.

* Adds yet another global
* Doesn't use the proper radio speak verb on the human

Closing due to it just being a meme.

**Comment by Iamgoofball** [comment]
i fixed the global issue but whats the radio speak verb

**Comment by actioninja** [comment]
https://file.house/ke2M.png

**Comment by Iamgoofball** [comment]
those dont count, two of them are issues and 2 of them are robots

**Pull request closed without merging**
