### PR TITLE
Moves freezer pipes around a bit on cog1.

### PR DESCRIPTION
**Pull request by Laboredih123**
[BUG]

## About the PR 
Reduces the amount of pipes and fixes a case of overlayed pipes in the freezer.

## Why's this needed? 
Bug bad, pipe spam bad.

## Changelog 

```changelog
(u)Laboredih123
(+)Less pipes to deal with in the cog1 freezer, wow.
```

### CODE REVIEW

**Comment by Laboredih123** [comment]
why mapdiffbot fail :(

**Comment by Laboredih123** [comment]
heres how it looks like now (hid some stuff to make it clearer) (wow so cool quad pipe)
image

**Comment by TheTyrant25** [comment]
the changelog entry should probably mention which map's freezers are being changed.

**Comment by Laboredih123** [comment]
ok done

**Pull request merged**
