### PR TITLE
Clarion perspective tilesets

### PR DESCRIPTION
**Pull request by nefarious6th**
## About the PR 
Swaps the tilesets on Clarion for the 3/4ths perspective ones. Many thanks to Dions for letting me go ahead with this.

## Why's this needed? 
Clarion is a nice map; 3/4ths perspective tilesets update it and make it fit with the rest of the sprites. This PR now comes with windows and blinds! Updates some APCs locations and removes some redundant APCs. Moves some mail cutes to not be on windows.

## Changelog

```
(u)Dions & Nefarious6th
(*)Clarion now uses the 3/4ths perspective tilesets
```

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Are you intending to touch windows in the near future?

**Comment by mordent-goonstation** [comment]
You'd also probably want to do a pass of stuff against the south walls, as some things on them may not look right any more (and should be placed on a different wall), e.g.:
image

**Comment by mordent-goonstation** [comment]
I think lights on north walls need adjusting, too? 
image

**Comment by nefarious6th** [comment]
> I think lights on north walls need adjusting, too?
> image

Thank you for catching this; I'll give another pass to the map and work out the stuff on the walls.

WRT the windows, I would be interested in doing them in the near future, I just thought it was best to separate that. A lot of the windoors and thindows I don't think I'll do anything with since they're used in some places as walls and fundamentally changing the layout of Clarion goes a little beyond the scope of what I was aiming to do.

**Comment by nefarious6th** [comment]
Wall update
calrionpodbayv2
Probably will have the object movements done by early tomorrow morning!

**Comment by ZeWaka** [comment]
gotta do the windows as well imo

**Comment by nefarious6th** [comment]
> gotta do the windows as well imo, looks really bad otherwise

Would you prefer that on this PR or in a separate and subsequent one?

**Comment by nefarious6th** [comment]
Round 2!
geneticsclarion

**Comment by pali6** [comment]
In order to change wall and window types you need to do changes in `map.dm` and not in the dmm file itself. Something along the lines of:
```
	windows = /obj/window/auto
	windows_thin = /obj/window/pyro
	rwindows = /obj/window/auto/reinforced
	rwindows_thin = /obj/window/reinforced/pyro
	windows_crystal = /obj/window/auto/crystal
	windows_rcrystal = /obj/window/auto/crystal/reinforced
	window_layer_full = COG2_WINDOW_LAYER
	window_layer_north = GRILLE_LAYER+0.1
	window_layer_south = FLY_LAYER+1
	auto_windows = 1
```

**Comment by pali6** [comment]
Also, almost ceratinly unrelated to the contents of this PR, two of Clarions APCs are apparently badly configured - incorrect area strings. (The one in botany and the Research Sector APC.)

**Comment by nefarious6th** [comment]
> In order to change wall and window types you need to do changes in `map.dm` and not in the dmm file itself. Something along the lines of:
> 
> ```
> 	windows = /obj/window/auto
> 	windows_thin = /obj/window/pyro
> 	rwindows = /obj/window/auto/reinforced
> 	rwindows_thin = /obj/window/reinforced/pyro
> 	windows_crystal = /obj/window/auto/crystal
> 	windows_rcrystal = /obj/window/auto/crystal/reinforced
> 	window_layer_full = COG2_WINDOW_LAYER
> 	window_layer_north = GRILLE_LAYER+0.1
> 	window_layer_south = FLY_LAYER+1
> 	auto_windows = 1
> ```

Neat; I can work on this with a little guidance in the coding channel and have it sorted out probably by the end of the weekend.
The APCs that give runtimes I did notice; I didn't touch them but I know exactly which ones they are. I don't know how you would normally fix them, but I'm happy to do whatever I need to there to make them work okay, as long as that isn't scope-creep-y for this PR?

**Comment by pali6** [comment]
Not scope-creepy-imo, the problematic var is areaname or something along those lines. It points to non-existing areas.

**Comment by mordent-goonstation** [comment]
Few areas that look off:

- Medbay:
image
- Community Center: 
image
- Corridor just west of Community Center (and APCs on N->S walls in general), but this is not a problem exclusive to Clarion so outside scope of your PR, just highlighting as an area for people to hit if they want: 
image
- Escape: 
image
- CE's office (mail/disposal chutes): 
image
- Mining magnet communications dish (grilles look weird): 
image
- Substations (thindows running along the bottom, could probably push the thrusters south one and use the full windows?) 
image
- Detective's office: 
image
- Escape: 
image
- Owlery sign: 
image
- Arrivals: 
image

Overall, I think we can get away with merging this if the "lights on the corners" bits are addressed. Everything else is minor and could be hit in a follow up PR (for the sake of getting this one merged).

**Comment by nefarious6th** [comment]
Alright: managed to hit on everything Mordent pointed out (I pinky promise I got all the unmoved lights and cameras this time) EXCEPT for some of the weird-ly placed APCs on N-S walls and fixing the disposal chute placements on the HoS office and Arrivals (requires expansion). I did move around Robotics on this.

**Comment by ZeWaka** [comment]
wrong PR bro

**Pull request merged**
