### PR TITLE
Methanol

### PR DESCRIPTION
**Pull request by vocalpocal**
## About the PR 
Adds Methanol, a sneaky poison for bartenders! It can be only created by fermenting wood in still, allowing both wooden logs from botany and wooden furniture. You can only create 5 units of methanol at a time by filling the still with any item with wood material, and it takes 5 seconds to brew each item. Watch out when you make it though, because it is quite volatile!

This PR also adds wood material to most wooden furniture on the station without changing sprites/colour of those items (except when they are disassembled but who cares).

Methanol effect:
Each cycle it is in your system, it increments a specific counter by 0-2. This increment is paused while the victim has any ethanol in their system. But if the methanol counter reaches 40, the first symptoms kick in: blurry vision, and each cycle there is a roll for either 2 TOX, OR 3 OXY with an additional 0.6 units of formaldehyde -- the probability for either of this effects is methanol_counter%. Also at this stage, there is a 20% chance of vomiting, misstep and scary status texts. If the methanol counter reaches 80, the victim becomes completely blind and takes 1-4 BRAIN damage, in addition to previous effects.

## Why's this needed? 
This is a very sneaky chemical for bartenders. You could poison someone's beer with this. Because Methanol has an extremely slow decay rate (0.02 compared to ethanol's 0.05), your victim could show no symptoms as long as they stay drunk.  They are going to be in a world of pain when they sober up though.

my first PR pls no bully

12.7.2021
Nerfed methanol_counter>40 effect:
Previous: One of the following each cycle: 2 TOX; OR 3 OXY and a separate 50% chance of decaying into 0.6 units of formaldehyde
New: Probability of one of the following based on methanol counter (prob% is equal to methanol counter, so starts at 41-42% and 100% at 100 counter or more): 2 TOX; OR 3 OXY and a separate 50% chance of decaying into 0.6 units of formaldehyde

## Changelog
```changelog
(u)vocalpocal:
(+)Added Methanol reagent, which can be acquired by fermenting wood in a still.
(+)Added wood material to many pieces of furniture on the station
```

### CODE REVIEW

**Comment by PrimeNumb** [comment]
Could use a changelog entry

**Comment by vocalpocal** [comment]
> Could use a changelog entry

I try to be brief and concise with my commit messages, and there have not been any significant changes since the original PR (except now I nerfed it a little).

**Comment by PrimeNumb** [comment]
> > Could use a changelog entry
> 
> I try to be brief and concise with my commit messages, and there have not been any significant changes since the original PR (except now I nerfed it a little).

Oh I am talking about the ingame changelog (there's a template for it that you removed) that would introduce the reagent. You don't actually have to extensively document what you changed in each individual commit, that would be absurd.

For example:

## Changelog


```
(u)vocalpocal:
(+)Added Menthol reagent, which can be acquired by fermenting wood in a still.
```

**Comment by vocalpocal** [comment]
> > > Could use a changelog entry
> > 
> > 
> > I try to be brief and concise with my commit messages, and there have not been any significant changes since the original PR (except now I nerfed it a little).
> 
> Oh I am talking about the ingame changelog (there's a template for it that you removed) that would introduce the reagent. You don't actually have to extensively document what you changed in each individual commit, that would be absurd.
> 
> For example:
> 
> ## Changelog
> ```
> (u)vocalpocal:
> (+)Added Methanol reagent, which can be acquired by fermenting wood in a still.
> ```
> 
> EDIT:
> 
> This changelog:
> 

Oooooh That is very cool! I did not know this was a thing. Thanks!

**Pull request closed without merging**
