### PR TITLE
Admin/Mentor Mouse Dance

### PR DESCRIPTION
**Pull request by makkipakki**
[FEATURE]
## About the PR and why it's needed 
Adds a basic happy bouncy dance for mentor and admin mice with flavour text, based off of the :bouncerat: emoji on discord.
It's important to have a way to show how amused you are when the clown you were teaching how to honk ran full-tilt into a borging artifact. You can only *flip so many times, variety is good.

I based the code off of current dance code and puzzled the movement and stuff together, if anything is glaringly bad please point it out so I can fix it.

2020-09-29 04_19_08-Window
bouncy

## Changelog

```
(u)makkipakki:
(+)For mentor and admin mice, added a bouncy dance animation and text for the *dance emote
```

### CODE REVIEW

**Comment by Tiggersaurus** [comment]
Omg yessssss

**Comment by ZeWaka** [comment]
should be using animate() imo

**Comment by Kyle2143** [comment]
Yes plz

**Comment by LanceFyre99** [comment]
I adore this

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
As Zewaka said, these should really, really be using animate calls. It looks fluid, but using for loops and sleeps is overall worse for performance and tidiness. 

If you need examples for how to use animate calls to peform this type of complex animation, look in AnimationLibrary.dm. This could actually go there because I can imagine is working really well for other things cause it looks so nice.

A similar example might be /proc/animate_levitate or /proc/animate_spin

**Pull request closed without merging**
