### PR TITLE
Makes anti-histamine stroger. Epi no longer remove histamine.

### PR DESCRIPTION
**Pull request by MarkNais**
[BALANCE]
## About the PR 
Diphenhydramine now removes 15u histamine (from 3u). Epinephrine no longer removes any.

## Why's this needed? 
Epinephrine was removing 15u (*mult) histamine per tick. Anti-histamine was removing 3u.
That's whack.
Also I think Diphenhydramine could use a boost.

## Changelog

```
(u)MarkNstein:
(+)Anti-histamine is 5 times stronger. Epinephrine no longer removes histamine.
```

### CODE REVIEW

**Comment by pali6** [comment]
I'd prefer this to have a minor changelog entry since it's a balance change afterall (`(+)`).

**Comment by Tarmunora** [comment]
Epinephrine should probably directly counteract hist OD (anaphylaxis) in some way

**Comment by Gerhazo** [comment]
I have no medical education or knowledge, but as far as I've heard/read (which could very much be wrong please do correct and disregard me if so) epinephrine is the first-line treatment for stuff of this sort while antihistamines are used for lesser cases, which seems to fit in with how effective the two are relatively.

**Comment by UrsulaMejor** [comment]
This is pretty much the exact opposite of how these things work in real life, which imo would be incredibly weird for a new player.

**Comment by zjdtmkhzt** [comment]
Wow, real life is so dumb and unbalanced, you just use epinephrine for everything.
I feel like diphenhydramine should definitely have some niche, though? It's not exactly like epinephrine is in shorter supply than antihistamine, so why even use antihistamine ever?

**Comment by MarkNais** [comment]
Me making this PR came from 2 things: First, forgetting *Epi* Pens exist.
Second: Not seeing any mention of histamine in the epi' entry on the wiki.
Wiki edit is easy and I can do it later, but from my initial perspective (someone who's family doesn't suffer allergies) I wouldn't think to use epi' in game for histamine.
Unless someone has a clear idea for a change for Diphenhydramine, I'm probably just going to close this PR.

**Pull request closed without merging**
