### PR TITLE
allow the rafflesia to smoke its reagents

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
This PR makes it so that the Rafflesia (#5580) can now smoke all it's associated reagents. (Reagents gotten from splicing.)

To facilitate this, it also makes it so that spliced plants are now based on the plant type of the dominant parent, instead of the generic plant type, so that they will have the same HYPspecial_proc.

## Why's this needed? 
It gives some more flexible tools to botany instead of just "mass produce x chem or food".
Curare was removed, and even if you manage to splice clf3 into the plant, it will just self-destruct with the smoke, so the worst thing you can put in is stuff like radium (which may destroy the plant too? not sure) or amanitin.
And if a traitor does do that, if one just goes to the plant tray, and click drags, it is very easy to get rid of the plant.
Unlike the old (imbalanced) explosive tomatos, this would require you to drag around a giant plantpot instead of having 50 explosive items in a bag. (The same actually applies to hotboxing too, this would be a lot more telegraphed than a hotbox.)
For all of these and more reasons, I think that this would be a good change that would not cause significant balance issues.
And if issues do arise, the size and amount of chemical smoked can be easily adjusted via the formulas.
Thanks for coming to my ted talk.

On the other hand, it opens up a lot of very useful and fun ways to make plants that people will love, like some kind of triple citrus smoke room, or whatever, idk.

With the change to HYPspecial_proc inheritance, maybe we could even have more changes in the future where splicing can affect special plant types in cool ways.
## Changelog

```changelog
(u) zjdtmkhzt
(*) Spliced plants should now properly inherit the special behavior of their dominant parent. (For instance, rafflesia.)
(*) The rafflesia can now smoke all of its spliced reagents, instead of just miasma.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
This is a no from me. Not being able to splice in other chemicals was one of the points in favour of this plant being merged in the first place.

**Comment by zjdtmkhzt** [comment]
That was because it would pose similar issues to hotboxing though, and this seems like it would be both more work than a hotbox, and much more telegraphed, since a person would need to first splice the chems to this specific plant (rather than any random hotboxable herb) and then they would also need to lug around a giant blooming plantpot, which would already be leaking chems, making it really obvious.

By contrast, a hotbox can be made from a single bag from your backpack with up to 50 herbs in it, and it also causes fire, smoke, and makes the chems be really hot.

So I think if hotboxes can be in the game, then this plant which seems much less problematic could certainly be too?

**Comment by Tarmunora** [comment]
We had to nerf and readjust hotboxing over a half-dozen times to get it to a halfway-OK state that doesn't flood half the station with boiling THC on a daily basis, and I'd really rather not reopen that can of worms any more than I have to.
If some other dev thinks that this is a really good idea, they can merge it, but I won't. 🤷

**Comment by zjdtmkhzt** [comment]
Yeah, that's fair, I'm sure it  must have been very annoying, because people would probably hotbox a lot for the same reason they always grow weed - lol420memes xD.

I am hopeful that this would be less the case with this, since it's not, uuuh, cannabis based.

**Comment by vocalpocal** [comment]
So you are saying this PR fixes HYPSpecial proc splicing bug? In that case this is huge and should be added.
FYI you can't make Synth Cats with funny names because their spawn proc wont work after splicing because of this bug.

**Comment by zjdtmkhzt** [comment]
I wasn't aware any other plants actually had interactions that weren't working due to splice stuff. If the devs decide not to merge this, I'll split the HYPSpecial thing off into another PR.

**Comment by vocalpocal** [comment]
For rafflesia, I think the effect is fine. The tray should be quite manageable by sec and anyone who notices someone being a jackass -- compared to a huge pile of omega weed burning with the power of two suns enabled with just one produce satchel and a welder.

**Comment by Johann-Strauss** [comment]
I may be mistaken and someone please correct me if I'm wrong, but the smoke produced by the Rafflesia is not really that big, so for a mischievous botanist to create a smoke big enough to pose a treat would require several of these, wich is far more laborious than lightning a pile of weed stashed on a produce bag.

All in all, i am a big fan of the proposed change.

**Comment by zjdtmkhzt** [comment]
It's sort of a combined scaling where both cropsize and potency need to have a certain amount, I think.
Though with the current potency scaling the max you'd get of a single chem in a smoke is potency*0.15, I think? (Potency*3/10, but at least half of that would be miasma)

And of course, the scalings could always be adjusted or capped more.

**Comment by vocalpocal** [comment]
> I may be mistaken and someone please correct me if I'm wrong, but the smoke produced by the Rafflesia is not really that big, so for a mischievous botanist to create a smoke big enough to pose a treat would require several of these, wich is far more laborious than lightning a pile of weed stashed on a produce bag.
> 
> All in all, i am a big fan of the proposed change.

As far as I know, miasma, when it is smoked, reduces smoke spread significantly by making it more dense (more stuff inside of one turf cloud, but smaller overall radius). So yeah, rafflesia is a quite smart choice for a smoking plant.

**Comment by zjdtmkhzt** [comment]
That is true, miasma has a smoke_spread_modifier of 3, unlike most other things. I am not exactly sure how much this hinders the spread though.

**Comment by vocalpocal** [comment]
I really wish this was merged. I have big plans for this plant, and they are not even for antag use. Grass and charcoal and you have grass-gro dispenser without downsides!

**Review by pali6 — APPROVED** [review]
I'm gonna merge this as an experiment because I like it. If it screws up balance ~~yass will yell at me and revert it~~ I'll try to figure out if there's a way to fix the balance or whether to revert it.

**Pull request merged**
