### PR TITLE
Player visible volume for atmospherics

### PR DESCRIPTION
**Pull request by CheffieGithub**
[ATMOSPHERICS][QoL]
## About the PR 
Adds volumes to the descriptions of Portable atmos tanks, Canisters, Scrubbers, Pumps and the Repressurisation device. 
Atmos scanner now shows you the volume of the thing you scan. 

For pipe parts this is a sum of all connected segments volume.

example of volume sum:
image

Syndicate jetpack description:
image

## Why's this needed? 
Volume is needed for some gas calculations so if any engineers want to work out how many moles of farts they have they can do it now!

## Changelog 

```changelog
(u)Cheffie
(+)You can now see the volume of various atmospherics objects by examining them for portable objects or with the atmospherics scanner for pipes.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
It feels weird for everyone to be able to just know how much volume a tank has, maybe make this a function of atmos scanner instead? Like the base goal though.

**Comment by CheffieGithub** [comment]
I could just make it 'Its labled to have a volume of X litres.' Would that be better?

**Comment by ThatFiveGuys** [comment]
> I could just make it 'Its labled to have a volume of X litres.' Would that be better?

That would work as well

**Review by frawhst — APPROVED** [review]
I like this a lot. Tank volume isn't communicated at all, which leads to a lot of weird misconceptions about what pressure means.

**Pull request merged**
