### PR TITLE
clean up RobustLight2.dm

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Pathing made fully absolute for the light datums, partially for atom stuff at the bottom.
`src `and `global` added for scope. (shouldn't effect behaviour just more readable)
moved `/atom/movable` mechanics related things to `atom.dm`.
`TRUE` / `FALSE` conversion.

## Why's this needed? 
Much easier to find things. Mechanics interactions don't belong in the robust lights file. Arguably more readable this way.

### CODE REVIEW

**Comment by Azrun** [comment]
What does "moved /atom/movable mechanics related things to atom.dm." have to do with robust lights... 🫠

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
cooltext445710790206610

**Comment by BatElite** [comment]
Well would you rather keep those vars in the robustlight code file then?

**Review by ZeWaka — APPROVED** [review]
thanks, this still needs to be split but this is a great start

**Comment by CheffieGithub** [comment]
How much should it be split? The diff is massively inflated from what vsc said it was due to indent changes.

**Comment by ZeWaka** [comment]
> How much should it be split? The diff is massively inflated from what vsc said it was due to indent changes.

not this pr, i mean splitting this file into multiple others, out of scope of this PR

**Review by TobleroneSwordfish — APPROVED** [review]
Oh sorry I didn't realise the mechanics stuff was actually *in* the robustlight file, that's awful

**Pull request merged**
