### PR TITLE
Completely redesign cogmap1 Mechanic's Lab

### PR DESCRIPTION
**Pull request by penny64**
[QOL]
## About the PR 

image
image
image
image
image

This builds the mech lab mostly up from the ground up
- One ruck kit and two manufacturers
  - High pop experience on Main 1 is the main factor
  - I enjoy the maps with two of them more in general, it's nice not to be on top of each other
- Equipment layout
  - Nothing in doorways or walking paths
  - Manufacturer and ruck kit positioned by the service window to encourage interaction!
- Data room
  - Some amount of defense from the greytide trying to get your gloves 
  - Data terminals, mechanics love em
  - Shutters on the outside windows, open by default to scream out "I'm doing crime!" to the world
  - Router window has no blinds, go take a peek at their secrets!
  - Electrified window still provides opportunities for crime
  - There's a camera
 - An actually reasonable number of tables
 - PC is loaded with FROG for connecting to DWAINE
 - Carts are loaded with equipment to compensate for less tables
 - Mule beacons instead of just a cargo pad
 - Added a phone so people can call in requests
 - Added some starting mats
 - A scanner because mechanics are frequent DWAINE users

Additionally, mechanics are granted access to engineering control rooms(as we removed their door to it, which was weird anyway).
## Why's this needed? 

Takes advantage of the space available, modernizing it up to standard with other newer maps and making the experience on highpop much more enjoyable and relaxed.

It also feels nice, and is cozy.
## Changelog

```changelog
(u)Penny
(*)Improves the layout of cog1 mechanic's lab and adds equipment and a data closet
```

### CODE REVIEW

**Comment by Zonespace27** [comment]
if you ask me, the upper area seems a bit cramped, what I'd suggest is move things around a bit to look like [this](https://imgur.com/a/r9fsfvA) (pardon the shitty MS paint), along with slightly editing the hot loop's room above to make room for the door's new position

**Comment by penny64** [comment]
@Zonespace27 I'm sorry, you saw pictures of an old dead version

**Review by ZeWaka — CHANGES_REQUESTED** [review]
data room camera: off the window please
data room lightswitch: offset on the wall properly
main room bottom light: off the window
main room side lights: why are they not offset properly

is it intentional you are wasting space below the SMESes with the wall?

some incandescent lights would be nice too

**Comment by BatElite** [comment]
I think none of the east/west lights on cog1 are offset properly since they're manual instead of autopositioning. Not my call to make ofc but maybe that's something for a lighting pass PR.

More importantly though: As far as I can tell you've not actually connected the SMESes to the regulated grid on this design.

**Comment by penny64** [comment]
I did waste a tile for spacing, consecutive wallspace is more valuable than a tile of floorspace

**Comment by penny64** [comment]
And oops, SMESes connected now, heh

**Comment by Azrun** [comment]
`techcomputer3` seems a little weird as part of this...
Whats up with the light below the Engine Output Monitoring Computer?
GPS Waypoint for Mechanics Lab is gone

**Comment by Crackaduck** [comment]
only thing id consider is making the door to the storage room connect with the rest of engineering, they feel so little like a unified department and this just cuts them off more

**Comment by penny64** [comment]
I'm actually giving them access to the lobby via the main doors with a new access

**Comment by Sovexe** [comment]
The closet loses half of the top row of the room and created two different sections of extra thick walls.

Why not just slide the closet up 1 tile into your double ref walls and avoid making the mechanics main area smaller?

image

**Comment by penny64** [comment]
@Sovexe that's the combustion chamber, a newer map would have a maint tunnel as heat shielding, we have two walls

**Comment by Azrun** [comment]
> 
> That room would get very toasty/combust, which is why you can see on the diff I didn't make that double wall, it was already there

Room has three tiles with cardinal adjacency with a single reinforced wall though right? Also I think I'd prefer if the SMES terminals were covered/protected (just by floor tile at least).

**Comment by penny64** [comment]
Engineers told me it's better to work on them like this

**Comment by Azrun** [comment]
Lack of redundancy of wiring makes it so all output from those SMES go through Mechanics lab before coming back into the room.

**Comment by penny64** [comment]
image

I can do this to make the room bigger bit it ruins my feng shui, big rectangles are boring

**Comment by penny64** [comment]
image

**Comment by penny64** [comment]
Alright I'm happy where we're at here

**Comment by penny64** [comment]
The diff bot cannot render the hot loop pipe with that wire turn for some reason but I have tested and it's all working, and it's in my screenshot

**Review by ZeWaka — APPROVED** [review]

**Comment by penny64** [comment]
The SMES units aren't plugged in atm that wire knot under the hot loop power room door needs to be replaced with a turn

**Comment by penny64** [comment]
@ZeWaka there we go thanks

**Review by flrsh — CHANGES_REQUESTED** [review]
Please replace the double walls in the engine room with a row of tiles. The SMES room and mechanics backroom should serve as adequate buffer already. 

Please also reroute the wiring so that it doesn't go under walls. 

Otherwise looks good to me!

**Comment by penny64** [comment]
image

Alright I got you I think this back room is gonna get toasty tho

**Comment by flrsh** [comment]
Thanks! Just to make sure, were the areas also updated? The lines in your screenshot don't seem aligned with the rooms.

**Comment by penny64** [comment]
Areas weren't finished yet then but I fixed them!

**Review by flrsh — APPROVED** [review]

**Pull request merged**
