### PR TITLE
New Item: Pepper Spray Bottle.

### PR DESCRIPTION
**Pull request by Wisemonster**
[BALANCE] [FEATURE] [GAME OBJECT]

## About the PR 
This pr gives the HoP locker a pepper spray bottle. This bottle can only be filled with capsaicin, and holds 100u.

## Why's this needed? 
The HoP currently has very little defenses when it comes to people raiding his office. The flash can easily be ignored by a quick trip to a pod bay. This let's the HoP defend himself at least a little bit better, without encouraging sec-HoP behaviour.

## Changelog

```changelog
(u)Wisemonster
(*)The HoP locker now comes with a bottle of pepper spray, to 
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Implementation of this as a spray bottle seems really weird, should probably be closer to a short range smoke powder flamer in terms of function

**Comment by Chatauscours** [comment]
I am not a fan of adding gear used by real life police to the game, even less a fan of giving it to the HoP who is supposed to be a civilian role. And if anything, I agree with Ikea that HoP's protection should be tied to his office, not to his gear.

**Comment by Wisemonster** [comment]
> I am not a fan of adding gear used by real life police to the game, even less a fan of giving it to the HoP who is supposed to be a civilian role. And if anything, I agree with Ikea that HoP's protection should be tied to his office, not to his gear.

Except pepper spray is a very common tool used by civilians as a form of self-defense.

**Comment by TobleroneSwordfish** [comment]
> Except pepper spray is a very common tool used by civilians as a form of self-defense.

Depends how illegal it is in your country :P
I do like the idea of giving the HoP something else in the way of self defence though.

**Pull request closed without merging**
