### PR TITLE
super secret easteregg

### PR DESCRIPTION
**Pull request by amylizzle**
## About the PR 
flock is `ba.ba`

Sprite used with permission from Hempuli

image
image
image

## Why's this needed? 

funi

### CODE REVIEW

**Comment by trazodont** [comment]
Awww 🥺 Ba.ba

**Comment by CaioFrancisco** [comment]
Show us the sprite, or be doomed with my light disappointment.

**Comment by amylizzle** [comment]
image

**Review by frawhst — APPROVED** [review]
cute

**Pull request merged**
