### PR TITLE
Changes Various Glasses COVERSEYES

### PR DESCRIPTION
**Pull request by Wisemonster**
[QoL] [BALANCE]

## About the PR 
This pr changes various glasses to have the COVEREYES trait, rather than all of them having the trait.

## Why's this needed? 
Currently, all glasses block these affects:
-barbering
-blocking eyelasers
-condiment shaker attacks
-penlights
-throwing sponges
Some glasses don't really make sense to block these, for example prescription glasses. This changes it so that items that would "cover eyes" (i.e. goggles, blindfolds) aren't literally every single glasses items.

```changelog
(u)Wisemonster
(+)Glasses, sunglasses (except sechuds), eyepatches, and blindfolds no longer count as eye cover. Watch out for salt shaker attacks!
```

### CODE REVIEW

**Comment by BatElite** [comment]
I still don't see (ha) how eye surgery wouldn't be impaired by basically all glasses. The sailor moon diadems sure (why are they glasses anyway) but otherwise the only things not covering at least one eye are monocles or eyepatches, and the flag just doesn't handle individual eyes.

Also there's minor stuff that COVERSEYES influences, actually:
-barbering
-blocking eyelasers
-condiment shaker attacks (okay then)
-penlights
-throwing sponges

head surgery doesn't actually care about glasses, but I'm guessing that's more for ease of debraining someone with glasses on than eye surgery.

**Comment by Wisemonster** [comment]
> I still don't see (ha) how eye surgery wouldn't be impaired by basically all glasses. The sailor moon diadems sure (why are they glasses anyway) but otherwise the only things not covering at least one eye are monocles or eyepatches, and the flag just doesn't handle individual eyes.
> 
> Also there's minor stuff that COVERSEYES influences, actually: -barbering -blocking eyelasers -condiment shaker attacks (okay then) -penlights -throwing sponges

To clarify, I was basing it on logically how you would shift the glasses out of the way if attempting to do eye surgery on someone that had said glasses on. For example, an eye patch you would shift out of the way by simply flipping it up, or glasses you would move up or down slightly, while things like goggles/blindfolds would be too "in the way" to be able to perform surgery. Granted, currently head/eye surgery doesn't take COVERSEYES into account, I still think making it so literally every single glasses slot item blocking these affects is a bit silly. (For example, it doesn't make sense that prescription glasses block any of these.)

And on a side note, I planned on making a follow-up pr that changes capsaicin to use these changes.

**Comment by flrsh** [comment]
Personally it doesn't make a ton of sense that these glasses *wouldn't* block these, since they're still glasses. Besides maybe like the eyepatch.

**Comment by Wisemonster** [comment]
Hell, it makes even less sense that

**Pull request closed without merging**
