### PR TITLE
OVERHAULS THE ENTIRE DAMNED GAME

### PR DESCRIPTION
**Pull request by comradef191**
### RETURNS THE GAME TO AS IT WAS* IN THE r4407 RELEASE

_*rule-breaking terms have been purged & modern admin.txt attempted to be recreated_
## Why's this needed? 

FOR TOO LONG NOW WE HAVE SUSTAINED FEATURE BLOAT
NO MORE
I PRESENT A SOLUTION:
WE MUST RETURN TO OUR ORIGINS, YE OLD r4407.

### CODE REVIEW

**Review by mordent-goonstation — APPROVED** [review]
Sounds good. Also highlights a need for a new size label.

**Review by ZeWaka — APPROVED** [review]

**Review by mordent-goonstation — CHANGES_REQUESTED** [review]
Please fix your merge conflicts.

**Comment by Sovexe** [comment]
Return to monke

**Comment by comradef191** [comment]
> 
> 
> Please fix your merge conflicts.

done

**Comment by frawhst** [comment]
image

**Pull request closed without merging**
