### PR TITLE
Alt + hover over mobs shows names + pronouns

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 

KxFpRcJxQW
Hold Alt to see these name tags under people. Shadows obscure them so there's no risk of seeing people in darkness through this. However, I believe as they are currently they appear over other objects. 

Currently it applies to all mobs. If there's demand I can change it to apply only to /mob/living/carbon/human instead.

You aren't able to see the name if you can't see the tile the mob is standing on.

**NEW CHANGES:** Standing on a tile with a shrub on it hides your name. If your name is Unknown your name is not shown. If your ID name and face name don't match the *face name* is shown. Let me know if the last point is controversial.

## Why's this needed? 
It sucks having to hunt a persom with your cursor and alt click them, then read the chat to see who they are. Yeah, experienced players know that they can just look in the bottom left corner of the client window to see the name but newer players don't.
Also @Flaborized sorta requested this so she might have even better reasons.

## Changelog
```changelog
(u)pali
(*)Holding alt + hovering over people with your cursor shows their names and pronouns
(*)AI, borgs and ghosts see all mobs' names when holding alt
```

### CODE REVIEW

**Comment by pali6** [comment]
> I like it, but this completely ruins hiding in bushes.
Sechud already did that since forever. I could add a check for mob movement to see if they aren't on a tile with bush which wouldn't be too much trouble but mob movement is already one of the more performance-intensive processes on highpop so not sure if it's worth it.
> Names can also get extremely long, either by a user giving themselves a long name or extra modifiers added to names.
True. What do you tihnk would be a good solution? Cutting off the name after X characters? Splitting the name into multiple lines? Making the name just be one long line? I guess we could start with deleting labels from the name.

**Comment by raymondh2** [comment]
Deleting labels seems like a sane place to start.

**Comment by pali6** [comment]
Labels stripped. As a bit of a hacky solution I could make it display just first two words of the name?

**Comment by pali6** [comment]
Regarding pronouns: I think it's a good idea but first I'd like to see if this alone isn't too intrusive. If this PR gets merged I'll make a second one that adds the pronouns.

**Comment by pali6** [comment]
Oh and also I'd like to hear some opinions about the visual parameters of these name tags. Specifically:

transparency, vertical offset, font size, outline colour, text colour

**Comment by Sovexe** [comment]
image
doesnt seem to work for ghosts

**Comment by pali6** [comment]
This should fix now. If you see any other mob types not using UpdateName let me know.

**Comment by pali6** [comment]
Actually I had an idea, I'll probably make shrubs hide these and maybe make second PR to do the same for arrest icons.

**Comment by Flaborized** [comment]
I don't have any particular reasoning that's better than yours, I think its a fantastic QoL addition. Looks great to me, readable but not too obtrusive, will probably contribute to some fun screenshots in the future where funny names are involved. Great work!

**Comment by pali6** [comment]
The neat thing about how it's done right now is that it doesn't need to handle the maptext one by one. Removing your own name tag would require a rewrite to a more complicated slower system.

Imo I can many pronouns look non intrusive with this.

I get your concerns about people trying to blend in. What are your thoughts on making it so your name doesn't show on the name tag if it's Unknown. Doesn't show the issue entirely but it makes you stand out less.

**Comment by pali6** [comment]
Also even if this feature doesn't go through as is it could at least be useful if enabled for ghosts.

**Comment by pali6** [comment]
Now it only shows stuff on hover + alt. AI, borgs, wraiths and flockmind are exampt. This is tied to a mob property.

**Pull request merged**
