### PR TITLE
Add MechComp association component

### PR DESCRIPTION
**Pull request by glassofmilk**
[FEATURE]
## About the PR 
This adds a new MechComp piece - the Association Component. It's similar to the selection component, but it stores a map instead of a list. For adding new associations, it expects a signal structured like a packet with a series of key/value pairs, for example `key1=value1&key2=value2`. For sending a value, it will check to see if the signal being provided exists in its map, and if so, it returns the value. Following the previous example, a signal of `key1` would have the Association Component sending along `value1`.

The Association Component has three modes: mutable, immutable, and list. In mutable mode, if you try to add a key/value pair that already exists, the old value will be replace by the new value. In immutable mode, values cannot be replaced. In list mode, any new values for a key will be added to the existing value as a comma-delimited list.

New sprite:

## Why's this needed? 
Create a voting machine! Use it to store associations between PDA addresses and their owner's name! Do something absolutely awful that I didn't anticipate!

## Changelog

```
(u)glassofmilk:
(*)Added the new Association Component - a MechComp piece that stores key/value pairs
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Could we get a maximum size on the list here? The string build for the description could be pretty debilitating with 100+ entries.

**Comment by glassofmilk** [comment]
@ZeWaka How about having the description only contain the first 10 or 20, but I also add a config option that lets you see the whole list? I could make the same change to the selection component, which has also had some performance issues in the past when it gets too bloated.

**Comment by ZeWaka** [comment]
> @ZeWaka How about having the description only contain the first 10 or 20, but I also add a config option that lets you see the whole list?

Moreso thinking about performance on the server / crash-ability.

**Comment by glassofmilk** [comment]
> > @ZeWaka How about having the description only contain the first 10 or 20, but I also add a config option that lets you see the whole list?
> 
> Moreso thinking about performance on the server / crash-ability.

By config option, I mean you'd have to smack it with your multitool and select "View all associations" to get them to print out. Someone would have to be doing something malicious in order to crash the server.

**Pull request merged**
