### PR TITLE
chore: erase racist button

### PR DESCRIPTION
**Pull request by imnotjames**
## About the PR 

Remove what is probably an older joke that might have been funny at some point.

It's a button that declares the person that presses it a racist and then gibs them.  Err.. "makes them a racist"?

## Why's this needed? 

we don't really need a button that does this.  I don't really get the joke.

We need less of these in the world, let's not have a button for this.

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
I thought you were avoiding saying the joke in your PR but it literally is a racist button, wow

**Comment by imnotjames** [comment]
Oops, didn't remove the reference to it in z2

**Comment by Studenterhue** [comment]
There's a kinda a weird story about this button, which appears in the Ass Day Arena/Respawn Arena surrounded entirely by lava. Originally, this button gave you an accent that did things like replace your words with like "cunt", "horsefucker", and "yiff", among a bunch of other things inspired by the mannerisms of a former admin who often said some really weird and rather NSFW things as a joke. That got removed (with said former admin's blessing, who I think said they had no idea there was such a thing inspired by them) because it was kinda gross and broke slurs/sexual content rules, so this button's basically been hanging on without the punchline. That's a good way to describe it really, an joke with a punchline that doesn't make sense anymore.

**Comment by Kyle2143** [comment]
Replace it with a button that if you press it, it bans you from the server for like an hour.

**Comment by Superlagg** [comment]
Replace it with a button that gives you admin, you press it and it gives you a cat named admin.

**Comment by imnotjames** [comment]
I'll implement things if it's suggested as part of a review otherwise I will continue assuming y'all are brainstorming.

Please continue.

**Comment by Eagletanker** [comment]
Rename the button the Big Red Button, and if you press it it makes the shaking explosion effect and kills youZ.

**Comment by MatheusIsNotAvailable** [comment]
Add all the ideas but it picks from one of them when you press it :)

**Comment by imnotjames** [comment]
Rename the button "Developer Preparedness System" and if you press it it creates a fake runtime error that comes from a random proc of a random file

**Comment by Tarmunora** [comment]
tag/label your PRs

**Comment by wsock** [comment]
Yeah lets remove everything offensive. lets start with homophobic admins like Tarmunora

**Pull request merged**
