### PR TITLE
Resprites batons

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
[WIKI]

## About the PR 

Resprites batons and stun canes
Captura de Tela (244)

## Why's this needed? 

their shading looked kind of outdated before and I always felt they looked bad compared to other security stuff

## Changelog

```changelog
(u)Arthur Holiday
(+)Resprited stun batons and stun canes
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Hm. Stun cane could do with looking a little less stun and a little more cane, if you get what I mean

**Comment by Kyle2143** [comment]
I don't really see a need to resprite any of these except for the stun cane. These feel like a lateral move.

**Review by Kyle2143 — CHANGES_REQUESTED** [review]
So the stun cane definitely needs a different design, it's arguably better than the current stun cane in terms of general design, but it doesn't really capture the fancy pants Monopoly man "cane" aspect that the current one does.

I think my main issue with these resprites are:
1. The stun baton and NTSO stun baton are that these don't really look much different design wise. That's not to say they are bad, just that they . The colours of the stun/energy part are a bit brighter which I think looks good, but but the only differences in design are the red dots on the handle and the stun tip being larger. Oh and the inclusion of the string that was previously only on the NTSO baton.

2. The stun baton is an old design, but the NTSO baton is only a year or so and I think it looks alright, since this patch isn't really a redesign and more about respriting old things to bring them up to a modern standard, I don't really think it's needed here. I think the bulbous tip on that one looks a bit worse than the current one. (I'm not really a fan of making the stun tip look this much larger on the stun batons in general)

3. I think the red/blue lights on the handle would be better if they reflected either the current state of the baton (on/off) or the state of the power cell (more coding) through changes in colour. The active states for the regular baton and the stun cane are both animated, but the NTSO baton is not, seems strange to add animation for one more, but not the other. And the active state for the standard baton has a frame or two where it looks like it's off, not sure how I feel about that one really, that might be good it might make it less obvious that its active.

**Comment by MatheusIsNotAvailable** [comment]
Closing because I simply lack the energy to work on the requested changes rn, if someone wants to pick up on it and do their own PR just @ me on discord, I am Arthur.

**Pull request closed without merging**
