### PR TITLE
Fellable trees

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[FEATURE] [GAME OBJECTS]
## About the PR 
Lets you cut down trees with any sawing or chopping tool.
Comes with extremely realistic tree falling animation: https://i.imgur.com/CWWlRaj.mp4.
Tree falling sound modified from [Log Falling in Forest.](https://freesound.org/people/kev_durr/sounds/396509) by [kev_durr](https://freesound.org/people/kev_durr/), used under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0). Modifications done by Alyas.
Also re-paths all trees from `/obj/tree1` to `/obj/tree` and moves sakura and carcosa trees to be `/obj/tree`s too.
Chopping is disabled on restricted z levels just in case it breaks an azone or two.

This will most likely fail all kinds of map checks due to doing several complete find-replaces over old maps. Someone brave will have to hit merge regardless.
## Why's this needed? 
Terrainify and other admin tree-related gimmicks often put trees all over the station z level, but players are unable to commit mass deforestation. I want to be able to put trees in annoying places without ruining the round.

## Changelog 

```changelog
(u)LeahTheTech
(*)Trees can now be felled using any sawing or chopping tools.
```

### CODE REVIEW

**Review by Azrun — CHANGES_REQUESTED** [review]
Audio should be mono and likely compressed a bit.
https://hackmd.io/@goonstation/audio

**Comment by TobleroneSwordfish** [comment]
Hopefully that's compressed enough? Audacity refuses to nuke it further.

**Comment by Gannets** [comment]
SS13 survival mode...

**Comment by BatElite** [comment]
without separating the stump from the tree, that animation looks very weird

**Comment by Azrun** [comment]
> without separating the stump from the tree, that animation looks very weird

🤔 Beyond the separation it seems like the point of rotation for the two animations does make it hinge kind of oddly.

**Review by Azrun — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
mmm it could be smoother, but like this it kinda looks like it's juuust hanging on before toppling so I think it's okay

**Comment by frawhst** [comment]
!merge_upstream

**Comment by TobleroneSwordfish** [comment]
~~I hate the map merge driver I hate the map merge driver I hate the map merge driver.~~

**Pull request merged**
