### PR TITLE
Check for valid BR drop location

### PR DESCRIPTION
**Pull request by flappybatpal**
[BUG]

## About the PR 
Check BR drop location is valid when kicking players out of the shuttle.

## Why's this needed? 
I don't know how but this failed on Oshan with an error pick() from empty list. Possibly turfs destroyed from a macro bomb?

### CODE REVIEW

**Comment by Sovexe** [comment]
Turfs shouldn't ever be destroyed to my knowledge, only ever replaced.

**Review by pali6 — CHANGES_REQUESTED** [review]
This doesn't fix the bug. The first pick still runs on the same list and will runtime.

**Review by pali6 — APPROVED** [review]
Inefficient as heck but so was the old code

**Comment by pali6** [comment]
Oh, checks failing. Better fix that

**Pull request merged**
