### PR TITLE
Adds vampire serum and werewolf serum to the random chem blacklist and removes them from artifacts.

### PR DESCRIPTION
**Pull request by DimWhat**
[Removal] [Balance]
## About the PR 
This will add vampire and werewolf serums to the blacklist of chemicals not allowed to be randomly selected. This make the chems werewolf serum and vampire serum much more difficult to get your hands on.

## Why's this needed? 
These chems are incredibly powerful when you are able to get them, as they give you antagonistic abilities but none of the abilities. When chemicals like this are mass produced by methods of chem duplication and just handed off to just about everyone you get plenty of people ready to act like antags because they have the abilities. On top of that these chems can be randomly gotten by an actual antagonist that then stacks the effects on top of their actual antagonistic abilities.

I think you probably should have to _at least_ actually make the dang thing instead of getting a bunch of odd cigs or randomly getting it in an artifact.

Edit: It turns out that the recipe doesn't actually work currently, poking around the discord for possible objections to reviving the chem.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Label please @DimWhat

**Comment by Camryn-Buttes** [comment]
> I think you probably should have to at least actually make the dang thing instead of getting a bunch of odd cigs or randomly getting it in an artifact.

This is currently impossible to do from scratch, but you don't seem to have actually done anything to address that.

**Comment by DimWhat** [comment]
> This is currently impossible to do from scratch, but you don't seem to have actually done anything to address that.

Do you mind linking said issue or was this an unreported bug?

**Comment by DimWhat** [comment]
Closing this PR to instead fix the current issues with the werewolf transformation and an eventual overhaul of the two chemicals.

**Pull request closed without merging**
