### PR TITLE
TGUI Clothing Booth

### PR DESCRIPTION
**Pull request by DisturbHerb**
[TGUI][QOL][OBJECTS]

## About the PR 
This should hopefully be the first of numerous PRs to rework the clothing booth. For the sake of atomisation, this PR converts the clothing booth to a TGUI with as few changes as possible on the back-end (but i did do a little bit of cleaning up and reorganisation). Apologies if any of the code I've written is awful.

An image of the new clothing booth interface.

There are a few new things from a user-facing perspective,
- Character preview can be rotated now. Whee!
- Purchase confirmation has moved solidly away from the buttons you use to select the desired clothing item, instead it's on the bottom-right.

### To do
- Re-organise the `clothingbooth_item` list to prune the category list down.
  - Similarly, fix the name mismatch cases (eg. hairclips != barettes).
- Add tabs for item slots for further filtering.
- Maybe a search function?

## Why's this needed? 
Part of ongoing TGUI-ification efforts.

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
To be clear, is the todo list for this PR or future PRs? Confused since it isn't a draft

**Comment by DisturbHerb** [comment]
> To be clear, is the todo list for this PR or future PRs? Confused since it isn't a draft

for da fuuuutuuuuure 👻

**Comment by DisturbHerb** [comment]
lmao hopping in the booth lags my game to shit, is it the big fuckin' list that it has to fetch? who knows!

**Comment by TobleroneSwordfish** [comment]
Best guess on the lag is it's the result of sending all those sprites to the frontend at once, you could try making `ui_static_data` only provide the items in the current category and make changing categories update the static data.

**Review by TobleroneSwordfish — APPROVED** [review]

**Pull request merged**
