### PR TITLE
Federation

### PR DESCRIPTION
**Pull request by cheekybrdy**
## About the PR 
New Map: Federation, with very distinct boundaries between departments, yet still federated.
Please note this is my first map and PR so please be understanding about rookie errors.
I saw some discussion on the discord about current maps being oversupplied at round start, I tried to implement this but may have gone overboard.
Room equipment was based on cog1 so any things that are exceptions for the classic that shouldn't be repeated would likely be in the map.
Yet to implement:
Area zoning for pandemic ward
Asylum piping
all airbridge controller @ bridge
pathologist retextured armoury auth for pandemic ward
law rack with equality on round start (for the silicon department wing)
## Why's this needed? 
New map, with design for highpop which only has 4 maps at the moment, brings a very unique layout and a fresh take on highpop gameplay.

## Changelog

```changelog
(u)Cheekybrdy
(*)
(+)
```

### CODE REVIEW

**Comment by BatElite** [comment]
Hey, there seem to be some neat places and ideas in here although the map needs a lot more time in the oven, but it's roomy enough that it can probably change easily. Here's a bunch of mostly unsorted things I found just looking around in SDMM, haven't tried running the map. Also, I appreciate the map is very unfinished, so hopefully I skipped everything that you've obviously not gotten to yet.
I'm not a dev and not heavily involved with goon anymore, so I'm probably not going to keep up to date with this effort. Good luck though.


Major issues

-I'm not going to complain about the many pipes going through walls since most maps do that in places (except for the disposal pipe in west medbay that one's just nasty), but several areas are set up wrong (particularly around sec but not exclusively). Pipes can cross over one another fine but you can't put multiple in the same direction on the same tile, the system isn't advanced enough to handle that.
-Although I appreciate criming toys, the syndie destruction, purge and rewind systems in maint are well into overkill for maint goodies.
-The mail network as is won't function as most things end up in the mail room. The pipes need to loop back at some point. (see cog1 for a simple setup, and cog2 for one that has several loops and a central router)
-`/area/station/chapel` is an abstract type for some reason, but you can just make the whole chapel the sanctuary subtype
-The listening post is kinda fucked in general: it's not meant to be on station, the wall between the foyer and the cairngorm teleporter is simulated, and I'm pretty sure the buddies in there are just hostile to everybody. Also the strelka isn't appropriate.
-The 3 N2O cans in the patho sector are, but it might be fine if you replace them with a static N2O tank (probably enough to feed all the rooms too). The N2O pressure tank in engineering seems odd too, but I personally approve. :P
-Quartermasters don't have engineering access, so they can't open one of the doors to get in their office. When they get there, they're missing a bunch of manufacturers and a way to easily get crates out front.
-Your engine is hotwired by default. To map SMESes properly, you need to lead the raw engine output into `/obj/machinery/power/terminal`s that feed into the SMESes. Then you can have a wire from under the SMES to the station grid. If you need an example cog1 is probably easiest, because the raw engine wire is brown and easier to follow because of that. When you fix this, also look at the spare SMES in security.
-Speaking of that room with the SMES, dedicated execution chambers *really* aren't a good vibe.
-I'm not sure if the mining teleporter functions on space maps. The mineral magnet is also rectangular and I think it needs to be square to function.
-Jazz lounge looking straight onto a major hallway limits its capacity for crime.
-The inputs to the huge toxins burn chambers and the mixer need pumps/valves.
-All of medbay has just one nanomed to supply them.
-6 tasers and 4 eguns in the armoury is fairly spicy. Might get antags to pay attention to the dang place though. :P (Probably ask others for second opinions on that one, I'm not a sec/combat balance person)
-I appreciate this is probably because the map is a draft, but there's so few windows into places.


Minor issues/concerns

-Red crosses in medbay are (to my knowledge) discouraged, so the one in medbay's floor should maybe be changed.
-If the free-standing bit of medbay is meant to be another pathology lab, it's missing an autoclave
-I don't remember patho that well but 8 centrifuges seems way superfluous 
-Armory auth computer isn't an appropriate match for the 
-Also I don't think it can do any harm, but why the nuclear centrifuge in there?
-I appreciate you've got the cleanerbot in robotics, but usually there's a drain near the operating tables too
-The robotics database is unused and I think doesn't do anything
-You don't need to add Faith to the chaplain's locker, they spawn with it.
-The long couch (whose comical length I love) doesn't have proper ends
-Some of the chapel pews are missing the top bit
-Library doesn't need the torpedo guide if the map doesn't have torpedos
-Space tile under the NAS-T in the listening post foyer, and another under a conveyor in the ghostdrone factory
-A few misplaced firedoors around the bridge
-The bridge windows need electrification
-I think data terminals need a wire with a node at the center to work, and if I'm correct in that the mainframe isn't 
-Missing turret control for the computer core
-Missing corner in that nasty disposal pipe in west medbay
-Missing wire for the APC to that main engineering/atmospherics room
-What are those carousel units in engineering going to power?
-Missing wall in the telesci pad room
-Missing mug rack in the medbay break room (critical, I know), same with sec.
-The shower room in the medbay/bar cluster is only accessible via maint?
-EVA missing tank dispenser and RCD crate, luminol grenade is kinda weird to see there?
-Missing bit of pipe under a chute in botany
-Sauna pipe junction is probably non-functional, but there's dedicated junctions instead. (I think you have to search for manifold)
-Missing wire corner near in sauna/barber maint
-I haven't heard of the prototype Nano-fabricator (the blue tinted one), but it seems like it has no recipes.
-Prototype RCD in tool storage is, I think, a deathtrap from an azone.
-A few of the main station sections are done in plating instead of floortiles
-Medbay hand trader is missing the supply marker
-Missing cap's spare
-Misplaced bedsheet in bridge wall.
-Bar doesn't have a reagent heater, bartender is kinda just missing the stuff normally in their office too.
-Robotics is missing the borg parts crate I think
-Chemistry is missing a bunch of glasswear and stuff, also there's no source of welding fuel in all of sci.
-Clock 188 in the HoS room?

**Review by ZeWaka — CHANGES_REQUESTED** [review]
No reviews will occur until un-drafted.

**Comment by cheekybrdy** [comment]
Really sorry about mentioning wrong person. So sorry!

**Comment by nefarious6th** [comment]
likewise, not a dev and probably won't have further time to follow the progression of this, but some things from my look at it in sdmm
**general**
- less of an issue in this construction, but there was a previous map named samedi that similarly had the modular department layout and in playtesting and it's brief run it had a lot of chokepoint issues
- i beeelieve every map has now moved off of using the old top-down door and window assets and currently use the 3/4ths perspective ones. you have a mix of the two styles in here which is a little jarring. i also understand some of the doors from the top-down perspective weren't copied over to the 3/4ths perspective and have tried to duplicate some before for destiny; i know it's a large effort but if there's an intent to use the old-style departmental doors, like the glass airlocks in command or the green ones in civilian areas, it might be worth the effort to either make up the new door icons of the top-down ones into 3/4ths or get someone else to work with you on this. i might have some of these doors kicking around as an unfinished sprite bundle somewhere too, if you want to finish them or use them as your base, but no guarantees i can find them.
- the window spawners you have on the map right now are all the thindow/wingrille combo spawners. if you're looking for the full-tile windows, the spawners you want will be bubblegum pink (for plasmaglass), and blue with the center square with the grate on it filled in blue as well.
- i'm part of the evil minority that doesn't mind so much piping routes under walls but just consider that if someone were to try and fix or divert pipes for loafing or singularity-feeding, they'd have to take some walls down too.
- wiring through walls may be slightly more evil though and usually wiring runs under doors on most maps in the majority of spots for ease of fixing/cutting/hotwiring. i think oshan does a pretty good job of this, if you wanted a frame of reference for what it might look like.
- i don't know what the general dev opinion is on the walls from donut 3, but from what i remember, the preference is not towards using them; this gets into that "if you have someone who can do it," area like the doors; sadly making walls is a task i don't think tons of people enjoy, so making a unique wallset isn't super urgent or essential
- most department nodes only have two ways in or out: airbridges or busting down an exterior wall/window. if an ai were rogue and to retract and bolt airbridges, few departments might have a way to get everybody out without breaching the place outright. space-faring friends like lings can also easily be shut off from the station and trapped outside. a few airlock entrances/exits like what donut 3 has might be good.
- maintenance should be thoughtful; it can be essential on RP for radstorms or in general as alternative routes; science is lacking in maint capacity, i think (for obvious reasons), but that could potentially be deadly in blowouts
- there's a lot of wall-mounted objects that are On walls, but that puts them in the walls, which can cause weird problems sometimes with things intended for player use. rechargers in a few places are like that, for example. objects for use are usually on the floor tile in front of where they appear on the wall, and then just pixel-shifted to look as if they're on the wall, but the locus of their interactability remains somewhere in open floorspace
- because of the 3/4ths perspective, stuff on southern walls just has a tendency to look really weird and cramped; try to maximize the space on the other cardinal directions of walls for a better fit of sprites of things like APCs and rechargers
- missing some freebies like gas masks and tools in maint that those evil staffies need to live (this is what they tell me, at least)

**silicon**
- check for floaters, there's some floating ai turret controls, lights, and cameras. you can pixel-shift the controls onto the wall from the tile it's on right now
- APCs like the mainframe deploy their own type of terminal on the tile you placed them on and thus need a wire node there; there's a few spots where you have the full-tile wire that won't power the APC on top of it
- ai needs a terminal underneath too for some DWAINE-related things

**sec**
- is just really red. you have good flooring on the medbay dept that i'd like to see maybe some of the same principle in security with less red and more black on main halls to sort of visually break the place up
- the brig timers are floating
- i think it came up in talking about some older maps that had duplicate locker sets, but eguns and tasers are balanced in a way where having the 2/6 or 7 of them you'd normally have in a round is part of balancing, so introducing twice as many of each could definitely cause some balance disruption
- check rechargers here
- syndie agent corpse in the top right is a dialogue object and may prompt some sort of interaction or have unnecessary related description; just double-check and potentially make into its own decal object type

**science**
- check the couple of walls and doors in the north that are at diagonals; those are technically not airtight, which is why tiles for walls and such always connect to each other
- check junction boxes are on the walls
- the LRT sort of blocks the entry into the telescience room, it may need to be moved around
- test chamber and tsci pad are prone to explosions and probably need reinforced flooring like what you have in toxins

**med**
- cryo tubes require a hookup to a small oxygen and fan system in order to get cryoxadone to work effectively and for patients to not suffocate
- rotation on the one thing of tape for the monkeyvendor is off
- robotics has one table in front of a door on the left

**civ**
- hydro is a lil tiny for the amount of trays in there; imagine potentially 6 people trying to run around in there
- periodic janitor closets across the depts might be nice; janitors would see the most movement on this map and it might be hard to get back to home base
- it's worth noting, i know you pulled faith out of the locker, but the bullets you have there too probably need to go; kinetics are supposed to be harder to find ammo for but in this particular case the subtype you have for faith-specific bullets are actually coded to function a bit more like hollow-points and so they have an increased damage compared to the .22s you can print in general fabricators. those first four bullets are exclusive, and rather deadly.
- if this is a space map, the radio room would be redundant on the radio station that spawns on the other z-level. two record players could lead to spam potentially
- i personally am not super into 1-tile-wide hallways and would recommend changing the hallways around the merchant docks to be two tiles wide

**bridge**
- missing some of the external airlock access spawners; this is in each dept i think but i only noticed it here oop
- bottom left maint is missing an access spawner

**Comment by flrsh** [comment]
I don't think the team is currently interested in any new maps unless they bring something particularly unique and interesting to the table. Given that this seems to be your first shot at mapping and at contributing in general, I recommend first working on some smaller, more self-contained projects such as random rooms and asteroid field/trench prefabs. It's fine if you want to keep working on this map to practice and improve your skills, but I do not see us adding it to our map rotation at any point.

**Pull request closed without merging**
