### PR TITLE
Give radio show hosts unique looking headphones

### PR DESCRIPTION
**Pull request by BatElite**
[feat]
## About the PR 
Finished up a sprite for nice big headphones intended for the radio show host while making a sprite for Gannets' Comtac thing. Functionally no different from their not-a-captain-headset.
afbeelding

## Why's this needed? 
Finally something worth stealing from the radio station!

(Also it looks neat and fitting and makes the radio host easily identifiable)

## Changelog

```changelog
(u)BatElite
(+)The radio show host found a pair of vintage headphones in their closet, so they now spawn with that.
```

### CODE REVIEW

**Comment by penny64** [comment]
On the note of stealing them- add them to the antag objectives maybe?

**Comment by Yellow-Mushroom** [comment]
Super cool headsets!! Would you be down for me later adding some color variants as job rewards for them?

**Review by flrsh — APPROVED** [review]
Very cool!

**Review by Gannets — APPROVED** [review]

**Comment by BatElite** [comment]
Making them an antag objective is probably moot because the radio host is a late-join role. Only late traitors (and maybe spies?) would have a chance to get an objective for it.

I'm fine with colour variants myself, just be careful that if you make a red one it might get too similar to the sprite that the Comtac headset might use (Gannets willing).

**Pull request merged**
