### PR TITLE
removes duplicate phone.dm

### PR DESCRIPTION
**Pull request by DisturbHerb**
[CLEANLINESS][GAME OBJECTS]

## About the PR 
this removes the `phone.dm` in the `/machinery/phone` folder. this also moves the currently used (and most updated version of) `phone.dm` from `/machinery` to the `/machinery/phone` folder

## Why's this needed? 
i don't think we need two nearly identical files kicking about, probably, maybe

### CODE REVIEW

**Comment by DisturbHerb** [comment]
god damn, maybe i don't know which phone is the right one 😰

**Comment by ZeWaka** [comment]
have you tested this PR?

**Comment by DisturbHerb** [comment]
> have you tested this PR?

yeeeees. nothing seemed to be broken on the user-facing side, and it compiles. if there's something going on then i've missed it

**Comment by frawhst** [comment]
Will revert if this breaks phones I guess

**Pull request merged**
