### PR TITLE
Removes duplicate head of staff lockers from Destiny 

### PR DESCRIPTION
**Pull request by nefarious6th**
## About the PR
Removes the second set of lockers in the heads of staff's quarters on Destiny and follows from #2928 

## Why's this needed? 
Gear in the lockers is balanced for people to only have one set of it, not two sets.

### CODE REVIEW

**Comment by nefarious6th** [comment]
Classic me forgetting to update my fork with my own PRs...I'll reopen this in a minute or two

**Comment by nefarious6th** [comment]
Cleaned up now!

**Comment by pali6** [comment]
I see changes in non-Destiny files, I assume those were unintentional?

**Comment by ZeWaka** [comment]
it's because they based off a branch that their other removal PR commits got added to

**Comment by nefarious6th** [comment]
Let me know if I need to open this on a separate PR; I tried to save you all the duplicate PR problem and figured it'd be okay because all it would overwrite would be commits from my last PR that was merged, and it would just be overwriting the same stuff, so nothing realistically would change. I can always try this again on a clean slate, though. Sorry for the chaos on the commit history here.

**Comment by ZeWaka** [comment]
You either need to make a new PR or force push to this one with proper commits, yes

**Comment by nefarious6th** [comment]
This still needs some work because now everything should be okay on it except for one issue that undoes Flourish's movement of the tree on Manta into the bar. I am going to give that another shot tomorrow since I have some things to fix up for tonight, but big thanks to Adhara for the help so far.

**Comment by ZeWaka** [comment]
Going to be fixed?

**Comment by nefarious6th** [comment]
Fixed; sorry this took forever. Live and learn, I guess.

**Review by pali6 — APPROVED** [review]

**Pull request merged**
