### PR TITLE
Renames Density material property to Toughness

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
All instances of density in material code have been renamed to toughness. This pr plans to have a child pr soon that reintroduces density for the weight of materials. 

## Why's this needed? 
This should clarify on what toughness actually does a lot. Currently it is unclear from a player side how hardness and density interplay with armor and weapons. This should make it much more clear what exactly density does. 

## Changelog

```changelog
(u)Ikea
(*)The density material property has been renamed to toughness
```

### CODE REVIEW

**Comment by amylizzle** [comment]
*screams in #8767 *

**Comment by Tarmunora** [comment]
Eh, don't really see the need myself.

**Comment by ThatFiveGuys** [comment]
> Eh, don't really see the need myself.

The big thing this does is open the door for a new stat for the weight of materials, which should add a vector to make matsci armor way more interesting

**Comment by amylizzle** [comment]
Why not just use density to calculate weight where needed, since it's gonna be dependant on volume anyways?

**Comment by ThatFiveGuys** [comment]
> Why not just use density to calculate weight where needed, since it's gonna be dependant on volume anyways?

Because having gear punish you for using the better stuff is silly, i dont want the harder to get materials to be a sidegrade from the way easier to get materials

**Comment by amylizzle** [comment]
So then why not just create a new property and switch some uses of density onto the new property where appropriate?

**Comment by ThatFiveGuys** [comment]
> 

Current values are balanced around there effectiveness for armor, so it seems smarter to use the stat already balanced for armor for armor.

**Pull request closed without merging**
