### PR TITLE
Don & Doff Actionbars

### PR DESCRIPTION
**Pull request by Azrun**
[balance][add to wiki][help wanted]
## About the PR 

*Adds actionbars when wearing or removing certain equipment.
 - https://docs.google.com/spreadsheets/d/1GjsdWvnHx28w02Qcdg5odcij0lJ5XgKzsybwf2dfKOg/edit?usp=sharing
   - NOTE: This a preliminary pass of the don/doff times for an "unfamiliar" individual.  -1 takes no time.
 - Allow for training and "familiarity" to equipment interactions
 👨‍⚕️(Medical Training) - 👮 (Security Training) -👩‍🔧(Engineering Training)
   - Tanks/Jetpacks take 1/2 👩‍🔧 (Otherwise 2 seconds)
   - Firesuits/SUV Suit take 1/2 time 👩‍🔧
   - Welding Helmet takes 1/2 time 👩‍🔧
   - Spacesuits take 1/2 time 👩‍🔧 or 👮
   - Gas Masks takes 3/4 time 👩‍🔧 or 👨‍⚕️
   - EmergencyHood/Rad Hood/Chem Hood take 1/2 time 👨‍⚕️
   - Chemsuits/Biosuits take 1/2 time 👨‍⚕️
     - Paramedic Armored takes 1/2 👨‍⚕️ or 👮
   - Armor takes 1/2 👮
   - Helmets takes 1/2 👮
     - Space Helmets 1/2 👮or 👩‍🔧
   - HoS, HoP, and Captain gear use 1/2 to corresponding Head...
     -  Some regalia takes NORMAL time for those familiar with that class of clothing and 50% longer for those that aren't. 
     - HoS's Cape only really has actionbar for !HoS
   - Traitor/Nukie gear use 1/2 time ONLY for people assigned that role. (TODO)
 - Allow for effects to adjust equipment interactions.
   - Crime reduces time by 10%
   - Clumsy has 1/3 chance of increasing by 20%
   - Ethanol has chance scaled with consumption of increasing by 20% (not stacking with clumsy)
 - Small amounts of movement are allowed without completely stopping actionbar.

Global variable used as a scaling factor to allow for evaluation of feature.

- [ ] Additional development pending Developer interest.
- [ ] Address above TODO items.
- [ ] Additional pass on equipment.
- [ ] Break don/doff duration into constants to avoid magic numbers and standardize behavior.

## Why's this needed? 
Increases strategic depth/value by limiting ability for immediate tactical response by adding animation priority to changing equipment.  Favors aggressors who are equipped to deal with the defender's current equipment, as the state can not be immediately changed.  Additionally further action of the aggressor has the ability to delay or stop the defends ability to adjust their equipment.

Additionally this adds another lever to pull to adjust the value of a piece or class of equipment going forward.

## Changelog

```changelog
(u)Azrun
(*)Actionbars added to wearing and removing more complicated equipment.  Duration adjusted based on training, traits (clumsy), and drunkenness.
```

### CODE REVIEW

**Comment by Azrun** [comment]
I'll throw up a more comprehensive spreadsheet for review and comment, but preferably to a **smaller** audience iif interest is garnered.

**Comment by nefarious6th** [comment]
I've mentioned it before, I don't like this idea a tremendous amount; it seems like complexity of controls/strategy for no real purpose. Too "HRP-stylings", I guess. I don't like reductions of "on-the-fly" thinking because I think there's a wealth of unique gameplay made there specifically.

- Buffs changelings who can spacewalk with no problem pretty heftily; now no one can instantly follow and gear up along the way/immediately and jump out. You lose eyes on critical situations and potentially meaningful interactions. 
- Makes it more difficult to survive unplanned EVA moments like spacewalking, getting spaced, or ventings/bombings. 
- Makes retrieving bodies in space seem less likely; not worth the additional time input to gear up
- Extra unnecessary hassle between switching between armors/coats/suits for cosmetic reasons, extra unnecessary hassle between switching between backpacks/tanks. Sometimes I just toggle between them, sometimes I'll put the tank on my back if I think I'm in a spot where I might slip or crit and drop it if it's in my hand. This just clouds those interactions too much. 
- Minimal, but makes honorary coat transfers and stuff no longer a quick thing. 
- Minimal, but rolls back a bunch of cool outfit/cosmetic work people have recently done since I believe the new meta would instead be to target specific pieces of gear early in the round and equip them early and continue to wear them all round on the ///chance/// they're required in order to save time when it comes to spacing or confrontation. I expect a lot of people wearing orange EVA suits now. 
- Minimal, but may be confusing for new players.

I think there's different and better ways to adjust gear balancing; disorient resist was a notable recent one. Movement speeds would be one I'd like to see applied to some items before even touching on adding a whole new system. I'd rather just see nukie exosuit gear become non-removalable like the cursed mask, or some of the trinket NTSO/TURDs stuff is to prevent crew from sniping it after downing a nukie and going to fight other nukies, if that was a primary concern for this PR.

**Comment by Eagletanker** [comment]
My 2 cents
Space Suits are balanced by the fact it takes about 10 seconds or so to put on a suit and internals and it's not very useful as armour, and this is just artificially expanding the length to put it on and take it off while slowing down gameplay for anyone who isnt Engineering or Sec with no really fun thing to do other than stand still and wait for your suit to go on. Also puts any chase into sec favor, cause if your plan relies on drifting into the void on the next airlock against the sec officers who are faster than you, it means you get stunned and captured before you have a chance to finish putting on your suit. I think this just is needlessly making the game slower rather than the usual fast pace action and mostly equal playing field of goon

**Comment by Flaborized** [comment]
I feel like the issues this change addresses are definitely real balance issues that theoretically exist but the negative effect on quality of life this would impart on pretty much any part of the game where you gotta dawn or doff stuff makes it Not Worth It. 

I also think that having it be instant lets players feel more connected to those 'oh shit gotta get my protective gear on' moments. With your change, that moment becomes 'Oh no I hope the *bar* fills up before I die' instead of 'Oh no, _**I**_ gotta do something that will save myself'. I think the latter is much more satisfying in a game-feel sorta way and is a better mechanical representation of what's happening.

I also just don't see the point for regalia, or armor vests, or anything people wear all-round. Like, I don't think people put on armor vests right before a fight, they just wear them everywhere because they don't slow you down (not a bad thing at all). This would only really affect items that slow you down, and *armor items* (since I think combat is the most important thing hit by this change) that slow you down are actually quite weak now, or undesirable. It kinda makes the bad armor worse in that way.

**Comment by Camryn-Buttes** [comment]
Flaborized has succinctly summed up my thoughts better than I ever could have.

**Comment by Azrun** [comment]
Consider this as possible functionality for difficult to Don/Doff items OR items that should have a warning mechanism as to the ramifications of wearing it (straight jackets & _secrets._

**Pull request closed without merging**
