### PR TITLE
AI Text Status

### PR DESCRIPTION
**Pull request by Nexusuxen**
## About the PR 

Adds a scrolling text status option for the AI designed to appear similar to a command line screen. Includes a *flip animation that is the base animation, but 5x as fast.
The colors of the lines in the sprite will be determined by the AI's color, as the lines are an alpha layer and thus transparent.

Below: A screenshot of it used in-game.
image

Below: A gif view of the sprite itself.
<image src="https://user-images.githubusercontent.com/28785926/90447445-551cb780-e0b1-11ea-8c38-6aecbb8776c2.gif" width=160 height=160>

## Why's this needed? 

It's not **needed** per se, but it's something that some people said they'd use or like seeing in-game. ~~and i really really really want to use this as NEX-13 ALL the time~~

## Changelog

```
(u)Aft2001:
(+)Adds 1 new status option for AI, "Text", which is a scrolling text screen. Your AI color will change the color of the lines
(+)Also has a *flip animation! Technically!
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
definitely not worthy of 3 major changelog entries

**Comment by pali6** [comment]
Also missing author name in the changelog.

**Comment by Nexusuxen** [comment]
Fixed the 2 issues. Sorry about the bullets there, thought it was relative to the PR itself and not the code as a whole.

**Comment by ZeWaka** [comment]
> Fixed the 2 issues. Sorry about the bullets there, thought it was relative to the PR itself and not the code as a whole.

not following the format still

**Comment by Nexusuxen** [comment]
Alrighty, fixed now? Sorry, I rarely ever make PRs

**Comment by ZeWaka** [comment]
> Alrighty, fixed now? Sorry, I rarely ever make PRs

Nope :/ 
Try looking at another PR with a changelog or using the format provided when you open a PR.

**Comment by Nexusuxen** [comment]
Okay I am an idiot thank you so much. That should do it

**Comment by ZeWaka** [comment]
> Okay I am an idiot thank you so much. That should do it

It's still improper, but I'll just fix it for you.

You had:
```
(u): Aft2001
(-) Adds 1 new status option for AI, "Text", which is a scrolling text screen. Your AI color will change the color of the lines
(-) Also has a *flip animation! Technically!
```

The correct version is:
```
(u)Aft2001:
(+)Adds 1 new status option for AI, "Text", which is a scrolling text screen. Your AI color will change the color of the lines
(+)Also has a *flip animation! Technically!
```

**Comment by Nexusuxen** [comment]
OH. Yep. Thank you so much oh my god. Okay, yeah, not touching that part in the future at all. Sorry!!

**Comment by pali6** [comment]
Don't mind me, I just clicked on the wrong tab.

**Pull request merged**
