### PR TITLE
Cog1 Cloning Redesign

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
* Fork of #4776 which has since been abandoned
* Includes a number of fixes on the original PR

- wires under window not using nodes
- air pipe not using manifold
- missing light switch
- improper door access spawners
- fire alarm on window
- removes unneeded ai camera

image
image

## Why's this needed? 
* Make cloning less cramped

### CODE REVIEW

**Comment by Sovexe** [comment]
There's a sink on the door that I'll have to fix tomorrow

**Comment by Vaskritaya** [comment]
excruciatingly minor opinion: I sorta wonder if it wouldn't look better to swap the positions of the scanners and consoles, so that the consoles are next to the chutes. Would mean the chairs fill up the middle of the room more and give the geneticists more breathing room rather than being crammed into the edges of the room (just my opinion, others might disagree)

**Comment by Wisemonster** [comment]
I agree with Vaskritaya. It'll let the geneticist be closer to the chutes, and let the right side console user smoke without setting the fire alarm off

**Comment by Sovexe** [comment]
sure

image

**Pull request merged**
