### PR TITLE
heisen hotel

### PR DESCRIPTION
**Pull request by Laboredih123**
[DNM]
## About the PR 
Due to restructuring, we are now hotel chain.

image
image

## Why's this needed? 
👍

## Changelog 

```changelog
(u)Management
(*)We are hotel now.
(+)Servers 1 & 3 have been renovated, with 4 still under construction. Management recommends turning 'horizontal split' under your screen settings on.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
You're 2 months early

**Comment by Laboredih123** [comment]
> You're 2 months early

early bird gets the isometric sprites or somethin like that

**Comment by Laboredih123** [comment]
fuck you mean conflict, how could this pr possibly conflict

**Comment by Laboredih123** [comment]
although im closing this pr, id like to note that contributions to the branch remain open, so that someday we can have fully isometric heisen hotel.

**Pull request closed without merging**
