### PR TITLE
New pda sprites

### PR DESCRIPTION
**Pull request by Retrino**
## About the PR 
adds new fancy appearances to all the pdas with little details for each department.

## Why's this needed? 
pdas haven't gotten a touchup in a while. these ones are shiny and cool

## Changelog

```
(u)Retrino:
(*)PDAs now have shiny new sprites by Jinnerotto (Jinnerotto#8229 on Discord)!
```

Screenshot (208)

### CODE REVIEW

**Review by Gannets — APPROVED** [review]
Looks good to me!

**Review by flrsh — APPROVED** [review]
Very cute!

**Comment by MarkNais** [comment]
Hey Retrino,

I really like the new PDAs, well done and thanks for contributing! Specifically, the redesign gives me some real GameBoy design vibes, and I love that.
I do have some (attempted) constructive criticisms on the sprites, please don't take them personally. 
Generally: 
- The screen, antenna, d-pad, and two buttons below the d-pad stand out well. A lot of the rest of the detail blurs into abstract noise I.M.O.
- The color trimming on the bottom right sometimes looks like a chunk was removed from the PDA, not sure how to blend it better. Maybe less dark-pixels between the base and trim.
- Many times, the detail really resolves to noise, such as the bottom-brown PDA - resolves to a cracker like texture. Perhaps it is meant to be a speaker-grille? Maybe the dots need to be darker? No dots?
- The pixels of the form at the bottom left of the screen often break up the mold of the PDA. The colour banding can look nice (Like the top left), but in other cases it doesn't resolve well in my mind (looking at the other left PDAs).

Some specific cases:
- In many in-game situations, the staffie's PDA looks like it is made of a dark gold, while the Captain's looks like a banana yellow - SA's seeming to have more gloss than Captain's. I'd recommend trying to make the SA's a dull, matte grey. Make it look cheap, for the lowest tier on the corporate ladder.
- The clown's PDA isn't saturated enough I.M.O., the checker(?) pattern isn't very pronounced.

**Comment by pali6** [comment]
> I'd recommend trying to make the SA's a dull, matte grey. Make it look cheap, for the lowest tier on the corporate ladder.
Came here to say this ^. But I also agree about the clown pda. The other details Mark mentioned don't stand out that much too me but also I'm not an art person.

**Pull request merged**
