### PR TITLE
Adds Photocopiers to Various Locations in Oshan

### PR DESCRIPTION
**Pull request by DisturbHerb**
[QOL][MAPPING]

## About the PR 
Photocopiers are placed in Oshan's Bridge and Research.

## Why's this needed? 
I want to photocopy documents. I want to photocopy them *now*, without having to trek to the radio lab or the dorms. Essentially, this is just a QoL feature for bureaucracy nerds. Like me.

## Changelog

```
(u)DisturbHerb:
(+)Added photocopiers to various locations in Oshan.
```

### CODE REVIEW

**Review by flrsh — COMMENTED** [review]
Photocopier in research is okay, would strongly prefer not having the rest because they mess with the flow and outline of the rooms. And in general, people should be compelled to walk around the station; crew quarters isn't *that* far away.

**Review by flrsh — CHANGES_REQUESTED** [review]
Forgot to hit request changes, whoops.

**Comment by DisturbHerb** [comment]
Perhaps this PR was made out of my own, sheer impatience. I understand the rationale for only keeping the photocopier in Research, but I at least want to have one in the Bridge. From a roleplay perspective, it makes more sense for station command to have their own printer rather than the HoS or MD trudging to the crew quarters or radio lab to print.

**Comment by DisturbHerb** [comment]
*Really* wanted to keep the one in QM, though :(

**Comment by flrsh** [comment]
> Perhaps this PR was made out of my own, sheer impatience. I understand the rationale for only keeping the photocopier in Research, but I at least want to have one in the Bridge. From a roleplay perspective, it makes more sense for station command to have their own printer rather than the HoS or MD trudging to the crew quarters or radio lab to print.

How about the netcafe? You could remove the table with the scanner and put the photocopier there?

image

**Comment by DisturbHerb** [comment]
> How about the netcafe? You could remove the table with the scanner and put the photocopier there?
I like that idea, but would that also involve the removal of the photocopier from the Bridge?

**Review by DisturbHerb — COMMENTED** [review]
oh wait i forgot, i removed every single one other than the research and bridge ones TBD

**Comment by flrsh** [comment]
> I like that idea, but would that also involve the removal of the photocopier from the Bridge?

Yes. Also, sorry, I just made some changes to Oshan and now you have merge conflict. You can either (a) close this PR, create a new branch based on the latest master, and remake your changes (b) hard reset to the commit before your change, pull from master, make your changes, and force push to this branch (c) have me add your changes and add you as a co-author. 

Sorry about this!

**Comment by DisturbHerb** [comment]
Yeah, I'll close this PR and have you make the changes according to your specifications; with the new photocopiers in the netcafe and Research. Would anyone miss having a scanner in the netcafe, though?

**Comment by DisturbHerb** [comment]
> Yeah, I'll close this PR and have you make the changes according to your specifications; with the new photocopiers in the netcafe and Research. Would anyone miss having a scanner in the netcafe, though?

**Pull request closed without merging**
