### PR TITLE
Adds some very legal hats

### PR DESCRIPTION
**Pull request by Esstoo**
[CLOTHING][FEATURE]

## About the PR 
Adds a Nanotrasen version of the Syndicate Hat and the Very Syndicate Hat, producing lavender instead of miasma.
Fixes the Syndi hat Inhands Sprites a bit

## Why's this needed? 
Nanotrasen wants to show off too.

## Changelog 

```changelog
(u)Esstoo
(+)Nanotrasen has started "Production" of Nanotrasen approved headwear.
```

https://github.com/goonstation/goonstation/assets/88528068/8397786a-b8a5-42cc-a704-2bce8201362e

### CODE REVIEW

**Comment by Glamurio** [comment]
Always a fan of visible sprites in the PR so people don't have to download the DMI to check.

**Comment by Esstoo** [comment]
> Always a fan of visible sprites in the PR so people don't have to download the DMI to check.

You can check the Icon diff bot in the "checks" tab to see any changes to icons without downloading the .dmi file
I've still added a video, but you can still check the bot to see individual North, East, South and West Sprites.

**Comment by ZeWaka** [comment]
Not a huge fan

**Comment by MintyPhresh** [comment]
Fine with this as admin-only but if this was player-obtainable it would get old quick

**Comment by WALPVRGIS** [comment]
Not really a fan (we don't need a NT version of every Syndicate thing that exists! But new/unique NT-branded stuff would be cool) Having it produce Lavender is thematically a bit strange to me? I'd rather the lavender effect be a unique thing for botany to produce, but also it doesn't really scream Nanotrasen to me 🤔

**Comment by Esstoo** [comment]
I'll close this for now, Until I can find ways to improve on this.

**Pull request closed without merging**
