### PR TITLE
Remove small bots from robotics fabricator

### PR DESCRIPTION
**Pull request by Tarmunora**
[REMOVAL]
## About the PR 
Remove the ability to print robots (secbot/etc) from the robotics fab

## Why's this needed? 
There are perfectly good construction recipes for these bots that are completely trivialized by the ability for a fab to just spit out a half-dozen bots at the push of a button.

## Changelog

```
(u)Tarmunora:
(*)Removed small bots from robotics fabricator
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
I would mainly advise removing the secbots, but I guess the others could be gotten rid of as well.
Can mechanics scan bots to produce them with their fabricator? If so, we should maybe consider if that should be removed too.

**Comment by j-awn** [comment]
maybe the hand-crafted small bots could have special features or more customization options? reward people for taking the time to lovingly assemble their very own securitron... or medibot.

**Comment by MarkNais** [comment]
Handmade bonuses would be neat, but I've often thought the bot manufacturing was too trivial

**Comment by moonlol** [comment]
This change is just going to make the other bot types, especially floor and fire bots much less used, if at all. Imo just remove sebot and maybe medbots, the rest are fine and already heavily underused

**Comment by TTerc** [comment]
I think the best solution would be to change the fabricator recipe for the secbots, something as simple as bohrum/dense metal requirement would make spamming secbots a little bit more difficult
I'm against the removal, since it's an underused feature anyway, as Moonlol said. And you either see people spamming secbots or printing medibots/cleanbots, rarely

**Comment by Tiggersaurus** [comment]
I regularly make use of most of the little bots, especially when there's no robotics peeps. One medbot and sanibot each for robotics and medbay normally. Pls no take away ;-;

**Comment by Kyle2143** [comment]
It'd make me sad to see the AI be unable to make bots itself. I wish it had some way to do so if we do this.

**Comment by mordent-goonstation** [comment]
If this PR is to be merged, I would like for there to be an easier way to gather the items needed to construct the assorted bots. With #2442 there's easy access to medkits to make medbots, but I think that this will make it _very_ hard to make secbots due to the need for both a stun baton and a helmet. I'm sorta okay with that, but I would look to make the more common ones (e.g. the sanitation drone - which needs a bucket) a little more accessible.

Medbay's bloody enough as it is.

**Comment by MarkNais** [comment]
Per Morden't comment, perhaps adding buckets to the general fab and the jani-vend (if it isn't already in there).
If you're dipping into fab code, maybe add hard-hats to the mining fab too (for mining drones) (And maybe remove BELOVED digbot from it too)

**Comment by Tarmunora** [comment]
closing this, going with the idea of making them (notably med/secbots) more expensive instead. See #2497

**Pull request closed without merging**
