### PR TITLE
Cybernetic hypospray context menu

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[FEATURE] [QOL] [SILICONS]
## About the PR 
Turns the `tgui_input_list` menu for the cybernetic hypospray into a `contextActions` menu.

image
The menu does not close on movement, and the actual names of the chems are shown on hover.
Also allows for future reagent-based context action menus.

## Why's this needed? 
Much nicer to use.

## Changelog

```changelog
(u)LeahTheTech
(*)The Cybernetic hypospray now uses a shiny new context action menu.
```

### CODE REVIEW

**Comment by Saicchi** [comment]
I get why you used `KI` for Potassium Iodine but shouldn't it be `Pi` so its in line with the others?

**Comment by TobleroneSwordfish** [comment]
My reasoning is that it's the only one where the abbreviation is the start of two words, so they should be capitalised? I dunno if that makes sense.

**Review by virvatuli-gh — COMMENTED** [review]
I don't know enough about the code to review and approve this outright but I love the idea. Much more player-friendly instead of cycling the object in your toolslot.

**Review by virvatuli-gh — APPROVED** [review]
This works as intended and rocks, and I'm not interested in seeing it go stale, so it's going in now.

**Pull request merged**
