### PR TITLE
Lets janitors parry csabers and katanas with mops

### PR DESCRIPTION
**Pull request by ryebek**
## About the PR 
Puts parry code into items.dm, so its an item level proc, and makes janitors able to parry anything under /obj/item/sword and /obj/item/katana with a mop. Depending on feedback, might make it necessary for the mop to be in their active hand.

## Why's this needed? 
People get salty as fuck over csaber and katana rampages,  and I thought this would be a fun dumb thing to add. Also I love watching janitors clean up after rampagers.

### CODE REVIEW

**Comment by Tarmunora** [comment]
Might be better as ASS_JAM content

**Comment by Gannets** [comment]
I actually think this is hilarious. Maybe give it a fairly high chance to destroy the mop in the process?

**Comment by ryebek** [comment]
Right, after some discussion on discord, I'm gonna be adding a 33% chance for handle_katana_parry to break the mop, and a 69%(haha funny sex number) chance for handle_parry. But I'm also working on a feature creep that'll make it work on mop health rather than chance, so I'll be making a PR for matsci mops sometime in the next 10 years.

**Comment by Kyle2143** [comment]
I like the change, I think it's funny and fun. But I can't, in good conscience, merge this in the state it's in. That's mostly my fault though.

When I made the parry functionality originally; I did it with an extremely specific use-case in mind, namely only katanas and csabers being able to parry blows from eachother. As I think you've seen in making this, I did not make this "system" scalable or extendable even a little bit. It was a total hack to put it bluntly. 

For some time, I've wanted to re-write it because after seeing how it turned out gameplay wise, I thought it would be fun to add to more items. But I can't do it in the state this is in right now. It needs two things to make it a good addition to the code, I think:
1. It needs to be a more generalized proc, instead of having both handle_parry and handle_katanaparry on obj/item.
2. I hoped to have it incorporated into mbc's intent and block changes that he'd been toying with so I was sort of waiting until those were finished, but mostly I waited because I'm lazy.

**Comment by ZeWaka** [comment]
Linter failure.

**Comment by Kyle2143** [comment]
Closing this for now. Will add when parrying is reworked, but that's contingent on some other changes.

**Pull request closed without merging**
