### PR TITLE
Loose borg parts now have appropriate/non-generic sprites

### PR DESCRIPTION
**Pull request by BatElite**
[CLEANLINESS]
## About the PR 
Short version:
This PR shuffles some things around so that loose borg parts now show sprites matching how they look on borgs - light parts no longer look like standard parts when they're not attached to a robot frame, same for reinforced limbs etc.

borglimbs-preview

Tedious detail:

I've matched the naming convention for loose parts (in robot_parts.dmi) and the appropriate mob limbs (in robots.dmi), and then reused some code to produce an icon_state for every limb. Hopefully that'll encourage future additions to follow the naming scheme. Mostly things are more consistent between the two files now. The limbs in particular had different naming schemes between the two.

Loose heads don't reference the mob sprites anymore, which means they don't face directions. With the graphics for loose and attached separate, it should now be relatively easy to make sprites _specifically_ for loose parts. I didn't, most of this stuff is just front-facing mob parts but centered in the canvas.

Servotron chest (the ribs) and light limbs have been given some near-transparency to make them easier to click on.

I've removed the "{part} + o" sprites, which I think were once layered on top of frames but aren't referenced anymore. They were a bit confusing in there.

The only changes to robots.dmi are state name changes, I didn't touch the actual graphics.

--

Since half of this PR is renaming internal stuff it's well possible I've missed or messed up a part, but I'm pretty sure I tried them all.

## Why's this needed? 
It's very nice if things look like what they are.

(Someone specifically requested I fix light chests, hence the branch name, but if it's worth doing... :P)

## Changelog

```
(u)BatElite:
(+)Loose cyborg parts now match how they look on borgs.
```

### CODE REVIEW

**Comment by comradef191** [comment]
YES YES YESSSSSS

**Comment by BatElite** [comment]
Yay!

I was thinking how/where to let you know, f191, but you already found it. :P

**Comment by Tiggersaurus** [comment]
Eeeeeeeeee

**Comment by ZeWaka** [comment]
holy shit i didn't know that these had different item states

**Pull request merged**
