### PR TITLE
Fix monkeys picking up huge objects

### PR DESCRIPTION
**Pull request by monkeymilesmoo**
## About the PR 
Hopefully monkeys shouldn't be going around grabbing super huge objects now
should fix:
https://github.com/goonstation/goonstation/issues/13636
https://github.com/goonstation/goonstation/issues/13793

## Why's this needed? 
There's no way a monkey is stronger than me :,(

## Changelog 

```changelog
(u)monkeymilesmoo
(+)Monkeys are no longer bodybuilders
```

### CODE REVIEW

**Comment by Laboredih123** [comment]
accept it. monkey stronger. stop trying to stop monkey

**Comment by monkeymilesmoo** [comment]
😢

**Comment by monkeymilesmoo** [comment]
I can't code for nothin X_X

**Comment by CheffieGithub** [comment]
W_CLASS_GIGANTIC is used for items that can't be picked up at all. Bulky is used for items which don't fit in backpacks

**Review by Tarmunora — APPROVED** [review]
hm. I think a more generic solution would be better, but this is a good enough hotpatch

**Pull request merged**
