### PR TITLE
Increases sinks cleaning amount from 2 to 5

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Sinks now clean 5 hygiene per click instead of 2

## Why's this needed? 
Having to click a sink 50 times just isnt good gameplay, making it take 20 times I think is a good middle ground between discouraging (as you still want showers to be the better option), but not frustrating. 

## Changelog 

```changelog
(u)Ikea
(+)Sinks now increase hygiene better
```

### CODE REVIEW

**Comment by thegrb93** [comment]
Imo, they should only be able to raise your hygiene up to a certain amount, like max of 10 or 20.

**Comment by ThatFiveGuys** [comment]
> Imo, they should only be able to raise your hygiene up to a certain amount, like max of 10 or 15.

This would make sinks useless and Id rather not make hygiene management even more hell for doctors then it already is

**Comment by thegrb93** [comment]
I main doctor and I don't have issues. Besides, your other PR added chem protection to hygiene so it should be less of a worry with that.

**Comment by thegrb93** [comment]
I think every medbay has a shower inside/nearby though? And you can make your patients bleed less if you use the right tools.

**Comment by thegrb93** [comment]
Well I don't like that this essentially obsoletes showers.

**Comment by ThatFiveGuys** [comment]
Clicking a thing 20 times is still pretty tedious

**Comment by thegrb93** [comment]
You'd never get to that point since you could just click one of the plentiful sinks every now and then.

**Comment by thegrb93** [comment]
I think you should still get stink messages from the rest of your stinky body, so I'm standing by a hygiene cap on sinks.

**Comment by ThatFiveGuys** [comment]
Gameplay over realism

**Comment by thegrb93** [comment]
It's roleplay

**Comment by ThatFiveGuys** [comment]
If sinks being slightly better ruin your immersion I think thats on you

**Comment by thegrb93** [comment]
It's pretty dumb

**Comment by thegrb93** [comment]
> If sinks being slightly better ruin your immersion I think thats on you

To clarify, I think slightly better sinks is good, but they just need a cap as a tradeoff.

**Comment by ThatFiveGuys** [comment]
I just think a cap, even ignoring the mud of things like how would you dictate the regeneration of sink cleaning potential, would just make them feel pretty useless

**Comment by thegrb93** [comment]
Well I was thinking just a simple 'if you're above X hygiene, don't go any higher'. 20-25 would be fine I guess.

You'd need a separate hygiene counter for hands if you wanted to make it perfect, but that's overkill.

**Comment by ThatFiveGuys** [comment]
Just doesnt seem fun to deal with

**Comment by thegrb93** [comment]
> Just doesnt seem fun to deal with

What if the sink put it at the cap with a single click instead of adding 5? Then you'd just have to click once to remain above the stink line threshold.

**Comment by ThatFiveGuys** [comment]
That feels weird and I dont really see what it adds

**Comment by thegrb93** [comment]
Never mind then. This is still too much of a buff considering it takes about 8 clicks and lots of mouse movement to undress and dress for taking a shower.

**Comment by ThatFiveGuys** [comment]
Lot less tedious of movements, feel tends to matter a lot more then whats actually happening as people arent robots, and taking off your clothes and putting them back on tends to feel better then just clicking a single object repeatedly

**Comment by ThatFiveGuys** [comment]
I agree but outside of scope

**Comment by Kubius** [comment]
In a literal sense, yes, but it's pertinent to the balance discussion.

Here's an idea; what if the amount stayed at 2 or went up to 3, but there was an auto-repeating action bar for handwashing so you only get one chat message and don't have to spam click?

**Comment by Kubius** [comment]
It'd take about the same amount of time as before if the cleaning value were left at 2. Cleaning your whole body with handwashing is unrealistic, but you can definitely get up along your arms a decent way; if you wanted something of a compromise, it'd make sense to require that you're in a jumpsuit or armor and not something completely spacetight.

**Comment by Kubius** [comment]
Prepared aforementioned action bar in #11954 as a possible alternative to this.

**Comment by MarkNais** [comment]
#11954 was merged.
TAKE A SHOWER!
(or use one of the other power-gamey methods)

**Pull request closed without merging**
