### PR TITLE
Standardises The Kondaru Armoury

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Mapping] [Balance] [QoL] [Add To Wiki]

## About the PR:
In effect, this PR redesigns the Kondaru Armoury, as seen below, allowing for the addition of a phaser crate, two night vision goggles, a breaching hammer, and a box of flashbangs. The communications console has also once again been moved inside of the Armoury.

image

However, I would much rather this be seen as the first PR in a series of PRs working to standardise the various maps' armouries. A list of essential and optional equipment for armouries may be found here: https://hackmd.io/@Mister-Moriarty/BkmMgDLZs

When compared to the above list, in addition to the standardised equipment, the Kondaru Armoury also possesses:
* 2x Riot Launchers
* 2x 40mm Smoke Shells
* 3x Crowd Dispersal Grenades
* 3x Flashbangs
* 1x Flashbang Box
	* x7 Flashbangs
* 3x Emergency Auto-Injectors (Atropine)

## Why's this needed? 
Armouries really be standardised as to contain the same basic equipment as each other, while also being distinct in their unique own ways. As for Kondaru, the missing phaser crate is a inexorable peeve of mine; Kondaru is somewhat mid-to-high population map, Security should not require to rely upon Cargo for phasers, should the need arise to use them.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)Redesigned the Kondaru Armoury, adding a phaser crate, two more night vision goggles, one additional breaching sledgehammer, and a box of flashbangs. The communications console has been moved back inside of the Armoury.
```

### CODE REVIEW

**Comment by Kubius** [comment]
The map change appears good structurally, though I personally might make a few slight adjustments to the connecting causeway (bump left and right windows one tile west and east respectively, anti-biological crate on the left, comms computer on the right, no top left fixed chair, new top right rolling chair).

Thoughts on the topic of the armory standardization list:

- I think it's a good concept to establish standardized contents lists for any important storage room in general, Armory being no exception.
- Have you considered making your "essentials" section a prioritized list so smaller maps like Atlas can pick and choose the contents considered most vital?
- How did you arrive at the contents of this list? It seems reasonable enough, but standards generally ought to be arrived at by consensus if they're something every map is expected to adopt (Input Wanted tag might also be good here).

**Comment by Kubius** [comment]
Sensible response. In the case of the top thing, I'd actually consider moving the comms computer left / chair down and moving the anti-biological crate into the armory, but I think it makes reasonable sense to have it outside the armory so I no longer have a strong opinion on that.

**Comment by Kubius** [comment]
Would you like the "Input Wanted" tag? You'll potentially get more feedback that way. Elsewise, I'll just sign off on this as it seems overall alright.

**Comment by Mister-Moriarty** [comment]
I'll add it now.

**Review by Kubius — APPROVED** [review]

**Comment by Tarmunora** [comment]
I'd probably swap phaser crate and grenade crate in the essential/optional lists

**Review by ZeWaka — CHANGES_REQUESTED** [review]
x

**Comment by Mister-Moriarty** [comment]
> I'd probably swap phaser crate and grenade crate in the essential/optional lists

I should clarify that I have swapped them, as it is a tad difficult to tell in retrospect; the phaser crate has been moved to essential, and the grenades crate has been moved to lower priority, as requested by Tarmunora.

**Pull request merged**
