### PR TITLE
Resprites Surgical Instruments

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[Medical] [Sprites]

## About the PR:
Resprites scalpels, circular saws, hemostats, surgical scissors, enucleation spoons, and sutures.
Circular saws and surgical scissors will no longer choose between several different sprites.

image
image

## Why's this needed?
The surgical instruments currently look outdated when compared to other sprites, alongside the suture currently being nigh unclickable.

## Changelog:
```changelog
(u)Mr. Moriarty & Arthur Holiday
(+)Resprited scalpels, circular saws, hemostats, surgical scissors, enucleation spoons, and sutures. The wonderful circular saw sprite was kindly provided by Arthur!
```

### CODE REVIEW

**Comment by CaioFrancisco** [comment]
scissors looked fine imho and i'll miss the blood on the saw, but i'm still all in for this resprite

**Comment by Mister-Moriarty** [comment]
> i'll miss the blood on the saw

Sprites being pre-bloodied feels odd to me. If something needs to start the round looking bloodied, then it should be done through spawning cleanable blood on it using New().

**Comment by NightmareChamillian** [comment]
Looking very good! I'm still of the opinion that either scissors or the hemostat should be mirrored to aid at-a-glance differentiability, however.

**Comment by frawhst** [comment]
Could you flip the scissors/hemostat horizontally so all the tools are facing the same direction?

**Pull request merged**
