### PR TITLE
Chaplain Additions

### PR DESCRIPTION
**Pull request by TheTyrant25**
[FEATURE]
## About the PR
Adds new chaplain gear.
Things included:
- Resprited default bible to not have such a blatant christian cross. Also removed the name "the bible", instead replacing it with "holy text". 
- Add multiple new custom bible types with various themes (blank, eyes, dark eyes, blue, purple, X, green, skeleton, burnt, clowns, cluwnes, redwhite, redblack, bluewhite and sulphur)
- Adds new chaplain clothing with various themes (green robes and mask, weirdo jumpsuit and mask, burnt robes and mask, light hat and robes, and nature hat and robes)
- adds a new file, robe.dm, containing the chaplain gear like robes and masks, as well as moving pre existing robes and masks to there.
- Replaces chaplain equipment closets on every map with chaplain equipment vendors, which are job locked and have one of each bible type as well as all the old things that the closets had
- redid a lot of the code in bible.dm to be cleaner and work better with var editing.

## Why's this needed?
Using IRL religion in a video game is basically begging for controversy to occur. Fictional religions are safer. Old religious equipment has still been left in, this first part mainly refers to the resprited normal bible.
The goal of this project is to provide chaplains with extra props to use to enhance their gameplay. 

## Changelog

```changelog
(u)What, Tyrant, Rubi, Paco
(*)Add new Chaplain Gear for more variety in choice of religion.
(+)Adds multiple new bible types, multiple new chaplain clothes, and more.
```

## pictures
i hope the changelog doesn't break if it's not at the bottom
image
image
image
not including the bible icon states because there are a lot of them
image
image
image
image
image

### CODE REVIEW

**Comment by DisturbHerb** [comment]
i'd better still be able to be a protestant vicar with the 'oly bible, y'hear? /j

**Comment by deathrobotpunch** [comment]
so many runtimes

**Comment by TheTyrant25** [comment]
so many

**Comment by TheTyrant25** [comment]
> i'd better still be able to be a protestant vicar with the 'oly bible, y'hear? /j

yeah pretty sure just using a labeller on one of them with the name "Holy Bible" should have it return to pre pr behaviours

**Comment by Flaborized** [comment]
I think I said this in the Discord already but I'll say again here: I don't personally (this is my opinion and not an Official Dev View) like the idea of adding lots of reskins to Bibles, since Bibles have tons and tons of unique mechanics tied to them. They kill you instantly if you fart on them, have shared storage, can contain the chaplain's gun, "heal" people, and can damage two specific antags (one of which can't even hold the thing without giving themselves away and taking damage). I think an item with this many important features tied to it should have very consistent visuals, and I don't think making it less clear which item is/isn't a holy book that does all these things is worth the RP potential, especially when you can already make custom books.

**Comment by Glamurio** [comment]
> I think I said this in the Discord already but I'll say again here: I don't personally (this is my opinion and not an Official Dev View) like the idea of adding lots of reskins to Bibles, since Bibles have tons and tons of unique mechanics tied to them. They kill you instantly if you fart on them, have shared storage, can contain the chaplain's gun, "heal" people, and can damage two specific antags (one of which can't even hold the thing without giving themselves away and taking damage). I think an item with this many important features tied to it should have very consistent visuals, and I don't think making it less clear which item is/isn't a holy book that does all these things is worth the RP potential, especially when you can already make custom books.

Personally, I think the criticism is valid, however I also think the changes in this PR are VERY good QoL changes for the chaplain. I'd sooner remove some of the existing features from the Bible than to dismiss the ideas in here. 

Shared storage is arguably not necessary, the book farting thing is something that usually happens by choice (or by elaborate gimmicks), and the healing and damaging of antags is potentially the only feature which may be in contentious, considering any religion besides Christianity clashes with the lore behind damaging Vampires. 

Personally, I still don't see it as this big of a problem, despite its apparent complexity it's already a rarely relevant item.

**Comment by TheTyrant25** [comment]
only things left to do are getting the weirdo mask worn sprites and trying to figure out why the item_states are flat out just not working.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Long overdue review, although there are still quite a few bugs:
- All the holy text inhand states are broken, I'm not sure exactly why without debugging it but putting the inhands in the same file as the regular icon states might be the problem as afaik nothing else does this, consider moving them to `icons/mob/inhand/hand_storage.dmi` or similar.
- The worn icon state on the "weird mask" is missing, also is it meant to be a reference to something?
- The vendor is missing a panel open icon state.

On to Opinions:
- I really like the unique holy text sprites, but having them all available at once is a lot of bible items being put into the game and will also lead to them feeling less unique. I think having the chaplain pick a sprite at the start of the round would help with that and also reduce bible fart shenanigans a little bit.
- The green and burnt robes are jacket slot items that completely obscure the head but don't hide identity (all of this is weird). I know they're essentially recolours of the flock robe but that is also bad and there's no reason to have more of it.

**Comment by DisturbHerb** [comment]
I'm personally not happy about the complete removal of the current bible icon from the codebase, it should at least be an option to pick from in my opinion.

**Comment by TheTyrant25** [comment]
the idea is to step away from irl religions including christianity, at least that's what the original spriter said

**Comment by DisturbHerb** [comment]
For a universe that nominally has connections to real life events, cultures, and history in many aspects, it's strange to completely erase all references to real-world organised religion entirely.

Yeah, it's a video game where whether or not the lore is grounded in reality means nil, but having a chaplaincy role at all is gonna present potential avenues for abuse no matter what belief systems we choose to include. At least let those who can be tactful about it roleplay in the manner that they wish, no?

**Comment by SgtManGuy** [comment]
> For a universe that nominally has connections to real life events, cultures, and history in many aspects, it's strange to completely erase all references to real-world organised religion entirely.
> 
> Yeah, it's a video game where whether or not the lore is grounded in reality means nil, but having a chaplaincy role at all is gonna present potential avenues for abuse no matter what belief systems we choose to include. At least let those who can be tactful about it roleplay in the manner that they wish, no?

I had sprites for other religions and talked around about adding them. The general consensus (including from server staff, if I recall) was  "probably not a good idea". It feels wrong only having Christianity and no other real-world religions represented.

**Comment by DisturbHerb** [comment]
At the same time, Christianity being the only represented religion has been the status quo since... Eurghh.

**Comment by TheTyrant25** [comment]
i admit to have totally having lost track of the progress of this pr.

**Review by Tarmunora — CHANGES_REQUESTED** [review]
My personal opinions on the merits of the PR aside, which I may or may not get into later, some actionable items:

- seems to add a bunch of unused sprites in Chaplain_Extras.dmi

- having access to 12 bible items at once is kinda a lot. Maybe not an _issue_ but it is pretty weird feeling

- absolutely no clown/clwune bible. No, nope, not happening

**Comment by Tarmunora** [comment]
adding DNM for @Adharainspace

**Comment by TheTyrant25** [comment]
response too varied, scope too wide, change too big. Therefore; PR closing. Will probably atomize certain parts out to other, new PRs.

**Pull request closed without merging**
