### PR TITLE
Adding Photocopiers to more maps.

### PR DESCRIPTION
**Pull request by Emcee-Gore**
[MAPPING]

## About the PR 
It adds a Photocopier to (Oshan, CogMap2, Manta, Horizon and Destiny).
These are the most played maps which - for some reason do not feature one of these nifty machines.
They are way easier to handle than scanning and printing papers across the whole station; though spreading them has to be done manually.

Down below you see the areas I placed them Photocopiers at. Most are around the Crew Area, but some had to be placed close to Arrivals or the Bar due to space limitations on some maps.

Oshan:
Oshan
OshanSecond

CogMap2:
CogMap2
CogMap2Second
CogMap2Third

Manta:
Manta

Horizon:
Horizon
HorizonSecond

Destiny:
Destiny

## Why's this needed? 
Maps like Donut3 and CogMap1 already have them; I see only benefits in adding them to the other maps.

## Changelog

```
(u)Emcee-Gore:
(+)Added Photocopiers to (Oshan, CogMap2, Manta, Horizon and Destiny).
```

### CODE REVIEW

**Comment by Emcee-Gore** [comment]
I was told that Horizons map layout is purposefuly bad. I added to that. :)

**Comment by zjdtmkhzt** [comment]
For old feedback, see #1593 .

**Comment by Kubius** [comment]
Upcoming Kondaru fix batch PR #1629 handles photocopiers (including one in the pictured location), so those changes should probably be discarded.

Thoughts on locations you've selected:

- Oshan spot good. Maybe put one in northwest crew (bottom left corner of that 4x3 space), but not strictly necessary.
- Cog2 may want an additional few: my suggestions would be the bridge (move the utility tractor where the shrub is and put a photocopier where the tractor was), and potentially the net cafe (above the printer).
- Manta spot good, but maybe move table and photocopier to the left side of the room? Weird to have the photocopier ramming into a wall.
- Horizon spot is funny, but maybe have another one replace the table where the net diagnostics cartridge currently lives and move said cartridge to the east table by the other cartridges.
- Destiny spot is not good. Perhaps try the hallway south of Hydroponics, in the northwest nook right by the door - there's room there.

**Comment by Emcee-Gore** [comment]
I'll remove the Kondaru one,...

I tried placing it in the hallway south of hydroponics right next to arrivals but it was disliked...the area is already pretty cramped with several dozen people online.

**Comment by mordent-goonstation** [comment]
For Destiny, why not replace one of the computer setups here? https://goonhub.com/maps/destiny#l=158,169,1;z=2 
image

**Pull request merged**
