### PR TITLE
Flyable Eyewear

### PR DESCRIPTION
**Pull request by Conchuckter**
[FEATURE]
## About the PR 

This pull requests adds the ability for players to cause eyewear to fly off by attacking someone in the head with a weapon.
Helmets that cover your eyes stop your glasses from flying off entirely. 

The stability variable determines how often they get thrown off your face, with it needing to be under 30 to have your glass fly off at all. Getting hit in the face with a weapon lowers it and using help on your head, equiping and polishing your glasses increases it to a max of 100.

Stability also passively increases at a rate of 3 in the life loop.

[Video (This might download it to your computer so if you don't want that don't click it)](https://cdn.discordapp.com/attachments/890226559691157524/972006673038319666/Military_Lab_50_2022-05-06_17-25-24.mp4)

## Why's this needed? 

Adds another use to switching limb target during a fight and allows someone to combat against someone wearing sunglasses to protect against flashes, especially during a rev round.

My glasses! I can't see without my glasses! 🤓

## Changelog

```changelog
(u)Conchuckter
(*)You can now knock someones glasses off by hitting them in the head with a item, so make sure you keep them on your face by using self help intent to straighten them.
```

### CODE REVIEW

**Comment by Eagletanker** [comment]
This probably warrants a forum thread

**Comment by nefarious6th** [comment]
GOOD. now i'll take even more lunch money from nerds

**Comment by Conchuckter** [comment]
> GOOD. now i'll take even more lunch money from nerds
> 
> edit: oh, smacking sunnies off people you want to be able to flash is probably good too, yeah, also that

I made sure to make it so you couldn't break glasses with a flash because I thought that would be bad

**Comment by NightmareChamillian** [comment]
IMO chances should be more situationally changed by protection of the helmet and damage of the attacking item, as is this seems a little weird and wonky.

**Comment by nefarious6th** [comment]
> > GOOD. now i'll take even more lunch money from nerds
> > edit: oh, smacking sunnies off people you want to be able to flash is probably good too, yeah, also that
> 
> I made sure to make it so you couldn't break glasses with a flash because I thought that would be bad

yea, no worries. i mentioned briefly on the forum some counterplay options i like that i think this opens up. giving some wiggle room to vamps to be able to actually target sec team members is something i really like here; likewise if sec's got a problematic person running around with telecrystal glasses/sunglasses/whatever that they're having trouble catching, i like that a few smacks targeting the head might be able to break or destroy the glasses (whatever this ends up as!) to give a minute or two for the team to act and actually subdue the person.

**Comment by Tarmunora** [comment]
I don't think this is a good direction. We've been slowly moving away from pure RNG "i win" rolls in combat, and this would be a regression in that department.

**Comment by Conchuckter** [comment]
> I don't think this is a good direction. We've been slowly moving away from pure RNG "i win" rolls in combat, and this would be a regression in that department.

I'm gonna to try and make it still rng based but more controllable such as helmets preventing it from happening.

Also instead of glasses completely breaking in thinking either they can be repaired or they just fall off.

**Comment by colossusqw** [comment]
> I'm gonna to try and make it still rng based but more controllable such as helmets preventing it from happening.
> 
> Also instead of glasses completely breaking i'm thinking either they can be repaired or they just fall off.

I agree with the glasses falling off as them just breaking seem like they would be a pain to repair, and just falling off gives you a chance to recover them mid combat.
As for the RNG, wouldn't it be better to have it require a certain amount of hits or shoves to the head, then have a increasing chance of each shove, which would then naturally go back down if you weren't hit in the face for a bit?

**Comment by Conchuckter** [comment]
> > I'm gonna to try and make it still rng based but more controllable such as helmets preventing it from happening.
> > Also instead of glasses completely breaking i'm thinking either they can be repaired or they just fall off.
> 
> I agree with the glasses falling off as them just breaking seem like they would be a pain to repair, and just falling off gives you a chance to recover them mid combat. As for the RNG, wouldn't it be better to have it require a certain amount of hits or shoves to the head, then have a increasing chance of each shove, which would then naturally go back down if you weren't hit in the face for a bit?

I was maybe thinking something like a stability variable that when you get hit in the face goes down and when you click on yourself with help intent goes up, to control the chance of your glasses flying off.

**Comment by flrsh** [comment]
> We've been slowly moving away from pure RNG "i win" rolls in combat, and this would be a regression in that department.

Agreed.

I also agree that this PR seems to just make certain people's (e.g. medical, sec) lives harder, and also just makes targeting the head (+ welding masks) even more meta. I think the *idea* of hitting someone in the face with something and having their glasses fly off can be funny, but I think this implementation makes it too significant of a combat thing.

**Comment by Conchuckter** [comment]
> > We've been slowly moving away from pure RNG "i win" rolls in combat, and this would be a regression in that department.
> 
> Agreed.
> 
> I also agree that this PR seems to just make certain people's (e.g. medical, sec) lives harder, and also just makes targeting the head (+ welding masks) even more meta. I think the _idea_ of hitting someone in the face with something and having their glasses fly off can be funny, but I think this implementation makes it too significant of a combat thing.

Hey, I actually removed the pure rng aspects a bit ago, now you have to hit quite a few times for there to even be a chance that they fly off.

**Pull request closed without merging**
