### PR TITLE
Prevent unconcious emotes

### LINKED ISSUE #5868: It is possible to make loud emote sounds voluntarily whilst unconscious
Submitter: balarak
**Describe the bug**
It is possible to make loud emote sounds voluntarily whilst unconscious. This seems strange as by nature being unconcious means you have no control of your body
**To Reproduce**
Oh no I have been stung by a changeling
drool
drool
fall over
spam scream, fart and burp for 60 seconds despite being in no control of your body

**Expected behavior**
as soon as you fall asleep, all emotes should be disabled until you wake up

**Additional context**
it seems to me some people pick obnoxious fart sounds for their characters just for this purpose

Reported on: Goonstation 1 Classic: Heisenbee 2021-09-01 14:22:57

### PR DESCRIPTION
**Pull request by flappybatpal**
[BUG][BALANCE]

## About the PR 
Disallow voluntary emotes when unconscious (paralysis).

## Why's this needed? 
Scream, burp and fart function during unconscious but other emotes do not.
Currently the game allows changeling stung or other unconscious players to make a screaming racket, unconscious people aren't known for screaming.
Fixes #5868 

## Changelog

```changelog
(u)Flappybat
(+)You can no longer emote while unconscious.
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
I am unsure of possible knock on effects but I can't think of anything that is important that should be emoted while unconscious. We already block nearly everything.
Originally I tried setting src.emote_allowed but this wouldn't get cleared.
A possible alternative would be to change src.emote_allowed in paralysis but then this would get cleared if you emoted before it kicked in, which wouldn't be too hard with the three second SPAWN_DBG usually used to reset emote_allowed so we'd need to check anyway.

**Comment by Vaskritaya** [comment]
Does this only affect intentional emotes, or do things that force you to emote also get suppressed? For example, being given styptic on the operating table while anaesthetized currently makes you scream, which is a little silly.

**Comment by flappybatpal** [comment]
Involuntary emotes will still occur.

**Comment by millicentjwi** [comment]
ok but dont remove fart, thats pretty funny to do while unconscious

**Pull request merged**
