### PR TITLE
Let's revolutionaries see undisguised heads.

### PR DESCRIPTION
**Pull request by Wisemonster**
[FEATURE] [GAMEMODE] [INPUT WANTED]

## About the PR 
This pr is a draft due to being unable to test this on local.

This pr makes it so that revs can see who is a head of staff if they are undisguised.

## Why's this needed? 
Heads of staff currently can currently walk past a group of revs in plain clothes without drawing their attention due to remembering who is a head of staff being somewhat difficult during a rev round. This helps to let revs know who is a head of staff.

## Changelog

```changelog
(u)Wisemonster
(*)Converted revolutionaries can now see who is a head of staff if they are undisguised.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Heads shouldnt be able to disguise to hide themselves in the crowd as its just very unfun, I think having disguised heads not having the icon is bad

**Comment by Wisemonster** [comment]
I could change this to simply let revs see heads even if their disguised. Would be less coding as well.

**Comment by ThatFiveGuys** [comment]
> I could change this to simply let revs see heads even if their disguised. Would be less coding as well.

Id personally like this

**Comment by CaioFrancisco** [comment]
that's a really awkward change. headrevs are supposed to be the only ones who see heads no matter what, so they actually matter to see through lies instead of being the ones who rev everyone. i'm full in to let revs see heads but only when they are not disguised.

**Comment by Tarmunora** [comment]
revs already have a fairly hefty information advantage (knowing exactly who their allies are)
Don't really think they need even more of that.

**Comment by Wisemonster** [comment]
Alright, I think I'm gonna change this back to being able to see undisguised heads, but not disguised heads.

**Comment by Wisemonster** [comment]
I think #11015 is a better solution to this problem.

**Pull request closed without merging**
