### PR TITLE
Disable hostile critters from being pets

### LINKED ISSUE #18598: Pet person pets seem to have aggressive AI in some cases
### Labels

[BUG]

### Description

Seen with wasps and geese

### Steps to reproduce

1. Spawn with pet person
2. Wasp
3. AAAA

### Expected Behavior

I expected them to be tame!

### Additional Information & Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Knipje**
[Balance] [Critters]

## About the PR 
Removes the option of wasps spawning in as pets and immediately attacking their owners.

Fixes #18598

## Why's this needed? 
Pets should be polite and not murderous.

### CODE REVIEW

**Comment by Retrino** [comment]
wasps makes sense, but why snakes and scorpions? theyre tameable mobs

**Comment by Knipje** [comment]
mb misread code there and thought they wouldnt/couldnt be domesticated

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
The issue is that the pet person code is meant to give them a "tame" AI but doesn't, there are several other hostile types that won't be covered by this PR

**Comment by TobleroneSwordfish** [comment]
[7391fa2](https://github.com/goonstation/goonstation/commit/7391fa20116de976260b804baca880fb45b095b9)

**Pull request closed without merging**
