### PR TITLE
Adds drip clothing to the clothing booth

### PR DESCRIPTION
**Pull request by Sir-Mora**
## About the PR 
adds drip clothing to the clothing booth with a suit item, jumpsuit item, and shoes.
monkey sprites are already made for all 3 as well.

## Why's this needed? 
drip would be funny and fashion is cool 😎

### CODE REVIEW

**Comment by DimWhat** [comment]
I dislike this meme.

**Comment by Yellow-Mushroom** [comment]
Clothing booth is very,, findable. Like means everyone can get one every round with very little work. I’d prefer these be in a prefab of some kind where people have to put in work to get a more meme-y pair of clothing

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
icons/obj/clothing/overcoats/item_suit_gimmick.dmi, the clothing doesn't have a name

**Comment by Sir-Mora** [comment]
> icons/obj/clothing/overcoats/item_suit_gimmick.dmi, the clothing doesn't have a name

fixed

**Comment by alexeric123** [comment]
I *think* people dont want this in the clothing booth, maybe just add the items for now? to use at admin discretion

**Comment by virvatuli-gh** [comment]
These kinds of flavour-of-the-month meme references only "work" if that month wasn't a year and a half ago, and honestly this one wasn't good to begin with. Really not that interested in seeing this kind of clothing in the game, even if it is just ironic.

**Comment by winterboekje** [comment]
goon arc'teryx update

**Comment by virvatuli-gh** [comment]
Closing this because the PR doesn't have any effort put into it (no screenshots of the items, no description other than "it's drip clothing). Not interested in having this kind of thing added to the game at this time.

**Pull request closed without merging**
