### PR TITLE
No eating/drinking/pills with gas masks

### PR DESCRIPTION
**Pull request by Valtsu0**
[Game Objects][Balance]
## About the PR 
Prevents eating, drinking and swallowing pills while wearing a gas mask.
Does not apply to nukie masks
Does not prevent others from force feeding you as that is arguably a buff.

oh also adds pronouns to some messages near the changes
## Why's this needed? 
It's mostly to make some reason not to wear one, even if a quite small one.
Should make people take off the gas mask sometimes, at least on rp.
Needing an extra hand to take a pill might do something on classic.

## Changelog 

```changelog
(u)Valtsu0
(+) You can no longer eat, drink or swallow pills while wearing a non-syndicate gas mask
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
#9196 was a previous PR with a similar proposed change.

**Comment by Valtsu0** [comment]
Both of those are from over 2 years ago.

**Comment by AXLFAN2000** [comment]
stopping nukies from eating their nukie donk pockets in combat is a bit of a nerf

**Comment by Valtsu0** [comment]
forgot about those, i'll change it

**Comment by pgmzeta** [comment]
It's weird that it stops you from eating but not getting force fed. Previously have thought about preventing chugging with a gas mask as a Minor Nerf instead of full eating restriction.

**Comment by IPling** [comment]
Personally I find this a confusing mechanic for newer players. As to them it seems extremely arbitrary to only apply to gasmasks, which becomes even more arbitrary as nukies get an exception.

With balance its eh. Of course its a small one which is fine, yet I feel like the weight of the inconvenience for the majority of players outweighs the benefits this PR brings.

**Comment by Valtsu0** [comment]
Third time was not the charm

**Pull request closed without merging**
