### PR TITLE
Fix foam dart barrier duplication

### LINKED ISSUE #8700: Foam Dart Duplication
### Labels

[MINOR]

### Description

Foam darts duplicate on hitting a security barrier

### Steps to reproduce

1. Find a foam dart gun
2. Produce a barrier
3. Fire foam darts at barrier, one will drop on hitting the barrier, and a duplicate will bounce back and drop again.

### Expected Behavior

The dart should either drop on hit or drop on reflection, not both.

### Additional Information & Screenshots

Reported by: Andy123XV
On server: Goonstation 1 Classic: Heisenbee
Round log date: 2022-05-23-08-23
Reported on: 2022-05-23 09:08:41

### PR DESCRIPTION
**Pull request by pgmzeta**
## About the PR 
Changes foam dart spawning to be either on hit or when it stops moving due to maximum shot distance, instead of when it's deleted.

## Why's this needed? 
Fixes #8700

## In-game Demo
https://user-images.githubusercontent.com/91498627/170890518-c72db4e1-cc77-4478-99e9-ac7244880bb7.mp4

### CODE REVIEW

**Comment by ZeWaka** [comment]
This seems snowflackey and incorrect.

**Comment by TDHooligan** [comment]
it may be appropriate to instead move the dart creation code to 'on_hit' and 'on_max_range_die', similar to AEX slugs.

**Comment by Tarmunora** [comment]
Would probably be best to add better bounce handling (e.g.: an on_bounce proc that would called instead of on_end, etc etc), but I don't have a clear mental picture of how to work that one out myself rn, so 🤷

**Comment by pgmzeta** [comment]
on_bounce was my gut reaction, just thought it might be an overblown solution for this one projectile.

That said, I'm sure people will find good uses for it once in place :)

**Pull request merged**
