### PR TITLE
TGUI Freezer

### PR DESCRIPTION
**Pull request by pgmzeta**
[GAME OBJECTS][UI][QOL]
## About the PR 
Lifted the core knob/temp display UI element from the reagent heater/cooler for the freezer
image

## Why's this needed? 
TGUI :)

### CODE REVIEW

**Comment by ZeWaka** [comment]
image

**Comment by pgmzeta** [comment]
> image

added to PR desc

**Comment by ZeWaka** [comment]
> > image
> 
> added to PR desc

y so tall, so much blank space

**Comment by pgmzeta** [comment]
> > > image
> > 
> > 
> > added to PR desc
> 
> y so tall, so much blank space

ok i scrumnched it
image

**Pull request merged**
