### PR TITLE
Donut 2 polish

### LINKED ISSUE #147: No means to make soup on Donut 2
**Describe the bug**
Donut 2 is missing the required facilities for making soup

**To Reproduce**
1. Go in Donut 2's kitchen
2. Notice lack of stove, soup pot, etc.

**Expected behavior**
There should be one on Donut 2 too.

### PR DESCRIPTION
**Pull request by F-OS**
[ASS-JAM] [BALANCE]
Closes #147
## About the PR 
This PR:
- Ports modern features to the kitchen, increases its size, and adds a freezer, while also giving it more raw ingredients and detaching it from the bar.

- Alters the gibber's code to make its use in a small room better for the chef

- Installs an external cooling loop for the freezer

- Messes with the flow of the bar a bit to try and make it nicer for the bartender

- Gives the jazz lounge blunt-rolling equipment, hobowine, and the commemorative plaque.

- Deletes a lattice in maint that had no reason to be there.

- Fixes the density on a grille for a room in maint.

- Fixes artlab networking

- Replaces the water tank that used to be in chemistry with a foam tank and fire-extinguisher

- Fixes access for toxins storage

- Gives toxins a pump-control computer

- Gives cyborgs more chargers around the station.

- Gives robotics two toolboxes. 

- Gives the QM an announcement computer.

- Fixes an APC in the boxing ring

- Scatters some air tanks around the station

- Gives the bathroom a toilet paper holder

- Gives medical a new manufacturer, alters the flow of surgery and adds a nanomed, expands maint around the morgue.

- Gives cloning some meat.

## Why's this needed? 

Donut 2 as a map has always been janky for modern audiences, this PR helps reduce that a bit.

## Changelog

```
(u)Fosstar:
(*)Modernized and fixed up Donut 2 a bunch. The map is available during Ass Jam!
```

### CODE REVIEW

**Comment by F-OS** [comment]
Oh fuck lol I accidentally edited every pen throughout the entire map

**Comment by F-OS** [comment]
Added massive changes, may want to check to make sure they look good and reconsider the approval.

**Comment by ZeWaka** [comment]
What's with the shuttle change on z2 @F-OS?

**Comment by F-OS** [comment]
> 
> 
> What's with the shuttle change on z2 @F-OS?

Shuttle would dock backwards before the change, so you'd have to spacewalk in order to get in, that change fixes it so the shuttle comes in correctly.

**Pull request merged**
