### PR TITLE
Death Wish Pickable Trait

### PR DESCRIPTION
**Pull request by Flaborized**
## About the PR 

This PR changes the implemented but not pick-able trait "death wish" to be more reasonable and then lets players pick it. It gives you +2 points!! but it's not really worth it, it's more for a fun challenge.

Effects:
- Doubles all the damage you take
- including oxy and tox damage
- stacks with everything else that increases damage
- woaw

Removes death wish's additional effect of halving your health. That's too much!!! This is much more manageably unmanageable. Double damage is a TON. This will effect things that give you death wish in-game but... that's ok I think they're all gimmicks that work just as well with regular death wish.

icon I drew for it:

deathwish

video of most extreme examples (roach taking blunt and pug taking oxy):

https://github.com/goonstation/goonstation/assets/53125172/1ecf55dd-3973-4989-8ff6-b923cd0cbadc

not everything will kill you this quickly but it's honestly pretty fast still

## Why's this needed? 

It's not a "good" or "useful" trait but it is: really fucking funny. Taking it is *only* to your detriment unless you're doing some weird microbomb thing. I can understand if we don't want something *this* goofy but like, I personally think it's hilarious and would be good and fun. Maybe even some incredible masochist would want to play the game regularly with this. It doesn't make the game unplayable or anything, just uh, don't get hit 😃 :sparkles: 

## Changelog 

```changelog
(u)Flaborized
(*)New pickable trait: Death Wish. It doubles the damage you take from ALL sources. Are you BAD enough to take it?
```

### CODE REVIEW

**Comment by Ilysen** [comment]
oooh this is SPICY. while I'm nobody in particular, if I could toss my hat into the thing I think it should probably show up on medical records like puritan and the like? just cuz it seems pretty important for docs and the like, and might be useful for forensics purposes too. just my thought though!!

**Comment by Flaborized** [comment]
> oooh this is SPICY. while I'm nobody in particular, if I could toss my hat into the thing I think it should probably show up on medical records like puritan and the like? just cuz it seems pretty important for doctors to know about, and might be useful for forensics purposes too. just my thought though!!

Good idea, added with the Technical Medical Name "Extreme Vulnerability" and insightful description "Skin and immune system similar in consistency to paper mache"

**Comment by Gannets** [comment]
This is perfect for my build, thank you

**Comment by TobleroneSwordfish** [comment]
Not a fan of this for a few reasons:
- Command/revheads dying instantly when beaten on rev rounds would suck and people will D: (nukies too, but you could just remove it there)
- Something this impactful should have a very obvious visual tell, roach is a good example of this. Imagine if you mindhack someone and then they die in 3 fire extinguisher hits as soon as you get into a fight.
- It stacks with roach and pug extra oxygen damage, meaning you can make some incredibly pathetic characters, exacerbating the above issues.

**Comment by Flaborized** [comment]
> Not a fan of this for a few reasons:
> 
>     * Command/revheads dying instantly when beaten on rev rounds would suck and people will D: (nukies too, but you could just remove it there)
> 
>     * Something this impactful should have a very obvious visual tell, roach is a good example of this. Imagine if you mindhack someone and then they die in 3 fire extinguisher hits as soon as you get into a fight.
> 
>     * It stacks with roach and pug extra oxygen damage, meaning you can make some incredibly pathetic characters, exacerbating the above issues.

I agree with some of these yeah. Adding a visual tell would be *ideal* but it's difficult to think of something that would really Fit. In lieu I've added a little examine text thing right at the bottom and in Red, which should at least help cue in people who are in the Know at least. 

I also blocked it from operatives entirely (it removes the trait after equipping you). This is inelegant but I think it's basically incompatible with the antag lol

Revheads kinda suck with this but I wouldn't want to specially remove it because it then becomes a Tell, regular heads on rev rounds I think are ok to die semi-randomly or be especially vulnerable, see also: heads leaving the station before they realize it's a rev round. Other antags are Solitary Affairs mostly so I think this is Fine on them.

**Comment by Glamurio** [comment]
As someone who desperately wants more negative quirks just to spice things up, this is really cool. Frankly I wouldn't be concerned with metagaming too much; power gamers will avoid it and people who roll it will be aware of it and play extra careful. An examine text string seems perfectly serviceable as a warning, I'd almost argue it's not needed but I see no harm in having it safe for antags now fishing for people with this trait to kill.

**Comment by Laboredih123** [comment]
f

**Comment by Glamurio** [comment]
Surely this is still on the menu and just kind of got forgotten right?

**Pull request closed without merging**
