### PR TITLE
Adds Penlights and Stethoscopes to Medical Fabricators

### PR DESCRIPTION
**Pull request by DisturbHerb**
[QOL]

## About the PR 
Adds the ability to fabricate penlights and stethoscopes in a Medical Fabricator. Penlights cost 1 metal and crystalline matter, while stethoscopes cost 2 metal and 1 crystalline matter.

## Why's this needed? 
Many maps have few or none of these tools lying around. They're great for roleplaying, so I thought that I'd add them.

### CODE REVIEW

**Comment by DisturbHerb** [comment]
Turns out, I don't know how labels work. 😔

**Comment by Carbadox** [comment]
Thoughts about maybe repurposing stetoscope as a possible Medical Doctor job reward?

**Comment by DisturbHerb** [comment]
> Thoughts about maybe repurposing stetoscope as a possible Medical Doctor job reward?

If it was a level 0 reward, that would be nice. Buuuut, stethoscopes are also neat hacking tools for safes. Putting them in a Nanomed would make them more accessible and you wouldn't need to bludgeon a doctor to death to get one.

**Review by ZeWaka — APPROVED** [review]

**Comment by flrsh** [comment]
I'd prefer it if NanoMeds mostly just had healing stuff and not equipment (besides health scanners). Maybe add these to medical equipment lockers? There should be one on each map.

**Comment by DisturbHerb** [comment]
> I'd prefer it if NanoMeds mostly just had healing stuff and not equipment (besides health scanners). Maybe add these to medical equipment lockers? There should be one on each map.

I dislike that option because more penlights and stethoscopes can't be manufactured if, say, the lockers were blown up or if all the equipment was taken. Honestly, I thought that the best option would be to be able to fabricate them in the medical fabs. This was more of a stop-gap solution.

**Review by flrsh — APPROVED** [review]

**Pull request merged**
