### PR TITLE
Broken Bones, Casts, Splints, and Crutches

### PR DESCRIPTION
**Pull request by TheTyrant25**
[FEATURE]
## About the PR
Does what it says on the tin, really. Reactivates and cleans up the somewhat stagnant broken bone code that's been sitting in the attic and lets bones in limbs (arms and legs only) break under extreme circumstances. These broken bones, depending on the severity, either aggravate your wounds (inflicting more brute damage to you) if you try to use them, or are completely useless, as if you had no limb there at all. The broken bones are then healed slowly by putting a splint or cast on the limb in question and waiting (or throwing them in the sleeper). They won't heal until some kind of brace is attached to the limb to 'hold the bones in place'.
In a secondary addition, to deal with loss of function in a leg, crutches are being added (wheelchairs of course already exist). Holding one in a hand, even if not actively selected, lets you move around at normal speed (although you stand a chance of tripping if you sprint everywhere like a lunatic), letting you move around better while injured or amputated.
## Why's this needed?
It's a neat idea, the framework was already there, and my main goal was to have some kind of treatment which can't be solved instantly but actually requires checkups and takes longer than the time it takes to shove them in cryo/hold an automender to the wound site. Great for RP of course, and for classic players, this gives a roboticist one extra job to do, as it's predicted that most people won't bother healing a limb and will just amputate.
## Changelog
```changelog
(u)Tyrant
(*)Bones can now break under extreme circumstances. Heal broken bones by putting the affected limb in a cast or a splint!
(+)Crutches have been added to the game. They increase mobility when held in hand if you're suffering from a broken leg, or a lack of leg. 
```

### CODE REVIEW

**Comment by TheTyrant25** [comment]
this is still a work in progress, but i may point out that it is slightly controversial. Possibly worth making a forum post on it?

**Comment by flrsh** [comment]
Haven't looked too closely at the code but I would much, much rather you work on improving an existing system, such as organs and organ damage, than adding a new one with a similar design (`my main goal was to have some kind of treatment which can't be solved instantly but actually requires checkups and takes longer than the time it takes to shove them in cryo/hold an automender to the wound site`).

**Comment by TheTyrant25** [comment]
it appears my atomised refactor pr has caused some conflicts

**Comment by TheTyrant25** [comment]
after much consideration, I am abandoning this project.
The scope is much too wide and the change far too big.
I'll probably roll out some of the minor tweaks in atomised form (notably crutches, maybe sprains)
But as it stands, it appears that bones breaking will not fit in with the current combat and health system of the game and will represent a large paradigm shift.
Sorry to everyone who was looking forward to it. One day I may implement a version of this, in the form of sprains, and we'll get there more gradually. But this change is too much too fast.

**Pull request closed without merging**
