### PR TITLE
renames MONO to SOLO

### PR DESCRIPTION
**Pull request by DisturbHerb**
## About the PR 
title

## Why's this needed? 
look hey man i don't wanna be reminded that mono means other things other than "one" okay

### CODE REVIEW

**Comment by frawhst** [comment]
are you trying to get us sued by disney

**Comment by DisturbHerb** [comment]
> are you trying to get us sued by disney

i can take on the mouse let me have at him

**Review by ZeWaka — APPROVED** [review]
i don't care

**Comment by frawhst** [comment]
shrugmerge

**Pull request merged**
