### PR TITLE
Donut3 Second Bathroom

### PR DESCRIPTION
**Pull request by Cherman0**
## About the PR 

Donut3Bathroom

Adds a second bathroom to Donut3, adjacent to the bar and south of the chapel. Uses those perspective stall doors instead of actual powered airlocks for the stall doors. Also modifies the original bathroom to have them too.

## Why's this needed? 

Donut3 had only one bathroom previously, and for one reason or another it blew up quite often, leading to an unstoppable stinktide on RP. 

## Changelog 

```changelog
(u)Cherman0
(+)Added a second bathroom to Donut3, by the bar.
```

### CODE REVIEW

**Comment by trazodont** [comment]
oml second bathroom for donut 3, bless. Any chance it could get a washing machine?? gotta love that freshy laundered clothes.

**Comment by Cherman0** [comment]
Yeah, I could fit one in there. Its pretty close to the crew quarters locker room which has two though.

**Comment by BatElite** [comment]
Given the location you've picked, I think it'd be nice to style it as a shower room for the adjacent gym & sauna. Pretty ideal door location, though the layout of the bathroom itself isn't set up for it.

I think the 3 tile shower stalls look kinda awkward and take up relatively much space. If I were designing that, I'd probably have a dividing wall with toilets up top and communal showers below.

**Comment by Cherman0** [comment]
I could do a tad of rearranging to make the door work. I personally dont mind gang showers but I know a lot of RP players have pretty strong feelings about being naked in front of other people, so keeping the shower stalls is important.

**Review by flappybatpal — CHANGES_REQUESTED** [review]
Checked out ingame, no issues except a misplaced disposal pipe:
image

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
