### PR TITLE
Airlock packet protection, take two

### PR DESCRIPTION
**Pull request by pali6**
[balance] [input wanted]
## About the PR 
Packets controlling an airlock now need to contain an `access_code` field that matches the door's internal access code.
This code can be found out by either bruteforce or by unscrewing the access panel and looking at a tiny display inside.
Currently the code is randomly generated number between 1 and 32.
The code has a chance to get scrambled when pulsing the AI control wire.
Providing incorrect code has a chance to make the door beep and blink red.

## Why's this needed? 
Currently packet hacking is a bit too powerful. Arguably easier than wire hacking, possible to automate, possible to do remotely, fast, impossible to detect after the fact and hard to detect as it's happening.
This PR forces you to either bruteforce it which will make the door blink and beep a bit and will take some time. Or you will need to unscrew the access panel to get the code that way which means interacting with the door manually.

I'm considering making the 1-32 range different for different "importance" of doors or maybe straight up not having the display visible on the unscrewed access panel on some doors (armory? head-level acces?). Let me know what you think of that.

## Changelog
```
(u)pali
(*)When using packets to hack airlocks you now need to provide access_code. You can either guess it or read it from the wire panel.
```

### CODE REVIEW

**Review by ZeWaka — APPROVED** [review]
code is correct

**Review by flrsh — APPROVED** [review]

**Review by Tarmunora — APPROVED** [review]

**Comment by Tarmunora** [comment]
Could even make the deny packet say if the provided code is too high/too low 🤔
idk if that would be good though

**Comment by pali6** [comment]
I could but at that point I'd probably increase the default range to a number higher than 32. Maybe something like 128?
And have armory (and maybe command) airlocks not include the display with the number?

**Comment by pali6** [comment]
I think I'm gonna try this version and maybe increase difficulty on important airlocks later based on feedback for this.

**Comment by HalfEnder776** [comment]
This is sorta fine but it makes automatic door hacking too slow to be worth it due to the wifi components delay. you would essentially not only need a cabinet to do the math you would also need to have two delay components before sending each of the 32 signals or the signal wouldn't be sent (due to the wifi components delay). Also even if you still wanted to do it you would need to be in range of the cabinet... 

Door packet hacking wasn't over powered it was overused and easy to make. I like the idea of making it much much more complicated but nerfing it out of existence removes a great reward for those who put enough time into it.

you would also need a way for your components to stop sending signals or else your essentially going to walk into a door and when it finally opens it's still going to be trying to hack it until you walk into another one.

It takes me about 5 seconds to physically hack open any door, why would i send all the time to make something that in the end would just inconvenience me?

why not make a way to calculate the code for example sending a scrambled code that you have to decrypt in some way (like a cabinet filled with arithithic components and such), hell you could make the way it's decrypted different each round and give players some way to find out the decryption method (i dont mean just putting in su access and typing something to get the headpass that sucked tbh [way to easy and you dont even need to know anything about the network to do it]). like how about building a machine using components that prods the network a bit and get the decryption method?

how about a cloud computing cabinet that cannot be moved but has extremely high range and can send/receive signals from device frames only (because even if you could fix all these other problems the lack of range of the cabinet computer would be a deal breaker)

The point of this is to separate people who just type in what there told and people who actually understand how packets and the network work.

welp this was sorta a rant sorry i just really dislike the idea of completely removing features that are too op completely (i think i heard something about tg doing that idk im still quite new)
there is probably many spelling errors here too so rip.

**Pull request merged**
