### PR TITLE
Adds the Mining Combat Helmet to hacked mining fabricators

### PR DESCRIPTION
**Pull request by muzcl**
[CLOTHING] [BALANCE]

## About the PR
Adds the Mining Combat Helmet (previously only obtainable via the hat trait, iirc) to hacked mining fabricators, and it changes the description to make it clear the armor isn't obtainable. It has the same material requirements as the industrial armor, but lowered significantly on account of it only being the helmet.

## Why's this needed?
The helmet is pretty good looking, and it could be used as an alternative "evil" industrial helmet other than the syndicate command helmet, which is limited to syndies. The mining fabricator is also really lacking items when hacked, only having the RCD and the ammo for it.

## Changelog

```changelog
(u)Idiot
(*)Added the Mining Combat Helmet to hacked mining fabricators.
```

### CODE REVIEW

**Comment by Sbmhawk** [comment]
7 head prot is a bit too much for something easily producible, maybe if it required starstone or something, idk

**Comment by muzcl** [comment]
> 7 head prot is a bit too much for something easily producible, maybe if it required starstone or something, idk

Didn't know it had that, yeah, I'll change that, my bad.

**Comment by muzcl** [comment]
I've buffed the combat stats significantly, but I've removed the rad protection. This should make it easier to tell if someones using it for combat or mining. It also requires erebite instead of uquill now, so its not as easy to make as the indy set.

**Comment by Sbmhawk** [comment]
> > 7 head prot is a bit too much for something easily producible, maybe if it required starstone or something, idk
> 
> It doesn't have 7 head protection. You're probably thinking of a different item, since according to the code it only has 2 melee prot.

You are right, I was looking at the salvager helmet

**Comment by Tarmunora** [comment]
Mmm, no. Don't think this would be a good add.

**Comment by muzcl** [comment]
Yeah, fair enough

**Pull request closed without merging**
