### PR TITLE
Map Correctness Runtime / CI Checks

### PR DESCRIPTION
**Pull request by pgmzeta**
[Mapping][Tooling][Code Quality]
## About the PR 
Picks up #8370 - I don't have push access to the branch, and there are merge conflicts on the maps there. Will submit map fixes separately to avoid future merge conflicts on this PR. Will keep it in draft until the map fixing work is done.

This PR makes it so runtime checking on GitHub CI will do some basic checks of whether maps have some easy to detect errors. In addition, this runs a subset of checks directly against prefabs and random rooms.

Current checks:
Missing followup navbeacons on patrols and tours
APCs without cables attached
Unanchored objects on walls
Windows on space or walls
Doors on space or walls
Networked machinery without data terminals
Blinds without switches
Station areas without APCs
Non-maint station areas with lights and without light switches
Unsimulated turfs in non-arrivals station areas

## Why's this needed? 
Bug prevention, map consistency/quality.

### CODE REVIEW

**Comment by pgmzeta** [comment]
!merge_upstream

**Comment by pgmzeta** [comment]
I think the current batch of open fixes will get this passing! So close :)

**Comment by nefarious6th** [comment]
G O O D   P R

**Comment by pgmzeta** [comment]
need to check & fix random rooms, or else the runtime checks will fail whenever a random room that does not fit the new specs is generated into a map.

For example:
```
[18:47:26] map_correctness.dm,128: Unsimulated station turfs:
The swamp grass /turf/unsimulated/floor/auto/grass/swamp_grass on 123, 88, 1 in South Inner Maintenance```

**Pull request merged**
