### PR TITLE
Fixes every doubled turf in maps and most missing types in some old maps

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Fixes every map key that has a doubled turf. 
Fixes old types on oldmap, trunkmap, chiron, concept, density, mushroom, samedi, and the silo setpiece (most should compile now)
Fixes non perspective walls on kondaru as well as the doubled turfs.
Fixes invisible plating using icon_states for damage instead of the subtype with overlays in these maps.

## Why's this needed? 
Updatepaths kept screaming about them and it was annoying. Oldmaps updated for the possible gimmick and ease of viewing.

### CODE REVIEW

**Comment by Laboredih123** [comment]
this is so epic, i was planning to do this but im too lazy

**Comment by Laboredih123** [comment]
oldmap seems a bit broken however still, lot missing

**Comment by Laboredih123** [comment]
still, nice work

**Comment by CheffieGithub** [comment]
oldmap had some things without mirrors but it also won't ever work as it is with current code I don't think

**Comment by CheffieGithub** [comment]
but also most of the missing stuff is just bad icon edits

**Comment by flappybatpal** [comment]
How the heck to review a 400k line change PR 💀

**Comment by CheffieGithub** [comment]
smallest mapping PR

**Comment by CheffieGithub** [comment]
I would say just review the mdb diff but the diff is broken

**Comment by CheffieGithub** [comment]
the diff is back

**Comment by CheffieGithub** [comment]
Im going to atomise this out

**Pull request closed without merging**
