### PR TITLE
Removes Chem Grenade assemblies from traitor buylist, gives RD a ManuDrive that can fabricate grenade assemblies.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 

**This pr is a branch of #5952, do not merge this without merging that first, or do, itll implement the ManuDrive system if you want that.**

Chem Grenade assemblies are completely gone from the traitor buylist. The RD has a ManuDrive that comes equipped with a recipe for grenade metal casings and grenade fuzes. The Grenade metal cases cost 5 met-3, and the fuses cost 4 met-1 and 2 con-2 (claretine tier). Both the metal cases and the fuses take 10 seconds to fabricate on speed 3. The Grenade Assembly ManuDrive is a spy thief target

## Concerns 

This pr will change chem balance, and chem is well, yknow, chem. There is one thing that beaker assemblies cant do, they cant be fitted into a riot launcher. Now, for the most part this is pretty fine and wont lead to anything too broken, however. chlorine azride explosions (and other low tier explosions like potassium and water) are incredibly easy to make. Chlorine azride explosions deals around 70 damage, make a few azride grenades and steal a riot launcher, you now got a pretty solid makeshift HE grenade launcher. Important to note that this strategy is possible in game currently, via debris chem grenades. To prevent that from being unbalanced, this pr may need to come alongside further balancing that reduces the damage caused by these easy explosions.

## Why's this needed? 
Chem grenades are not a very useful traitor item, basically everything you can do with them antag wise beaker assemblies can do better. Not to mention chem grenades have cool non antag use like making clearner grenades.

## Changelog

```changelog
(u)Ikea
(*)Nanotrasen now has the production rights to grenade assembly kits and now syndicate agents no longer have access to such an item. Nanotrasen has supplied the RD with a ManuDrive capable of producing grenade assemblies, some syndicate spies may wish to steal it however.
```

### CODE REVIEW

**Comment by BatElite** [comment]
Outside of anything else, 20s per half of a grenade is an awfully long wait.

Also, while I'm a fan of narrative changelog entries that one seems a bit overly long. (you've also misspelled valuable in it)

**Comment by ThatFiveGuys** [comment]
Main reason why it was so slow was initially because that was designed to be the tradeoff with beaker assemblies. However since i decided they should cost mining mats, long production time is probably no longer needed and i can cut production time in half.

**Comment by zjdtmkhzt** [comment]
Not sure if the changelog has been edited since BatElite's comment, but it seems ok to me?

**Comment by ThatFiveGuys** [comment]
Ive shortened it since batelite’s comments.

**Pull request closed without merging**
