### PR TITLE
Boosts Network Security of Airlocks

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Adds an internal verification counter to airlocks. Whenever the airlock is opened it increases it by 1, it hits 100 it overflows back to 0. Opening a door also sends a packet with this counter.
Now comes the tricky part: In order to manipulate the door using packets you need to include the current value of this counter. That means that you either need to wait for someone to open the door in a legit way or you need to bruteforce a bit.
Currently you have 100 options to bruteforce through. I'm willing to negotiate on this number.

## Why's this needed? 
Door hacking is trivially easy currently, especially with the advent of portable mechcomp frames. This should help a bit.

## Changelog
```
(u)pali
(*)Airlock wireless network security got a boost. Be sure to include the right verification counter value in your hacking attempts.
```

### CODE REVIEW

**Comment by moonlol** [comment]
(pali want alternative idea i give alternative idea)
Each department has its own code, which is used for opening lockers/doors/whatnot. The auth disk and NOTHING else contains a "master" code which can be used as a substitute for the departmental codes. Have each opening/unlocking of a locker/door print out a small portion of the departmental code (with some fake characters, like **FD**54 one time and A**D6**7 another time. (bold being correct), so that you will need to piece together the code via either getting a large enough sample size so that you can make the code without any problems or brute force a larger but still small set of possible codes (akin to irl wifi hacking on some encryptions)

**Comment by pali6** [comment]
I like the idea of it being access / department based somehow. Making every single door distinct is probably overkill.

**Comment by ZeWaka** [comment]
Flourish commented about a higher/lower response packet, so we can bisect if we're doing it by hand

**Comment by pali6** [comment]
I like higher/lower! It makes it easier to do bruteforcing by hand but won't help you that much with a mechcomp machine unless you make it really big.

**Comment by hexphire** [comment]
As someone who uses mechcomp regularly I really enjoy the versatility door hacking brings to the table, but I agree that in the current form door packets are wicked simple to crack/spoof. 

Most of the ideas i had have already been suggested it seems, but combined they seem even better. A combined departmental passkey you could only sniff portions of at a time, but with a mastermind game like feedback on wrong keys? It's probably over complicated but might encourage more mechcomp use and sniffing. If it's still to easy, the departments could change keys at an interval to keep it reasonable.

**Comment by Superlagg** [comment]
Could require the sending wifi component to have an authentication disk inside.

And so mechanics dont immediately rush-n-mug the captain for half a dozen different forms of AA, they could use some kind of mechcomp thing that copies the disk in the captain's inventory onto blank floppies.

**Comment by glassofmilk** [comment]
I like the idea of having a higher/lower response, but I'd also like to see something where the code doesn't change per door - once you've hacked it, you can get back in, the same way it works with door wires. Also, give each door randomized wires. If you're going to slow down one type of hacking, slow 'em ALL down!

**Comment by Tarmunora** [comment]
Randomize the order of the wires, but keep the effects-per-colour the same perhaps

**Comment by Superlagg** [comment]
> Randomize the order of the wires, but keep the effects-per-colour the same perhaps

That alone would slow me down with doorhacking. Most of the time, I don't even read which wire I cut, just its position in the list, only actually paying attention to the color when its not close to the top or bottom of the list.

**Comment by Ley-bunned** [comment]
the big, real differences between manual hacking and packet hacking is forensics/having to stop and screw open the door's access panel. Even though door hacking is quite fast you still leave a trail around the station as you go.

Also, "if this is nerfed, nerf X" isn't a sound argument, because packet hacking is getting nerfed for specific reasons. Bundling a door hack nerf without discussing it individually and extensively seems like a way to ignite discord/the forums/OOC between rounds.

**Comment by awfulworldkid** [comment]
A simple idea to make automatic packet-hacking harder: Add a verification key that's just the door ID, but backwards, that needs to be provided to open the door. Reversing a string is easy for humans to do, but difficult and complex to do programmatically, which makes it an easy check against automation. Also, it's easy enough to generate, assuming BYOND has any way to read strings back to front.

**Comment by MarkNais** [comment]
> ...Add a verification key that's just the door ID, but backwards,..

That would be *mostly* solved with a single Regex Replace component, and maybe another signal split or check.

**Comment by Boxlta** [comment]
It seems like it would be trivally easy to just use a control unit, Which can be put in device frames, to make a simple loop that counts from 0-100 and modifys the packet to do so, perhaps taking 10ish seconds to brute force a door down

**Comment by MarkNais** [comment]
0.4 seconds per wifi transmission, multiplied by 100-verification possibilities, leads to 40 seconds (max) to cycle through a door.
I set my control units to 0.5 seconds to avoid any queue conflicts. So ""statistical"" average door would take 25 seconds? 
Assuming you want to leave no fingerprints, add time to ping with PDA, set signal's address_1 in the casing...
Sounds reasonably slow to me.

**Comment by pali6** [comment]
Will figure out the proper way to do this later in a different PR. Thanks for all the feedback.

**Pull request closed without merging**
