### PR TITLE
Fix the bat form icon turning into coffinescape icon when clicked

### PR DESCRIPTION
**Pull request by thegrb93**
## About the PR 
Fix the bat form icon turning into coffinescape icon when clicked

## Why's this needed? 
Confused the heck out of me when I first played vampire

### CODE REVIEW

**Review by ZeWaka — APPROVED** [review]

**Comment by ZeWaka** [comment]
reminder to label your PRs

**Comment by thegrb93** [comment]
> reminder to label your PRs

Will do

It actually occurred to me that it would be useful for the icon to toggle correctly, and for the coffin-escape to use a different icon. That sound like a better idea?

**Comment by thegrb93** [comment]
It would be nice if there was another bat icon that this one could actually toggle between so you know if you have it enabled or not.

**Comment by thegrb93** [comment]
I think that was the original intent, but they coded it wrong.

**Comment by thegrb93** [comment]
Maybe lighting up the background would work?
image

**Comment by thegrb93** [comment]
Just need to add the icon and test it

**Comment by thegrb93** [comment]
Looks to be working

**Pull request merged**
