### PR TITLE
Nukies now come with flyzapper implants, flyzapper implants no longer zap nukies.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr gives nukies flyzapper implants. This pr also changes flyzapper behavior,  anyone with the mind of a nuclear operative or a gunbot will not be directly zapped, they will get minor disorient due to the larger elecflash. 

## Why's this needed? 
Micros damage other nukies, which means the death of an operative further helps cascade the death of other operatives. Microbombs also contribute to depressurization, which hurt for the gamemode. Flyzappers also immediately destroy gear upon death through elec gib, unlike the prolonged destruction currently. This overall should both buff nukies and be better for the round.
Current flyzapper damage values (note the absence of people in a 3x3 area due to gibbing) (This does not include zapping from any machinery which also contribute to damage):
image

## Changelog

```changelog
(u)Ikea
(*)Nuclear Operatives now come with flyzapper implants, flyzapper implants have also been reprogrammed to not directly zap nuclear operatives.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
I like how this is a lot more impactful than the pathetic microbombs nukies have right now, but feel like flyzappers don't seem to be in the style of nuke ops as much as microbombs, or, as I was considering adding, a more firey microbomb, if that makes sense. Granted that's a really minor nitpick

also do you think you could add sawflies to the "doesn't get zapped" field, unless them not being in there was on purpose? It seems a little weird one of the nukeop summons doesn't get added, but the other doesn't.

**Comment by ThatFiveGuys** [comment]
I agree with the thematics thing honestly but a key bit of this is minimization of nukie collateral damage and none of those things you can really do with that. Good point with the sawflies.

**Comment by flappybatpal** [comment]
This is one for Gannets but I thought the purpose of the microbomb was to mostly destroy the nukies gear rather than the damage. While you can tend to get their weapon, getting their ammo is much more difficult/rare.

**Comment by NightmareChamillian** [comment]
@flappybatpal the issue stands that the current microbomb really only strips the nukies of their gear for the crew- as opposed to preventing too much free stuff from landing in the wrong hands it makes it easier, intentionally or otherwise

**Comment by ThatFiveGuys** [comment]
> I'm not really a fan of this. Microbombs are a tide-turner when nukies are losing, as it creates further damage to the station which makes it more difficult for unprepared crew to disarm. I have seen many nukie rounds where Ops going boom actually helped the last couple of alive Ops to defend through taking out crew and blowing holes in the station.
> `Microbombs also contribute to depressurization, which hurt for the gamemode.` this I don't agree with at all, as depressurization is an essential part of the nukies' arsenal, hence why they also have so many explosive options.

Around half the rounds i see micros, they end up severely hurting other nukies. Theres a reason why micros tend to come in chains to where one persons death triggers another persons death which etc. Even ignoring that extreme, they also contribute to attrition damage which adds up fast. Micros tend to hurt far more then they help.

**Comment by MetricDuck** [comment]
> @flappybatpal the issue stands that the current microbomb really only strips the nukies of their gear for the crew- as opposed to preventing too much free stuff from landing in the wrong hands it makes it easier, intentionally or otherwise

Pouches & backpacks should burn when a micro explodes, destroying ammo contained therein.

**Comment by Tarmunora** [comment]
Seconding katzen and virv on this one.

**Comment by ThatFiveGuys** [comment]
I should probably elaborate on the depressurization thing, this is a take Ive seen from gannets and agree with. Basically what depressurization does is mutes gunshot sounds, slows people down, and forces crew to find internals before engaging. Overall it just dulls down gunfights and makes them less exciting then they could be.

**Pull request closed without merging**
