### PR TITLE
Monkeys can use humanoid limbs, fixes polymorph, etc

### PR DESCRIPTION
**Pull request by Superlagg**
## About the PR 

Limbs are no longer restricted to either monkeys and nonmonkeys, so now monkeys can use big adult limbs, and nonmonkeys can put those little baby arms on and it looks fucking awful, but monkeys can use robot limbs, so it's a-okay. #2967 

NPC monkeys have their appearanceholders randomized, so when they're humanized, they'll be a bit more diverse.

Randomizing an appearanceholder's looks has a chance to set each of the customization colors to different colors, as opposed to always making them all the same color. NPC lizards should look more lizardy, and spawned in humans should look more like the rest of the crew.

When a wig is made, that base toupee sprite is hidden if there's any other hair on the wig.

Added a few vars that'll let you shift up or down the arms and legs on the mob's sprite. This is to get human/monkey limbs to appear in roughly the right spot.

Moved the customization vars for most gimmick mobs to make use of initializeBioholder, and removed their SPAWN_DBG(0) things.

Made the disguiser use the appearanceholder's CopyOther proc to do its disguising thing. Seems to work just like it used to.

Fixed polymorph and the hair chems from not working at all. #2964 

Made most things that change a mob's appearance call update_colorful_parts(), as that updates their colorful parts, like their hair.

initializeBioholder now sets the mob's appearanceholder's gender to the mob's gender on initialization.

Makes stable mutagen call update_colorful_parts(), so it should work if it didnt before.

Monkey heads on nonmonkey bodies are no longer jammed in the middle of their chest. 

## Changelog

```
(u)Superlagg:
(+)Monkeys and non-monkeys can now share limbs.
```

### CODE REVIEW

**Comment by Superlagg** [comment]
Yay, fixed the runtime!

**Comment by Tarmunora** [comment]
please test things if you have not done so already

**Comment by Superlagg** [comment]
> please test things if you have not done so already

From what I can tell, everything seems to work. Apparently the stable mutagen part didn't work properly, but I fixed it and it should be fine now.

**Comment by Tarmunora** [comment]
#yolo

**Pull request merged**
