### PR TITLE
Sechud/Prodoc Overlay Reposition

### PR DESCRIPTION
**Pull request by Nexusuxen**
[A-UI] [C-Bug]

## About the PR 

Repositions the SecHUD and ProDoc HUD overlay elements to the bottom right and left respectively. Example:
image

## Why's this needed? 

Currently, the typing indicator and the Traitor/antag indicator overlap with the Health and Sec indicators respectively. You can't see someone's health while they're typing, which is occasionally annoying/problematic, looks unclean, and is almost definitely unintended.

## Changelog

```changelog
(u)Nexusuxen
(+)Moved the ProDoc and SecHUD overlay elements to the bottom of character sprites.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
definitely disagree with this movement

**Comment by NightmareChamillian** [comment]
I think it should be moved as not to interact with the typing indicator, but I'm in concordance with zewaka in that the position's not exactly the best. Maybe move it a few pixels down or to the other side?

**Comment by ThatFiveGuys** [comment]
I'd much prefer moving the traitor and chat indicator down a few pixels to be right below these indicators then moving these indicators all the way down here. The health indicator being at the feet just looks bad.

**Comment by Nexusuxen** [comment]
That's very fair; I had considered other options, but this was something I already had thrown together for a while but never actually made a PR for.

Another possibility is dynamically moving the indicators whenever they'd overlap. One way of doing this might be having indicator 'slots' (probably 4 per side), with the game moving indicators lower down based on their priority.

For the moment I'll close this due to negative feedback, but I might look into doing the above sometime if that method gets approval and I can manage wrangling overlay code.

**Comment by ZeWaka** [comment]
> Another possibility is dynamically moving the indicators whenever they'd overlap. One way of doing this might be having indicator 'slots' (probably 4 per side), with the game moving indicators lower down based on their priority.

I like this! Though maybe the typing one should not exist in that because it's on the side

**Pull request closed without merging**
