### PR TITLE
Unhots the gas storage apc on Destiny since that's not very hot

### PR DESCRIPTION
**Pull request by nefarious6th**
[mapping]

## About the PR 
Unhots gas storage APC

## Why's this needed? 
Whoever made this engineering design and powernet decision before was clearly a dunce. Fixing their sloppy work, enforcing Space OSHA-compliance across the stars.

### CODE REVIEW

**Comment by pali6** [comment]
What's up with the valve -> pipe change in toxins? Accidental revert?

**Comment by nefarious6th** [comment]
> What's up with the valve -> pipe change in toxins? Accidental revert?

Probably; let me fix it

**Comment by nefarious6th** [comment]
fixed

**Comment by ZeWaka** [comment]
there looks to be changes still, like you turned the pipes into valves?

**Comment by nefarious6th** [comment]
> there looks to be changes still, like you turned the pipes into valves?

Yeah, that's what they should've been, which is what I fixed afterPali's comment. I fixed them in an earlier thing but they got reverted. Without them, the gas going into the toxins hotloop just gets purged immediately. Let me know if you meant some other pipes on the station.

**Pull request merged**
