### PR TITLE
Resprite of all worn bedsheets

### PR DESCRIPTION
**Pull request by jan-antilles**
[sprites][human resprite]

## About the PR 
Now the resprited spacepeople can hide under a bedsheet, cut holes in it to peek out, or tie it around their neck like a marvelous cape.=

## Why's this needed? 
Because it's fun.

### CODE REVIEW

**Comment by Flaborized** [comment]
dope

**Review by Gannets — CHANGES_REQUESTED** [review]
Merge conflict!

**Comment by jan-antilles** [comment]
Ack! I thought I went through and updated all the conflicts. Flaborized said they looked good. Am I still overwriting some?? ><

**Comment by ZeWaka** [comment]
your branch is **really** old, you should update

**Pull request closed without merging**
