### PR TITLE
Makes reactions and reagents use current temperature when adding reagents

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Currently pretty much all reactions create reagents at 20°C. This PR makes it so the result is of the same temperature as the reactants. Similarly for reagents creating other reagents by different means.

## Why's this needed? 
Current behaviour is not very intuitive. I also think that the modified behaviour might lead to some more interesting interactions in the future.

## Changelog

```changelog
(u)pali
(*)Reactions now produce reagents at the temperature of the ingredients (as opposed to 20°C which was the previous behaviour.
```

### CODE REVIEW

**Comment by pali6** [comment]
This will likely break some things. And I'd love to hear thoughts on what might get broken. Some reactions / reagents should likely use a custom temperature but I'm not sure which ones.

Stuff that definitely needs changing so far:
- mg_nh3 <-> mg_nh3_cl reaction, currently it keeps reacting back an forth in a loop. Does anyone know how it should behave irl? Should we jsut remove it?

**Comment by pali6** [comment]
Also this will need similar changes in the secret submodule. TODO after merging this.

**Comment by MarkNais** [comment]
Chems resetting their temperature when a reaction occurs is unintuitive and frustrating. I can't help with the technical issues, but I'd very much like to see this change get merged.

**Comment by TDHooligan** [comment]
The resetting of temperature is unintuitive from a realism point of view but it's a really nice convenience step for a lot of reactions that do require heat, since you can make the heated chemical, pour the result into your room-temperature beaker then start with the next one. 

I, personally, don't see why it's frustrating to work with, as heated recipes are the outliers, yet excess heat is often a detriment. 

There is nothing fun added by forcing a cooling step to common chemicals like Diethylamine, or medical ones like Charcoal, Perfluorodecalin - every recipe that requires heating will now require cooling before they're safe to consume!  

This also very likely trip up even experienced chemists making smoke mixes and make the slowest part of chemistry (heating things) even slower, by requiring a cooling step afterwards.

I, personally, have made a few interesting mixes using this little intricacy, from pill grenades I've shared with a few folk, and these may be made impossible or have to be rewritten.

**Comment by pali6** [comment]
Hmm, we could add a thing to reactions that labels them as endo/exothermic and lowers/increases the result temperature by a number given there.

**Comment by TDHooligan** [comment]
Additionally - from experience, new chemists often do recipes one at a time, reading the next just after completing the previous one. It's a pretty big ask to make chemists remember to cool down every heated reaction they do, while they are just getting used to making even basic recipes.

Adding endo/exothermic reactions could solve the issue of scalding hot healing chems, but then you're putting yet another layer of complexity on chemists - some recipes require cooling, others don't. others require more heating afterwards. Making even a fairly simple mix can already take new chemists 10-20 minutes of the round, complicated ones can take even longer. 

It's a pretty huge change to the fundamentals of chemistry. Something that's been accepted as the norm since the creation of it. Up until this point, i've not heard a complaint about it. I'd argue this could be a huge change to chem balance, bigger than the slow reactions from a year or so ago. To top it all off, it's for something that will make chemistry slower, harder and more accident prone than it already is.

**Comment by mordent-goonstation** [comment]
> To top it all off, it's for something that will make chemistry slower, harder and more accident prone than it already is.

I view these as positive effects.

Could some of the issues with heated medical chemicals be mitigated by having them approach the temperature of their surroundings better? I haven't looked at the performance implications and suspect there are quite a few, but if "make a bunch of charcoal and leave it on the counter to cool off" is a viable way to get it back down to safe levels in a reasonable time frame then it wouldn't slow that down.

From the [Chemicals](https://wiki.ss13.co/Chemicals) page on the wiki:

Medical chemicals that would need to be cooled to be applied safely:

* Charcoal
* Calomel
* Perfluorodecalin
* Menthol (I've not once seen people synthesize this)

A lot of narcotics chemicals require heat to produce:

* Bath Salts
* Cat Drugs
* Crank
* Krokodil
* Methamphetamine

There's a bunch of poisons that require heat to make, but not like a little extra accidental burn damage is going to be a problem here.

A miscellaneous chemical that might be more of a pain because of this:

* Simple Syrup - would need cooling after if using in non-malicious/non-floorpills drinks

I haven't got time to go through all of the chemicals that require heat and are a precursor to another chemical right now, but one I can think of is Capulettium (requires Neurotoxin, which requires high heat) which would need to be cooled if you're using it as an anesthetic for surgery (or just whack them with some silver sulfadiazine afterwards, whatever).

Atropine requires Diethlyamine, which needs light heating, so synthesized atropine would probably be a little warm (though due to the other precursors probably being room temperature this would be mitigated). Same for Diphenhydramine, Ephedrine, and Epinephrine.

Overall I think additional complexity to making "safe" chemicals is warranted and welcome. If merged there will obviously be some adjustment issues for people with muscle memory or assumptions or whatever, but they'll learn.

We could mitigate the "newbies not cooling" it issue with some potential improvements on the wiki (for example, if a recipe has a reagent that is hot if synthesized we could give them a visual warning with a tooltip to indicate as such), e.g.:

image

**Comment by TDHooligan** [comment]
Making temperatures volatile and room-temperature reliant will make them extremely unreliable & accident prone. Beaker bombs will become either irrelevant (cool down below the point of feasibly being lit with an igniter) or dangerous (a hellburn sets every beaker bomb on the station alight)

What benefit does making chemistry slower and harder have? It will only make it more antisocial - Genetics was specifically changed to stop people sitting in one spot staring at a PC a whole round, what will make slow, painful Chemistry any more fun from slow Genetics? Accidentally smoking a mix you took and your 10-minute 

The only issue here seems to be that chemicals coming into existence at 20 degrees is mildly annoying, so we're going to break several years' muscle memory, make it harder 

As a side note - I can totally see great value in there being a few heat-reliant exo/endothermic reactions like an instant Infernite as an actual recipe using the existing system.

**Comment by mordent-goonstation** [comment]
I feel like comparing Chemistry to Genetics isn't really fair. The actual time spent "working" in Chemistry to create any given reagent is incredibly low (sometimes you have to spend a bit gathering reagents from other sources, which this change doesn't affect).

This **may** add an additional step that will less-than-double the synthesis time (at most an extra cooling step of no more than the amount you heated it to). Most reactions don't care for temperatures, so it will likely be much less than this. If your precursor required heating to make, when you mix it with other precursors it'll lower the temperature as well (so the end product requires less cooling).

Essentially, I don't think that "making chemistry take longer" is a significant factor in the balance here (it's something, for sure, but not damning in itself). The list of chemical recipes this change will affect is relatively low. Really, if the actual synthesis time is a significant factor it's because you're making thousands upon thousands of units of something, which seems like a fine thing to make take longer as it devalues it (you have less of the round to do something with your 2,000 units of meth, so maybe just make 200 units?).

I fully agree this will have ramifications for the ChemiCompiler and that will need some decently extensive testing to make sure you can still reasonably produce the same sorts of things with it (having a cooling step tacks on quite a bit of extra time/work here for something that already takes a while, so it would make using it for some things probably non-viable - perhaps the "cool to 20C on synthesis" effect could be added to ChemiCompilers, as a way of making them more attractive compared to manually doing it?).

> rebalance the entirety of every reaction

This is a gross overstatement as the vast majority of reactions are not temperature reliant.

I view this change as a way of adding depth to the system; as a an example, what if a consumable reagent (a la stabilizing agent) could be made that, if present in a container, meant that when reagent recipes trigger the reagents are set to 20C (i.e. current behavior), or perhaps shifts the temperature towards room temperature by an amount proportional to the amount consumed?

> Making temperatures volatile and room-temperature reliant will make them extremely unreliable & accident prone. Beaker bombs will become either irrelevant (cool down below the point of feasibly being lit with an igniter) or dangerous (a hellburn sets every beaker bomb on the station alight)

Fully agree with this, I was considering more the case where they're laying around in the open rather than in a container/on someone's person, though I get that that could be unintuitive as well. I think that this might be too large of a change and worthy of its own PR/discussion rather than being part of this one, but my general point is that "flaws" in this PR could be addressed with other changes rather than not going anywhere at all.

**Comment by Tarmunora** [comment]
Probably a patch worth at least testmerging, as that's probably the only way to really see how things shake out.
I think that damage from hot/cold chems in general is an issue that should be looked at in future though, to get get more reasonable values or to remove it entirely

**Comment by zagoon** [comment]
Out of scope for this PR, but some might find this change more palatable if there were a quick way to decrement the temps of reagents in containers similar to heating with an igniter or welding tool.

**Comment by Adharainspace** [comment]
everyone complaining about cooling is missing the easiest way to cool. just spam water into beakers, thats how i cool down stuff like clf3 after making it. you dont need a reagent heater/cooler always. just press a button until water stops becoming steam.

**Pull request closed without merging**
