### PR TITLE
Aetherion Station

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [INPUT WANTED] [FEATURE] [EXPERIMENTAL] [ADD TO WIKI] [COMPLEX]

## About the PR
Adds the Aetherion Station.! Sorry about that last PR, back in May. It's actually ready for playtesting this time!

The station is intended to be approximately the size of clarion/donut2, servicing low population servers, and lower midpop if needed.

The lore of the station is mostly vague and left for people to put together themselves, but there is one major theme: Disparity. The south-west crew quarters are very nice and luxurious, while in other parts there is dirt, filth, and unfinished looking construction. The robot depot, for instance, is a shuttle that has been hastily repurposed and wired up. Meanwhile, the pool is huge, as is most of the guest wing (known as "Neptunis Space Hotel"), as a sort of contrast. Just compare the staff crew quarters near research and the guest rooms near the pod bay. It's a world of difference.

Major (and some minor) features include:
- a chemlab with direct access to medbay, so that you can let aspiring pharmacists in to play with the equipment.
- A crematorium connected to the morgue by a direct door connection. Crime opportunities.
- Courtroom and the customs desk occupying the northwest corridor.
- random rooms in off station shuttles (consider them rooms being delivered to the station for construction), along with unfinished and extensive lattice networks for space chases, and unfinished rooms under construction.
- the robot depot being wired up in a ship in what seems like it was meant.
- fully functioning exterior belt delivery system. The ability to slap an export sticker directly on a crate and have it sell without going through cargo.
- A centralised bridge, since it seems the sensible place to install it. Also centralised maints, for if you want to break into the bridge or tech storage or hydroponics bay.
- extensive maintenance shafts, for crime.
- AI law room connected to the computer core by airbridge. 
- Engine room able to be disconnected from main engineering corridor by airbridge. Fully functional and symmetrical looking TEG. The disconnect allows for possible cogmap1 style random engines in the future. Also features a lattice framework for a potential placement of a singularity engine (which looks like a good idea at first but would disrupt the belt hell heavily, hence why it was never finished)
- false walls for escaping assailants (mainly in the crew quarters, akin to how irl hotels have false panels for maintenance)
- clown hole as a ship that smashed into the side of the station.
- noodle the bird having its own tiny ship near escape.
- the filthy tank near the pool filled with muck and other nasty stuff.
- custom ghost drone satellite and listening post.
- Medical Director has a direct view of the operating theatre.
- People who fall into disposal pipes in the south of the station (neptunis) get ejected out the security ejection chute instead of going to disposals. Safety first! (if you're a guest who's paying a lot of money to NT, that is, the crew can deal with it)
- many more things which i've forgotten to mention. Have a look and find stuff for yourself!

## Why's this needed?
There are not many options for very lowpop map votes, other than picking atlas. Most "lowpop" stations are tailored toward low to middle populations, and while atlas is viable for player counts of under 10, it lacks many features that other maps have in order to be that small. This station is designed to accommodate nearly empty crews due to its compact layout, without sacrificing any rooms or departments.

It was initially intended to run alongside or replace atlas, but since as mentioned, atlas is so small, nothing can really match it in its size. It's now more similar to the donut2/clarion size bracket, which is still lowpop, just not as small as atlas. I didn't particularly want to make the station inconvenient to navigate, so that resulted in the station sort of swelling during development, but it should still be fairly quick to get from one end to another, without departments feeling cramped. Of course, that's my own opinion, and should be taken with a grain of salt. Ideally play-testing or testmerging would be performed to gauge playability first.

## Changelog
```changelog
(u)Tyrant
(*)Added Aetherion Station
```

## Notes
The idea that started this project was an offhand mention that we could do with more lowpop maps. I took that idea a bit too far.

I'm well aware that developer consensus is that maps need a unique gameplay experience in order to be added. I made this map anyway, primarily as a way to learn more about mapping in a hands on way and also to learn what makes good and bad map design. It would be absolutely wonderful if this got into rotation regardless.

## Image of Aetherion as of 20th October 2023, the time of pull request.
Here is a screenshot of the station, with cables and pipes filtered out for a better view.

### CODE REVIEW

**Comment by ZeWaka** [comment]
i know you wrote about it in your description, but this doesn't really jive with:
> we currently aren't really accepting new maps unless they offer a dramatic departure from normal gameplay through unique mechanics

**Comment by 444Portal** [comment]
> i know you wrote about it in your description, but this doesn't really jive with:
> 
> > we currently aren't really accepting new maps unless they offer a dramatic departure from normal gameplay through unique mechanics

is this meant to read "we currently aren't really" or "we currently really aren't"

**Comment by ZeWaka** [comment]
> > i know you wrote about it in your description, but this doesn't really jive with:
> > > we currently aren't really accepting new maps unless they offer a dramatic departure from normal gameplay through unique mechanics
> 
> is this meant to read "we currently aren't really" or "we currently really aren't"

We are not unless something convinces us differently.

**Comment by 444Portal** [comment]
> [Large amount of back and forward quotes]
> 
> We are not unless something convinces us differently.
Noted!

**Comment by Azrun** [comment]
https://github.com/goonstation/goonstation/pull/14150#issuecomment-1558518375
https://github.com/goonstation/goonstation/pull/14150#pullrequestreview-1456546285
https://github.com/goonstation/goonstation/pull/16571#issuecomment-1773028695

Feel free to re-open once these have been addressed.

**Comment by TheTyrant25** [comment]
not really sure if i even can address it...

**Comment by TheTyrant25** [comment]
I'd like to know what specifically would have to be changed for the map to be even considered, if possible.

**Comment by Azrun** [comment]
A) Offers a dramatic departure from normal gameplay through unique mechanics
B) Convinces us to add it.

Ideally this would have been done as part of the player-projects in Discord and discussion with staff.  There may have been some ambiguity about expectations but hopefully that has been clarified above, if not please let us know.

**Pull request closed without merging**
