### PR TITLE
Accessory slot.

### PR DESCRIPTION
**Pull request by DisturbHerb**
[CLOTHING][UI][EXPERIMENTAL][FEATURE][QOL][INPUT WANTED]

## About the PR 
This PR adds barebones support for the accessory slot, a new clothing slot that behaves similarly to the belt. The accessory slot is tied to the "Toggle Inventory" option, so it will hide and become invisible with the other worn clothing options. Accessories can be any `/obj/item` with `c_flag = ONACCESORY` as defined in `defines/clothing.dm`. 

accessory

The icon for the accessory slot itself is supported by all the HUD styles, after I bodged together a set of codersprites that take one of @WALPVRGIS' scarves, sorry!

image

Mob examine text for when the target mob is wearing an accessory can be varied by where the accessory is worn, which can be set with a `/obj/item` variable, `accessory_location`. The values are determined in `defines/clothing.dm`.

image

~~Currently, the clothing layer that accessories show up on is defined in `layer.dm` as `MOB_OVERLAY_BASE - 9` after bumping `MOB_ARMOR_LAYER` to `MOB_OVERLAY_BASE - 9.1`. I'm not entirely sure if it should stay that way, maybe we don't want accessories showing up above armour, but I'll put off that decision for later. At some point, it could be worthwhile adding two different layers for accessories that appear above or below armour (so that, say, security badges would show up above an armour vest but a tie would not).~~

So far, there aren't actually any items that are part of this PR that can be worn in the slot. Below is an example of it working with the stethoscope; sprites courtesy of @avimour.

image
image
image

## Why's this needed? 
I'unno, really, I just wanted to wear my stethoscope around my neck. Maybe there's a use for it, somewhere.

## Changelog 

```changelog
(u)DisturbHerb
(*)Added the accessory clothing slot to human mobs.
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
All the defines in `accessory_locations.dm` could probably just be moved to `clothing.dm`. Yeah.

**Comment by flrsh** [comment]
Adding to what Flaborized said -

```
I (personally) don't like the idea of a cosmetic-only slot very much, if it's meant to be solely for aesthetic purposes I think it takes up valuable UI and HUD real estate for not a lot of gain. There's lots of cosmetic items that go in other slots, but there's also lots of useful stuff, and thus seeing someone wear a cosmetic item still relays the info to you; if you see someone wearing a jacket you know they don't have armor on for instance. The mob sprites give you a *lot* of info and I think adding more noise to them without any real implications mechanically isn't good.
```

An accessory slot is problematic code and design wise as well. How are you going to decide which items go in the accessory slot and which go in other slots? How will various accessories layer? How will different accessories interact with various mechanics such as acid, choking, eating, removal, etc.? This would clutter the UI, reduce visual clarity, unnecessarily complicate many game mechanics, and require a lot of special code handling. 

Imo it would make more sense to just add a dedicated neck slot with defined behavior. 

DNMing for additional admin discussion.

**Comment by flrsh** [comment]
Since no one else commented, as an update (which you probably expected) - most of the other admins / devs I've talked to agree that a neck slot would be preferable. I think some would still be against, or at least, not very enthused with a neck slot (I myself am somewhat ambivalent), but I think it'd be more viable than a general accessory slot.

**Comment by DisturbHerb** [comment]
Closed until I can find more time to work on this.

**Pull request closed without merging**
