### PR TITLE
Janitor Sprite Updates

### PR DESCRIPTION
**Pull request by binarysudoku**
## About the PR 

Janitor sprite updates, some perspective fixes, some polish, some consistency passes

* New-perspective mop bucket
* New-perspective laundry machine
* New-perspective cone
* Resprited buckets
* New-perspective caution sign
+ Flipped all cleaner bottles to face right
+ Added outline to mop
+ Added highlight to tsunami bottle

## Why's this needed? 

Just art updates

## Changelog

```
Erinexx:
* New-perspective mop bucket
* New-perspective laundry machine
* New-perspective cone
* Resprited buckets
* New-perspective caution sign
+ Flipped all cleaner bottles to face right
+ Added outline to mop
+ Added highlight to tsunami bottle
```

### CODE REVIEW

**Comment by flrsh** [comment]
Why were cleaner bottles flipped to face right? I feel like most people would hold them in the original orientation. Also, I personally prefer old buckets.

**Comment by pali6** [comment]
I also prefer the old buckets but the new ones follow the 3/4 perspective. Maybe if the shading was a bit more subtle and the bucket rim was a bit more pronounced?
But I personally am fine with the bucket sprite as it is, things don't need to be perfect.

**Comment by binarysudoku** [comment]
> Why were cleaner bottles flipped to face right? I feel like most people would hold them in the original orientation. Also, I personally prefer old buckets.

I flipped them on the logic that it makes sense for every item to consistently face right (guns should do this, but looking at them I figured it would also make sense with the cleaner bottles) - I'm not sure if this is an issue of "what you're used to doesn't look weird" or if they legitimately look weird flipped, but honestly I'd definitely like to hear your opinion :)

As for buckets, I can revert them for now and they can be revisited later!

**Comment by ZeWaka** [comment]
* The sponge sprite seems to lose a lot of contrast.
* I definitely prefer the spray bottles facing the other direction,
* The new caution sign loses a lot of perspective, makes it seem very flat.
* I actually like the new buckets more, but not the mop bucket. (is in perspective though)
* Laundry machine door could do with more differentiation against the main body when closed.
Rest looks good.

**Pull request merged**
