### PR TITLE
refactor pipe.dm

### PR DESCRIPTION
**Pull request by TheTyrant25**
[CODE QUALITY]
## About the PR
I was about to start on auto atmos pipes, atmos pipe spawners if you will. But everything was implicitly nested. This could not stand. Kindly ignore the branch name for now, I'll reuse it later.
## Why's this needed?
Make The Code Better Code.

### CODE REVIEW

**Comment by Laboredih123** [comment]
i was planning to do this ahhh

**Comment by Laboredih123** [comment]
i can start on this right now if you wish, probably should have anyway long ago

**Comment by TheTyrant25** [comment]
ah hell its conflicting already

**Comment by TheTyrant25** [comment]
this pr accumulated like 40 merge conflicts in under 24 hours, so unless it's instamerged, I don't think it's tenable.  I'll leave it to you @Laboredih123

**Comment by Laboredih123** [comment]
ight

**Pull request closed without merging**
