### PR TITLE
Silences dead monkeys some more

### PR DESCRIPTION
**Pull request by flappybatpal**
[BUG]

## About the PR 
Stops monkeys screaming when dead by adding emote_check in mutantraces.dm.

## Why's this needed? 
Dead monkeys scream when crushed by doors or the "You are scalded by the hot chemicals/You are frostbitten by the freezing cold chemicals" which can occur when a monkey corpse rots and leaks miasma in a fire.

### CODE REVIEW

**Comment by flappybatpal** [comment]
I've tested with and without, as far as I can see it doesn't affect monkeys except that I think they could scream more often before as this implements a cooldown using the same emote_check code as cow and chicken mutantraces.

Tested punching, stabbing, grabbing, throwing, shoving and flamethrowering and all result in satisfactory monkey screaming.

**Review by ZeWaka — APPROVED** [review]

**Comment by Kyle2143** [comment]
Uh... why? Monkeys scream, they should scream when someone is sawing through their bones to harvest their organs to sell on the space black market. Death means nothing to the noble monke

**Comment by flappybatpal** [comment]
Although kinda funny dead mobs shouldn't emote, both situations this occurs are spammy and unique to monkeys. It's only an unintended behaviour due to emote code needing an overhaul.

**Comment by Tarmunora** [comment]
Might as well do it for monkey farts as well

**Comment by ZeWaka** [comment]
> Might as well do it for monkey farts as well

u can fart when dead though due to gas bloating

**Comment by flappybatpal** [comment]
Testing and now screaming/farting seem to match up with human emotes.

**Pull request merged**
