### PR TITLE
Oshan Random Rooms

### PR DESCRIPTION
**Pull request by Sord213**
## About the PR 
Adds randomized rooms in maint. Random room locations:
Screenshot_113
Screenshot_114
Screenshot_115
Screenshot_116
Screenshot_124

## Why's this needed? 
variety good

## Changelog

```changelog
(u)Pali and Sord
(+)Added randomized rooms to Oshan
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Isnt the area to the left of qm the only stock market area on oshan? Should probably add an area elsewhere to compensate for its removal. Also personally i dont like the random room near tech storage as that wide open area was always a nice place to work on mechcomp.

**Comment by Sord213** [comment]
> Isnt the area to the left of qm the only stock market area on oshan? Should probably add an area elsewhere to compensate for its removal. The coffee machine in that area looks a bit awkward too. Also personally i dont like the random room near tech storage as that wide open area was always a nice place to work on mechcomp.

After some feedback here + in discord I removed the random room by tech storage and added a stock exchange PC to information office. Also the coffee machine is better looking in the change, the screenshot was just out of date a little

**Comment by Eagletanker** [comment]
I think this runs into some of the problems as with the cog2 PR. Some pretty distinctive crime spots and such are being removed, and should probably instead be changed to add to the map (maybe fallen containers around the station in eye sight of a maint window?)

**Comment by frawhst** [comment]
!merge_upstream

**Comment by flrsh** [comment]
Added in bb23c9dd39f5f4fd636179fc498742ca0c0f44d3, sorry Sord for the very long wait!

**Pull request closed without merging**
