### PR TITLE
make option for reenabling the top menu easier to find

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
image
^ This one ^

UPDATE:
Apparently people actually use this feature, so I changed things so that disabling the menu now gives an alert in chat that tells you about the existence of the button. The alert also has a link to reenable the menu, in case the disabling was an accident.
I also changed the anchoring on the menu button, so it should be less likely to be hidden behind other stuff.
You can see a video below.
https://user-images.githubusercontent.com/35579460/149184262-46d181dd-e106-4d02-acfb-7bdbd135a903.mp4
## Why's this needed? 
We keep getting mentorhelps about how to bring the menu back, especially since the button to do so is often not visible without moving the screen divider further to the left.

~~I think hardly anyone actually uses this feature? 
But I am going to put INPUT WANTED on this PR so you can yell at me if you do and we can find another solution!~~

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
I see, I honestly didn't think there were people who played like that. I will change the stuff them.

**Comment by zjdtmkhzt** [comment]
Made adjustments, how's this?
https://user-images.githubusercontent.com/35579460/149184262-46d181dd-e106-4d02-acfb-7bdbd135a903.mp4

**Comment by zjdtmkhzt** [comment]
me when I realize I didn't push my changes:
:o

**Comment by TTerc** [comment]
Yeah, I like the alternative a lot!

**Pull request merged**
