### PR TITLE
Chainsaw resprites

### PR DESCRIPTION
**Pull request by Cherman0**
## About the PR 

What it says on the tin. Respites the chainsaw and syndie chainsaw. Credit to End for the plastic base, palette, and general inspiration.

GreenSaw
RedSaw

## Why's this needed? 

Perspectivizing, general sprite quality

### CODE REVIEW

**Comment by virvatuli-gh** [comment]
I like them! They look nice and chunky. That being said I personally would rather the green "chainsaw" look more like the sound tries to portray it as, an electric trimmer saw thing rather than a gas powered horror like the syndie one. But it's not a strong desire on my part, I like the sprites either way.
Gonna get Walp to chime in though

**Comment by Cherman0** [comment]
Does the green chainsaw have sounds? I noticed in testing that only the red chainsaw actually made a noise when you start and stop it. I originally did give the green one tiny saw teeth, but it didnt give me enough visual fidelity to make the shading look right.

**Comment by flappybatpal** [comment]
> Does the green chainsaw have sounds? I noticed in testing that only the red chainsaw actually made a noise when you start and stop it. I originally did give the green one tiny saw teeth, but it didnt give me enough visual fidelity to make the shading look right.

Yes, I gave it electric hedge trimmer style noises. The only issue we have changing the tool is that you can chop down trees with them now, which would be a bit strange with a trimmer.

**Comment by pali6** [comment]
@Flaborized had some concerns about this

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
While I love the new sprites, I think there definitely needs to be a bit more differentiating the two types (in the same way that the older ones did). Like making the red chainsaw a bit sharper in design or more intimidating etc.

**Comment by Cherman0** [comment]
Made the syndie saw have bigger blades to make it stand out more.
RedSaw

**Review by flappybatpal — APPROVED** [review]
I thin more can be done but the sprite is decent and they are a bit more distinguished now.

**Review by ZeWaka — COMMENTED** [review]
why does the green chainsaw spin faster than the deadlier red chainsaw? did you mess up the frame timings?

**Comment by Cherman0** [comment]
> why does the green chainsaw spin faster than the deadlier red chainsaw? did you mess up the frame timings?

Thats how it is currently and I assumed it was intentional. If it isnt it would be a trivial .dmi edit to change.

**Comment by ZeWaka** [comment]
> > why does the green chainsaw spin faster than the deadlier red chainsaw? did you mess up the frame timings?
> 
> Thats how it is currently and I assumed it was intentional. If it isnt it would be a trivial .dmi edit to change.

It seems either wrong or backwards to me

**Comment by Cherman0** [comment]
Updated red saw to match green saw speed: 
RedSaw

**Comment by ZeWaka** [comment]
better than existing

**Pull request merged**
