### PR TITLE
Faith Casing Ejection Fix

### PR DESCRIPTION
**Pull request by makkipakki**
[BUG - MINOR]
## About the PR 
This change makes the Chaplain's pistol Faith function like a semi-auto, ejecting an empty case after every shot (like the sprite implies).

## Why's this needed? 
Currently the pistol functions like a revolver and dumps all of the empty cases on reload, which is misleading.

## Changelog

```
(u)makkipakki:
(+)The chaplain's pistol Faith now functions like a semi-auto
```

### CODE REVIEW

**Comment by Gannets** [comment]
Makes sense to me, it's a semiauto 👍

**Comment by Sovexe** [comment]
I believe Urs has previously commented that this was intended to be a single action revolver

as such the correction would be only dropping the casing when reloading

**Comment by UrsulaMejor** [comment]
it was originally gonna be a single action but the beretta is just way cooler, makkipakki is correct here

**Comment by makkipakki** [comment]
> 
> 
> it was originally gonna be a single action but the beretta is just way cooler, makkipakki is correct here

I actually had no clue you intended it to be a revolver originally! I hope I didn't mess with your plans when I made the sprite, I could have made it a single-action just as easily!

**Pull request merged**
