### PR TITLE
werewolves can walk on glass

### PR DESCRIPTION
**Pull request by ZWRh3**
[BALANCE]

## About the PR 
slightly refactors material shards and makes werewolves immune to them similar to cows

## Why's this needed? 
its honestly just sad to see wws get robusted by the piles of glass every round has, **especially** the glass from them breaking windows with their own arms

## 

```changelog
(u)ZWRh3
(+)Werewolves are now immune to walking on shards similar to cows.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
I'm pretty sure them being unable to walk on glass is like, intentionally their only real biggest weakness. Furthermore it's easy enough for them to just walk around it/pick up the shard.

Granted, maybe it's for the better if they don't have such an obscure achilles' heal, and instead have an issue like more vulnerability to burn damage. I feel like I'd have to watch a round of this play out before I had really any major opinions on it.

**Comment by Wisemonster** [comment]
> I'm pretty sure them being unable to walk on glass is like, intentionally their only real biggest weakness. Furthermore it's easy enough for them to just walk around it/pick up the shard.
> 
> Granted, maybe it's for the better if they don't have such an obscure achilles' heal, and instead have an issue like more vulnerability to burn damage. I feel like I'd have to watch a round of this play out before I had really any major opinions on it.

Except they are also weak to silver bullets (or rather, bullets in general) and wolfsbane. Hell, glass shards are easier to get than wolfsbane, considering you have to get botany grow it rather than just creating and breaking a thindow.

**Comment by ZWRh3** [comment]
> I'm pretty sure them being unable to walk on glass is like, intentionally their only real biggest weakness. Furthermore it's easy enough for them to just walk around it/pick up the shard.
> 
> Granted, maybe it's for the better if they don't have such an obscure achilles' heal, and instead have an issue like more vulnerability to burn damage. I feel like I'd have to watch a round of this play out before I had really any major opinions on it.

they are comically easy to just stun or shoot even without silver bullets

**Comment by ZWRh3** [comment]
!merge_upstream

**Comment by Momoberry** [comment]
> I'm pretty sure them being unable to walk on glass is like, intentionally their only real biggest weakness. Furthermore it's easy enough for them to just walk around it/pick up the shard.
> 
> Granted, maybe it's for the better if they don't have such an obscure achilles' heal, and instead have an issue like more vulnerability to burn damage. I feel like I'd have to watch a round of this play out before I had really any major opinions on it.

I feel like their biggest weakness is having basically no clothing in general, and this is just a byproduct. I wouldn't mind werewolves being strong upfront and not having the issue of glass since they are actually the only antagonist FORCED to rampage. Critters can get away with disguises and stuff, and they usually talk normally. werewolf becomes like impossible to understand and can't wear most clothing, so it sorta balances out. They have a lot of major weaknesses, they just aren't really used that much I find.

**Review by flrsh — APPROVED** [review]
Changed it to a minor changelog.

**Pull request merged**
