### PR TITLE
Resprites Eye Spider Tear Puddles

### PR DESCRIPTION
**Pull request by MitchTheUser**
## About the PR 

Quick Mini Resprite here: resprites the puddles of tears made by crying Eye Spiders. Transparency is kept in the sprites, but they now have actual shading and highlights. Urine.dmi, and it's associated Urine Puddles have also been deleted, as Urination has been removed and the puddle sprites were obsolete.

UrineSimpleDisplay

## Why's this needed? 

The old sprites were flat single transparent shades, which do not look good at all.

TearDisplay

### CODE REVIEW

**Comment by Retrino** [comment]
may as well just remove the urine puddle sprite

**Comment by MitchTheUser** [comment]
> may as well just remove the urine puddle sprite

Yeah, I agree, since I can't really see the sprite having any use other than just existing. I deleted urine.dmi, and I also changed the PR title, description and pictures to match it, including removing my theory that sweating created tear puddles (they don't).

**Comment by Cherman0** [comment]
Might be good to push the sprite up a few pixels so it's centered in the tile? Otherwise looks good

**Comment by LaCumbiaDelCoronavirus** [comment]
> > may as well just remove the urine puddle sprite
> 
> Yeah, I agree, since I can't really see the sprite having any use other than just existing. I deleted urine.dmi, and I also changed the PR title, description and pictures to match it, including removing my theory that sweating created tear puddles (they don't).

theyre used for a small secret medal


unrelated: maybe make the puddles as transparent as the old ones? it seems a bit unrealistic rn

**Comment by ZeWaka** [comment]
> theyre used for a small secret medal

Where? I don't see anything.

**Comment by Retrino** [comment]
> > > may as well just remove the urine puddle sprite
> > 
> > 
> > Yeah, I agree, since I can't really see the sprite having any use other than just existing. I deleted urine.dmi, and I also changed the PR title, description and pictures to match it, including removing my theory that sweating created tear puddles (they don't).
> 
> theyre used for a small secret medal
> 
> unrelated: maybe make the puddles as transparent as the old ones? it seems a bit unrealistic rn

if they *are* used for one, the medal should be reworked since piss is unobtainable anyway

**Comment by LaCumbiaDelCoronavirus** [comment]
> > theyre used for a small secret medal
> 
> Where? I don't see anything.
> 
> i also think they should be slightly more transparent yeah

Button Pusher medal. dont need piss at all to get it. its just a funny effect

**Comment by ZeWaka** [comment]
But like it isn't, I really don't see how it's used

**Comment by MitchTheUser** [comment]
> Might be good to push the sprite up a few pixels so it's centered in the tile? Otherwise looks good

Pushed the sprite up some pixels to make it more centered.

> unrelated: maybe make the puddles as transparent as the old ones? it seems a bit unrealistic rn

> i also think they should be slightly more transparent yeah

Made the puddles more transparent.

**Pull request merged**
