### PR TITLE
Standardize and change the credits symbol to ⪽

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Currently the credits symbol is $ and is used sometimes in front of the number and sometimes after.
This PR standardizes this usage. Creates a define for the symbol and changes the symbol to ⪽.
image

## Why's this needed? 
I think ⪽ looks sorta like C and vaguely futuristic. Feels like it could fit in-game. But I welcome any other suggestions for the symbol!

## Changelog

```changelog
(u)pali
(*)Credits symbol has been changed from $ to ⪽
```

### CODE REVIEW

**Comment by pali6** [comment]
Some other C-like alternatives we could consider instead: ᑦ ℂ ⵎ ʗ ᑕ 𝇋 くᙅ ᕦ ᐸ

**Comment by DisturbHerb** [comment]
lemme firmly plant my face into unicode code tables to find alternatives 👀

**Comment by Bartimeus973** [comment]
The only thing that i can think about would be adding this symbol to the list of crayon drawings considering we already have € and $

**Comment by Eagletanker** [comment]
I don’t think most players have this on their keyboards unlike $ so there’s that to consider

**Comment by TobleroneSwordfish** [comment]
> I don’t think most players have this on their keyboards unlike $ so there’s that to consider

Might be possible to make `$c` or something turn into `⪽` when typed into chat/paper etc. Although from what I recall of speech code it would probably be a pain to implement and maintain.

**Comment by Yellow-Mushroom** [comment]
I enjoy ⍧, people can type out $c, or with crayon write c and put an exclamation point through it. It also matches $ with the line

**Comment by ZeWaka** [comment]
There's also ¤

**Comment by DisturbHerb** [comment]
> The only thing that i can think about would be adding this symbol to the list of crayon drawings considering we already have € and $

in that same vein, banners too

**Review by flrsh — APPROVED** [review]

**Pull request merged**
