### PR TITLE
Adds the Ore Scoop to the mining manufacturer

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
## About the PR 
Adds  the Ore scoop to the mining Manufacterer 

## Why's this needed?
 the only ore scoopers are the ones that spawn at game start on the so if you lose it you have to steal one from another miner 

## Changelog

```
(u)MatheusIsNotAvailable & Retrino:
(+)Added the ore scoop to the mining fabricator!
```

### CODE REVIEW

**Review by flrsh — APPROVED** [review]

**Comment by flrsh** [comment]
Just realized that this does the same thing as #2705. Do people have a strong preference for material cost (which seems to be the only difference)?

**Comment by MatheusIsNotAvailable** [comment]
What happened was me not seeing that Retrino had already made a PR for the same thing I made, the code is basically the same, only real difference is the material cost, I dont know what people think about the material price since no one has commented on it.

**Comment by BatElite** [comment]
2705 puts the scoop in a slightly more sensible place (next to the satchels), but mostly I feel like the 10s build time is a bit high for the item in question.

Really either one would work, but I'd vote for this one. Doubt the material costs will matter at all.

**Comment by Retrino** [comment]
doesn’t matter to me which is merged really, the only reason i changed mat pricing was to make it more realistic. to mention my print time, i upped it because the time coded doesn’t carry over to the game in the same way, i think when i tested it the time was actually something like 2.7 seconds? either way, it’s the same coding, so doesn’t matter much

**Comment by MatheusIsNotAvailable** [comment]
Yeah, the code timing thing is weird, makes it less then it acctually is, with my code it might be too fast, almost instantly I think, mats dont matter too much normally and I think it will matter even less since it is mining, his one is in a better position too(next to the satchels). Doesn't matter much to me wich one is merged.

**Comment by flrsh** [comment]
The timing thing is weird, but I think that's outside the scope of either of these PRs! @Tarmunora should look into it though :pelterfrog:

Merging this one because I already added co-authors.

**Pull request merged**
