### PR TITLE
Player piano mechcomp integration

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Gives the player piano 3 mechcomp inputs.
- Play
- Set Notes
- Set Timing
- Reset

Also gives an output that triggers when playing finishes.
Also did some minor refactoring I guess.
## Why's this needed? 
Fun?
- Custom Jukebox
- Fun jingle for your shop
- Play Megalovania and demand payment for periods of silence (maybe don't do that one)

Sorry about the GIANT FLASHING PURPLE RECTANGLES in the video, I think my recording software did not like the tooltips.

https://user-images.githubusercontent.com/35579460/163493025-14978e19-e5c1-4cf2-936e-db4b153a29f5.mp4

## Changelog

```changelog
(u) zjdtmkhzt
(+) Player pianos now have mechcomp integration.
```

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
I should probably do something about connections to unanchored pianos...

**Comment by Eagletanker** [comment]
Finally I can make my jukebox of just all star

**Comment by zjdtmkhzt** [comment]
Alright, added some changes to make sure unanchored pianos can't be hooked up.
May also make it impossible to hook up vending machines that got tipped over? idk if that was possible before, it sure isn't possible now.

The system for when specific things can or can't be connected should probably be expanded in the future to allow for more specific checks for objects than just level and being anchored for everything, but that's byond the scope of this PR.

I consider this ready for review now!

**Review by pali6 — APPROVED** [review]
I quickly scrolled through the code, I even looked at some of the lines

**Pull request merged**
