### PR TITLE
adds 5 new songs and places them

### PR DESCRIPTION
**Pull request by aquariofury**
## About the PR
Adds 9 new songs that me and my friend Not Tom made into two record sleeves, and places them into the some spots that feel thematically appropriate in the debris field and into prefabs in the trench. Adds a random crate spawning in the trench that includes the second record sleeve and an old song (distant star) 

## Why's this needed?
More music is always cool in games, and many of these songs were written with specific areas of goonstation in mind!

## Changelog

```
(u)aquariofury
(+)Added 5 new songs, hides them in the debris field and trench

### CODE REVIEW

**Comment by DimWhat** [comment]
I think this should have a changelog.

**Comment by aquariofury** [comment]
youre right, i didnt credit you for the map placements im sorry G

**Review by ZeWaka — CHANGES_REQUESTED** [review]
changelog is not in the prescribed format

**Review by virvatuli-gh — CHANGES_REQUESTED** [review]
All of the filesizes are gigantic compared to all of the other radio music currently ingame. I haven't listened to all of them yet but they should be inline with other similar files already in the codebase.

**Comment by aquariofury** [comment]
thanks for all the feedback guys!! i hope ive changed everything to be more compliant, if not keep it coming

**Comment by Yellow-Mushroom** [comment]
Love your music Aquario, very excited to hear your stuff in game

**Comment by virvatuli-gh** [comment]
Merge conflicts will need to be fixed (filepaths for radio music have been changed with a restructuring PR). I'll review the tracks themselves this weekend!

**Review by virvatuli-gh — APPROVED** [review]

**Pull request merged**
