### PR TITLE
Add Oshan Carousel east and west mailrooms

### PR DESCRIPTION
**Pull request by pgmzeta**
[mapping][feature]
## About the PR 
Adds mailrooms connecting the carousel to the cafeteria and hall by technical storage.

## Why's this needed? 
make carousel more useful

## Map screenshots

Screenshot 2024-09-16 232628
Screenshot 2024-09-16 232650

## Changelog 

```changelog
(u)glowbold
(*)Oshan now has carousel destinations by the cafeteria ("West Carousel") and technical storage ("East Carousel")
```

### CODE REVIEW

**Comment by Cherman0** [comment]
I like the east room and dislike the west room. Aside from looking cool, that fishtank is easily accessible from the ranch so that they can make coral chickens and other chickens that have to be made underwater.

**Comment by Glamurio** [comment]
Yooo, built-in sushi belt on Oshan? I love it.

**Comment by TobleroneSwordfish** [comment]
I like these but I would really miss the fish tank. Maybe have it go through the fish tank and set the mailroom back a bit?

**Comment by pgmzeta** [comment]
Updated the cafeteria endpoint to preserve the fishtank. The detective's ladder area was a casualty instead.

**Pull request merged**
