### PR TITLE
Traitors now get 25 TC - Buylist items are scaled to match

### PR DESCRIPTION
**Pull request by Zonespace27**
[Balance] [Input Wanted]
## About the PR 
This PR increases the TC count for traitors to 25 from 12, but also scales the cost of all traitor items to be about equivalent to what they were before.

The only mechanical additions/features that have been added are:

- Microbombs now have an average of 1.1 explosion power (`prob(90) ? 1 : 2`), down from 2.25 (`prob(25) ? 3 : 2`), to account for them still sticking at 1 TC
- Macrobombs now roll the microbomb chance a number of times equal to its cost in TC (25), instead of using its own strange math
- You can now buy TC from uplinks in stacks of 5 as well
- Traitors do get the equivalent of 0.5 extra TC (12 -> 25 instead of 12 -> 24)

## Why's this needed?

This change may not do much immediately in this PR, but I fully intend to make a future PR regarding balance and cost of the items, but here's some reasons why this is a good change in the long term:

- Currently, items that cost the same can be hard to stand out. For instance, take the Agent Card (1 TC) and the Chameleon Jumpsuit (1 TC). The agent card is miles better and more worth the TC than the jumpsuit, but you can't make the jumpsuit picked more by making it cheaper, it's already as cheap as can be, and you can't increase the agent card's price _at all_ without knocking it from costing 1/12th your TC to 1/6th, which is a massive jump in terms of TC breakpoints.
- In a future PR, I plan to increase/decrease the price of some items, bringing their cost to what would properly reflect their effectiveness, something that in some cases is undoable with how underinflated our TC are.
- It may lead the way to future content that could potentially give traitors a small amount of extra TC, which giving even _1_ more to traitors currently would upend a lot of balance decisions.

## Why not rebalance the item's costs in this PR?
I'd like to get the go-ahead on the concept first before making actual balance changes, in addition to atomization concerns.

Edit: Here's a document I threw together, which increases/decreases the cost of certain items by 1, [here](https://docs.google.com/document/d/1a_fG0agz3gRAdSM2rxAi8kWzowdr6glghUNWUbnlv9g/edit?usp=sharing).
## Changelog

```changelog
(u)Zonespace
(*)Traitors now get 25 TC, but their uplink item costs have been scaled to match this increase.
```

### CODE REVIEW

**Comment by Kyle2143** [comment]
If you're just flat doubling every single item cost, why did you (double+1) the total TC amount?

Also, I'm not really sure that this complete rework to Traitor item TC purchasing is warranted right now. There's always a tradeoff to be made between precision and usability/clarity in anything. Distilling any item down to a single number value of it's "worth" is hard, and reasonable minds will disagree.

I can see wanting to add more Traitor item purchasing precision at one point in the future, but a non-trivial amount of time has went into balancing already. This PR reads like you want to get free reign to do a rebalance on it without making a case for its necessity other than "adding more granularity is better".

**Comment by Zonespace27** [comment]
> If you're just flat doubling every single item cost, why did you (double+1) the total TC amount?

I admit this is just a bit of a taste thing (multiples of 5 are better than multiples of 6 imo), but I honestly believe this will not be a major balance upheaval in the long run. Giving them 1 extra TC is equal to 0.5 extra with regular TC numbers, and it's not like you'll be able to buy a cloaker + c-saber anyway, since they'll cost 26 together. I will update the PR body to reflect this balance change as well.

> Also, I'm not really sure that this complete rework to Traitor item TC purchasing is warranted right now. There's always a tradeoff to be made between precision and usability/clarity in anything. Distilling any item down to a single number value of it's "worth" is hard, and reasonable minds will disagree.

And I believe the granularity is better for balance, since you'll be able to more accurately balance items with their value (jumping from 1 to 2 TC normally is from 8% to nearly 17% of your TC, versus jumping from 4% to 8% with my proposed system), and what's the reason in waiting? Very few changes have been made to uplinks and TC costs recently (stims change is the most recent, I think?)

> I can see wanting to add more Traitor item purchasing precision at one point in the future, but a non-trivial amount of time has went into balancing already. This PR reads like you want to get free reign to design a rebalance on it without giving much information on the plan other than "more granularity is better", and that's a big ask.

It wasn't my intent for this PR to sound like I'm looking for "free reign to design a rebalance" of traitor equipment in uplinks and their cost. To reiterate more specifically, I'm looking to make some minor TC edits (+/- 1 TC) to some traitor items, which would bring their costs up or down to match with their purchase rates. In fact, I can probably put together a design document with my proposed changes (to be made in a later PR should this get merged) later tonight or tomorrow, depending on how much time I have.

**Comment by Eagletanker** [comment]
> If you're just flat doubling every single item cost, why did you (double+1) the total TC amount?
> 
> Also, I'm not really sure that this complete rework to Traitor item TC purchasing is warranted right now. There's always a tradeoff to be made between precision and usability/clarity in anything. Distilling any item down to a single number value of it's "worth" is hard, and reasonable minds will disagree.
> 
> I can see wanting to add more Traitor item purchasing precision at one point in the future, but a non-trivial amount of time has went into balancing already. This PR reads like you want to get free reign to design a rebalance on it without giving much information on the plan other than "more granularity is better", and that's a big ask.

To add on to what kyle said, there's nothing in here worth odd amounts, so nothing gets changed other than just making the math take a bit longer/more of a pain. imo if you want to make traitor toys that arent seen as much more seen, then they just need some love, rather than completely changing tc and how all that stuff is balanced.

**Comment by Zonespace27** [comment]
> To add on to what kyle said, there's nothing in here worth odd amounts, so nothing gets changed other than just making the math take a bit longer/more of a pain. imo if you want to make traitor toys that arent seen as much more seen, then they just need some love, rather than completely changing tc and how all that stuff is balanced.

Yes, as I've said in the PR body, making things worth an odd amount of TC will be planned for the PR after this,  since that hits closer to a "balance" change than this, which is more of a "get the go-ahead" PR.

**Comment by TDHooligan** [comment]
i kind of agree with the idea but also think it could become a bit more of a nightmare calculating what you can and cant buy at once, as most items will be two digits.
perhaps it's worth taking another look over these 1 cost items to see if extra features could be put onto them, as ultimately these items will still be competing with 'more microbomb' which is, for lots of players, always a fairly nice pickup.

**Comment by zjdtmkhzt** [comment]
Does this account for antagonists that do not buy their microbombs, like hunter and nukies?

**Comment by ThatFiveGuys** [comment]
I personally think 25 is way too big of a number, it seems like the scale of that number alone can be overwhelming. Not to mention i dont think the scale is needed. Id much prefer to see it changed to a smaller number like 20 tc

**Comment by Flaborized** [comment]
I think this PR is bad for the game, because I think that decreasing the value of each TC makes picking sets of items more complicated and daunting. It's just more math to do, and less immediately obvious to figure out what items can be bought with what. People *already* opt out of picking any set of items at all by buying surplus crates because they don't want to pick out items, and I think this would exacerbate that. 

Obviously the change makes each TC worth (about) half as much, but I think that's also to the detriment of the point system. Small, impactful numbers are easy to compare and make meaningful decisions about, which I think is good. Of course, this only really applies when values are actually made to be odd, especially if items are worth just 1 TC. But if you do change items to be in accordance to this new pricing, you'd definitely want a 1TC item so that players can't ever be left over with unspent TC.

To me, these are strong reasons to not make this change *even with granular balancing*, but without any actual mechanical 
pricing changes I think this is just Worse with no immediate benefits. Especially since, in the immediate, normal loadouts will be left unsatisfyingly with one unspendable TC. Makes no sense as a PR on its own in my opinion, and still pretty bad even with later balancing changes.

**Comment by Zonespace27** [comment]
Added a document featuring my suggestions for price increases/decreases to the PR body

**Pull request closed without merging**
