### PR TITLE
Horizon APC fix

### PR DESCRIPTION
**Pull request by nefarious6th**
[mapping][bugfix]
Horizon runtime fixes by @Eagletanker 

## About the PR 
Fixes Horizon APCs

## Why's this needed? 
Runtimes

### CODE REVIEW

**Comment by Eagletanker** [comment]
Damnit I forgot an area

**Comment by nefarious6th** [comment]
first commit has the info you want; file size artificially large because i saved over the map with the updated file ¯\_(ツ)_/¯

**Comment by Sovexe** [comment]
> first commit has the info you want; file size artificially large because i saved over the map with the updated file ¯_(ツ)_/¯

Am I understanding that your PR blows out all of the most recent changes and reverts it to an older version of the map with apc fixes?

**Comment by nefarious6th** [comment]
> > first commit has the info you want; file size artificially large because i saved over the map with the updated file ¯_(ツ)_/¯
> 
> Am I understanding that your PR blows out all of the most recent changes and reverts it to an older version of the map with apc fixes?

it's the updated map version it just saved weirdly when i saved the downloaded file into my local repository and makes it look like it redoes the entire map. map diff renders shows where the APCs + cables were added correctly.

**Comment by Sovexe** [comment]
> map diff renders shows where the APCs + cables were added correctly.

to be fair #4229 didn't show any changes on the diff either when it changed those 40k lines that I'm wondering might have been reverted. Though I'm not entirely certain what was changed https://mdb.affectedarc07.co.uk/Files/252047483/2387696447/6/diff.png

**Comment by nefarious6th** [comment]
> to be fair #4229 didn't show any changes on the diff either when it changed those 40k lines that I'm wondering might have been reverted. Though I'm not entirely certain what was changed https://mdb.affectedarc07.co.uk/Files/252047483/2387696447/6/diff.png

i'll try re-merging master into this and work from there 🤷

**Comment by ZeWaka** [comment]
failing.

**Pull request merged**
