### PR TITLE
Bringing Cogmap2 up to date

### PR DESCRIPTION
**Pull request by Laboredih123**
## About the PR 
Brings Cogmap2 up to date as much as possible and yeets thindows.
Sets those rwindows with rthindows around them into reinforced plasma glass because clearly those windows wanted extra protection.

## Why's this needed? 
Begins the process of bringing maps to date.
Zewaka doesn't like thindows because apparently they are related to some bug.

## Changelog

```changelog
(u)Laboredih123
(*)Eradicates thindows from COGMAP2
(*)Sets all manually placed windows and grilles into wingrille_spawners, except for pesky non-reinforced windows as they spawn thindows.
(*)Replaces fully surrounded rwindows/rthindows into rplasmaglass.

```

### CODE REVIEW

**Comment by Laboredih123** [comment]
wait uh forgot the settings.json

**Comment by Laboredih123** [comment]
ignore everything behind the merging from master. thats unrelated to this pr

**Comment by ZeWaka** [comment]
> ignore everything behind the merging from master. thats unrelated to this pr

you should clean up your fork's master due to this

**Review by ZeWaka — COMMENTED** [review]
Really would've preferred this to be two separate PRs.

**Comment by Laboredih123** [comment]
> Really would've preferred this to be two separate PRs.

I'm guessing that means I should close this one and make another pr doing the same thing but not touching thindows. Then touch thindows.

**Comment by Laboredih123** [comment]
Still not experienced with PRs sorry

**Comment by ZeWaka** [comment]
Yeah it's just hard to review the thindow changes when every other window was touched at once.

**Comment by Laboredih123** [comment]
The thindows touched were the AI and Armoury

**Comment by Laboredih123** [comment]
Anyway Imma close this

**Pull request closed without merging**
