### PR TITLE
A recoloring of Kitchen Machinery

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
## About the PR 

Changes the colors of some kitchen machinery to a color pallet that is used in other places in the game, to hopefully make it look better than what it already is. 

## Why's this needed? 

having stuff share a color pallet is nice and looking good is also nice.

## Changelog

```
(u)MatheusIsNotAvailable:
(+)Made a small recoloring of some kitchen machinery 
```

### CODE REVIEW

**Comment by MatheusIsNotAvailable** [comment]
Everything that was changed compared to with the previous sprites

**Comment by ZeWaka** [comment]
to me, fryer1 looks like burnt oil instead of the previous oil color

**Review by flrsh — CHANGES_REQUESTED** [review]
Please try to use slightly lighter colors for shading. Near-black outlines are pretty jarring, especially if you have shadows that are that color.

**Comment by MatheusIsNotAvailable** [comment]
Ok, I will change it again

**Comment by MatheusIsNotAvailable** [comment]
@flrsh made it lighter as you requested

**Comment by flrsh** [comment]
Personally I'm not a fan of these recolorings (in that they don't add anything for me and I feel content with the originals), but if another developer feels strongly, I'll defer to them.

**Pull request closed without merging**
