### PR TITLE
Improves Cogmap1 Burnchamber Radiator Pipe coverage

### PR DESCRIPTION
**Pull request by comradef191**
## About the PR 

Adds a few more Radiator Pipes to the Enginering Burnchamber of Cogmap1.

## Why's this needed? 

Small QoL change that makes running the engine on cog1 just that slightly less painful

## Changelog

```
(u)Comradef191:
(+)Slightly Improved Radiator Coverage in the Cogmap1 Engineering Burnchamber
```

### CODE REVIEW

**Comment by Sovexe** [comment]
if the idea is removing the pipes from the burn chamber, why leave the top right pipe in the burn chamber

**Comment by comradef191** [comment]
Just had a much better idea that minimises the amount of pipes that could burst, standby.

**Comment by Sovexe** [comment]
image

requires some modification

**Comment by comradef191** [comment]
image
New Improved Layout

**Comment by Sovexe** [comment]
this also works

**Pull request merged**
