### PR TITLE
Removing finger snapping off chance from *snap and removes nipple tweaking

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
[QoL]
## About the PR 

This PR removes the 1/20 (5%) chance of having your finger snap off when you used the *snap emote. This gave 20 brute. 
I also removed the nippletweaking emote

## Why's this needed? 

This is needed as the 5% chance of receiving 20 brute for using a hotkey emote completely nuked any use of the emote for its purpose other than to deal massive amounts of damage to themselves.

Also nippletweaking is gross

## Changelog

```changelog
(u)Yellow-Mushroom
(*)Removed the chance to have your finger snapping off
(*)Removed nipple tweaking emotes
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
you're removing nipple tweaking? _you monster_

**Comment by ZeWaka** [comment]
big downvote, PR description is evasive to what the PR actually does

**Comment by Yellow-Mushroom** [comment]
> 
> 
> big downvote, PR description is evasive to what the PR actually does

Went ahead and fixed it, I was worried that mentioning it would Streisand effect nipple tweaking

**Comment by Gannets** [comment]
I'm not especially attached to either of these. But if the damage is the problem couldn't you just reduce or remove the damage component?

**Comment by flrsh** [comment]
Seconding Gannets, reducing the damage to 10 seems fair to me.

**Comment by Yellow-Mushroom** [comment]
> 
> 
> Seconding Gannets, reducing the damage to 10 seems fair to me.

emoting with a chance of doing damage to yourself completely stops the emote from being used, that's why snapping is never used

**Comment by ZeWaka** [comment]
> > Seconding Gannets, reducing the damage to 10 seems fair to me.
> 
> emoting with a chance of doing damage to yourself completely stops the emote from being used, that's why snapping is never used

I disagree. I use the snap emote ingame when I play semi-often. It's fun to do the 'tough guy finger snapping' with a gang before you beat someone up.

**Comment by Kyle2143** [comment]
Trying to sneak in a change inside your PR by omitting it from the title and description is really awful. Don't do it again, I am unsure if we have a rule against it deliniated in the contributor guidelines, but it should go without saying. Regardless, I'll update those soon to reflect it.

As far as snapping goes, I think simply reducing the damage to something like 1-5 would be better. 20 is unreasonably high, I didn't know it was that high.

Regarding the tweak emote. That's Dr. Singh's joke and I wouldn't remove it without his say so.

**Comment by Yellow-Mushroom** [comment]
> Trying to sneak in a change inside your PR by omitting it from the title and description is really awful. Don't do it again, I feel like I should close this PR on principle even though Zewaka edited the title. I am unsure if we have a rule against it deliniated in the contributor guidelines, but it should go without saying. Regardless, I'll update those soon to reflect it.
> 
> As far as snapping goes, I think simply reducing the damage to something like 1-5 would be better. 20 is unreasonably high, I didn't know it was that high.
> 
> Regarding the tweak emote. That's Dr. Singh's joke and I wouldn't remove it without his say so.

I didn’t think it was an issue since nipple tweaking is super gross, I asked a dev and a few other people and they said it was just a gross a relic of old goon so I didn’t think it would be a big deal to tag it onto the PR I was pushing through about snapping instead of making a seperate one. I didn’t realize how bad of an idea it was. I’ll just close this :/

**Comment by ZeWaka** [comment]
> so I didn’t think it would be a big deal

> I was worried that mentioning it would Streisand effect nipple tweaking

these two quotes are not in conjunction with each other

**Comment by Yellow-Mushroom** [comment]
> 
> 
> > so I didn’t think it would be a big deal
> 
> > I was worried that mentioning it would Streisand effect nipple tweaking
> 
> these two quotes are not in conjunction with each other

Man I'm just tired of this, I didn't understand the severity of not overtly stating that I was removing nipple tweaking as I thought it was extremely inappropriate and not for Goonstation as its a sexual harassment thing "4. Bigotry and sexual content is a non-negotiable hard 'no'.". I originally had it stated as "removing a gross emote" since I thought my mentioning nipple tweaking it would have a Streisand effect of making people nipple tweak which would make me honestly not want to play that round anymore. I asked multiple people and a Dev and got told it was an old relic so I didn't think anyone would miss having an in-code way to sexually harass people in-game.

**Comment by flrsh** [comment]
For what it's worth I'm totally onboard with removing nipple tweaking. I think the issue other people had was just that your PR was initially quite evasive about what it did. All in all though it's not a big deal, so I hope you don't take it too harshly.

**Comment by Yellow-Mushroom** [comment]
> For what it's worth I'm totally onboard with removing nipple tweaking. I think the issue other people had was just that your PR was initially quite evasive about what it did. All in all though it's not a big deal, so I hope you don't take it too harshly.

Thank you, I think I overreacted about this whole thing, I’ll probably make another PR soon for snapping without removing the finger snap, and probably another for nipple tweaking if no one gets to it first

**Pull request closed without merging**
