### PR TITLE
Makes Donut 3 mineral magnet larger

### PR DESCRIPTION
**Pull request by TTerc**
## About the PR 

As the title says. Instead of 9x9, the magnet inner area is now 11x11:

Also made several other tweaks to mining office, scroll down to the comments section to see them.

## Why's this needed? 

People have been saying donut 3 mineral magnet is too small and I agree with them. It's noticeable when some pulled asteroids are weirdly shaped, like they were "cut" from a larger asteroid

## Changelog

```changelog
(u)TTerc
(+)Donut 3: Made mineral magnet area larger, tweaked the mining office layout.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
now the magnet is really off-center, possible to move it?

**Comment by TTerc** [comment]
hmm off center to what?
here's how it looks zoomed out, there is no way to move it really, without changing the design of rooms nearby

**Comment by ZeWaka** [comment]
no, like the projection unit thing, blue and white

**Comment by TTerc** [comment]
hmm, it'll always be slightly off center due to the ring being 11x11. I can move it a bit, shifting the catwalk layout or place two mineral magnet thingies on both sides I guess (like on Horizon)

**Comment by ZeWaka** [comment]
> hmm, it'll always be slightly off center due to the ring being 11x11. I can move it a bit, shifting the catwalk layout or place two mineral magnet thingies on both sides I guess (like on Horizon)

yeah, i was moreso saying it's *even more* offcenter now

**Comment by TTerc** [comment]
So I made the magnet less off center but due to having to change the shape of mining office slightly I also ended up tweaking the donut 3 mining overall. Notable changes:
-moved the mineral magnet console outside for easier access and lit up the outside catwalks
-added an extra fabricator and extra recharger to refinery
-fixed an improperly placed fire alarm
-fixed the arc plater direction
Overall personally I'm happy with the changes and I think it improves the mining experience

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
