### PR TITLE
Adds more viarety in station/big station bounties, makes them more common.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
The amount of person bounty amts has been reduced to 4 (mostly to keep the bounty total amount roughly equal) and the station_bounty_amt and big_station_bounty_amt has been upped by 1. Several higher impact items have been added to these lists (just look at code for this one). Oh also adds some ifdef for things so ocean stuff isnt a bounty on space maps and vice versa.

## Why's this needed? 
These types of items being stolen tend to have the most impact on the overall flow of the round. By having more of these items stolen, and the stolen items being more impactful, this should increase the impact spies directly have on a round.

## Changelog

```changelog
(u)Ikea
(+)The amount of station/big station item bounties for spies has been increased.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
ditto on the telesconsole.

two other questions: port-a-brig was removed from bounty list. intentional or not, since it is replaceable (also getting arrested in it and then waiting in interro and stealing it while you wait is hilarious).

any way to verify that the  selector will choose the captain's space suit OR the red captain's space suit OR the blue captain's space suit for the space suit bounty versus choosing the Red Captain's Spacesuit for the bounty, which might not be in a round? i didn't see anything for it but might've missed it.

**Comment by nefarious6th** [comment]
> ditto on the telesconsole.
> 
> two other questions: port-a-brig was removed from bounty list. intentional or not, since it is replaceable (also getting arrested in it and then waiting in interro and stealing it while you wait is hilarious)?
> 
> any way to verify that the selector will choose the captain's space suit OR the red captain's space suit OR the blue captain's space suit for the space suit bounty versus choosing the Red Captain's Spacesuit for the bounty, which might not be in a round? i didn't see anything for it but might've missed it.

**Comment by ThatFiveGuys** [comment]
SMES and teleconsole are both replaceable by cargo and tech storage respectively.  Port a brig removal was unintentional and Ill readd that, for the space suit question, good point Ill test that out.

**Comment by ZeWaka** [comment]
Labels

**Comment by ThatFiveGuys** [comment]
> ditto on the telesconsole.
> 
> two other questions: port-a-brig was removed from bounty list. intentional or not, since it is replaceable (also getting arrested in it and then waiting in interro and stealing it while you wait is hilarious).
> 
> any way to verify that the selector will choose the captain's space suit OR the red captain's space suit OR the blue captain's space suit for the space suit bounty versus choosing the Red Captain's Spacesuit for the bounty, which might not be in a round? i didn't see anything for it but might've missed it.

Readded port a brig, and also tested it out but game doesnt care about spacesuit colors.

**Pull request merged**
