### PR TITLE
Resprites critter roaches

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 
This resprites critter roaches, as in, the lil pests you see sometimes. Includes a resprite for Robot Cockroaches and also the ghost critters (so there are updated colour keys etc for that). Previews (updated 26/5 after some feedback);

image
roachanim3
roachanim4
RoachScale

I tried to make the front and back view animations emphasize their crawliness. Ahaha.

## Why's this needed? 
As cute as the old roach sprites were, the perspective on the north and south views bugged (hehe) me a little. I figure people might be attached to the old sprites, so if folks don't want to merge this then that's alright. Just wanted to give repriting it a shot for fun, and people seemed to like the new sprites on imspriter!

## Changelog

```changelog
(u)Walpvrgis
(+)Roach critters have had a resprite to match perspective better.
```

### CODE REVIEW

**Comment by penny64** [comment]
I kinda don't like how complicated their designs are!

**Comment by WALPVRGIS** [comment]
> 
> 
> I kinda don't like how complicated their designs are!
> They have a significant presence

Is there anything in particular that stands out with regards to this?

**Comment by BatElite** [comment]
Do you think you can make the line where the wings overlap less contrasting? I think that might stand out a bit much atm.

**Comment by WALPVRGIS** [comment]
> 
> 
> Do you think you can make the line where the wings overlap less contrasting? I think that might stand out a bit much atm.

Here's a quick edit with a bit less detail (lightened the outlines too so they're less striking) :)
image

**Comment by penny64** [comment]
@WALPVRGIS I'm sorry I couldn't express myself well but I think that lookr great!

**Comment by WALPVRGIS** [comment]
> 
> 
> @WALPVRGIS I'm sorry I couldn't express myself well but I think that lookr great!

All good! I'm happy to make changes based on feedback, just wasn't sure where to start hehe. :P

**Review by Gannets — APPROVED** [review]
Yep, happy with these after the changes
Looks great!

**Pull request merged**
