### PR TITLE
(ADOPT) Adds 10 new departmental puffer coats

### PR DESCRIPTION
**Pull request by Retrino**
## About the PR 

Adoption of #14099 by Thrush. All sprites done by her and Sunkiisu. 

10 new puffer coats added to their respective departmental vendors/equipment boxes. Specifically, the sec, 3 medical, sci, and 2 engi go into their vendors, while the botanist, rancher and janitor's go into their equipment boxes. examples below from the original pr
243516690-464d0429-92be-496a-a169-55d318bd18e8
243516609-8c8a9d58-97c2-4342-a374-90d52fcd695a
243516856-4985e3a0-2c22-439f-8e42-c725e1a10f27

## Why's this needed? 
These were approved but went stale, and as the original PR states, more departmental clothing is a great option for character customization while still keeping job theme. These sprites were too good to let go to waste.

## Changelog 

```changelog
(u)Temthrush & Sunkiisu
(*)Adds 10 different outerwear which can be found in department vendors/equipment boxes. See PR for location details.
```

### CODE REVIEW

**Comment by Flaborized** [comment]
since my review was requested: looks alright, don't have very strong feelings on this PR or the last one though

**Comment by Retrino** [comment]
> since my review was requested: looks alright, don't have very strong feelings on this PR or the last one though

if youre wondering why, i requested since you originally had approved the changes and requested flabo because... sprites

**Comment by Flaborized** [comment]
> > since my review was requested: looks alright, don't have very strong feelings on this PR or the last one though
> 
> if youre wondering why, i requested since you originally had approved the changes and requested flabo because... sprites

i am flabo :eye:

**Comment by Retrino** [comment]
> > > since my review was requested: looks alright, don't have very strong feelings on this PR or the last one though
> > 
> > 
> > if youre wondering why, i requested since you originally had approved the changes and requested flabo because... sprites
> 
> i am flabo 👁️
LMFAO im so sorry, i cant read

**Comment by Azrun** [comment]
Do we have an answer for: https://github.com/goonstation/goonstation/pull/14099#issuecomment-1591513124

I like the assets. I just don't know if I like the assets in normal games.

**Comment by Retrino** [comment]
> Do we have an answer for: [#14099 (comment)](https://github.com/goonstation/goonstation/pull/14099#issuecomment-1591513124)

yes, i have a couple points in regards to that. 

answering the question of why stations would even stock winter coats: in a plasma research facility, accidents and breaches are to be expected. and when our maps are majority space based, those breaches are going to make everything pretty cold. stations are equipped with all sorts of machinery and items to help deal with these breaches, so something simple like winter coats doesnt seem too far fetched for them to provide. (also, have yall ever been in office buildings? cold as hell)

from a game design perspective, its to my understanding that job clarity is important. providing more options for players to choose from lets them keep the customization aspect, while still having the clarity in departmental theme. this seems like a win win to me. 

the bit about space sears… i dont know, this seems heavily subjective. ive worked at many places that had hoodies, jackets, shirts, etc with company branding. they fit within the themes and color palettes of the departments, are they not uniform in that sense?

**Review by DisturbHerb — APPROVED** [review]
Approving just to get this thing tagged for final dev review.

**Comment by DimWhat** [comment]
I like a lot of these more than the actual departmental winter coats we have right now and would kinda prefer something like getting one per job like how we get bespoke backpacks (for the most part) for roles.

**Comment by DisturbHerb** [comment]
I think that the current sets of winter clothing we have and the puffer jackets should be able to co-exist, and made available via the vendors. I don't think tying them to xp or medal rewards is the right way to go about things, as they are more painful to implement with increasing numbers of variants.

At present, stock seems too low to keep up with the vigorous demand, and the number available per role (2 to a variant) is not at parity with regular winter coats (which come 5 to a variant).

**Comment by wolfolotl** [comment]
from playing a few rounds with them testmerged: they look quite good, and they communicate each job well. only real issue (aside from no monkey sprites right now) is if somebody's walking around in a coat from a different department, but the same could be said for like... our current winter coats, or the extra jumpsuits. so it's not really an issue inherent to the coats in my eyes

**Comment by Spyritdragon** [comment]
I've definitely enjoyed them while testmerged, and other than the supply issues I definitely think it's been a nice addition. I'm not a huge fan of the idea of it being an XP linked medal reward to convert an existing piece personally - I definitely agree they should be able to coexist with the existing winter coats. Many departments also dont have a default outerwear you could easily change with a medal. 

Perhaps if in the vendor, they could use slightly increased numbers to alleviate supply issues. Though I think part of the demand is also likely simply from how new they are, I still think they'll be quite popular in the long run.

**Comment by AXLFAN2000** [comment]
Not a huge fan of it being more medal rewards, I enjoyed it being in vendors though it would be nice if it was a slightly higher stock and for jobs that don't have departmental coats normally (Janitorial) it would be nice if it was added to the JaniTech coz not all maps have the janitorial equipment boxes

I absolutely dig the sprites though they fit well while being unique (and the botanist one is perfect for angler as well)

**Comment by Retrino** [comment]
if they remain in the vender, the amount of coats available will probably stay the same. part of my argument with this pr is increasing the diversity in departmental clothing, but having everyone wearing the same puffer jacket sort of comes full circle with that specific point. 

ive heard your woes, the xp idea sucks. i also agree because im not going to code geneticist xp. however, i still like the idea of them being a job reward, like ai skins. the only issues i see with this are the consistency (why are one of the coats in the vender and the other is a job reward) and an old bug with dying and being cloned causing you to no longer be able to claim job rewards. if that bug has been fixed by now… huzzah

**Comment by pali6** [comment]
My arguments for this are that fashion which lets people see at a glance what department you are is preferable to fashion which does not. Therefore this is good.

But if others don't want it in as-is we could compromise of including these as winter seasonal content similarly to how stuff is in fall mode right now.

**Comment by AXLFAN2000** [comment]
The goal of diversity makes sense, I'd rather see these in as a medal reward or limited vendor stock than not have them at all.  I really enjoy how they look and from asking around it seems like a lot of other people did too so hopefully there's a home for them in the game without being a seasonal thing

**Comment by frawhst** [comment]
Gonna add these as winter-only for now

**Pull request merged**
