### PR TITLE
Fixed Oshan Toxins

### LINKED ISSUE #12663: Oshan Toxins not working proper
### Labels

[BUG] [MAJOR]

### Description

It's very difficult to use oshan toxins as heat leaks

### Steps to reproduce

1. Go scientist, go oshan, go toxins
2. start a burn to heat up some plasma
3. the heat shields   fail to shield heat
4. the room heats up to an unbearable degree
5. you are forced to apply burn patches to yourself or fully suit up in order to use oshan toxins

### Expected Behavior

The heat shields actually keep the heat out, the room not heat up (like in every other toxins lab)

### Additional Information & Screenshots

It's been like this for a long time from what i can tell. I am fairly certain that this isn't `possibly intended` since no other toxins work like that, but who knows? If it is intended, just lemme know i guess.

### PR DESCRIPTION
**Pull request by TheTyrant25**
[MAPPING] [MAJOR]
## About the PR 
Replace the turf under the oshan heat shield with `/turf/simulated/floor/engine/vacuum`, in line with toxins in other maps like cogmap.
It was previously `/turf/simulated/floor/plating/random`, which probably was why the entire room would heat up despite the heat shield being locked

## Why's this needed? 
Toxins was totally unusable without a firesuit pretty much. fixes #12663

### CODE REVIEW

**Comment by TheTyrant25** [comment]
note: some heat still leaks through, but the regular amount. Like on other maps

**Comment by TDHooligan** [comment]
_technically_ unrealistic, but also, pointless and frustrating for oshan scientists
i think it's a good idea.

**Comment by TheTyrant25** [comment]
the turfs actually inside the burn chamber are vacuum anyway. It's not really that much of a stretch to remove the air from the window

**Comment by TDHooligan** [comment]
yeah nevermind, misinterpreted the patch (now just a good change)

**Comment by TDHooligan** [comment]
yeah nevermind, misinterpreted the patch (now just a good change)

**Pull request merged**
