### PR TITLE
Rainburger and Colorpaste

### PR DESCRIPTION
**Pull request by stonepillars**
[crayons][sprites][feature]
## About the PR 

* Adds colorpaste, a flashy goo made by putting yuckburn and 3 crayons in an oven. Has 5 units of colorful reagent.
     * Mark my words, this will be used in another PR for crayon-related crafting shenanigans. Probably something involving making longer-lasting material crayons that take more effort than plating.

* Adds rainburger, a equally flashy rainbow burger made using colorpaste (Dough + Colorpaste). Has 5 units of colorful reagent.

## Why's this needed? 

image
Because crayons are awesome and I am going to make stuff with colorpaste in the future. For now it's a way to make small amounts of colorful reagent for the chemically ignorant.

## Changelog

```changelog
(u)Stonepillar
(*)Added rainburger, created using dough and colorpaste. Check minor changes for how to make colorpaste.
(+)Colorpaste can be created burning something in the oven, and then putting it back into the oven with 3 crayons.
```

### CODE REVIEW

**Comment by DimWhat** [comment]
Would prefer it be like colored krabby patties from spongebob

**Comment by Kyle2143** [comment]
This sprite is pretty decent, but I was actually 100% expecting Pretty Patties yeah.

**Review by flrsh — CHANGES_REQUESTED** [review]
I think there's like three different names for the burger - rainburger, crayonburger, and colorburger. Could you change the names/paths so that it's consistently one name please?

**Review by flrsh — APPROVED** [review]
Looks fine to me.

**Review by Tarmunora — CHANGES_REQUESTED** [review]
critter_egg iconstate is modified

Also, the colourpaste/rainburger sprites seem a bit too flashy/high-saturation. Could they be toned down?

**Comment by stonepillars** [comment]
For more than one reason, this PR is being closed. Mostly to just re-sprite the entire pull, but also because I want to re-write it _after_ fleshing out the crayon-related features that will stem from it. Expect a different pull in the future with this feature.

**Pull request closed without merging**
