### PR TITLE
TGUI contributor rewards

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR [qol]

chui bad. tgui good. contributors yay.

## Why's this needed? 

die die die die die

get fukt @TheFakeElon this is proof i can make PRs :shipit:

### CODE REVIEW

**Comment by flrsh** [comment]
You're setting a bad example for how to fill out the PR template image

**Comment by ZeWaka** [comment]
> You're setting a bad example for how to fill out the PR template image

i answered the questions it asked

**Comment by Josephin23** [comment]
just as i wanted to make robotic hypospray TGUI, how convenient

**Comment by ZeWaka** [comment]
!merge_upstream

**Pull request merged**
