### PR TITLE
Phones resprited by TheStoneGol

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
image

## Why's this needed? 
The current phones are all monochromatic which doesn't look all that great imo.

## Changelog

```changelog
(u)TheStoneGol
(*)Phones have been resprited
```

### CODE REVIEW

**Comment by Arthur-Holiday** [comment]
These are harder to tell apart

**Comment by TobleroneSwordfish** [comment]
> These are harder to tell apart

realistically you generally know which phone you're picking up by where it is, not what colour it is
could colour the dials and buttons though I suppose

**Comment by penny64** [comment]
I don't like the gray

**Comment by pali6** [comment]
Updated to look like this https://cdn.discordapp.com/attachments/890231630097182720/916302104447045703/unknown.png

**Review by frawhst — APPROVED** [review]
I enjoy these

**Pull request merged**
