### PR TITLE
Requisition payout buff pass

### PR DESCRIPTION
**Pull request by Kubius**
[BALANCE]
## About the PR 

Buffs the new QM requisitions to a state where they're a bit more competitive with other sources of income:

**Civilian: Event Catering**
- Baseline fee increased from 500 to 6,000.
- Weight decreased to 70.
- This is a rather heavy load on the Kitchen even in the minimum scenario, so less frequency and better reward should make sense.

**Civilian: Interior Outfitting**
- Baseline fee increased from 800 to 2,200.

**Civilian: Crew Embarcation**
- Baseline fee increased from 700 to 1,500.
- Payout randomization now scales with crew count, up to a peak of 4,800 additional credits when making 12 gear sets.
- While fairly straightforward to assemble, this one can grow quite tedious considering the heavy volume of cloth input and manufacture required, and can require infrastructure that doesn't start in QM, hence the higher peak reward.
- Payout per unit of water increased from 4 to 5.

**Civilian: Birthday Party**
- Baseline fee increased from 900 to 2,000.
- Fee per cookie in cookie variants increased from 160 to 240.
- Bigger increase for cookie variants due to the amount of labor involved in them.

**Aid: Breach Recovery**
- Baseline fee increased from 1,200 to 3,000.

**Aid: Medical Aid**
- Baseline fee increased from 1,100 to 3,000.
- Pay per surgical item buffed: 180 for most types, 190 for circular saws (bit of variance), 330 for staple guns (cost more to manufacture).
- Pay per health analyzer increased from 450 to 600.
- Pay per bandage increased from 150 to 210.
- Pay per latex glove pair increased from 110 to 150.
- Individual items paid out a bit stingy given you'll probably have to manufacture them yourself and can't just dump them out of a toolbox, ergo buffs.

**Aid: Computer Core Failure**
- Baseline fee increased from 900 to 2,500.

**Aid: Supply Chain Failure**
- Baseline fee increased from 900 to 2,400.
- Payout per unit of welding fuel increased from 4 to 6.

**Scientific: Organ Analysis**
- Baseline fee increased from 1,750 to 2,500.

**Scientific: Spectrometry**
- Baseline fee increased from 750 to 1,200.
- Relatively small increase is due to the already good payout from individual items.

**Scientific: Botanical**

- Payout increased from 950 to 3,500.
- Per-seed payout increased from 300 to 900.
- This requires a fair bit of dedication to accomplish compared to alternatives, and even with the vendor refill reward, its previous state was not even close to appealing as a long-term goal to pin.

## Why's this needed? 

Requisitions are a bit undertuned in their launch state, and after assessment of how rewarding they've felt post-launch, a bit of an upward bump seemed suitable. These shouldn't outcompete other options by miles, but the payouts should feel much better after assembling the necessary items.

### CODE REVIEW

**Comment by Nexusuxen** [comment]
I haven't played with this personally but a couple people I've talked to have lamented over the inability to print out the requisitions - namely ones that come as big lists that other departments need to work on (such as Botany and Catering). This isn't directly related to the PR, but in terms of improving the new system, perhaps this could be considered?

**Comment by Kubius** [comment]
Very good suggestion, can and likely will tackle that in a separate PR.

**Review by Tarmunora — APPROVED** [review]
lgtm

**Review by pali6 — APPROVED** [review]
Looks good to yass

**Comment by Azrun** [comment]
👍numbers go brrr 👍

**Pull request merged**
