### PR TITLE
Cog1 - Redesigned cloning bay and genetics lab

### PR DESCRIPTION
**Pull request by scrcr0**
[QOL]
## About the PR 
Redesigned the cloning/genetics sections of medbay. Compactified genetics and expanded the staging area around the cloning console. Moved lockers out of the main corridor and into the staging area. Genetics has been reduced in size ~~and now has direct access to the monkey pen.~~

Updated.

- Route to monkey dome now requires passing through OR.
- Moved mutadone out of easy reach of passing crew.
- Moved some other room props around to make room for door and maintain easy movement through the genetics suite.

cloning_pr_4
cloning_pr_5
cloning_pr_6

## Why's this needed?
Cloning has always been a mess. With only a single tile's width of space to move around in, things quickly got messy and confusing. Storage lockers in the main corridor would inevitably end up pushed around and block movement through the space. Bodies would often go un-scanned because of the lack of space and reluctance to use the morgue. 

## Changelog

```changelog
(u)zcrow
(*)Redesigned the Cog1 cloning bay/genetics labs to optimize space and efficiency. 
```

### CODE REVIEW

**Comment by Flaborized** [comment]
I don't really like how this change gives geneticists a little easy-access door to the monkeydome. The map was built specifically with the route of 'geneticist has to take the monkey through surgery with all the sharp tools' in mind and I think removing that aspect makes the map blander and worse, even though it gives genetics an easier time. Better to just have the doors roughly the way they were imho

Also this is a minor nitpick but if the pill bottle on the surgery table is a mutadone pill bottle I think it's a Much Worse Spot for it. It's good when people ask genetics for mutadone specifically (even though really any doctor can give it to you), this change means they only need to walk into the operating theatre instead of genetics itself which I think is easier to accomplish without talking to anybody

**Comment by scrcr0** [comment]
> I don't really like how this change gives geneticists a little easy-access door to the monkeydome. The map was built specifically with the route of 'geneticist has to take the monkey through surgery with all the sharp tools' in mind and I think removing that aspect makes the map blander and worse, even though it gives genetics an easier time. Better to just have the doors roughly the way they were imho
> 
> Also this is a minor nitpick but if the pill bottle on the surgery table is a mutadone pill bottle I think it's a Much Worse Spot for it. It's good when people ask genetics for mutadone specifically (even though really any doctor can give it to you), this change means they only need to walk into the operating theatre instead of genetics itself which I think is easier to accomplish without talking to anybody

Appreciate the feedback. Making those changes won't be a big task. My proposed revisions:
- Replace the route to monkeydome to go via the OR, as before.
- Move the mutadone away from the counter to somewhere where players need to interact with geneticists to get to it.

**Comment by scrcr0** [comment]
Updated.

- Route to monkey dome now requires passing through OR.
- Moved mutadone out of easy reach of passing crew.
- Moved some other room props around to make room for door and maintain easy movement through the genetics suite. 

cloning_pr_4
cloning_pr_5
cloning_pr_6

**Comment by BatElite** [comment]
Don't forget to put a gene power module back in somewhere.

**Comment by scrcr0** [comment]
> Don't forget to put a gene power module back in somewhere.

oh snap, good spot. will update today.

**Review by flrsh — COMMENTED** [review]
I don't think the monkey pen needs to be so big - consider expanding the left side of genetics down so that both sets of equipment are on the same y axis (and if you do this, probably replace the table with a full trash chute, and put some more tables right next to the top windows).

**Comment by scrcr0** [comment]
> I don't think the monkey pen needs to be so big - consider expanding the left side of genetics down so that both sets of equipment are on the same y axis (and if you do this, probably replace the table with a full trash chute, and put some more tables right next to the top windows).

Got it. I was originally aiming to avoid changing existing map features too much, but if you consider this a good option then consider it done!

**Comment by scrcr0** [comment]
Okay, updated as requested. I'm not super sure about the new shape of the monkey pen, but at least its more 'organic' now.

cloning_pr_8

**Comment by mordent-goonstation** [comment]
What's this highlighted stretch of wire for?
image

I would take a guess that electrifying the exterior windows was the goal here. Are they electrified in the OG version? If so, move the wires to electrify the exterior windows now. If not, I don't think they're doing anything so snip 'em, I guess?

**Comment by mordent-goonstation** [comment]
I would also consider putting the intercom on the wall rather than the window. Windows are somewhat more... temporary.

**Comment by scrcr0** [comment]
> What's this highlighted stretch of wire for?
> image
> 
> I would take a guess that electrifying the exterior windows was the goal here. Are they electrified in the OG version? If so, move the wires to electrify the exterior windows now. If not, I don't think they're doing anything so snip 'em, I guess?

You know what thats a good question. It may have already been under the existing windows, so I'll move it back to where it should be. As for the intercom, noted, will fix it to a wall instead.

**Comment by scrcr0** [comment]
Rerouted that janky cable back under the windows where it belongs. Moved the intercom to a solid wall, rather than the window it was previously attached to. 

cloning_pr_10
cloning_pr_9

**Review by flrsh — APPROVED** [review]
Looks good to me. If you wanted that part of the monkey pen to look a bit more natural, you could plop a long couch down by the palm tree, up to you.

**Comment by Kubius** [comment]
Conflict is likely due to the version of the map that's been edited being prior to the book rework. Other notes not related to conflict:

- Windows are not properly wired, and a wire is sticking into the east wall for what seems to be no particular reason.
- Fire alarms should generally not be attached to south walls or windows if possible, and it's both; there's a spot open on the wall by the east door that would be very suitable.
- Ephemeral xmas lights being inside junction windows (west and south) is weird.
- A chair on the west side of the north-center table might make a nice addition, but is not strictly required.

**Review by Kubius — COMMENTED** [review]
Conflict is likely due to the version of the map that's been edited being prior to the book rework. Other notes not related to conflict:

- Windows are not properly wired, and a wire is sticking into the east wall for what seems to be no particular reason.
- Fire alarms should generally not be attached to south walls or windows if possible, and it's both; there's a spot open on the wall by the east door that would be very suitable.
- Ephemeral xmas lights being inside junction windows (west and south) is weird.
- A chair on the west side of the north-center table might make a nice addition, but is not strictly required.

**Comment by scrcr0** [comment]
> Conflict is likely due to the version of the map that's been edited being prior to the book rework. Other notes not related to conflict:
> 
> * Windows are not properly wired, and a wire is sticking into the east wall for what seems to be no particular reason.
> * Fire alarms should generally not be attached to south walls or windows if possible, and it's both; there's a spot open on the wall by the east door that would be very suitable.
> * Ephemeral xmas lights being inside junction windows (west and south) is weird.
> * A chair on the west side of the north-center table might make a nice addition, but is not strictly required.

Got it. Will update my repo with latest master and copy the map changes over. I'll fix those flagged issues alongside.

Thanks!

**Comment by flrsh** [comment]
@scrcr0 still working on this?

**Comment by Bram-KEP** [comment]
This seems cool, having cloning be less of a mess is nice.

**Comment by ZeWaka** [comment]
@scrcr0 ?

**Comment by scrcr0** [comment]
Apologies, IRL got in the way and this fell by the wayside. Update coming later today.

**Pull request closed without merging**
