### PR TITLE
Renames inappropriate Grones soda

### PR DESCRIPTION
**Pull request by Studenterhue**
## About the PR 
Renames the "Ballin' Banana Testicular Torsion" Grones drink to "Crunchy Kidney Stone Lemonade" (credit goes to Camryn Buttes for that name), keeping in line with the general naming scheme of other Grones sodas. (Personally, I also think it's plain better than my initial suggestion of "At Least It's Not Discount Dan's"). Contents are still urine, same as before.

## Why's this needed? 
"Ballin' Banana Testicular Torsion" runs afoul of our "no sexual content" rule, given the references to genitalia ("testicular" references the testicles, and in that context, "banana" refers to the penis rather than the fruit).  Personally, I think it's kinda funny, but it's also a name that's inappropriate for our servers and so should be changed.

Also, I think "Crunchy Kidney Stone Lemonade" is simply funnier than the previous, regardless of whether it breaks the rules.

### CODE REVIEW

**Comment by penny64** [comment]
I don't completely agree that that drink violates that rule since it's a medical condition and the replacement isn't very funny and doesn't match the tone.

**Comment by Studenterhue** [comment]
> 
> 
> I don't completely agree that that drink violates that rule since it's a medical condition and the replacement isn't very funny and doesn't match the tone.
> It breaks the rule in the same way that *piss does, in that a penis may theoretically be involved.

I acknowledge that "testicular torsion" refers to a medical condition, but the "no sexual content" rule forbids references to genitalia in all contexts, including medical. That's what "non-negotiable hard 'no'" means; there might be some contexts where griefing is okay for example, depending on the situation, but there is no such dependency for this rule. Talking about genitalia in a medical context is a little "softer" than say describing one's penis during ERP or insulting people about the size of their genitalia, but that doesn't mean it's still not forbidden.

I don't think the comparison to *piss is warranted. You can write about piss without talking about the sex organs, but "testicular torsion" very explicitly refers to a part of male genitalia. It's not just a "theoretically involved"; it's a "is involved".

To reiterate, if someone has another idea on what to name it, I'm all ears. This was just something  I came up with on the spot, not something chosen by a committee of admins or anything, so I don't want people to assume this is a "you have to accept this name regardless if you like it or not" situation.

**Comment by Kyle2143** [comment]
Yeah, I don't really feel like this violates the rule technically or even the spirit of the rule. Which is that it's supposed to keep out the sort of creepy or sexually charged interactions with players out of the game since that this game is not about having cybersex.

**Comment by Camryn-Buttes** [comment]
Crunchy Kidney Stone Lemonade

**Comment by penny64** [comment]
> Crunchy Kidney Stone Lemonade for a name

I love this even if we just add it

**Comment by Studenterhue** [comment]
> Crunchy Kidney Stone Lemonade for a name

I like it as well, and it does fit the general pattern of Grones soda names. Reason enough for me to switch over to that. 

> But this seems like a reasonable thing within the confines of the rule, it's not creepy or sexually charged content.
> The most important question is: does it make people uncomfortable? Maybe we should do a discussion thread?

Yes, it _has_  made people uncomfortable. Way back before I became admin, I introduced the game to a friend, and he mentioned how he found it kinda icky. Another friend of mine raised concern about it months ago because they also found it gross, and there was a sort of unfortunate "well, it's been like that forever I guess, it can't be helped" atmosphere. Even if it's not creepy or sexually charged, it still keeps away people interested in cybersex and similar by giving them practically zero ground to work on.  

I don't see any reason to make this a discussion thread about the rule, amongst the forum regulars or the admins. It is not poorly written, and there isn't some glaring loophole. In my eyes, this is just a clash of interpretations between a handful of people. Yes, I am also saying I, respectfully, disagree with kyle's view of the rule. It doesn't necessarily mean the entire admin team's position on the rule is conflicted or contradictory (actual enforcement is quite consistent), and I don't think we need a thread to resolve our differences.

I don't see much reason for a thread to come up with a name either, for it seems we both agree on a name now. Anybody's welcome to make a new thread to solicit another name idea, though, and, hey, if someone has something even better than "Crunchy Kidney Stone Lemonade", great. But I'm pretty happy with that name right now, so while I'm open, I'm not actively seeking.

**Comment by penny64** [comment]
That's all I needed to hear, the new name is great and will only affect the most squeamish

**Review by flrsh — APPROVED** [review]
Fine with me!

**Pull request merged**
