### PR TITLE
Unique Sprites For Cap/HoS Eguns

### PR DESCRIPTION
**Pull request by Flaborized**
[FEAT]

## About the PR 

As mentioned in the egun overlay PR, this PR adds a unique sprite for the egun the captain and HoS spawn with. Also changes the icon-switching for egun modes slightly since despite making that PR basically so I could make this one, I didn't have the foresight to account for how I'd implement this :shelterfrog:

Purely a cosmetic difference, no stat change or anything. Any eguns you get from a source other than the head lockers will look like the old variant. The cap's is meant to be slightly gaudy, while the HoS' is meant to fit their pseudo-cool aesthetic and I think looks particularly nice with the stun setting on.

Also no blue and red cap variants in this, they're meant to be fully distinct from the HoS variant, easily recognizable at a glance, and don't show up on your character's sprite at all, so blue and red caps will have to manage.

## Why's this needed? 

Have you ever been a traitor and stolen the egun from the HoS? It feels great, but it'd feel at least 2X better if the gun had the visual motifs of the HoS, just to remind yourself how cool you are for having managed it. Maybe if you have both they can remind you of the good times you had stealing them! Similarly, if you've ever been a secoff and caught a traitor who had an egun, you know who lost theirs and who to ~~blame~~ return it to. Or if they're scanned and everyone has one, you know who's fault it was.

I also think having some unique gear is cool and builds character. Hopefully accomplishes this without making them look so different as to make them look like different weapons (also why I want the in-hands to remain the same). Plus I think they look cool!

## Changelog 

```changelog
(u)Flaborized
(+)The HoS and Captain now have slightly unique looking eguns, to match their usual outfits.
```

### CODE REVIEW

**Comment by BatElite** [comment]
`so blue and red caps will have to manage.`
Finally, all these dorks will be redeeming the sword

**Comment by Cherman0** [comment]
While I think its more a symptom of egun sprites in general than this specific PR, i feel like its kinda hard to tell what the decals are, physically. They seem a bit too shiny to be paint but too flush with the gun to be an additional metal plate to me.

**Review by Tarmunora — COMMENTED** [review]
If you mechscan one of these, do you get a generic, or the painted one?

**Comment by Flaborized** [comment]
> If you mechscan one of these, do you get a generic, or the painted one?




Tested, you get painted, and can even scan both of them at once if you want, which is the behavior I intended (you can sorta 'blame' the cap or hos if eguns are floating around)

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
