### PR TITLE
Speed radio because having to click on individual channels to talk on them is annoying and I am too lazy to use ;

### PR DESCRIPTION
**Pull request by deathrobotpunch**
## Why's this needed? So when I am being murdered I can easily out them on radio, and also because QOL would be improved with this

### CODE REVIEW

**Comment by frawhst** [comment]
# Something went wrong here

**Comment by deathrobotpunch** [comment]
> Something went wrong here

I agree

**Comment by frawhst** [comment]
Oh I see. You're not merging your branch into our master branch, you're merging our master branch into our other outdated branches.

**Comment by deathrobotpunch** [comment]
> Oh I see. You're not making a PR to merge your branch into our master branch, you're merging our master branch into our other outdated branches.
> 
> Should say "wants to merge X commits into `master` from `yourname:branchname`" here. image

I realised that but it won’t let me change the base to master, hoefullly the admins close this soon

**Pull request closed without merging**
