### PR TITLE
3x3 random room: Portal room

### PR DESCRIPTION
**Pull request by FlameArrow57**
[CONTEST]

## About the PR 
This PR adds a portal 3x3 random room. Contains a note with an easter egg to a game.

image

## Why's this needed? 
Random room for contest

### CODE REVIEW

**Comment by FlameArrow57** [comment]
Can change note to a different theme if not wanting the easter egg

**Comment by blackrep** [comment]
Does entering portal actually do anything? If it's one of those portals that warps you to a random nearby location, might be usable to break into nearby restricted areas.

**Comment by FlameArrow57** [comment]
It doesn't, you can't actually enter it, it blocks entering the turf it's on

**Comment by ZeWaka** [comment]
Denying due to low effort

**Pull request closed without merging**
