### PR TITLE
Buffs potato cells

### PR DESCRIPTION
**Pull request by Crackaduck**
## About the PR 
this PR buffs potato cells by approximately 25%, not exactly 25% on small power cells however, potato passive regeneration is ever so slightly above that, however its so minimal I cant bother to find the exact percentage buff, and max capacity is also a bit higher on weapon cells, sitting at about a 45% buff

## Why's this needed? 
potato battery's, while mainly a joke, or meant to be a battery you switch to when your main one runs out in the case of skillfully cultivated ones, are still very underwhelming in terms of power, even when compared to poorly made matsci ones,  and could use a slight buff at the very least.

## Changelog

```changelog
(u)Carsontheking
(+)Potato batterys buffed
```

### CODE REVIEW

**Comment by BatElite** [comment]
genrate/recharge_rate are better the higher they are, right? Is it intentional that you're lowering those?

**Comment by Crackaduck** [comment]
> genrate/recharge_rate are better the higher they are, right? Is it intentional that you're lowering those?

I'm lowering the random factor yes, because it gets the generate/recharge_rate from the endurance divided by the random factor, unless I am misunderstanding of the code. Also thinking of changing it to buff them even more, but one change at a time

**Comment by Crackaduck** [comment]
> Would rather see a mild flat change than a scaling buff

could there be both? Even with a 100 U base buff for the small cells you'd need a average of 205 potency potato to match a plasma stone on capacity (181). The recharge is still a bit punishing, needing 44 endurace without a buff to match a plasmastone cell (.8). Keep in mind I haven't looked at the matsci code, but I do know that generic plasmastone is very much on the lower end of matsci powercells.

**Comment by Tarmunora** [comment]
Thoughts on non-linear scaling? Improved DNA scaling in the 0-50 range or so would probably be reasonable while not making absurdly-statted plants balloon out of proportion

**Comment by vocalpocal** [comment]
Personally I don't see much need to buff potato cells, as they are more of a joke. I tried to use them as an energy source in my arc fiend gimmick but I couldn't suck power out of them. I think either base stat buff or nonlinear is the way to go, because potato cells are just too laborious. 
Endurance infusion is painfully slow (compared to potency or MR/PR infusion) and if you want to blow potatoes to even just 200-300 endurance you need to spend at least 30 minutes in botany... and then you have potatoes that charge after 15 minutes of not being used yay. You can honestly just forget about endurance self recharging and focus on potency instead. Who even needs rechargeable potato cells when you get 20 of them in one harvest?
Actually, a potato mutation which produces potato cells directly would be both funny and convenient.

**Pull request closed without merging**
