### PR TITLE
Split combat log into multiple logs

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
The eventual goal is to split off some non-combat stuff from the combat log to new log types.

- [x] chemistry
- [ ] building / craft
- [ ] other stuff?

Misc changes:
- Re-enabled logging of dissolving bathbombs. No idea why it was commented out.
- Logs withdrawing from syringes
- Moves some misc logging categories around (erebite explosions to bombing, crop harvesting to station, teleportation to station, etc etc)

## Why's this needed? 
Everything is combat now, it's awful.

### CODE REVIEW

**Comment by pali6** [comment]
!merge_upstream

**Comment by pali6** [comment]
!merge_upstream

**Comment by frawhst** [comment]
Misc thoughts I'm typing out as I make changes: 
- Sorry for the massive amount of commits I was doing basically one change per commit for easier tracking (debatable)
- My personal standards are:
    - use chemical/food/drink on other person: **combat**
    - use chemical/food/drink on self/floor/wall/object: **chemistry**
    - do something to station (harvest plant, pick up item): **station**
    - station does something to you (you slip, you get gibbed by a portal, you get crushed by a vending machine): **combat**
        - teleporting is still station because it Feels like station (unless the teleporting also steals your liver or whatever)
    - indirect murdery stuff which is far off is **station** (buying a barrel of monkeys). indirect murdery stuff which is very proximate to murder is **combat** (activating a barrel of monkeys, toggling turrets, emagging shit)
- Losing/gaining mutations isn't really combat but I can't think of a better place. Maybe we could make a new abilities/bioeffects category? For gaining/losing abilities, gaining/losing mutations, and using abilities


TODO:
- Dejank pickpocket gun
- Maybe don't log Klutz stuff. I'm willing to try it and I'm also willing to axe it after a couple days if it adds bloat
- ~~Dejank artifact logging~~ that's a whole nother PR
- Revise extinguishers; maybe log under chemicals as it's already combat if you hit a person

**Comment by frawhst** [comment]
also i went through every instance of "combat" in the code and while I probably missed a few this should be pretty comprehensive for 'things that are combat that should not be combat'
also feel free to contest any of them I was fanning the hammer

**Comment by frawhst** [comment]
i'm gonna deconflict this by the end of the week

**Review by pali6 — COMMENTED** [review]
Looks good to me. Can't approve because this is technically my own PR even if aloe did all the work, smh.

Will need a matching PR in https://github.com/Xkeeper0/ss13-log-viewer

Will need secret repo changes

**Comment by frawhst** [comment]
Should be good to go once ^ that PR is merged

**Pull request merged**
