### PR TITLE
UM-002 - Afterlife Bar Renovations

### PR DESCRIPTION
**Pull request by UrsulaMejor**
## About the PR 

[Picture](https://i.imgur.com/GPkWNVn.png)

**Splits the afterlife bar into two parts**

- Upper Lounge is a sanctuary zone (no hurting other people), and is where you spawn.

- Lower Area is not a sanctuary zone.

- Going for a classy feel for the upper area, a sort of less classy feel for the lower area

- Buncha random bits and bobs around the new afterlife bar setup.

**Supporting code work**
- Added new sanctuary area for afterlife bar, made bar spawns into sanctuary zones, and added corresponding area sprites

- Made an afterlife version of the ATM that doesn't let you do deposits

- Made an afterlife version of the slot machine that takes cash instead of card withdraws

- Made a new map light, BRIGHTER WHITE, to make lighting up the bar easier

## Why's this needed? 

I felt like there's a bit of a disconnect right now between players who want to use the Afterlife Bar as a safe place to chill, and players who want to use the Afterlife Bar for a more anarchy-driven experience. I thought that splitting the bar into two mechanically and thematically distinct areas would help give both groups of players more of what they want.

While I was doing this, I expanded the afterlife bar to fill in some of the empty construction zones  surrounding it, and added a few more activities to do (blackjack, roulette, cash-based slots, etc.), and fixed some minor annoyances I had with the bar (for example, how close the ladder to heaven was to the exit light)

## Changelog

```
(u)UrsulaMajor:
(+) Renovated the Afterlife Bar, splitting it into a sanctuary lounge and a basement bar
```

### CODE REVIEW

**Comment by RSG250** [comment]
does it have a cigarette machine ? and other vending machines?

**Comment by UrsulaMejor** [comment]
Yes to cigarette machine, otherwise it has the same vending machines it already had

**Comment by geneva-breaker** [comment]
arcade + slot machines should probably be in the upper floor, avoid single-wide passages and dead ends when possible

**Comment by geneva-breaker** [comment]
oh also that pipe into the aquarium is going to frustrate some people im sure, not everyone who ends up there will understand to suicide out. biofilter it to the bar disposals imo

**Comment by UrsulaMejor** [comment]
Didn't want to put the arcade and slots on the upper level, as I wanted to make sure all solo activities were in the lower level (the upper level is for safe socializing). That said, I talked with warc in the discord and ended up rearranging things to get rid of the single-wide passageways and dead ends by moving the arcade/slots and vendors around a bit.

Added a biofilter to the aquarium chute. Now you can only pollute it with junk, not people.

**Pull request merged**
