### PR TITLE
Enables atmos archiving

### PR DESCRIPTION
**Pull request by Laboredih123**
[ATMOS][EXPERIMENTAL]

## About the PR 
Enables atmos archiving, making atmos behave equally in all directions as you would expect, instead of tending to prefer going some direction. Previously disabled for performance concerns, I believe atmos should be performant enough for this to be on again.

## Why's this needed? 
Consistency in atmos interactions is good, one could say.

### CODE REVIEW

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
I said this on discord, but just for the github record: since this is a flag that disabled for performance reasons it should be profiled with the `Disco Inferno` test scenario before being re-enabled.

**Comment by Laboredih123** [comment]
ok will do

**Comment by Laboredih123** [comment]
i infact, did not get around to it. will soon

**Comment by Laboredih123** [comment]
didnt then either lols lmaos

**Comment by Laboredih123** [comment]
should be super cheap nonetheless

**Comment by Laboredih123** [comment]
oh yeah this waiting on atmos optimisations pr

**Pull request closed without merging**
