### PR TITLE
Bespoke engineer gas masks

### PR DESCRIPTION
**Pull request by NightmareChamillian**
## About the PR 
This PR adds a purely cosmetic yellow-visored gas mask for engineers. It can be found in the engineering equipment/clothing vendor, and the CE's locker.
image
image

## Why's this needed? 
I'm of the opinion that the green gas mask just doesn't look good with the yellows and oranges of almost every engineer uniform there is, and would like to have an option of having a color-coded variant available to engineers. Lorewise, I feel like it wouldn't be too far of a stretch for engineers have uniquely identifying gas masks given the fact that their tools and space suits have departmental colors. 

## Changelog 

```changelog
(u)NightmarechaMillian
(+)Engies now get yellow-visored gas masks, which can be found in the clothing vendor. No, they're not better than normal ones.
```

### CODE REVIEW

**Comment by pali6** [comment]
I personally think this looks a bit too similar to the engineering space suit helmet at a glance and I sort of like the recognizability of the relatively iconic green gas mask. So I'm mildly against but only mildly.

**Comment by Momoberry** [comment]
fashion nice

**Comment by NightmareChamillian** [comment]
It used to use the same visor colors as the helmet, but I changed it to be more noticeably yellow. I can hue-shift it to be even yellower if it's really that much of an issue.

**Comment by Tarmunora** [comment]
Not really a fan of this.

**Review by MarkNais — APPROVED** [review]
I'm cool with it.

**Comment by pali6** [comment]
I think it just looks too close to the engineering space suit helmet and I don't think I'd want it like this in the game. If other devs disagree enough they can of course reopen the PR

**Pull request closed without merging**
