### PR TITLE
Chameleon backpacks and belts are now quiet

### PR DESCRIPTION
**Pull request by Zonespace27**
[BALANCE]
## About the PR 
No longer do chameleon backpacks and belts put the message in chat along with the rustle noise when you put things in it

## Why's this needed? 
So you can pull out/put away contraband quietly, so you aren't forced to use pockets for fear of "Joe Badman has put away the cyalume saber"

## Changelog

```changelog
(u)Zonespace
(+)Chameleon backpacks and belts no longer show a message when putting away/pulling out items
```

### CODE REVIEW

**Comment by Flaborized** [comment]
as the maker of chameleon backpack: this is a pretty cool idea, nice!

**Comment by Chatauscours** [comment]
I do like the change, but this would inderectly nerf the silent storages as both cost 1 TC, and the outfit is already extremly powerful in the right hands. Maybe with the change it would be considerate to raile the cost of the outfit to 2 TC.

Also, someone should slap an "add to wiki" label on this.

**Review by ZeWaka — COMMENTED** [review]
hmm yeah this does nerf stealth storage.... dunno what to think

**Comment by ZWRh3** [comment]
> hmm yeah this does nerf stealth storage.... dunno what to think

maybe just  enable it for the nukie one?

**Comment by Tarmunora** [comment]
Agree that this steps on the toes of stealth storage pretty heavily. Leaning towards a no on this

**Comment by flrsh** [comment]
Echoing Yass and Flab - 

>I forgot to reply to the PR when I saw the replies but upon reading the other comments and thinking about it I don't really think the change in general is good after all 
there's already an entire item designed to do exactly the thing this does, and it does it better. especially doesn't make sense to double the price for it since currently you could already pay 2 for a better version of this
and in general it's good to keep traitor item's identities unique when we can imo

**Pull request closed without merging**
