### PR TITLE
Adds a clown funeral parlor.

### PR DESCRIPTION
**Pull request by NewyearnewmeUwu**
## About the PR 

This adds a clown funeral parlor to the random rooms pool. It also adds a funny little flower that someone could get into mischief with. This is my first mapping PR of note so I appreciate any feedback.
image

## Why's this needed? 

It's funny.

### CODE REVIEW

**Comment by DimWhat** [comment]
Maybe add some stuff animal? It's still quite a funny idea though!

**Comment by NewyearnewmeUwu** [comment]
Yeah i'll just do that lol

**Comment by ZeWaka** [comment]
Picture in PR please

**Comment by NewyearnewmeUwu** [comment]
> Picture in PR please

Done.

**Review by frawhst — APPROVED** [review]
lgtm

**Pull request merged**
