### PR TITLE
Resprites several food inhands

### PR DESCRIPTION
**Pull request by MitchTheUser**
[OBJECTS]

## About the PR 

Resprites the inhand sprites for the following:
- Beer Bottle.
- Beer Bottle Shank.
- Coffee Cup
- Tea Mug.
- Pumpkin.
- Espresso Cup
- Cleaver.

FoodInhandsDisplay

In addition:
- EVERY TYPE OF PIE NOW HAS UNIQUE INHANDS.

This includes: Custard, Bacon, Fish, Butt, Cream, Chicken Pot, Slurry, Pumpkin, Lemon Meringue, Weed, Chocolate, Key Lime, Apple, Blueberry, Raspberry, Cherry, Blackberry, and Strawberry.

PieInhandsDisplay

## Why's this needed? 

Their current inhands don't properly resemble their item sprites. This PR should help create consistency between them.

Most of the sprites lacked any east facing directional sprites, which have now been added. 

Some problems with previous inhands:
- Beer bottle/shank used old bottle icons.
- Pie was very crusty and low quality, likely created by shrinking a pie sprite poorly.
- Coffee cup had inconsistent coloring based on direction. Item sprite was also recently resprited.
- Tea shared inhand sprite with the coffee cup instead of having its own.
- Pumpkin was extremely simple and did not resemble a pumpkin at all.
- Espresso Cup shared inhand sprite with coffee cup instead of having its own.
- Cleaver colors were inaccurate to its item sprite. North facing sprites were also in the wrong hands.

### CODE REVIEW

**Comment by DimWhat** [comment]
Those are some JUMBO sized coffee cups

**Comment by DisturbHerb** [comment]
> Those are some JUMBO sized coffee cups

caffeine drinker grindset 💪

**Review by flappybatpal — COMMENTED** [review]
Beer
- Feel the beer bottle shank is hard to read but inhand sprites are small so I'm not sure that can really change. Possibly highlighting on the sharp edges?
- Fancy beer has no inhand sprite. Technically it's not a beer subtype and the bottles are different colors so it may be out of scope, there are a whole lot of other bottles (mead, cider) that don't have an inhand right now.

Coffee cup
- espressocup uses the takeaway coffee cup sprite, should probably not until it gets a unique cup sprite

Tea cup
- Fairly indistinct but it matches the source and as always there is a lack of pixels to work with. 

Pumpkin
- Could also be used for `/obj/item/clothing/head/pumpkin`

**Comment by MitchTheUser** [comment]
Image has been updated with changes/additions.

> * Feel the beer bottle shank is hard to read but inhand sprites are small so I'm not sure that can really change. Possibly highlighting on the sharp edges?

I updated the shank to be a bit brighter at the tips to stand out more.

> * Fancy beer has no inhand sprite. Technically it's not a beer subtype and the bottles are different colors so it may be out of scope, there are a whole lot of other bottles (mead, cider) that don't have an inhand right now.

For the fancy beer, it is out of scope to make inhands for them, since fancy beer randomly chooses from a selection of 11 colors and 7 labels, making for a very high amount of combinations, the best I could do is give it a generic beer inhand. I do however plan to make some inhands for the other types of alcohol, but that will be another PR since there is so many variants in the game.

> * espressocup uses the takeaway coffee cup sprite, should probably not until it gets a unique cup sprite

I created unique inhands for the espresso cup.

> * Tea: Fairly indistinct but it matches the source and as always there is a lack of pixels to work with.

I added the little tea bag coming out of the cup to make it stick out as a tea cup instead of a brown mug.

> * Pumpkin: Could also be used for `/obj/item/clothing/head/pumpkin`

I plan to add some unique inhands in a future PR when I resprite the Jack-O'-Lantern.

**Comment by flappybatpal** [comment]
Oh something I forgot from yesterday! Jan pointed out that newer pies had the pie tin removed.

image

It does match the older pies but the newer ones have no tin, are browner and a different shape.

**Comment by MitchTheUser** [comment]
As always, the image has been updated with additions.

> It does match the older pies but the newer ones have no tin, are browner and a different shape. At some point I expect all the pies would be resprited,

I agree that the pie inhand didn't represent how a lot of pies in the game looked, so I went ahead and added about 17 unique inhands for every type of pie in the game.

> There was also feedback that the pumpkins would be weird held underarm after clothing layering.

I did some testing and the inhands looks mostly fine. It did overlay a few pixels on backpacks, but that seems to be a problem with other inhands, and its not that noticeable.

**Review by ZeWaka — APPROVED** [review]

**Comment by flappybatpal** [comment]
Tested every pie.

**Pull request merged**
