### PR TITLE
Refactor, resprite, and revise of book.dm stuff

### PR DESCRIPTION
**Pull request by nefarious6th**
[wiki][cleanliness][sprites][mapping]
## About the PR
bookssample1
dummiesguidetomatsci

**REFACTOR:**
- Books moved and stored as .txt strings under strings/books (35 files)
- Organizes book.dm into sections based off book types; notes which books still require reviews for later PRs
- Replaces all instances of books with new object paths (75 files)

**RESPRITE:**
- Interdictor unique blueprint sprite
- Interdictor Guide unique cover sprite
- MatSci guide unique cover sprite

**REVISE:**
- Re-wrote Dummies' Guide to MatSci
- Made Geothermal Capture System book more readable for future editing (some work could still be done)
- Reviews and updates on all other books not noted as still needing revision in comments of book.dm
- Added links to wiki pages at foot of relevant guides
- Fixes unicode character appearances in-game

## Why's this needed? 
**REFACTOR:**
The original book.dm when I went to move the Interdictor Guide to it:
yoinks
Makes adding and editing books easier to do.

**RESPRITE:**
- Interdictor blueprints use artifact analysis forms which I think is Bad for an important mechanic
- MatSci books should be identifiable

**REVISE:**
Books (especially the pocket guides) can be good sources of information for players in-game; they augment resources on the wiki or are directly presented on the wiki as guides for certain features. Keeping this stuff updated in-game benefits updating the wiki, and vice versa. 
Hopefully the updates and revisions make the books more useful for players; and make it easier to maintain these as relevant sources of information going forward.

Other notes:
Add to wiki label to update the MatSci pages and sprites; add interdictor blueprint sprite; update content of other books.

FROM WHAT I CAN TELL, this would require two book updates in secret content of Urs Dungeon (one instance of `obj/item/paper/book/dwainedummies` to `obj/item/paper/book/from_file/dwainedummies` ; another instance of `obj/item/paper/book/medical_guide` to `obj/item/paper/book/from_file/pharamcopia`). Potentially other secret areas too?

### CODE REVIEW

**Comment by Eagletanker** [comment]
Wait, isn’t the Urs dungeon in the editor? I’ve opened it up in SDMM before.

**Comment by nefarious6th** [comment]
> Wait, isn’t the Urs dungeon in the editor? I’ve opened it up in SDMM before.

From what I understand, that's an older version and the most recent is in the secret repo.

**Comment by nefarious6th** [comment]
this is up to date on all the current merged and open non-draft engineering prs that have been added; i burnt out on the grifening stuff for this week but will come back around to finishing it when i inevitably go through the actual playing cards file to fix a bunch of grammar/syntax errors in there.

aware of kubius's interest in doing something else with the blueprints for the interdictor. would prefer to layer that under things in the crate in another pr; if that's not favorable i can resprite on this one.

**Review by flrsh — APPROVED** [review]
From what I can tell everything looks good.

**Pull request merged**
