### PR TITLE
Altered Horizon's Pharmacy

### PR DESCRIPTION
**Pull request by CrystalClover**
## About the PR 
Altered Horizon's Pharmacy by adding a second chem station and a much needed glass recycler, while also rearranging the layout a bit.

newhorizonpharmacy

## Why's this needed? 
A glass recycler was sorely needed and having 2 chem dispensers is nice

## Changelog

```changelog
(u)C.Clover
(+)Added Glass Recycler to Horizon Pharmacy
```

### CODE REVIEW

**Review by flrsh — CHANGES_REQUESTED** [review]
I don't think they need a second chem station. The glass recycler is good though.

**Comment by CrystalClover** [comment]
After re-arranging and removing second dispenser: 
Capture

**Comment by flrsh** [comment]
!merge_upstream

**Review by flrsh — APPROVED** [review]
Looks good to me. In the future, make sure to pull before you start working on anything, to ensure that you have the latest copy of the map. Before I merged the upstream branch, your PR was [accidentally removing](https://camo.githubusercontent.com/4abd7fa06821f95f39a7b0b64e57058d7409e56695df3ad32e0b7b9836825b7c/68747470733a2f2f6d6462322e616666656374656461726330372e636f2e756b2f696d616765732f3235323034373438332f363731363633323634352f6d2f302f302d646966662e706e67) the recently added status displays because your working copy was outdated.

**Pull request closed without merging**
