### PR TITLE
gives hop a taser, adds manta jacket to all maps with alternate styles, and gives hop alt suit job rewards

### PR DESCRIPTION
**Pull request by Crackaduck**
[FEATURE]
## About the PR 
adds the manta jacket to hop's spawn items on all maps, gives the manta jacket an alternate style where you wear it open and on your shoulders, gives the manta jacket an alternate grey appearence when using alternate jumpsuit feature.
Gives the hop a taser with 200pu power cell, that can only be fired in single shots, appearing in their locker.
gives the hop claimable grey suits and dresses for level 0.
image
image
image
image
image
image
image

## Why's this needed? 
it gives the hop more fashion options
it gives the hop a energy-pistol to defend themselves with, and disincentives buying security equipment as hop because you will already have equipment to defend yourself with, hops can will obtain weaponry if they want, better weaponry than the stun pistol on offer, that along with being better weaponry overall will also include a stun baton with their weapon of choice as that is included with ANY security weapon purchases.

## Changelog

```changelog
(u)Carsontheking
(*)Gives the HOP a 200pu single shot taser
(+)Gives the HOP new clothing options you can claim using "check-job-rewards"
The HOP's manta jacket has been added to their invintory on all maps, and now has a new grey alternative when using the alternate jumpsuit feature
```

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
HoP doesn't need a taser, they're not security. 👎

**Comment by scrcr0** [comment]
Taser is anything but weak.

**Comment by mopcat** [comment]
hop is the paperwork guy, the most intense thing they should be doing is deciding whether the clown gets all access or not. they don't need a gun, especially a gun as strong as a taser with 200pu. if someone's causing trouble then they can call security or use the flashes they start with, and hops powergaming by buying security equipment is a problem best solved with a different solution than "have them start with a gun"

**Comment by Azrun** [comment]
Process wise, this seems like it should be two different PRs. This way the discussion between the two rather different parts of the PR don't stop/impede it.

**Comment by nefarious6th** [comment]
Agree with Azrun; I like the alt suit and I think the cape could be cool, if maybe needs a little discussion, but I am in general a fan of fleshing out cosmetic things for some of the other Heads that people pay less attention to and I think this would match that one silly tricorne hat really nicely.
I feel a little weird about the Manta coat on all maps, but I felt the same way about the HoS cape becoming not-Manta exclusive too.
If you split stuff into multiple PRs but keep this one, double-check your icons; your branch looks like it might be outdated and deleted some of the more recent gun and monkey PRs that were merged! 

(TIL There's an alt color scheme for the ticketwriter?)

**Comment by Tarmunora** [comment]
Atomize your prs

**Comment by Flaborized** [comment]
I said this early on when you were making this, but I don't like either addition. Both of them feel like they're turning the HoP into a more militarized 'cool guy' role, which I think is far less interested and far less unique than the direction we could be taking the job. The alt jacket very very much so looks like the HoS cape, and I don't think it (or the grey color scheme) fits the job well at all. Just because something Looks Cool and because people Like It on another job doesn't make it a good addition, and not every job is supposed to look the same kind of cool. IMO there's stronger directions to take the HoP fashion-wise.

The gun to me is similar. doesn't fit the role it's being given to. Just because an HoP player might *want* a unique gun, doesn't mean they should get one. Otherwise looking at implementation, there's several existing sprite changes reverted in this PR which is... bad.

Also your PR doesn't mention this but it seems to make the HoP spawn with Manta loadout by default, on all maps. I'm not a fan of this either as I think it's pretty dramatically making the 'military cool guy' aesthetic the default.

**Comment by Crackaduck** [comment]
truth be told the gun was more a item that would be added in addition to a portable id computer, but I'm not really good enough at code to make that. The idea was to add in a portable id computer, then the idea for a small taser came, because "if the hop is going to be going around the station, changing id's people could steal their id even easier than before, so lets give them a weapon to stop people from stealing their id, it shouldn't be melee, as someone with the hops id could take the card and close a door, preventing the melee weapon or flash from being used, thus it should be a ranged weapon, not something as powerful as a security taser, but comparable as so its not completely worthless" and that's how the taser came to be. FUN FACT: it was originally going to have two modes, stun and disarm, however I don't know how one would code a disarm mode so it only has stun.

**Comment by ThatFiveGuys** [comment]
Im fine with the HoP being an easy theft target. That's how they are now. They're the loot target for getting AA without dealing with the armor and gun of captain. The battery it uses is the same as the battery the taser uses, alongside the projectile. This would effectively give the HoP a taser, which is strong as hell.

**Pull request closed without merging**
