### PR TITLE
Using a wire cutter on an assembly prevents its inhand interaction

### PR DESCRIPTION
**Pull request by Valtsu0**
[FEATURE][GAME OBJECTS]
## About the PR 
Using a wirecutters on timer, proximity or radio/igniter and radio/horn assemblies prevents its inhand interaction. Changes its examine text to reflect that.  Using a wirecutters again allows you to interact with it again. Trying to use it tells you so.

## Why's this needed? 
Currently, there is little to no point in surgically implanting remote activated bombs into people, since they can just fart and turn them off. Preventing people from turning off the detonator would allow more antag gimmicks

## Changelog 

```changelog
(u)Valtsu0
(+)Using wirecutters on relevant assemblies prevents their inhand interaction.
```

### CODE REVIEW

**Comment by Valtsu0** [comment]
Will return to this later

**Comment by Valtsu0** [comment]
Later is now

**Comment by Valtsu0** [comment]
Idk if i should make a new pr. Well this being near the end of the list is probably fine

**Review by ZeWaka — COMMENTED** [review]
as much as i hate this duplicate code, it doesn't make sense to bring it up to obj/item/assembly i don't think

**Pull request closed without merging**
