### PR TITLE
Cloning console patch 1

### PR DESCRIPTION
**Pull request by ThePotato97**
## About the PR 

Updates some wording on the paper.
Only someone with a head ID can delete records.
Fixes css property names and order.
HealthStat now uses children instead of content.
Title Cased the console name.

## Why's this needed? 
Fixes implant showing nothing, prettiness, consistency with other scanners.

## Changelog

```
(u)ThePotato97:
(+)Only head IDs can delete cloner records now.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Need a changelog for head id

**Review by ZeWaka — APPROVED** [review]

**Comment by zjdtmkhzt** [comment]
Not sure if I agree with only heads being able to delete cloning records. 
I feel like Doctors should have that option, seeing as they are the ones usually operating the cloner?
It's not that big a deal, seeing as cloners are easy to sabotage, but idk.

**Comment by ThePotato97** [comment]
> 
> 
> Not sure if I agree with only heads being able to delete cloning records.
> I feel like Doctors should have that option, seeing as they are the ones usually operating the cloner?
> It's not that big a deal, seeing as cloners are easy to sabotage, but idk.

Just doing what the paper says

**Comment by ThePotato97** [comment]
I need to do some changes to the UI

**Comment by ThePotato97** [comment]
image

**Comment by ZeWaka** [comment]
> image
> 
> Is this better/worse?

worse, it looks like a mobile app

**Comment by ThePotato97** [comment]
> 
> 
> > Is this better/worse?
> 
> worse, it looks like a mobile app, I no longer want to merge this

That's why i asked for DNM

**Comment by ThePotato97** [comment]
image
image
image

**Review by ZeWaka — CHANGES_REQUESTED** [review]
IconStack documentation for the component reference missing (was on upstream)

**Review by ZeWaka — CHANGES_REQUESTED** [review]
super minor but: icon is before icon.stack in the table of contents, but it's actually above

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
