### PR TITLE
Lovely emotes!

### PR DESCRIPTION
**Pull request by DimWhat**
[Feature] [Sprite]
## About the PR 
Adds the love, care, and heart emotes which are locked behind having pure love in your system. Also adds a single sprite for when the emote is used. The idea was by the wonderful Jan.antilles.

## Why's this needed? 
It's a pretty cute thing and makes the pure love chemical a little more special.

## Changelog
```
(u)DimWhat:
(+)Adds the care, love, and heart emotes. Though you need to be full of love so you can share it with your crewmates. <3
```

### CODE REVIEW

**Comment by BenLubar** [comment]
Was speech_rel intentionally removed from the spritesheet?

**Review by flrsh — CHANGES_REQUESTED** [review]
To me, the messages come off as kinda awkward and unwelcome. I don't think I'd want an emote that said `you display your affection towards [person]`, or `you care about [person]`, or `you make a tiny heart shape in [person]'s direction`. They feel forced and kinda stilted. Generally, I think you want to show, not tell, and generally I think it's fine to have to custom emote to do this sort of stuff.

**Comment by DimWhat** [comment]
> To me, the messages come off as kinda awkward and unwelcome. I don't think I'd want an emote that said `you display your affection towards [person]`, or `you care about [person]`, or `you make a tiny heart shape in [person]'s direction`. They feel forced and kinda stilted. Generally, I think you want to show, not tell, and generally I think it's fine to have to custom emote to do this sort of stuff.

I see your point flourish. I primarily created this PR as of jan's request and not of whether or not it would fit in the game. That was a problem on my part and not anyone elses. I personally did not think this PR would go through but I do think making this PR was a good learning experience on how emote code works and what could be done with it. I did not mean to make it seem as weird as I made it. I'm sorry. Have a wonderful day.

**Comment by flrsh** [comment]
You have nothing to apologize for. Just because I think the emotes are weird doesn't mean every single person thinks they are. There's no problem with making a PR and having people say that they don't like it. Glad coding this was a learning experience!

**Pull request closed without merging**
