### PR TITLE
Adds firefighter helmet to a bunch of places and tweaks firefighter helmet and suit stats

### PR DESCRIPTION
**Pull request by DimWhat**
[Mapping] [Balance]
## About the PR 
Will completely replace the hard hat that is generally on the same rack as a fire suit on most maps with a firefighter helmet. Adds them to the fire fighter crate since they totally should come with the suits and adds a 50% chance to the fire closet to contain a fire fighter helmet as well as adding them to spots that lacked hard hats in donut 3 and Oshan.

Also tweaks the stats of the fire helmet to be more heat resistant than before and **lowers** the fire fighter suits fire resistance by 5% to compensate for the hat.

New stats:
- Melee: -3
- Heat: 15%
- Cold: 5%
- Ear Disorient: 8%
- Eye Disorient: 8%

## Why's this needed? 
We have fire fighter helmets and they currently are only used in manta. I think all maps should have them since they fit better than hard hats. Also the firefighter helmets do not currently have any differences than a normal helmet other than the sprite, so I felt the need to make it have it's own stats.

## Changelog

```changelog
(u)DimWhat
(*)The hard hats that came with firesuits on station have been replaced with firefighter helmets
(+)Altered the stats of the firefighter helmet and suit.
(+)Added firefighter helmets to fire lockers and crates
```

### CODE REVIEW

**Comment by DimWhat** [comment]
my title is WAY too long, what was I even thinking!

**Comment by DimWhat** [comment]
WOOPS

**Comment by Azrun** [comment]
Default helmet puts you at 10 hot and 10 cold, reduction of cold seems odd. Hats gives 10 cold, 5 hot.

Base:10
Shoes: 7 (5 for Orange... poor engineers)
Gloves: 3
Jumpsuit: 5
Face: 7 (Gas), 5 (Breath)
Body: 50 (Firesuit) vs 65 (Heavy Firesuit)

Yeah this allows folks to get heat resistance at round start by putting internals, firesuit and fire-helm. (Engineers need to upgrade to non-orange shoes OR put on gas mask). 👍

**Comment by mordent-goonstation** [comment]
> Default helmet puts you at 10 hot and 10 cold, reduction of cold seems odd. Hats gives 10 cold, 5 hot.
> 
> Base:10
> Shoes: 7 (5 for Orange... poor engineers)
> Gloves: 3
> Jumpsuit: 5
> Face: 7 (Gas), 5 (Breath)
> Body: 50 (Firesuit) vs 65 (Heavy Firesuit)
> 
> Yeah this allows folks to get heat resistance at round start by putting internals, firesuit and fire-helm. (Engineers need to upgrade to non-orange shoes OR put on gas mask). 👍

Complete fire immunity without the heavy firesuit seems a bit odd to me.

**Review by flrsh — COMMENTED** [review]
Imo the firefighter helmets should be available only through QM.

**Comment by DimWhat** [comment]
> 
> Complete fire immunity without the heavy firesuit seems a bit odd to me.
Addressed. The helmet now has 15% fire resistance.

**Review by flrsh — APPROVED** [review]

**Review by pali6 — APPROVED** [review]

**Pull request merged**
