### PR TITLE
engivac spelling error fix

### PR DESCRIPTION
**Pull request by deathrobotpunch**
## About the PR 
fixed the material vacuum name that used to be materiel

## Why's this needed? 
spelling error bad

### CODE REVIEW

**Comment by Wisemonster** [comment]
This probably doesn't need a changelog

**Comment by deathrobotpunch** [comment]
ok

**Comment by deathrobotpunch** [comment]
changelog removed

**Review by frawhst — APPROVED** [review]

**Comment by blackrep** [comment]
I assumed it was intentional. Materiel is a real word.
https://www.merriam-webster.com/dictionary/mat%C3%A9riel

**Comment by deathrobotpunch** [comment]
> I assumed it was intentional. Materiel is a real word. https://www.merriam-webster.com/dictionary/mat%C3%A9riel
> 
> > equipment, apparatus, and supplies used by an organization or institution

it’s a word but not used in the right context, materiel is mainly used for military resources. and anyway the description of the engivac has the word material in it anyways

**Comment by deathrobotpunch** [comment]
how has this not been merged yet?

**Pull request merged**
