### PR TITLE
Add PTL to Nadir

### PR DESCRIPTION
**Pull request by MarkNais**
## About the PR 
Adds a PTL to Nadir, replacing the SE random-spawn room. It is connected to the turbine and southern catalytic engines.
The high-voltage was stylistically laid with large radius bends. The turbine-wire travels through the false walls of SE maint as a shortcut. Notably false-walls must be deconstructed in order to manipulate wires underneath.

**Side-effect**: The southern catalytic engine grid is connected to the turbine grid; either engine can charge the other's intended SMES units; muddies the clarity of the `power monitor` computer's `Engine Output` graph (it is a sum of all engines). The connection can be easily undone (revert a commit).

I also intentionally engine-electrified this wingrille. 
image

Changes have been tested:
- Connections confirmed to both engine types,
- PTL profit generated, and
- All APCs charging.

The windows have become properly transparent since taking the screenshot below.
I used the stronger windows (like those found near Escape) as it's an "important" station area.
image

## Why's this needed? 
💲🤑💸💰💵💴💶💷💱💹💳
Incentivizes aggressive nuclear-engine & catalytic-engine use. Side effects may include:
- Increased cooperation with Siphon personnel.
- Increased usage of the catalytic engines.
- Increased traitor activity w/ reactor.
- Increased traitor activity w/ hot-wiring.
- An decrease in "Days since last meltdown". image

## Changelog 

```changelog
(u)MarkNstein
(*)Nadir: Added a PTL located at the South East hull connected to the turbine and southern catalytic engines.
```

### CODE REVIEW

**Review by Kubius — APPROVED** [review]
Seems reasonable on the whole. I'd say probably skip connecting up the catalytic substations, as they're the map's equivalent to solars, but I don't have an explicit objection to laying a cable for engineers to hook them up with.

**Comment by Cherman0** [comment]
I'd agree that the cat stations shouldnt be connected to it. Aside from being inconsistent with how passive generators are normally wired, having them on separate grids is helpful because it means that one hotwired grid doesnt compromise multiple generators. Otherwise they sort of lose their utility as a backup.

**Review by TheTyrant25 — APPROVED** [review]
looks fantastic!

It's been stale for a while though, so I have to ask; is there a good reason why it hasn't been merged yet that I don't know about? Or was it just forgotten a little (totally understandable)

P.S. typical colour schema for the cable line leading off the reactor network is to use a blue cable to indicate "this bit goes to the ptl". Totally optional of course, but i'm partial to it personally. Maybe worth considering?

**Comment by TheTyrant25** [comment]
Will this be merged?

**Review by Glamurio — APPROVED** [review]

**Pull request merged**
