### PR TITLE
Prevent shuttle hotbox on RP

### PR DESCRIPTION
**Pull request by flappybatpal**
[BALANCE]

## About the PR 
Prevents plants igniting on the shuttle if the server is on roleplay mode.

## Why's this needed? 
It feels like 1/4 of admin helps from RP are about shuttle hotboxing.

## Changelog

```changelog
(u)Flappybat
(*)RP shuttles have been fitted with the newly developed hotbox shields to reduce complaints.
```

### CODE REVIEW

**Comment by pali6** [comment]
Implement in `/obj/item/plant/herb/combust_ended` instead please.

**Comment by colossusqw** [comment]
Does this still allow for post centcom hotboxing? Asking for a friend...

**Comment by flappybatpal** [comment]
> Does this still allow for post centcom hotboxing? Asking for a friend...

Yes because it's working off the specific shuttle status and location. Centcom isn't covered.

**Comment by frawhst** [comment]
Would personally rather just do this for both servers, feels like a weird thing to put behind an ifdef. Open to other dev opinions though.

**Comment by ZWRh3** [comment]
> Would personally rather just do this for both servers, feels like a weird thing to put behind an ifdef. Open to other dev opinions though.

antags using deathweed on shuttle shouldnt be prevented, nonantags hotboxing lsd in a public like shuttle is an issue tho albeit not a code one.

**Comment by Azrun** [comment]
I like the idea of this or similar being the present on both server tires, but for there to be means for antagonists to circumvent it.

**Pull request merged**
