### PR TITLE
Lottery rounds will no longer wish you luck

### PR DESCRIPTION
**Pull request by DisturbHerb**
[EVENTS][REMOVAL]

## About the PR 
Lottery Round 1. They no longer wish us the best of luck. There is no more faceless entity wishing us luck for the upcoming prize draw.

## Why's this needed? 
who is wishing me the best of luck. WHO ARE YOU. WHO IS ORGANISING THE LOTTERY, I WANT TO ASK THEM WHY I KEEP LOSING

### CODE REVIEW

**Comment by RSG250** [comment]
but why? i can imagine an lottery ticket machine with a screen saying good luck to ya after a purchase.

**Comment by DisturbHerb** [comment]
> but why? i can imagine an lottery ticket machine with a screen saying good luck to ya after a purchase.

the lottery machine isn't the one telling you good luck, it's a station announcement

**Comment by UrsulaMejor** [comment]
why tho

**Comment by RSG250** [comment]
> > but why? i can imagine an lottery ticket machine with a screen saying good luck to ya after a purchase.
> 
> the lottery machine isn't the one telling you good luck, it's a station announcement

automated announcments can wish people luck though???

**Comment by DisturbHerb** [comment]
> > > but why? i can imagine an lottery ticket machine with a screen saying good luck to ya after a purchase.
> > 
> > 
> > the lottery machine isn't the one telling you good luck, it's a station announcement
> 
> automated announcments can wish people luck though???

do automated announcements use first person pronouns?????

**Comment by ZWRh3** [comment]
> do automated announcements use first person pronouns?????

if advertisements count yes

**Comment by Sord213** [comment]
If this is a joke PR it fell flat on its face. Otherwise, 😕

**Pull request closed without merging**
