### PR TITLE
Contained corpses no longer make miasma

### LINKED ISSUE #477: Miasma smoke is generated from a corpse in a body bag.
[BUG]

**Describe the bug**
Miasma smoke is generated from a corpse in a body bag.
**To Reproduce**
1. Kill someone.
2. Place corpse in body bag.
3. Wait until it starts to rot and produce miasma.
4. See that miasma is spreads.
**Expected behavior**
I'd assume that the body bag would either delay a body from rotting so that it wouldn't spread miasma, or at least contain the miasma until it's opened.

**Additional context**

### PR DESCRIPTION
**Pull request by Tarmunora**
[FIX]?
## About the PR 
Corpses in body bags and welded lockers/etc will no longer produce miasma, other decomposition is unaffected

## Why's this needed? 
Allows people to hide corpses in lockers again, closes #477 

## Changelog

```
(u)Tarmunora:
(+)Corpses in body bags and welded lockers/etc will no longer produce miasma
```

### CODE REVIEW

**Comment by Flaborized** [comment]
As far as I know miasma is *supposed* to leak out of lockers, disposal chutes ect. That was the reasoning behind adding it IIRC, to make hiding corpses a little bit harder in the long term.

**Comment by pali6** [comment]
What if smoke / miasma generated inside objects stayed inside until opened or until there's enough that it starts to leak out.

**Comment by Gerhazo** [comment]
To add to the thoughts being posted, someone also mentioned somewhere welding a locker shut causing it not to leak, which I thought was kind of interesting.

**Comment by Sovexe** [comment]
existing discussion for reference
https://forum.ss13.co/showthread.php?tid=14532

**Comment by mybluecorners** [comment]
I like pali and gerhazo's suggestions - weld the locker to completely lock in the smoke, and smoke reagents building up inside a locker and leaking out sounds cool

**Comment by Tarmunora** [comment]
Changed to only block from welded storages and body bags. Containing smoke inside things until opened is uh, outside the scope of this 😰

**Pull request merged**
