### PR TITLE
passive bioeffects rebalance

### PR DESCRIPTION
**Pull request by Tarmunora**
[BALANCE]
## About the PR 
i'm so sorry, wikipeople 

- [x] Enable `power` on all bioeffects
- [x] Remove `variant` from bioeffects and replace with `power` where needed
- [x] Rebalance beneficial passives to need power booster chromosome for full effect

Maybes:
~~Rebalance negatives with powerbooster?~~
~~Useless/utility?~~
- [x] Rebalance/~~remove~~ some bioeffects outright (thermal res stands out)
- [x] Rebalance genetic stability
- [x] 2nd balance pass on empowered effects

Specific effects for unempowered bioeffects:
- [x] Fireres: remove total BURN damage immunity - empowered give 50% resistance to all burn damage
- [x] Coldres: no change - empowered prevents slipping on ice??
- [x] thermalres: provides 50% heat/cold prot - empowered provides base benefits of fireres and coldres? [make fireres, coldres, thermalres mutually exclusive]
- [x] Elecres: remove baton immunity from both - empowered gives 40% body disorient resist
- [x] rad resist: 75% radprot
- [x] alcres: no change - empowered entirely negates aim penalty when shooting drunk 
- [x] toxres: 66% damage reduction instead of 100%
- [x] breathless: REBREATHING prop - BREATHLESS when empowered
- [x] psychic_resist: no change, empowered protects against psyblasts
- [x] regenerator: ~~Halved effect~~ 2/3 effect - 4/3 when empowered, empowered also gains double limb regrow odds
- [x] detox: ~~Halved effect~~ 2/3 effect - 4/3 when empowered
- [x] examine stopper: Only blocks examines from >~~3~~1 tile
- [x] dead scan: no change, empowered adds "dead" desc to examine text
- [x] noir: no change - empowered makes vision grayscale
- [x] strong: no change - empowered gives 50 health-deficiency-adjustment
- [x] radio brain: only give general comms (145.9)
- [x] hulk: no change. Empowered does not decay from damage.
- [x] Nightvision: smaller overlay
- [x] X-ray: No SEE_MOBS or see_invisible
- [x] Toxic Farts: no change, empowered adds toxin to fart
- [x] physically fit: ~~Halved effect~~ 2/3 effect - 4/3 when empowered
- [x] Blood overdrive: ~~Halved effect~~ 2/3 effect - 4/3 when empowered

Genetic stability
- [x] Remove Robust Genes trait, add +25 base stability
- [x] Once-over of beneficial gene costs
- [x] Ditto for negative
- [x] Ditto for powers
- [x] Ditto for speech/misc
- [x] ~~Once-over for stability thresholds~~ adjust power failrates
- [x] Actually do something about stability thresholds

```diff
+toxres 40 -> 30
+anerobic 40 -> 30
+regen 40 -> 25
+detox 15 -> 10
+noir 5 -> 0
+strong 0 -> 5
+xray 30 -> 20
+nightvision 25 -> 15
+fitness 5 -> -5
+blood overdrive 15 -> 5

+clumsy -5 -> -10
+narcolepsy -5 -> -15
+tourettes -5 -> -10
+funky limbs -20 -> -25
+mutagenic field 50 -> 35
+spatial destabilization 15 -> 10
+unfit -5 -> -10
-tinnitus -5 -> 0
+anemia -5 -> -10
+polycythemia -5 -> -10

+hemochromia-U 5 -> 0
-cat 25 -> 50
+ethanol production 0 -> -5
-chemical production 0 -> 15
-unstable chemical production 0 -> 25
+chronal additive inversement 10 -> 0
+temporal displacement 10 -> 0

-jumpy 5 -> 10
+telepathy 5 -> 0
-adrenaline rush 5 -> 15
+dimshift 20 -> 15
+photokinesis 5 -> 0
-erebokinesis 5 -> 15
+tk pull 15 -> 10
+darkcloak 20 -> 15
+chameleon 20 -> 15
```

## Why's this needed? 
Currently, passive bioeffects tend to be pretty strong on the upper end, and the concept of balance through genetic stability breaks down when they can all be spliced with the stabilizer chromosome with no penalty to efficacy.

## Changelog

```changelog
(u)Tarmunora
(*)Rebalances 'beneficial' bioeffects to accept the Power Booster chromosome. See PR for details. There are a lot of details.
(+)Rebalances genetic stability costs of many bioeffects (mostly buffs). See PR for details. Again,
(+)Removes robust genes trait, increases base genetic stability
(+)Change formula for genetic power failrates at lower stability
```

### CODE REVIEW

**Comment by Crackaduck** [comment]
some of these I agree with, specifically the immunity genes, essentially removing all fire/burn/radiation/depressurization damage without any downside is too strong. But others changes them WAY too underpowered compared to their cost, where the benefit is either completely minimal with a stabilizer trait, or not worth the price with empowered, especially when most people wont have robust genetics, like blood overdrive or physically fit, which are already fairly weak traits comparatively to others. I could see a slight nerf to them, like 30 to 20 for physically fit, but the effect being cut in HALF is brutal. Not to mention genetics is already fairly balanced, taking a extreme time investment to get the genes you want with the traits you want, along with all the traits being removeable with a mutadone dart from the MD, (unless they take a hit to their stability and use a Reinforcer) who has the weapon for these exact reasons. TLDR: I think the extremely cheap, easy, and frankly OP traits like fire res and cold res could use a nerf, but others like meta neural antenna are fine as is.

**Comment by ThatFiveGuys** [comment]
Meta Neural brain seems semi harsh, the downside of that for me was having your sidebar spammed up with every radio comm. Maybe have empowered meta neural be old behavior? Removing wallpunch for hulk would be good (See non antag geneticist getting hulk and breaking down all the walls to security in 30 seconds) however I feel like itd need something else. there's Sov thing of being able to pick anything up would be neat however that may be a taddd bit broken to be used.

**Comment by cluwneunora** [comment]
gaming

**Comment by Crackaduck** [comment]
specific trait disagreements aside, I dislike this change massively, because it feels like it doesnt account for stability anywhere near as much as it should. going under 100% will seriously mess you up, specific genes have a chance of just straight up kill you by chance if your under 100% stability. Stability is already a VERY tight market for geneticists to work with, and nerfing every passive to either pitiful levels, or making them have a stability hit, feels extremely harsh. maybe if people were given more stability to work around with, it would be fine, or the threshold for genes misfiring was increased so people could be safe at lower stability levels, but even in genetics current state, many people will never go bellow 100% stability, there are few negative genes in the game which give enough stability to be considered "worth the trade", and this entire thing feels like it will destroy the stability economy to be honest.

**Comment by ChairSurfer** [comment]
wait since when did they actually ask the community for feedback? i thought tarm was trying to speedrun most unpopular nerfs any%, lets make lotus contain luminol, yeah, the crew will really find that useful, making a useless chem readily available does not make it any less useless, making them a UV light does not make them any more useful considering UV lamp is scannable lol, and why does porta remote take telecrystal now? can be bought at martian, its more of an annoying inconvenience than a real nerf

PS i woulda called out these nerfs alot sooner, but we all know how you lot take criticism, yall are so predictable on how you react to criticism that i darent even use my real username, cuz i dont wanna get banned for saying what everyone is thinking

**Comment by UrsulaMejor** [comment]
I think one point of balance to consider re: time to reward ratio is that the existence of the gene booth massively amplifies the reward for finding any given gene.

**Comment by Xkeeper0** [comment]
I strongly disagree with most of these changes, which are apparently designed to make the base power *actually useless* unless you splice it with power booster. Genetic stability is a bad mechanic anyway because going below 50 makes you basically unintelligible, causes all of your abilities to fail often, and so on. That's without considering how people can get fucked up stability numbers (I've seen people with 0 active mutations who have a stability below 50, causing them to gibber most of their speech as it is)

The various major resistances are also supposed to be harder to get by nature of being more rare in gene pools and requiring more difficulty to unlock.

I'm not sure what's being balanced here. All this is doing is making it so that nobody is going to want or have these passives any more because they'll either be worthless, easily replaceable, or cause a hit to stability. _And hits to stability are catastrophic._

> I think one point of balance to consider re: time to reward ratio is that the existence of the gene booth massively amplifies the reward for finding any given gene.

Not *reward*. They increase the *impact*. A geneticist will likely get nothing from most gene booth uses -- the vast majority of the time, genes are set to either free or cheap. When you're at the point of giving away things like X-Ray Vision or Regeneration (which, in my experience, is _very, very rare_) you already have a surplus of materials beyond anything you can use from having maxed out the research tree _and_ money isn't useful because nobody has any and there's generally no use for it even if you did.

But the gene booth specifically increases the reach of genetics and gives them a reason to provide these genes to the crew. They might not see any immediate benefit for it, but now the crew has a reason to at least stop by Medbay to pick up things that will let them survive when the station invariably goes to hell.


If you want to take care of gene nerds, mutadone goes in hyposprays and features an instant, unblockable injection. Or you can use the mutadone darts. Or you can force-feed them vanilla and see if the RNG will instantly remove all of their active mutations.

Again, this is the kind of pointless change that nobody is asking for. Nobody likes gene nerds, but this is just literally making everything worse / less useful or _zero benefit to anyone_.

**Comment by Vaskritaya** [comment]
I like the idea of giving unusually strong genes a nerf and a power booster effect, making the tradeoff between power and safety. Things like thermal, o2, etc. That makes sense, and I understand the motivation of this change.

That being said, I feel like a lot of these changes are nerfs for the sake of nerfs as a brainless way to give everything a power booster effect without needing to consider the balance. The end result of a lot of this, I think, will be that less-valued genes will appear in the gene booth even less (because why waste the booster chromosomes, when you need them for more important things?), and that this PR would cause booths to even more frequently just be the core resistances and no other more niche effects, because +1 stamina regen and +15 max stamina just isnt that interesting or useful. 

It is also worth mentioning that unstabilized genes are already largely frowned upon by Medical staff, at least on RP, which further limits the odds of Empowered genes showing up. 

Overall I'm highly skeptical of a lot of these changes and agree with Zamujasa on most of what they said, although I am a bit more receptive to changes to things like thermal, toxic resistance, anaerobic, etc.

**Comment by Ley-bunned** [comment]
There's basically no reason to empower most genes right now and the immunity genes let people ignore quite a lot of gameplay for minimal effort. Remember, the prime beneficiary of stabilized 02, thermal and antitox is not going to be a geneticist but a crew member showing up at the gene booth and reaping the benefits. For them there's no price involved, just a tiny amount of time and credits, and they end up very very hard to kill outside of raw brute damage and explosions.

**Comment by alexeric123** [comment]
> I think one point of balance to consider re: time to reward ratio is that the existence of the gene booth massively amplifies the reward for finding any given gene.
Honestly, if that's how nerfs are done, I'd rather the gene booth be removed, as that will give genetics more interaction, while not making genetics useless like this will.
Other people have mentioned this, but any stability hit makes the rest of the round unfun.

**Comment by Vaskritaya** [comment]
At the time of writing my last comment, many of the prescribed changes of the draft were dead-simple nerfs which halved effectiveness, with no indication they could be made stronger than they are now, and stability adjustments a mere "maybe", with failure rates totally unmentioned. I think the current form of the PR is a lot more palatable, but I do think that it will be critically important to closely monitor the effects of this PR if implemented, so that all the inevitable miscalculations can be ironed out. 

Additionally, if stability is going to now be a thing that comes into play more frequently, it might be worth investigating how poor stability works at a fundamental level and adjusting it to be more engaging and interesting, rather than just having it inconvenience you in an unfun way with gurgling and things like that. Obviously, that's something for a different PR, but I feel it's worth bringing up.

**Comment by Tarmunora** [comment]
One notable issue with stability is that if you have no powers, you can completely ignore it down to 50 stability, and down to 40 if you don't care about speech

**Pull request merged**
