### PR TITLE
Updates portable air pump, tank dispenser, portable seed fabricator visuals

### PR DESCRIPTION
**Pull request by BatElite**
[feat]
## About the PR 
This PR adds new and good sprites for the things mentioned in the title. Air pumps now have directional sprites so it looks like you're pulling them around by the handle, and they sway when on because not every side is animated. Tank dispensers now show whether or not they're empty of either type of tank they can hold. The seed fabricator looks not shit.

Also I poked atmos cans because they defined a couple of images globally, and I was told that one shouldn't when I tried that myself. (It's a little bit of a kitchen sink PR, sorry.) I didn't think changing that would be worth its own PR.

pumpstuff_preview

## Why's this needed? 
Sprites are good and so is things looking nice.

## Changelog

```
(u)BatElite:
(+)Updated portable air pumps, tank dispensers and the portable seed fabricator!
```

### CODE REVIEW

**Comment by pali6** [comment]
I love the air pump and the tank dispenser but the seed fabricator just looks a bit too weird and un-seed-fabricator-like to me. But I don't know what design would be good for it. Hopefully other people will chime in with their feedback.

**Comment by BatElite** [comment]
I can't really help in the sense that I made it and I think it's great, but I can sorta explain my thought process: The idea was to have something that you could just stick into the dirt (like a dibber) and it spits out the seed in there. Since the bit that makes seeds would be inexplicable anyway I just made it aesthetically pleasing.

**Review by flrsh — CHANGES_REQUESTED** [review]
The air pump's south facing sprite looks flat to me, maybe because the brighter color is used for highlights on all the other directions, but is a large rectangle here? I'd suggest making it thinner. The same goes for the left rectangle of the tank dispenser sprite. You could probably remove it altogether, because it doesn't make that much sense why there'd be two compartments anyways (at least to me), and just make the right rectangle larger and give it a more obvious "vending" interface? 

> The idea was to have something that you could just stick into the dirt (like a dibber) and it spits out the seed in there.

To me this makes a lot of sense, though I agree that this sort of style isn't what we usually see around the station. Still, it's very aesthetically pleasing, so I like it a lot, maybe someone could also add some cool flavor code in another PR so botanists can also use it as a toy sword or something.

**Comment by BatElite** [comment]
Woop woop getting back on this

The reason for those large highlights is they're meant to be 45 degree bevels that catch more light. I simply picked the lightest colour because that kepy the colour count low (5 for the blue ramp I think)

I think with what you're suggesting we'd roughly end up at this. The dispenser is still more or less two parts because I've been drawing on the old design for it. I don't know how well the bevel reads now, I'm at the point where I know what the sprites are trying to do too well to judge that accurately.

afbeelding

**Comment by flrsh** [comment]
Your newer design looks good to me!

**Review by ZeWaka — APPROVED** [review]

**Review by pali6 — APPROVED** [review]

**Review by flrsh — APPROVED** [review]

**Pull request merged**
