### PR TITLE
Gives MD+MDocs medical labcoats roundstart, swaps medical clothing locker med labcoats with normal labcoats, add cool medical labcoat as Patchwork reward

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Title, medical doctors and medical directors now spawn with medical labcoats. In medical clothing locker, there is now 2 labcoats instead of 3 medical labcoats. Patchwork now gives out a *cool* medical labcoat. 
image

## Why's this needed? 
I think this labcoat not only looks very neat, but I think it greatly increases the recognizability of doctors. Currently doctors look nearly visually identical to scientists from the front facing view. Doctors are one of the most important roles to be visually distinct, and I think this change should help them with that a lot.

## Changelog

```changelog
(u)Ikea, Flaborized
(*)Medical doctors and directors now spawn with medical labcoats. Regular labcoats can now be found in medical clothing lockers and the Patchwork medal reward now grants a <i>cool</i> medical labcoat (sprite by Flaborized!). 
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Doctor recognizability I dont think is an “issue” as in it stands out a lot, however generally speaking i think the more recognizable a job is (especially doctors) the better. A lot of doctors current uniform doesnt stand out much and isnt super recognizable at a glance and i think this helps contribute to doctors having to chase people down and shit in order to heal them.

 On improving visual identification by improving spawning gear. By removing the labcoat you would improve recognizability, but this is just bad, not only is this a nerf this also just looks less good. You can replace the labcoat with a different outersuit, but not much outersuits fit doctors, and most of those things are filled by other doctor clothing options. So the only option we’re really left with is changing the labcoat sprite. For good recognizability, its best to do something similar to what doctors currently have, which means really the only practical option is a labcoat with white primary and red secondary coloring, and things like a red cross… which is just the medical labcoat. Its hard to make an item to fulfill a niche when that niche is already filled by an item very well.
 
I am very much not opposed (ie supportive) to replacing the medal reward though. Main reason why i was fine with removing it was because the reward was already redundant and useless. Currently i have not much ideas as of the time writing this comment of what reward would be fitting to replace this reward with, so suggestions would be appreciated.

**Comment by pgmzeta** [comment]
When the nurse dress was updated ( https://github.com/goonstation/goonstation/pull/8506 ) the red medical cross was replaced with a blue one. Maybe something similar could be done for either the reward or non-reward version of this?

**Comment by NightmareChamillian** [comment]
Correct me if I'm wrong, but isn't there already a blue version of the doctor labcoat in the game that spawns in donut 3's break room?

In regards to my take on the changes, I'm a huge fan. Beyond my medical guide, the labcoat is usually the first thing I swap out for something that yells "I'm a doctor", so to me this is just a time saver, and if someone really wants to be a doctor with a labcoat they can just change into one.

**Comment by flrsh** [comment]
Added Flab's cool medical labcoat as the Patchwork reward.

image

**Comment by ThatFiveGuys** [comment]
Oh fuck me forgot to add that to this pr thank you

**Pull request merged**
