### PR TITLE
Remove slight gradient from Asimovs laws

### PR DESCRIPTION
**Pull request by JORJ949**
[Silicons] [Feature]
## About the PR 
Removes minor gradient from Asimov's law set

## Why's this needed? 
Who even knew this was a thing? Removed to make the disguised law module actually the same colour as asimov's no matter what law you replace.

### CODE REVIEW

**Comment by amylizzle** [comment]
That's there to provide a visual clue if someone messes with the law order. Having said that, if you're fine with it being removed then so am I

**Comment by JORJ949** [comment]
> That's there to provide a visual clue if someone messes with the law order. Having said that, if you're fine with it being removed then so am I 

I dont think I have ever seen that used mainly because of how negligible the difference is but also because if you want to mess with laws its probably not going to be changing the order around, and if you are gonna put in that effort it shouldnt really be noticable from a glance and the gradient kind of defeats the purpose of the disguised module.

**Review by TobleroneSwordfish — APPROVED** [review]
I think it's fine to be able to hide that you've messed with the order, and I certainly never noticed this was a thing sooo

**Review by amylizzle — APPROVED** [review]
Yeah, fine by me :+1:

**Comment by amylizzle** [comment]
One thought is that you might wanna do the same for the other law sets - iirc they both have gradients too

**Comment by JORJ949** [comment]
> One thought is that you might wanna do the same for the other law sets - iirc they both have gradients too

The only other lawset with a gradient is the syndicate one but that doesn't matter really

**Pull request merged**
