### PR TITLE
Fruit Milk added to Vending Machine

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
Adds in Creaca's Fruit Milk to the coffee vending machines; each bottle contains 30 units of milk and 20 units of pineapple juice. 
unknown (12)

## Why's this needed? 
I think it would be fun to have a cute little fruit milk drink you can buy and sip from while you work. 

## Changelog

```changelog
(u)Roddy
(+)Adds in some tasty fruit milk to a vending machine near you. 
```

### CODE REVIEW

**Comment by t-toasted** [comment]
Re: the fruit juice being pineapple. I'd have liked to have the fruit juice be randomized each time but, being unsure how to... code that, I just made it one type. Also sorry if the code is Weird.

**Comment by DisturbHerb** [comment]
> Re: the fruit juice being pineapple. I'd have liked to have the fruit juice be randomized each time but, being unsure how to... code that, I just made it one type. Also sorry if the code is Weird.

you could do this by using one of the probability procs or a switch statement on `New()` to change the contents, icon states, and  names

**Comment by Tarmunora** [comment]
who the heck makes pineapple milk. I'm scared.

**Comment by t-toasted** [comment]
> who the heck makes pineapple milk. I'm scared.

sippy sippy

**Comment by NightmareChamillian** [comment]
Something I cooked up for a random juice on spawn, for ease of copy pasting
`New()
		..()
		reagents.add_reagent("[pick(list("juice_watermelon",  "juice_blueberry", "juice_watermelon", "juice_cherry", "juice_apple", "juice_peach", "juice_grapefruit", "juice_blackberry", "juice_strawberry", "juice_orange", "juice_cran"))]", 20)`

**Comment by t-toasted** [comment]
> Here, this should work for adding a random juice on new. Keep in mind copy pasting won't exactly work but this is more or less what you'll want to do:
> 
> ```dm
> New()
> 		..()
> 		reagents.add_reagent("[pick(list("juice_pineapple",  "juice_blueberry", "juice_watermelon", "juice_cherry", "juice_apple", "juice_peach", "juice_grapefruit", "juice_blackberry", "juice_strawberry", "juice_orange", "juice_cran"))]", 20)
> ```

ooooh, thank you. If I get around to actually making it random this will be very helpful

**Review by flrsh — APPROVED** [review]
Fruit milk image
I can also walk you through randomizing the juice if you want. Just ping me in #imcoder!

**Pull request merged**
