### PR TITLE
Donut2 Engineering Department and Power Grid redesign

### PR DESCRIPTION
**Pull request by Cherman0**
## About the PR 

A total redesign of engineering on donut2 to try to modernize it while retaining the unique "features" of donut2. The image describes it in more detail than I could, but notable changes include moving the CE office into engineering, cleaning up engineering storage, making more room for collectors, and moving engineering podbay.

## Why's this needed? 

Engineering on Donut2 feels the least loved of the departments since the map's reintroduction, especially with regards to how little space it gives you for construction and the singularity. This should give engineers some more room to breathe.

## Changelog 

```changelog
(u)Cherman0
(*)Donut2's engineering department has been redesigned.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
just map review stuff

aesthetically really nice
grid looks fine

the hallways on the east/west/north of the singularity could use a little extra in them, just maybe chairs, folding tables, a little more to liven up especially the west

west maintenance hall might be missing an AI camera

collectors aren't networked

not sure if you are able to access the collector control from a diagonal like that, but i have no experience with such a setup, so i don't know for sure that it's blocked

ruck + reverse fab inside the chief's office might pose some balance concerns with who can/can't access/monitor the ruck

blinds on the external face of the windows strikes me as a little odd-looking

if you keep the hole where the command teleporter was, make sure the wingrille spawners are reinforced

access spawner + firelock missing on the yellow engineering door into the hangar 👁️ 

nice work

**Comment by Cherman0** [comment]
- Addressed the stuff in maintenance, should be better now.
- Collector arrays dont communicate on the PNET, and they can be accessed diagonally.
- I dont think I've seen anyone complain about the ruck in the CE office on Kondaru or Nadir, so it should be fine. Certainly isnt worse than the QMs being able to buy a ruck and deploy it anywhere, lol.
- The blinds on the outside of the windows was because we dont have blinds that fit a north-to-east or west inside corner, and I didn't want them to be inconsistent.
- Reinforced the windows and fixed the podbay door stuff.

**Comment by pali6** [comment]
Why is my review requested here?

**Comment by Cherman0** [comment]
> Why is my review requested here?

Not sure, actually. I had an issue earlier that made it request review from everyone, but i removed those and just left sord. Maybe you were looking at the email that sent you?

**Review by Sord213 — CHANGES_REQUESTED** [review]
Screenshot_692
Okay starting out with the secondary atmospherics room. This feels largely unnecessary. There's already a large atmospherics room, I don't see the reason to add a second one that is just for plasma and maybe kinda probably mixing TTVs? If you want plasma cooling capabilities I'd rather see that added to the existing atmos than a new weirdly placed one. The windows that can be viewed into from the little public storage room. The weird cutup of the AI upload's security perimeter.

Screenshot_698
This all seems fine, along with the CE's quarters.

Screenshot_695
Screenshot_696
Screenshot_697
I dislike all of these hallway maint corridors. Nothing in them reads as "this leads to a power storage room". Two of them have single tile entrances as well which will further make them seem like random areas not important power access corridors. They feel very empty and out of place. Also mixing the two plating styles in the SMES rooms.. Stick to one style, please.

Additionally, this change increases the amount of engineering space suits from 3 to 7. Two in engineering proper, two right next to it in the pod bay, and one per SMES substation. This is a massive change. Compare this to cogmap1 which has 2 and donut 3 which has 4 in engineering and one per solar setup, totaling 6. Drop this number down to 3 or 4.

Screenshot_699
Why the engineering airlocks on an exterior airlock? This is done on no other map and is just strange.

Screenshot_700
Screenshot_701
These two areas are narrowed down to a single tile's width. pls

Screenshot_702
Self explanatory.

Screenshot_694
Finally the singularity core. I like the expansion, but dislike the catwalks around it and overall setup. I understand why you set them up that way, to allow for expansion and creation of more collector arrays, but I dislike how it looks as it's expected to be expanded and ran as a large singularity, rather than accommodating a large singularity setup. 

If this was a new map, I'd say it looks cool and is neat, but you're altering an existing, historied map with a completely new design that is a drastic change from what it was previously so I'm going to look at it differently. 

The railings are excessive, and also general dev sentiment is that railings are kind of ugly, which I find myself agreeing with. They should be used sparingly.

The collectors aren't wired up properly. As far as I'm aware from looking at the code and using them previously, they have to be wired directly into the grid to function.

The two SMES units in the main engineering room just seem like they'll cause confusion. One powers part of the station, one powers just the singularity core. Unless you examine or actually check the name of the SMES you could set one and think it's fine, or set them thinking they work in tandem. Some visual differences from them, instead of a complete mirror setup, would alleviate this.

You also removed the notes explaining the four power grids. Even though you can see the other SMES units you might not know that they're working on independent power grids.


Overall I'm not a fan of a lot of these changes, but I'm not against them if what I outlined above is corrected.

**Review by Sord213 — COMMENTED** [review]
Okay starting off, here.
Screenshot_48
Why two tank storage units? These have variables that can be edited to adjust how many of each tank spawns in them.
The highlighted walls, especially the walls on the left, are excessive. Compare to the old upload:
Screenshot_49

Screenshot_50
This....aint it. A single wire going through walls feeding that quadrant of the station. Compared to the current version where the wires going through the walls were the raw power, not the actual station power coming from the SMES unit. If someone went and blew up one of the arms or cut the wires in the walls you're not completely out of power. Also, the SMES storage room is now only accessible via space with a space suit. This is not an improvement from the current version or your previous iteration.

Screenshot_51
I'd like to see a door into the bridge on the green mark, and a blast door that is controlled from inside the bridge on the red.

Screenshot_52
Power wire going through wall? Also bed layout is...odd.

Screenshot_53
Rounding back to this layout, which is where the majority of my issues with these changes lies. This whole singularity core is weird. The yellow highlighted areas are empty and feel off if you don't make more collectors.

If you attempt to make the largest size singularity you can by placing the field generators on the red mark you put the beams through the collector arrays. 

You also can't see the singularity from the safety of the control room, so you are required to have a space suit just to look at the singularity.

Screenshot_54
Now with the changes to the overall singularity core if a nukie warps to the engineering pod beacon and there's any engineers working here they're just flat out busted immediately. Compare to the current version where there's a chance a nukie could park their pod near the station side airlock and possibly go unnoticed.
Screenshot_55

**Comment by Cherman0** [comment]
Addressing the concern about the power wires going through the support around the singularity before reaching the station, I feel that making the SMES units closer to engineering necessarily makes them farther away from where they supply power to and makes this a rather unavoidable problem, if the separate grids are to be preserved. But considering that the original design of Donut2 already has plenty of wire chokepoints where one cut wire would cut off a large area and that it hasn't been a major problem (especially compared to how often donut2 gets blackouts because nobody set the SMES units), I don't feel like it will be a significant issue in practice.

**Review by Sord213 — COMMENTED** [review]
Yeah I'm still not a fan of the singularity core overall. Trying to put all four SMES units in one spot definitely doesn't work. I'd be fine with moving the some of the other changes (CE's office and hangar moving, diplomatic chambers, teleporter) but the rest (singularity core, inner engineering, mini atmos) I don't see getting accepted in any state similar to what it is now.

**Comment by ZeWaka** [comment]
You have linter failures.

**Comment by Cherman0** [comment]
Yeah, I noticed. Should be resolved now, forgor APCs in the substations

**Comment by ZeWaka** [comment]
@Sord213 ?

**Review by Sord213 — CHANGES_REQUESTED** [review]
Screenshot_240
Not a fan of the rad collector room. I'd prefer the old room design. 
Revert the maintenance side plasmaglass windows on AI upload as well, feels very off having them in maint.
Move the SMES instructions paper on top of the SMES unit, so you're likely to pick it up and see it when setting the power.
Could just be layering issue but make sure there's a firelock and access spawner on the green highlighted door. And a couple other doors around engineering.
Move the VR pod thing down a tile.

Screenshot_241
Screenshot_242
Screenshot_243
I don't really like...any of the SMES room changes at all. I prefer the old rooms and maintenance layouts.
The point of the clown hole was to have the window into the room so it seemed like the clown just sorta built it themselves and also had the hotwired APC. I thought the hotwired clown hole APC was a funny gag but I'm not suuuuuuper attached to it.

Also obviously make sure that merge conflict marker isn't there.

**Comment by Sord213** [comment]
Yeah I'm gonna be honest I don't really see this getting pushed through, for a lot of the stuff I stated above, as it's not what I'd like to see for Donut 2. If you'd like to make a PR of just the stuff like the hangar, CE's office, and the side rooms adjoining those + the diplo quarters and teleporter changes, I'd be cool with those.

**Pull request closed without merging**
