### PR TITLE
Different-colored medibots get different chems

### PR DESCRIPTION
**Pull request by j-awn**
[FEATURE][BALANCE]
## About the PR 

Medibots get a slight rework. Depending on the base medkit a medibot is constructed from, the medibot gets a different base healing chem, a new ailment to treat, and a new chemical to use when emagged. 

```
medkit  - base chem        - condition          - emagged chem
vanilla - n/a              - n/a                - n/a
brute   - salicylic acid   - hypo/hypertension  - ants
burn    - menthol          - ear/eye            - acetaldehyde
tox     - smelling salts   - radiation          - atrazine
oxy     - perfluorodecalin - anaphylaxis        - cyanide
neuro   - robustussin      - brain              - neurotoxin
crit    - n/a              - crit               - formaldehyde
head    - all of the above - n/a                - sarin
```

To make this work, the procs that govern medibot behavior were slightly refactored.

## Why's this needed? 

This PR gives the active roboticist the ability to enhance medbay significantly. This PR also buffs medibots (which I find are currently underused) significantly for both normal and traitor uses. I chose the new conditions to be treated carefully, to make sure that doctors were still required for a functioning medbay:

1. A patient just barely in crit might be fully healed by a series of medibots, but deep crit requires atropine or electric shock.
2. Synaptizine is not a very efficient chem for dealing with brain damage, and even a stack of saline and salicylic acid is a slow treatment for brute damage. A human or borg can treat patients much faster than even a stack of medibots.
3. Surgery and bleed damage are completely untouched by medibots
4. Most of the high-tier healing chems are not synthesized by medibots (other than perfluorodecalin, which was already synthesized by the Head Surgeon). Additionally, any chemicals that heal on `TOUCH` can't be applied by medibots.

With the exception of the head surgeon, the emagged chemicals are all easy to acquire or produce, and a chemist could synthesize a cocktail of the other new chemicals with little effort in only a few minutes.

Finally, the distribution of conditions and base chemicals was chosen for balance. The crit (or berserker, dusty medkit, etc.) medibot can heal patients in crit by itself, but only gets base chemicals to do it. The oxygen medibot has a strong base chemical, but anaphylaxis is quite rare. The tox medibot treats radiation (which is very helpful!) but its new base chem is smelling salts, which works only against a handful of knockout chems. 

## Changelog

```
(u)Jawns:
(*) Medibots constructed from different medkits have different chemicals and treat different ailments.
```

### CODE REVIEW

**Comment by TDHooligan** [comment]
a few of these specialised chems are left out of automation owing to their ease of becoming problematic, such as:
filgrastim (easily causes blood OD)
heparin (worsens bleeds)
smelling salt (causes tox to people not in crit, does not heal if not in crit) 
antihistamine (stuns, although rarely)

it may be worth switching vanilla medbots to Potassium Iodide as charcoal can very frequently get in the way of fixing people, then putting charcoal in the new Toxin bots

i also think, personally, the sheer volume of different outputs for these medbots is staggering to keep track of. I'd totally be game for it to be 1 improved chemical per type + the HS getting those upgrades. maybe the emag changes, too.

**Comment by Tarmunora** [comment]
Can't say I'm a fan. I don't think that 'heal-by-medibot' is terribly fun for doctors or patients, and I personally don't think it should be encouraged.

**Comment by Cthucky** [comment]
Injecting robustussin to treat brain damage?  Injecting menthol to treat ear/eye damage?  That makes even less sense than the standard spaceacillin injections.  Maybe I'm misunderstanding.

**Comment by j-awn** [comment]
> Injecting robustussin to treat brain damage? Injecting menthol to treat ear/eye damage? That makes even less sense than the standard spaceacillin injections. Maybe I'm misunderstanding.

Yes- each medibot gets a new base chem, along with a new condition to treat and an additional new chem for that condition specifically. For example, the burn medibot will inject saline to treat brute, menthol for burns, charcoal for tox, salbutamol for oxy, AND oculine for ear/eye damage.

**Comment by j-awn** [comment]
> a few of these specialised chems are left out of automation owing to their ease of becoming problematic, such as:
> filgrastim (easily causes blood OD)
> heparin (worsens bleeds)
The brute medibot should only be injecting these if someone is already hyper/hypotensive; the only danger I see here is if the injection amount is set too high and people are given far too much of the chemical, which can already happen with saline.
 
> smelling salt (causes tox to people not in crit, does not heal if not in crit)
This is valid. As per your comment below, maybe the default medibot could inject triple citrus, and the fancy tox medibot could inject charcoal? I don't really like that triple cirtus isn't a medical chem per se (and ants isn't a poison) but it gets the job done.

> antihistamine - debuffs stamina, stuns, although rarely, though will probably still be fine

The medibot will only inject antihistamine if the patient is overdosing on histamine- I think this will be fine.

**Comment by ZeWaka** [comment]
Needs more discourse, moving to forums.

**Comment by PrimeNumb** [comment]
Medibots are supposed to be supplements to doctors, so pushing them in this direction is something I am not a big fan of either.

**Pull request closed without merging**
