### PR TITLE
Cleaner Grenade Manudrive

### PR DESCRIPTION
**Pull request by Wisemonster**
[FEATURE] [GAME OBJECTS]

## About the PR 
This pr adds a cleaner grenade manudrive to custodial supply lockers.

## Why's this needed? 
Currently, 3 janitors get about 6 cleaner grenades to share, which isn't a lot, especially on main, and the only refill methods involve either a janitech refill cart, or a janitor supplies box, which comes with a lot of filler if only being bought for the cleaner grenades. This aims to help with this problem by giving janitors a way to print some cleaner grenades

## Changelog

```changelog
(u)Wisemonster
(+)Custodial supply lockers now come with a cleaner grenade manudrive.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Seems way too cheap, a single box of wires will be able to make 35 cleaning grenades (mats in fabricator code are in tenths). Outside of scope but ideally manufacturers should be able to use chemicals, in the meantime molitz (for the bubbles) and ice (for the water cleaning also because it requires some cooperation) should probably be used in the recipe and the amount of materials used should be bumped.

**Comment by CaioFrancisco** [comment]
If a Janitor had to use chems to produce cleaning grenades, then they might as well do smoke + cleaner. Ice can be easily obtained from the bar and I have no argument against using molitz. Perhaps there could be a machine to make cleaning grenades just by putting a beaker some space cleaner in it though.

**Comment by ThatFiveGuys** [comment]
> If a Janitor had to use chems to produce cleaning grenades, then they might as well do smoke + cleaner. Ice can be easily obtained from the bar and I have no argument against using molitz. Perhaps there could be a machine to make cleaning grenades just by putting a beaker some space cleaner in it though.

Smoke bombs are more clunky and harder to use and make, i dont think this is a real concern for not requiring space cleaner.

**Comment by Conchuckter** [comment]
Reverse fabricating grenades feels a bit wierd, refilling makes a lot more sense.

Also why don't you just make them mech scannable instead of using a manudrive?

**Comment by Wisemonster** [comment]
> Reverse fabricating grenades feels a bit wierd, refilling makes a lot more sense.
> 
> Also why don't you just make them mech scannable instead of using a manudrive?

I was looking at manudrives cause this would allow them to visit any fabricator and print some cleaner grenades, rather than have to ask/break into mechanics every time they want to print some cleaner grenades (which on main, would be frequently).

**Pull request merged**
