### PR TITLE
Adds more hydroponics trays to Oshan's hydroponics

### PR DESCRIPTION
**Pull request by Lythine**
[ADD TO WIKI] [MAPPING]
## About the PR 

Adds three more hydroponics trays to Oshan.
image

## Why's this needed? 

This gives Oshan a nice amount of trays to start with similar to other maps, which prevents fighting over trays, then spending time ordering and setting up a hydroponics crate.

## Changelog

```changelog
(u)Lythine
(+)Added more trays to Oshan's hydroponics.
```

### CODE REVIEW

**Comment by DimWhat** [comment]
Neither of the UV lamps are accessible.

**Comment by Lythine** [comment]
Kondaru does the same thing; all you need to do is move the hydroponics trays, which aren't anchored by default.

**Comment by DimWhat** [comment]
Just because another map does it doesn't mean it's good.

**Comment by Lythine** [comment]
I don't see what the problem is? The lamps aren't very active objects, they need to be turned on once early on and then never touched again. Surrounding it with trays is what you're meant to do. Are you suggesting it should be on by default?

**Comment by DimWhat** [comment]
I'm suggesting that this layout is not good.

**Comment by nefarious6th** [comment]
A potential solution for the top might be to make that double door a single door; put one of the three trays in that top section on either side in front of the shrubs; the other could go next to the front desk if you removed the one shrub sitting in front of the wall there. Alternatively the two corner shrubs could be removed and replaced with the trays, and the UV lamp swapped with the spot of the remaining tray.
I wouldn't know how to fully accomodate the set of trays on the left. I guess two tiles of width of stuff feels a little intrusive into the room when all of the other decor in the room is only one tile in from the walls?

**Comment by DimWhat** [comment]
I like this much better. Everything is accessible out the gate and leaves room for reorganization if somebody sees to do that.

**Review by mordent-goonstation — APPROVED** [review]

**Review by flrsh — APPROVED** [review]
I may futz with the layout a bit more, later.

**Pull request merged**
