### PR TITLE
Adds "Block Stacker" medal and Tetris AI skin

### PR DESCRIPTION
**Pull request by Lythine**
[FEATURE] [MEDAL] [SPRITES]

## About the PR 
Adds a medal called "Block Stacker" which is obtained by getting a score of 30,000 or higher in Robustris Pro. 
tetrismedal
This unlocks the Tetris AI skin reward which makes your AI screen perpetually play tetris. Background changes to be AI's color.
ai-tetris-big

## Why's this needed? 
It's another cool cosmetic for the AI to enjoy.

## Changelog

```changelog
(u)Lythine
(*)Added the Block Stacker medal and a Tetris AI skin reward for it.
```

### CODE REVIEW

**Comment by virvatuli-gh** [comment]
I love this! Does it play nice with the different screen colours?

**Comment by BatElite** [comment]
It looks like it's opaque, so mostly you'd jsut get the coloured light in the background.

**Comment by Lythine** [comment]
Currently the screen itself doesn't recolor in any way, but you can still recolor to change the light your holograms and screens give off, similar to the existing malfunction skin. No idea how it would recolor and still look good.

**Comment by geneva-breaker** [comment]
> Currently the screen itself doesn't recolor in any way, but you can still recolor to change the light your holograms and screens give off, similar to the existing malfunction skin. No idea how it would recolor and still look good.

I think you'd have to make the block animation an overlay and keep the screen blank for recoloring

**Review by Gannets — APPROVED** [review]
A really nice sprite & a welcome additional AI option.

**Review by flrsh — APPROVED** [review]
Neat medal and reward!

**Pull request merged**
