### PR TITLE
Reworks debris field crates and their loot 

### PR DESCRIPTION
**Pull request by flrsh**
[FEATURE] [REWORK] [WIKI]

## About the PR 

(I'm mostly PRing this so I can check the map and icon diff.)

This PR reworks debris field crates and their loot. 

The crates now randomly spawn across the map instead of always spawning in fixed positions. 

The crates no longer require you to solve a puzzle and instead are anchored (preventing any teleporting) and locked through an anti-tamper device. Smashing the anti-tamper device unanchors and unlocks the crates. 

The pool of possible loot has also been adjusted and expanded. Each crate will always contain at least three different kinds of items - aesthetic-motivated (e.g. clothing, skins, decor), department-motivated, and player-motivated. 

Some examples of new loot by Flaborized:

image
imageimage

The anti-tamper devices (also sprited by Flab) in action:

image

## Why's this needed? 

The crates randomly spawning and being anchored prevents players from using telescience to teleport them all to the station. Instead, players now have to physically visit locations and break the anti-tamper mechanisms first. This encourages a bit more exploration. 

The puzzles were usually just a time gate and not fun or engaging (especially if you just use an online solver or whatever). By replacing the puzzles with anti-tamper devices (which have a cool sprite and accompanying sfx) that you have to smash, I think it actually makes opening the crates more satisfying, since you get more visual and auditory feedback. 

The adjustment and expansion of the pool of possible loot also (hopefully) makes it so these crates are more interesting and worthwhile. 

## Changelog

```changelog
(u)Flaborized + Flourish
(*)Loot crates (the kind which you can find across the debris field) have been reworked. Along with now randomly spawning across the map, they no longer require you to solve a puzzle and instead are anchored and locked through an anti-tamper device. Smash the anti-tamper device with a hefty object (such as an extinguisher) to unanchor and unlock the crate. 
(*)Loot crate contents have also been adjusted - they now pull from a larger pool of possible loot and will always contain at least three different kinds of items. Sprites by Flab! 
```

### CODE REVIEW

**Comment by Sbmhawk** [comment]
Does smashing the anti-tamper device break the items inside?

**Comment by flrsh** [comment]
> Does smashing the anti-tamper device break the items inside?

Nope! Just unanchors + unlocks the crate. A variant that *does* destroy the items (unless unlocked with a pin or something) could be cool as a thing you could find and use yourself, but that's out of scope for this PR.

**Comment by nefarious6th** [comment]
looks awesome

**Comment by flrsh** [comment]
> Do you think you could add the crown, birdman suit, long bee, and antlers as funny clothing loot? Would love to see them cycle around more often as whacky costumes.

I think most of those are already obtainable through QM, and I'd like the clothing loot here to be fairly distinct from other sources, so probably not.

**Pull request merged**
