### PR TITLE
Moves ricin and ghost chilli juice to be brewing results instead of inherent reagents

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BALANCE] [HYDROPONICS]
## About the PR 
Ricin rice and ghost chilli peppers no longer contain their poisons directly, instead needing to be refined in a still to get it.

## Why's this needed? 
The existence of extremely deadly and stealthy spliceable poisons severely limits botany design space with regards to things that inject reagents. I think it'd be cool if we could have more interesting ways to apply reagents without giving rise to infinite ricin death traps.
See #15317 and #14516 for examples of features that are hampered by the existence of these spliceable poisons.
## Changelog 

```changelog
(u)LeahTheTech
(*)Ricin and ghost chilli juice reagents are no longer present directly in their respective crops, instead requiring them to be brewed in a still.
```

### CODE REVIEW

**Comment by Glamurio** [comment]
Good idea, might I suggest cross-referencing it with #14794 because it contains a still rework that includes `brew_amount` which could be used to further refine the amount of reagents produced via still.

**Comment by TDHooligan** [comment]
i think a visual effect for these reagents would solve the issue nicely, and make uber-spliced plants even more  awful looking

**Comment by colossusqw** [comment]
> i think a visual effect for these reagents would solve the issue nicely, and make uber-spliced plants even more awful looking. but this is also a good bandaid solution

A visual indicator seems like it would be a cool way to make them still possible whilst a very obvious threat

**Comment by TobleroneSwordfish** [comment]
I've given my reasoning for this, I think it's the best way to allow for more creative and consistent botany features, and losing ricin rafflesias for that is frankly an upside. This is also the only way I can see the nettle and maneater updates being mergeable.

**Pull request merged**
