### PR TITLE
Fix critters not being able to use storages

### LINKED ISSUE #8509: Critters cannot see inside containers
### Labels

[BUG]

### Description

Critters cannot see inside containers.

### Steps to reproduce

1. Be a critter
2. Pick up a container such as a box
3. Press hotkey for using or click on container

### Expected Behavior

For the container contents to be shown

### Additional Information & Screenshots

_No response_

### PR DESCRIPTION
**Pull request by FlameArrow57**
[PLAYER ACTIONS][GAME OBJECTS][BUG]

## About the PR 
This PR fixes critters not being able to use or see inside storages.

Also prevents small animals from using storages.

The HUD style for storages used is still regular human style, not critter style

## Why's this needed? 
Bug fix, fixes #8509

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
One slight issue with flockdrones:
image
I'll uhh let you figure out what to do about that.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
x

**Comment by FlameArrow57** [comment]
I just moved the egg button if that's fine

image

**Comment by ZeWaka** [comment]
Egg

**Comment by FlameArrow57** [comment]
image

**Pull request merged**
