### PR TITLE
Updates the edit character button to use human resprite sprites

### PR DESCRIPTION
**Pull request by MatheusIsNotAvailable**
## About the PR 
Captura de Tela (26)
## Why's this needed? 
Should have probably been updated along with the other stuff

### CODE REVIEW

**Review by virvatuli-gh — CHANGES_REQUESTED** [review]
It's missing the drop shadow that the other buttons' icons have (and previous icon used to have). Could also update the ghost to not be the super old ghost sprite from eons ago too, if you felt so inclined 👀

**Comment by MatheusIsNotAvailable** [comment]
I would rather not use the newer ghost because it looks small and harder to read on  the button, could sprite something special for it but that is for another PR.

**Comment by BatElite** [comment]
I think that ghost still shows up in a secret(?) spot btw.

**Review by ZeWaka — APPROVED** [review]

**Review by virvatuli-gh — APPROVED** [review]
oops, forgot about this PR when I went out-of-country. Looks good 2 me now

**Pull request merged**
