### PR TITLE
Adds a new Z5 prefab: The Mauxite Hideout

### PR DESCRIPTION
**Pull request by CheffieGithub**
## About the PR 
Adds a new prefab which is completely built into an old mauxite comet / asteroid.
The structure inside is mostly made of mauxite making use of the new material sprites.
Exclusively uses the new flood lights for lighting.

Notable contents:
Four angry fermids.
One loot spawner.
Precious ore and mauxite building materials.
Two chemical grenade casings.
One uniquely named rockworm. (cute)
One spacesuit and jetpack set.

image

image

full bright:
image

## Why's this needed? 
More variety in prefabs is nice. Makes use of mauxite material crafting which currently isn't mapped.

## Changelog 

```changelog
(u)Cheffie
(+)A new structure has been detected in the asteroid belt.
```

### CODE REVIEW

**Review by TobleroneSwordfish — COMMENTED** [review]
Looks cool, although half of the code changes don't seem related to this PR?

**Comment by CheffieGithub** [comment]
All the changes are somehow related since I needed to make subtypes of stuff for materials.
New comet turfs and walls that aren't mauxite are there since if im going to add one I may as well add them all for anyone looking to make anything else later.

**Comment by ZeWaka** [comment]
Can we get some images in the PR desc?

**Comment by CheffieGithub** [comment]
done

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
