### PR TITLE
Add PTL, MD office and CE office to atlas

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Adds a second ship to mirror the science one
On the second ship is a PTL, CE office, engi storage, and engi hangar (ignore the debug generator in the storage room)
image
Reclaim empty room for the MDir office and swap it with the toilets
image
Move the north trader dock onto the outer ship and expand mechanics and refinery slightly
image

## Why's this needed? 
Adds many things that arent presently on atlas such as ABCU units, the PTL and a portamedbay

## Changelog 

```changelog
(u)JORJ949
(*)Added a second smaller "ship" to atlas on the northwest side of the ship, on board is a PTL and CE office.
(+)Added a Port-A-Medbay and MDir office to atlas.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Oh this is really coool! I love the inbuilt PTL mirror setup. Maybe for symmetry and ease of access the cables should go over the gantry rather than under the airbridge?

**Comment by JORJ949** [comment]
> Maybe for symmetry and ease of access the cables should go over the gantry rather than under the airbridge?

I wanted the PTL wire to be easily reached by any engineers looking for a potential hotwire, instead of running it through mining.

**Comment by Cherman0** [comment]
Mmm... I like the concept of putting in a CE office and PTL and I like the symmetry, but these don't seem like things that would be on a detachable ship. It would be a larger map overhaul but maybe it would make sense for mining to be on a ship (with the magnet somewhat mirroring the toxins test platform) and haivng the engineering stuff be where mining currently is?

**Comment by JORJ949** [comment]
> Mmm... I like the concept of putting in a CE office and PTL and I like the symmetry, but these don't seem like things that would be on a detachable ship. It would be a larger map overhaul but maybe it would make sense for mining to be on a ship (with the magnet somewhat mirroring the toxins test platform) and haivng the engineering stuff be where mining currently is?

My lore excuse for it is that the realised atlas doesnt have a PTL and instead of doing an expensive retrofit on a large-scale ship they retrofitted another ship that was going to be scrapped and sent it to dock with atlas.

**Pull request merged**
