### PR TITLE
Resprites several foods, changes chip bag behavior, and adds Potato/Onion Chips.

### PR DESCRIPTION
**Pull request by MitchTheUser**
## About the PR 

ChipsDisplay

Chips, Onion Chips, Granola Bars, and Honey Wonks now have shiny new sprites. The chip bags now function as proper bags and can be opened and closed, with sprites for being closed, opened, and empty. Alongside this, there are now individual chips in the bag. Each bag holds 8 chips, the status effects from the food are given by the chips themselves, and the sprites are unique to its bag type. 

## Why's this needed? 

Chips and Onion Chips have old and messy sprites and looked weird since the bag was eaten. It was also in the wanted resprites list. This brings it in line with the design and behavior of the other food bags.

Granola Bars were in cabinet perspective. This brings it in line with other candy bars while maintaining its thin design.

Honey Wonks was in cabinet perspective, generally looked dull, and didn't match the other cereal box sprites.

## Changelog 

```changelog
(u)MitchSmith
(+)Chips, Onion Chips, Granola Bars, and Honey Wonks Cereal Boxes have new sprites.
(+)Adds Potato Chips and Onion Chips.
(+)Chip bags now work as actual containers and have 8 Chips in them.
```

### CODE REVIEW

**Review by WALPVRGIS — APPROVED** [review]
This is a sprite-only review, I haven't looked at code, but it works fine in testing. I suspect that the onion chips are actually meant to look like funyuns, Bc of how similar the packaging looks:

image

So that would be a nice change if you were willing, but I don't care a huge deal lol. Maybe if we wanted to differentiate the chip designs more that is an option. Otherwise, sprites look good to me 👍

**Comment by MitchTheUser** [comment]
> So that would be a nice change if you were willing, but I don't care a huge deal lol. Maybe if we wanted to differentiate the chip designs more that is an option. Otherwise, sprites look good to me 👍

K, I made the chip look more like an onion ring and edited the bag to show the presence or lack of an onion chip in them.

**Comment by MitchTheUser** [comment]
!merge_upstream

**Comment by MitchTheUser** [comment]
Unfortunately this branch has some problems that were unable to be fixed, I'll be recreating this on a new branch without the problems this one got.

**Pull request closed without merging**
