### PR TITLE
Manta escape subs!

### PR DESCRIPTION
**Pull request by j-awn**
[FEATURE]
## About the PR 

Manta gets escape subs!

## Why's this needed? 

Nobody should be stuck on Manta.

## Changelog

```
(u)Jawns:
(*)NSS Manta equipped with escape submarines. Terms and conditions may apply.
```

### CODE REVIEW

**Comment by flrsh** [comment]
Could the number of escape subs be reduced to 4 or 6? Or would that ruin the balance aesthetically?

**Comment by j-awn** [comment]
> Could the number of escape subs be reduced to 4 or 6? Or would that ruin the balance aesthetically?

It could be reduced- do you prefer 4 or 6?

**Comment by flrsh** [comment]
> It could be reduced- do you prefer 4 or 6?

I'd prefer 4!

**Comment by pali6** [comment]
What's the status of this?

**Pull request closed without merging**
