### PR TITLE
Security Vendor Changes

### PR DESCRIPTION
**Pull request by Sord213**
[INPUT]

## About the PR 
Splits up the loadouts in the Security Vendor between two sections; Loadout and Utility. Also adds a few more Utility items. Each token comes with two Utility credits, so you can pick two items from the list below.
Current utility item choices:
Four morphine autoinjectors
Two Robust donuts
Four crowd dispersal grenades
Forensics scanner
High Capacity Power Cell (300)
Advanced first aid kit, the one that spawns with menders
NVGs
Two boxes of 40mm PBR rounds (4 shots total)

Nothing is lost from the old loadouts, just lets you pick what bonus stuff you get. Also adds in a free barrier to every loadout!

## Why's this needed? 
Brings more versatility into selecting a loadout as a Security Officer. Should hopefully improve the secoff experience by allowing them to pick what gear they want and adapt to situations better.

Also removes the "Support" loadout. I've seen too many new secoffs select the loadout, not knowing they don't get a ranged stun weapon then being stuck with it the entire round. Often times these players would simply disconnect.

Update: Replaced 200 cells with 300 cells after the received feedback. Added a "Just a Baton" loadout that comes with baton + barrier as well for security officers who do not want a ranged weapon.

## Changelog

```changelog
(u)Sord:
(*)Reworked Security loadouts in the Security equipment vendors.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Would be nice perhaps if there was a restriction against taking 2 of the same item. Might not be needed though.

**Comment by Eagletanker** [comment]
Could there remain the support loadout but you get more utility tokens in exchange for no ranged weapon?

**Comment by Sord213** [comment]
> 
> 
> Could there remain the support loadout but you get more utility tokens in exchange for no ranged weapon?

As of right now I don't think there's a way to make selecting one loadout grant more utilities.

**Comment by Tarmunora** [comment]
A 'utility token' that grants a single utility purchase perhaps? (and you would get one free 'utility token' in the gun-less loadout)

**Comment by Eagletanker** [comment]
> A 'utility token' that grants a single utility purchase perhaps? (and you would get one free 'utility token' in the gun-less loadout)

Yeah, I was imaging something like that.

**Pull request merged**
