### PR TITLE
Fixes the wifi component not corrupting the missile packet

### PR DESCRIPTION
**Pull request by ThePotato97**
[BUG]

## About the PR 

Fixes the wifi component not corrupting the missile packet so it's like the packet sniffer on PDAs

image
image

## Why's this needed? 

Must've been overlooked.

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
So, with both that and the sniffer not working, how are you supposed to be able to get the missile packet if you are a nerd?
Asking for a friend.

**Comment by ThePotato97** [comment]
> 
> 
> So, with both that and the sniffer not working, how are you supposed to be able to get the missile packet if you are a nerd?
> Asking for a friend.

You're not supposed to get it

**Comment by zjdtmkhzt** [comment]
pali seemed to imply on the discord that there were other, more involved ways?

**Comment by ThePotato97** [comment]
> 
> 
> pali seemed to imply on the discord that there were other, more involved ways?

Piece it together from scrambled information

**Comment by zjdtmkhzt** [comment]
Surely you wouldn't get enough pieces for that from the amount of missiles from one detomatix?

**Comment by ThePotato97** [comment]
> Surely you wouldn't get enough pieces for that from the amount of missiles from one detomatix?
> Anyway, I have never seen anyone abuse this, and mass pda bombs doesn't really seem that bad.
> So I don't really see a need to remove it.

Multiple wifi components each would get part of the code with 1 missile

**Comment by zjdtmkhzt** [comment]
Ah, I see, that makes sense, thanks.

**Review by Sovexe — APPROVED** [review]
sidenote - The way I use to get the code in one attempt will still work fine

**Review by ZeWaka — APPROVED** [review]

**Comment by ThePotato97** [comment]
> 
> 
> sidenote - The way I use to get the code in one attempt will still work fine

Mainframe radio?

**Pull request merged**
