### PR TITLE
Oshan engineering lockers

### PR DESCRIPTION
**Pull request by trerri**
## About the PR 
Adds 2 lockers to Oshan's Engineering department, since there were only 3 even though there are 5 engineering slots (:byondood:).

## Why's this needed? 
Because at least once have I latejoined as engineer and found myself lacking in utility belts and usefulness.

## Changelog

```
trerri:
+ Added 2 extra engineer's lockers to Oshan.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
@trerri this branch is not clean

**Comment by trerri** [comment]
@ZeWaka what does that mean

**Comment by pali6** [comment]
You're modifying `code/WorkInProgress/Electronics.dm` and `icons/obj/device.dmi`.

**Comment by pali6** [comment]
And now there's also a merge conflict, sorry! You'll have to change `icons/obj/device.dmi` to `icons/obj/item/device.dmi`.

**Pull request closed without merging**
