### PR TITLE
Cargo on Horizon's routing vastly simplified, "renovates" horizon barbershop.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr has cargo come from the right side of the ship, with a relay to deal with selling and buying things. A lot of the previous cargo routing has been gutted, and the barber has been replaced 
image
image
image
image
image

## Why's this needed? 
The reason why I added the barber changes in this pr is due to the barbershop being a part of the routing system,  just gutting the previous infrastructure would leave it looking empty and bad. Horizons cargo system frequently breaks, is painful to repair, and makes thing take a long time to arrive to cargo. Simplifying it and making it closer should help alleviate these issues a lot.

## Changelog

```changelog
(u)Ikea
(*)Cargo's routing system on horizon has been vastly simplified.
(*)Nanotrasen has renovated horizon's barbershop for industrial hair cutting.
```

### CODE REVIEW

**Comment by Momoberry** [comment]
It would be a huge QOL to horizon QMs for this to get merged.

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
Yeah no the infinite lag-o-rama of conveyors by the barber shop isn't good

**Comment by ThatFiveGuys** [comment]
Do conveyors make a lot of lag? I can reduce the amount of conveyors in it. Cant really have the old design barber shop with the removed cargo infrastructure without it feeling very out of place

**Comment by Momoberry** [comment]
> Yeah no the infinite lag-o-rama of conveyors by the barber shop isn't good Should've atomized the change

I'm honestly confused with conveyor game philosophy on goon. If they're that lag producing, why do we have such huge systems dependant on them like hell belts and the crate mailing systems? I feel like that would be a pretty big performance boost to just get rid of them and have a pipe system around for mailing instead. We have several different systems for the same things, I guess?

**Comment by ZeWaka** [comment]
> > Yeah no the infinite lag-o-rama of conveyors by the barber shop isn't good Should've atomized the change
> 
> I'm honestly confused with conveyor game philosophy on goon. If they're that lag producing

They're not that lag producing, but why have it running endlessly if nobody is ever going to that ship to even see it.
Also, it's literally acting as filler, both in the spatial (takes up room) and gameplay (no meaningful addition to how one interacts with the map) sense. Filler content never feels good.

**Comment by ThatFiveGuys** [comment]
The hallway now links up with it through the chutes, and said hallway is purposefully dirty and out of place. I think its eye catching enough to lead a lot of people to check out the barbershop out of curiousity alone. Barbering is a pretty common new player gimmick i see done and my intent here is to allow that to actually be practical to do on horizon now (considering previously it was hidden so no one went there, while this should get people to come to the barber shop). 

That being said, since (I presume) off conveyors make far less lag, i could (and will) toss in a switch to turn them on/off, and probably will remove the outer layer of conveyors too.

**Comment by ThatFiveGuys** [comment]
Fucked this branch up so gonna redo it

**Pull request closed without merging**
