### PR TITLE
Resprites the captain's antique laser gun.

### PR DESCRIPTION
**Pull request by DimWhat**
## About the PR 
Changes the sprite of the captain's antique laser gun to a newer sprite. Big thanks to cogwerks and flaborized for giving me advice.
image

## Why's this needed? 
The old one really needed it. It hardly fits the artstyle nor does it look great.

## Changelog

```changelog
(u)DimWhat
(+)Respriited the captain's antique lasergun
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
This was definitely a more crusty sprite so a resprite would be highly appreciated. The purple strip is hard to read and the pallete makes it look martian-e, may be good just removing the sprite entirely. The gun seems very flat and the red bulb on top of it feels distached from the rest of the gun.

**Comment by DimWhat** [comment]
converting to draft as the sprite needs more work

**Comment by DimWhat** [comment]
Alright touched up the sprite.

**Comment by 13spacemen** [comment]
@DimWhat This is a very nice sprite, may I have your permission to port this to TGstation and other AGPLv3 codebases?

**Comment by DimWhat** [comment]
@13spacemen Uh hi I'm sorry I didn't talk to you sooner, I tend to use discord. Please contact me there. I'm DimWhat#5995

**Pull request merged**
