### PR TITLE
Lowers the space of fanny packs to 5

### PR DESCRIPTION
**Pull request by DimWhat**
[Balance]

## About the PR 
Lowers the slots in fanny packs and funny packs from 7 to 5. This does not lower the amount of space in the syndicate belt pack.

## Why's this needed? 
Fanny packs are very very good belts that have no real restrictions or difficulty in getting. They currently are functionally the same as a backpack except you can also wear a backpack as well as a fanny pack. I believe these should be toned down slightly as to be not as good as a backpack.

## Changelog

```changelog
(u)DimWhat
(*)Made fanny packs (not funny packs) only have inventory 5 slots.
```

### CODE REVIEW

**Comment by penny64** [comment]
You say they should be nerfed but why?
What is the end?

**Comment by DimWhat** [comment]
> You say they should be nerfed but why?
> What is the end?
I said this right here.
> They currently are functionally the same as a backpack except you can also wear a backpack as well as a fanny pack.

**Comment by 112358sam** [comment]
The clown gets a funny that is a type of fanny pack, and that will inherit this change. Maybe that should be set to 7 since they don't get backpacks?

**Comment by mordent-goonstation** [comment]
> The clown gets a funny pack that is a type of fanny pack, and that will inherit this change. Maybe that should be set to 7 since they don't get backpacks?

Given how easy backpacks are to get, I don't see this as a real balance thing. If we were to make funny packs hold more than fanny packs it would probably be for the purpose of making it so the clown is a good target to loot.

**Comment by DimWhat** [comment]
I am quite willing to add the input wanted tag

**Comment by penny64** [comment]
@DimWhat that's just a statement

Why is it bad for them to be this way

**Comment by Azrun** [comment]
Consider modification of:
https://github.com/goonstation/goonstation/blob/7f51873c5dbe6b80d3567f1b8121bc16729a18ce/strings/roundstart_hints.txt#L55

**Comment by Carbadox** [comment]
I wrote my thoughts on the forum post but I think the fanny pack deserves a better fate than having it's identity removed by nerfs and while I approve and understand of the sentiment and cause behind the change, the execution isn't something I'm a fan of

**Comment by penny64** [comment]
I wanna copy this one here

> Where I'm sitting I really like:
Spawning them randomly in maint, we can add them to a random item spawner

> Adding some actual consequences, like being easier to shove users.

> A five slot fanny pack still holds five tool belts worth of items, you're not actually adding any consequences and people will still rush them because they are still amazing.

**Comment by Tarmunora** [comment]
edited to keep clowns at 7 slots

**Pull request merged**
