### PR TITLE
Security health implants only send out an alert on death.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr removes the ability for security health implants sending out health alerts upon people entering crit. This means that now security health implants only send out an alert upon reaching death. Normal health implants behavior is unaffected.

## Why's this needed? 
This change is primarily designed to nerf  competent security teams. With the competence of security recently, clearer indications of when security is alerted, and/or the alerts happening later on should help with the situation of 5 sec offs swarming a single antag. When someone enters critical is most of the time unclear during combat, unlike death which has very clear indicators (death gasp + examine text). Not only that, but for weaker weapons and/or longer battles, the time between someone entering crit and them dying can be far longer. This should give antags more time to deal with killed people, and also a more clear indicator on when security is going to come swarm.

## Changelog

```changelog
(u)Ikea
(*)Security health implants now only send out an alert on death, normal health implants behavior is unaffected.
```

### CODE REVIEW

**Comment by swinglow20** [comment]
Some thoughts: Security doesn't exist in a vacuum. That miner in crit who can't speak because of a mutation sure does wish he could notify someone of his condition. Removing the alert also detracts from medbay. I know at least on RP a lot of doctors will wear what I like to call a "Field medic" set, and go out of their way to leave medbay to help injured crew. They can't do much for a person if they're already dead. The way this is framed seems to revolve solely around the way security responds to a situation. I wasn't even aware security had access to the medical alerts beyond security officers linked in the system. Overall, this change does a lot more harm than good, and seems to lean in to the rampaging side of the game.

**Comment by Nexusuxen** [comment]
Maybe it would be best to only have Security be alerted once someone dies, whereas Medbay gets alerted when they also go into crit?

**Comment by Yellow-Mushroom** [comment]
> Maybe it would be best to only have Security be alerted once someone dies, whereas Medbay gets alerted when they also go into crit?

I really like this idea

**Comment by ThatFiveGuys** [comment]
Normal health implants behavior is now unchanged, security implants still dont send out an alert on crit.

**Comment by Eagletanker** [comment]
> Some thoughts: Security doesn't exist in a vacuum. That miner in crit who can't speak because of a mutation sure does wish he could notify someone of his condition. Removing the alert also detracts from medbay. I know at least on RP a lot of doctors will wear what I like to call a "Field medic" set, and go out of their way to leave medbay to help injured crew. They can't do much for a person if they're already dead. The way this is framed seems to revolve solely around the way security responds to a situation. I wasn't even aware security had access to the medical alerts beyond security officers linked in the system. Overall, this change does a lot more harm than good, and seems to lean in to the rampaging side of the game.

You cannot survive every encounter, and the cloner does bring these people back. With the cloner changes it’s rare you see non security crit alerts, so I don’t think this changes much aside from making fighting sec not as much of a hassle considering they have 4 ways to rapidly and quickly get the attention of other security

(Also crisis alert exists which you can just hit at any time on the by and by)

**Comment by nefarious6th** [comment]
> Normal health implants behavior is now unchanged, security implants still dont send out an alert on crit.

you can just stack a normal with a sec-issue as a secoff then and get the same effect as a current normal or current sec-issue?

**Comment by ThatFiveGuys** [comment]
Could, however most/all security officers wont, too much work for too little gain.

**Comment by ThatFiveGuys** [comment]
Im fine with security being able to retrieve the corpses of there colleagues because oftentimes medical doesnt, and half the time the death is a sec ass wandering into space. In both this pr and current behavior, security only gets alerts from those with security implants.

**Comment by pali6** [comment]
> It seems like a better way of doing this would be to remove security from the `MGA_MEDCRIT` group?

That's what I'd do too if I wanted to tweak this.

**Comment by flrsh** [comment]
I agree with a lot of the commenters in the forum discussion thread; try these suggestions in a new PR if you're committed to the general idea. 

> Maybe it would be best to only have Security be alerted once someone dies, whereas Medbay gets alerted when they also go into crit?

> It seems like a better way of doing this would be to remove security from the `MGA_MEDCRIT` group?

**Pull request closed without merging**
