### PR TITLE
Improves performance with an open stat panel

### LINKED ISSUE #10993: Wraith client lag
### Labels

[BUG]

### Description

When playing wraith my client framerate seems lower and choppy.

### Steps to reproduce

1. Be wraith
2. Move around and observe the choppy framerate

### Expected Behavior

I expected to not lag just for being a wraith

### Additional Information & Screenshots

Not related to the wraith rework, have been experiencing this for a while.
My CPU usage seems to be consistently about 5% higher when playing wraith, not sure if this means anything or really how to go about diagnosing this. I'm just posting this to see if anyone else has this issue or an idea of what causes it.

### PR DESCRIPTION
**Pull request by MetricDuck**
## About the PR 
Having the stat panel open whilst being a wraith or blob noticeably impacts client framerate. 

Through the process of making random changes and compiling I've determined that it's because we're sending src.points as number to the stat panel, when we should be sending it as a string.

Do I know how or why this PR improves performance? No. 

Can I quantify the performance improvements? Yes!

### Current Performance
(benchmarked to my laptop)

30 seconds as human running around the donut 3 bar with the status panel open:
image

30 seconds as wraith running around the donut 3 bar with the status panel open (this feels incredibly choppy/laggy):
image

30 seconds as wraith running around the donut 3 bar with the status panel closed:
image

### Post-PR Performance
30 seconds as wraith running around the donut 3 bar with the status panel open:
image

Comparing each scenario as a ratio of human GetMapIcons calls:
- Human: 100%
- Wraith w/ stat panel shut: 100%
- Wraith w/ stat panel open (pre PR): 67%
- Wraith w/ stat panel open (post PR): 92%

## Why's this needed? 
Peformance improvement.
Fixes #10993

### CODE REVIEW

**Comment by MetricDuck** [comment]
Bear in mind there's still a slight performance hit, particularly with blob.

**Comment by Tarmunora** [comment]
is this also an issue for admin stats panel etc?

**Comment by MetricDuck** [comment]
> is this also an issue for admin stats panel etc?

Testing indicated most of the slowdown came from src.points alone. The admin tab didn't feel like it made a measurable difference when running about as a human, though I converted runtimes to a string just in case.

Alarmingly, setting the proc that sleeps stat updates from 0.1 seconds (for admins) to 30 seconds still resulted in slowdown: it wasn't updates that were causing (all) the slowdown, it was apparently the display of a number to the player that was the issue.

Also confusing is that the client compiler doesn't seem to pick this up? I've had to use number of calls over a real time period as the metric to measure performance, but time spent is proportional to # of calls. It's using the same amount of CPU despite lagging?

I've just remembered BYOND.com is a thing so I'll try and make a test case for it raise this as a BYOND bug today/tomorrow.

**Comment by MetricDuck** [comment]
My test case doesn't suffer any slowdown from sending a number to the stat panel

😭

**Comment by ZeWaka** [comment]
> Also confusing is that the client compiler doesn't seem to pick this up? I've had to use number of calls over a real time period as the metric to measure performance, but according to the compiler the time spent is still in the same proportion to # of calls as before. So it's doing less overall calls that cost the same? Alternately the lag is server side

the client profiler is notoriously inaccurate

**Comment by MetricDuck** [comment]
Drafting so I can investigate this further

**Comment by MetricDuck** [comment]
This isn't the right solution

**Pull request closed without merging**
