### PR TITLE
Updates most vending machines w/ directionals

### PR DESCRIPTION
**Pull request by SgtManGuy**
## About the PR 
Updates the majority of vending machine sprites & adds north, west, and east facing directionals. Also de-warcrimes the medical vendor.

## Why's this needed? 
It's been on the wanted resprite list for some time now. And it looks nice!

## Changelog

```changelog
(u)What/SgtManGuy
(+)Updated most vending machine sprites with directionals.
```

### CODE REVIEW

**Comment by Josephin23** [comment]
screenshots?

**Comment by SgtManGuy** [comment]
> screenshots?

Of course. Attached is an image of several of the modified sprites. 
image

**Comment by Flaborized** [comment]
I said this in #imspriter when the project was nearer to its start, but I feel like a lot of these designs lose a lot of visual clarity by having completely different imagery based on the directionals. The color schemes used are often quite different as well. Learning what every vending machine looks like and what they sell is a skill you pick up as you play the game, but it's much more difficult to do that if when it's facing north it looks completely different.

Here's a picture of the cigarette vendor to demonstrate my point. It looks like three entirely different machines. Keep in mind that 99% of the time you'll only ever see one directional state used in an instance, since vending machines rarely move.

unknown


I think *some* of the vendor designs in the PR get away with this by having unique shapes (the pizza vendor especially) but in general I *personally* don't think that making the designs fit in slightly more accurately is worth the loss in visual clarity, Keep in mind that my opinion is jut my own and not necessarily representative of how other admins feel tho

**Comment by ZeWaka** [comment]
> ...but in general I _personally_ don't think that making the designs fit in slightly more accurately is worth the loss in visual clarity...

yeah I really agree with that, even though none of these directionals would really be used right away, it should be obvious what the machine is from every direction - even the back

also i think i said this in the past, but i'll whitelist this PR for the feature freeze - even though it breaks the technical rules.

**Comment by SgtManGuy** [comment]
> but I feel like a lot of these designs lose a lot of visual clarity by having completely different imagery based on the directionals

Admittedly, this was a bit of a challenge. I asked folks which they preferred to _generally_ guide me, but if there's anything that is in need of a redesign for readability let me know.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
x

**Comment by SgtManGuy** [comment]
Alright, updated a good number of the sprites so they should be easier to identify now. Also redesigned the computer parts (?) vendor on being asked to do so.
North-facing sprites that displayed the backs should all be removed, too. I couldn't get them working the way i wanted to.
Let me know if there's any issues, please. This github stuff is odd and alien to me.

**Comment by ZeWaka** [comment]
wizard and janitor seem to still have a back

**Comment by SgtManGuy** [comment]
> wizard and janitor seem to still have a back

My bad. I've removed those and quickly double checked everything - Please let me know if I missed anything.

**Comment by SgtManGuy** [comment]
Updated everything. New vending machines are accounted for, but they currently lack directional sprites. I may get around to adding them later.

**Review by ZeWaka — COMMENTED** [review]
looks good enough - what's with shifting all the sprites downwards?

**Comment by SgtManGuy** [comment]
> looks good enough - what's with shifting all the sprites downwards?

I had to adjust the size of the sprites to make the directionals work. They look fine in-game from my observations.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
