### PR TITLE
Separate captain's armor

### PR DESCRIPTION
**Pull request by Glamurio**
[Balance] [Clothing]

## About the PR 
This PR separates the captain's armor into individual pieces.

image

Adds `/obj/item/clothing/shoes/swat/captain`, which are stat-wise identical to the swat shoes that captain usually starts with.
Adds `/obj/item/clothing/gloves/swat/captain`, which are stat-wise identical to the swat gloves that NTSO usually starts with.

Subsequently, makes captains start with the aforementioned boots and gloves equipped.

Also fixes a minor duplicate name in `hand_feethand.dmi`, namely `bgloves`.

## Why's this needed? 
Helps readability of individual parts, such as gloves and shoes. Also increases customizability.

## Changelog 

```changelog
(u)Glamurio (Ryou) & DimWhat & Piesuu
(*)The captain has cut up their armor into individual parts, which can be equipped separately.
```

### CODE REVIEW

**Comment by CheffieGithub** [comment]
I think `shoes/swat/captain` and `gloves/captain` would be better paths than capX

**Comment by Glamurio** [comment]
> I think `shoes/swat/captain` and `gloves/captain` would be better paths than capX

Good point.

**Comment by DimWhat** [comment]
Personally I think giving the gloves disarm prot is a bit much. I do like them being protective enough to pat out flames and being insulated though.

**Comment by BatElite** [comment]
Personally I feel if the gloves/shoes on the sprite were bothering folks, we might as well just be rid of them instead

**Comment by DimWhat** [comment]
Just checked, the monkey version of the blue captain has a lot of white around it for some reason. Might wanna fix that in the DMI

**Comment by Garash2k** [comment]
Captain not starting with insuls is funny though. Whether or not a captain tides insuls at the start of a round is a fun test of character, and it's extra funny if they use the bridge's unsulated gloves!

**Comment by Tarmunora** [comment]
Atomize this.
Split the repaths and the new content into different PRs

**Comment by Glamurio** [comment]
> Atomize this.
> Split the repaths and the new content into different PRs

I've undone the repaths from this PR and atomized them to #15665

**Review by Tarmunora — CHANGES_REQUESTED** [review]
`icon_state` sprite for the gloves is pretty bad

**Review by Tarmunora — CHANGES_REQUESTED** [review]
Additionally with this change captain armor should no longer hide gloves/shoes from examine

**Comment by Glamurio** [comment]
Updated glove sprites by Piesuu
image

**Review by Tarmunora — APPROVED** [review]

**Comment by TobleroneSwordfish** [comment]
!merge_upstream

**Pull request merged**
