### PR TITLE
Syndicate Tricks and Traps box

### PR DESCRIPTION
**Pull request by flappybatpal**
[FEATURE][WIP][WIKI]

## About the PR 
1. Adds a pair of decoy grenades. Each grenade has a seven second fuse and then plays the sounds of a fairly realistic, randomised, two part gunfight before causing either a fake explosion shockwave or a large puddle of blood.

image

https://user-images.githubusercontent.com/70909958/107638030-ed61b680-6c66-11eb-9436-90a8ca4e0145.mp4

2. Bear traps! There are space bears after all. Safety first!

image

## Why's this needed? 
The Syndicate Tricks and Traps box contains three different tools for traitors to cause headaches with.

### CODE REVIEW

**Comment by zjdtmkhzt** [comment]
I feel like a real gunfight usually has more shots fired in close succession? And it sounds a bit uniform, maybe make the delay rand() rather than pick()?

**Comment by pali6** [comment]
Agreed with zjdt. Note that calling `rand()` without arguments generates a random decimal number in range 0-1, this might be useful after some scaling. (E.g. `sleep((rand() * 0.3 + 0.1) SECONDS)`.)

**Comment by AwkwardDryad** [comment]
this is such a wonderful concept! i love mindgames soooooo much! 😍

**Review by ZeWaka — CHANGES_REQUESTED** [review]
linters, and WIP label

**Comment by Gannets** [comment]
I want these bear traps so bad.

**Comment by flappybatpal** [comment]
Unfortunately I've cursed myself by trying to make a spider mine that doesn't suck.

**Pull request closed without merging**
