### PR TITLE
Add the myhouse good dog to detnet room

### PR DESCRIPTION
**Pull request by monkeymilesmoo**
## About the PR 
The det net room reminded me of the ending from myhouse.wad so obviously the sleepy dog must be added.

goodboy

## Why's this needed? 
The crab in there just wasn't cutting it for detective moral support.

## Changelog 

```changelog
(u)monkeymilesmoo
(+)The detective gained a virtual friend
```

### CODE REVIEW

**Comment by colossusqw** [comment]
> Where is this sprite from?

The sprite is from a DOOM custom map called myhouse.wad, i'm not sure we currently have permission to use it but if we do this would be pretty cool nod to a fantastically told story. Good doggies are good doggies :).

**Comment by monkeymilesmoo** [comment]
Yeah I'm not sure about the permission of using it, but nobody really knows who the creator of the map actually is 😅. And as already said it's from a doom map called myhouse.wad

**Comment by monkeymilesmoo** [comment]
https://www.doomworld.com/forum/topic/134292-myhousewad/

**Comment by monkeymilesmoo** [comment]
Apparently the dog sprite comes from this pull request to gzdoom: https://github.com/coelckers/gzdoom/pull/374

**Comment by monkeymilesmoo** [comment]
Nvm there is a txt file in the zip that says media from the mod is "free to copy and redistribute the material in any medium or format."

**Comment by pali6** [comment]
I don't think it fits much

**Comment by monkeymilesmoo** [comment]
Specifically since it _is_ in vr doesn't that mean it can be whatever? I'm not really sure what the limits of a virtual created space are

**Comment by pali6** [comment]
I believe even in VR we want to sort of keep our visual style. But that's just my opinion, maybe other devs are ok with this.

**Comment by flrsh** [comment]
> I believe even in VR we want to sort of keep our visual style. But that's just my opinion, maybe other devs are ok with this.

Agreed.

**Comment by ZeWaka** [comment]
Going to close this after the dev feedback, as it doesn't seem like it's quite a good fit stylistically. I think we'd be more open to some other reference, or a different sprite more in-line with the game.

**Pull request closed without merging**
