### PR TITLE
Makes detective require 15 rounds before playing.

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Title

## Why's this needed? 
For purposes of comparision, 30 rounds are required before you can play as a security officer, 5 rounds are required to play as before a security assistant. The security job that spawns with lethals should not have a shorter time lock then the job that just gets a barrier and some flashes.

## Changelog

```changelog
(u)Ikea
(*)15 rounds are now needed to be able to play as detective.
```

### CODE REVIEW

**Comment by MetricDuck** [comment]
25 rounds @ 50 minutes is 20.8 hours. Locking content behind 2.5 whole workdays of time is bad for the game IMO.

**Comment by ThatFiveGuys** [comment]
Detective has lethals, honestly personally id put it above security round lock for that reason alone (only other sec roles that have lethals are whitelisted) however thatd be contreversial. Personally im done with a non antag dect filling me with lead and me dying, cant say its fun.

**Comment by rmeaper** [comment]
Although I do hate dets who are judge, jury, and executioner, I think that 25 rounds is way too long of a time. A judge det has less game ruining potential than a shitsec. I feel 10 rounds is more appropriate. That's more than enough time to filter out most of the people who just play det for the gun. If you play 10 rounds to be a judge det, then you'll probably play 25 rounds to be a judge det.

**Comment by ThatFiveGuys** [comment]
Detectives can literally shoot people to death on the spot unlike security. The potiental for harm of detectives is honestly greater for detectives because at least when tased youre still alive.

**Comment by rmeaper** [comment]
I still think the 10 round limit is enough, it stops people from other servers hopping on just to shoot people, and new players with only 10 rounds of experience can't do enormous amounts of damage. The worst experience I've had with a det is when he executed me for a minor crime after sec cuffed me. Sec cloned me and it was ok. The worst experience I've had with a shitsec is being stun batoned for a minor crime, then put in the gibber. Detectives are limited by security cooperation, shitsec are much more annoying. 

I also worry that putting roles behind round limits lead to a sense of elitism, although I agree that the detective definitely needs one. 20 hours is too much of a limiter for new players. 

Maybe make a forum post to get more peoples opinions, I might be in the minority.

**Comment by UrsulaMejor** [comment]
Locking content behind timers is an absolute last resort option.

**Comment by Vaskritaya** [comment]
On one hand, I understand the arguments that secoffs should be locked while det shouldn't. Secoffs do arrests, and detectives don't, in theory. Secoffs are the ones responsible for if someone's round is enjoyable or not some of the time, det isn't, in theory. So on and so on.

However, the fact remains that detective, as a security job, has less time restrictions than secass despite having more gear, more access, and more personal influence. At the very least, the job that is immediately handed a gun and handcuffs should require, at least, the same amount as secass, minimum.

**Comment by Gannets** [comment]
If there should be a timer, I'd be happier seeing it have parity with SecAss. A global "play this long to prove you aren't inherently bad" timer.

**Comment by ThatFiveGuys** [comment]
Really wouldnt make sense for parity with sec ass for two main reasons 1. Potiental for harm, the potiental of the harm a sec ass can do is far greater then what a detective can do. Security assistants only have flashes and barriers, while detectives have a pretty high damage gun + stun rounds. 2. Security assistants are for learning while detective assumes youve already learned the sec basics. Sec ass’s are there so you can be leaned into learning sec, detectives are tossed into the world with a gun and told anyways stop crime or something i guess. Id much prefer to see people play sec ass before dect instead of the other way around. 

So uhh yeah, lowest amount id be “okay” with for a round lock for detective would probably be in the terms of 15 rounds. Personally considering the fact that detective has a gun (and when you got a hammer everything is a nail), id put the round lock pretty high at 25 as a good amount.

**Comment by Momoberry** [comment]
> 
> 
> Detectives can literally shoot people to death on the spot unlike security. The potiental for harm of detectives is honestly greater for detectives because at least when tased youre still alive.

Being shot on the spot is generally more fun than being cuffed and dragged around for 10 minutes by a sec off. We have a very fast cloning system on goon. Still, we did see just how many people were shitters on the temp servers with no timelock as sec though. I think there's a valid point to having sec be time-locked, even detective. Or even just a round of each department or something, to understand basic gameplay functions. 

I had security officers asking me where escape was and how to charge their tasers and batons yesterday and that really doesn't fill me with confidence. Its not very fun having your entire round shifted and messed around with cause a new sec off didn't understand something and made a wrong play and now you're cuffed and dragged around by someone who doesn't even know how to uncuff you.

**Comment by ThatFiveGuys** [comment]
Never be afraid to involve someone else, if a sec off is just dragging you around, just say something over comms. Like at most its a 5 minute inconvinence instead of a round ender.

**Comment by Momoberry** [comment]
> 
> 
> Never be afraid to involve someone else, if a sec off is just dragging you around, just say something over comms. Like at most its a 5 minute inconvinence instead of a round ender.

I do agree, but sec players have a mentality of ignoring people they've caught. But i feel like most of it is cause the verbal vomit of a stunned lizard is obnoxious to read, unfortunately.

**Comment by ThatFiveGuys** [comment]
That can suck and can definitely be annoying, however at least me personally being inconvinced for a small portion of the round is far less annoying then being filled with lead by a non antag and taken out of a round for the grand crime of farting on someone

**Comment by vocalpocal** [comment]
this is getting out of hand

**Comment by UrsulaMejor** [comment]
> 
> 
> That can suck and can definitely be annoying, however at least me personally being inconvinced for a small portion of the round is far less annoying then being filled with lead by a non antag and taken out of a round for the grand crime of farting on someone

Adminhelp

**Comment by ThatFiveGuys** [comment]
I do, iirc my most recent ahelp is exactly me ahelping that! However, the issue is this keeps on happening. 

To go on a tangent here, if we look at what security is given, only NTSO and HoS are given things that are directly lethal roundstart. What's in security's arsenal is only tasers, batons, no lasers or the like. Even in the armory, the only lethals security gets are fire weaponry that's primarily there for blobs, one grenade thats purpose is primarily dealing damage (shrapnel which is suited for usage against nukies and not individuals), and two phasers (which do low damage). The reasoning I've always heard for this is less out of balance, but that we can only trust whitelisted people with lethals. Giving any security officer ready access to lethals would have them constantly overreacting and using them inappropriately, overall not being fun for others.

If we give a first time player a gun, tell them stop criminals, what do we expect them to do besides shoot people with it. If we can only trust whitelisted security members with lethals, why should we trust a first time player in the security department with them. Now of course, we could remove the lethals the detective spawns with and have them be from hacked SecVends only, however I think both you and I wouldn't like this. As my experience as a player, I have seen relatively far more detectives commit shitty actions then security officers, and in my view a large aspect of this is due to the fact we're trusting absolutely new players with no clue what's going on with not lethalling people for minor crimes.

Due to several devs disagreeing with this, Im lowering this down to 15 round lock. This is half of a security officers round lock. Ideally, theyd play a few rounds of security assistant first, get the idea you're not supposed to gun down people for minor crimes, then play detective. Its important to note that currently due to a lack of cloud saves, security officers do not have a round lock. While I am not an admin, I speculate that there has been much more ahelps regarding security officers then before the tide. While a large aspect of this is due to the tide, lots more new players, I dont think that's the full story. When we get cloud saves back up running, Id request you take note of how the rate of ahelps regarding security officers changes, after all, how do we expect an absolutely new player to deal with such a complicated job as security?

**Comment by flappybatpal** [comment]
I think this is reasonable. Getting a gun and sec-ish access is kind of a big deal in your first few rounds. Would be easy to think you can shoot people with lethals. It's true that sec has higher responsibility and requirements so 10-15 sounds about right.

**Pull request closed without merging**
