### PR TITLE
Adds color customization and talk sounds to the roach mutantrace

### PR DESCRIPTION
**Pull request by Lythine**
[FEATURE]

## About the PR 

This allows roaches to change their skin and eye color. Roaches also now make chirps when talking rather than using humans' talk sound. 

colorfulroaches2

## Why's this needed? 

Roaches were previously pretty boring. They had one appearance and one appearance only; not even hulk made them change color. This changes that. Additionally I noticed that roaches have the same talk sound as humans so I thought it'd be a nice change to make as well. 

## Changelog

```changelog
(u)Lythine
(*)Adds skin tone customization and talk sounds to the roach mutantrace.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Not a huge fan of them being able to be colored any color, I'd honestly prefer detail markings that you could color.

**Comment by virvatuli-gh** [comment]
`roach.ogg` and `roach_ask.ogg` have some highs that are very shrill and pretty hard on the ears. Consider making them more to the same levels as `roach_exclaim.ogg` which is perfect!

**Comment by Flaborized** [comment]
I like the eye color, but I think the actual body color looks bad and doesn't really fit 'cockroach' at all. Some kind of variety in appearance is cool but they absolutely don't fit being Neon Rainbow Multicolor Spectacular imho

**Comment by Lythine** [comment]
Alright, I've made the body color based on the skin tone setting rather than hair color and updated the preview image. That allows for a fair bit of customization while still being cockroach-like in color.

**Review by ZeWaka — APPROVED** [review]

**Comment by virvatuli-gh** [comment]
Audio sounds perfect now!

**Comment by Flaborized** [comment]
I still think it's a bit of a visual downgrade as there's no longer a two-tone color scheme (between the darker brown and much lighter brown), or at least there's much less contrast between the two. And the hue shifting is gone 😢 But otherwise that's better yeah

**Comment by Kyle2143** [comment]
What is the colour shift range on these skins? They should be much more drab than lizards.

**Pull request merged**
