### PR TITLE
Airlock packet control fixes

### PR DESCRIPTION
**Pull request by Nexusuxen**
[FIX] [STATION SYSTEMS]

## About the PR 

Airlocks now make noises when bolting and unbolting from packet commands. Airlocks can also no longer be bolted/unbolted via packet if the bolt control wire is cut.

## Why's this needed? 

Bugfix. Bug bad. I squash :)

## Changelog 

```changelog
(u)Nexusuxen
(+)Airlocks now make sounds when un/bolted via packets. Can no longer toggle door bolts via packet if bolt wire cut.
```

### CODE REVIEW

**Comment by soleilan** [comment]
weird that if its already bolted open and you do it via packet it unbolts and bolts again but I guess thats how it worked before too

**Review by soleilan — COMMENTED** [review]
weird that if its already bolted open/closed and you do it via packet it unbolts and bolts again but I guess thats how it worked before too, otherwise seems to work fine 👍

**Comment by Nexusuxen** [comment]
That's only for secure_open and secure_close, which are intended to *make* it open or close, so it does a check to see if it's already bolted first. The regular open and close don't do that afaik

**Comment by soleilan** [comment]
yeah I just found it weird that if you tried to secure_open while it was already bolted open it'd just make two noises. could probably check if the door is already bolted open before executing a secure_open, but it's not that big of a deal, I was just testing all edge cases

**Comment by Nexusuxen** [comment]
oh shit it does? hold up lemme fix, thank you!

**Comment by Nexusuxen** [comment]
Update:
Fixed the described edge case; doors will no longer try to secure_open or secure_close if already bolted open/bolted close respectively. Also added `src.` before some variables and proc calls as per guidelines.

**Pull request merged**
