### PR TITLE
Allow SecHUD flags to be set on RecordTraks

### PR DESCRIPTION
**Pull request by FlameArrow57**
[GAME OBJECTS][FEATURE][QoL]

## About the PR 
This PR allows security RecordTraks to be able to have a sechud flag that can be set, through a radial menu option, that will be applied whenever you scan someone.

If the RecordTrak is dropped the flag is reset.

image

In the examine text for a RecordTrak, it will now also show the arrest mode and sechud flag.

## Why's this needed? 
RecordTraks allow you to set an arrest status, but they aren't able to set a sechud flag to show the reason why.

## Changelog 

```changelog
(u)FlameArrow57
(+)Security RecordTraks now have the ability to set a SecHUD flag as an option. Upon being dropped the flag will be reset.
(+)RecordTraks can now be examined to see their current arrest mode, as well as any SecHUD flag set.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Could maybe put the flag icon in the center to signify that it's different from the other options. Also is there a reason for the reset on drop? Not much else works like this, and you could just reset by entering a blank flag.

**Comment by FlameArrow57** [comment]
Idk, I was thinking the icon is big enough that it looks a bit off not being able to see yourself?

image

Reset on drop was more intended so that you don't hand it off to someone with them picking it up and forgetting to reset the flag

**Comment by TobleroneSwordfish** [comment]
I think having the flag in the center is definitely better, ideally it wouldn't be on the radial menu at all since it's entirely separate from the other options, but I can't really think of another way to input it.

**Comment by FlameArrow57** [comment]
Okay done

**Pull request merged**
