### PR TITLE
Added two random rooms: "tomato" and "plushbridge" 

### PR DESCRIPTION
**Pull request by Creathian**
## About the PR 
This PR adds two new random rooms to the pool of existing random rooms. The "tomato" room is a 3x3 prefab and "plushbridge" is a 5x3 prefab. The new rooms use existing assets, so I doubt too much will be impacted. (unless I made some huge mistake i'm new aaaa)

**Plush Bridge**
image

**Tomato**
image

## Why's this needed? 
More random room variety is always fun!

### CODE REVIEW

**Comment by DimWhat** [comment]
cute

**Comment by WALPVRGIS** [comment]
Aw, cute idea. The singuloose plush is actually a donator plush, might want to ask the player if they're cool with this use! (see #5644)

**Comment by Creathian** [comment]
> Aw, cute idea. The singuloose plush is actually a donator plush, might want to ask the player if they're cool with this use! (see #5644)

Oh! Thank you for letting me know, I had no idea! I'll see if I can get in touch with them and ask for permission to use it.

**Comment by Creathian** [comment]
> Aw, cute idea. The singuloose plush is actually a donator plush, might want to ask the player if they're cool with this use! (see #5644)

Permission has been granted!
image

**Comment by Sord213** [comment]
Changelog entry is unnecessary for a couple random rooms on their own.

**Comment by Creathian** [comment]
> Changelog entry is unnecessary for a couple random rooms on their own.

Makes sense! This is my first time contributing, so I wasn't too sure.

**Comment by flrsh** [comment]
The plush bridge is adorable. Congrats on your first PR! 🎉

**Pull request merged**
