### PR TITLE
Shift around Oshan security a bit

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Move the HoS announcement computer into the HoS office 
Move the rechargers and phone off the main sec table to make space for disks and pinpointers
Replace spread out "desk" officer spawns with assistants, officers spawn around main table
Push sec area one tile into armory to expand walkable area
Expand sec table for more space
image

## Why's this needed? 
Im paranoid every time I announce something as HoS on oshan that someone will grab my ID
There is no space for pinpointers and disks unless I want to go grab a decon tool and start destroying stuff
the main walkway from the front to back of sec was cramped at the entrance only being a 1 tile corner, now its bigger

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Looks good, one tiny nitpick: I'd rather keep the disposal chute as a full one because that makes it more obvious as an escape route (which is a good thing, I think?)

**Comment by JORJ949** [comment]
> Looks good, one tiny nitpick: I'd rather keep the disposal chute as a full one because that makes it more obvious as an escape route (which is a good thing, I think?)

Yeah good point, I just put it on the wall because the room already feels cramped (also its a pretty rubbish escape considering disposals is right there)

**Review by TobleroneSwordfish — APPROVED** [review]

**Review by MyNameIsRomayne — CHANGES_REQUESTED** [review]
image
Is this there in the final changes? Looks like you forgot to rotate/edit this lamp by the entrance to main security, it's floating.

**Review by MyNameIsRomayne — APPROVED** [review]
Disregard, I apparently didn't know lights auto choose dirs now. This looks cool!

**Comment by MyNameIsRomayne** [comment]
image

**Pull request merged**
