### PR TITLE
Underwater escape pods!

### PR DESCRIPTION
**Pull request by j-awn**
[MAPPING] [SPRITES] [INPUT] [FEATURE]
## About the PR 

Oshan gets some fancy new underwater escape pods! Oshan's escape hallway is enlarged to accommodate the new escape pod launching bays.

## Why's this needed? 

I always get pissed off when I missed the shuttle on Oshan, because there's no way to get to the shuttle if you miss it. No more!

## Changelog

 
```
(u)Jawns:
(*)New underwater escape tanks offer a convenient and safe means of evacuating Oshan

### CODE REVIEW

**Comment by Sovexe** [comment]
MapDiffBot isnt working currently, please include a screenshot of the changes

**Comment by j-awn** [comment]
kj1axv3

**Review by flrsh — CHANGES_REQUESTED** [review]
Both mbc and I really like the idea and the sprites for the underwater escape pods! However, we're not a fan of the extra space in the escape hall, as it feels unnecessary. To quote mbc, `its Very Intentional that the only way to 'safely' board escape on oshan is to walk down a long hallway that you cannot see the end of`. In other words, it's intended that it funnels players into hazards and is something a traitor can take advantage of. In terms of reorganizing where the escape pods would be, maybe you could put two on each side of the hall? And if you wanna add a cafeteria-esque type thing, we'd prefer you expand the current escape lobby instead of the hall.

**Comment by j-awn** [comment]
> Both mbc and I really like the idea and the sprites for the underwater escape pods! However, we're not a fan of the extra space in the escape hall, as it feels unnecessary. To quote mbc, `its Very Intentional that the only way to 'safely' board escape on oshan is to walk down a long hallway that you cannot see the end of`. In other words, it's intended that it funnels players into hazards and is something a traitor can take advantage of. In terms of reorganizing where the escape pods would be, maybe you could put two on each side of the hall? Like in [this room](https://cdn.discordapp.com/attachments/182254397999415296/775592859674869780/unknown.png). And if you wanna add a cafeteria-esque type thing, we'd prefer you expand the current escape lobby instead of the hall.

I didn't really want to add the cafeteria-esque thing at first. The space just looked bad without it. I could add the two sided escape pod bays if I extended the hallway out significantly- do you think that would make sense?

**Comment by flrsh** [comment]
> I didn't really want to add the cafeteria-esque thing at first. The space just looked bad without it. I could add the two sided escape pod bays if I extended the hallway out significantly- do you think that would make sense?

Extend a couple tiles? Yeah I think that'd make a lot of sense!

**Comment by j-awn** [comment]
oshan_pods

**Comment by j-awn** [comment]
oshan_windows

**Review by flrsh — APPROVED** [review]

**Pull request merged**
