### PR TITLE
Removes burst mode from tasers

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Taser burst has been removed completely from the taser, alongside all the related sprites and code.

## Why's this needed? 
I was initially conflicted on if this should nerf it or remove it. I think removing it would be the best. The burst mode makes the taser shotgun basically completely irrelevant. The burst ability of shotgun is only useful close up, unlike burst. While the taser shotgun is more energy efficent, you can just rely on pointblanks with the taser in order to get shots in completely efficently, or if youre good count on your aim.  Even from a balance perspective, I dont think itd be possible to get burst to a good state. Increasing the energy cost wouldnt change much, insta-stunning someone is a much higher reward then running out of taser energy and having to use your baton. Making the burst mode no longer one shot stun I feel would just make the mode never be used. 

## Changelog

```changelog
(u)Ikea
(*)Taser burst has been removed from the taser.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
!merge_upstream_master

**Comment by ThatFiveGuys** [comment]
!merge_upstream

**Comment by flrsh** [comment]
Copy pasting from #9558 -
> I actually think burst fire is fine, too, since it's a gamble (and it's not more cost efficient either - it costs 75, while regular taser shots cost 25).
If the taser shotgun sucks, it should be improved.

**Comment by nefarious6th** [comment]
i dont see this getting merged, but im not against the idea.

**Comment by ThatFiveGuys** [comment]
> Copy pasting from #9558 -
> 
> > I actually think burst fire is fine, too, since it's a gamble (and it's not more cost efficient either - it costs 75, while regular taser shots cost 25).
> 
> If the taser shotgun sucks, it should be improved.

I think taser shotgun is honestly overpowered right now, its just taser burst mode is even more overpowered. Having a one handed long and short ranged insta stun will always outclass the two handed short ranged insta stun, if you made it cost 150 pu or whatever, people would just pointblank with the taser instead of pointblanking with the shotgun.

**Comment by ThatFiveGuys** [comment]
To put it in a shorter way, the downside of missing has penalties doesn't matter when you can easily arrange things to where you never miss (aka getting next to someone, pulling out taser, and pointblanking).

**Comment by flrsh** [comment]
> its just that burst inherently fills the same niche as shotgun due to pointblanking

"These two modes have similar effects when you shoot them at pointblank" != "these two modes inherently fill the same niche". There are more ways to use and shoot a gun than just at pointblank. 

I can appreciate wanting to get rid of (relatively) longer instastuns, but if your issue is with pointblank, I'd rather you rework that than remove the entire mode itself (especially when most people use it at range).

**Comment by ThatFiveGuys** [comment]
My issue isnt with pointblanking, I think pointblanking is good, its just that in this case due to pointblank, since shotgun tends to be used pointblank due to being a shotgun, and taser burst still can be used in pointblank and burst is actually good at long range, no matter how many nerfs you slap onto it relating to range or power consumption, the best case scenario is you make burst into a one handed taser shotgun where its used in the way of get next to antag then pull out gun and shoot them (doing it like this is basically impossible to miss). Pointblank makes this process easier but it isnt what makes this process possible.

**Pull request closed without merging**
