### PR TITLE
Underwater prefab/area: Marijuana Trench

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT]
## About the PR 

Adds a new water Z5 prefab with a dank crevice, in which weed of both the sea and terrestrial varieties can be found, the latter within a small abandoned structure. Also slightly modifies the pitfalls that were previously only for Polaris to be more configurable, and adds suitably configured variants for said prefab.

Currently configured for a 35% spawn chance.

## Why's this needed? 

Tarm had an idea and I decided to explore it. Not strictly needed, but could be a fun thing to have.

### CODE REVIEW

**Comment by ZeWaka** [comment]
dank

**Review by Tarmunora — CHANGES_REQUESTED** [review]
not even a single piece of omega weed? 😔

**Review by ZeWaka — APPROVED** [review]
dank

**Review by Tarmunora — COMMENTED** [review]
dank

**Pull request merged**
