### PR TITLE
Merges Robusttin with Spaceacillian

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr removes Robusttin from the game, and with the exception of frog flu adds spaceallin as a cure to the diseases that robusttin otherwise wouldve cured . This also moves the overdose effect of robusttin to spaceacillin.

## Why's this needed? 
Robusttin is just really useless, the only thing it cures is really niche diseases, and spaceallin already fills the niche of generalist disease fixer chem. I think the amount of chemicals medical gets can be overwhelming and this chemical doesnt really have a reason to exist, the overdose effects is fun though so its being moved to spaceacillin.

## Changelog

```changelog
(uIkea
(+)Robusttin has been removed and spaceacillin can now cure The flu and the common cold. Spaceallin now has the overdose effect of Robussttin
```

### CODE REVIEW

**Comment by DisturbHerb** [comment]
you'll make me cry <;(

**Comment by ThatFiveGuys** [comment]
> you'll make me cry <;(

Even more reason to merge this pr

**Comment by Tarmunora** [comment]
mm nah. robustissin has it's place as the chicken soup of medbay

**Comment by ThatFiveGuys** [comment]
> mm nah. robustissin has it's place as the chicken soup of medbay

What does this mean?

**Pull request closed without merging**
