### PR TITLE
Fixes a number of vr related bugs

### LINKED ISSUE #227: Cleaning murderbox deletes the intercom inside
**Describe the bug**
The intercom is deleted by the cleanbot button

**To Reproduce**
1.  Join vr
2. Enter murderbox gear area
3. Enter murderbox itself
4. Press clean bot button
5. See Error

**Expected behavior**
The intercom staying just like the clean and logout buttons

### PR DESCRIPTION
**Pull request by moonlol**
[FIX]
## About the PR 
Fixes murder box clean function from clearing the intercoms placed inside.
Also fixes the ability buttons layering on top of each other.
closes #227  
Also does a few improvements to the cleaner. instead of using 7ish for loops it just uses 2
Fixes having to transform twice in order to become werewolf

## Why's this needed? 
Fixes a number of bugs

### CODE REVIEW

**Comment by ZeWaka** [comment]
Like MBC was saying earlier in discussion, I'm not sure if the button removal is good concerning new players.

**Comment by moonlol** [comment]
Fixed the layering issue while keeping the logout ability

**Comment by moonlol** [comment]
huh seems like bot dont remove tags.

**Comment by ZeWaka** [comment]
neither of these really warrant a changelog

**Comment by moonlol** [comment]
aight

**Pull request merged**
