### PR TITLE
Engineering Grenade Pouch

### PR DESCRIPTION
**Pull request by Saicchi**
[FEATURE][WIKI]

## About the PR 

Adds an engineering grenade pouch that can be dispensed from the engineering clothing vending machine, there are only 3 per machine. 
This pouch can only hold:
- Metal Foam Grenade
- Red Oxygen Grenade
- Firefighting Foam Grenade

The sprite is a simple resprite of the security pouch.

## Why's this needed? 

Allows engineers to use one of their pocket slots to hold engineering grenades and grenades only instead of using a box in their backpack.

## Changelog 

```changelog
(u)DrWolfy
(+)Add engineering station repair grenade pouch to their vendor
```

### CODE REVIEW

**Review by TobleroneSwordfish — APPROVED** [review]
I like this.

**Review by Mister-Moriarty — COMMENTED** [review]
Regarding the sprite, to me it looks too orange to be congruent with other Engineering department items; Kubius, Kusibu#1649 on Discord, sprited a pouch that I believe would be more inline with Engineering's colour scheme.

**Comment by Saicchi** [comment]
That works. I'm not a spriter so I did the bare minimum with mine (make it yellow).

**Comment by NightmareChamillian** [comment]
Honestly, I feel like it'd be better to just have a generalized pouch for tiny, obscure engineering items (like the atmos scanner, light replacer, and APC pinpointer in addition to just the engineering grenades).

As it stands right now, I just don't see any real use for carrying around only engineering grenades, especially in a low quantity. If I'm ever carrying more than one at a time (in the rare instances I'm coming out of engineering to do station repair), I'll use a box, which lets me hold seven as opposed to three. 

I'm not directly opposed to it, but it does seem like a halfway approach to addressing the issue and might not see much use because of its limits. Would love to have a dev chip their two cents in, though.

**Comment by flappybatpal** [comment]
Historically there was push back against more storage items for most jobs.

**Comment by Tarmunora** [comment]
wha.
no. No we are not giving engineers a grenade pouch lmao.

**Pull request closed without merging**
