### PR TITLE
Sleepwalker trait

### PR DESCRIPTION
**Pull request by flappybatpal**
[FEATURE][WIP]

## About the PR 
Adds the Sleepwalker trait which spawns you in a random corridor in your pajamas!

image

## Why's this needed? 
I thought it was funny.

## Changelog

```changelog
(u)Flappybat
(*)Added sleepwalker trait, you slept in and forgot your clothing!
```

### CODE REVIEW

**Comment by flappybatpal** [comment]
This messes with roles with unique clothing (eg captains hat). This could just attempt to equip clothing like most traits but that would fail for a lot of jobs making this rather pointless. I think I can detect that and spawn replacements in the backpack which seems like a satisfactory solution.

**Comment by BatElite** [comment]
As I understand the pajamas are a medal reward currently? Wouldn't that make this "too easy" to get them?

(I think it's Emily who made them available and probably knows more & better, hence the request)

**Comment by UrsulaMejor** [comment]
these pajamas are currently a medal reward. I'm open to the idea of different, slightly less cute pajamas being a trait, but not these.

**Comment by flappybatpal** [comment]
Caro mentioned this, I saw nothing about them in find so I had assumed they were just clothing.

There's the bathrobe but I assume that's a suit layer, is the regular underwear option you can pick in character select available? Boxer shorts would be appropriate./

**Comment by MatheusIsNotAvailable** [comment]
I think it would be better to give the trait pajamas an new clothing sprite, when the pajamas were made there were already ideas to make other variations of them.

**Pull request closed without merging**
