### PR TITLE
Lizards can be selected through character creation

### PR DESCRIPTION
**Pull request by Superlagg**
[FEATURE]
## About the PR 

You can choose to be either a human or a lizard in the character creation menu.

## Why's this needed? 

so box ta can stop playing a fucking human

Also as someone who outright refuses to show up to work without scales and a ssshitty accent, I want to spend my spacebux on other things too. Plus, ever since buying lizard's started being a thing, I've been a bit more pissy about dying and more reluctant to do dumb things, cus it'd mean potentially running out of cash to fuel my dumb space-animal addiction. Which sucks, cus I like dying like an idiot to dumb things!

## Changelog

```
(u)Superlagg:
(*)Removed Reptilian from SpaceBux purchases. Instead, you can choose to be one through character creation.
```
piss

### CODE REVIEW

**Comment by Carbadox** [comment]
I always assumed the point of mutant races being behind Spacebux purchases was to make them unique. Alien species aren't really all that, well, alien if they're common.

**Comment by moonlol** [comment]
> I always assumed the point of mutant races being behind Spacebux purchases was to make them unique. Alien species aren't really all that, well, alien if they're common.

I agree to this for races like skeleton and cow which are quite unique. But lizards are the most played race (except human obv) so they are already quite common, so i dont see why you'd want to just keep a barrier that is an annoyance to some

**Comment by comradef191** [comment]
While I do love lizards being in character creation, I'd prefer for races such as Cow, Skeleton & Roach, which are mainly joke races and not often played, to remain as a Spacebux purchase.

**Comment by Superlagg** [comment]
> I always assumed the point of mutant races being behind Spacebux purchases was to make them unique. Alien species aren't really all that, well, alien if they're common.

But lizards are already pretty common, I tend to see several of them every shift, and a lot of them on people I've seen as a lizard on previous rounds.

Also I disagree about aliens being less alien if they're everywhere. To me, alienness is more in how it interacts with the crew, which is largely in the hands of the player. 

> Edit: Races like skeleton and squid (iknowsquidisntinthepr) should definitally not be roundstart pickable, as squids essentially ignore the ocean aspect entirely, and skeletons get a strong omnizine like heal from milk in addition to 2 free trait points (as puritan has no effect).

Squid's not in the PR cus they ~~dont have tails~~ have actual legit advantages on water maps.

Didn't know that milk was _that_ effective on skeletons! Or that puritan doesn't gib them! Definitely taking them out of the PR.

> While I do love lizards being in character creation, I'd prefer for races such as Cow, Skeleton & Roach, which are mainly joke races and not often played, to remain as a Spacebux purchase.

Good point, most of the non-lizard mutants are, for the most part, cool gimmick creatures that aren't supposed to be commonplace, which this would most certainly do. Would also simplify things a lot if it was a simple toggle between human and lizard.

Also, a few really good points brought up on Discord:
> we could also make it so selecting the option in character preferences just toggles auto-buying of that bux item

Keeping the purchase at the end of the round already does that, and lizard players also already buy it if they don't have it. Point is to remove the cost so lizard players don't have to worry so much about dying, and people like me don't feel so bad about murdering lizards. It's expensive, people like it, and I feel that the drawbacks should be strictly IC-based.

> mutantraces are like the only good spacebux sinks we have.
> Well, I mean expensive ones that people consistently buy.

True, but part of that is because buying a mutantrace means you can't buy something else as well. And that we just need more neat expensive things to buy, which I can definitely help with!

> Honestly I think this game shouldn’t be swarming with animal people

Probably wouldn't be swarming much more than it already is. Keep in mind, in exchange for scales and slightly improved dark vision, you're also (supposedly) considered non-human, made a bigger target for people to fuck with, sound like an asshole, and are permanently bald.

> Higher cost “snake” option which is just a limbless lizard

planned

> we don't want to give people advantage for spacebux

> And lizard people get free infravision too
> That’s a point costing trait otherwise

I could make it deduct trait points, or rework the lizard's mild nightvision into something else, like impaired thermoregulation or something.

**Comment by moonlol** [comment]
>  > Edit: Races like skeleton and squid (iknowsquidisntinthepr) should definitally not be roundstart pickable, as squids essentially ignore the ocean aspect entirely, and skeletons get a strong omnizine like heal from milk in addition to 2 free trait points (as puritan has no effect).

> Squid's not in the PR cus they dont have tails have actual legit advantages on water maps.

> Didn't know that milk was that effective on skeletons! Or that puritan doesn't gib them! Definitely taking them out of the PR.
Puritan doesnt gib anyone anymore, skeletons are unable to be cloned so its essentially the same result in the end for both (no successful clone)

**Comment by Ley-bunned** [comment]
There's no harm in this PR and lot of people would be very happy if they didn't have to spend all their spacebux on being a lizard.

**Comment by Superlagg** [comment]
Okay now instead of every spacebux mutant being selectable, its now just a toggle between human and lizard.

**Comment by GoldenKeyboard** [comment]
Could you also change it so that cloners always copy over your race regardless of genetic analysis? I've immediately suicided and DNRd because of my refusal to play as not my race

**Comment by Gannets** [comment]
Makes good gameplay sense, but has some fairly big lore implications.

**Comment by Superlagg** [comment]
Im gonna close this cus even tho it works, it sucks and is better handled thru traits.

**Pull request closed without merging**
