### PR TITLE
Feature/pop extended jobs

### PR DESCRIPTION
**Pull request by Adharainspace**
[ENHANCEMENT]
## About the PR 
this makes it so that if theres more than the set amount players (65 as of right now but u can change it) in the lobby pregame, it enables a bunch more jobs
also theres a toggle to make it "fuzzy", so it can trigger between 60 - 65 (or 5 - the number)
heres a count of the standard job counts with this pr: 

- secoff = 7 (vs 5 previously)
- roboticist = 4 (vs 3 previously)
- scientist = 7 (vs 5 previously)
- med doc = 8 (vs 5 previously)
- con worker = 2 (vs 1 previously)
- qm = 5 (vs 3 previously)
- eng = 7 (vs 5 previously)
- chef = 3 (vs 1 previously)
- botanist = 6 (vs 5 previously)
- chaplain = 2 (vs 1 previously)
- clown = 2 (vs 1 previously)
total base jobs (- staffies) = 69 (vs 53 previously)

also, i add all the jobs that have a random chance to be in and all the jobs that show up only on certain days of the week to 
a pool, then pick random jobs from that pool for a total of 19 gimmick jobs also being available (which is 24 * 0.8 rounded)

final results:
image

also all these nums are easily adjustable, and please yell at me for bad code, and all that standard stuff

also i did a tiny refactor of the random jobs and just made them do that stuff in the job controller instead of on the jobs individually

also i made medical doctors spawn with medical belts, over concerns that there wouldnt be enough of those to go around.

## Why's this needed? 
 to try to cut down on the whole "theres 36 staff assistants oh god" problem that we've been seeing a lot with highpop. 
also it gives people more to do, so hopefully they can get the jobs they want with some extra slots and more gimmick jobs. 

## Changelog

```
(u)adharainspace:
(*)if there's 65 or more people in the pregame lobby, a bunch of additional job slots will be unlocked.
```

### CODE REVIEW

**Comment by Ley-bunned** [comment]
I can't wait to abuse 4 lawyers every round. A Good PR.

**Comment by jan-antilles** [comment]
Yes please!! This will be a huge help, especially on the RP server.

**Comment by Adharainspace** [comment]
i screwed up the title sorry

**Comment by Adharainspace** [comment]
replaced the image bc of a few inaccuracies

**Comment by Adharainspace** [comment]
people mentioned that meddocs might not have enough belts. ill update this pr with a solution in a bit

**Comment by Adharainspace** [comment]
just cleaned up some dumb comments / commented out code i left in

**Comment by Adharainspace** [comment]
might close this in favour of a population cap instead. seems kinda redundant idk. ill sleep on it

**Comment by Adharainspace** [comment]
yea ditto above

**Pull request closed without merging**
