### PR TITLE
Improve surgery by better informing the user

### PR DESCRIPTION
**Pull request by Crystalwarrior**
## About the PR 
Improves flavor text and feedback for surgery to better inform the surgeon, stemming from lengthy discord discussion and [this topic](https://forum.ss13.co/showthread.php?tid=17499)

## Why's this needed? 
current surgery needs a whole bunch of tiny changes to be a better and more enjoyable system that can be better grasped by players new to it without code diving. Failure chances especially are the poorest explained part, and the current wiki guides fail to put due attention as to why your steps might fail. This PR aims to remedy the issue by putting the reason why you failed at the forefront so there is no confusion that you must re-attempt the step and you have a way to reduce the fail chance.

## Changelog

```changelog
(u)Crystalwarrior
(*)Surgery gives better feedback on why your current step failed (being drunk, patient is awake, etc.) and informs you to reattempt your step. Confusion flavortext (making wrong steps) also has a 50% chance to tell you you're wrong.
(+)Major damage surgery screw-ups now have unique flavor text with no overlap with minor damage screw-ups.
```

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
I hate surgery code being stuck in 1 giant ass code file with 0 modularity and shittons of copy-pasted code, but making an overhaul of that mess is outside the scope of this PR.

**Comment by Momoberry** [comment]
Would like to see surgery fails have similar text to certain drug overdoses, MSG, etc,, where it's in large, bolded coloured (probably red) text if it's severe. I think a lot of the issues with clarity, not just in this PR either, come from almost all of the reaction messages in the chatbox are all the same format, font and size. The only real difference is the colour, and that can get swooped up fast with the sea of messages. Scope creep, but something that I think would benefit the core issue that this PR is apart of with missing text queues.

**Comment by Crystalwarrior** [comment]
> Would like to see surgery fails have similar text to certain drug overdoses, MSG, etc,, where it's in large, bolded and coloured (probably red) text if it's severe. I think a lot of the issues with clarity, not just in this PR either, come from almost all of the reaction messages in the chatbox are all the same format, font and size. The only real difference is the colour, and that can get swooped up fast with the sea of messages. Scope creep, but something that I think would benefit the core issue that this PR is apart of with players missing text queues.

Honestly doable! Just give me an example of an OD message you mean and I can copy its formatting into this pr

**Comment by Momoberry** [comment]
Here's some grabs from the code for examples. 
Enriched MSG https://i.gyazo.com/b99809b2e874e41fd4a1021d8df227e5.png, 
which produces https://i.gyazo.com/f7158ff87e5de48ef66bf947707a6d5a.png

Bath Salts https://i.gyazo.com/8bfe7a64578583d52c5cf5439b9c5f46.png.
which produces https://i.gyazo.com/03e54fe9fa7acbaef1e215dc0256c0b5.png

LSD https://i.gyazo.com/0e6a9a8041ecfe4001de875670f738f8.png,
which produces https://i.gyazo.com/8b7f617a3238225d9e1de0bcc36ad338.png.

I would've put them in raw text, but uh, i'm not sure how to format it while keeping the proper spacings, plus github wants to make it actually run in the chatbox.

**Comment by Crystalwarrior** [comment]
New formatting

dreamseeker_3DX1D6eOSJ
dreamseeker_AujEvrnX1T

**Pull request closed without merging**
