### PR TITLE
Pod Wars | You can no longer pick up enemy armor.

### PR DESCRIPTION
**Pull request by Zonespace27**
[QoL]
## About the PR 
This PR adds a feature not dissimilar to what currently happens, in Pod Wars, when you pick up enemy PDAs or radios. That being, it "explodes" then gets deleted.

## Why's this needed? 
Disguising as the enemy team is not a good thing, since the antag overlays for your team are notoriously finnicky, and have led to multiple teamkills, both by and to me. Also, in my opinion, you shouldn't be able to do this in the first place, since this is a team vs team PVP mode where you should be able to trust the people who appear to be on your team.

### CODE REVIEW

**Comment by DimWhat** [comment]
So to be clear, this stuff doesn't explode outside of podwars right?

**Comment by Zonespace27** [comment]
> So to be clear, this stuff doesn't explode outside of podwars right?

It does not.

**Comment by Kyle2143** [comment]
Hmmm. I wasn't aware of an issue with the antag overlays updating poorly. In the tests I've seen it's been responsive. But yeah, this makes sense too, they shouldn't be wearing enemy armor. Though I did like people stealing the commanders' hats as a trophy.

**Comment by Kyle2143** [comment]
I'm going to merge this at least temporarily until I have a chance to re examine that antag overlay code. It's ugly and expensive, but I thought it was faster than it apparently is. The issue is probably with having so many people to draw images for, but if it's working correctly then that still doesn't really explain it taking minutes to run.

**Pull request merged**
