### PR TITLE
Fix cheesewheel recipe only needing a single cheese

### PR DESCRIPTION
**Pull request by thegrb93**
## About the PR 
Fixes only needing a single cheese to make a cheesewheel

## Why's this needed? 
Fixes: #11887
Fixes: #10598

### CODE REVIEW

**Comment by t-toasted** [comment]
Although initially the cheese wheel was intended to require multiple cheeses, upon hearing feedback that having chef be able to make infinite cheese without cheese smoke could be good, I personally didn’t fix it because I think it’s very funny this way. But if it’s a balance issue then sure

**Comment by thegrb93** [comment]
Less a balance issue and more that it's overwriting other recipes that need cheese.

**Comment by thegrb93** [comment]
I just noticed https://github.com/goonstation/goonstation/issues/10598

I think if you want to keep it as is, amt1 should be 1 instead of 4.

**Comment by frawhst** [comment]
> Will close in a few days if no other devs raise complaints

i'm a liar
But yeah, I'd be fine with `amt1 = 2`? Slow the cheese recursion down slightly and clean up the recipe

**Comment by thegrb93** [comment]
Hang on, I copypasted and botched it

**Comment by thegrb93** [comment]
There we go, fixed a few more

**Review by pali6 — APPROVED** [review]

**Pull request merged**
