### PR TITLE
Standardizes the Pet For the HoP

### PR DESCRIPTION
**Pull request by Wisemonster**
[FEATURE] [CRITTER]

## About the PR 
Places Orwell, the HoP's Atlas pet, across most in-rotation stations.

## Why's this needed? 
Currently, the HoP is the only head that does not have a standard pet, completely lacking any pet on most in-rotation maps. This pr gives the HoP a standard pet, to reduce confusion when the HoP talks about his pet, and to let him have a pet in general.

## Changelog 

```changelog
(u)Wisemonster
(+)The HoP has decided to take his loyal dog Orwell to more stations!
```

### CODE REVIEW

**Comment by Glamurio** [comment]
Justice for Blair.

**Comment by DisturbHerb** [comment]
put blair back!!!

**Comment by Wisemonster** [comment]
Ok, I can either put blair back on Clarion and Oshan, and keep Orwell on every other map, or put Blair on every map, and replace Orwell on Atlas

**Comment by DisturbHerb** [comment]
to replace is to be scariligeous. there must be balance in the universe. 🐶

**Comment by Wisemonster** [comment]
Ok, I returned Blair to Clarion/Oshan, I could also try to even out which dog is on each station, although that would be difficult to maintain when maps enter/leave rotation.

**Comment by Wisemonster** [comment]
Ok, I fucked over this pr real bad, gonna remake it to clear up these conflicts

**Pull request closed without merging**
