### PR TITLE
TGUI React

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

Moves us from Inferno 7.4.11 to React 18.2. This is a big project!
This initiative is the result of dozens of hours of work by the Goonstation team & community.

**Node 20+ is now required if you're using your own node installation**
**If using the easy provided node install, you might need to delete your old cached installation**

## Why's this needed? 

* Align to upstream.
* Switch to entirely Typescript interfaces for bug detection and ease of coding.
* Update to tgui-core, a shared library system that will make it much easier to keep up-to-date and share improvements.
* It'd be nice to just have real hooks. Our implementation is probably the best possible for Inferno, don't get me wrong.
* React is just easier to maintain and easier to read. It's the web dev standard.

## Changelog
```changelog
(u)ZeWaka, Mordent, Garash2k, pgmzeta, Romayne, cringe, and upstream TGUI contributors
(*)A large portion of the game's UI interfaces have been reworked internally. Be sure to report any bugs!
```

<details>
<summary>Old Bug List</summary>

* ~~`Interface ListInputModal was not found.`~~
* ~~Reagent component does not update contents/color/composition - **i think this is due to mordent's weird memo conversion** (Update: it was due to mordent's weird memo conversion)~~
  * ~~It updates eventually / on close/re-open; adding/removing reagents and ejecting the beaker used to be instant but are now delayed~~
  * ~~Chem Dispenser, Drink Dispenser, Reagent Heater/Cooler, Operating Computer, etc.~~
* ~~Genetics console~~
  * ~~When decrypting gene sequence, on pressing "Attempt Decryption" the sequence stays instead of being reset~~
  * ~~Fixed other weird bugs with research crashing~~
  * ~~Research timer countdown for genetics don't update unless re-opened; they show HH:MM:SS~~
* ~~Intercoms show tall box like headsets~~
* ~~Manufacturers have I/Gear icons on new lines~~
* ~~Operating Computer does not show color boxes right (bloodstream reagent colour/blood color)~~
* ~~PIN numbers are small~~
* ~~SMES input/output sliding bars are too wide~~
* ~~ID Modification computer lost all colors~~
* ~~Brig timer time remaining text doesn't update dynamically (updates on re-open)~~
* ~~Switching tabs quickly on Plantmaster Mk4 replaces the window with a Loading dialog often, even with no seeds in the plantmaster~~
  * ~~This is due to ratelimiting on `update_static_data`~~
  * ~~Sidestepped with a better refreshing behaivor~~
* ~~`<TimeDisplay>` is broken and I cannot fix it~~
* ~~For whatever reason, the `IDComputer__DeptBox_color_{colour}` classes do not work~~
* ~~telesci also looks odd~~
* ~~chem dispensers do not show their reagents (reagents component broken probably) - **need mordent on this**, they converted it to a weird form of memo shit that doesn't make that much sense~~
* ~~mini sleeper has a minor formatting error~~
* i might be going crazy here but i swear genetics was green and not teal - this is set SUPER weirdly
- [x] Regular paper doesn't load: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284850050
- [x] artifact paper looks weird, ~~black input boxes~~, light checkbox borders
- [x] pressing enter on paper moves focus out instead of inserting a newline
- [x] setting sliders to specific values by clicking them requires extra clicks?: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284921545
- [x] Color picker doesn't allow dragging to change values: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284944140
- [X] computer3 Terminal interface doesn't autoscroll: #20279
- [X] Terminal UI Enter button doesn't work: #20280
- [X] Map vote background lost it's voted/winner color: #20281
- [X] Chemicompiler text input eats letters: #20284
- [x] Computer Terminal command history no longer accessible through up/down arrows: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284890979

</details>

### CODE REVIEW

**Comment by ZeWaka** [comment]
Closing stops running checks ish

**Comment by ZeWaka** [comment]
lets update the totals lol

**Comment by ZeWaka** [comment]
bug report: the tgui-dev-server spams weird errors into the console when running it

**Comment by pgmzeta** [comment]
* `Interface ListInputModal was not found.`
  * breaks Cargo Transporter
  * breaks `spawn` partial path match
  * Command Teleporter console
* Reagent component does not update contents/color/composition
  * It updates eventually / on close/re-open; adding/removing reagents and ejecting the beaker used to be instant but are now delayed
  * Chem Dispenser, Drink Dispenser, Reagent Heater/Cooler, Operating Computer, etc.
* Genetics console
  * When decrypting gene sequence, on pressing "Attempt Decryption" the sequence stays instead of being reset
  * Research timer countdown for genetics don't update unless re-opened; they show HH:MM:SS
* Intercoms show tall box like headsets
* Manufacturers have I/Gear icons on new lines
  * image
* Operating Computer does not show color boxes right (bloodstream reagent colour/blood color)
  * image
* PIN numbers are small
  * image
* SMES input/output sliding bars are too wide
  * image
* ID Modification computer lost all colors
  * image
* Brig timer time remaining text doesn't update dynamically (updates on re-open)
  * image
* Switching tabs quickly on Plantmaster Mk4 replaces the window with a Loading dialog often, even with no seeds in the plantmaster

**Comment by MyNameIsRomayne** [comment]
I'm going to edit this as I go along and run into issues trying to fix things:
<TimeDisplay> is broken and I cannot fix it
image

**Comment by pgmzeta** [comment]
the reagent display works initially, it just doesn't update at all; if you put a filled beaker in a new machine it shows the reagent display as expected. not sure what would be causing an update failure there but it may be related to the timer update issue?
Screenshot 2024-08-07 105848

**Comment by ZeWaka** [comment]
re: the list modal, yeah i know. it got refactored a bunch but needs porting of some qol features pali made to the new interface, which is a bit of work

**Comment by Garash2k** [comment]
Bug: Regular paper doesn't load, and artifact paper looks weird. I found it searching for todo-react so I imagine y'all are aware, commenting still just in case.

image

**Comment by Garash2k** [comment]
Feature loss: Computer Terminal command history accessible through up/down arrows

Both with the pre-TGUI window and the pre-React one, the up/down keys could be use to retrieve old commands. It was done by adding a `history` prop to TGUI Inputs so naturally it's gone now. It could be done outside the scope of this PR, but I think it shouldn't be forgotten about.

image

I've added a comment in #20280
image

**Comment by Garash2k** [comment]
Bug: setting sliders to specific values by clicking them requires extra click?

It used to be that we could left click a slider, then type a number, and the slider would be set to that value.

But now it's like we enter a weird fake edit mode. After a 2nd click we can start editing the number, but even then it's not selected, we have to delete it.

It's either a component issue or it's implementation. I've notice the bug with both the Manufacturer, Oxygen vendor and Injector belt UIs.

https://github.com/user-attachments/assets/377a4f66-2842-425b-8954-a78f3017f325

**Comment by Garash2k** [comment]
The color picker, used for character generation and the dye vendor, doesn't move the cursor while click dragging it around anymore. It only updates once right after left clicking.

https://github.com/user-attachments/assets/dc65a8ea-8549-401d-8c40-f971ac7517e7

**Comment by Garash2k** [comment]
(big ugh) the chemicompiler's text input sometimes eats letters. There was something challenging about making the text loading buttons work once and once only and the solution doesn't work anymore

https://github.com/user-attachments/assets/d0f401ea-3607-4713-b7b9-94847cf6d878

**Comment by Garash2k** [comment]
I think I should summarize what I found:

- [X] computer3 Terminal interface doesn't autoscroll: #20279
- [ ] Regular paper doesn't load, and artifact paper looks weird: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284850050
- [ ] Computer Terminal command history no longer accessible through up/down arrows: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284890979
- [ ] setting sliders to specific values by clicking them requires extra clicks?: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284921545
- [ ] Color picker doesn't allow dragging to change values: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284944140
- [X] Chemicompiler text input eats letters: #20284
- [X] Terminal UI Enter button doesn't work: #20280
- [X] Map vote background lost it's voted/winner color: #20281

**Comment by MyNameIsRomayne** [comment]
#20372 - I made a fix for the console history but it changes the behavior to be largely on the DM side of things. It could be merged after this PR to fix what would otherwise be a loss of QoL, not sure what's wanted here but I'll just leave it up in the air for now I suppose

**Comment by Laboredih123** [comment]
bit of a big pr

**Comment by Garash2k** [comment]
Looking at the Plantmaster Mk4 point, some properties can be justified to be put in static_data, but many of them can't, adjusting it

**Comment by Garash2k** [comment]
Is this broken? `<Popper>` isn't used anywhere so it's not a big deal if it is I guess
image

**Comment by Garash2k** [comment]
> Genetics console -- When decrypting gene sequence, on pressing "Attempt Decryption" the sequence stays instead of being reset

Looks like it got fixed since this was reported.

https://github.com/user-attachments/assets/2377a448-aca8-4d6d-9bba-8fbdd8fec2fb

**Comment by Garash2k** [comment]
Update on the genetics looks, it's not that the color changed, it's that there's an erlenmeyer icon that started appearing in the background that wasn't there before. Also, the progress bars had a themed look that they lost.
master/react:
bw7txl
y1vypz

**Comment by ZeWaka** [comment]
> Also I got this weird bug, when new researches pop up, they don't have text, and everything is fixed after a refresh. Pretty bizzare, I'm not sure if it's just me.

yes this has happened to me, it used to be worse before my changes to how researches are stored internally, maybe that needs to be changed for the finished researches also

**Comment by Laboredih123** [comment]
tgui thaw just a week away, oh wow

**Comment by Laboredih123** [comment]
when the tg ui is made for tg :(

**Comment by mordent-goonstation** [comment]
ArtifactPaper updated with a bit of a hack (background color overrides) to deal with black-backgrounds. Now has an issue with white-border for checkboxes.
image

**Comment by Garash2k** [comment]
This point got fixed by upgrading to tgui-core 1.2.0 🎉
> setting sliders to specific values by clicking them requires extra clicks?: https://github.com/goonstation/goonstation/pull/20060#issuecomment-2284921545

image

**Comment by ZeWaka** [comment]
thats about it, final wrapup and go-over of `TODO-REACT` stuff, and write the PR text

**Comment by Garash2k** [comment]
Clicking on Paritcool's *Add Particle* button results in a white window.
image
image

The following error can be seen looping while running a dev server:
image

**Comment by Garash2k** [comment]
New available researches have their title&description missing
image

They show up fine after closing and opening the window
image

**Pull request merged**
