### PR TITLE
Allow mouse wheel scrolling to set target body attack zone

### PR DESCRIPTION
**Pull request by FlameArrow57**
[PLAYER ACTIONS][QoL]

## About the PR 
This PR makes it so that scrolling the mouse wheel will set the target body zone that you attack

I saw that mouse wheel implementation in the code is hardly used, which would make this simpler to implement, and I think mouse wheel scrolling is pretty fast, compared to an action like hitting multiple hotkeys or a single hotkey to cycle between zones.

Performance when scrolling the mouse wheel to set the zone:
image
Performance when scrolling over at atom that implements MouseWheel is roughly the same.

Things to note that I found-
-client/MouseWheel() is not called at all when in a scrollable interface, like the chat log, or a TGUI interface
-It is called most everywhere else (I think)

## Why's this needed? 
Currently there's 6 zones you can select, including chest, arms, legs, and head. This makes it so that in order to set your target attack zone faster than clicking the HUD zones, you either have to override more important hotkeys, or angle your hand in a painful way to reach the hotkeys for the zones you want to attack which is even more difficult when moving around

## Changelog 
```changelog
(u)FlameArrow57
(*)Scrolling the mouse wheel will now set the target body zone you are attacking. Scrolling downwards is in the order head -> chest -> left arm -> right arm -> left leg -> right leg, without wrap around. 
```

### CODE REVIEW

**Comment by kbsmilk** [comment]
Golly, the greatest katana buff there ever was...
Nah really though, this is great. There are probably already folks using outside software to "rebind" this, so this levels the playing field.

Sidenote though, I would make it NOT loop. It helps muscle memory if you can jam the wheel all the way up/down to "reset" your position to an end-point, and work from there. Like having a home position, you know?

**Comment by ZeWaka** [comment]
This order is weird. Why not top down or bottom up?

**Comment by FlameArrow57** [comment]
Sure

**Review by pali6 — APPROVED** [review]
I feel like chest should be inbetween the arms but that might just be me.

**Pull request merged**
