### PR TITLE
Buff the effect of EMP on borgs

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
This pr increases the damage emp do to borgs from 10 to 55. This also makes emps stun borgs for 5 seconds. To make these thresholds work, standard heads have had their healths decreased from 175 to 160, and sturdy arms and treads have gone from 100 health to 115. 

With the current numbers, it takes 1 emp to remove all of a light borgs limbs, 2 emps to kill a light borg and remove all of a stanrdard borgs limbs, and 3 emps to kill a standard borg and strip a sturdy borg of all its limbs.

## Why's this needed? 
Currently, it takes 3 pulse rifles or emp grenades just to remove a light borgs limbs. This should make emp a far stronger counter to borgs.

## Changelog 

```changelog
(u)Ikea
(*)EMP's now stun borgs for 5 seconds, disable modules for a max of 5 seconds, and now do far more damage to borgs.
```

### CODE REVIEW

**Comment by Wisemonster** [comment]
Does this affect borgs hit by pulses from the emp gene?

**Comment by Wisemonster** [comment]
So that means that a round-start roboticist with mildly mutated could spawn mass de-limbing the borgs?

**Comment by TobleroneSwordfish** [comment]
Might be better to make EMPs disable modules temporarily? Since that tends to be the issue in countering borgs, not raw tankiness.

**Comment by Tarmunora** [comment]
> Might be better to make EMPs disable modules temporarily? Since that tends to be the issue in countering borgs, not raw tankiness.

Agreed. Issues with borgs are rarely "they take too much damage to kill" and moreso "they are moving too fast to hit" /" dancing over lube/plasmafire/hellsmoke/etc" / "recovery+tele modules makes them impossible to pin down"

**Review by Tarmunora — CHANGES_REQUESTED** [review]
Should rename `module` to `upgrade` here, as cyborg modules are the things that hold the tools etc.

**Review by Tarmunora — APPROVED** [review]

**Pull request merged**
