### PR TITLE
Resprite the flashbang box as a real grenade box

### PR DESCRIPTION
**Pull request by blackrep**
[Game Objects]
## About the PR 
Feedback from #13214 is that people would actually like a unique grenade box sprite rather than a cardboard box. This PR does the following:
1. Replace the cardboard flashbang box with a wooden grenade box with a flashbang sticker on top
2. Swaps the guardbuddy kit from the flashbang box sprite to a generic box sprite (not sure why it was using flashbang?)

Sprite:
image
Ingame:
image

## Why's this needed? 
Testing the waters to see if people like this sprite. If it gets merged I just replace the grenade icon on the sticker to create new grenade boxes.

### CODE REVIEW

**Comment by Gerhazo** [comment]
It kind of looks like a big box/crate that'd block your movement rather than something you can fit in your backpack.

**Comment by blackrep** [comment]
> It kind of looks like a big box/crate that'd block your movement rather than something you can fit in your backpack.

Valid feedback. But it's about the same size as the det's revolver case. With this current sprite, likely wouldn't be able to shrink it anymore without losing the sticker.

**Comment by TobleroneSwordfish** [comment]
Imo the detective's revolver box and other big in-hand boxes shouldn't be that big either, it confuses everyone the first time they come across them.

**Comment by blackrep** [comment]
> Also might be a nit-pick but this sprite looks a little military for a box of crowd control flashbangs, maybe would be better for frag grenades?
Got any examples of what you would expect a less military box for a bunch of grenades would be?

**Comment by ZeWaka** [comment]
@TobleroneSwordfish

**Comment by ZeWaka** [comment]
Closing since it doesn't seem like this sprite is going to work out.

**Pull request closed without merging**
