### PR TITLE
Action(bar)s Don't Restart on Successive Attempts

### PR DESCRIPTION
**Pull request by MarkNais**
[REWORK] [QOL]
## About the PR 
Add a new check when a (new) action starts:
If there is an existing action of the same ID that has it's state set to END: resume the existing action, do not use (destroy) the attempted new action.

BBfi3ui184
I'm rapid-fire clicking the table in the above GIF. Cosmetic bug: my interruptions are "pulling" the color towards red, but it springs back to blue when I stop.
(I know it springs back to green instead of blue in the gif, it's been fixed)
## Why's this needed? 
In my opinion, actions restarting because you triggered their start-condition twice, is bad user experience.
When I click the table with a wrench, and I'm 3/4 done, accidentally clicking it again should not "reset" my progress.

Furthermore, many noobs spam-resist cuffs. Maybe they think it will help? (like spamming resist to roll out a fire does.) However, users don't even get any visual feedback that spamming isn't working, since cuffs take so long that the colored bar doesn't even render.

## Changelog

```
(u)MarkNstein:
(*)Action(bar)s will no longer reset upon successive attempts.
```

### CODE REVIEW

**Comment by Carbadox** [comment]
fuck yes

**Comment by Tiggersaurus** [comment]
Yusyusyus

**Comment by MarkNais** [comment]
MBC pointed out to me a couple days ago that this breaks any "repeat" action bars, like the automender.
I've started a fix, just gonna take more time to complete.
Note to self: fix:
```automender
vamp suck
vamp range suck
force_lightning_action
force_choke_action
force_heal_action```

**Comment by MarkNais** [comment]
7uoL7cBQ9D

Changed and tested the following looping actions:
```automender
vamp suck
vamp range suck
force_lightning_action
force_choke_action
force_heal_action

**Pull request merged**
