### PR TITLE
Minor changes to Cow mutantrace sprites

### PR DESCRIPTION
**Pull request by WALPVRGIS**
[SPRITES] [WIKI]
## About the PR 
Makes a couple of small changes to Cow people sprites; adjusts perspective on snout, updates horns to match the Cranial Keratin Formation changes, adds ears (I think this helps a lot with making them more cow-like). Note that horns stick out of helmets; this happens with the current cow sprites as well.

Old:
image

New:
image

## Why's this needed? 
Player feedback, adjusting to match new perspective a lil more accurately

## Changelog

```changelog
(u)Walpvrgis
(+)The cow mutantrace has had a few visual adjustments.
```

### CODE REVIEW

**Comment by BatElite** [comment]
Not related to the changes you did which look good to me, but I wish the hoof colouring thing was more than just a line around the bottom

~~give cows full hoof paint~~

**Review by Tarmunora — APPROVED** [review]

**Review by flrsh — CHANGES_REQUESTED** [review]
I think it's really funny that cows have no ears and a smooth head, and I also think them having smaller horns instead of larger ones fits them better. I think the sprite changes are a pretty significant aesthetic shift.

**Comment by WALPVRGIS** [comment]
> 
> 
> I think it's really funny that cows have no ears and a smooth head, and I also think them having smaller horns instead of larger ones fits them better. I think the sprite changes are a pretty significant aesthetic shift.

I'm about to head to bed, so no ingame examples sorry! But do you have thoughts on this quick update?

image

**Review by Sovexe — APPROVED** [review]
Personally I think that that new ears and horns look good, and helps them look more cow like

**Comment by flrsh** [comment]
> I'm about to head to bed, so no ingame examples sorry! But do you have thoughts on this quick update?

I think that retains the cow-ness for me. Let me know when you push those changes.

**Comment by WALPVRGIS** [comment]
> 
> 
> > I'm about to head to bed, so no ingame examples sorry! But do you have thoughts on this quick update?
> 
> I think that retains the cow-ness for me. Let me know when you push those changes.

Finally got the time to make those changes just now. 👍

**Comment by flrsh** [comment]
Sorry for the late response! @WALPVRGIS I think the genetics icon isn't updated, could you change that? Otherwise looks good to me!

**Comment by WALPVRGIS** [comment]
@flrsh Oops, thought I did that, thank you for catching it! Should be up to date now :)

**Review by flrsh — APPROVED** [review]

**Pull request merged**
