### PR TITLE
Expands and alters nuke targets for current rotation maps

### PR DESCRIPTION
**Pull request by BatElite**
[balance][input wanted]
## About the PR 
Gannets requested earlier today that someone add some new nuke targets on the active maps, so here we are with a PR that adds a bunch.
Below are the suggestions I'm making:

**Cogmap:**
+bridge
+stock exchange (not very large, but might produce interesting fights on the public market especially since there's a little space until the hallway compared to EVA)
+escape arm
+crew lounge (middle room only)
+chapel

**Cogmap 2:**
+bridge
+chapel
+mining staff room
+central warehouse

-Replace TEG room with the engine control room, which has a few more entrances

**Donut 3:**
+bridge
+courtroom
+main security room
+botany

**Kondaru**
+telescience
+public market (listed as "merchant docks" because that's its most recognisable trait
+chapel
+nerd dungeon
+fitness room
+news office

**Clarion:**
+bridge
+community center (AKA chapel)
+aviary
+QM storage (not to be confused with the office which is already a target. Maybe merge?)

-removed EVA due to size
-removed robotics, it's tiny and cramped

**Destiny:**
+escape shuttle docking room
+kitchen

-removed EVA because it's next to arrivals and the size of a gnat's fart

**Horizon**
+cloning
+hot loop room (engine control is already listed, too similar?)
+botany
+mech lab
+mining staff room
+robotics
+south crew quarters (next to the pool)

**Oshan:**
+security main room
+engineering main room
+science lobby
+crew quarters
+mining

**Manta:**
+courtroom
+chemistry
+hydroponics
+Rising Tide bar

Drafted because I need to poke a couple area related things (clarion's funeral parlour uses the same zone as the community center/chapel, donut3 has something similar). Also I'm thinking about Ozymandias but I don't have a big list and maybe Kubius wants to do that themselves.

I didn't test this, but I have had strongdmm open beside to check the areas were correct.

## Why's this needed? 
Gannets asked for it. I think half these target lists are copy-pasted and it'd be nice to have some more specificity per map. Oshan didn't have any targets on the right third of the station for instance.

## Changelog

```
(u)BatElite:
(*)Almost all maps now have additional nuke planting targets!
```
## Wanted input
I'm sure there's a lot of discussion to be had about which make for good targets.

### CODE REVIEW

**Comment by Gannets** [comment]
Thanks for making this PR! My only edits for now would be:
-pod bay would probably result in crummy pod combat
-catering storage has a lot of cool entry points but is suuuuper cramped for 8 ops.
-fitness room would suffer from the same "i can't shoot over this?" issues that the pool had.
Otherwise these all seem like good additions.

**Comment by Kubius** [comment]
Thoughts on Kondaru additions:

- Telescience is alright, if a bit weird.
- Merchant docks are pretty close to space so might be a little too easy to speedrun, but do have the advantage of the east entrance from Maintenance permitting some interesting surprise attacks.
- Chapel, nerd dungeon and fitness room should be fine.
- Botany would make an exceedingly awkward battleground. Firm no.
- EVA is an interesting pick, but probably hardmode for the nukies because of how difficult it is to reach the location stealthily, even when warping into the center beacon. I think this might be a bad plan.

Some alternative locations to consider: Aviary, central warehouse, news office, waste disposal.

On the topic of Ozymandias, it already has ten entries so it's pretty stocked, but here are some potential options if you think there should be more: engineering tool storage, the bridge (counts both Officers' Lounge and the proper Bridge dome), the communications center (next to bridge), inner maintenance (counting both NW inner maintenance and west inner maintenance), or the research and medical break rooms.

**Review by Gannets — CHANGES_REQUESTED** [review]
If you wanna implement me and kubius' suggestions here, I'll get it merged. 👍

**Comment by flrsh** [comment]
Oshan: All seem okay to me!

Clarion: Secure dock is too difficult to access if nukies weldmag doors, operating room and tool storage are too small and cramped, I'd probably also change the area of the QM/mining hangar if QM storage is added as a target area.

Destiny: A bunch of the different options for medbay are too small and cramped, I'd just stick with what was there previously. The research lab is also too difficult to reach and has too many chokepoints.

Manta: Inner engineering and security officers' quarters are too difficult to reach, det's office is too small and cramped, engineering storage is too small and cramped if nukies decide to plant in the second room with all the lockers. Probably remove the engineering power room while you're at it. Some potential additions might be hydroponics and the courtroom.

**Comment by BatElite** [comment]
I'll get to this later today.

**Comment by BatElite** [comment]
I changed everything mentioned here, but here's the additons
Kondaru:
-I actually already added the news office at the last minute and forgot to list it, oops
-aviary, general warehouse added
Disposals is sadly a bit cramped + the conveyors lining the south wall make crushing the nuke fairly easy. I'd love for a map with disposals as a nuke target someday though.

Manta:
-added courtroom, hydroponics & the bar (I thought that was a target already? In any case it's about as hard a spot wrt obviousness as hydroponics I feel)

With that, this is ready as far as I'm concerned.

Some further technical notes for the less self-explanatory commits:
I added a new area for Clarion: the funeral parlor. It can probably be added to a couple other maps in the future (Ozy and Donut 3 come to mind) but for this PR it's so nukies can't stuff it in a cramped spot if they have to target thee community center. The only side effect is that the storage room door now says "Funeral Parlor" but IDK what can be done about that, renaming the area "tile" on top breaks things.

Trying to test the above was working, I found that a couple of APCs on Clarion had gone bad and I had to fix those before I could.

**Review by Gannets — APPROVED** [review]

**Pull request merged**
