### PR TITLE
allow soulsteel mobs to be possessed

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
Allows soulsteel mobs to be possessed, if there isn't already a mind controlling them.
## Why's this needed? 
It's pretty fun! And methods of turning mobs into soulsteel are few and far between. (I can really only think of transmutation bombs, finding one that did soulsteel would be exceedingly rare.
So this would probably mainly affect stuff like chickens.

Now, I'm not saying that this is a good idea or that it won't cause any issues.
I just think it'd be fun to have a conversation about whether or not this might be a neat addition to the game!
It could also be restricted to just certain types of mobs.

### CODE REVIEW

**Comment by Sovexe** [comment]
This would need to disable monkey and mob ai or you're not going to have much control over your actions

**Comment by zjdtmkhzt** [comment]
I don't think you would be able to possess monkeys with this, as they already have a mind due to their AI somehow?
But yeah, chickens and stuff may be a little annoying (but funny) so disabling AI may be a good idea.

**Review by ZeWaka — CHANGES_REQUESTED** [review]
above

**Comment by zjdtmkhzt** [comment]
AI should be disabled now on possessed mobs.

I also made a small change because before you would be prevented from possessing a soulsteel thing in the first 3 minutes of the round and it was annoying.

**Review by geneva-breaker — CHANGES_REQUESTED** [review]
For as rare as soulsteel mobs are, I'm very reluctant to put a ghost into *anything* that isn't nerfed to the bones. 

This also doesn't seem to have any provisions to reenable the AI, and only addresses one type of AI (mobai's activation is slightly different). 
Aside from the technical issues i'm not a huge fan of the concept, but yeah the AI issue needs work and testing.

**Comment by zjdtmkhzt** [comment]
Hmm, I didn't feel reenabling AI would be very important, because the only way the ghost is leaving again is by the mob dying, usually.
And if the mob were SR'd after that, I think that would drag the ghost back inside the mob too, right?

So it would probably only matter if someone possessed a mob, then died in the mob, and then went and got their ghost inside some *other* mob, in which case the first mob would be alive but not be AI enabled.
Seemed like kind of an unimportant edge case to me, but I could make SR reenable AI if the resurrected mob has no associated mind or something.

I'm not sure what other kind of AI you mean? I tested with the trench critters, chicken people, and shitty bill and all seemed to have their AIs properly disabled.
Stuff like npcs (ie. monkeys with AI / syndicate operatives / whatever) already have a mind for some reason, so this would not let you possess them.
Stuff like bodyswapping via other means doesn't disable any AI stuff either, so I don't feel like it would be much of an issue if it didn't disable it here either, tbh.
Honestly, if balance is a concern, it might even be good to leave the AI on, to make things harder to control for the ghost, representing a battle between the mobs instincts and the soul trying to take control.

**Comment by zjdtmkhzt** [comment]
I'm really mainly doing this because I keep hearing people be sad you can't possess soulsteel chickens, but maybe it'd be better to start out with just those and then later expand to other mobs, if that goes well.

I wouldn't wanna do that without asking Urs though, so I'll just shelve this for now!

**Pull request closed without merging**
