### PR TITLE
Eating cooldown

### LINKED ISSUE #2137: Pests MUST have an eating cooldown. Not a bug, but a massive unpunishable GRIEF.
Submitter: xuriel
Right now one pest can destroy half an hour(or basically infinite amount), worth of Chef's work in 2 seconds by mass eating infinite amount of food. All it takes is to click really fast.
It is not okay when combined efforts of botany and chef can be destroyed in 2 seconds with no effort by a non-antag, who should not even be in the round anymore.

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Makes it so you have to wait 0.5 seconds between bites.
Resolves #2137

## Why's this needed? 
People just instantly inhaling a stack of food can be hilarious but also not great for the chef that spent dozens of minutes preparing all that. Especially when it comes to ghost critters.

## Changelog
```
(u)pali
(*)Eating food now has a short cooldown
```

### CODE REVIEW

**Comment by moonlol** [comment]
For critters id understand and support this change, but people too?

**Comment by Sartorius7** [comment]
The ability for critters and humans to eat food super quickly  feels more like a feature than a bug, and it limits the usefulness of the survivor trait, where the ability to eat food as fast as possible is often the difference between life and death. It's quite easy to stop a ghost critter from eating food quickly in the first place by simply setting up the mousetraps provided in the kitchen.

**Review by Tarmunora — APPROVED** [review]
Good change. Incidentally, having a short delay between bites (and half a second *is* short) gives more value to high-`heal_amt` foods for the purpose of healing from food, making them more worth the time/effort/etc to make as opposed to mashing lower-healing food into your mouth at 10 clicks a second.

**Comment by moonlol** [comment]
Theres already great value in higher healing foods as its more space efficent, you can only cram in so manu burgers. To really benefit from healing in a combat scenario you need the survivalist trait. And even then above crit damage doesnt really matter (damage that wont put you in crit)

**Comment by moonlol** [comment]
Add a changelog for godssake atleast

**Comment by Adharainspace** [comment]
this already existed in the form of a click delay when eating foods, before the c hotkey and eat by pressing c was added. this is a consistency pr imo.

**Comment by Sartorius7** [comment]
Please add a changelog entry, also mention that this brings the eating speed in line to how it was before the introduction of the action key

**Comment by moonlol** [comment]
> this already existed in the form of a click delay when eating foods, before the c hotkey and eat by pressing c was added. this is good a consistency pr imo. 

Its been like this too long to be really about consistency imo

**Comment by Adharainspace** [comment]
> > this already existed in the form of a click delay when eating foods, before the c hotkey and eat by pressing c was added. this is good a consistency pr imo.
> 
> Its been like this too long to be really about consistency imo

how? the click delay added when eating food was intentional. im willing to believe that no one bothered to check when they added the c hotkey attack self fast food eating, and only got around to it now.

**Comment by moonlol** [comment]
I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago

**Comment by Adharainspace** [comment]
> I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago

so whats the issue with fixing it now?

**Comment by pali6** [comment]
> I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago
That's not a valid excuse for leaving it in.

**Comment by moonlol** [comment]
> > I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago
> 
> so whats the issue with fixing it now? 

Its been here so long and not talked about as an issue and is frankly harmless that changing it feels like a "no fun allowed" to me. A much better solution would be adding this exclusively to ghost critters

**Comment by pali6** [comment]
> > > I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago
> > 
> > 
> > so whats the issue with fixing it now?
> 
> Its been here so long and not talked about as an issue and is frankly harmless that changing it feels like a "no fun allowed" to me. A much better solution would be adding this exclusively to ghost critters

Humans can grief the same way as ghost critters can.

**Comment by moonlol** [comment]
> > > > I meant that its been so long like this that if it was going to be fixed it wouldve been a long time ago
> > > 
> > > 
> > > so whats the issue with fixing it now?
> > 
> > Its been here so long and not talked about as an issue and is frankly harmless that changing it feels like a "no fun allowed" to me. A much better solution would be adding this exclusively to ghost critters
> 
> Humans can grief the same way as ghost critters can.

A human under normal circumstances cant respawn near infinitally, and squeeze through doors

**Review by flrsh — APPROVED** [review]
I agree with Adhara, it's nice for consistency. 

Also it sucks when you're a chef and you make a bunch of food and someone eats all of it before you can react.

**Comment by TTerc** [comment]
I'm also against it as a user of survivalist trait because it really nerfs it, to the point of me considering disabling it (if this gets merged)
And I don't really understand the reason of the nerf, because some hypothetical situation when someone eats all the chef's food rapidly doesn't justify the change imo.
I'm not against the change that affects critters only, since this was the initial concern that was brought up

**Comment by pali6** [comment]
If this makes survivalist too weak I'd rather buff survivalist.

**Comment by TTerc** [comment]
I'd be okay with that
I don't know how it works exactly but from what I've observed during ass jam, it heals around 2 hp per bite. Buffing that to adjust it to the cooldown would be good enough for me

**Review by MarkNais — APPROVED** [review]

**Comment by flrsh** [comment]
> I'm also against it as a user of survivalist trait because it really nerfs it, to the point of me considering disabling it (if this gets merged)

How does this really nerf survivalist?

**Comment by TTerc** [comment]
You can heal while eating food as fast as you can click
So adding a cooldown will obviously nerf it

**Comment by flrsh** [comment]
> You can heal while eating food as fast as you can click
> So adding a cooldown will obviously nerf it

Does needing 3 seconds to eat something instead of 1 really constitute a nerf? In the majority of cases, you'd still eat your food the same, maybe a few seconds slower, and that'd be that.

**Comment by MarkNais** [comment]
Survivalist being -1 trait point doesn't make it seem like a "major" trait (-2 or -3), So I don't consider this a big nerf to it. You still get the bonus health per each bite, 2 bites per second. It's still a meaningful benefit.

**Comment by TTerc** [comment]
Well, to me, it's all about time. You'll spend considerably more time healing yourself via food than you did before. And in certain scenarios, those few seconds can make a big difference. And thus, the overall usefullness of this trait will be lower too
Eh anyways, I don't really wanna dispute over it endlessly, I have voiced my opinion, I believe a slight buff would be fair. I'll leave this up to you

**Review by ZeWaka — APPROVED** [review]

**Comment by Kyle2143** [comment]
If you have matter eater or empowered matter eater, you should not have the cooldown.

**Comment by ErwinSnowden** [comment]
> If you have matter eater or empowered matter eater, you should not have the cooldown.

Sad that empowered matter eater no longer exists... heh...

**Pull request merged**
