### PR TITLE
PDA Port-A-* Apps now use teleporting animations

### PR DESCRIPTION
**Pull request by pgmzeta**
[QoL]

## About the PR 
Adds the teleport effects already in use for port-a-* remotes to the equivalent PDA apps.

## Why's this needed? 
Consistency between porters and PDA apps; use cool animations.

### CODE REVIEW

**Comment by pgmzeta** [comment]
not really a feature ^^'

**Comment by frawhst** [comment]
`if (hasvar(P5, "occupant"))`
what the fuck is going on in this file. what is a `P5`.  why is this code not shared between porter remotes and apps. aa

**Review by frawhst — APPROVED** [review]
seems good though

**Comment by pgmzeta** [comment]
it's one one big-long-huge Topic and i'm too scared of PDA code to attempt simplification

> `if (hasvar(P5, "occupant"))` what the fuck is going on in this file. what is a `P5`.

clearly a persona fan wrote this code

**Pull request merged**
