### PR TITLE
Resprites Several Types Of 40mm Shells Alongside Some Minor Name Clarifications

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[QoL] [Wiki] [Cleanliness]

## About the PR:
Smokes shells and smoke shell boxes now have unique green sprites, similar in theming to fog grenades; paint marker round boxes have been resprited to use a white 40mm box with orange tipped shells, and no longer create a blood effect when they hit someone; the Grenadier's HEDP shell boxes now have a new HE shell box sprite, and their HE shell boxes now have a concentrated HE shell box sprite; and pod seeking HE shell boxes alongside general pod HE shell boxes also have a new shared sprite. Also reprites the projectiles to match the colour of their respective boxes.

Sprites, and the ammo types that use them:
40mmSmoke  40mmPaint
40mmNonlethal  40mmLethal
40mmHE  40mmConcHE
40mmPodHE
It should be noted that Grenadier HE shells are more explosive than Grenadier HEDP shells, hence the additional gold band on the HE shell box. The plain red box, `40mm_lethal`, is also now rarely used for items outside of Admin-spawned objects; it just that most 40mm shells happen to be highly explosive.

## Why's this needed?
40mm shells should now be more discernible from each other, I also feel that it is out of place that paint marker rounds use the same sprite as instantly-gibbing, pod launched shells.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)Resprited 40mm smoke shells, 40mm paint marker rounds, 40mm HE pod and pod seeking shells, 40mm HEDP shells, and 40mm HE shells.
```

### CODE REVIEW

**Review by Azrun — COMMENTED** [review]
Code looks pretty good.

**Comment by Tarmunora** [comment]
Additional sprites for the paint rounds (bright orange?) would definitely be a nice-to-have if you're up for it

**Comment by Mister-Moriarty** [comment]
> Additional sprites for the paint rounds (bright orange?) would definitely be a nice-to-have if you're up for it

My colour classification for 40mm shells is based off of the 12ga round boxes; orange is used for the flares. While 40mm incendiary shells aren't quite in the game, when spriting the new boxes, I still felt it was pertinent to keep orange colouring to incendiary ammunition. Excluding orange, perhaps yellow, purple, or pink could be used for paint rounds, alongside a recolour of the paint applied, if necesssary.

**Comment by Mister-Moriarty** [comment]
40mm_paint

**Pull request merged**
