### PR TITLE
Moves Manta Arrivals

### PR DESCRIPTION
**Pull request by comradef191**
## About the PR 
Moves Manta Arrivals away from Escape, placing it in the empty space next to QM instead.

## Why's this needed? 
As it is, It's extremely easy to accidentally damage Arrivals due to its poor placement of it being right next to Escape and Engineering.

## Changelog

```
(u)Comrade f191:
(*)Moved Arrivals on Manta to QM rather than Escape.
```

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
I think the idea of this PR is definitely sound. If the conflicts could be tidied up (probably involves re-applying the changes on the latest .dmm again), I think this definitely warrants merging.

**Comment by comradef191** [comment]
OH GOD

**Comment by comradef191** [comment]
AAAAAAA

**Comment by comradef191** [comment]
I FUCKED UP
FUCK IT
NEW BRANCH+PR

**Pull request closed without merging**
