### PR TITLE
Adds Chemistry and Robotics Ad, sorts radiostation folder sounds into music and adverts folder

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Adds Chemistry ad by Brixx79, sorts radiostation folder sounds into music and adverts folder

## Why's this needed? 
New ad. Better organisation. 

## Changelog

```changelog
(u)Brixx79
(+)Added new Chemistry and Robotics radio tape adverts. 
```

### CODE REVIEW

**Review by virvatuli-gh — CHANGES_REQUESTED** [review]
File structure looks good to me but the new advert is enormous. There is absolutely no reason why a 1 minute .ogg should be 3mb big. I can compress it for you (if you don't want to do it yourself). The filesize should be inline with the other adverts currently ingame.

Other than that organization is good, separating the adverts and music is a great idea!

**Comment by Carbadox** [comment]
Added the robotics ad, both files are compressed versions by Virva.

**Review by virvatuli-gh — APPROVED** [review]

**Comment by virvatuli-gh** [comment]
Just a minor thing but you should change the title to reflect both adverts are being added (or include it description), just to aid any searches for the PR in the future. Other than that looks good!

**Comment by Brixx79** [comment]
Thanks for your help in creating this.  I really appreciate it.

**Pull request merged**
