### PR TITLE
Card updates

### LINKED ISSUE #4805: spacemen grifening cards can pick mob names of non-manifest mobs
[bug - trivial]

**Describe the bug**
Random name picking for Spacemen the Grifening mob cards includes NPC mobs that had not been previously included.

**To Reproduce**
1. Buy Grifening Cards
2. Check your cards out to see what you got
3. See that you have "Head of Security chicken man" and "Research Director chicken man" and "Traitor cloned human" as mob names

**Expected behavior**
For the mob card names to be drawn from the manifest names of players in the round.

**Screenshots**
chickenmangriffening

### PR DESCRIPTION
**Pull request by nefarious6th**
[cleanliness][QoL][bugfix]

## About the PR 
This PR:
- [x] Removes all the spaces used to indent lines and changes them out for tabs so revisions in playing_cards.dm compile 
- [x] Cleans up some sprites in playing_cards.dmi to match art style
- [x] Reduces the tedium to open and actually use Griffening Card Decks
- [x] Re-adds the riffle shuffle
- [x] Fixes #4805 
- [x] Makes picking up cards decks in pockets and backpacks more obvious (related: #5001 & #4804) (courtesy of @eX-n0x)

## Why's this needed? 
- Code standards and usability
- Spacemen the Griffening is actually a really neat mechanic and having 5 minutes of action bars to open the base decks doesn't help players get to the point of engaging with the feature.
- Misc. bug fixes and feature re-implementation

## Changelog
```changelog
(u)eX.n0x & Nefarious6th
(+)Card decks can now be taken out of pockets using the "pick up" action.
(+)The process to open a Spacemen: the Grifening deck box is now easier!
(+)Realistic card shuffling re-added; your cards might stick to each other!
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
Going to fail runtime until I fix all 1000 lines of indents.

**Comment by nefarious6th** [comment]
I will finish fixing runtimes. Later.

**Comment by eX-n0x** [comment]
D: Please, I can't take all the credit for this. All I did was fix a few bugs, you did almost all of the work yourself. At least add your name to the changelog.

**Review by ZeWaka — APPROVED** [review]
alexa play the beep beep beep song

**Comment by Azrun** [comment]
Still creates ghosts instances in pocket and backpack when moved back to hand consider changes similar to 051d627e or something that performs `/obj/item/attack_hand` handling for properly handling storage objects and proper removal from pockets.

Riffle shuffling on any spawned card_group appears to cause runtime as the deck is deleted and then not made into an empty list.

**Comment by nefarious6th** [comment]
😔 will try to work out by the end of next week

**Review by ZeWaka — CHANGES_REQUESTED** [review]
playing_cards.dm:1214 must go.

**Comment by nefarious6th** [comment]
I got rid of the line but I'm fairly certain there's still something wrong with it; I don't know what exactly, but after I stack ~15 shuffles within the span of about 30 seconds, my client will crash. Not sure where to go with this.

**Comment by ZeWaka** [comment]
@nefarious6th could you just remove the riffle shuffle and revisit it in a later PR?

**Comment by ZeWaka** [comment]
pong

**Comment by Azrun** [comment]
image
Investigating and will likely re-PR.

**Pull request closed without merging**
