### PR TITLE
Donut 3 Medical Break Room Update

### PR DESCRIPTION
**Pull request by t-toasted**
## About the PR 
Refreshes the staff room in Donut 3; adds in the medical uniform locker, majorly, since it was missing and could cause issues if a doctor either lost their gear or a new doctor was added from the HoP. Also edits some of the area by adding in more sofas- mainly directed at the RP server, as the room tends to be used for discussions/police investigations/therapy sessions. 

## Why's this needed? 
A medical clothing locker has been desperately needed in donut 3 for a long time. Instead of simply putting it in the all and adding another obstruction to the corridor, adding it to the staff room keeps things organized. Removing unused items and objects from the room helps make it more useful, and takes into account feedback from both classic and RP servers. 

## Changelog

```changelog
(u)Roddy
(+)Updates Donut 3 break room and adds in a medical uniform locker
```
unknown (7)

### CODE REVIEW

**Comment by t-toasted** [comment]
Fixes #9331

**Comment by t-toasted** [comment]
The more I look at the bottom section the less I enjoy it, so if anyone else has an issue with it, I can try to edit it again

**Comment by ZeWaka** [comment]
definitely not major changes

**Comment by t-toasted** [comment]
> definitely not major changes nor are two necessary

Minor changes it is

**Pull request merged**
