### PR TITLE
Standardise intercom type usage across maps

### PR DESCRIPTION
**Pull request by BatElite**
[feat][cleanliness]
## About the PR 
This PR is meant to go through all maps currently in rotation and replace default intercoms into the departmental subtypes where appropriate. Currently some maps use all varedited types over presets (cog1), or a mix of both (cog2/donut3) or it's just the sec and brig radios from the listening outpost that need replacing (Kondaru)

Non-mapping changes:

-Changes the catering frequency from 1485 to 1463 (taken from cog1's catering intercoms), as 1485 is also the security intercom frequency.
-Adds a frequency for botany-specific intercoms (1446) and a pre-configured subtype for it.

- [x] Cog1
- [x] Cog2
- [x] Donut3
- [x] Clarion (didn't need changes, thankfully)
- [x] Destiny
- [x] Kondaru
- [x] Oshan Laboratory
- [x] Manta
- [x] Atlas (didn't need changes)

The only non-standard thing I left is there's a toxins-engine core intercom link on Cog1. AFAIK no other map has something like that so it felt a little pointless to turn into a subtype.

## Why's this needed? 
Standardisation of mundane crap is good, the future really. We could have that future today. Wouldn't want to have several maps ignore changes made to departmental intercoms.

### CODE REVIEW

**Comment by BatElite** [comment]
Considering whether or not I should make Cog1 its own PR since there's a bunch of mapping PRs open on that map, and unlike the rest of the maps I think every single intercom needs replacing there.

**Comment by Kubius** [comment]
Listening post intercoms on Kondaru have now been handled in #3689 fixbatch.

**Review by Sovexe — APPROVED** [review]

**Comment by ZeWaka** [comment]
will merge once resolved

**Review by ZeWaka — APPROVED** [review]

**Review by flrsh — APPROVED** [review]
Thank you for your hard work!

**Pull request merged**
