### PR TITLE
Atlas mining/podbay expansion (+ peripheral changes)

### PR DESCRIPTION
**Pull request by Kubius**
[FEAT]
## About the PR 

Significantly expands the aft section of Atlas on both port and starboard sides, with the following primary changes:

- Mining has been expanded. The pod bay is significantly larger, a quantum telescope is now available to miners (though no magnet yet - see end note), and the refinery portion has been split off into a publicly accessible sub-area.
- The aft starboard pod bay has been expanded. It's now equipped with a proper pod construction room including fuel / firefighting tanks, a ship component fabricator and assembly parts, and is no longer gated to maintenance access.
- In the process of these changes, airlocks for the merchant shuttles were rekerfuffled, and both merchant shuttles are now accessible without maintenance access.
- Some other minor things of note: Mechanics' lab is slightly more spacious, and an office supply closet have been added in maintenance spots near the pod bay (the map had none of either previously).

Addition of a mining magnet would likely be a good thing to do subsequently, but I've opted to do that in a subsequent PR partly for the sake of atomization, partly because I don't know where to put it.

## Why's this needed? 

Improves the usability and feature set of Atlas.

## Changelog

```changelog
(u)Kubius
(*)Atlas' mining department and main pod bay have received a significant overhaul, including the opening of the main pod bay, the arc smelter, and the merchant docks to public access.
```

### CODE REVIEW

**Comment by 112358sam** [comment]
Glad to see Atlas mining get some updates. After #5003 there is now a quantum telescope circuit board at the mining outpost. I think it is good to add one to Atlas as well, but the outpost now does effectively have one. Also, it would be really useful if you included a screenshot of the altered area. It would make it easier for giving input on the changes.

**Comment by Kubius** [comment]
> 
> 
> Also, it would be really useful if you included a screenshot of the altered area. It would make it easier for giving input on the changes.

One is automatically generated via MapDiffBot with before, after and a differential highlight. https://github.com/goonstation/goonstation/pull/5365/checks?check_run_id=2975350758

**Comment by Kubius** [comment]
> 
> 
> After #5003 there is now a quantum telescope circuit board at the mining outpost. I think it is good to add one to Atlas as well, but the outpost now does effectively have one.

Noted and adjusted commentary on such.

**Comment by Eagletanker** [comment]
> Glad to see Atlas mining get some updates. After #5003 there is now a quantum telescope circuit board at the mining outpost. I think it is good to add one to Atlas as well, but the outpost now does effectively have one. Also, it would be really useful if you included a screenshot of the altered area. It would make it easier for giving input on the changes.

Atlas already had a QT in tech storage IIRC.

**Comment by Kubius** [comment]
Most maps have a QT for mining so the magnet-locked resources aren't gated behind Research's cooperation; Atlas' existing quantum telescope in the technical storage isn't accessible to miners by default.

**Review by Gannets — APPROVED** [review]
👍

**Pull request merged**
