### PR TITLE
Clothing Booth: Adds new clothing options

### PR DESCRIPTION
**Pull request by WALPVRGIS**
## About the PR 

Adds 30 new outifts (jumpsuit/uniform layer) + 9 new shoes + 2 headwear accessories, including some white/uncoloured options for players wanting to use paint to dye their clothing. Many of these items are priced affordably so that Staff Assistants/Civilian Roles/Gimmick Roles could conceivably purchase them if they wanted to customize their appearances. Can change this if needed. They are mostly recolours of a few base clothing sprites I've made (and so, finishing resprites of them is not a huge task for me).

I have also rearranged some weirdness in the clothing booth categories; including rearranging category list order, a whole new category for dresses, and moving some items to more appropriate categories.

Batch1Outfits

ClothesExamples

## Why's this needed? 

Player/character customization _good_. This isn't _needed_ with the resprite in-progress, but I'm impatient as I started making these a while ago. I have already re-sprited much of these for the new base as well.

## Changelog

```changelog
(u)Walpvrgis
(*)Adds new clothing to Clothing Booth/Vendor (30 outfits, 9 shoes and 2 hats)! Time for a makeover?
```

### CODE REVIEW

**Review by Carbadox — APPROVED** [review]

**Comment by AwkwardDryad** [comment]
omg this is gorgeous!!! the only issue is that they'll need to be redrawn for the human resprite.......

**Comment by Avatharian** [comment]
you might consider checking out the Human Resprite project. It's fairly imminent, which means that these clothes will need to be modified for it.

**Comment by WALPVRGIS** [comment]
> 
> 
> omg this is gorgeous!!! the only issue is that they'll need to be redrawn for the human resprite.......
> 
> human resprite is actually why i've been putting off making anything clothing related



> 
> 
> you might consider checking out the Human Resprite project. It's fairly imminent, which means that these clothes will need to be modified for it.

Ehe, no worries, thanks for bringing it up! :) I mentioned in the description that I've already resprited several of these (just need to do the colour variations etc) so they should be ready at or around resprite launch!

**Comment by AwkwardDryad** [comment]
> Ehe, no worries, thanks for bringing it up! :) I mentioned in the description that I've already resprited several of these (just need to do the colour variations etc) so they should be ready at or around resprite launch!

i'm heccin blind

**Comment by Adharainspace** [comment]
id love if you could show off a full portfolio of front view what these all look like when worn on someone. might be a bit time consuming, but getting the idea from just the worn sprites is hard

**Comment by WALPVRGIS** [comment]
> 
> 
> id love if you could show off a full portfolio of front view what these all look like when worn on someone. might be a bit time consuming, but getting the idea from just the worn sprites is hard

I'm down to do this! :) I'll make some previews and add some more screenshots above.

**Comment by WALPVRGIS** [comment]
Aaaand added preview images of all of the outfits + shoes and the lil headsprout leaf! I didn't do a preview for the white top hat as it's just the basic one already ingame, but in white so that people could more accurately paint it if they wanted more colours. :)

**Pull request merged**
