### PR TITLE
Expands Manta ranch and changes the adjacent construction area to a market stall

### PR DESCRIPTION
**Pull request by Gremyrivolk**
[MAPPING]

I emerge from the incomprehensible morass of github still a civilian; My spirit is broken but I am no wiser for it.

## About the PR

Upgrades the Manta ranch, adding 1 extra pen, a mailpipe, a supply closet, a public-facing desk, a couple potted plants, a supply desk, and 2 hydro trays.

image

## Why's this needed? 

Copy pasted from my last PR because the reasons are identical:
- Raising multiple breeds of chicken at once is only possible if you have enough pens to store each breed, since mixing breeds and feeds in a single pen leads to interference and stops chicken speciation. Increasing the number of pens allows for more chicken variety in a single round and increases the rancher's utility.
- Adding hydro trays allows ranchers to grow chicken feed without stealing trays or resources from botany, pretty self-explanatory.
- Oshan's secluded sanitary pen is kind of just meant to be a cute thematic place to raise experimental or superpowered chickens, as well as support the rearing of chickens that create a lot of mess (void chickens, ipecac glass chickens, etc.)

## Changelog

```changelog
(u)Gremy
(*)Expands the Manta ranch and changes the construction area below it to be a market stall with a cute little duck with a hat in it.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
I think these look great! The Oshan solution you did is really good; I love the window to the main hall, the door into hydro, the orientation of the sub bay launching out instead of up, and the little sitting area/some of the maintenance stuff around. Everything here feels very well-connected and I think the split Ranch with the table and Ranch desk window in the middle is cool since people can walk up and be kind of "in the middle" of the Ranch and get a better glimpse of everything going on there.

**Review by flrsh — CHANGES_REQUESTED** [review]
The Oshan ranch is a bit small, but I'd like to rework that myself. The new Manta ranch, I think, proportionally, is too large. I'd recommend reducing it lengthwise by a few tiles (and turning that area into an empty construction area or market stall) and making it non-completely-rectangular in shape.

**Comment by Gremyrivolk** [comment]
Alright, dropped Oshan and redid Manta (The image in the main PR has a tile error that I fixed in the final version) but otherwise shows the final layout of the ranch.
I somehow managed to fuck up and corrupt the file resolving merge conflicts but after downloading the PR map file again I somehow miraculously wound up merging a perfectly pristine file that's fully-up-to-date with the last change to the master Manta file with no loading errors as far as I can tell. This is incredibly disconcerting because I have no idea what I was doing and do not understand why there is no longer a problem but since I know so little I have no choice but to roll with it

**Review by flrsh — APPROVED** [review]
Sorry it took me so long to approve this! Your changes look nice!

**Pull request merged**
