### PR TITLE
Reverts medical vendor palette changes.

### PR DESCRIPTION
**Pull request by SgtManGuy**
## About the PR 
Reverts the changes made to the med and nanomed vendors.

## Why's this needed?
Makes medbay colors more consistent. if there's going to be a change to the color scheme it should be all at once.

### CODE REVIEW

**Comment by flappybatpal** [comment]
I feel like this is making a bit of an assumption about the level of consistency.
For example, Oshan medbay right now, red crosses are the minority:
image

I'd rather see people putting effort into PRing more blue crosses, considering the small chance we might get forced to change them by the organisation.

**Comment by frawhst** [comment]
I’m gonna

**Comment by Josephin23** [comment]
i'd rather not have the server commit a war crime, honestly just make all the crosses into blue ones

**Comment by Cherman0** [comment]
I agree with changing back the medivend to red. It pops out a lot more against the blue and white floor palette of medbay (which is important for things you want people to be able to find), and also matches the doctor coat.

**Pull request merged**
