### PR TITLE
Fixes random room runtime checker

### PR DESCRIPTION
**Pull request by TealSeer**
[TOOLING] [BUG]
## About the PR 

Changes random room checker code to actually load the prefabs properly, I didn't get any runtimes on my local server which is suspicious but it definitely loads all the prefabs. Also adds stack trace for catching invalid types that exist in prefabs

## Why's this needed? 

The random room checker does nothing right now due to a bug

### CODE REVIEW

**Comment by amylizzle** [comment]
Make a random room that you know should throw a runtime and test it with that.

**Comment by TealSeer** [comment]
oh good idea

**Comment by TealSeer** [comment]
got it to properly runtime so looks like that works

**Comment by TealSeer** [comment]
lets hear it for failing checks 🎉

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
