### PR TITLE
Interacting with a sink with a soup pot will fill it with water

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Clicking on a sink with a pot in hand will fill it to the brim with water.

## Why's this needed? 
I think this is the interaction most people expect that should happen and not "cleaning it"

@UrsulaMejor Feedback on if this is alright with you because I know this your project so might you might have a different perspective on this.

### CODE REVIEW

**Comment by twoski** [comment]
what does cleaning a pot do? I assumed if you transfer all it's contents out there's nothing to technically clean

**Comment by Carbadox** [comment]
Cleaning blood stains, only visually though as the forensic evidence stays

**Comment by twoski** [comment]
what about a 2-step system

- if it's bloody clean the blood
- if not bloody then fill with water

**Comment by UrsulaMejor** [comment]
sounds fine to me, if the code looks good

**Pull request merged**
