### PR TITLE
Tactical flamethrower

### PR DESCRIPTION
**Pull request by Tarmunora**
[FEATURE]
## About the PR 
Adds a tactical flamethrower for the nukeop firebrand, which comes with a back-mounted fuelpack which stores both the fuel (4000u napalm, subject to change) and propellant, while also acting as a jetpack (because why not).
Replaces the standard napalm flamethrower in firebrand crates.

Additionally moves some flamer code around and renames a few poorly named variables
Allow fireax to be worn on belt

Sprites by Schwick:
sprote

## Why's this needed? 
Nukeop firebrands having the same cobbled-together flamer as staffies felt silly.

## Changelog

```
(u)Tarmunora:
(*)Added tactical flamethrower for nukeop firebrands! Sprites by Schwick
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
@Gannets Please feel free to come up with a better name than "tactical flamethrower". 😃

**Comment by makkipakki** [comment]
this looks really awesome but how do disarms work with it? I'm concerned that my days of stealing the flamethrower and igniting the whole nukie squad are over.

**Comment by Tarmunora** [comment]
You'd have to also steal the backtank

**Comment by makkipakki** [comment]
> You'd have to also steal the backtank

*scream

**Comment by Tarmunora** [comment]
Might be worth making it snap back to the fuelpack a la phone handsets. Hm

**Comment by BatElite** [comment]
Firebrands having a difficult-to-steal flamer is probably better for them overall, since it's already a friendly fire hazard in their own hands. Looks good.

(Also aaa this reminds me I should do the fireaxe PR at some point aaa)

**Comment by Gannets** [comment]
Love the changes, not got any good name ideas atm.

**Comment by ZeWaka** [comment]
> Might be worth making it snap back to the fuelpack a la phone handsets. Hm

Probably not... People can steal just the flamer thing you hold anyways if I understand correctly.

**Comment by Ley-bunned** [comment]
If their inventory is taken up by an ax for a belt, a napalm backpack, and I assume one pouch of incendiary grenades...and probably a mini O2 because you don't want to run internals off your jetpack/fuel, they probably need an anti-flamethrower theft mechanism(phone snapping, I guess) so they can switch to the ax without worrying about their inventory.

**Comment by Tarmunora** [comment]
Re inv management: Flamer can be safely stowed in the fuelpack (click fuelpack with flamer, click it again with open hand to retrieve it), and fireaxe does fit in fannypacks or whatever the nukeop equivalent is called - putting it on the belt is so that pyros who decide to take the RPG pouch or something can still carry around their axe.

**Comment by pali6** [comment]
I didn't check code too closely but I trust you it works.

**Pull request merged**
