### PR TITLE
Changes cargo crate sec token to sec assistant token

### PR DESCRIPTION
**Pull request by Arthur-Holiday**
[BALANCE]

## About the PR 
Changes the token to a sec ass one, also drops the value from 10k to 7.5k

## Why's this needed? 
Makes it harder to get stun weapons, it was very trivial to get your hands on a token from one of these, and I think that's a bad thing.

## Changelog

```changelog
(u)Arthur Holiday
(+)Token on security ressuply cargo crate is now a security assistant token.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
It's easy enough to get your hands on the crate, but then you have to get it open, break into security and redeem the token to get access to the weapons. This requires either an EMAG or a sec ID that you've probably had to mug a secoff for anyway, so you might as well have just taken their taser.

**Comment by Wisemonster** [comment]
> It's easy enough to get your hands on the crate, but then you have to get it open, break into security and redeem the token to get access to the weapons. This requires either an EMAG or a sec ID that you've probably had to mug a secoff for anyway, so you might as well have just taken their taser.

While yes, you do need to enter some kinda sec area to redeem the token, it doesn't have to be main sec. In cog1, there's a sec gear vendor in the checkpoint right next to cargo, meaning all someone needs to do is emag the crate and a door, and they got a tazer, shield, and baton

**Comment by ThatFiveGuys** [comment]
Relevant thread here: https://forum.ss13.co/showthread.php?tid=17741
Not hard to hack into hop and snag aa real fast. Personally I like what this pr is going for, I dont like the execution however. This would make the crate basically useless, itd probably be better to just remove the crate then this. While I assume this is trying to make the crate used for deputization, the stuff sec ass's have is easily found in sec and far more convinent to get by just grabbing it from sec then getting it through cargo. I feel like this would just make the crate never ordered and useless.

**Comment by Wisemonster** [comment]
Wouldn't this pr make it so a secoff who loses all their gear to something like the crusher effectively be demoted to secass when cloned, unless a HoS was on duty?

**Comment by ThatFiveGuys** [comment]
Personally I like the idea cyber suggested in the thread I linked, "Assuming restrictions are tightened, maybe an interesting way to do it would be biological locks? Since it's valuable cargo, NT sends it in special tamper-proof crates: Blasting them open grinds the contents, and they can only be properly opened with the biometric signatures of certified NT security personnel. It prevents the described lower effort play, but still allows antagonists (or desperate crewmembers) some windows such as stealing away a corpse and cutting off the arm, or drawing blood for mutagen or using polymorph, maybe some others that I'm not thinking of." 
Would probably fix basically all of the shittery that comes with that crate but also still keep the qol and shit for sec offs.

**Comment by TobleroneSwordfish** [comment]
>In cog1, there's a sec gear vendor in the checkpoint right next to cargo, meaning all someone needs to do is emag the crate and a door, and they got a tazer, shield, and baton

surely then a better solution would be removing vendors from checkpoints (although that would make them more vulnerable to being destroyed)

**Comment by SirSnek** [comment]
> It's easy enough to get your hands on the crate, but then you have to get it open, break into security and redeem the token to get access to the weapons. This requires either an EMAG or a sec ID that you've probably had to mug a secoff for anyway, so you might as well have just taken their taser.

I just wanted to inform you that you do not need either of those things, any explosion has a chance to break them open scaling with power. Removing sec vendors from checkpoints isn't a good idea, it removes the little purpose they have and makes security a lot more vulnerable as anyone who rushes a bomb roundstart and uses it on the vendor has now removed all security stun weapons from the round.

**Comment by PrimeNumb** [comment]
> Wouldn't this pr make it so a secoff who loses all their gear to something like the crusher effectively be demoted to secass when cloned, unless a HoS was on duty?

Yes.

**Comment by SirSnek** [comment]
Eh, all or most armouries have a locker with I believe 2 req tokens and some other gear. Moving them to a blast resistant sec access only crate in sec should be a good enough solution. It's a high risk high reward area for antags but it still lets secoffs that get gibbed gear up.

**Comment by Josephin23** [comment]
Honestly I feel like making the crate blast-resistant and imunne to EMAGs would be good enough, prevents general shittery by non-antags unless they get AA, though with it you can just get into armory and not have to order the crate at all.
This really causes more problems than it solves, as Wisemonster said earlier it would effectively make secoffs get demoted to seasses upon death unless there's a HoS, giving the role even more power than it already does.
Also don't forget that you get a pinpointer when vending out gear, making just stealing gear from a dead secoff give you a giant downside provided they leave it at sec.

**Pull request closed without merging**
