### PR TITLE
Replace the flockmind deathsound with legally distinct pacman death sound

### PR DESCRIPTION
**Pull request by amylizzle**
## About the PR 
Wakawakawaka

Credit to aquario for the sound.

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
I dont really think this sound or flocks becoming visible on death fit with flocks thematically

**Comment by amylizzle** [comment]
As discussed on discord, alternative perspective: haha silly space ghost go waka

**Comment by FlameArrow57** [comment]
While the sound is funny, I don't think Flockmind needs a pacman death sound, it doesn't make much sense and isn't really in theme

**Comment by flrsh** [comment]
> While the sound is funny, I don't think Flockmind needs a pacman death sound, it doesn't make much sense and isn't really in theme

**Comment by amylizzle** [comment]
sadface

**Pull request closed without merging**
