### PR TITLE
Mobs entering chutes: Adds actionbar and animation

### PR DESCRIPTION
**Pull request by MarkNais**
## About the PR 
Mobs entering chutes through either click-drag, or grab-click will start an action bar and associated animation for being shoved into the chute. Icon of the action bar is dynamic to the type(color) of the chute being entered, and whether the person is entering voluntarily or not. 
I've tried to maintain the delay to be the same half-second pre-PR. Not sure if actionbars come with some initial overhead, so I've set the delay to 0.4 seconds.

Actionbar icon sprites by BatElite.

## Why's this needed? 
**Players instantaneously disappearing from existence while clambering into a chute is dumb.**
Almost all of our mob movement and removal has visual (and *often* audio) feedback:
- Lockers have the opening and closing of their door
- MechComp has swirls
- Telepad has swirls and residue
- Telering has sparks at destination
- Telering handheld portal animates on entry

As silly as it is to hop into a chute while cuffed and pulled by sec, it's bad to have no player-feedback.

Also @UrsulaMejor told me to.

ewZ0lddJGO
(This gif is slower than actual-changes)

## Changelog

```changelog
(u)MarkNstein
(*)Entering chutes now has an animation and action bar. Chute-entry has been made faster.
```

[QoL][FEEDBACK][BALANCE]

### CODE REVIEW

**Comment by MarkNais** [comment]
If I can find a suitable sound in the codebase, I may also add a quite sound too — like I originally intended.

**Comment by flappybatpal** [comment]
Brig chute sound could be used unless there is a risk of it being confused.

**Comment by Gerhazo** [comment]
I like it.
Possibly personal opinion, but maybe it'd look better slightly slower? Not sure how easy it'd be to adjust but if it is maybe it's worth trying out and comparing.

**Comment by MarkNais** [comment]
> I like it.
> Possibly personal opinion, but maybe it'd look better slightly slower? Not sure how easy it'd be to adjust but if it is maybe it's worth trying out and comparing.

Single number change for both action bar time and animation time. `duration`

**Comment by geneva-breaker** [comment]
jumping into chutes is already russian-roulette levels of risk/reward as far as escaping chases- anything that makes that easier to interrupt makes it fundamentally useless in my opinion. 

Additionally if this touches transport chutes, which are meant to instantly repressurize and autoflush as soon as they're occupied, it's going to call for some pretty thick rebalancing. 

kicking and screaming "not everything needs an action bar" right now

**Comment by UrsulaMejor** [comment]
There's already a delay, warc, and has been for a long time. This action bar is the same length of time as that delay.

The current delay is invisible to the player initiating the disposal shove, and imo most things with an invisible delay could benefit from an action bar.

**Comment by pali6** [comment]
Would private (visible only to you) action bars be a better alternative according to you, warc?

**Comment by geneva-breaker** [comment]
Kay, after shootin' the shit with some other folks, here's my advice / request:
1) only play the shrinking animation when/AFTER the action succeeds 
2) make the action bar / icon visible only to the user if self-flushing, globally if flushing someone else

**Comment by MarkNais** [comment]
Some larger context: I developed the animation before I developed the action bar because I thought the animation was the stronger half of this PR-idea. Personally I see action bars as a crutch that we use when animations would be too hard or too complex to fully sprite out and animate. That is to say, I find the action bar largely redundant with the animation playing but it does help add an indicator to players that the action is interruptible.

I lightly disagree with only starting the animation if it succeeded. The animation is representative of the (abstract) action as it is being performed. I think you should play while it's being performed - and is vulnerable to interruption - not once it has succeeded.

I'm ok with a private action bar for self insertions.

**Comment by geneva-breaker** [comment]
the animation's great

anyway the request is specifically to _avoid_ telegraphing the move for stealth and escape reasons- 
balance-wise chutejumping is already very precarious, and displaying the anim while the delay is ongoing makes it a little bit too easy to eject the person before they can flush, which results in a stun. 

also breaks things like hiding in a chute and pulling someone in, as they can see it coming with way too much reaction time.

**Comment by MarkNais** [comment]
> also breaks things like hiding in a chute and pulling someone in, as they can see it coming with way too much reaction time.

Yeah why shouldn't someone be able to resist getting pulled in?

> anyway the request is specifically to _avoid_ telegraphing the move for stealth and escape reasons-
> balance-wise chutejumping is already very precarious, and displaying the anim while the delay is ongoing makes it a little bit too easy to eject the person before they can flush, which results in a stun.

In my opinion, things that should be show-success-after-completion:
- Actions that are discrete in execution, but large in final-affect

things that should be show-as-it-happens:
- Actions that are large and expressive

And I've largely imagined chute entering to look like this goofy cat and it's carboard box: https://www.youtube.com/watch?v=TbiedguhyvM
Yes, chute entering is an escape attempt, but it's motions should not be *stealthy*. I suspect it has historically been regarded as a sneaky thing because it never had an animation or any other indication for years.

However, after watching that video on loop, how does this sound:
- Remove all interuptability from the action; thematically treat it as someone making a strong leap-and-tuck into the chute - pretty hard to stop someone's midair motion.
- Keep the animation starting and timing as is.
- Open the chute UI as soon as the action starts, instead of at the end.

**Comment by Kyle2143** [comment]
I think that this is okay to have an action bar for doing it to other people, not for doing it yourself.

I believe this was discussed before and we came to that conclusion.

**Review by ZeWaka — APPROVED** [review]
code looks good.

**Comment by geneva-breaker** [comment]
Opening chute UI at the begining of the animation actually makes it nearly unstoppable in any way- kind of a problem- because you can send the flush command as you're getting in and bypass the wait. 

The opposite is true when stuffing someone else, as they can open the UI and click eject before they've even finished being stuffed. 

Information availability is a huge problem with anything stealth or trap related, and this is one of the oldest japes. If you intend to turn it on it's head, that's going to take a lot of testing and justification if you don't want to make people mad about it. 
Chute escapes are already *very* difficult to pull off if your chaser has even the slightest indication you intend to jump- and this is going to reduce that chance to zero. 
This could be merged for ass_jam to test it out, but I have a very poor outlook for it, if it still telegraphs this broadly.

**Comment by MarkNais** [comment]
With some IRL stuff taken care of, I can direct my attention towards this PR again...
10 days have passed since last-comment, so I'm gonna try to recap things:

While I didn't *explicitly* type it out in the PR: my intention _was_ to make chute-jumping less stealthy, as the current "popping out of existence" is dumb i.m.o.  From my joined-in-late-2019 perspective, animation-less chute-jumping (and pulling) **being stealthy** seems more like a relic of bad game design than an intentional feature. Like, _why the hell_ is jumping into a chute a stealthy action when I imagine it to look like this cat jumping into a box: https://www.youtube.com/watch?v=TbiedguhyvM
If further rebalancing in terms of interruptability, timing, or otherwise is required, I'm happy to do some testing. (Sadly I couldn't prep this for September's AssDay). And yes, I do find the animation to be much "stronger" than the action bars. I'm comfortable making the self-chute action bar private (or removing it).

Warc mentioned only playing the animation after successful entry: on a technical level, I'm not sure how easy this would be, as the player _and their sprite_ would be hidden within the chute, meaning I'd have to try to replicate their sprite and all it's overlays to create the animation.

One idea: open the UI at the start of the animation, but increase the delay from triggering a flush and the flush executing.

And I'd like to remind: If we can agree to the overall flow of animation / UI / flushing, then further PRs/commits can be made fine-tuning the timing and other balancing considerations. Yeah I'll get the initial flack from the community about breaking their super-epic chute escapes, I was expecting that from the start.

So my proposal as of right now:

- Remove all interruptability from the action; thematically treat it as someone making a strong leap-and-tuck into the chute - pretty hard to stop someone's midair motion.
- Keep the animation starting as soon as the click-drag is done.
- Shorten the animation to 0.2 seconds. My original PR gifs were set to the old delay duration of 0.5 seconds. 
- Open the chute UI once the animation ends. (Same as current behavior)

Hopefully the animation completing quickly will keep chute-jumping semi-viable. I'll record some gifs of the above changes sometime this week.

**Comment by MarkNais** [comment]
ThePotato recommended adding `animate_storage_rustle` and I think that's an O.K. idea. Writing it here for later.

**Comment by MarkNais** [comment]
Oh, ok.
Like, yes, this is on my "agenda", just life stuff snowing me down.
(To share my inner thoughts: Warc being the loudest (and justified) critic of this PR, I was planning on sharing more iterations on this idea in #admin-coder discord, ONCE I got back to working on this)

**Comment by ryebek** [comment]
I'm gonna have to agree with warc that only the player should see the action bar, except when forcing other people in, where everyone can see it. Sneaking into a chute is a very important stealth tactic, and a very fun one at that, so I don't like removing some of its viability as an escape tactic, considering I feel theres a pretty good balance as things currently are. No complaints about adding an animation though, that shits fire(and long overdue).

**Comment by geneva-breaker** [comment]
So uh, where are we even at on this boy?

**Comment by MarkNais** [comment]
What're your thoughts on:

- Remove all interruptability from the action; thematically treat it as someone making a strong leap-and-tuck into the chute - pretty hard to stop someone's midair motion.
- Keep the animation starting as soon as the click-drag is done.
- Shorten the animation to 0.2 seconds. My original PR gifs were set to the old delay duration of 0.5 seconds.
- Open the chute UI once the animation ends. (Same as current behavior)

**Comment by MarkNais** [comment]
I've made the changes per my last message *except* private action bars. (Stuns and trying to do 2 things at once will still interrupt the actions)
Private bars are a different sub-class of action bars. To implement the desired effect I'd have to double-implement the action bar, once as private, and again as public. Out of scope of this PR: making "private-ness" an argument instead of a sub-class would be more flexible.

**Pull request merged**
