### PR TITLE
Changes the current tail regrowth cooldown from 5 minutes to 2 minutes.

### PR DESCRIPTION
**Pull request by Momoberry**
## About the PR 
Just changes the timer on the ability to be two minutes, as it felt too long to me at five minutes for the lack of gameplay implications it had. I'm wondering now if the wriggling time is too long, but i could actually not find the code for that feature. It wriggles around for a rather insane amount of time.

## Why's this needed? 
I wanted it. Other lizard players liked the idea, and lizard tends to be a "weaker" race than other options, so I'd like their goofy abilities to be less of a cooldown to balance it out. They don't have insane benefits like radproof or immunity to plasmaglass, etc. Two minutes is more than enough time to prevent people from spamming tails everywhere, which is why it got a significant cooldown in the first place.

## Changelog

```changelog
(u)MomoBerry
(+)Adjusted the tail regrowth ability cooldown from five minutes down to two minutes.
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
FWIW bartimus added the wriggling behavior, so you'll want to ping him in order to situate that

**Comment by Momoberry** [comment]
Oh, accidentally labelled it as a bug, pfft. My bad

**Comment by Momoberry** [comment]
There, bit more specific now instead of being vague!

**Comment by Bartimeus973** [comment]
If you want to change the duration of the living, twitchy tail, head to code/obj/critter/misc.dm, look for /obj/critter/livingtail and change **maxsteps = rand(10,20)** to another number!

**Comment by Momoberry** [comment]
Tweaked it, now it can either flop around for a moment or for a solid 20 seconds

**Comment by WALPVRGIS** [comment]
Looks good to me!

**Pull request merged**
