### PR TITLE
fixes #1834

### LINKED ISSUE #1834: Sleeper agent objective cannot achieve on Cogmap1
Submitter: Wasaws

**To Reproduce**
1. Become a sleeper agent in corgmap1.
2. Obtain the following objective: Objective #1: Activate the computer mainframe's self-destruct charge.
3. There was no nuke in the computer mainframe.
4. Failed the objective.

**Expected behavior**
I was hoping to see a nuke as what the wiki said, but there wasn't one...

**Screenshots**
Don't have it

**Additional context**
It's confused me for the whole game until I ask a mentor, in which they state that there is no nuke in corgmap1. But different than WIKI which it says there was one... so I'm even more confused now...

Reported on: Goonstation 2020-08-16 00:17:29

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
fixes #1834

### CODE REVIEW

**Comment by Gerhazo** [comment]
Was this tested? The way traitors and sleeper agents setup objectives work differently as far as I know. An objective set already includes escape objectives and whatnot, whereas this code tries to add them in manually. The following lines of code also start rolling a random amount of objectives to pick and other things and the list it will try to pick from (the objective_set) is a list of lists (a list of regular objectives and a list of escape objectives). This feels very broken and non-compatible to me.

**Comment by pali6** [comment]
Removing /regular is pointless as it was never included in the first place.

**Review by pali6 — CHANGES_REQUESTED** [review]
Oh and also Gerhazo is totally right. You are calling typesof on a completely wrong type.

**Comment by Gerhazo** [comment]
> Oh and also Gerhazo is totally right. You are calling typesof on a completely wrong type.

The typesof would be correct (of just the objective_set, that is, though it would also need to pick() one at random), as there are several different traitor objective_sets, it's just the following lines that handle picking one and distributing its objectives need to do it in a completely different way.

If you (refering to Carbadox, or anyone else for that matter) continue to work on this, I recommend looking into the definition of objective_set as well as examples of it being used. It basically handles everything for you when it's created with the target antagonist mob as the argument.

**Pull request closed without merging**
