### PR TITLE
Emergency suits/tanks for QM emergency crate

### PR DESCRIPTION
**Pull request by Kubius**
[REWORK] [INPUT]
## About the PR 

Alters the complement of the Emergency Equipment crate QM can order, replacing half of the air tanks with emergency O2 tanks and adding emergency space suit sets of the sort that can be found in lockers or starting boxes. The complement of these sets also decreases to four, to compensate for their improved completeness and usability.

## Why's this needed? 

Means of attaining additional emergency gear of this sort are currently limited, if not nonexistent - upgrading the emergency crate significantly improves their availability without making it completely trivial, and makes it a more generally appealing pick outside of emag shenanigans.

**Important note: If you believe this would too heavily lessen the impact of hull breaches, please do not hesitate to reject it.** This is a concern that I believe merits consideration, and I've tagged this as input wanted for that reason.

## Changelog

```
(u)Kubius:
(+)QM's emergency crate now contains emergency-grade spacesuits and tanks.
```

### CODE REVIEW

**Comment by flrsh** [comment]
I like this change! Though, I'd still like to see some regular air tanks in the crate, because even though they're not the ones with the "emergency" prefix, they definitely feel a lot more like it. Maybe have a mix?

**Comment by Kubius** [comment]
A mix of tank styles sounds reasonable enough - should they be additional (i.e. retain the 4 emergency O2 tanks and also add 2 air tanks) or a replacement for some of the O2 tanks (i.e. 2 and 2 or 3 and 3)?

**Comment by flrsh** [comment]
I think a replacement for some would be good!

**Comment by Kubius** [comment]
Contents tweaked - now contains 2 emergency O2 tanks and 2 air tanks.

**Pull request merged**
