### PR TITLE
Adds kitchen fountains to all the maps in rotation that don't have them

### PR DESCRIPTION
**Pull request by TTerc**
## About the PR 
As the title says (well, all the maps except Clarion)

## Why's this needed? 

Currently, only donut 3 and manta have kitchen fountains and they're pretty cool. Chefs always deserve more love, right?

## Changelog

```changelog
(u)TTerc
(+)All the maps in rotation except Clarion now have kitchen fountains.
```

### CODE REVIEW

**Comment by Sovexe** [comment]
No changes to Clarion are currently permitted

**Comment by TTerc** [comment]
alright

**Comment by flrsh** [comment]
I don't think maps that have already have a connected kitchen and bar need a fountain. I think it's good if the chef has to come into the bar and ask for something (or dispense it themselves and face the wrath of the bartender).

**Comment by TTerc** [comment]
> I don't think maps that have already have a connected kitchen and bar need a fountain. I think it's good if the chef has to come into the bar and ask for something (or dispense it themselves and face the wrath of the bartender).

Hmm, I kinda don't understand your concerns:
-Some maps on the list (Destiny and Horizon) don't give chefs bar access at all, those places are separate
-If bar and kitchen are connected to each other, chef and bartender are forced to interact with each other anyway, as the chef usually leaves the food at the bar table. And they usually chat with each other very often wiliingly, so putting the kitchen fountain wouldn't really remove any level of interaction between them
-Most importantly, kitchen fountain is a pretty neat piece of equipment that has some unique reagents that can't be acquired by simply asking the bartender for them. And I always thought of them as a nice way to get funny soup bases. Who wouldn't like a peper soup?

I'll throw in a screenshot of the kitchen fountain UI for reference, some people on discord were surprised this thing even exists and they didn't know what it contains:

**Pull request closed without merging**
