### PR TITLE
Always add people to the respawn controller on ghostize

### PR DESCRIPTION
**Pull request by frawhst**
[bug] [cleanliness]
## About the PR 
Currently there's a bunch of niche things that Just Delete You (science ghost, macho man slim jim, etc). Now whenever you get turned into a ghost for any reason, you get added to the respawn controller.

Note that ghostize is also used for things like turning target observers into regular observer ghosts; in this case they'll already be in the respawn controller, but the check in `subscribeNewRespawnee` is super cheap, so that shouldn't be an issue.

Also removed some un-needed code from `ghostize` because why not.

## Why's this needed? 
Bunch of niche things or weird interactions weren't subscribing people to the controller. Now you'll always get it UNLESS something is deleting your mob without ghosting you, but that's a whole other problem.

### CODE REVIEW

**Comment by pali6** [comment]
Is client color reset somewhere else? I guess it'd make sense if it was in /mob/Login or something like that but I'm too lazy to check.

**Comment by frawhst** [comment]
> Is client color reset somewhere else? I guess it'd make sense if it was in /mob/Login or something like that but I'm too lazy to check.

https://github.com/goonstation/goonstation/blob/f7f6dd9e04de2afb6d1ec1bef48db7ef0591a831/code/mob.dm#L515
Yep

**Review by pali6 — APPROVED** [review]

**Comment by pali6** [comment]
Hm just some thoughts. What happens if a ckey gets subscribed twice (because of death + ghostize). Also what happens if O.ckey is null?

**Comment by frawhst** [comment]
> Hm just some thoughts. What happens if a ckey gets subscribed twice (because of death + ghostize).

subscribeNewRespawnee checks if the person is already subscribed, and doesn't do anything if so.
> Also what happens if O.ckey is null?

The top of `ghostize()` requires the mob to either have a mind or a key, and doesn't do anything if it has neither. I'd assume that it has to have a ckey in either of those cases. There is still the issue that if you get crushered/gibbered/etc (alive -> body deletion) while disconnected, you don't come back to a ghost, but that's a larger issue than this PR is touching.

**Pull request merged**
