### PR TITLE
Removes e-meter, minor clean up of an old file

### PR DESCRIPTION
**Pull request by Carbadox**
## About the PR 
Removes the e-meter and replaced duplicated code of instruments and cardboard boxes with a comment that directs their current location.

## Why's this needed? 
The E-meter is supposedly a references/joke about Scientology and that's about it. It serves no purpose than clutter and we've got a couple of MHelps from people confused about it. It uses the same sprite as the securitron which is also kind of bleh.

Removed the duplicate code while I was hanging around in the file.

### CODE REVIEW

**Comment by flrsh** [comment]
I think it'd be cool to get it a new sprite and give it a bit more flavor if we think it's too bland right now.

**Comment by Tarmunora** [comment]
Make it give vague karma readouts

**Comment by Carbadox** [comment]
If anyone wants to maintain it l, then be my guest. 

But I don't imagine there's alot of people who are/would be and neither am I, as I see this, as mentioned above, clutter

**Review by ZeWaka — APPROVED** [review]

**Comment by Kyle2143** [comment]
Don't remove this. Though it could have a better sprite.

**Comment by Carbadox** [comment]
The emphasis for why this is clutter is being applied here to the fact that its using an old sprite, will very most likely not receive any attention for the foreseeable future, is only used in two distinct places and serves no purpose other than to be a random number generator. 

The joke is least important part.

**Comment by Kyle2143** [comment]
The joke is the most important part. We have plenty of joke/reference objects in the game, many of them old. I don't really see a reason to remove this one.

**Pull request closed without merging**
