### PR TITLE
Unstick spaced atmos groups

### PR DESCRIPTION
**Pull request by Azrun**
[bug - major]
## About the PR 
Skip space_fastpath() when a group aborts processing.  
Add diagnostics overlays to atmos and pipes to see molar distributions.
Cleanup a runtime found when trying to debug atmos.

Impacts:
Given an area that is spaced via bomb or RCD and was re-grouped...  That area will no longer act as a buffer when interacting with other groups. (Seems like the desired behavior, but will increase effect of spaced station sections)
image

## Why's this needed? 
Resolves issue of being unable to purge burn chamber due to spaced ATMOS group taking in gas, aborting group processing, spacing the group and merging before processing individual tile's neighbors are processed.  This was causing spaced groups to essentially be SPACE barriers. 

Current | Fix
---|---
 Previous Behavior | Fix

## Changelog
```
(u)Azrun:
(+)Should now be able to vent combustion chambers.  Spaced areas of the station should now spread.
```

### CODE REVIEW

**Comment by Tarmunora** [comment]
Will this be the PR that kills hellburns? 👀
(iirc combustion chamber spacing weirdness is related to hellburns being possible)

**Comment by moonlol** [comment]
> Will this be the PR that kills hellburns? 
> (iirc combustion chamber spacing weirdness is related to hellburns being possible)

thats a good thing though

**Review by ZeWaka — APPROVED** [review]

**Comment by Azrun** [comment]
Hellburns seemed fine?  I had to turn off gas pumps and wait to take the picture because it was still getting so hot you couldn't see that the fix did anything without looking at molar quantities.

**Comment by Tarmunora** [comment]
#yolo

**Pull request merged**
