### PR TITLE
Makes catwalks auto-connectable

### PR DESCRIPTION
**Pull request by CaioFrancisco**
[CLEANLINESS] [INTERNAL]
## About the PR 

This PR makes it so catwalk's sprites can automatically connect to one another when one is placed near another. There are a few things to note about the PR though:
- This does not remove all the different catwalk types for different icon_states, primairly because maps still use it, and I don't want to touch maps because of the absolute hell it is to manage a PR including map changes.
- The icon_states for catwalks in the original `icons/obj/grille.dmi` file have not been removed, to not possibly break any secret content stuff.
- The sprites for the normal catwalks south, north, west, east and not connecting to another didn't exist originally, and since I'm not a good spriter, I simply repeated the north + south sprite for the vertical sprites and the west+east for the horizontal ones. If it is absolutely necessary though, I will try to sprite those as well.

## Why's this needed? 

To get rid of the abysmal pain that dealing with catwalks internally is. And because I'm planning to do constructable catwalks in the near future.

### CODE REVIEW

**Comment by RelentlessGarbage** [comment]
Player-built catwalks, you say? Consider my interest piqued.

**Comment by CaioFrancisco** [comment]
I'm gonna do it after (and if) this PR gets merged. If catwalks can't auto-connect to each other, any player-built catwalk would look broken. I'm mostly thinking of 1 rod for lattice and 1 rod for building the catwalk, which amounts to a metal sheets per catwalk in empty space.

**Review by flappybatpal — APPROVED** [review]
Seems ok to me. The seam on cross intersections feels a bit more pronounced but there was already one.

We should follow this up with auto catwalks on maps and cleaning up the sprites.

It might be good to have automatic lattice too?

**Comment by CaioFrancisco** [comment]
Since the code applies on all catwalks, all catwalks in all maps already auto-connect (and override the previous directions. If that sounds destructive, I can try to code an exception for the case-scenario where there's already a direction.) Yeah, the sprites do need some cleaning up, I'd say the maintenance ones specially, but a proper spriter would probably disagree with me. Also, lattice have special sprites connecting to each other?!

**Comment by flappybatpal** [comment]
Apologies, I misunderstood the change replacing all existing catwalks.

**Pull request merged**
