### PR TITLE
Item health pass

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[CLEANLINESS]
## About the PR 
Makes item health default to being based on item weight and adds specific health values for a lot of items where weight doesn't correlate for inventory reasons.

Weight class health values are as follows:
TINY: 2
SMALL: 3
NORMAL: 4
BULKY: 6
HUGE: 7
GIGANTIC: 8

Notable health changes from this:
Paper 10 -> 2
Jumpsuits 50 -> 10

## Why's this needed? 
Item health is used to determine how fast something burns, is dissolved in acid or is absorbed by a flockdrone. Currently almost all items have the default value of 4, with a couple of weird exceptions such as jumpsuits having 50 (please let me know if there's a good reason for this)
With flock being actively worked on and Nadir (#7730) using acid as a core mechanic it would be nice for item health to make sense.

### CODE REVIEW

**Comment by Eagletanker** [comment]
probably should make them last longer cause that means theres like no time to put out items

**Comment by TobleroneSwordfish** [comment]
> probably should make them last longer cause that means theres like no time to put out items

Most items have more health after this PR, it's only tiny and small size items that have less. (could bump the whole lot up so tiny is at where most items are now I suppose)

**Comment by Momoberry** [comment]
Looks like a good change.

**Comment by NightmareChamillian** [comment]
If not done already, you think you could up the health for pouches and emergency air tanks? They're two tiny items that should probably be more durable than not.

**Pull request merged**
