### PR TITLE
Allows scan_health proc to scan eyes as well

### PR DESCRIPTION
**Pull request by CaioFrancisco**
## About the PR 

Health analyzers and other medical equipment that scan for organ health will be able to scan eyes as well.

## Why's this needed? 

Gotta be able to scan those beautiful eyes of yours.

## Changelog

```changelog
(u)Caio029
(+)Allows health analyzers with organ scan upgrade to scan for eye health as well.
```

### CODE REVIEW

**Comment by CaioFrancisco** [comment]
I'm unsure if this counts as a feature or not. Tell me your opinion and I may close this PR to re-open it after the feature freeze.

**Comment by ZeWaka** [comment]
changelog format is incorrect

**Comment by CaioFrancisco** [comment]
that should be it, i think

**Comment by ZeWaka** [comment]
> that should be it, i think

nope, you shouldn't've deleted the template 😩 - do you need me to do it for you? try just looking at any other pr

**Comment by CaioFrancisco** [comment]
Incompetence is my way. I hope the changelogs are correct now.

**Pull request merged**
