### PR TITLE
Add CommasterLite to Mining outposts

### PR DESCRIPTION
**Pull request by JORJ949**
## About the PR 
Adds CommasterLite program that has all the functionality of commaster except it cannot recall the shuttle
Adds commasterlite consoles to:
- The mining outpost in the asteroid field
- The Pasiphae on nadir (replaced full comms console+added dish)
- Oshan's Tech outpost

Consoles could use a better name than "Light communications console" but I couldnt think of one

## Why's this needed? 
More alternative methods to call the shuttle are good but you dont want someone to recall from offstation

## Changelog 

```changelog
(u)JORJ949
(*)The mining outpost is now equipped with communications consoles incapable of recalling the shuttle.
```

### CODE REVIEW

**Comment by TobleroneSwordfish** [comment]
Why would a syndicate spy outpost be able to call an NT shuttle though?

**Comment by JORJ949** [comment]
> Why would a syndicate spy outpost be able to call an NT shuttle though?

What if it called the syndicate version of the shuttle (do these exist for all maps?) with some additional flavour of NT wondering why the syndicate decided to offer their crew a shuttle

Other explanations are that they stole the tech and codes because they want their operatives as trusted by NT as possible and them dying sat on an exploded station isnt very good for business

Honestly no explanation will fit perfectly this is more to provide alternate options to calling the shuttle if comms dishes go down, I didn't put much thought into lore

**Comment by JORJ949** [comment]
Moved from post to NT outposts because as pointed out, it doesnt particularly make sense.

**Comment by JORJ949** [comment]
And over the course of a day I have determined this feature is probably not needed and very minor. I should think before I code...

**Pull request closed without merging**
