### PR TITLE
More misc hats + new special baldcap

### PR DESCRIPTION
**Pull request by binarysudoku**
[HUMAN RESPRITE]
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
new bald cap: the strange bald cap (5head)
image

### CODE REVIEW

**Comment by ZeWaka** [comment]
why does the baldcap just have no sprite at all now?

**Comment by binarysudoku** [comment]
> why does the baldcap just have no sprite at all now?

@Flaborized had the idea to remove the sprite but keep the "disable hair" flag so that it allows you to have bald cap that matches to skin tone, rather than always being the same white skintone

**Comment by flrsh** [comment]
Why do some hats have N or S sprites that are one pixel taller/shorter than all the other directions?

**Comment by binarysudoku** [comment]
> Why do some hats have N or S sprites that are one pixel taller/shorter than all the other directions? In particular, the firefighter hat, the jetson hat, the cyalume knight hood, the cwhat hat, the witchfinder hat, and the tophats.

some hats are tilted backward, or sit back on the head (eg. the tophats) so theyll be a pixel south when looking north

for the most part i THINK its correct, but if there are any that look incorrect with that in mind please do let me know and ill adjust them

**Comment by flrsh** [comment]
> some hats are tilted backward, or sit back on the head (eg. the tophats) so theyll be a pixel south when looking north
> 
> for the most part i THINK its correct, but if there are any that look incorrect with that in mind please do let me know and ill adjust them

That makes sense! I can't tell if they look correct or incorrect from the screenshots, but it'd be super easy to nudge some pixels if any of them end up looking odd ingame, so I think it's all good! Really nice work as always!

**Review by flrsh — APPROVED** [review]

**Pull request merged**
