### PR TITLE
Resprite for the communication console

### PR DESCRIPTION
**Pull request by ThyOverlord**
## About the PR 
This PR resprites the Communications console found in  
```
icon = 'icons/obj/computer.dmi'
icon_state = "comm"
```
image
This resprite redesigns them to more accurately show that they are a communications console and helps variate it from the other highly similar consoles.

Sprite-0002-export

https://github.com/goonstation/goonstation/assets/73948103/8d292f90-eb8a-48fb-92b4-aa3295e960c1

## Why's this needed? 
Requested via the "Wanted Resprites/Redone Assets" by ZeWaka

### CODE REVIEW

**Comment by ZeWaka** [comment]
changelog not major nor necessary

**Review by ZeWaka — APPROVED** [review]

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
> err... is everything good? do you need me to do anything?

You or someone else will need to merge master in.

**Comment by ThyOverlord** [comment]
YIPEEE ALL checks PASSED WOO
(THANK you glowbold and leah 🙏)

**Comment by ThyOverlord** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ThyOverlord** [comment]
we try one more time

**Comment by ZeWaka** [comment]
hello it is me overlord i made this code yes

**Pull request merged**
