### PR TITLE
Replace borg upgrade sprites, update descriptions.

### PR DESCRIPTION
**Pull request by BatElite**
## About the PR 
Replaces the current cyborg upgrade sprites with ones that are more visually distinct. The descriptions of nearly all of them are adjusted to better fit the new sprites, explain their functionality better, or for (admittedly nitpicky) consistency between descriptions. The HUD graphics for cyborg upgrades are altered slightly to account for the new sprites being considerably larger.

upgradecomparison
Left to right, top to bottom:
Efficiency, speed, propulsion, teleportation, recovery, repair
Meson, spectroscopic, prodoc, construction visualizer (has it's own sprite now), force shield, heat shield
Expansion, recharge pack, repair pack

(Yes you can still get the construction visualizer from robotics fabs.)

## Why's this needed? 
The new sprites are much more visually distinct and interesting than the old boxes.

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Resident spriters are cool with it, so fine with me.

Only one that seems off to me is the recharge pack - it's a green tank, but the self-repair upgrade has green tanks on it as well (as opposed to the repair pack, which has an orange tank).

Any chance you could clear up that inconsistency?

**Comment by Tiggersaurus** [comment]
I fucking love you. These look amazing O_O

**Comment by BatElite** [comment]
> Only one that seems off to me is the recharge pack - it's a green tank, but the self-repair upgrade has green tanks on it as well (as opposed to the repair pack, which has an orange tank).
> 
> Any chance you could clear up that inconsistency?

I have no problem with making it power-stepping/tank thingy orange, which would look something like this:
Autorecoverytweak2

That look better?

**Comment by mordent-goonstation** [comment]
> > Only one that seems off to me is the recharge pack - it's a green tank, but the self-repair upgrade has green tanks on it as well (as opposed to the repair pack, which has an orange tank).
> > Any chance you could clear up that inconsistency?
> 
> I have no problem with making it power-stepping/tank thingy orange, which would look something like this:
> Autorecoverytweak2
> 
> That look better?

Works for me! Just going for some consistency with "repair = orange" and "energy = green" or whatever, as you lose the visual icons which give a more familiar cue what they do.

**Pull request merged**
