### PR TITLE
Resprited the barrel-fire.

### PR DESCRIPTION
**Pull request by Enderthunder**
## About the PR 
This PR resprites the barrel0 and barrel1 in stationobj.dmi

this pr is also compatible with a possible expension in the world of barrels.

BarrelUltra

## Why's this needed? 

I felt that this was needed as the current sprite is quite old and it shows,
This is part of the respritement project when it comes to updating old sprites which are still in use, but look old or stand out too much. 
Also because i became bored but i still wanted to help out and resprite something.
this project has also sparked the idea of a barrel system/storage compartment, this idea however requires more thought.
and admin input.

Massive Shoutouts to Arthur-Holiday for the amazing sprite and palette, you are the BEST!

barrelia1
barellia2
barellia3

### CODE REVIEW

**Comment by Arthur-Holiday** [comment]
Post new sprite In game pls, preferebly somewhere where it spawns naturally

**Comment by Enderthunder** [comment]
> 

ah, i seem to have forgotten to do so, i will do so immediately

**Comment by Enderthunder** [comment]
i will add some minor changes to this post tomorrow based on feedback.

**Comment by Gannets** [comment]
Looks much better now. Would appreiate seeing the fire animation too before merge.

**Review by Gannets — APPROVED** [review]

**Comment by ZeWaka** [comment]
oh yes this is much more metallic and gritty than the previous sprite, good work

**Pull request merged**
