### PR TITLE
[SERIOUS!!!!!] REBALANCING "LRP" PISS

### PR DESCRIPTION
**Pull request by mathis650**
## About the PR 

PISS IS LRP! IT RUINS GOON MAIN'S HRP EXPERIENCE...... PISS IS GROSS! PISS IS NOT FUNNY!!! IM NOT LAUGHING!

## Why's this needed? 

PISS IS GROSS. PISS SLIPPED ME! PISS IS STINKY!!!!!
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

## Changelog

```changelog
(u)matlap
(*)FUCK PISS
(+)GET THE VOICES OUT OF MY HEAD
```

### CODE REVIEW

**Comment by comradef191** [comment]
FINALLY
WE CAN PLAY IMMERSIVELY

**Comment by MatheusIsNotAvailable** [comment]
+1 to this, can we also remove farts? Thanks for making this game more serious

**Comment by mathis650** [comment]
removing farts is next!!!!! people arent ready for it yet 🤬🤬🤬

**Comment by mathis650** [comment]
sorry guys my cat walked across my keyboard and closed the pr..... merge this devs.... unless you are cringe lrp player 
image

**Pull request closed without merging**
