### PR TITLE
Autoinjector resprite (Adoption of #7100)

### PR DESCRIPTION
**Pull request by DisturbHerb**
[MEDICAL][OBJECTS]

## About the PR 

This is an adoption of #7100 by @BatElite with minor code changes. The description below has been copied verbatim from the original PR.

Fancy sprites for autoinjectors (based on real life ish designs), with ever fancier animations on using them

- [ ] VR flavours
- [ ] Big flavours (+ figure out what to do with animations for them)
- [ ] ~~The state I left the icon updating code in is uhhhh~~
  - Superseded by this PR.

This is just a brief draft for now I'm gonna leave this for now and bap the morgue PR

image

## Why's this needed? 

New sprites good, perhaps.

## Changelog 

```changelog
(u)BatElite
(+)Auto-injectors have been resprited!
```

### CODE REVIEW

**Comment by NightmareChamillian** [comment]
I love the art, I think the sprites are great, but I'm concerned about the practical implications of merging this: 

spent autoinjectors, especially later in a round, tend to litter medbay's floor. Having larger autoinjector sprites, as well as ones that don't quite as obviously differentiate between spent and unspent seems like it'll detract slightly from QoL.

**Comment by DisturbHerb** [comment]
> spent autoinjectors, especially later in a round, tend to litter medbay's floor. Having larger autoinjector sprites, as well as ones that don't quite as obviously differentiate between spent and unspent seems like it'll detract slightly from QoL.

maybe doctors should try using the bin /j

the photo is rather old given that the PR is itself rather old and was iterated on before it closed, they're easier to differentiate *now* at the very least

**Comment by Glamurio** [comment]
> I love the art, I think the sprites are great, but I'm concerned about the practical implications of merging this:
> 
> spent autoinjectors, especially later in a round, tend to litter medbay's floor. Having larger autoinjector sprites, as well as ones that don't quite as obviously differentiate between spent and unspent seems like it'll detract slightly from QoL.

I don't necessarily think that people littering the floor should be a reason not to have nice, easy readable sprites. If anything, dirty ground is a great reason to create gameplay to clean up or call a janitor. Some medbays even have a vacuum cleaner, just use that.

**Comment by MeggalBozale** [comment]
I don't think it would do much to make the sprites 'more obvious' except encourage people to clean up after each other using autoinjectors. And I certainly don't see it as a reason to not have cooler sprites. Also, it's not like there was much opportunity to tell between spent/unspent as-is.

**Comment by flappybatpal** [comment]
They are already litter, if anything having them larger might encourage more tidying up.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
