### PR TITLE
Streamline Destiny Engineering to be more in line with other maps

### PR DESCRIPTION
**Pull request by Glamurio**
[GAME OBJECTS] [STATION SYSTEMS] [BALANCE] [QOL] [INPUT WANTED]

## About the PR 
Adds a power transmission laser to the south of engineering, where the auxiliary comms dish was located and moves the comms dish to the north of the ship instead. Adds a gas mixer to the combustion chamber, alongside an engine output monitor. Rewires some of the cables, moves the furnace crates to more appropriate spaces.

## Why's this needed? 
Destiny was missing a PTL, even though it used to have one. It was also crucially missing a gas mixer, unlike all other maps. These changes will bring Destiny more in line with the engineering departments on other maps.

## Changelog

```changelog
(u)Glamurio (Ryou)
(*)Add PTL and Gas Mixer to Destiny to put it more in line with other maps.
(+)Relocated furnace crates for both coal and cerenkite.
```

### CODE REVIEW

**Comment by nefarious6th** [comment]
There's a construction room I'd much rather have the PTL put in that was reserved for the PTL once someone got done making a vertical version of it. I would much rather a PR that does that versus sort of carelessly tossing it in the bottom of engineering.

I'm a fan of the manual mixing but I'll let others give feedback on that.

**Comment by Glamurio** [comment]
Hey, I'm 100% with you, a vertical PTL would be a lot more sensible, though I disagree with the notion of waiting for someone to be done with it until we put a PTL on the map. I don't think the placement is careless, I felt like it was the only sensible spot the PTL could go without interfering anywhere else. But just so I understand, could you show me which location this PTL was supposed to go?

The mixing aspect though I don't have strong feelings on. I've heard complaints from engineers in-game that dislike Destiny because of that, and I saw no reason to not include it, it's essentially QoL.

**Comment by nefarious6th** [comment]
Construction room is to the right of main engineering. 

Just make sure PTL direction doesn't vaporize anything exiting/entering cargo

**Comment by Glamurio** [comment]
Just as an update on this, I'm currently working on a vertical PTL so that I can place the PTL into the construction site as discussed.

**Comment by ZeWaka** [comment]
don't really think destiny should have a ptl at all

**Comment by Glamurio** [comment]
image
So, before I go any further with this, I have some questions how you envisioned this.

Is the laser meant to be positioned like that? Would you replace the walls with glass? Should the laser be moved to the right to shoot out the window instead? Would that damage the heater?

ZeWaka, could you elaborate why you're against PTL on Destiny? It seems unclear to me, and also any other fellow Engineers I've encountered.

**Comment by ZeWaka** [comment]
> ZeWaka, could you elaborate why you're against PTL on Destiny? It seems unclear to me, and also any other fellow Engineers I've encountered.

doesn't really work lorewise

**Comment by Glamurio** [comment]
Time to make a forum thread, in that case.

**Pull request closed without merging**
