### PR TITLE
Add hotkeys to store to/unstore from belt and backpack

### PR DESCRIPTION
**Pull request by FlameArrow57**
[PLAYER ACTIONS][FEATURE][QoL]

## About the PR 
Adds hotkeys that let you automatically store items specifically to the storage in your belt or backpack slot. Default key is "H" for belt and "N" for backpack
-Pressing the hotkey will automatically store anything that you are holding to the storage item in that slot
-You don't need the storage UI open for it to work
-It keeps track of the last item you stored, so pressing the hotkey again will automatically take what you last stored out of the storage, without you needing to open the UI

## Why's this needed? 
-QoL/faster player inventory interaction

## Changelog 

```changelog
(u)FlameArrow57
(*)Added two new hotkeys for auto-storing/unstoring items to/from your belt storage (default "H") and backpack storage (default "N")
(+)Hotkeys do not need the storage UI to be open, and have a 1 second cooldown on alternating store/unstore actions
```

### CODE REVIEW

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Not sure about the rest of the PR but this in particular is an "oh god no":
> It keeps track of the last item you stored, so pressing the hotkey again will automatically take what you last stored out of the storage, without you needing to open the UI

This would let you take out a stun baton/gun/other weapon for a single game tick, hit someone with it and then stow it again without giving them any chance to respond or disarm you. You could bind it to a mouse key, hover your cursor over someone and press `side mouse -> left click -> side mouse` for a free attack.

In general I'm not too sure about adding *even more* hotkeys, especially quick swap ones that more or less require you to rebind them to be useful. Seems like it's adding to the pile of things you need to learn/set up for combat.

**Comment by FlameArrow57** [comment]
Okay, intent was mainly for QoL not exclusive to combat - what about adding a click delay to the hotkey? not sure if that'be counter intuitive or not

**Comment by Glamurio** [comment]
The only way I could see this work out is if it started a relatively quick action (ca. 1 second or so), that way you're about as fast, albeit a little slower than doing it manually, but it is more convenient. Just be sure to make the action private and uninterruptible.

**Comment by ZeWaka** [comment]
delay would make this a lot more feasible

**Comment by FlameArrow57** [comment]
Okay I added a cooldown on taking an item out, which triggers when storing the item

**Comment by FlameArrow57** [comment]
Okay it now has cooldowns on the hotkey for alternating storing/unstoring, but you can still quick store a bunch of items

**Comment by FlameArrow57** [comment]
@TobleroneSwordfish Are you okay with this PR if it's only to quick store to belt/backpack, but not take out?

**Pull request closed without merging**
