### PR TITLE
Re-Add Status Display

### PR DESCRIPTION
**Pull request by Azrun**
## About the PR 
Demo: https://streamable.com/9182z1
Adds Status Control back to all PDA's that previously had them.

- [ ] Likely needs evaluations on MAC to ensure I didn't screw up the font...

## Why's this needed? 
https://github.com/goonstation/goonstation/projects/2#card-38790833

## Changelog

```changelog
(u)Azrun
(*)Status Displays are back (but as of right now not placed on all maps).
```

### CODE REVIEW

**Comment by Azrun** [comment]
image
Example of original implementation

**Comment by Zonespace27** [comment]
It'd be interesting if instead of them working by spess magic, they worked with packets, albeit requiring a headpass to alter them?

**Comment by Azrun** [comment]
> 
> 
> It'd be interesting if instead of them working by spess magic, they worked with packets, albeit requiring a headpass to alter them?

What spess magic to do you speak of?!? This is nothing but farm to table certified organic signals! (As per original implementation.)

**Comment by WALPVRGIS** [comment]
Ooh, do these use a specific font? I feel like it could be styled differently to give the text more space while still being readable if so. :0 These are looking great so far. :)

**Comment by Azrun** [comment]
> 
> 
> Ooh, do these use a specific font? I feel like it could be styled differently to give the text more space while still being readable if so. :0 These are looking great so far. :)

I made a custom font to mirror the old sprites.  Based on feedback regarding readability they have at least 1 pixel of kerning and are using an outline to improve readability. https://cdn.discordapp.com/attachments/834308203041783868/870420993854820472/StatusWindowDemo01.mp4 shows an example of kerning removed from `A` and `B`.  Original goal was to provide 1:1, but I guess I've failed that with the kerning and outline.... 😜 

@WALPVRGIS What stylistic changes do you think would help?

**Comment by WALPVRGIS** [comment]
Ohh I see what you mean! Yeah kerning at this resolution is absolute hell, lol. Hmm, if the reason for the outline is readability, might be worth just removing the outline and making the screen itself darker for contrast? I guess it depends on how much like the originals you want it to look though! :)

Here's a quick example i bucket-filled in photoshop, ehe. I think I darkened the outer column of pixel on the lettering too, though I'm not sure if this is in the right direction;

screenexample

**Comment by Azrun** [comment]
I think that looks a LOT better. Darkening the border improves readability by giving the illusion of space with kerning removed, the original sprite _glyphs_ had that only on the right side which helped but sometimes looked squished depending on the characters.

That'll be easy enough to whip up a quick demo for. Thanks!

**Comment by Azrun** [comment]
image
image
Adjusted  ~ glyph to 1 pixel for dynamic countdowns and adjusted kerning for 1 pixel spacing.  Adjusted left-side thickness to allow it to alias.  `4` and `5` have slightly thinner right-side thickness alias faster.

I think removing the kerning looks great and darkening the display was great improvement.  Solves the spacing issues.

I think adjusting the rightside thickness of all glyphs to match the `:` depicted may be an overall improvement.

**Comment by Azrun** [comment]
Profile with 500 scroll status displays mostly due to a spawned loops to update at 2 Hz. 😄 
image
Will optimize and maybe look at scaling based on number of displays in world to avoid griefing.

Static Image
image

Static  Text
image

**Comment by Azrun** [comment]
Improved 500 Displays

Scrolling Image
image

Static Image
image

Static Text
image

**Comment by WALPVRGIS** [comment]
Latest demo vid looks great! 😺

**Pull request merged**
