### PR TITLE
Cows have ears now and better hooves and tail!

### PR DESCRIPTION
**Pull request by GuvGuvington**
ad1
ebetterdefaultad

[Mutantraces] [Sprites]

## About the PR 
Added ear sprites to special layer 3, fixed an
issue with cow snoots booping through masks,
redid the tail sprites, fixed the weird white
soles on their hooves, slightly changed udder shading and moved all cow files
in a new "cow" folder in icons/mob!
Why did I create a new folder instead of simply
editing the existing file?
I wish to add alternative cow styles in the
near future, just how pugs do, but its broken,
so this PR only contains stuff for the default
spotted cow design.

THIS DOES NOT IMPACT YOUR ABILITY TO COLOUR HOOVES AND HORNS.
THE EARS ARE NOT COLOURED BY HAIR COLOURS.

## Why's this needed? 
Cows have such big, beautiful ears!
The current cow sprites having none is like having a lizard without.... scales?
Also, the tail is so smal and puny, its hardly even there and the brushy tip? - Only exists in the describtion!
I don't know why the soles are white, but it looks very weird to me.
Anyways, this PR seeks to fix all of that, so if any of the things taht bother me ever bothered you, then this might be of interest to you!
Screenshot (519)
Screenshot (521)
Screenshot (520)
Screenshot (522)
Screenshot (524)
Screenshot (523)

## Changelog 

```changelog
(u)GuvGuvington
(+)Cows have ears now, a brushier tail aswell as improved hoof and udder sprites!
```

### CODE REVIEW

**Comment by GuvGuvington** [comment]
> put images in pr please

done!

**Comment by TobleroneSwordfish** [comment]
Feedback from our resident cow main Cal: the ears look a little too big and look odd without a wig, maybe try something closer to the ones from the original version of #5703
(Yes I know it got rejected but I really do think cows would look a lot better with ears, and those ones stick out less if you're not wearing a wig)

**Comment by GuvGuvington** [comment]
> Feedback from our resident cow main Cal: the ears look a little too big and look odd without a wig, maybe try something closer to the ones from the original version of #5703 (Yes I know it got rejected but I really do think cows would look a lot better with ears, and those ones stick out less if you're not wearing a wig)

I see how you can find them too big, but I really like them that way.
They stand out well in the 32x32 style and are still clearly visible with wigs

**Comment by TobleroneSwordfish** [comment]
Well you're welcome to wait for other feedback, but as a dev I'm going to say it's unlikely to be merged as-is.

**Comment by GuvGuvington** [comment]
> The white strip on the current hooves is colored by the hair color channels, same as the horns. Players can already make them brown, or pink, or whatever.

Hair colour channel colours the entire foot, not just the soles.
Choosing a brown colour to make the soles brown instead of white, paints the rest of the foot black.
It always looks bad.

**Comment by GuvGuvington** [comment]
> Oh wow I never noticed that. Ok yea I like your hooves more. Though I think being able to tint the whole hoof is still a good option to leave in.
> 
> While i'm here I'll mention I think the ears are too big. I know heads are oversized in this game but the ears don't look proportional even to that.

My pr does not mess with your ability to colour the hooves or horns

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
Seconding smaller ears, for the front/back views only (side view looks great to me); while I think the ears are cute, wigs are not the default for mutantraces and the base mutantrace sprites should not be designed as though it were. Would be open to having the bigger ears as an option in the future but as the PR currently is, would just like them smaller for now thanks. c:

**Comment by GuvGuvington** [comment]
> Seconding smaller ears, for the front/back views only (side view looks great to me); while I think the ears are cute, wigs are not the default for mutantraces and the base mutantrace sprites should not be designed as though it were. Would be open to having the bigger ears as an option in the future but as the PR currently is, would just like them smaller for now thanks. c:

Will do!
Bigger and no ears are doable ina  future pr, along with the different fur designs once I get special_style to work with the cow extra parts.

**Comment by GuvGuvington** [comment]
> Feedback from our resident cow main Cal: the ears look a little too big and look odd without a wig, maybe try something closer to the ones from the original version of #5703 (Yes I know it got rejected but I really do think cows would look a lot better with ears, and those ones stick out less if you're not wearing a wig)

Updated the PR to use ears with a 3x3 size, rather than the 4x4 of the old ears.

**Comment by GuvGuvington** [comment]
> Seconding smaller ears, for the front/back views only (side view looks great to me); while I think the ears are cute, wigs are not the default for mutantraces and the base mutantrace sprites should not be designed as though it were. Would be open to having the bigger ears as an option in the future but as the PR currently is, would just like them smaller for now thanks. c:

Updated to use smaller ears that are 3x3 pixels in size, rather than 4x4.

**Review by flrsh — CHANGES_REQUESTED** [review]
A few things -

I'm pretty sure cow noses poking through some masks was intentional. I know some people like that and some don't, but since it's actually more of a feature than a bug, if you'd like to change that, please make a separate PR.

Similarly, the white line on the bottom of the hooves was so cows can have a little bit of color. Please re-include that. 

If we're going to add ears, I'd like to add the ears from #5703. I think they fit the cow sprite more. 

Finally, could you make ears a toggleable option with the special style code, in this PR? I like playing earless cows and I want us to continue having that option.

**Comment by GuvGuvington** [comment]
> A few things -
> 
> I'm pretty sure cow noses poking through some masks was intentional. I know some people like that and some don't, but since it's actually more of a feature than a bug, if you'd like to change that, please make a separate PR.
> 
> Similarly, the white line on the bottom of the hooves was so cows can have a little bit of color. Please re-include that.
> 
> If we're going to add ears, I'd like to add the ears from #5703. I think they fit the cow sprite more.
> 
> Finally, could you make ears a toggleable option with the special style code, in this PR? I like playing earless cows and I want us to continue having that option.

Im gonna add the noses poking through masks and the white soles back and I'm gonna replace my ear sprites from the ones from #5703.

About the toggelabillity using the special style code: I actually always intended to use special_style, as a matter of fact I actually painstakingly designed two alternative fur designs.
Problem is that the snout, tail and the ears aren't affected by special_style at all and I have no idea how to fix that.
If I figured out how to make them work, I would be more than happy to include a no-ear option as well as a big-ear one, using one of my ear sprites.
Along with the sprites from #5703, of course.

**Comment by flrsh** [comment]
Apologies for the late response and thank you for the changes! Fair point with the special style code being difficult to work with, I think what you have now works for me.

**Pull request closed without merging**
