### PR TITLE
lets you put frames onto occupied turfs

### PR DESCRIPTION
**Pull request by zjdtmkhzt**
## About the PR 
This makes it so when you click a turf with a device frame, you will place it on that turf.

## Why's this needed? 
Sometimes it can be hard to deploy things on turfs that already have dense objects on them. For instance, when someone takes the mainframes data terminal, it can be quite difficult to put down a replacement on the mainframe turf.

I considered adding a check for if the turf is dense. Not sure if necessary or if maybe for some machines deployment on dense turfs makes sense.
## Changelog

```changelog
(u) zjdtmkhzt
(+) You can now put mechanics frames onto floors by clicking the floors with the frames.
```

### CODE REVIEW

**Comment by pali6** [comment]
Won't this make walking through walls relatively easy? Place a genetek / clonescanner / other such machine on a wall and you can now walk through it.

**Comment by zjdtmkhzt** [comment]
That is true, what if I add a check for both turf density and restricted z-level?

**Comment by pali6** [comment]
Listening posts have airlocks too. Sure you could add those as an exception along with windows and grilles but it just feels like there might still be unforeseen issues. I guess partially these could instead be done by a density + ON_BORDER check but also our usage of ON_BORDER is a bit inconsistent, maybe grilles and airlocks should have ON_BORDER too? Idk

**Comment by pali6** [comment]
Now I'm going on a tangent but basically in my mind the idea of ON_BORDER is that it's an obj that covers the tile fully (perhaps conditionally e.g. based one direction like ThinkDOS) and as such doesn't let you interact with stuff on the tile even if you are right next to the tile. In my mind this sorta exemplifies the unclear distinction between something like a console or a locker and a window / grille / door (with walls being a special case as turfs but being sorta ON_BORDER).

**Comment by TTerc** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
i think no.
we can do something for the terminals and 'floor objects' like that maybe but i think allowing this for all frames is bad for reasons above

**Pull request closed without merging**
