### PR TITLE
New radio station tape - Cloning PSA

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 
Adds a new radio station tape for a Cloning Public Service Announcement. By Cenith and Phuzzy (I'm just a PR poster).
Voiceover: Cenith of the Black Pants Legion
Musical backing is "Inspretional Wave" by khalafnasirs 2020 - CC-NO 3.0

Also adds the Pope Crunch ad tape to Manta and Oshan since it was missing.

## Changelog

```
(u)Cenith & Phuzzy
(*)New radio station tape - Cloning PSA
```

### CODE REVIEW

**Comment by PhuzzySA** [comment]
Again, all thanks to Cenith of the Black Pants Legion for her amazing kiwi accent! Expect more of these soon!

**Review by ZeWaka — APPROVED** [review]

**Review by ZeWaka — CHANGES_REQUESTED** [review]
Needs soundcache

**Comment by pali6** [comment]
I though radio station stuff is excluded from the sound cache.

**Review by ZeWaka — APPROVED** [review]
> I though radio station stuff is excluded from the sound cache.

u right

**Pull request merged**
