### PR TITLE
Use IMMUNE_TRENCH_WARP for atoms that shouldn't fall to z5 via seafloor hole

### PR DESCRIPTION
**Pull request by pgmzeta**
## About the PR 

adds two new exceptions to the list of things that get warped to the trench on a surface hole: forcefields and lasers

maybe a "floating" object property makes sense at this point idk?

## Why's this needed? 

* oshan 'meteors' can sink forcefield segments :|||||
* it's a little silly that energy manifestations have physical gravity 

## TODO
- [x] Double-check laser interactions
- [x] make it a property

### CODE REVIEW

**Comment by imawxome** [comment]
Im pretty sure neutrons can fall into trench holes as well, i remember seeing "the neutron falls into the deep hole!"

**Comment by Glamurio** [comment]
> maybe a "floating" object property makes sense at this point idk?

An object property would make a lot of sense, given the list of exceptions, however I don't think "floating" is a consistent name. Perhaps something more along the lines of "can_fall"? That covers most of these and sounds less odd than saying reinforced cables float.

**Review by frawhst — APPROVED** [review]
Yeah we really need a better system for generally untouchable/intangible things. This is much cleaner than the current gross check.

**Review by amylizzle — APPROVED** [review]
Oh that's nice, maybe chuck it on `/datum/projectile` as well?

**Comment by pgmzeta** [comment]
> Oh that's nice, maybe chuck it on `/datum/projectile` as well?

didn't find a read the flag off the datum when set directly. added a blanket exception instead, which is probably fine? Not sure if any slow-moving ones would want to sink

**Comment by pgmzeta** [comment]
> Oh that's nice, maybe chuck it on `/datum/projectile` as well?
had to do it on /obj/projectile for the effect

**Pull request merged**
