### PR TITLE
Slightly less gradual explosions

### PR DESCRIPTION
**Pull request by pali6**
## About the PR
Currently running away from explosions is way too easy. This PR tries to remedy that by:
- processing all mobs first, then all objects, then all turfs
- removing as many sleeps and lagchecks from ex_act as possible
- doing minor optimizations to the explosion stuff
As a consequence very large explosions will now cause a bigger lagspike but those don't happen that often generally so it should be fine.

## Why's this needed? 
Being able to run from an explosions that is centered on you is very unintuitive and it makes explosions feel way less deadly.

## Changelog

```
(u)pali
(+)Internal explosion changes that will hopefully make it harder to run away from them
```

### CODE REVIEW

**Comment by pali6** [comment]
I recommend merging #957 first once it's ready and then I'll fix the merge conflicts here.

**Comment by pali6** [comment]
Also if anyone can figure out where obj ex_acts lagcheck / sleep let me know, I was unable to track it down properly. I'm reasonably certain it's somewhere in /obj/machinery but I ruled out a bunch of the obvious candidates and also `robogibs()`.

**Comment by Ley-bunned** [comment]
This was a bit of a fun quirk, sad to see it go. But it probably needs to. Might even do some good with explosions being weird on humans.

**Comment by pali6** [comment]
@Tarmunora Please check if I haven't accidentally screwed up your changes.

**Comment by Tarmunora** [comment]
Looks good 👍

**Comment by Gannets** [comment]
As fun as running away from explosions is, this change makes sense. You shouldn't really be able to cheese your way out of being blown up.

**Pull request merged**
