### PR TITLE
Adds two new Sechud flags: Detain and Suspect.

### PR DESCRIPTION
**Pull request by Keiiro**
[ADD TO WIKI] [STATION SYSTEMS] [QOL]
## About the PR 
Adds two new criminal statuses to the security records: *Detain* and *Suspect*. (Middle and Right respectively)
image_2024-05-24_182814284
Setting someone to Detain will send an alert to security's PDA group, the Detain flag will aso take priority over the Contraband flag. Both new flags do not have any unique behavior otherwise. Those marked as *Detain* will *not* trigger securitrons or security scanners. 

Other flags are unchanged for atomization purposes.

## Why's this needed? 
The paroled criminal status is often used by security as a way to indicate a crew member either: 

- Has committed a crime and has been released, **(Intended purpose)** 
- Has committed a minor crime and needs to be handled/ticketed/fined, 
- Needs to be brought in to security for interrogation,
- Is a suspect in an ongoing investigation,
- Is a member of a gang.

This PR adds two dedicated flags that hopefully will be able to communicate these scenarios more clearly.

## Changelog 

```changelog
(u)Keiiro
(*)Two new criminal statuses have been added to the security records: Detain and Suspect.
```

### CODE REVIEW

**Comment by Glamurio** [comment]
Very good change.

**Review by frawhst — APPROVED** [review]
Slightly iffy on the detain sprite (not sure a triangle conveys 'detain'), but the code looks fine.

**Comment by Keiiro** [comment]
> Slightly iffy on the detain sprite (not sure a triangle conveys 'detain'),

Hmh. I thought it too, but I couldn't come up with another idea that would fit. I'm open to suggestions for a different symbol for the detain status (That can fit within the sprite)

**Comment by FlameArrow57** [comment]
> > Slightly iffy on the detain sprite (not sure a triangle conveys 'detain'),
> 
> Hmh. I thought it too, but I couldn't come up with another idea that would fit. I'm open to suggestions for a different symbol for the detain status (That can fit within the sprite)

What about handcuff symbol?

**Comment by Keiiro** [comment]
> What about handcuff symbol?

Best I can do given the sprite size.
image_2024-05-29_221546311

**Comment by Valtsu0** [comment]
Personally I like the triangle

**Comment by Glamurio** [comment]
I like both the handcuffs and triangle, no preference.

**Comment by ZeWaka** [comment]
i like the cuffs

**Review by TTerc — APPROVED** [review]
yeah, I prefer the cuffs as well, looks good overall

**Pull request merged**
