### PR TITLE
Adds Status Displays To Cog2

### PR DESCRIPTION
**Pull request by Wisemonster**
## About the PR 
This pr adds status displays across Cog2.

## Why's this needed? 
Let's more people be aware/use the feature.

## Changelog

```changelog
(u)Wisemonster
(+)Added status boards to Cog2

### CODE REVIEW

**Comment by Eagletanker** [comment]
You probably dont need to keep putting the added status displays into the changelog and could signifcatly shrink it by just saying added status boards to all maps

**Comment by Wisemonster** [comment]
> You probably dont need to keep putting the added status displays into the changelog and could signifcatly shrink it by just saying added status boards to all maps

Aight, although are you requesting that I add status displays to the remaining maps, and have them all in a single pr?

**Comment by Eagletanker** [comment]
up to the people who made the remaining maps

**Comment by virvatuli-gh** [comment]
> > You probably dont need to keep putting the added status displays into the changelog and could signifcatly shrink it by just saying added status boards to all maps
> 
> Aight, although are you requesting that I add status displays to the remaining maps, and have them all in a single pr?

They are requesting you do things that you do not need to do. Having a changelog is fine, but please use the minor tag `(+)` instead of the major tag `(*)` to for something of this nature, if it is even necessary. Keeping them in separate PRs is good, the more focused a PR is (and thus small) makes it easier to review and more likely to be accepted. I've already edited your changelog for this PR, but use the [contributor guidelines](https://hackmd.io/@goonstation/docs/%2F@goonstation%2Fcontribute#Making-PRs-read-before-making-a-PR) in the future to reference this stuff!

**Review by virvatuli-gh — APPROVED** [review]

**Pull request merged**
