### PR TITLE
Removes screen orientation flipping from space madness

### PR DESCRIPTION
**Pull request by TTerc**
[removal][wiki]

## About the PR 

As the title says

## Why's this needed? 

People were reporting it's making them literally sick, we don't really need things that make players uncomfortable ingame.

### CODE REVIEW

**Comment by Zonespace27** [comment]
aside from being a disease, what does space madness do that LSD/psilocybin don't?

**Comment by TTerc** [comment]
Makes you shout various different phrases exclusive to that disease (with the clown having unique ones).
If someone wants to add more content to space madness to compensate for the removal, feel free to, but I still think the screen flipping should be gone, considering I've received ahelps from the people complaining about how it makes them genuinely sick.

**Comment by alexeric123** [comment]
I forget, but does the screen flip multiple times?
Or is it just one flip that goes away when its cured?

**Comment by TTerc** [comment]
6% chance per tick for the orientation to change, on stage 5 of the disease

**Comment by alexeric123** [comment]
Maybe just change it to one reverse at stage 5, instead of having it constantly change then?
It would make it less nauseating for sure.

**Comment by TTerc** [comment]
I'm still personally not a fan of keeping this specific effect in any form

**Comment by MatheusIsNotAvailable** [comment]
I always this was a bug or an admin messing with me, I even ahelped it was making me sick once and asked them to stop if it was the case. I always just restart when it happens, thank you for removing it.

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
