### PR TITLE
Minor gun balance and refactoring

### LINKED ISSUE #101: Taser / gun balance feedback thread
Please respond to this issue with concerns regarding the *balance* of tasers, wavegun, lawgiver, etc. as a direct consequence to #55 for the purposes of a followup rebalance if necessary.

Also just general stun/gun balance I suppose

### PR DESCRIPTION
**Pull request by Tarmunora**
## About the PR 
~~Makes yet another sweeping change to tasers, and other guns:~~
~~Tasers and other stunner projectiles will now have a capped stun time based on projectile power, with slightly increased disorient to compensate~~
Tweaked the stamina damage calculations for kinetic weapons - notably reduces the stamina damage of riot shotguns
Buffed derringers a fair bit
Gun bleeding is now affected by armor, and should work for more kinds of bullets (refactored into `bullet_act()` in damage.dm, instead of being an on_hit on the `projectile/bullet` path)
Refactored taser/etc stuns out of `on_hit()` into `bullet_act()`
~~Detain mode on lawgiver no longer stuns on the AoE - strictly requires a followup or direct hits~~
Buckshot ammo has it's knockback again
Wavegun EMP mode is significantly less effective against nuclear bombs
Fixed bug where you always were considered to be a little drunk for the purposes of shooting guns

## Why's this needed? 
~~Tasers are currently a little too good at doing everything themselves, this encourages security to follow up with a baton, instead of relying on magdumping tasers~~
Other stuff was just refactors that needed to happen eventually, and misc balance tweaks that probably won't upset anything overmuch
~~Detain mode was being perhaps a little too strong. Not too sure about this one.~~

## Changelog

```changelog
(u)Tarmunora:
(+)Changed misc gun balance
```

### CODE REVIEW

**Comment by Flaborized** [comment]
I like this PR, some of the changes are ideas that I supported/had in the issue thread linked, I personally think this would make playing sec more fun and dynamic. Would like to see other's opinions on it though as well cuz it's kinda a big change!

**Comment by Ley-bunned** [comment]
This looks good. I told Tarm over discord that the previous change wasn't a huge difference for me. This is going in the right direction for tasers. The other changes appear fine. Riot shotgun was a fairly oppressive weapon when used well.

Derringer change is also good, though it needs to be seen in play.  It was 200 stam and near-lethal damage, right? 1 TC for a stun is probably a bit of a bargain! But we'll see.

**Comment by Kyle2143** [comment]
I can see the use for this. There was a change a while ago that made tasers not stun long enough to cuff someone if you pointblanked them and then started the cuffing, which I'm fairly sure has been changed since. But it got me in the habit of always batoning people once they're down, so I don't think I'll personally see any effect from this change to tasers.

I'm also glad that spread was a bug, I noticed it the other day and assumed it was intentional which I didn't like, glad it's gone.

As for the damage and balance changes in it, it's hard to tell how it's going to feel based on looking at numbers, they are definitely worth trying out.

**Comment by UrsulaMejor** [comment]
feels like these should be split into a couple different prs. the bug fix doesn't have much to do with the stun cap for nonlethal weaponry, and should be added asap without having to consider it chained to the stun cap change.

Not opposed to the stun cap, as most things have one, but it should be reasonably high; high enough for a non sec officer to apply cuffs using only the taser + taser point blanks. Using the baton should be good strategy, not required gameplay.

**Comment by Flaborized** [comment]
I feel that as long as the taser _is_ able to cuff someone as a non-sec-officer, it'll be the dominant way to do so as a sec officer as well. Especially considering it takes sec officers a much shorter amount of time to handcuff somebody, there's just not a really great reason to do the taser -> baton combo when you can do the taser -> taser -> taser combo. The taser feels like it's better at doing what the baton does, either being used as follow up after someone has been stunned by a taser or being used as a close-range stun weapon. Taser is better at the former because you don't have to swap what you're holding in your hand whatsoever, so it's much easier to lay three point-blanks into someone than it is to pull out your baton and worry about that. For the former, in my experience tasers are _most_ useful at melee range, because it's very easy to step out of range of a baton and basically kite people by running in for short periods of time and running out: The taser doesn't have this weakness so it's a better option in melee fights.

Like I've said a bunch, cuffing someone is essentially a "fight win condition" that leads very quickly into them being dead if the person who's cuffed them wants them dead. I think that it should be a Very Earned State, and that it's more dynamic if it requires more tools from sec to achieve. As for non-sec-officers, stealing a taser is quite easy in my experience, and there's already tons of utility an antag could get out of stunning someone for a short period of time. This just adds a little more challenge to Murdering People I feel, and would help make combat a little more slow, which I think is good!

I can agree with this probably deserving a separate PR though, the bugfixes are a much less contentious change

**Comment by UrsulaMejor** [comment]
You should be using the baton to conserve ammo, if for no other reason. Your shots are limited, but the baton is dramatically less do. The baton is also just generally better than the taser at melee range now that the point blank taser stun was reduced.

I don't really like the idea of enforcing a play style, especially one that is more challenging and relies a lot more on precise clicking with a melee weapon.

**Comment by Tarmunora** [comment]
Taser balance changes (mostly, may have missed something) reverted for this PR, may show up again later

**Comment by flrsh** [comment]
What's the status + feedback on this PR?

**Comment by Tarmunora** [comment]
> 
> 
> What's the status + feedback on this PR?

current status: gun/projectile code/balance is no longer worth the time and headaches to fix.

**Pull request merged**
