### PR TITLE
Fixed an issue that let players equip item limbs

### PR DESCRIPTION
**Pull request by PrimeNumb**
[BUG_MINOR]

## About the PR 

Adds an edge case to one instance of the equip functionality.

## Why's this needed? 
Fixes things like being able to equip items that can't be dropped, which would break things in general.

## Changelog

```
(u)RichardGere:
(+)Fixed an issue where players were able to equip items attached to limbs.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
I feel like this is probably intentional in some cases.

**Comment by PrimeNumb** [comment]
> I feel like this is probably intentional in some cases.

For example: You can put an item limb into your belt, which will break the equipment slot.

**Comment by ZeWaka** [comment]
Doesn't this break electropacks, cluwne gear, NASSA suits, and literally almost everything else with `cant_self_remove = 1`?

**Comment by PrimeNumb** [comment]
> Doesn't this break electropacks, cluwne gear, NASSA suits, and literally almost everything else with `cant_self_remove = 1`?

Nope! I tested owlbombs, cluwning and electropacks and it works fine. 
I forgot to include the case where the user actually clicks the slot (instead of using the hotkey) so I pushed that as well.

**Comment by PrimeNumb** [comment]
> There are some items that currently have both `cant_self_remove` and `cant_drop` set to 1, which means they'd break with this change. For instance, `/obj/item/clothing/mask/horse_mask/cursed`. Not sure what the best way to approach this would be; we could remove the `cant_drop = 1` from all of them, but then that'd change the intended functionality.

Woops! You're right, this does break it.
So the problem is mainly that you can equip item limbs (and just break equipment slots entirely with them), and I see now that the intended behavior of `cant_drop `isn't necessarily that they're unable to be equipped.

There's no property like `is_limb` that I can check on the item (and I am not so sure it's a good idea to add one just yet), so I've resorted to checking whether the item's `loc` is a subtype of `/obj/item/parts`, which is only the case if it's attached to a limb (correct me if I am wrong).

**Pull request merged**
