### PR TITLE
Adds a Cleaner Manudrive to Atlas

### PR DESCRIPTION
**Pull request by Wisemonster**
[FEATURE] [GAME OBJECTS]

## About the PR 
Adds a cleaner grenade manudrive to the atlus jani closet.

## Why's this needed? 
Originally didn't add it due to atlas's size, I now think it's fine if the jani's had 1 manudrive.

## Changelog 

```changelog
(u)Wisemonster
(+)Added a cleaner grenade manudrive to the atlas jani closet.
```

### CODE REVIEW

**Comment by frawhst** [comment]
why does atlas have a special janitor's closet anyways

**Review by Gannets — APPROVED** [review]
sure

**Comment by Azrun** [comment]
> why does atlas have a special janitor's closet anyways

Agreed, why not `/obj/storage/secure/closet/civilian/janitor`?

**Comment by Wisemonster** [comment]
Looks like a different pr doing the same thing as this one has merged, so closing

**Pull request closed without merging**
