### PR TITLE
Monkeys and humans can be blindfolded by targeting their head.

### PR DESCRIPTION
**Pull request by MeijiIshinIsLame**
## About the PR 

Made it so that when a user has a blindfold in hand and target area set to head, attacking a human or monkey blindfolds them. You cannot do this by attacking yourself, but you can still equip by putting it in your glasses slot. The timer has a 1.3 second extension to make up for the previous method of dragging the target and selecting their glasses slot.

## Why's this needed? 

As a geneticist I found blindfolding monkeys annoying. Also, by extension of that, it doesn't really make sense to have to go through a menu to use the blindfold when it only has one purpose.

However, since it's been almost 7 years since I was active I may be lost as to what's fun, or if there's any compelling reasons to keep it the way it is, so I'm open for criticism.

## Changelog

```
(u)Fautz0:
(+)You can now blindfold monkeys and humans by attacking their head with a blindfold.
```

### CODE REVIEW

**Comment by ZeWaka** [comment]
Looks to be instant. It should be moved to an action bar or at least use the old timed action framework

**Comment by Gerhazo** [comment]
I think it's a bit arbitrary and if there was to be a thing with hitting people with a blindfold while targeting the eyes it should be a general feature for anything, not just monkeys.
Also extends that it probably shouldn't be instant, but in that case this whole thing reverts to the original behavior, just that instead of having to open their menu the game can assume that you want to put a blindfold on (as there aren't many other things you could be doing with a blindfold).

**Comment by MarkNais** [comment]
Definitely have it work on player-monkeys for consistency and counter-powergamers.
If the timer is added back, maybe prevent the monkey from moving during the timer? Blindfolding does seem unnecessarily hard.

**Comment by ZeWaka** [comment]
> If the timer is added back, maybe prevent the monkey from moving during the timer? Blindfolding does seem unnecessarily hard.

if you don't want a monkey to move, stun it

**Comment by Flaborized** [comment]
Blindfolding is frustrating and difficult on purpose (in the sense that it's slow and monkeys can walk out of it). I'd hate for it to become super trivial and instant. I also don't particularly see why it needs to be tied to help intent? It's not like you would want to do other things if you're clicking with a blindfold? And I agree with Gerhazo that it's weird that the behavior only applied to monkeys: it should ideally apply to everyone for mechanical consistency

**Comment by MeijiIshinIsLame** [comment]
Made a new commit. Now it's an attack property of the blindfold itself and works on all humans and monkeys. Should I make a new PR since this is sort of a different thing now?

I read the comments and you guys are right. It makes more sense for it to have a timer and be consistent. Also, the action is now done regardless of intent.

Right now it doesn't work on yourself because I wanted to stop accidental blindfolding.

I tried keeping the action bar at the default time, but it was a little too easy, so the timer has a 1.3 second extension. I timed myself doing the original action and it took about 1.3-1.5 seconds. I agree that it should be a little difficult, but I don't think this is something that should require navigating through a menu, considering there is only one thing you do with a blindfold.

**Comment by ZeWaka** [comment]
> 
> 
> Should I make a new PR since this is sort of a different thing now?

No need, just update the title and description. PRs are for evolving changes just like this, there's a reason you can keep adding on to them!

**Pull request merged**
