### PR TITLE
Adds ranches and electroplaters to Donut 3, Cogmap 2 and Horizon

### PR DESCRIPTION
**Pull request by TTerc**
## About the PR 
Title
Also adds electroplaters and rancher job spawner to cog1
screenshots for the ranches layout here: https://imgur.com/a/UK2dg4K

## Why's this needed? 
The more maps have them, the better, right?

## Changelog

```
(u)TTerc:
(+)Donut 3, Cogmap 2 and Horizon have ranches and electroplaters now. Cog1 also has electroplaters.
```

### CODE REVIEW

**Comment by UrsulaMejor** [comment]
@Tenryumi donut 3 changes

**Comment by Tenryumi** [comment]
Looks good to me! Go for it 👌

**Review by flrsh — CHANGES_REQUESTED** [review]
Not a fan of how Manta's bar has been shifted. I'd prefer adding the ranch myself.

**Review by flrsh — COMMENTED** [review]
Thanks!

**Review by flrsh — APPROVED** [review]
It won't stop showing "changes requested" unless I approve this. I'm not associated with any of these maps, so someone else should also take a look.

**Comment by UrsulaMejor** [comment]
Rough, but good enough. Might want to take another pass on Horizon's rancher area; it might look better stylized as an "Addition" rather than looking like a weird bulbous growth on the ship.

**Pull request merged**
