### PR TITLE
Adds Terrance

### PR DESCRIPTION
**Pull request by Fungal-Infection**
## About the PR 

It Adds **Terrance**

## Why's this needed? 

**Terrance**
image

### CODE REVIEW

**Comment by TheColorCyan** [comment]
watermelon🙏

**Comment by Fungal-Infection** [comment]
this singular watermelon has required 3 quickfixes

**Comment by DisturbHerb** [comment]
why is this good for the game 🤔

**Comment by Fungal-Infection** [comment]
you see, disturbherb, it adds **Terrance**

**Comment by pali6** [comment]
What

**Comment by Fungal-Infection** [comment]
**Terrance**

**Comment by Fungal-Infection** [comment]
merge

**Comment by TobleroneSwordfish** [comment]
coollogo_com-305832351

**Comment by ZeWaka** [comment]
Not seeing a good reason to add this.

**Comment by Laboredih123** [comment]
the fall of terrance

**Comment by Fungal-Infection** [comment]
Terrances Failure

**Comment by Jak27** [comment]
terrance has fallen
millions will riot

**Pull request closed without merging**
