### PR TITLE
Makes Meteor shower & other events required round time lowered

### PR DESCRIPTION
**Pull request by RSG250**
[Balance] [Station Systems]
## About the PR 
Meteor shower & other events required round time lowered from current times of
Meteor_shower = 55 to 26.6 minutes
vamp_teg = 40 to 26.6 minutes
blowout = 40 to 26.6 minutes
Black_hole = 40 to 26.6 minutes
26.6 minutes is the current time  sleeper agents are set

i expect this will significantly change how rounds play out, as players will need to learn deal with the aftermath of the events more and in the case of the blackhole event actually care enough to prevent it.

## Why's this needed? 
lowering the time would make it so people would not only be more familiar  with the events, they would figure out how to deal with them/ and their aftermath more effectively as people currently just tend to call shuttle when either a Blowout or a Blackhole who was not feed to dissipation happens 

id rather have people deal with the events rather than just give up and call shuttle tbh.

yell at me on discord if time need  adjustment

## Changelog 

```changelog
(u)RSG250
(*)Certain Major Random Events are now able to appear earlier in a round in Classic
```

### CODE REVIEW

**Comment by Wisemonster** [comment]
Might be a good idea to make the increased frequencies restricted to classic, considering rp rounds tend to last around 80 minutes.

**Comment by RSG250** [comment]
i mean i can definitely try

**Comment by RSG250** [comment]
theres probably a better way of doing it than i did, but im not the big smart so this will have to do till some one yells at me

**Review by frawhst — APPROVED** [review]
Will probably lead to a lot more annoyance with these events but that's imo fine since that's more pressure to make the bad ones Not Bad

**Review by ZeWaka — APPROVED** [review]

**Pull request merged**
