### PR TITLE
Added multiple basic and targeted emotes

### PR DESCRIPTION
**Pull request by DisturbHerb**
[QOL]

## About the PR 
Several new basic and targeted emotes have been added. These include:
* Basic
     * grunt
     * gulp
     * hold_up
* Targeted
     * boop
     * hand_shoulder
     * roll_eyes
     * sneer
     * squint

## Why's this needed? 
I like emotes. They're good for rolepalying. I like targeted ones too.

## Changelog

```changelog
(u)DisturbHerb
(+)Added several basic and targeted emotes. Check listbasic and listtarget to find 'em all!
```

### CODE REVIEW

**Comment by comradef191** [comment]
...The ability to boop?

Devs, Speedmerge this.

**Comment by DisturbHerb** [comment]
> ...The ability to boop?
> 
> Devs, Speedmerge this.

Ahah, no, do not. Please.

**Comment by comradef191** [comment]
> fixing the ability to boop at a range of 8 tiles

you monster, you killed Air Boops q-q

**Comment by DisturbHerb** [comment]
> > fixing the ability to boop at a range of 8 tiles
> 
> you monster, you killed Air Boops q-q

i'm already a monster, rupert has killed half his family in cold blood

**Comment by geneva-breaker** [comment]
Personally I only see utility in the hold_up emote. 
The rest look like rehashes of existing emotes but with a weird tone that doesn't really sit great with me, as a default emote. 
I think *me will stand in just fine for the rest. 
I'd merge hold_up but yeah, kinda cold on the bloat for the rest of these.

**Comment by Awfullyfishy** [comment]
All the targeted ones are lovely. I don't see any weird tones, and more targeted emotes are always welcome in my book. Having to type *me emotes is a slog and lets be real, a lot more people will use default emotes anyway. Let me roll my eyes and hold up sporks.

**Comment by Carbadox** [comment]
I think being afraid of bloat on a couple emotes on an entirely out of the way feature in a roleplaying sandbox where giving players more options is a bit non sensical

**Comment by DisturbHerb** [comment]
i'll eventually return to this when i'm no longer lumbered with working on chess 😔

**Pull request closed without merging**
