### PR TITLE
Get rid of ai_monitored areas

### PR DESCRIPTION
**Pull request by flappybatpal**
## About the PR 
Removes /ai_monitored/ areas.

## Why's this needed? 
ai_monitored is unused functionality.

### CODE REVIEW

**Comment by Chatauscours** [comment]
Good PR, but I think you will also need to change most of the turret control panels, as they are sometimes located outside of the area they are protecting, and have said area set manually in the map maker.

**Comment by ZeWaka** [comment]
Don't the lasers use this?

**Comment by flappybatpal** [comment]
> Don't the lasers use this?

I can't find sign in the code of anything but /obj/machinery/camera/motion using this which has no implementation outside of unused maps.

From a skim ir_beam just works off contact.

**Comment by Sord213** [comment]
> I can't find sign in the code of anything but /obj/machinery/camera/motion using this which has no implementation outside of unused maps.

Donut 2 uses these and they still work. Surprisingly useful as an AI. It will send a message in chat to the AI player when someone is detected in the monitored area. I wouldn't personally be opposed to adding them to more maps.

**Pull request closed without merging**
