### PR TITLE
Destiny Remapping

### PR DESCRIPTION
**Pull request by nefarious6th**
[qol] [rework][mapping]
## About the PR 
This PR does A Ton of Many Things to rework Destiny; partially in preperation for perspectivization and partially to resolve some of the outdated features and common complaints about it.

destinyremap
destinyremap_noareas

## Why's this needed? 
Makes this map nicer to play on. Paves the way for a full 3/4 perspectivization.

## The Long Part (Highlights)

**Holistic Stuff:**
- APCs were moved into the rooms they operate for, versus all being in maintenance
- APCs, fire alarms, and other wall objects were moved off the southern walls
- Swaps caution tiles over to decals
- Redoes the powernet to use iconstate wires
- Accounts for PRs 3694, 3259, 3351, 3350, 3682, 3781, 3884, 3377; saves a spot for the ice dispenser in the bar

**Engineering:**
_Mining_
- Refinery is now public access
- Mining has moved to the **south** of the East Primary Hall to have direct access to the airlock
- The magnet now has a catwalk surface so miners and others have a chance to stop themselves before floating away into space

_Cargo_
- MULE Bot has joined Destiny Cargo! Drop offs are in the Northwest Net Cafe, North Primary Hall outside the Aviary, Medbay Lobby, Tool Storage, Hydroponics Bay, Kitchen, Arcade, and Research Lobby
- The Cargo bay is larger and more open.

_Engine_
- Two of the engine SMESs and the power computers are now kept in a room south of the control room. This is easier to access both SMESs and secures critical equipment behind Engineering-access-only doors
- The airlocks to the East and West Solar fields and related SMESs are now Engineering-access only
- A temporary construction room was made south of Cargo...I’m sure if you look closely at it, you can figure out what big projects NT might have planned for the space. For now, you’re welcome to renovate!

**Security:**
- **Significant** rearrangements; more open lobby space, removal of thindows that were used to create critical boundaries (Equipment Room and Brig), brig chutes added
- Armory was made internal in the Department versus being off the main hall
- Beepsky was re-pathed to be more in the all-access areas; he had a nasty habit of leaving Security doors to sensitive locations open
- Turrets were placed outside  Beepsky’s House where the Armory backs up to; The turret control is in the HoS’s office
- Armory got slightly more gear, notably an emergency alcohol fountain and NARCS
- For when someone inevitably blows up Security to break out Stirstir, an air repressurization setup has been added to the nearby west maint. The admin grief-alert toggle for this valve is currently set to **off**. This can be changed.
- Added two additional Securitrons in the north of the station and in the Bar
- Added Security Assistant spawns

**Medical:**
- **Significant** rearrangements; more open lobby space
- Cloning is now relatively public but still guarded. You’ll have to get through the Geneticists to reach Cloning from the public hall...speaking of which...
- Pathology and Genetics are now split into respective and separate departments/rooms; Pathology occupies the space of the old Medical Research
- A Psychiatrist’s Office was added; additional psychiatrist job override can be done for this, it is not currently set
- For when someone inevitably blows up Medbay to destroy the cloner, an air repressurization setup has been added to the nearby northwest maint. The admin grief-alert toggle for these valves is currently set to **off**. This can be changed. It has two injectors, one in the back section of medbay and one in the front section

**Civilian:**
- There’s now a Ranch! It has two pens, windows and a front desk.
- Janitors now have a bigger Office room above Research. They now have an additional supply closet on the other side of the station between the Detective’s Office and Crew Bathroom.
- Chapel now has a mass driver and player piano

**Command:**
- AI upload is now slightly larger and the AI core does not back up against the reinforced wall into the primary hallway; full crystal glass spawners and AI shutters have been added
- The Computer Core now has a small hall that leads to it, versus being off the RD’s Office and maint.
- Each of the Heads’ unique items (War Medal, Diploma, Degree, First Dollar) have been added. Objectives involving these should now be valid if they aren’t currently, or can be added for this map!

**Research:**
- Per RSG's thinking, the ArtLab now has an emergency flusher
- For when someone inevitably blows up Chemistry, an air repressurization setup has been added to the nearby south maint. The admin grief-alert toggle for this valve is currently set to **off**. This can be changed

**Crew Areas:** 
- **Arrivals** has **_moved_**. It is now to the right of the Fitness Room (Mary moved too!), and has exits into the boxing ring and the Public Refinery as well as atmospheric forcefields. Hopefully this reduces Arrivals casualties from incidents in the main hall, Bar, and Kitchen. Central Primary Hall might be added as a nuke target in the future; it’s large and open. Hydroponics could also be added now that Arrivals is somewhere safer
- Boogiebot was added. Boogie on!

**Miscellaneous:**
- Tech Storage has moved; it’s close to where it originally was. It is now in maint south of Medbay
- An Observatory was added to the old Tech Storage location
- There's now a Central Maintenance across from the Research hall and next to Arrivals. The persistent bookshelf is now in here.
- The Central Primary Hallway was straightened out to be more navigable
- Maintenance has expanded; most areas are now at least 2-tiles wide. There’s some new hang out spots around in there too!
- A northwest warp beacon and southeast warp beacon were added for pod-goers
- Maintenance is now more broken-up into differently zoned areas; hopefully this improves ability to track locations since “West Maintenance” is no longer somewhere along the whole side of the ship
- For when someone inevitably blows up Escape in a nuclear plot, an air repressurization setup has been added to the crew quarters east maintenance. The admin grief-alert toggle for this valve is currently set to **off**. This can be changed.
- Drone factory is now by disposals
- Mime Hovel was added by the Observatory on the far left of the ship

Future projects?
- Custom MULE pathing?
- Asset perspectivization (doors, fakeobjects, PTL?)
- Perspectivization of tilesets on map
- Adding new nuke locations/adding objectives based around the Heads' items

## Changelog
```changelog
(u)Nefarious6th
(*)Destiny has received some significant remapping; highlights include layout changes to Security and Medical and the addition of a Ranch. See PR for extended details.
```

### CODE REVIEW

**Comment by RSG250** [comment]
1 question, where do the science guys go to eject artifacts that go boom?

1 gripe, as a miner i hate getting locked out by the shields,  *scream

**Comment by nefarious6th** [comment]
> 1 question, where do the science guys go to eject artifacts that go boom?
> 
> 1 gripe, as a miner i hate getting locked out by the shields, *scream

Good catch! Destiny never had a flusher but it was not something I considered either. What I can do is make a flusher system like the one on Manta that goes through some piping and dumps the artifact out the back of the station where the Chemistry Air Hookup is. I would've never thought of including one. Thanks for pointing it out!

I can also extend the shield area to include the magnet! Clarion does this but Destiny didn't, so it slipped my mind! 

Good finds, thank you!

**Comment by BatElite** [comment]
Glad to see an attempt to fix the super mess that is Destiny!

-Why change the mule tiles for decals? AFAIK the ones on donut3 have some odd layering going on.

-Door between the hallway and showers feels awkward.

-Could you find a way to make boxing area/pool bit a bit better interconnected? Maybe a door to the courtroom? Because at the moment the only way out is to go back the way you came and that sucks. :/

-While you're doing One Metric Fuckton of destiny changes, the window to the engine cold loop purge has a wall under if for some reason, so you can't actually look out there.

**Comment by nefarious6th** [comment]
> -Why change the mule tiles for decals? AFAIK the ones on donut3 have some odd layering going on.
I realized how ugly these looked very quickly and reverted them back to the floor tiles, I just forgot to edit that in the description.

> -Door between the hallway and showers feels awkward.
Removed.

> -Could you find a way to make boxing area/pool bit a bit better interconnected? Maybe a door to the courtroom? Because at the moment the only way out is to go back the way you came and that sucks. :/
Done!

> -While you're doing One Metric Fuckton of destiny changes, the window to the engine cold loop purge has a wall under if for some reason, so you can't actually look out there.
Done!

**Comment by nefarious6th** [comment]
🎉 First draft done and ready for review! Only thing I wish was that I had a way to set custom MULE bot pathing/door access since some of the Northern drop points still kinda have weird pathing to them despite a bunch of tests with tons of beacons in various different spots. Something for later.

**Review by ZeWaka — COMMENTED** [review]
Big fan of this overall.

Notes:
temporary construction room: i don't think those flashing road barrier things are deconstructible
No need for the _old.dmm file.
For the future: I would love to see more internal maint rather than just on the outside in this map.

**Comment by nefarious6th** [comment]
> Big fan of this overall.
> 
> Notes:
> temporary construction room: i don't think those flashing road barrier things are deconstructible
> No need for the _old.dmm file.
> For the future: I would love to see more internal maint rather than just on the outside in this map.
> In the future, please do try and split these up a bit more. Just one room/department for example.

Sure! This was a monster because I actually started by trying to remove the thindows which usually ends up with me cutting the map into pieces so it was hard to approach as a single-room-at-a-time thing. Sorry for the very long PR!

I will remove the barrier things and can push that soon (and update to remove the merge conflict).

I was also thinking about the maint a little while ago, but I'd like to maybe try to reorganize some stuff near the boxing ring to put either a short tunnel parallel to the east/west halls in or something like the little maint "closets" near the top half. Maybe something that connects to the utility room and then re-zoning the utility room into something under maint too? Would that be okay to do on this PR versus this getting pushed, then having another map reconfiguraton happen shortly after?

**Comment by ZeWaka** [comment]
> Maybe something that connects to the utility room below the pool and then re-zoning the utility room into something under maint too? Would that be okay to do on this PR versus this getting pushed, then having another map reconfiguraton happen shortly after?

Either works.

**Review by ZeWaka — APPROVED** [review]
At least one other dev should review this. LGTM.

**Comment by nefarious6th** [comment]
Definitely done on this for now aside from fixing any merge conflicts that pop up later. 👍 I think I hit everything I needed/wanted to with improving each department as much as possible after the cargo/mining stuff; and just did one more poke in Research since I identified interconnectedness with maint was pretty lacking there (and tried to follow BatElite's earlier suggestion to always offer a different way to exit than from where one came into an area). 

Did the info overlay checks for power + powernet, pipenets, atmos; manually checked buttons, levels, belts, and ghostdrone factory, and everything looks fine. I think any other additions/changes (like maybe moving Customs further south) can easily be done in another PR based on people's feedback if that's still a problem spot or not.

**Review by ZeWaka — APPROVED** [review]

**Review by flrsh — CHANGES_REQUESTED** [review]
I looked over this very briefly. I think you did really good work, and I love the changes and little touches that make the ship more comfy and lived in. 

Here are a couple small changes I'm requesting:

• Dividing the main security room into two so that prisoners who escape their cell have less room to run around in and have to get past two sets of doors to escape
• Somehow connecting the bar to maint; it's a popular hangout spot so making it easier to enter and exit would be good
• Expanding hydroponics by one or two tiles width-wise; you can have up to four botanists working there, so I think it makes sense if you expand it and reduce the ranch (typically one or two people)

**Comment by ZeWaka** [comment]
> • Somehow connecting the bar to maint; it's a popular hangout spot so making it easier to enter and exit would be good

idea: have a 'performer's door' that connects to the top of the stage, could remove the right stair as well. bathroom could be cut shorter for hall

**Comment by nefarious6th** [comment]
> • Dividing the main security room
> • Somehow connecting the bar to maint
> • Expanding hydroponics by one or two tiles

Done, done and done!

For the maint/bar stuff, I ended up connecting the stage to maint and the bathroom and moved all the clothing stuff there nd made it the "locker room" so it could be like a dressing room for the performers before they go on stage.
For hydro, I just made the map bigger overall to add the space; I got to do some other fine-tuning things because of this like adding a player piano in the chapel and an actual separated store room for plasma in gas storage.

Powernet overlay, pipe overlay, and atmos overlays look okay in-game. 

I'm done on this one unless there's other changes requested.

**Review by ZeWaka — APPROVED** [review]

**Review by flrsh — APPROVED** [review]

**Pull request merged**
