### PR TITLE
Adds a define to disable set_area

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[QOL]
## About the PR 
Extremely stupid and boneheaded solution to the "set_area is undefined" local server error, just removes all references to set_area. Obviously breaks the pregame HTML but you probably don't care about that if you're just local testing.

## Why's this needed? 
I HATE SET_AREA
I HATE SET_AREA
I HATE SET_AREA

### CODE REVIEW

**Review by pali6 — COMMENTED** [review]
Why not just make the FUCKING_HURRY define do this?

**Comment by TobleroneSwordfish** [comment]
> Why not just make the FUCKING_HURRY define do this?

Because I still want to be able to pick a specific role for testing and not get set_area locked. (unless I'm missing a way to do that with the FUCKING_HURRY define enabled?)

**Comment by pali6** [comment]
Can you check if https://github.com/goonstation/goonstation/commit/ae68814079ec184b36072ff8d710e701895a0069 possibly fixed the issue?

**Comment by TobleroneSwordfish** [comment]
> Can you check if [ae68814](https://github.com/goonstation/goonstation/commit/ae68814079ec184b36072ff8d710e701895a0069) possibly fixed the issue?

It seems to have! You have saved me an average of two or three restarts per build, thaaanks!

**Pull request closed without merging**
