### PR TITLE
Adds Headset Radio Icons For The Comms Officer And The Radio Show Host

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[QoL]

Forum Thread: https://forum.ss13.co/showthread.php?tid=17775

## About the PR:
Replaces the radio icon for the Radio Show Host's Headset, and adds a Communications Officer's Headset, complete with a unique icon. I've also capitalised "Radio show host's Headset" to "Radio Show Host's Headset".
co
rh

## Why's this needed?
The Radio Show Host having both access to all channels, and a civilian radio icon can be confusing at times, often prompting fears of a wiretap, especially when they chat to Security. On Manta, the Comms Officer being provided with a Captain's Headset can cause the crew to confuse them with the Captain, the Comms Officer often needing to clarify who they are.

## Changelog:
```changelog
(u)Mr. Moriarty
(+)The Radio Show Host and the Communications Officer now have unique radio icons.
```

### CODE REVIEW

**Comment by Zonespace27** [comment]
since IconDiffBot doesn't help here, mind providing screenshots?

**Comment by Mister-Moriarty** [comment]
> since IconDiffBot doesn't help here, mind providing screenshots?

I was just doing that now. I had made other icons, but on DimWhat's advice, these are the ones I have decided to PR.

**Comment by ZeWaka** [comment]
when I see CO i think commanding officer, which is confusing

**Comment by ZeWaka** [comment]
i also liked the record disc icon more than RH

**Comment by Mister-Moriarty** [comment]
I'll make a forum thread for it for it then, asking opinions and suggestions on icons.

**Comment by Mister-Moriarty** [comment]
An update as of 15/01/2022,
I've changed the icons to the vinyl record ones, as from the few people who have voiced an opinion, Discord, here, or the forums, the records seem to be the more popular.
Feel free to shout at me to change them back though, I can't make everyone happy.

**Review by virvatuli-gh — APPROVED** [review]

**Pull request merged**
