### PR TITLE
Increases freeze cooling amount

### PR DESCRIPTION
**Pull request by ThatFiveGuys**
## About the PR 
Freeze now cools you down 20k per lifeloop instead of 10k. 

## Why's this needed? 
This allows you to stack freeze with cryoxadone which I think is a very funny strategy to enable as its putting yourself at a decent chance of getting gibbed.

## Changelog

```changelog
(u)Ikea
(+)Freeze now cools you down 20 k per lifeloop
```

### CODE REVIEW

**Comment by ZWRh3** [comment]
iirc this means nothing in practice as the ethanol it decays into is at room temp regardless of its own temp

**Comment by ThatFiveGuys** [comment]
> iirc

This effects body temperature directly, should still work.

**Comment by Tarmunora** [comment]
make it 20K, just to be safe 🤌

**Comment by ThatFiveGuys** [comment]
> make it 20K, just to be safe 🤌

Done!

**Pull request merged**
