### PR TITLE
Moves pinpointers into own dmi, optimises sprites

### PR DESCRIPTION
**Pull request by BatElite**
[cleanliness]
## About the PR 
-Pinpointers and related item using the same style of icon (bloodtrak and id trackers) had their own sprites for the various arrows and stuff they display, even if the arrows themselves look identical between them.
-Most of the pinpointers were in device.dmi, except for the bloodtrak which had its own file.

This PR moves all the sprites to the new pinpointers.dmi (deleting bloodtrak.dmi in the process) and makes the arrow graphics into their separate icons, then applies them as an overlay. This reduces the amount of pinpointer frames from 53 per type to 1 per type + 52 common ones.

Nothing should change for players unless I messed up somewhere.

## Why's this needed? 
Organises graphics a little and shrinks total filesize a little. Also moves some crap out of device.dmi which is probably nice.

### CODE REVIEW

**Comment by Azrun** [comment]
~Fuuuuu my PR!~

Great cleanup.

**Comment by BatElite** [comment]
Were you planning on doing this too or is this going to conflict with something you're doing?

**Review by ZeWaka — APPROVED** [review]
super gross that all this functionality is duplicated 3 times

out of scope

**Comment by Azrun** [comment]
> Were you planning on doing this too or is this going to conflict with something you're doing?

Conflicts, but this is better in the long run. 👍

**Comment by BatElite** [comment]
Can look into refactoring them at some point, but I'll wait until Azrun's thing is through first.

**Comment by BatElite** [comment]
Should be up to date again, just waiting for the checks & label to clear.

**Pull request merged**
