### PR TITLE
Brain Spooning

### PR DESCRIPTION
**Pull request by Recusor**
Added two new snack items with identical stats. Added two new animated icons. Made slight changes to existing code in surgery_procs and added a significant amount of new code to spoon brains out.

## About the PR 
This is implemented the following way

Proceed with normal head surgery as if to remove brain.
Once skull is sawed open, if you use the spoon on harm intent you will get a new snack item in your hand and deal 20 brain damage to your patient.
New snack has a different icon if enucleation spoon or kitchen spoon is used. New snack item has 2 units of prions in it.
Brain spooning cannot occur if subject is dead.
Brain spooning does not destroy the brain itself, so people can still be borged or cloned.
When consumed or fed to someone else the snack item changes back to the type of spoon that was used.

In its current implementation in order to do eye surgery now you must be on the HELP intent. 

## Why's this needed?

I was inspired by Gore's whack ideas thread on the forums, and by the movie Hannibal. Brain damage is something that is tangential at the moment. This is a direct way to inflict a significant amount of brain damage in a way that makes sense. I envision an antagonist round on Donut3 where the traitor Medical Director captures people, spoons out enough of their brain that they cant open doors or use computers and plops them in the asylum, or other variations on this. Alternatively this invasive procedure could be used instead of the death penalty for some traitors (situational of course.)

By not destroying the brain it does not hamper the ability to clone or borg. The small amount of prions included in the snack (2u) seems balanced to me, and you lose the tool you were using if you use an extractor on it, also providing some level of balance.

This is my first ever submission on github, let alone for goonstation. Looking forward to all types of feedback!

Big thanks to the folks on discord in imcoder, especially pali, mordent, Emily, yass, Adhara, ZeWaka, Lux, DimWhat and moonlol.

Brainspoon
BrainEspoon

EDIT/UPDATE - Updated with the following things - Made it so that spooning out brains permanently reduces brain health. Also made it so that you can take a spoonful of brain and ADD it to an opened skull. Use the snack object (spoonful of brain) on a target that has their skull cut open. This adds to their maximum brainhealth, or fixes a previously scooped out brain. These changes are reflected in the meathead perk too. Shalhavet taught me alot and basically updated this all on their own! big, big thank you!

Please discuss thoughts on the brain addition feature. This could make it so that you can survive without O2 longer, among other things.

[input wanted]
[feature]

### CODE REVIEW

**Comment by Kyle2143** [comment]
I'm not sure, but doesn't this mean that it would be trivially easy to get a large amount of prions?

**Comment by Azrun** [comment]
nitpick - Descriptions missing punctuation. 

Means of keeping harvest-able prions well below 10 (burger amount) and/or a cooldown seems desirable.  There is something terrifying about having a bunch of ~staff assistants~ mindslaves you are are occasionally harvesting gray matter from. 👍

**Comment by Recusor** [comment]
> I'm not sure, but doesn't this mean that it would be trivially easy to get a large amount of prions?
> 
> Also, I wouldn't really say that it would be a good punishment for people since brain damage is very easily able to be healed with the rather abundant mannitol.

Potentially, but you can already get prions pretty easily with monkey brains. This is if anything a generally less efficient way to obtain them. Regarding healing it, yes, holy water and mannitol would do the job, but it would take a significant amount of mannitol I beleive.

In fact I have noticed another issue and not sure if i need to make a whole new PR. For the check on life I need to use (isalive(patient)) instead.

**Comment by Recusor** [comment]
Considering that the brain is not destroyed and how strong prions are, I am perfectly open to removing them from the snack item as well.

**Comment by Superlagg** [comment]
> Considering that the brain is not destroyed and how strong prions are, I am perfectly open to removing them from the snack item as well.

Could also be handled by having this permanently reduce their brain health afterwards. Maybe fixed through severe synaptizine OD or something.

**Comment by Recusor** [comment]
> > Considering that the brain is not destroyed and how strong prions are, I am perfectly open to removing them from the snack item as well.
> 
> Could also be handled by having this permanently reduce their brain health afterwards. Maybe fixed through severe synaptizine OD or something.

im looking into this now good idea!

**Comment by Emcee-Gore** [comment]
Hey - this looks fancy!

My take on the balance; man you could get easily an uncanny amount of prions from them monkey brains you can harvest from monkeys from monkey vending machines.

I guess to extract the 2u prions from the spoon one would need to extract it? Or can it be clicked on a beaker to then empty the spoon and transfer the 2u of prions directly?

In case the spoon gets destroyed by the reagent extraction process one would need 1 new spoon for every 2u of prions. You'd run out of spoons before you would run out of monkeys or kidnapped greytiders.

Sweet that you took a look at my idea thread. Nice work mate! :)

**Comment by Recusor** [comment]
> I guess to extract the 2u prions from the spoon one would need to extract it? Or can it be clicked on a beaker to then empty the spoon and transfer the 2u of prions directly?
> 
> In case the spoon gets destroyed by the reagent extraction process one would need 1 new spoon for every 2u of prions. You'd run out of spoons before you would run out of monkeys or kidnapped greytiders. So I do not see a balance problem in that regard.

Interesting point, you are right. An extractor would be needed to get them in a beaker and you would lose the spoon in order to access the prions without straight ingesting. It could be pointed out that  you could have like 6 spoon full at the same time and then quickly fed them to someone to give them kuru or yourself as an option as well in order to keep the spoons. Also enucleation spoons can be made from medical and robotics fabricators for cheap.

**Comment by Recusor** [comment]
Updated with the following. Big thanks to Shalhavet enitrely for these updated changes.

snacks.dm updated with a special use of Eat for the brainspoon snacks. If the snack item is used on someone with the harm intent the brain will be schlorped IN to the target. Either yourself or someone else. At the moment this does not check to see if any surgery states are active, so you can schlorp brain into anyone with or without surgery.

Additionally updated with a new variable, in brain.dm called amount_spooned_out that is tracked to determine the maximum brain HP available. If you have your brain scooped out 3 times, you wont be able to heal about 60 brain HP (the minimum amount needed for severe brain damage)

Changed damage.dm to look at brain.MAX_DAMAGE instead of just setting max brain health as 120.

Also changes Meathead in traits.dm to have them be affected by amount_spooned_out and and unable to raise brain hp above a certain amount

**Comment by Recusor** [comment]
Updated so that you can only schlorp a spoonful of brain into a skull that has already been cut open. Shalhavet is genius

**Comment by Recusor** [comment]
Um im not sure if i meant to click ask for review or not? Apologies if I shouldnt have done that!

**Review by pali6 — CHANGES_REQUESTED** [review]
There are concerns in the forum thread about the body horror aspect being a bit excessive. Will you attempt to address that / do you think it's possible to address the concerns while keeping the main point of the PR?

**Comment by Recusor** [comment]
Im looking for additional feedback on the form as the body horror aspect to see if transferring from one skull to another is acceptable or if the whole act of spooning is over the top.

**Comment by Recusor** [comment]
Ar this point I am going to close this request for now but thanks for all the feedback ! Looking forward to contributing in the future.

**Pull request closed without merging**
