### PR TITLE
Restricts Manta to RP_MODE servers

### PR DESCRIPTION
**Pull request by Zonespace27**
[Removal] [Input Wanted]
## About the PR 
This PR removes Manta from rotation on goon1/2.

## Why's this needed? 
Manta is plagued with issues that don't make it a great map for classic-tier antagging and crew action for a variety of reasons:

- Reinforced walls and electrified windows everywhere
- Maint tunnels are tiny and linear, defeating their main purpose (hiding crime)
- The camera network is massive, allowing the AI and camera consoles to see pretty much anywhere.
- The Armory and AI core are possibly over-defended, as they're both next to each other, and dead-center of the station.
- The movement of the Manta does nothing but hinder crew who fall off and the Nukeops (whose jetpacks don't block movement)
- The shields are... kinda pointless? They're just really annoying.
- The singularity is extremely close to escape.

In addition, I have heard many complaints from classic players about manta in general, which encouraged me to make this PR.

## Why should it stay on RP_MODE servers?
In addition to people (generally) seeming to like it on RP:
- It has a very cool theming that lends itself to RP well
- Some departmental areas (RD's office, bridge, security are a few) are very well built and look good for RP.
- It has a few gimmicks (Unique alarm message, movement) that can work well on RP

## Changelog

```changelog
(u)Zonespace
(*)Manta is now restricted to goon3/goon4.
```

### CODE REVIEW

**Comment by ThatFiveGuys** [comment]
Minor correction "Reinforced walls and electrified windows everywhere (this one has been partially rectified)", that pr got closed

**Comment by Zonespace27** [comment]
> Minor correction "Reinforced walls and electrified windows everywhere (this one has been partially rectified)", that pr got closed so that is false

Corrected

**Comment by Yellow-Mushroom** [comment]
I can’t input on main but it is still off a lot on RP too. Manta is a very tight map, 2 wide hallways in a lot of locations. 

I still think a lot of the critiques that you gave for main apply to RP also, as antags have an extremely huge uphill battle. 

3 security officers can clear the entirety of manta maints in 30 seconds max

this limits RP crime to two areas, the civilian section (just because it’s a weaker part of the map and forgotten about) and off-station (which is made significantly more difficult due to manta’s movement)

While this PR only focuses on its removal from main, I do think it’s removal from RP should be considered (atleast for >45 pop)

Security officers on RP have to give antags leeway, but when antags are walked into on a 10 minute basis because there is nowhere to crime, it is significantly more difficult to RP much of anything as compared to other maps

**Comment by wolfolotl** [comment]
I don't know if we want it either

**Comment by Zonespace27** [comment]
Pali sniped me >:(

8ea4eb0

**Pull request closed without merging**
