### PR TITLE
Flaborized sprites - tanks, engines, fire extinguisher

### PR DESCRIPTION
**Pull request by Sovexe**
## About the PR 
Adds new sprites

notably this does NOT include a VR extinguisher or pod engine 4

## Why's this needed? 
new sprites look better
image
image
image

## Changelog

```
(u)Flaborized:
(+)New sprites for tanks, extinguishers, and pod engines.
```

### CODE REVIEW

**Comment by Flaborized** [comment]
Hey, I don't think the icon state for **engine** is actually used for anything? Just engine-1 to engine-4. Thus the red smallest engine could probably be used for engine-4, since that one can't make pod portals to my knowledge and is therefore the Least Advanced Of Them All. lmk if that's wrong however and I'll makes another engine for it

**Comment by Sovexe** [comment]
> Hey, I don't think the icon state for **engine** is actually used for anything? Just engine-1 to engine-4. Thus the red smallest engine could probably be used for engine-4, since that one can't make pod portals to my knowledge and is therefore the Least Advanced Of Them All. lmk if that's wrong however and I'll makes another engine for it

corrected

**Comment by ZeWaka** [comment]
same w/ other PR: don't really think storing old versions of these is necessary

**Comment by Sovexe** [comment]
old sprites removed

**Pull request merged**
