### PR TITLE
Remove the Loafer

### PR DESCRIPTION
**Pull request by stonepillars**
[QoL]

## About the PR 

Removes the loafer. Keeps the loaves.
Loafer type now spawns a replacement pipe segment and deletes itself in case there
are loafers in the secret module somewhere

## Why's this needed? 

Loafer is a terrible (#958) stupid (#6970) dumb pipe that does nothing but cause lag and encourage
spessmen to (#6898) lag the (#7024) shit out of the server. It got me banned and now I'm seeking
vengance.

## Out of Context Testimonials

image
image
image

## Changelog

```changelog
(u)Stonepillar
(*)Removed the loafer.
```

### CODE REVIEW

**Comment by AmazingDragon353** [comment]
Linking only closed issues for something really isn't a good argument for getting rid of it, especially when the cause of the vast majority of lag problems came from nuggeting, which was already removed. 

If you got banned for using the loafer, maybe consider that it was your actions, not the loafer itself. I personally have never been banned for using the loafer, and I know many other people that are able to use it without issue. "It's a poor worksman who blames their tools" and all that. Also, not making a feedback thread on an extremely controversial change (especially when there are people who are actively working on improving loafsci, which this change would drastically affect) is pretty shitty. Reflect on your actions instead of trying to deflect the blame by pushing to remove something fun from the game.

**Comment by SirSnek** [comment]
Hey dragon do you know what day it is?

**Comment by Laboredih123** [comment]
April 2nd of course

**Comment by TTerc** [comment]
I like bread :(

**Pull request closed without merging**
