### PR TITLE
Add TGUI UI for the mechanical dropper

### PR DESCRIPTION
**Pull request by blackrep**
[TGUI][QoL]
## About the PR 
This PR converts the old mechanical dropper's UI to TGUI and polishes it up a bit. It adds a few new features:
1. The ability to see the current volume of reagent in the dropper
2. The ability to quickly type out the exact amount to draw / drop
3. The ability to quickly set min / max

Still todo:
- [x] Setting the min to 0.1 instead of 0 causes the Slider to step by 0.1 -> 1.1 -> 2.1 -> ... -> 10.0, see if it's possible to make this 0.1 -> 1.0 -> 2.0 -> ... -> 10.0
- [x] Find a way to color the Slider based on Reagent color. Currently it looks like it only takes a set of colors from colors.scss instead of arbitrary RGB values.

In this PR, I've removed the buttons that increments by 0.1 decimals, however have added the Slider component that can be slid for 1 unit increments & typed into to specify 0.1 increments.

## Why's this needed? 
The old UI is jank:
image

TGUI looks much prettier:
Untitled
image

## Changelog

```changelog
(u)Blackrep
(+) The mechanical dropper has been updated to a fancy new UI!
```

### CODE REVIEW

**Comment by blackrep** [comment]
Have some outstanding things I want to try fixing before being ready to merge. But if anyone knows the best way to resolve these issues, would love to get feedback early.

**Comment by ZeWaka** [comment]
!merge_upstream

**Comment by ZeWaka** [comment]
I haven't had the issue with the slider increments. It always resets to whole numbers for me.

**Review by ZeWaka — APPROVED** [review]

**Comment by mordent-goonstation** [comment]
To clarify above discussion: we're saying it (with the PR as-is) is not possible to set e.g. 0.5u or whatever, only 0.1, 1, 2, 3, and integers thereafter?

If so, I feel like this is kind of missing the point of the mechanical dropper.

**Comment by ZeWaka** [comment]
> To clarify above discussion: we're saying it (with the PR as-is) is not possible to set e.g. 0.5u or whatever, only 0.1, 1, 2, 3, and integers thereafter?

No @mordent-goonstation.  You can click sliders to set exact values.

**Pull request merged**
