### PR TITLE
Wearable Roses & Poppies

### PR DESCRIPTION
**Pull request by Munien7**
[HYDROPONICS] [CLOTHING] [SPRITES]
## About the PR 

Allows Roses, HoloRoses, and Poppies to be worn in the hair similar to the other wearable flowers we have currently. All other rose and poppy functionality stays the same.

image
image
Sprites by TemThrush

## Why's this needed? 

More pretty flowers in the hair, they look nice.

## Changelog 

```changelog
(u)Munien & TemThrush
(+)Made Roses and Poppies wearable in your hair.
```

### CODE REVIEW

**Review by ZeWaka — COMMENTED** [review]
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by Azrun** [comment]
This currently appears to impact `spacelight-e` ☹️

**Review by TheTyrant25 — COMMENTED** [review]
Looks good and it looks like it will work. One thing I must note though is that this will remove poppies from the "herb" ancestry meaning it won't be able to be made into blunts and things any more.

**Comment by Azrun** [comment]
> Looks good and it looks like it will work. One thing I must note though is that this will remove poppies from the "herb" ancestry meaning it won't be able to be made into blunts and things any more.

>All other rose and poppy functionality stays the same.

Please address this, otherwise the description is inaccurate.

**Comment by TheTyrant25** [comment]
closed on muniens request (he was far from puter)

**Comment by Munien7** [comment]
Closed as I don't really have the time to fix the dmi and sort out a solution for the poppy herb thing (I literally forgot they could be made into joints as I've never seen anyone do it ever lol) for the time being. I might revisit this another time or if anyone wants to pick it up that's fine.

**Pull request closed without merging**
