### PR TITLE
DMM Suite reader now supports TGM files

### LINKED ISSUE #1740: [$5 Bounty] Fix our DMM loader (DMM Suite) to work with the TGM format
**Describe the bug**
Our DMM tool cannot load/read TGM-format .dmm files.

**Bounty**
Bounty for this issue is **$5 USD**, let me (ZeWaka#3196 on Discord or @ZeWaka) know how you want to get paid if you fix this bug.

**To Reproduce**
If you attempt loading a TGM-format .dmm, the loader crashes and breaks.

**Expected behavior**
TGM-format .dmm files to load correctly.

**Additional context**
[TG's version of the suite](https://github.com/tgstation/tgstation/blob/master/code/modules/mapping/reader.dm) can load TGM files, but their version is not compatible with our license. Furthermore, their base suite version is more outdated than ours.

Our DMM suite is located at `code/z_dmm_suite`

[MAJOR]

### PR DESCRIPTION
**Pull request by pali6**
## About the PR 

Fixes #1740
The could be a lot better but to do that I'd probably have to start anew with the whole DMM Suite thing and that seems like *effort*. Let me know if there are some edge cases for which it's broken. Also note that this PR does not change prefab format to TGM.

Oh and also I haven't used this thing so far but feel free to test it by sending the bounty there: https://ko-fi.com/pali6

## Why's this needed? 
Sticking to one map format is good.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Does this still work with the normal DMM format?

**Comment by pali6** [comment]
Yep.

**Comment by pali6** [comment]
But also wait a moment because with very large maps there seems to be an issue.

**Comment by ZeWaka** [comment]
sicknasty bromato

**Comment by ZeWaka** [comment]
Bounty paid ✅ 

image

**Pull request merged**
