### PR TITLE
Resprite for fish found in food_fish.dmi!

### PR DESCRIPTION
**Pull request by ThyOverlord**
## About the PR 
 This PR resprites the fish given in the Food_fish.dmi, this includes 6 fish used in cooking and fishing! Also removes the dusty old sprites that were extremely outdated and blurry!
 
image
image

The second image posted are horizontal variants made preemptively in case they are ever needed! (They are not in the dmi but they are here to make their existence known!)

## Why's this needed? 
The current fish sprites are very bland and undescriptive. the new sprites proposed are much more recognizable and visually enjoyable! 

## Changelog

```changelog
(u)ThyOverlord
(+) Resprited the fish you see around the station.
```

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
Great sprites codedude

**Comment by ThyOverlord** [comment]
> Great sprites CodeDude
i am screaming

**Comment by ZeWaka** [comment]
definitely way too verbose of a changelog, i've trimmed it

**Review by ZeWaka — CHANGES_REQUESTED** [review]
you changed the name of the mahi mahi in the dmi without updating the code

**Comment by ThyOverlord** [comment]
> you changed the name of the mahi mahi in the dmi without updating the code

The change I made yesterday fixed this issue, previously I had the iconstate incorrectly as "mahi_mahi" When in the code its "mahimahi"
With the changes I made yesterday, there... shouldn't be this issue anymore unless the pr didn't update?

**Comment by Adharainspace** [comment]
these look good to me

**Pull request merged**
