### PR TITLE
Stirstir has a 10% chance to spawn with a lollipop

### PR DESCRIPTION
**Pull request by TealSeer**
[FEATURE] [GAME OBJECTS]
## About the PR 

Monsieur Stirstir has a 10% chance to spawn holding a lollipop in his right hand.

## Why's this needed? 

Nobody even likes him and all he has to eat in there is floor pills and old cigarette butts and nobody cares so maybe he can just have a lollipop sometimes

### CODE REVIEW

**Comment by TealSeer** [comment]
> why not a banana?

his AI would be too stupid to peel it and eating unpeeled banana gives 5 toxin damage which would mean invisible failure state for the monkey duty medal right off the bat also look at this 
image-4

**Comment by TealSeer** [comment]
honestly the big swirly lollipop is kind of the glue holding this whole idea together for me i want him to be a silly little boy and I couldn't give him a propeller cap cause the prisoner beret is a traitor item so this is the next best thing

**Comment by MeggalBozale** [comment]
Let him eat lollipops

**Review by 444Portal — APPROVED** [review]

**Review by AXLFAN2000 — APPROVED** [review]

**Comment by AXLFAN2000** [comment]
Let the lad have a treat he's been through enough

**Pull request merged**
