### PR TITLE
Adds coffee creamer (+ Generic coffee maker variant)

### PR DESCRIPTION
**Pull request by DisturbHerb**
## About the PR 
This PR adds coffee creamer bottles, which carry 50u milk. These have been placed next the coffeemakers on Cogmap1, Cogmap2, Oshan, Destiny, Clarion, Horizon, and Kondaru. Additionally, all coffeemakers which are in Engineering have been replaced by a subtype that is practically identical to what we had before. A generic coffeemaker and carafe type replaces the parents with a new set of sprites.

image
image

The sprite for the coffee creamer has been changed, per the requested changes below.

## Why's this needed? 
i don't like my coffee black

### CODE REVIEW

**Comment by t-toasted** [comment]
On Cog1, feel free to remove/move the candy the candy if it would look better to place the coffee creamer there. I was just filling space with the candy so I’m not overtly attached to it

**Comment by WALPVRGIS** [comment]
If you make these changes to the creamer bottle lid/top, I'd be happy to approve it sprite-wise! 👍 

image

**Review by WALPVRGIS — CHANGES_REQUESTED** [review]
See above comment, I am silly and forgot i could just req changes here!! oop

**Review by WALPVRGIS — APPROVED** [review]
Approved art-wise! Gotta test the mapping stuff but looks good to me 👍

**Comment by WALPVRGIS** [comment]
!merge_upstream

**Comment by flrsh** [comment]
Generic coffee maker image

**Pull request merged**
