### PR TITLE
Clarion patho removal

### PR DESCRIPTION
**Pull request by nefarious6th**
[rework][removal]
## About the PR 
Removes pathology from clarion, moves around a bunch of stuff in medbay, adds a psychologist's office
clarionmedbay
clarionmedbayareas

## Why's this needed? 
noooooo moooooore pathoooooo
open concept clarion medbay

### CODE REVIEW

**Comment by nefarious6th** [comment]
missing light switches in medbay and robo
missing blind switch in robo

**Comment by nefarious6th** [comment]
missing tele beacon

**Comment by BatElite** [comment]
Looking at the map diff bot you've got corruption appearing over the station + a touch on the listening post

I don't really see why removing patho would require moving around all of medbay, but if you're doing that then IMO the morgue would sooner in maint than the main area

**Comment by nefarious6th** [comment]
> Looking at the map diff bot you've got corruption appearing over the station + a touch on the listening post
> 
> I don't really see why removing patho would require moving around all of medbay, but if you're doing that then IMO the morgue would sooner in maint than the main area
ty for pointing out the corruption, missed that totally

removing patho opened up a lot of space and i've been meaning to look over clarion's medbay for a while. for the morgue, i placed it there since when i last talked to the original creator of the map, she had drafted up a movement of the md office and morgue similar to this; though i recognize what you're saying and that my reasoning for doing it doesnt necessarily mean it's the best spot for it.

**Review by Sord213 — CHANGES_REQUESTED** [review]
Hm. I think I'd rather see the morgue on the left wing. A little spookier having to drag the corpses through maint. Either swap that out with the psychiatrist's office or the storage room. 

Could you expand robotics a little bit upwards? One or two tiles would be fine. These changes shrink robotics pretty drastically. I'd also like to see a door from robotics into the nearby maint on the left. The layout is a little strange as well. Maybe move the operating area to the top where the AI shells are, and the fabricators to the left wall or something. Has a strange flow as is.

Screenshot_134
Another thing that I'm thinking of looking at the map is it'd be nice for the two sections of maint to connect. Bumping robotics up a bit shouldn't be too bad as there's a lot of empty space in medbay above it.

Screenshot_133
This sitting/waiting room seems kinda like a waste of space. Maybe turn it into a 5x3 randoom room or two. Would be nice for Clarion to get _some_ random rooms.

There's a disposal pipe with no chute above it right next to the pharmacy entrance. The lower area with the fabricator and nanomed could probably use a chute as well.

The door control buttons in the MDir's office are on the same tile as the personal computer? Seems really weird, someone could be on the other side of the table and press them.

**Comment by nefarious6th** [comment]
appreciate feedback; going to go ahead and close this as other people try reworks of the map, carte blanche, which I believe is probably a more fruitful approach. if that doesnt pan out, anyone is welcome to return to and adopt this

**Pull request closed without merging**
