### PR TITLE
Allow personal portables in backpacks

### PR DESCRIPTION
**Pull request by penny64**
8

[QOL]
## About the PR 

This allows the smaller, rarer, fancier portable laptops to fit into backpacks

image

## Why's this needed? 

Players naturally think the smaller laptops would fit in their backpack and it makes sense mechanically, and thanks to their rarity/cost this maintains a sense of balance like one that's already in place while actually making them desirable.
I personally think both should fit but not trying to rock the boat.
## Changelog

```
```

### CODE REVIEW

**Comment by witheld9** [comment]
I'm pretty sure the failed tests here aren't my doing

**Comment by Azrun** [comment]
This ends up being a straight upgrade of `luggable_computer`.  Being able to put it in your backpack seems like a **huge** buff, but I'm not really familiar with the breadth of the power of packet-fu.  Items taking up a hand-slot is a pretty big cost in having to do inventory management.

Seems like `setup_charge_maximum` and/or `setup_drive_size` should be costed accordingly.  Some maps just have a `/obj/item/luggable_computer/personal` laying around and Psychiatrists spawn with them.

**Comment by penny64** [comment]
> This ends up being a straight upgrade of `luggable_computer`. Being able to put it in your backpack seems like a **huge** buff, but I'm not really familiar with the breadth of the power of packet-fu. Items taking up a hand-slot is a pretty big cost in having to do inventory management.


It's meant to be an upgrade just like it appears and I think that the relative rarity is still in line with that, I did consider both the few maps with them placed and the psychiatrist.
As for packet evil, generally laptops aren't that more useful than just using your PDA or Mechcomp- they can be deployed onto data terminals but so can your mechcomp cabinet, which can be deconstructed and placed in your backpack and has superior spoofing abilities. 
The radio range isn't special.
The main use for them is logging into DWAINE and not having them your backpack doesn't really affect how you're going to use this functionality- if you don't have a laptop you just log into the closest PC.

**Comment by geneva-breaker** [comment]
I just tested this and it doesnt seem to break anything important, so sure why not. 
however I don't think it needs a changelog

**Comment by penny64** [comment]
Sure removed

**Pull request merged**
